// SPDX-FileCopyrightText: Copyright (c) 2020-2026 The Lethe Authors
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR LGPL-2.1-or-later

#include <core/boundary_conditions.h>
#include <core/fichera_oven_grid.h>
#include <core/grid_birmingham_fluidized_bed.h>
#include <core/grid_cylinder.h>
#include <core/grid_impinging_jet_mixer.h>
#include <core/grid_periodic_hills.h>
#include <core/grid_uniform_channel_with_meshed_cylinder.h>
#include <core/grid_uniform_channel_with_meshed_square_prism.h>
#include <core/grids.h>

#include <deal.II/base/conditional_ostream.h>
#include <deal.II/base/mpi.h>
#include <deal.II/base/types.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/tria.h>

#include <algorithm>
#include <fstream>
#include <iostream>
#include <numbers>
#include <string>


/**
 * @brief Warn when a mesh scaling factor is applied to a grid which carries curved manifolds
 *
 * Meshes generated by deal.II (type = dealii) or by Lethe's built-in generators
 * (type = lethe) may carry curved manifolds attached to the triangulation.
 * GridTools::scale moves the vertices but does not scale these attached
 * manifolds, so a scale factor other than 1 can leave the manifolds
 * inconsistent with the mesh and distort curved geometries under refinement.
 * The scaling is still applied, but the user is warned so that the resulting
 * mesh can be checked; such geometries can alternatively be dimensioned through
 * the grid arguments.
 *
 * Grids whose cells and faces all use the flat manifold, such as the
 * hyper_cube or hyper_rectangle grids commonly used to delimit a mesh
 * refinement box, are invariant under scaling and do not trigger the warning.
 * Neither do gmsh meshes, which carry no manifold.
 *
 * @param[in] mesh_parameters The mesh parameters used to generate the grid
 *
 * @param[in] triangulation The triangulation the grid was attached to. It must
 * already carry its manifold ids, hence the check is made after the grid
 * generation.
 */
template <int dim, int spacedim>
static void
warn_if_scaling_curved_manifolds(
  const Parameters::Mesh             &mesh_parameters,
  const Triangulation<dim, spacedim> &triangulation)
{
  if (mesh_parameters.scale == 1.0 ||
      mesh_parameters.type == Parameters::Mesh::Type::gmsh)
    return;

  const std::vector<types::manifold_id> &manifold_ids =
    triangulation.get_manifold_ids();
  const bool has_curved_manifold =
    std::any_of(manifold_ids.begin(),
                manifold_ids.end(),
                [](const types::manifold_id id) {
                  return id != numbers::flat_manifold_id;
                });
  if (!has_curved_manifold)
    return;

  // The triangulation of a refinement box is serial, and its communicator is
  // consequently MPI_COMM_SELF. MPI_COMM_WORLD is used instead to ensure that
  // the warning is printed by a single process in every case.
  const ConditionalOStream pcout(
    std::cout, Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 0);
  pcout
    << "WARNING: a mesh 'scale' factor of " << mesh_parameters.scale
    << " is being applied to a '"
    << (mesh_parameters.type == Parameters::Mesh::Type::dealii ? "dealii" :
                                                                 "lethe")
    << "' grid. \nScaling moves the mesh vertices but not the curved "
       "manifolds attached to the triangulation, which can distort the "
       "geometry under refinement. \nVerify the resulting mesh, or dimension "
       "the geometry through the grid arguments instead."
    << std::endl;
}

template <int dim, int spacedim>
void
attach_grid_to_triangulation(Triangulation<dim, spacedim> &triangulation,
                             const Parameters::Mesh       &mesh_parameters)

{
  // GMSH input
  if (mesh_parameters.type == Parameters::Mesh::Type::gmsh)
    {
      if (mesh_parameters.simplex)
        {
          auto        comm      = triangulation.get_mpi_communicator();
          std::string file_name = mesh_parameters.file_name;

          auto construction_data = TriangulationDescription::Utilities::
            create_description_from_triangulation_in_groups<dim, spacedim>(
              [file_name](dealii::Triangulation<dim, spacedim> &basetria) {
                GridIn<dim, spacedim> grid_in;
                grid_in.attach_triangulation(basetria);
                std::ifstream input_file(file_name);

                grid_in.read_msh(input_file);
              },
              [](dealii::Triangulation<dim, spacedim> &basetria,
                 const MPI_Comm                        comm,
                 const unsigned int /*group_size*/) {
#if defined(DEAL_II_WITH_METIS)
                GridTools::partition_triangulation(
                  Utilities::MPI::n_mpi_processes(comm),
                  basetria,
                  SparsityTools::Partitioner::metis);
#elif defined(DEAL_II_WITH_ZOLTAN)
                GridTools::partition_triangulation(
                  Utilities::MPI::n_mpi_processes(comm),
                  basetria,
                  SparsityTools::Partitioner::zoltan);
#else
                AssertThrow(
                  false,
                  ExcMessage(
                    "Parallel simulation with simplex meshes require that deal.II be compiled with either Metis or Zoltan"));
#endif
              },
              comm,
              Utilities::MPI::n_mpi_processes(comm) /* group size */,
              dealii::Triangulation<dim, spacedim>::none);

          triangulation.create_triangulation(construction_data);
          GridTools::scale(mesh_parameters.scale, triangulation);
        }
      else
        {
          GridIn<dim, spacedim> grid_in;
          grid_in.attach_triangulation(triangulation);
          std::ifstream input_file(mesh_parameters.file_name);
          grid_in.read_msh(input_file);
          GridTools::scale(mesh_parameters.scale, triangulation);
        }
    }
  // Dealii grids
  else if (mesh_parameters.type == Parameters::Mesh::Type::dealii)
    {
      if (mesh_parameters.simplex)
        {
          Triangulation<dim, spacedim> temporary_quad_triangulation;
          GridGenerator::generate_from_name_and_arguments(
            temporary_quad_triangulation,
            mesh_parameters.grid_type,
            mesh_parameters.grid_arguments);

          // Scale, rotate, and translate the mesh. The transformation is
          // applied to the quad/hex mesh, before it is refined and converted
          // to simplices, exactly as it is applied before the refinement of a
          // quad/hex mesh.
          apply_mesh_transformation(mesh_parameters,
                                    temporary_quad_triangulation);

          // initial refinement
          const unsigned int initial_refinement =
            mesh_parameters.initial_refinement;
          temporary_quad_triangulation.refine_global(initial_refinement);

          // flatten the triangulation
          Triangulation<dim, spacedim> flat_temp_quad_triangulation;
          GridGenerator::flatten_triangulation(temporary_quad_triangulation,
                                               flat_temp_quad_triangulation);

          Triangulation<dim, spacedim> temporary_tri_triangulation(
            Triangulation<dim, spacedim>::limit_level_difference_at_vertices);
          GridGenerator::convert_hypercube_to_simplex_mesh(
            flat_temp_quad_triangulation, temporary_tri_triangulation);

          GridTools::partition_triangulation_zorder(
            Utilities::MPI::n_mpi_processes(
              triangulation.get_mpi_communicator()),
            temporary_tri_triangulation);
          GridTools::partition_multigrid_levels(temporary_tri_triangulation);

          // extract relevant information from distributed triangulation
          auto construction_data = TriangulationDescription::Utilities::
            create_description_from_triangulation(
              temporary_tri_triangulation,
              triangulation.get_mpi_communicator(),
              TriangulationDescription::Settings::
                construct_multigrid_hierarchy);
          triangulation.create_triangulation(construction_data);
        }
      else
        {
          GridGenerator::generate_from_name_and_arguments(
            triangulation,
            mesh_parameters.grid_type,
            mesh_parameters.grid_arguments);

          // Scale, rotate, and translate mesh
          apply_mesh_transformation(mesh_parameters, triangulation);
        }

      // deal.II colorize some meshes material ID in a way that is not
      // compatible with the way we use material ID and boundary ID in Lethe
      // (e.g. GridGenerator ::subdivided_hyper_rectangle). Therefore, we reset
      // all material IDs to zero for dealii meshes.
      for (const auto &cell : triangulation.active_cell_iterators())
        cell->set_material_id(0);
    }

  else if (mesh_parameters.type == Parameters::Mesh::Type::lethe)
    {
      std::string grid_type = mesh_parameters.grid_type;

      // Customizable cylinder mesh
      if (grid_type.starts_with("cylinder_"))
        {
          AssertThrow(
            !mesh_parameters.simplex,
            ExcMessage(
              "Unsupported mesh type - custom cylinder mesh with simplex is not supported. Use a dealii cylinder to use simplex mesh."));

          GridCylinder<dim, spacedim> grid(grid_type,
                                           mesh_parameters.grid_arguments);
          grid.make_grid(triangulation);

          GridTools::scale(mesh_parameters.scale, triangulation);
        }
      // Periodic Hills grid
      else if (grid_type == "periodic_hills")
        {
          AssertThrow(
            !mesh_parameters.simplex,
            ExcMessage(
              "Unsupported mesh type - periodic hills mesh with simplex is not supported"));

          GridPeriodicHills<dim, spacedim> grid(mesh_parameters.grid_arguments);
          grid.make_grid(triangulation);

          GridTools::scale(mesh_parameters.scale, triangulation);
        }
      else if (grid_type == "fichera_oven")
        {
          AssertThrow(
            !mesh_parameters.simplex,
            ExcMessage(
              "Unsupported mesh type - Fichera oven mesh with simplex is not supported"));

          FicheraOvenGrid<dim, spacedim> grid(mesh_parameters.grid_arguments);
          grid.make_grid(triangulation);

          GridTools::scale(mesh_parameters.scale, triangulation);
        }
      else if (grid_type == "birmingham_fluidized_bed")
        {
          AssertThrow(
            !mesh_parameters.simplex,
            ExcMessage(
              "Unsupported mesh type - Birmingham fluidized bed mesh with simplex is not supported"));

          GridBirminghamFluidizedBed<dim, spacedim> grid(
            mesh_parameters.grid_arguments);
          grid.make_grid(triangulation);

          GridTools::scale(mesh_parameters.scale, triangulation);
        }
      else if (grid_type == "impinging_jet_mixer")
        {
          AssertThrow(
            !mesh_parameters.simplex,
            ExcMessage(
              "Unsupported mesh type - impinging jet mixer mesh with simplex is not supported"));

          GridImpingingJetMixer<dim, spacedim> grid(
            mesh_parameters.grid_arguments);
          grid.make_grid(triangulation);

          GridTools::scale(mesh_parameters.scale, triangulation);
        }
      else if (grid_type == "uniform_channel_with_meshed_cylinder")
        {
          AssertThrow(
            !mesh_parameters.simplex,
            ExcMessage(
              "Unsupported mesh type - uniform_channel_with_meshed_cylinder mesh with simplex is not supported"));

          GridUniformChannelWithMeshedCylinder<dim, spacedim> grid(
            mesh_parameters.grid_arguments);
          grid.make_grid(triangulation);

          GridTools::scale(mesh_parameters.scale, triangulation);
        }
      else if (grid_type == "uniform_channel_with_meshed_square_prism")
        {
          AssertThrow(
            !mesh_parameters.simplex,
            ExcMessage(
              "Unsupported mesh type - uniform_channel_with_meshed_square_prism mesh with simplex is not supported"));

          GridUniformChannelWithMeshedSquarePrism<dim, spacedim> grid(
            mesh_parameters.grid_arguments);
          grid.make_grid(triangulation);

          GridTools::scale(mesh_parameters.scale, triangulation);
        }

      else
        {
          AssertThrow(false,
                      ExcMessage(
                        "Unsupported mesh type - mesh will not be created"));
        }
    }

  warn_if_scaling_curved_manifolds(mesh_parameters, triangulation);
}



template <int dim, int spacedim>
void
setup_periodic_boundary_conditions(
  parallel::DistributedTriangulationBase<dim, spacedim> &triangulation,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information)

{
  AssertThrow(
    periodic_boundary_information.periodic_direction.size() ==
      periodic_boundary_information.periodic_neighbor_id.size(),
    ExcMessage(
      "There is a mismatch between the size of the periodic_direction and the periodic_neighbor_id maps"));

  // Setup periodic boundary conditions. Each periodic pair is stored once,
  // keyed by the principal boundary id of the pair.
  for (auto const &[id, neighbor_id] :
       periodic_boundary_information.periodic_neighbor_id)
    {
      auto triangulation_ptr = &triangulation;

      std::vector<GridTools::PeriodicFacePair<
        typename Triangulation<dim, spacedim>::cell_iterator>>
        periodicity_vector;
      GridTools::collect_periodic_faces(
        *dynamic_cast<Triangulation<dim, spacedim> *>(triangulation_ptr),
        id,
        neighbor_id,
        periodic_boundary_information.periodic_direction.at(id),
        periodicity_vector);
      triangulation.add_periodicity(periodicity_vector);
    }
}



/**
 * @brief Apply the initial refinement described by the mesh parameters
 *
 * This is the refinement carried out once, right after the grid has been
 * attached to the triangulation. Nothing is refined when restarting, since the
 * mesh stored in the checkpoint has already been refined.
 *
 * @param[in] mesh_parameters The mesh parameters used to decide how the
 * triangulation is refined
 *
 * @param[in] restart Flag indicating whether this is a restart
 *
 * @param[in,out] triangulation The triangulation which must be refined
 */
template <int dim, int spacedim>
static void
apply_initial_refinement(
  const Parameters::Mesh                                &mesh_parameters,
  const bool                                             restart,
  parallel::DistributedTriangulationBase<dim, spacedim> &triangulation)
{
  // Refinement of simplex meshes isn't possible yet. For dealii simplex meshes,
  // the initial refinement was already applied to the quad/hex mesh from which
  // the simplex mesh was generated, within attach_grid_to_triangulation.
  if (mesh_parameters.simplex)
    return;

  // On a restart, the triangulation is subsequently replaced by the one stored
  // in the checkpoint, which already carries its refinement.
  if (restart)
    return;

  if (mesh_parameters.refine_until_target_size)
    {
      const double minimal_cell_size =
        GridTools::minimal_cell_diameter(triangulation);
      const double       target_size = mesh_parameters.target_size;
      const unsigned int number_refinement =
        static_cast<unsigned int>(std::floor(
          std::log(minimal_cell_size / target_size) / std::numbers::ln2));
      triangulation.refine_global(number_refinement);
    }
  else
    {
      triangulation.refine_global(mesh_parameters.initial_refinement);
      refine_triangulation_at_boundaries(
        mesh_parameters.boundaries_to_refine,
        mesh_parameters.initial_refinement_at_boundaries,
        triangulation);
    }
}

template <int dim, int spacedim>
void
read_mesh_and_manifolds(
  parallel::DistributedTriangulationBase<dim, spacedim> &triangulation,
  const Parameters::Mesh                                &mesh_parameters,
  const Parameters::Manifolds                           &manifolds_parameters,
  const bool                                             restart,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information)
{
  attach_grid_to_triangulation(triangulation, mesh_parameters);

  setup_periodic_boundary_conditions(triangulation,
                                     periodic_boundary_information);

  // If the mesh is a GMSH mesh, we need to manually set the manifold id
  // of the face to be that of the boundary
  // ID, otherwise, we will be unable to use external manifold.
  // This is done manually by looping through all faces and giving them a
  // manifold id if there is a manifold associated with this number.
  if (mesh_parameters.type == Parameters::Mesh::Type::gmsh)
    {
      // Gather all the manifold ids within a set
      std::set<int> manifold_ids;
      for (unsigned int i = 0; i < manifolds_parameters.size; ++i)
        manifold_ids.insert(manifolds_parameters.id[i]);

      // Reset all the manifolds manually and force them to zero
      triangulation.reset_all_manifolds();

      // If the parameter file forces the occurrence of manifold,
      // loop over the faces of the triangulation. If the face of the
      // triangulation has a boundary id which corresponds to a manifold id
      // identified within the parameter file, then fix the manifold id of
      // this face manually to be that of the boundary id. In the past, this
      // was done by default for every face, but since 2023-12 this throws
      // (rightfully) an error in deal.II
      if (manifolds_parameters.size > 0)
        {
          for (const auto &face : triangulation.active_face_iterators())
            {
              if (face->at_boundary() &&
                  manifold_ids.contains(face->boundary_id()))
                face->set_all_manifold_ids(face->boundary_id());
            }
        }
    }

  // Finally attach the manifolds to the triangulation
  // Right now this should only occur for GMSH mesh, but the function is
  // generic enough.
  attach_manifolds_to_triangulation(triangulation, manifolds_parameters);

  apply_initial_refinement(mesh_parameters, restart, triangulation);
}

template <int dim, int spacedim>
void
read_mesh_and_manifolds_for_stator_and_rotor(
  parallel::DistributedTriangulationBase<dim, spacedim> &triangulation,
  const Parameters::Mesh                                &mesh_parameters,
  const Parameters::Manifolds                           &manifolds_parameters,
  const bool                                             restart,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information,
  const Parameters::Mortar<dim>                 &mortar_parameters)
{
  // If linear mortar manager, only two-dimensional cases are supported
  if (mortar_parameters.interface_type ==
      Parameters::Mortar<dim>::InterfaceType::linear)
    if constexpr (dim == 3)
      AssertThrow(
        false,
        ExcMessage(
          "The linear mortar interface type supports only two-dimensional cases at the moment."));

  // Check if stator and rotor meshes are of the same type
  AssertThrow(
    mesh_parameters.type == mortar_parameters.rotor_mesh->type,
    ExcMessage(
      "The mesh types for the rotor and stator geometries must be the same."));

  // Since the rotor and stator meshes are read separately, a dummy
  // triangulation is created for each part of the domain and then merged

  // Stator triangulation
  Triangulation<dim> stator_temp_tria;
  attach_grid_to_triangulation(stator_temp_tria, mesh_parameters);

  // Rotor triangulation
  Triangulation<dim> rotor_temp_tria;
  attach_grid_to_triangulation(rotor_temp_tria, *mortar_parameters.rotor_mesh);

  // Add a flag to cells on the rotor and stator triangulations; this will be
  // needed when attributing them an angular velocity. We use the material_id
  // flag because it won't be erased when the triangulations are merged.
  for (const auto &cell : rotor_temp_tria.active_cell_iterators())
    cell->set_material_id(1);

  for (const auto &cell : stator_temp_tria.active_cell_iterators())
    cell->set_material_id(0);

  if (mesh_parameters.type == Parameters::Mesh::Type::dealii)
    {
      // Get stator manifold ids without flat id
      unsigned int stator_ids_no_flat = 0;
      for (const auto &id : stator_temp_tria.get_manifold_ids())
        {
          if (id != numbers::flat_manifold_id)
            stator_ids_no_flat++;
        }

      // Get rotor manifold ids without flat id
      unsigned int rotor_ids_no_flat = 0;
      for (const auto &id : rotor_temp_tria.get_manifold_ids())
        {
          if (id != numbers::flat_manifold_id)
            rotor_ids_no_flat++;
        }

      // Shift rotor boundary IDs #
      unsigned int n_boundary_ids_stator =
        stator_temp_tria.get_boundary_ids().size();
      for (const auto &face : rotor_temp_tria.active_face_iterators())
        if (face->at_boundary())
          face->set_boundary_id(face->boundary_id() + n_boundary_ids_stator);

      // Keep track of modified IDs in faces and lines
      std::vector<bool> changed_manifold_ids_faces(
        rotor_temp_tria.n_active_faces(), false);
      std::vector<bool> changed_manifold_ids_lines(
        rotor_temp_tria.n_active_lines(), false);

      // Shift rotor manifold IDs #
      for (const auto &cell : rotor_temp_tria.active_cell_iterators())
        {
          if (cell->manifold_id() != numbers::flat_manifold_id)
            cell->set_manifold_id(cell->manifold_id() + stator_ids_no_flat);
          for (const auto &face : cell->face_iterators())
            {
              if (face->manifold_id() != numbers::flat_manifold_id &&
                  !changed_manifold_ids_faces[face->index()])
                {
                  face->set_manifold_id(face->manifold_id() +
                                        stator_ids_no_flat);
                  changed_manifold_ids_faces[face->index()] = true;
                }
              if constexpr (dim == 3)
                {
                  for (const auto line_index : cell->line_indices())
                    {
                      if (cell->line(line_index)->manifold_id() !=
                            numbers::flat_manifold_id &&
                          !changed_manifold_ids_lines[line_index])
                        cell->line(line_index)
                          ->set_manifold_id(
                            cell->line(line_index)->manifold_id() +
                            stator_ids_no_flat);
                      changed_manifold_ids_lines[line_index] = true;
                    }
                }
            }
        }

      // Store rotor manifolds in shifted IDs #
      for (unsigned int m = 0; m < rotor_temp_tria.get_manifold_ids().size();
           m++)
        {
          unsigned int temp = rotor_temp_tria.get_manifold_ids()[m];
          if (temp != numbers::flat_manifold_id)
            rotor_temp_tria.set_manifold(m + stator_ids_no_flat,
                                         rotor_temp_tria.get_manifold(m));
        }

      // Merge triangulations
      GridGenerator::merge_triangulations(
        stator_temp_tria, rotor_temp_tria, triangulation, 0.0, true, true);

      // Attach manifolds to merged triangulation
      unsigned int n = 0;
      for (unsigned int i = 0; i < stator_ids_no_flat; i++)
        {
          triangulation.set_manifold(n, stator_temp_tria.get_manifold(i));
          n++;
        }
      for (unsigned int j = stator_ids_no_flat;
           j < stator_ids_no_flat + rotor_ids_no_flat;
           j++)
        {
          triangulation.set_manifold(n, rotor_temp_tria.get_manifold(j));
          n++;
        }
    }
  else if (mesh_parameters.type == Parameters::Mesh::Type::gmsh)
    {
      // Merge triangulations
      GridGenerator::merge_triangulations(
        stator_temp_tria, rotor_temp_tria, triangulation, 0.0, true, true);

      // Gather all the manifold ids within a set
      std::set<int> manifold_ids;
      for (unsigned int i = 0; i < manifolds_parameters.size; ++i)
        manifold_ids.insert(manifolds_parameters.id[i]);

      // Reset all the manifolds manually and force them to zero
      triangulation.reset_all_manifolds();

      // Set manifolds
      if (manifolds_parameters.size > 0)
        {
          for (const auto &face : triangulation.active_face_iterators())
            {
              if (face->at_boundary() &&
                  manifold_ids.contains(face->boundary_id()))
                face->set_all_manifold_ids(face->boundary_id());
            }
        }

      // Attach manifolds to rotor-stator triangulation
      attach_manifolds_to_triangulation(triangulation, manifolds_parameters);
    }
  else
    throw std::runtime_error(
      "Unsupported mesh type - mesh will not be created");

  // Setup boundary conditions
  setup_periodic_boundary_conditions(triangulation,
                                     periodic_boundary_information);

  // Initial mesh refinement
  apply_initial_refinement(mesh_parameters, restart, triangulation);

  // Faces at rotor-stator interface
  unsigned int n_faces_rotor_interface  = 0;
  unsigned int n_faces_stator_interface = 0;

  // Check number of faces at the rotor-stator interface
  for (const auto &cell : triangulation.active_cell_iterators())
    if (cell->is_locally_owned())
      for (const auto face_no : cell->face_indices())
        if (cell->face(face_no)->at_boundary())
          {
            if (cell->face(face_no)->boundary_id() ==
                mortar_parameters.rotor_boundary_id)
              n_faces_rotor_interface++;
            if (cell->face(face_no)->boundary_id() ==
                mortar_parameters.stator_boundary_id)
              n_faces_stator_interface++;
          }

  // Total number of faces
  const unsigned int n_faces_rotor_interface_total =
    Utilities::MPI::sum(n_faces_rotor_interface,
                        triangulation.get_mpi_communicator());
  const unsigned int n_faces_stator_interface_total =
    Utilities::MPI::sum(n_faces_stator_interface,
                        triangulation.get_mpi_communicator());

  AssertThrow(
    n_faces_rotor_interface_total == n_faces_stator_interface_total,
    ExcMessage(
      "The number of faces at the rotor interface ID #" +
      std::to_string(mortar_parameters.rotor_boundary_id) + " (" +
      std::to_string(n_faces_rotor_interface_total) +
      ") is different from the number of faces at the stator interface ID #" +
      std::to_string(mortar_parameters.stator_boundary_id) + " (" +
      std::to_string(n_faces_stator_interface_total) + ")."));
}

template <int dim, int spacedim>
void
build_refinement_box_triangulation(
  const Parameters::Mesh       &box_mesh_parameters,
  Triangulation<dim, spacedim> &box_triangulation)
{
  attach_grid_to_triangulation(box_triangulation, box_mesh_parameters);

  // The initial refinement of a simplex dealii box mesh has already been
  // applied to the quad/hex mesh it was generated from, within
  // attach_grid_to_triangulation. Applying it again here would refine the box
  // twice.
  if (!box_mesh_parameters.simplex)
    box_triangulation.refine_global(box_mesh_parameters.initial_refinement);
}

template <int dim, int spacedim>
void
apply_mesh_transformation(const Parameters::Mesh       &mesh_parameters,
                          Triangulation<dim, spacedim> &triangulation)
{
  // Mesh scaling
  GridTools::scale(mesh_parameters.scale, triangulation);
  if constexpr (dim == 2 && spacedim == 2)
    {
      // Box mesh rotation around the origin of the system coordinates
      GridTools::rotate(mesh_parameters.rotation_angle, triangulation);

      // Box mesh translation
      Tensor<1, 2> translation_vector;
      translation_vector[0] = mesh_parameters.translation[0];
      translation_vector[1] = mesh_parameters.translation[1];
      GridTools::shift(translation_vector, triangulation);
    }
  else if constexpr (dim == 2 && spacedim == 3)
    {
      // Box mesh rotation
      GridTools::rotate(mesh_parameters.rotation_axis,
                        mesh_parameters.rotation_angle,
                        triangulation);

      // Box mesh translation
      GridTools::shift(mesh_parameters.translation, triangulation);
    }
  else if constexpr (dim == 3)
    {
      // Box mesh rotation
      GridTools::rotate(mesh_parameters.rotation_axis,
                        mesh_parameters.rotation_angle,
                        triangulation);

      // Box mesh translation
      GridTools::shift(mesh_parameters.translation, triangulation);
    }
}


template void
attach_grid_to_triangulation(Triangulation<2>       &triangulation,
                             const Parameters::Mesh &mesh_parameters);
template void
attach_grid_to_triangulation(Triangulation<3>       &triangulation,
                             const Parameters::Mesh &mesh_parameters);
template void
attach_grid_to_triangulation(Triangulation<2, 3>    &triangulation,
                             const Parameters::Mesh &mesh_parameters);


template void
setup_periodic_boundary_conditions(
  parallel::DistributedTriangulationBase<2, 2>  &triangulation,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information);
template void
setup_periodic_boundary_conditions(
  parallel::DistributedTriangulationBase<2, 3>  &triangulation,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information);
template void
setup_periodic_boundary_conditions(
  parallel::DistributedTriangulationBase<3, 3>  &triangulation,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information);

template void
read_mesh_and_manifolds(
  parallel::DistributedTriangulationBase<2>     &triangulation,
  const Parameters::Mesh                        &mesh_parameters,
  const Parameters::Manifolds                   &manifolds_parameters,
  const bool                                     restart,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information);
template void
read_mesh_and_manifolds(
  parallel::DistributedTriangulationBase<3>     &triangulation,
  const Parameters::Mesh                        &mesh_parameters,
  const Parameters::Manifolds                   &manifolds_parameters,
  const bool                                     restart,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information);
template void
read_mesh_and_manifolds(
  parallel::DistributedTriangulationBase<2, 3>  &triangulation,
  const Parameters::Mesh                        &mesh_parameters,
  const Parameters::Manifolds                   &manifolds_parameters,
  const bool                                     restart,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information);

template void
read_mesh_and_manifolds_for_stator_and_rotor(
  parallel::DistributedTriangulationBase<2>     &triangulation,
  const Parameters::Mesh                        &mesh_parameters,
  const Parameters::Manifolds                   &manifolds_parameters,
  const bool                                     restart,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information,
  const Parameters::Mortar<2>                   &mortar_parameters);
template void
read_mesh_and_manifolds_for_stator_and_rotor(
  parallel::DistributedTriangulationBase<3>     &triangulation,
  const Parameters::Mesh                        &mesh_parameters,
  const Parameters::Manifolds                   &manifolds_parameters,
  const bool                                     restart,
  const Parameters::PeriodicBoundaryInformation &periodic_boundary_information,
  const Parameters::Mortar<3>                   &mortar_parameters);

template void
build_refinement_box_triangulation(const Parameters::Mesh &box_mesh_parameters,
                                   Triangulation<2, 2>    &box_triangulation);
template void
build_refinement_box_triangulation(const Parameters::Mesh &box_mesh_parameters,
                                   Triangulation<2, 3>    &box_triangulation);
template void
build_refinement_box_triangulation(const Parameters::Mesh &box_mesh_parameters,
                                   Triangulation<3, 3>    &box_triangulation);

template void
apply_mesh_transformation(const Parameters::Mesh &mesh_parameters,
                          Triangulation<2, 2>    &triangulation);
template void
apply_mesh_transformation(const Parameters::Mesh &mesh_parameters,
                          Triangulation<2, 3>    &triangulation);
template void
apply_mesh_transformation(const Parameters::Mesh &mesh_parameters,
                          Triangulation<3, 3>    &triangulation);
