var searchData=
[
  ['navierstokesbase_0',['NavierStokesBase',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20globalblockvectortype_2c_20std_3a_3avector_3c_20indexset_20_3e_20_3e_1',['NavierStokesBase&lt; dim, GlobalBlockVectorType, std::vector&lt; IndexSet &gt; &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20globalvectortype_2c_20indexset_20_3e_2',['NavierStokesBase&lt; dim, GlobalVectorType, IndexSet &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20double_20_3e_2c_20indexset_20_3e_3',['NavierStokesBase&lt; dim, LinearAlgebra::distributed::Vector&lt; double &gt;, IndexSet &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokescouplingevaluation_4',['NavierStokesCouplingEvaluation',['../classNavierStokesCouplingEvaluation.html',1,'']]],
  ['navierstokesfunctiondefined_5',['NavierStokesFunctionDefined',['../classNavierStokesFunctionDefined.html',1,'']]],
  ['navierstokesnonnewtonianstabilizedoperator_6',['NavierStokesNonNewtonianStabilizedOperator',['../classNavierStokesNonNewtonianStabilizedOperator.html',1,'']]],
  ['navierstokesoperatorbase_7',['NavierStokesOperatorBase',['../classNavierStokesOperatorBase.html',1,'']]],
  ['navierstokespressurefunctiondefined_8',['NavierStokesPressureFunctionDefined',['../classNavierStokesPressureFunctionDefined.html',1,'']]],
  ['navierstokesscratchdata_9',['NavierStokesScratchData',['../classNavierStokesScratchData.html',1,'']]],
  ['navierstokesstabilizedoperator_10',['NavierStokesStabilizedOperator',['../classNavierStokesStabilizedOperator.html',1,'']]],
  ['navierstokesvofassemblerevaporation_11',['NavierStokesVOFAssemblerEvaporation',['../classNavierStokesVOFAssemblerEvaporation.html',1,'']]],
  ['newtonian_12',['Newtonian',['../classNewtonian.html',1,'']]],
  ['newtonnonlinearsolver_13',['NewtonNonLinearSolver',['../classNewtonNonLinearSolver.html',1,'']]],
  ['nitsche_14',['Nitsche',['../classParameters_1_1Nitsche.html',1,'Parameters']]],
  ['nitscheobject_15',['NitscheObject',['../classParameters_1_1NitscheObject.html',1,'Parameters']]],
  ['nonetracerreactionprefactor_16',['NoneTracerReactionPrefactor',['../classNoneTracerReactionPrefactor.html',1,'']]],
  ['nonlinearsolver_17',['nonlinearsolver',['../classNonLinearSolver.html',1,'NonLinearSolver&lt; VectorType &gt;'],['../structParameters_1_1NonLinearSolver.html',1,'Parameters::NonLinearSolver']]],
  ['nonlinearsolver_3c_20globalblockvectortype_20_3e_18',['NonLinearSolver&lt; GlobalBlockVectorType &gt;',['../classNonLinearSolver.html',1,'']]],
  ['nonlinearsolver_3c_20globalvectortype_20_3e_19',['NonLinearSolver&lt; GlobalVectorType &gt;',['../classNonLinearSolver.html',1,'']]],
  ['nonlinearsolver_3c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20double_20_3e_20_3e_20',['NonLinearSolver&lt; LinearAlgebra::distributed::Vector&lt; double &gt; &gt;',['../classNonLinearSolver.html',1,'']]],
  ['nonnewtonian_21',['NonNewtonian',['../structParameters_1_1NonNewtonian.html',1,'Parameters']]],
  ['normaldistribution_22',['NormalDistribution',['../classNormalDistribution.html',1,'']]],
  ['nsboundaryconditions_23',['NSBoundaryConditions',['../classBoundaryConditions_1_1NSBoundaryConditions.html',1,'BoundaryConditions']]],
  ['nsboundaryfunctions_24',['NSBoundaryFunctions',['../classBoundaryConditions_1_1NSBoundaryFunctions.html',1,'BoundaryConditions']]]
];
