// SPDX-FileCopyrightText: Copyright (c) 2026 The Lethe Authors
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR LGPL-2.1-or-later

#ifndef lethe_cylinder_grid_h
#define lethe_cylinder_grid_h

#include <deal.II/base/utilities.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/manifold_lib.h>

#include <sstream>

using namespace dealii;

/**
 * @brief Class that creates a custom cylinder geometry with different ways to mesh the circular part of the geometry.
 *
 * @tparam dim The dimension of the mesh, must be 3.
 * @tparam spacedim The dimension of the space where the mesh is defined, must be 3.
 */

template <int dim, int spacedim>
class CylinderGrid
{
public:
  /**
   * @brief Constructor for the CylinderGrid.
   *
   * @param[in] grid_type. The type of cylinder mesh to be generated. The
   * choices are:
   * cylinder_classic|cylinder_balanced|cylinder_squared|cylinder_regularized.
   * For more details on the different types of cylinder meshes, refer to the
   * make_grid function.
   * @param[in] grid_arguments. A string with 3 parameters, @code "subdivisions:
   * radius : half height", separated by a colon. The subdivisions parameter is
   * the number of subdivisions in the x direction, the radius parameter is the
   * radius of the cylinder and the half height parameter is half the height of
   * the cylinder.
   */
  CylinderGrid(const std::string &grid_type, const std::string &grid_arguments);

  /**
   * @brief make_grid. The make_grid function generates cylindrical meshes with different meshing strategies for the circular part of the geometry, depending on the cylinder type specified in the constructor. It also constructs the geometry manifold with SphericalManifold.
   *
   * @param[out] triangulation. The triangulation object on which the grid is
   * generated
   */
  void
  make_grid(Triangulation<dim, spacedim> &triangulation);

private:
  std::string grid_arguments;
  int         subdivisions;
  double      radius;
  double      half_height;

  // Enum for the different types of cylinder meshes.
  // The types are:
  // - ``cyclinder_classic``, equivalent to a subdivided cylinder from deal.II;
  // - ``cylinder_balanced``, a cylinder with a more balanced element size and
  // aspect ratio;
  // - ``cylinder_squared``, has squared type meshing in the middle of the
  // circular part and becomes more and more skewed towards the outer part of
  // the circular geometry to fit the circle;
  // - ``cylinder_regularized``, a regularized version of the squared type to
  // reduce the skewness of the elements at the outer part of the circular
  // geometry.
  enum class CylinderType : std::int8_t
  {
    ///Classic cylinder grid generated by deal.II
    classic,
    ///Cylinder grid with balanced element size
    balanced,
    ///Cylinder grid with square-type meshing in the center
    squared,
    ///Regularized square cylinder to reduce element skewness
    regularized
  };
  CylinderType cylinder_type;
};


#endif
