// SPDX-FileCopyrightText: Copyright (c) 2026 The Lethe Authors
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR LGPL-2.1-or-later

#ifndef lethe_grid_mw_pipe_and_waveguide_h
#define lethe_grid_mw_pipe_and_waveguide_h

#include <deal.II/base/utilities.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/manifold_lib.h>

#include <array>
#include <sstream>

using namespace dealii;

/**
 * @brief Generates a 3D mesh of a waveguide cavity embedded in a cylinder in which a liquid flows
 *
 * The geometry consists of three sections joined along the z-axis:
 * - A bottom cylinder
 * - A central cylinder into which the rectangular-based waveguide is embedded
 * - A top cylinder
 *
 * Note that the mesh of the cylinder is inspired from the hyper_ball function
 * of the deal.II library. Therefore, the center of the cylinder
 *
 * Boundary IDs are assigned as follows:
 * -0: Microwaves (MW) inlet
 * -1: Fluid flow inlet (bottom surface of the cylinder)
 * -2: Fluid flow outlet (top surface of the cylinder)
 * -3: Walls
 *
 * Material IDs are assigned as follows:
 * -0: Fluid in the channel (cylinder)
 * -1: Air in the waveguide (paving stone)
 *
 * A CylindricalManifold is attached to the curved lateral surfaces of the
 * cylinder so that mesh refinement preserves the shape of the fluid
 * channel.
 *
 * @tparam dim The dimension of the mesh, must be 3.
 * @tparam spacedim The dimension of the space, must be 3.
 */

template <int dim, int spacedim>
class GridMwPipeAndWaveguide

{
public:
  /**
   * @brief Constructor that parses grid parameters from a colon-separated
   * string.
   *
   * @param[in] grid_arguments A string with the following format:
   * @code "rectangle_width : rectangle_length : outer_radius : inner_length :
   * bottom_height : middle_height : top_height : bottom_resolution :
   * middle_resolution : top_resolution : shape" @endcode
   *
   * | #   | Field             | Format        | Required | Description                                                                             |
   * |-----|-------------------|---------------|----------|-----------------------------------------------------------------------------------------|
   * |  0  | rectangle_width   | double        | yes      | Waveguide width                                                                         |
   * |  1  | rectangle_length  | double        | yes      | Waveguide length                                                                        |
   * |  2  | outer_radius      | double        | yes      | Radius of the main cylinder                                                             |
   * |  3  | inner_length      | double        | yes      | Depending on the inner shape, it can be the square side or the circle radius            |
   * |  4  | bottom_height     | double        | yes      | Height of the bottom cylinder                                                           |
   * |  5  | middle_height     | double        | yes      | Height of the waveguide                                                                 |
   * |  6  | top_height        | double        | yes      | Height of the top cylinder                                                              |
   * |  7  | bottom_resolution | double        | yes      | Number of cells generated by the extrusion of the bottom cylinder                       |
   * |  8  | middle_resolution | double        | yes      | Number of cells generated by the extrusion of the center cylinder                       |
   * |  9  | top_resolution    | double        | yes      | Number of cells generated by the extrusion of the top cylinder                          |
   * |  10 | inner_circle      | true/false    | no       | True (default): The inner shape is a circle False: Inner square                         |
   * Example: @code "2 : 5 : 5 : 3 : 2 : 2 : 3 : 1 : 1 : 1 : true" @endcode
   */
  GridMwPipeAndWaveguide(const std::string &grid_arguments);

  /**
   * @brief Generate a cylindrical fluid conduit in which a block-shaped waveguide is embedded.
   *
   * The three parts of the geometry (bottom cylinder, center_cylinder (with the
   * waveguide), top cylinder) are first merged and returned coarse
   *
   * @param[in,out] triangulation The triangulation to fill with the mesh.
   */

  void
  make_grid(Triangulation<dim, spacedim> &triangulation);

private:
  /**
   * @brief The function detailed_circle is a tool used in the core of the file
   *
   * This function is an extension of the 2D part of the hyper_ball in-built
   * deal.ii function.
   *
   * Since the deal.ii merge function needs the two trangulations to have
   * overlapped points, we needed to produce a coarse circular mesh with two
   * points at the exact place where the rectangle would fit. This is why this
   * function was created.
   *
   * There are three main differences between hyper_ball and detailed_circle:
   *
   * -Fourteen points were added to the mesh (22 in this function, 8 in the
   * original one) to link the circle with the rectangle we want to merge and to
   * prevent triangular cells from being generated.
   *
   * -A central rectangle of
   * width equal to the waveguide width crosses the circle along the x-axis.
   * This minimises the aspect ratio of the cells contained within the central
   * rectangle because their shape stay nearly rectangular. -In the original
   * function, a square lies in the center of the circle. An argument has been
   * added to this function to chose between a square and a circle. We call this
   * shape the "inner shape" of the circle.
   *
   * @param[in] tria
   * @param[in] p
   * @param[in] a
   * @param[in] b
   * @param[in] r
   * @param[in] R
   * @param[in] shape
   *
   * @code "detailed_circle(&tria,&p,&a,&b,r,R,shape)" @endcode
   *
   * | #   | Field  | Format                         | Required | Description                                                      |
   * |-----|--------|--------------------------------|----------|------------------------------------------------------------------|
   * |  0  | &tria  | Triangulation <dim, spacedim>  | yes      | Triangulation used for the mesh                                  |
   * |  1  | &p     | Point<spacedim>                | yes      | Center of the circle                                             |
   * |  2  | &a     | double                         | yes      | Rectangle width                                                  |
   * |  3  | &b     | double                         | yes      | Rectangle length                                                 |
   * |  4  | r      | double                         | yes      | Outer radius of the circle                                       |
   * |  5  | R      | double                         | yes      | Inner circle radius or inner square side                         |
   * |  6  | shape  | true/false                     | yes      | True : the inner shape is a circle, False : it is a square       |
   * Example: @code "detailed_circle(disk,center,1,3,7,3,false)" @endcode
   */
  void
  detailed_circle(Triangulation<2, 2> &tria,
                  const Point<2>      &p,
                  const double        &a,
                  const double        &b,
                  const double         r,
                  const double         R,
                  const bool           shape);



  /// Width of the rectangular waveguide
  double rectangle_width;

  /// Length of the rectangular waveguide
  double rectangle_length;

  /// Outer radius of the cylindrical cavity
  double outer_radius;

  /// Inner length (radius if circle, side if square) of the central shape
  double inner_length;

  /// Height of the bottom cylinder
  double bottom_height;

  /// Height of the center section (waveguide embedded in cylinder)
  double middle_height;

  /// Height of the top cylinder
  double top_height;

  /// Number of cells generated by the extrusion of the bottom cylinder
  int bottom_resolution;

  /// Number of cells generated by the extrusion of the center cylinder
  int middle_resolution;

  /// Number of cells generated by the extrusion of the tops cylinder
  int top_resolution;

  /// Shape of the inner region: true = circle, false = square
  bool shape;
};


#endif
