# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shahab/Lethe_newversion/lethe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shahab/Lethe_newversion/lethe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shahab/Lethe_newversion/lethe/CMakeFiles /home/shahab/Lethe_newversion/lethe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shahab/Lethe_newversion/lethe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lethe-core

# Build rule for target.
lethe-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lethe-core
.PHONY : lethe-core

# fast build rule for target.
lethe-core/fast:
	$(MAKE) -f source/core/CMakeFiles/lethe-core.dir/build.make source/core/CMakeFiles/lethe-core.dir/build
.PHONY : lethe-core/fast

#=============================================================================
# Target rules for targets named lethe-solvers

# Build rule for target.
lethe-solvers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lethe-solvers
.PHONY : lethe-solvers

# fast build rule for target.
lethe-solvers/fast:
	$(MAKE) -f source/solvers/CMakeFiles/lethe-solvers.dir/build.make source/solvers/CMakeFiles/lethe-solvers.dir/build
.PHONY : lethe-solvers/fast

#=============================================================================
# Target rules for targets named lethe-dem

# Build rule for target.
lethe-dem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lethe-dem
.PHONY : lethe-dem

# fast build rule for target.
lethe-dem/fast:
	$(MAKE) -f source/dem/CMakeFiles/lethe-dem.dir/build.make source/dem/CMakeFiles/lethe-dem.dir/build
.PHONY : lethe-dem/fast

#=============================================================================
# Target rules for targets named gls_navier_stokes_2d

# Build rule for target.
gls_navier_stokes_2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gls_navier_stokes_2d
.PHONY : gls_navier_stokes_2d

# fast build rule for target.
gls_navier_stokes_2d/fast:
	$(MAKE) -f applications/gls_navier_stokes_2d/CMakeFiles/gls_navier_stokes_2d.dir/build.make applications/gls_navier_stokes_2d/CMakeFiles/gls_navier_stokes_2d.dir/build
.PHONY : gls_navier_stokes_2d/fast

#=============================================================================
# Target rules for targets named gls_navier_stokes_3d

# Build rule for target.
gls_navier_stokes_3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gls_navier_stokes_3d
.PHONY : gls_navier_stokes_3d

# fast build rule for target.
gls_navier_stokes_3d/fast:
	$(MAKE) -f applications/gls_navier_stokes_3d/CMakeFiles/gls_navier_stokes_3d.dir/build.make applications/gls_navier_stokes_3d/CMakeFiles/gls_navier_stokes_3d.dir/build
.PHONY : gls_navier_stokes_3d/fast

#=============================================================================
# Target rules for targets named gd_navier_stokes_2d

# Build rule for target.
gd_navier_stokes_2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gd_navier_stokes_2d
.PHONY : gd_navier_stokes_2d

# fast build rule for target.
gd_navier_stokes_2d/fast:
	$(MAKE) -f applications/gd_navier_stokes_2d/CMakeFiles/gd_navier_stokes_2d.dir/build.make applications/gd_navier_stokes_2d/CMakeFiles/gd_navier_stokes_2d.dir/build
.PHONY : gd_navier_stokes_2d/fast

#=============================================================================
# Target rules for targets named gd_navier_stokes_3d

# Build rule for target.
gd_navier_stokes_3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gd_navier_stokes_3d
.PHONY : gd_navier_stokes_3d

# fast build rule for target.
gd_navier_stokes_3d/fast:
	$(MAKE) -f applications/gd_navier_stokes_3d/CMakeFiles/gd_navier_stokes_3d.dir/build.make applications/gd_navier_stokes_3d/CMakeFiles/gd_navier_stokes_3d.dir/build
.PHONY : gd_navier_stokes_3d/fast

#=============================================================================
# Target rules for targets named initial_conditions

# Build rule for target.
initial_conditions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 initial_conditions
.PHONY : initial_conditions

# fast build rule for target.
initial_conditions/fast:
	$(MAKE) -f applications/initial_conditions/CMakeFiles/initial_conditions.dir/build.make applications/initial_conditions/CMakeFiles/initial_conditions.dir/build
.PHONY : initial_conditions/fast

#=============================================================================
# Target rules for targets named navier_stokes_parameter_template

# Build rule for target.
navier_stokes_parameter_template: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 navier_stokes_parameter_template
.PHONY : navier_stokes_parameter_template

# fast build rule for target.
navier_stokes_parameter_template/fast:
	$(MAKE) -f applications/navier_stokes_parameter_template/CMakeFiles/navier_stokes_parameter_template.dir/build.make applications/navier_stokes_parameter_template/CMakeFiles/navier_stokes_parameter_template.dir/build
.PHONY : navier_stokes_parameter_template/fast

#=============================================================================
# Target rules for targets named dem_3d

# Build rule for target.
dem_3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dem_3d
.PHONY : dem_3d

# fast build rule for target.
dem_3d/fast:
	$(MAKE) -f applications/dem_3d/CMakeFiles/dem_3d.dir/build.make applications/dem_3d/CMakeFiles/dem_3d.dir/build
.PHONY : dem_3d/fast

#=============================================================================
# Target rules for targets named c_dem_3d

# Build rule for target.
c_dem_3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c_dem_3d
.PHONY : c_dem_3d

# fast build rule for target.
c_dem_3d/fast:
	$(MAKE) -f applications/c_dem_3d/CMakeFiles/c_dem_3d.dir/build.make applications/c_dem_3d/CMakeFiles/c_dem_3d.dir/build
.PHONY : c_dem_3d/fast

#=============================================================================
# Target rules for targets named dem_parameter_template

# Build rule for target.
dem_parameter_template: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dem_parameter_template
.PHONY : dem_parameter_template

# fast build rule for target.
dem_parameter_template/fast:
	$(MAKE) -f applications/dem_parameter_template/CMakeFiles/dem_parameter_template.dir/build.make applications/dem_parameter_template/CMakeFiles/dem_parameter_template.dir/build
.PHONY : dem_parameter_template/fast

#=============================================================================
# Target rules for targets named initial_conditions.release.diff

# Build rule for target.
initial_conditions.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 initial_conditions.release.diff
.PHONY : initial_conditions.release.diff

# fast build rule for target.
initial_conditions.release.diff/fast:
	$(MAKE) -f applications_tests/initial_conditions/CMakeFiles/initial_conditions.release.diff.dir/build.make applications_tests/initial_conditions/CMakeFiles/initial_conditions.release.diff.dir/build
.PHONY : initial_conditions.release.diff/fast

#=============================================================================
# Target rules for targets named taylor-green-vortex_gls_bdf1.mpirun2.release.diff

# Build rule for target.
taylor-green-vortex_gls_bdf1.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylor-green-vortex_gls_bdf1.mpirun2.release.diff
.PHONY : taylor-green-vortex_gls_bdf1.mpirun2.release.diff

# fast build rule for target.
taylor-green-vortex_gls_bdf1.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gls_bdf1.mpirun2.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gls_bdf1.mpirun2.release.diff.dir/build
.PHONY : taylor-green-vortex_gls_bdf1.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named taylorcouette_gls.mpirun2.release.diff

# Build rule for target.
taylorcouette_gls.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylorcouette_gls.mpirun2.release.diff
.PHONY : taylorcouette_gls.mpirun2.release.diff

# fast build rule for target.
taylorcouette_gls.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/taylorcouette_gls.mpirun2.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/taylorcouette_gls.mpirun2.release.diff.dir/build
.PHONY : taylorcouette_gls.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named cylinder_gls.release.diff

# Build rule for target.
cylinder_gls.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cylinder_gls.release.diff
.PHONY : cylinder_gls.release.diff

# fast build rule for target.
cylinder_gls.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/cylinder_gls.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/cylinder_gls.release.diff.dir/build
.PHONY : cylinder_gls.release.diff/fast

#=============================================================================
# Target rules for targets named poiseuille_gls.release.diff

# Build rule for target.
poiseuille_gls.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poiseuille_gls.release.diff
.PHONY : poiseuille_gls.release.diff

# fast build rule for target.
poiseuille_gls.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/poiseuille_gls.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/poiseuille_gls.release.diff.dir/build
.PHONY : poiseuille_gls.release.diff/fast

#=============================================================================
# Target rules for targets named taylor-green-vortex_gls_sdirk2.mpirun2.release.diff

# Build rule for target.
taylor-green-vortex_gls_sdirk2.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylor-green-vortex_gls_sdirk2.mpirun2.release.diff
.PHONY : taylor-green-vortex_gls_sdirk2.mpirun2.release.diff

# fast build rule for target.
taylor-green-vortex_gls_sdirk2.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gls_sdirk2.mpirun2.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gls_sdirk2.mpirun2.release.diff.dir/build
.PHONY : taylor-green-vortex_gls_sdirk2.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named taylor-green-vortex_gls_sdirk3.mpirun2.release.diff

# Build rule for target.
taylor-green-vortex_gls_sdirk3.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylor-green-vortex_gls_sdirk3.mpirun2.release.diff
.PHONY : taylor-green-vortex_gls_sdirk3.mpirun2.release.diff

# fast build rule for target.
taylor-green-vortex_gls_sdirk3.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gls_sdirk3.mpirun2.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gls_sdirk3.mpirun2.release.diff.dir/build
.PHONY : taylor-green-vortex_gls_sdirk3.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named taylorcouette-unstructured_gls.release.diff

# Build rule for target.
taylorcouette-unstructured_gls.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylorcouette-unstructured_gls.release.diff
.PHONY : taylorcouette-unstructured_gls.release.diff

# fast build rule for target.
taylorcouette-unstructured_gls.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/taylorcouette-unstructured_gls.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/taylorcouette-unstructured_gls.release.diff.dir/build
.PHONY : taylorcouette-unstructured_gls.release.diff/fast

#=============================================================================
# Target rules for targets named taylorcouette_gls.release.diff

# Build rule for target.
taylorcouette_gls.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylorcouette_gls.release.diff
.PHONY : taylorcouette_gls.release.diff

# fast build rule for target.
taylorcouette_gls.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/taylorcouette_gls.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/taylorcouette_gls.release.diff.dir/build
.PHONY : taylorcouette_gls.release.diff/fast

#=============================================================================
# Target rules for targets named mms2d_gls.release.diff

# Build rule for target.
mms2d_gls.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms2d_gls.release.diff
.PHONY : mms2d_gls.release.diff

# fast build rule for target.
mms2d_gls.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/mms2d_gls.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/mms2d_gls.release.diff.dir/build
.PHONY : mms2d_gls.release.diff/fast

#=============================================================================
# Target rules for targets named mms2d_gls.mpirun2.release.diff

# Build rule for target.
mms2d_gls.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms2d_gls.mpirun2.release.diff
.PHONY : mms2d_gls.mpirun2.release.diff

# fast build rule for target.
mms2d_gls.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/mms2d_gls.mpirun2.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/mms2d_gls.mpirun2.release.diff.dir/build
.PHONY : mms2d_gls.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named mms2d-unstructured_gls.release.diff

# Build rule for target.
mms2d-unstructured_gls.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms2d-unstructured_gls.release.diff
.PHONY : mms2d-unstructured_gls.release.diff

# fast build rule for target.
mms2d-unstructured_gls.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_2d/CMakeFiles/mms2d-unstructured_gls.release.diff.dir/build.make applications_tests/gls_navier_stokes_2d/CMakeFiles/mms2d-unstructured_gls.release.diff.dir/build
.PHONY : mms2d-unstructured_gls.release.diff/fast

#=============================================================================
# Target rules for targets named mms3d_gls.release.diff

# Build rule for target.
mms3d_gls.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms3d_gls.release.diff
.PHONY : mms3d_gls.release.diff

# fast build rule for target.
mms3d_gls.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_3d/CMakeFiles/mms3d_gls.release.diff.dir/build.make applications_tests/gls_navier_stokes_3d/CMakeFiles/mms3d_gls.release.diff.dir/build
.PHONY : mms3d_gls.release.diff/fast

#=============================================================================
# Target rules for targets named mms3d_gls.mpirun2.release.diff

# Build rule for target.
mms3d_gls.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms3d_gls.mpirun2.release.diff
.PHONY : mms3d_gls.mpirun2.release.diff

# fast build rule for target.
mms3d_gls.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_3d/CMakeFiles/mms3d_gls.mpirun2.release.diff.dir/build.make applications_tests/gls_navier_stokes_3d/CMakeFiles/mms3d_gls.mpirun2.release.diff.dir/build
.PHONY : mms3d_gls.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named poiseuille3d_gls.release.diff

# Build rule for target.
poiseuille3d_gls.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poiseuille3d_gls.release.diff
.PHONY : poiseuille3d_gls.release.diff

# fast build rule for target.
poiseuille3d_gls.release.diff/fast:
	$(MAKE) -f applications_tests/gls_navier_stokes_3d/CMakeFiles/poiseuille3d_gls.release.diff.dir/build.make applications_tests/gls_navier_stokes_3d/CMakeFiles/poiseuille3d_gls.release.diff.dir/build
.PHONY : poiseuille3d_gls.release.diff/fast

#=============================================================================
# Target rules for targets named taylorcouette_gd.release.diff

# Build rule for target.
taylorcouette_gd.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylorcouette_gd.release.diff
.PHONY : taylorcouette_gd.release.diff

# fast build rule for target.
taylorcouette_gd.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_2d/CMakeFiles/taylorcouette_gd.release.diff.dir/build.make applications_tests/gd_navier_stokes_2d/CMakeFiles/taylorcouette_gd.release.diff.dir/build
.PHONY : taylorcouette_gd.release.diff/fast

#=============================================================================
# Target rules for targets named mms2d_gd.mpirun2.release.diff

# Build rule for target.
mms2d_gd.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms2d_gd.mpirun2.release.diff
.PHONY : mms2d_gd.mpirun2.release.diff

# fast build rule for target.
mms2d_gd.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_2d/CMakeFiles/mms2d_gd.mpirun2.release.diff.dir/build.make applications_tests/gd_navier_stokes_2d/CMakeFiles/mms2d_gd.mpirun2.release.diff.dir/build
.PHONY : mms2d_gd.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named mms2d_gd.release.diff

# Build rule for target.
mms2d_gd.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms2d_gd.release.diff
.PHONY : mms2d_gd.release.diff

# fast build rule for target.
mms2d_gd.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_2d/CMakeFiles/mms2d_gd.release.diff.dir/build.make applications_tests/gd_navier_stokes_2d/CMakeFiles/mms2d_gd.release.diff.dir/build
.PHONY : mms2d_gd.release.diff/fast

#=============================================================================
# Target rules for targets named taylorcouette_gd.mpirun2.release.diff

# Build rule for target.
taylorcouette_gd.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylorcouette_gd.mpirun2.release.diff
.PHONY : taylorcouette_gd.mpirun2.release.diff

# fast build rule for target.
taylorcouette_gd.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_2d/CMakeFiles/taylorcouette_gd.mpirun2.release.diff.dir/build.make applications_tests/gd_navier_stokes_2d/CMakeFiles/taylorcouette_gd.mpirun2.release.diff.dir/build
.PHONY : taylorcouette_gd.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named taylor-green-vortex_gd_bdf2.release.diff

# Build rule for target.
taylor-green-vortex_gd_bdf2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylor-green-vortex_gd_bdf2.release.diff
.PHONY : taylor-green-vortex_gd_bdf2.release.diff

# fast build rule for target.
taylor-green-vortex_gd_bdf2.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gd_bdf2.release.diff.dir/build.make applications_tests/gd_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gd_bdf2.release.diff.dir/build
.PHONY : taylor-green-vortex_gd_bdf2.release.diff/fast

#=============================================================================
# Target rules for targets named poiseuille_gd.mpirun2.release.diff

# Build rule for target.
poiseuille_gd.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poiseuille_gd.mpirun2.release.diff
.PHONY : poiseuille_gd.mpirun2.release.diff

# fast build rule for target.
poiseuille_gd.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_2d/CMakeFiles/poiseuille_gd.mpirun2.release.diff.dir/build.make applications_tests/gd_navier_stokes_2d/CMakeFiles/poiseuille_gd.mpirun2.release.diff.dir/build
.PHONY : poiseuille_gd.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named mms2d-unstructured_gd.release.diff

# Build rule for target.
mms2d-unstructured_gd.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms2d-unstructured_gd.release.diff
.PHONY : mms2d-unstructured_gd.release.diff

# fast build rule for target.
mms2d-unstructured_gd.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_2d/CMakeFiles/mms2d-unstructured_gd.release.diff.dir/build.make applications_tests/gd_navier_stokes_2d/CMakeFiles/mms2d-unstructured_gd.release.diff.dir/build
.PHONY : mms2d-unstructured_gd.release.diff/fast

#=============================================================================
# Target rules for targets named taylor-green-vortex_gd_bdf1.release.diff

# Build rule for target.
taylor-green-vortex_gd_bdf1.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taylor-green-vortex_gd_bdf1.release.diff
.PHONY : taylor-green-vortex_gd_bdf1.release.diff

# fast build rule for target.
taylor-green-vortex_gd_bdf1.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gd_bdf1.release.diff.dir/build.make applications_tests/gd_navier_stokes_2d/CMakeFiles/taylor-green-vortex_gd_bdf1.release.diff.dir/build
.PHONY : taylor-green-vortex_gd_bdf1.release.diff/fast

#=============================================================================
# Target rules for targets named mms3d_gd.mpirun2.release.diff

# Build rule for target.
mms3d_gd.mpirun2.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mms3d_gd.mpirun2.release.diff
.PHONY : mms3d_gd.mpirun2.release.diff

# fast build rule for target.
mms3d_gd.mpirun2.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_3d/CMakeFiles/mms3d_gd.mpirun2.release.diff.dir/build.make applications_tests/gd_navier_stokes_3d/CMakeFiles/mms3d_gd.mpirun2.release.diff.dir/build
.PHONY : mms3d_gd.mpirun2.release.diff/fast

#=============================================================================
# Target rules for targets named poiseuille3d_gd.release.diff

# Build rule for target.
poiseuille3d_gd.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poiseuille3d_gd.release.diff
.PHONY : poiseuille3d_gd.release.diff

# fast build rule for target.
poiseuille3d_gd.release.diff/fast:
	$(MAKE) -f applications_tests/gd_navier_stokes_3d/CMakeFiles/poiseuille3d_gd.release.diff.dir/build.make applications_tests/gd_navier_stokes_3d/CMakeFiles/poiseuille3d_gd.release.diff.dir/build
.PHONY : poiseuille3d_gd.release.diff/fast

#=============================================================================
# Target rules for targets named pvd_handler_01.release.diff

# Build rule for target.
pvd_handler_01.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pvd_handler_01.release.diff
.PHONY : pvd_handler_01.release.diff

# fast build rule for target.
pvd_handler_01.release.diff/fast:
	$(MAKE) -f tests/core/CMakeFiles/pvd_handler_01.release.diff.dir/build.make tests/core/CMakeFiles/pvd_handler_01.release.diff.dir/build
.PHONY : pvd_handler_01.release.diff/fast

#=============================================================================
# Target rules for targets named newton_non_linear_solver_01.release.diff

# Build rule for target.
newton_non_linear_solver_01.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 newton_non_linear_solver_01.release.diff
.PHONY : newton_non_linear_solver_01.release.diff

# fast build rule for target.
newton_non_linear_solver_01.release.diff/fast:
	$(MAKE) -f tests/core/CMakeFiles/newton_non_linear_solver_01.release.diff.dir/build.make tests/core/CMakeFiles/newton_non_linear_solver_01.release.diff.dir/build
.PHONY : newton_non_linear_solver_01.release.diff/fast

#=============================================================================
# Target rules for targets named bdf_01.release

# Build rule for target.
bdf_01.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bdf_01.release
.PHONY : bdf_01.release

# fast build rule for target.
bdf_01.release/fast:
	$(MAKE) -f tests/core/CMakeFiles/bdf_01.release.dir/build.make tests/core/CMakeFiles/bdf_01.release.dir/build
.PHONY : bdf_01.release/fast

#=============================================================================
# Target rules for targets named newton_non_linear_solver_01.release

# Build rule for target.
newton_non_linear_solver_01.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 newton_non_linear_solver_01.release
.PHONY : newton_non_linear_solver_01.release

# fast build rule for target.
newton_non_linear_solver_01.release/fast:
	$(MAKE) -f tests/core/CMakeFiles/newton_non_linear_solver_01.release.dir/build.make tests/core/CMakeFiles/newton_non_linear_solver_01.release.dir/build
.PHONY : newton_non_linear_solver_01.release/fast

#=============================================================================
# Target rules for targets named bdf_01.release.diff

# Build rule for target.
bdf_01.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bdf_01.release.diff
.PHONY : bdf_01.release.diff

# fast build rule for target.
bdf_01.release.diff/fast:
	$(MAKE) -f tests/core/CMakeFiles/bdf_01.release.diff.dir/build.make tests/core/CMakeFiles/bdf_01.release.diff.dir/build
.PHONY : bdf_01.release.diff/fast

#=============================================================================
# Target rules for targets named simulation_control_01.release

# Build rule for target.
simulation_control_01.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulation_control_01.release
.PHONY : simulation_control_01.release

# fast build rule for target.
simulation_control_01.release/fast:
	$(MAKE) -f tests/core/CMakeFiles/simulation_control_01.release.dir/build.make tests/core/CMakeFiles/simulation_control_01.release.dir/build
.PHONY : simulation_control_01.release/fast

#=============================================================================
# Target rules for targets named skip_newton_non_linear_solver_01.release

# Build rule for target.
skip_newton_non_linear_solver_01.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skip_newton_non_linear_solver_01.release
.PHONY : skip_newton_non_linear_solver_01.release

# fast build rule for target.
skip_newton_non_linear_solver_01.release/fast:
	$(MAKE) -f tests/core/CMakeFiles/skip_newton_non_linear_solver_01.release.dir/build.make tests/core/CMakeFiles/skip_newton_non_linear_solver_01.release.dir/build
.PHONY : skip_newton_non_linear_solver_01.release/fast

#=============================================================================
# Target rules for targets named pvd_handler_01.release

# Build rule for target.
pvd_handler_01.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pvd_handler_01.release
.PHONY : pvd_handler_01.release

# fast build rule for target.
pvd_handler_01.release/fast:
	$(MAKE) -f tests/core/CMakeFiles/pvd_handler_01.release.dir/build.make tests/core/CMakeFiles/pvd_handler_01.release.dir/build
.PHONY : pvd_handler_01.release/fast

#=============================================================================
# Target rules for targets named simulation_control_01.release.diff

# Build rule for target.
simulation_control_01.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulation_control_01.release.diff
.PHONY : simulation_control_01.release.diff

# fast build rule for target.
simulation_control_01.release.diff/fast:
	$(MAKE) -f tests/core/CMakeFiles/simulation_control_01.release.diff.dir/build.make tests/core/CMakeFiles/simulation_control_01.release.diff.dir/build
.PHONY : simulation_control_01.release.diff/fast

#=============================================================================
# Target rules for targets named skip_newton_non_linear_solver_01.release.diff

# Build rule for target.
skip_newton_non_linear_solver_01.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skip_newton_non_linear_solver_01.release.diff
.PHONY : skip_newton_non_linear_solver_01.release.diff

# fast build rule for target.
skip_newton_non_linear_solver_01.release.diff/fast:
	$(MAKE) -f tests/core/CMakeFiles/skip_newton_non_linear_solver_01.release.diff.dir/build.make tests/core/CMakeFiles/skip_newton_non_linear_solver_01.release.diff.dir/build
.PHONY : skip_newton_non_linear_solver_01.release.diff/fast

#=============================================================================
# Target rules for targets named restart_01.release.diff

# Build rule for target.
restart_01.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 restart_01.release.diff
.PHONY : restart_01.release.diff

# fast build rule for target.
restart_01.release.diff/fast:
	$(MAKE) -f tests/solvers/CMakeFiles/restart_01.release.diff.dir/build.make tests/solvers/CMakeFiles/restart_01.release.diff.dir/build
.PHONY : restart_01.release.diff/fast

#=============================================================================
# Target rules for targets named restart_01.release

# Build rule for target.
restart_01.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 restart_01.release
.PHONY : restart_01.release

# fast build rule for target.
restart_01.release/fast:
	$(MAKE) -f tests/solvers/CMakeFiles/restart_01.release.dir/build.make tests/solvers/CMakeFiles/restart_01.release.dir/build
.PHONY : restart_01.release/fast

#=============================================================================
# Target rules for targets named particle_wall_contact_pairs.release.diff

# Build rule for target.
particle_wall_contact_pairs.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_wall_contact_pairs.release.diff
.PHONY : particle_wall_contact_pairs.release.diff

# fast build rule for target.
particle_wall_contact_pairs.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_wall_contact_pairs.release.diff.dir/build.make tests/dem/CMakeFiles/particle_wall_contact_pairs.release.diff.dir/build
.PHONY : particle_wall_contact_pairs.release.diff/fast

#=============================================================================
# Target rules for targets named particle_wall_contact_pairs.release

# Build rule for target.
particle_wall_contact_pairs.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_wall_contact_pairs.release
.PHONY : particle_wall_contact_pairs.release

# fast build rule for target.
particle_wall_contact_pairs.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_wall_contact_pairs.release.dir/build.make tests/dem/CMakeFiles/particle_wall_contact_pairs.release.dir/build
.PHONY : particle_wall_contact_pairs.release/fast

#=============================================================================
# Target rules for targets named particle_wall_contact_force_nonlinear.release.diff

# Build rule for target.
particle_wall_contact_force_nonlinear.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_wall_contact_force_nonlinear.release.diff
.PHONY : particle_wall_contact_force_nonlinear.release.diff

# fast build rule for target.
particle_wall_contact_force_nonlinear.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_wall_contact_force_nonlinear.release.diff.dir/build.make tests/dem/CMakeFiles/particle_wall_contact_force_nonlinear.release.diff.dir/build
.PHONY : particle_wall_contact_force_nonlinear.release.diff/fast

#=============================================================================
# Target rules for targets named particle_wall_contact_force_nonlinear.release

# Build rule for target.
particle_wall_contact_force_nonlinear.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_wall_contact_force_nonlinear.release
.PHONY : particle_wall_contact_force_nonlinear.release

# fast build rule for target.
particle_wall_contact_force_nonlinear.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_wall_contact_force_nonlinear.release.dir/build.make tests/dem/CMakeFiles/particle_wall_contact_force_nonlinear.release.dir/build
.PHONY : particle_wall_contact_force_nonlinear.release/fast

#=============================================================================
# Target rules for targets named particle_wall_contact_force_linear.release

# Build rule for target.
particle_wall_contact_force_linear.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_wall_contact_force_linear.release
.PHONY : particle_wall_contact_force_linear.release

# fast build rule for target.
particle_wall_contact_force_linear.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_wall_contact_force_linear.release.dir/build.make tests/dem/CMakeFiles/particle_wall_contact_force_linear.release.dir/build
.PHONY : particle_wall_contact_force_linear.release/fast

#=============================================================================
# Target rules for targets named particle_particle_fine_search.release.diff

# Build rule for target.
particle_particle_fine_search.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_particle_fine_search.release.diff
.PHONY : particle_particle_fine_search.release.diff

# fast build rule for target.
particle_particle_fine_search.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_particle_fine_search.release.diff.dir/build.make tests/dem/CMakeFiles/particle_particle_fine_search.release.diff.dir/build
.PHONY : particle_particle_fine_search.release.diff/fast

#=============================================================================
# Target rules for targets named find_cell_neighbors.release.diff

# Build rule for target.
find_cell_neighbors.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 find_cell_neighbors.release.diff
.PHONY : find_cell_neighbors.release.diff

# fast build rule for target.
find_cell_neighbors.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/find_cell_neighbors.release.diff.dir/build.make tests/dem/CMakeFiles/find_cell_neighbors.release.diff.dir/build
.PHONY : find_cell_neighbors.release.diff/fast

#=============================================================================
# Target rules for targets named boundary_cells_and_faces.release

# Build rule for target.
boundary_cells_and_faces.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boundary_cells_and_faces.release
.PHONY : boundary_cells_and_faces.release

# fast build rule for target.
boundary_cells_and_faces.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/boundary_cells_and_faces.release.dir/build.make tests/dem/CMakeFiles/boundary_cells_and_faces.release.dir/build
.PHONY : boundary_cells_and_faces.release/fast

#=============================================================================
# Target rules for targets named particle_wall_contact_force_linear.release.diff

# Build rule for target.
particle_wall_contact_force_linear.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_wall_contact_force_linear.release.diff
.PHONY : particle_wall_contact_force_linear.release.diff

# fast build rule for target.
particle_wall_contact_force_linear.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_wall_contact_force_linear.release.diff.dir/build.make tests/dem/CMakeFiles/particle_wall_contact_force_linear.release.diff.dir/build
.PHONY : particle_wall_contact_force_linear.release.diff/fast

#=============================================================================
# Target rules for targets named integration_velocity_verlet.release

# Build rule for target.
integration_velocity_verlet.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integration_velocity_verlet.release
.PHONY : integration_velocity_verlet.release

# fast build rule for target.
integration_velocity_verlet.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/integration_velocity_verlet.release.dir/build.make tests/dem/CMakeFiles/integration_velocity_verlet.release.dir/build
.PHONY : integration_velocity_verlet.release/fast

#=============================================================================
# Target rules for targets named find_contact_pairs.release.diff

# Build rule for target.
find_contact_pairs.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 find_contact_pairs.release.diff
.PHONY : find_contact_pairs.release.diff

# fast build rule for target.
find_contact_pairs.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/find_contact_pairs.release.diff.dir/build.make tests/dem/CMakeFiles/find_contact_pairs.release.diff.dir/build
.PHONY : find_contact_pairs.release.diff/fast

#=============================================================================
# Target rules for targets named particle_wall_fine_search.release.diff

# Build rule for target.
particle_wall_fine_search.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_wall_fine_search.release.diff
.PHONY : particle_wall_fine_search.release.diff

# fast build rule for target.
particle_wall_fine_search.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_wall_fine_search.release.diff.dir/build.make tests/dem/CMakeFiles/particle_wall_fine_search.release.diff.dir/build
.PHONY : particle_wall_fine_search.release.diff/fast

#=============================================================================
# Target rules for targets named boundary_cells_and_faces.release.diff

# Build rule for target.
boundary_cells_and_faces.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boundary_cells_and_faces.release.diff
.PHONY : boundary_cells_and_faces.release.diff

# fast build rule for target.
boundary_cells_and_faces.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/boundary_cells_and_faces.release.diff.dir/build.make tests/dem/CMakeFiles/boundary_cells_and_faces.release.diff.dir/build
.PHONY : boundary_cells_and_faces.release.diff/fast

#=============================================================================
# Target rules for targets named find_contact_pairs.release

# Build rule for target.
find_contact_pairs.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 find_contact_pairs.release
.PHONY : find_contact_pairs.release

# fast build rule for target.
find_contact_pairs.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/find_contact_pairs.release.dir/build.make tests/dem/CMakeFiles/find_contact_pairs.release.dir/build
.PHONY : find_contact_pairs.release/fast

#=============================================================================
# Target rules for targets named insertion_uniform.release

# Build rule for target.
insertion_uniform.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 insertion_uniform.release
.PHONY : insertion_uniform.release

# fast build rule for target.
insertion_uniform.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/insertion_uniform.release.dir/build.make tests/dem/CMakeFiles/insertion_uniform.release.dir/build
.PHONY : insertion_uniform.release/fast

#=============================================================================
# Target rules for targets named particle_particle_fine_search.release

# Build rule for target.
particle_particle_fine_search.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_particle_fine_search.release
.PHONY : particle_particle_fine_search.release

# fast build rule for target.
particle_particle_fine_search.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_particle_fine_search.release.dir/build.make tests/dem/CMakeFiles/particle_particle_fine_search.release.dir/build
.PHONY : particle_particle_fine_search.release/fast

#=============================================================================
# Target rules for targets named insertion_uniform.release.diff

# Build rule for target.
insertion_uniform.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 insertion_uniform.release.diff
.PHONY : insertion_uniform.release.diff

# fast build rule for target.
insertion_uniform.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/insertion_uniform.release.diff.dir/build.make tests/dem/CMakeFiles/insertion_uniform.release.diff.dir/build
.PHONY : insertion_uniform.release.diff/fast

#=============================================================================
# Target rules for targets named particle_particle_contact_force_linear.release.diff

# Build rule for target.
particle_particle_contact_force_linear.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_particle_contact_force_linear.release.diff
.PHONY : particle_particle_contact_force_linear.release.diff

# fast build rule for target.
particle_particle_contact_force_linear.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_particle_contact_force_linear.release.diff.dir/build.make tests/dem/CMakeFiles/particle_particle_contact_force_linear.release.diff.dir/build
.PHONY : particle_particle_contact_force_linear.release.diff/fast

#=============================================================================
# Target rules for targets named find_cell_neighbors.release

# Build rule for target.
find_cell_neighbors.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 find_cell_neighbors.release
.PHONY : find_cell_neighbors.release

# fast build rule for target.
find_cell_neighbors.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/find_cell_neighbors.release.dir/build.make tests/dem/CMakeFiles/find_cell_neighbors.release.dir/build
.PHONY : find_cell_neighbors.release/fast

#=============================================================================
# Target rules for targets named integration_euler.release

# Build rule for target.
integration_euler.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integration_euler.release
.PHONY : integration_euler.release

# fast build rule for target.
integration_euler.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/integration_euler.release.dir/build.make tests/dem/CMakeFiles/integration_euler.release.dir/build
.PHONY : integration_euler.release/fast

#=============================================================================
# Target rules for targets named particle_wall_fine_search.release

# Build rule for target.
particle_wall_fine_search.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_wall_fine_search.release
.PHONY : particle_wall_fine_search.release

# fast build rule for target.
particle_wall_fine_search.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_wall_fine_search.release.dir/build.make tests/dem/CMakeFiles/particle_wall_fine_search.release.dir/build
.PHONY : particle_wall_fine_search.release/fast

#=============================================================================
# Target rules for targets named integration_euler.release.diff

# Build rule for target.
integration_euler.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integration_euler.release.diff
.PHONY : integration_euler.release.diff

# fast build rule for target.
integration_euler.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/integration_euler.release.diff.dir/build.make tests/dem/CMakeFiles/integration_euler.release.diff.dir/build
.PHONY : integration_euler.release.diff/fast

#=============================================================================
# Target rules for targets named particle_particle_contact_force_nonlinear.release

# Build rule for target.
particle_particle_contact_force_nonlinear.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_particle_contact_force_nonlinear.release
.PHONY : particle_particle_contact_force_nonlinear.release

# fast build rule for target.
particle_particle_contact_force_nonlinear.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_particle_contact_force_nonlinear.release.dir/build.make tests/dem/CMakeFiles/particle_particle_contact_force_nonlinear.release.dir/build
.PHONY : particle_particle_contact_force_nonlinear.release/fast

#=============================================================================
# Target rules for targets named integration_velocity_verlet.release.diff

# Build rule for target.
integration_velocity_verlet.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integration_velocity_verlet.release.diff
.PHONY : integration_velocity_verlet.release.diff

# fast build rule for target.
integration_velocity_verlet.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/integration_velocity_verlet.release.diff.dir/build.make tests/dem/CMakeFiles/integration_velocity_verlet.release.diff.dir/build
.PHONY : integration_velocity_verlet.release.diff/fast

#=============================================================================
# Target rules for targets named particle_particle_contact_force_linear.release

# Build rule for target.
particle_particle_contact_force_linear.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_particle_contact_force_linear.release
.PHONY : particle_particle_contact_force_linear.release

# fast build rule for target.
particle_particle_contact_force_linear.release/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_particle_contact_force_linear.release.dir/build.make tests/dem/CMakeFiles/particle_particle_contact_force_linear.release.dir/build
.PHONY : particle_particle_contact_force_linear.release/fast

#=============================================================================
# Target rules for targets named particle_particle_contact_force_nonlinear.release.diff

# Build rule for target.
particle_particle_contact_force_nonlinear.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle_particle_contact_force_nonlinear.release.diff
.PHONY : particle_particle_contact_force_nonlinear.release.diff

# fast build rule for target.
particle_particle_contact_force_nonlinear.release.diff/fast:
	$(MAKE) -f tests/dem/CMakeFiles/particle_particle_contact_force_nonlinear.release.diff.dir/build.make tests/dem/CMakeFiles/particle_particle_contact_force_nonlinear.release.diff.dir/build
.PHONY : particle_particle_contact_force_nonlinear.release.diff/fast

#=============================================================================
# Target rules for targets named directSteadyNS

# Build rule for target.
directSteadyNS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 directSteadyNS
.PHONY : directSteadyNS

# fast build rule for target.
directSteadyNS/fast:
	$(MAKE) -f prototypes/direct_steadyNS/CMakeFiles/directSteadyNS.dir/build.make prototypes/direct_steadyNS/CMakeFiles/directSteadyNS.dir/build
.PHONY : directSteadyNS/fast

#=============================================================================
# Target rules for targets named direct_gls_navier_stokes

# Build rule for target.
direct_gls_navier_stokes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 direct_gls_navier_stokes
.PHONY : direct_gls_navier_stokes

# fast build rule for target.
direct_gls_navier_stokes/fast:
	$(MAKE) -f prototypes/direct_gls_navier_stokes/CMakeFiles/direct_gls_navier_stokes.dir/build.make prototypes/direct_gls_navier_stokes/CMakeFiles/direct_gls_navier_stokes.dir/build
.PHONY : direct_gls_navier_stokes/fast

#=============================================================================
# Target rules for targets named protype_template

# Build rule for target.
protype_template: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protype_template
.PHONY : protype_template

# fast build rule for target.
protype_template/fast:
	$(MAKE) -f prototypes/template/CMakeFiles/protype_template.dir/build.make prototypes/template/CMakeFiles/protype_template.dir/build
.PHONY : protype_template/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... test"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... lethe-core"
	@echo "... lethe-solvers"
	@echo "... lethe-dem"
	@echo "... gls_navier_stokes_2d"
	@echo "... gls_navier_stokes_3d"
	@echo "... gd_navier_stokes_2d"
	@echo "... gd_navier_stokes_3d"
	@echo "... initial_conditions"
	@echo "... navier_stokes_parameter_template"
	@echo "... dem_3d"
	@echo "... c_dem_3d"
	@echo "... dem_parameter_template"
	@echo "... initial_conditions.release.diff"
	@echo "... taylor-green-vortex_gls_bdf1.mpirun2.release.diff"
	@echo "... taylorcouette_gls.mpirun2.release.diff"
	@echo "... cylinder_gls.release.diff"
	@echo "... poiseuille_gls.release.diff"
	@echo "... taylor-green-vortex_gls_sdirk2.mpirun2.release.diff"
	@echo "... taylor-green-vortex_gls_sdirk3.mpirun2.release.diff"
	@echo "... taylorcouette-unstructured_gls.release.diff"
	@echo "... taylorcouette_gls.release.diff"
	@echo "... mms2d_gls.release.diff"
	@echo "... mms2d_gls.mpirun2.release.diff"
	@echo "... mms2d-unstructured_gls.release.diff"
	@echo "... mms3d_gls.release.diff"
	@echo "... mms3d_gls.mpirun2.release.diff"
	@echo "... poiseuille3d_gls.release.diff"
	@echo "... taylorcouette_gd.release.diff"
	@echo "... mms2d_gd.mpirun2.release.diff"
	@echo "... mms2d_gd.release.diff"
	@echo "... taylorcouette_gd.mpirun2.release.diff"
	@echo "... taylor-green-vortex_gd_bdf2.release.diff"
	@echo "... poiseuille_gd.mpirun2.release.diff"
	@echo "... mms2d-unstructured_gd.release.diff"
	@echo "... taylor-green-vortex_gd_bdf1.release.diff"
	@echo "... mms3d_gd.mpirun2.release.diff"
	@echo "... poiseuille3d_gd.release.diff"
	@echo "... pvd_handler_01.release.diff"
	@echo "... newton_non_linear_solver_01.release.diff"
	@echo "... bdf_01.release"
	@echo "... newton_non_linear_solver_01.release"
	@echo "... bdf_01.release.diff"
	@echo "... simulation_control_01.release"
	@echo "... skip_newton_non_linear_solver_01.release"
	@echo "... pvd_handler_01.release"
	@echo "... simulation_control_01.release.diff"
	@echo "... skip_newton_non_linear_solver_01.release.diff"
	@echo "... restart_01.release.diff"
	@echo "... restart_01.release"
	@echo "... particle_wall_contact_pairs.release.diff"
	@echo "... particle_wall_contact_pairs.release"
	@echo "... particle_wall_contact_force_nonlinear.release.diff"
	@echo "... particle_wall_contact_force_nonlinear.release"
	@echo "... particle_wall_contact_force_linear.release"
	@echo "... particle_particle_fine_search.release.diff"
	@echo "... find_cell_neighbors.release.diff"
	@echo "... boundary_cells_and_faces.release"
	@echo "... particle_wall_contact_force_linear.release.diff"
	@echo "... integration_velocity_verlet.release"
	@echo "... find_contact_pairs.release.diff"
	@echo "... particle_wall_fine_search.release.diff"
	@echo "... boundary_cells_and_faces.release.diff"
	@echo "... find_contact_pairs.release"
	@echo "... insertion_uniform.release"
	@echo "... particle_particle_fine_search.release"
	@echo "... insertion_uniform.release.diff"
	@echo "... particle_particle_contact_force_linear.release.diff"
	@echo "... find_cell_neighbors.release"
	@echo "... integration_euler.release"
	@echo "... particle_wall_fine_search.release"
	@echo "... integration_euler.release.diff"
	@echo "... particle_particle_contact_force_nonlinear.release"
	@echo "... integration_velocity_verlet.release.diff"
	@echo "... particle_particle_contact_force_linear.release"
	@echo "... particle_particle_contact_force_nonlinear.release.diff"
	@echo "... directSteadyNS"
	@echo "... direct_gls_navier_stokes"
	@echo "... protype_template"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

