

"""
Convergence plot (L2 norm) of the TE10 mode for the waveguide benchmark.
Data taken from the .out files generated by the solver.
"""

import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import curve_fit

# ---------------------------------------------------------------------------
# Global plot style – publication quality (serif fonts, LaTeX rendering)
# ---------------------------------------------------------------------------
plt.rcParams.update({
    "text.usetex":        True,
    "font.family":        "serif",
    "font.serif":         ["Computer Modern Roman"],
    "font.size":          11,
    "axes.labelsize":     14,
    "axes.titlesize":     15,
    "legend.fontsize":    16,
    "xtick.labelsize":    11,
    "ytick.labelsize":    11,
    "lines.linewidth":    1.4,
    "axes.linewidth":     0.8,
    "xtick.direction":    "in",
    "ytick.direction":    "in",
    "xtick.major.size":   5,
    "ytick.major.size":   5,
    "xtick.minor.size":   3,
    "ytick.minor.size":   3,
    "xtick.top":          True,
    "ytick.right":        True,
})

# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------
h_size = np.array([0.25, 0.125, 0.0625, 0.03125, 0.015625, 0.0078125])

n_dofs_d1 = np.array([720,4320,29376,215424,1647360,12879360]) 
n_dofs_d2 = np.array([2016,13104,93600,705600,5475456])
n_dofs_d3 = np.array([4320,29376,215424,1647360,12879360])

# fmt: off
# Degree 1  (6 refinements)
residuals_Er_d1 = np.array([5.907202e-1, 5.320367e-1, 2.862564e-1, 4.962408e-2, 1.176478e-2, 2.936936e-3])  # Residuals for the real part of the electric field for degree 1.
residuals_Ei_d1 = np.array([4.149077e-1, 4.890303e-1, 2.315915e-1, 4.930252e-2, 1.161799e-2, 2.886278e-3])  # Residuals for the imaginary part of the electric field for degree 1.
residuals_Hr_d1 = np.array([5.816310e-1, 5.304793e-1, 2.846897e-1, 4.943593e-2, 1.168092e-2, 2.908837e-3])  # Residuals for the real part of the magnetic field for degree 1.
residuals_Hi_d1 = np.array([4.275905e-1, 4.888267e-1, 2.353982e-1, 4.930857e-2, 1.166051e-2, 2.916817e-3])  # Residuals for the imaginary part of the magnetic field for degree 1.

# Degree 2  (5 refinements)
residuals_Er_d2 = np.array([2.988491e-01,4.721492e-01,2.427398e-02, 6.025788e-03, 7.837775e-04])  # Residuals for the real part of the electric field for degree 2.
residuals_Ei_d2 = np.array([6.628463e-01,4.500659e-01,6.054008e-02, 6.091755e-03, 7.906104e-04])  # Residuals for the imaginary part of the electric field for degree 2.
residuals_Hr_d2 = np.array([3.287570e-01,4.648666e-01,2.801794e-02, 6.036317e-03, 7.849096e-04])  # Residuals for the real part of the magnetic field for degree 2.
residuals_Hi_d2 = np.array([6.468069e-01,4.601958e-01,5.911523e-02, 6.101385e-03, 7.913617e-04])  # Residuals for the imaginary part of the magnetic field for degree 2.

# Degree 3  (5 refinements)
residuals_Er_d3 = np.array([6.158498e-01, 1.331351e-01, 1.163227e-02, 5.870519e-04, 3.762534e-05])  # Residuals for the real part of the electric field for degree 3.
residuals_Ei_d3 = np.array([4.012373e-01, 1.813543e-01, 3.771406e-03, 5.799182e-04, 3.728215e-05])  # Residuals for the imaginary part of the electric field for degree 3.
residuals_Hr_d3 = np.array([6.051684e-01, 1.440006e-01, 1.134392e-02, 5.875975e-04, 3.765974e-05])  # Residuals for the real part of the magnetic field for degree 3.
residuals_Hi_d3 = np.array([4.175325e-01, 1.737063e-01, 4.652121e-03, 5.813913e-04, 3.736087e-05])  # Residuals for the imaginary part of the magnetic field for degree 3.
# fmt: on

# Collect data per subplot: (Er, Ei, Hr, Hi)
field_data = [
    [residuals_Er_d1[:-1], residuals_Er_d2, residuals_Er_d3],  # Re(E)
    [residuals_Ei_d1[:-1], residuals_Ei_d2, residuals_Ei_d3],  # Im(E)
    [residuals_Hr_d1[:-1], residuals_Hr_d2, residuals_Hr_d3],  # Re(H)
    [residuals_Hi_d1[:-1], residuals_Hi_d2, residuals_Hi_d3],  # Im(H)
]

# ---------------------------------------------------------------------------
# Plotting helpers
# ---------------------------------------------------------------------------
# Colour-blind-friendly palette (Tol vibrant)
COLORS   = ['#1b9e77','#d95f02','#7570b3']
MARKERS  = ["o", "s", "D"]
DEGREES  = [1, 2, 3]
N_PTS    = [len(h_size) - 1, len(h_size) - 1, len(h_size) - 1]  # pts per degree

titles = [
    r"$\Re(\mathbf{E})$",
    r"$\Im(\mathbf{E})$",
    r"$\Re(\mathbf{H})$",
    r"$\Im(\mathbf{H})$",
]


def fit_slope(h, err, n_fit=3, offset=0.8):
    """Log-linear fit on the last *n_fit* points.

    Returns slope, h_ref, fitted_ref where h_ref and fitted_ref cover
    only the fitted region, shifted up by *offset* (in log-space) so
    the reference line sits clearly below the data.
    """
    log_h = np.log(h[-n_fit:])
    log_e = np.log(err[-n_fit:])
    m, b = np.polyfit(log_h[-2:], log_e[-2:], 1)
    fitted = np.exp(m * log_h + b + offset)   # shift up for visibility
    return m, h[-n_fit:], fitted


# ---------------------------------------------------------------------------
# Build figure  (2 x 2 subplots, shared axes)
# ---------------------------------------------------------------------------
fig, axs = plt.subplots(2, 2, figsize=(7.5, 6.5), sharex=True, sharey=True)

for idx, ax in enumerate(axs.flat):
    for d, (deg, n, col, mkr) in enumerate(zip(DEGREES, N_PTS, COLORS, MARKERS)):
        h   = h_size[:n]
        err = field_data[idx][d]

        # Data points
        ax.loglog(h, err, marker=mkr, color=col, markersize=5,
                  markerfacecolor="white", markeredgewidth=1.2,
                  linestyle="-", linewidth=1.2, zorder=3,
                  label=rf"$p={deg}$")

        # Asymptotic slope (short reference line, offset below data)
        slope, h_ref, fit_ref = fit_slope(h, err)
        ax.loglog(h_ref, fit_ref, ls="--", color=col, linewidth=1.0,
                  alpha=0.7, zorder=2)

        # Slope label at the midpoint of the reference line
        mid = len(h_ref) // 2
        ax.annotate(rf"$\mathbf{{{slope:.2f}}}$", xy=(h_ref[mid], fit_ref[mid]),
                fontsize=12, color=col, ha="right", fontweight="bold",
                xytext=(-6, -2), textcoords="offset points")

    # Subplot cosmetics
    ax.set_title(titles[idx])
    ax.grid(True, which="major", ls="-", lw=0.4, alpha=0.35)
    ax.grid(True, which="minor", ls=":", lw=0.3, alpha=0.25)
    ax.minorticks_on()

# Axis labels on outer edges only
for ax in axs[1, :]:
    ax.set_xlabel(r"Mesh size $h$\,[m]")
for ax in axs[:, 0]:
    ax.set_ylabel(r"$\|u-u_h\|_{L^2}$")

# Single shared legend at the top
handles, labels = axs[0, 0].get_legend_handles_labels()
fig.legend(handles, labels, loc="upper center", ncol=3,
           frameon=False, bbox_to_anchor=(0.5, 1.01))

fig.tight_layout(rect=[0, 0, 1, 0.96])
fig.savefig("waveguide.png",  dpi=400, bbox_inches="tight")
fig.savefig("waveguide.pdf",  bbox_inches="tight")
plt.show()