Lethe Open-Source Library: internalFunctionParserCustom::ParserImplementation< n_components > Class Template Reference
internalFunctionParserCustom::ParserImplementation< n_components > Class Template Reference
#include <mu_parser_internal.h>
Public Member Functions
ParserImplementation ()
virtual ~ParserImplementation ()=default
void initialize (const std::string &vars, const std::vector< std::string > &expressions, const std::map< std::string, double > &constants, const bool time_dependent=false)
void init_muparser () const
double do_value (const dealii::Tensor< 1, n_components > &p, const double time, unsigned int component) const
void do_all_values (const dealii::Tensor< 1, n_components > &p, const double time, dealii::ArrayView< double > &values) const
Public Attributes
std::vector< std::string > expressions
Private Attributes
dealii::Threads::ThreadLocalStorage< ::internalFunctionParserCustom::ParserData > parser_data
std::map< std::string, double > constants
std::vector< std::string > var_names
bool initialized
unsigned int n_vars
Detailed Description
template<int n_components>
class internalFunctionParserCustom::ParserImplementation< n_components >
Class that interfaces with muParser.
Template Parameters
n_components
Definition at line 210 of file mu_parser_internal.h.
Constructor & Destructor Documentation
ParserImplementation()
template<int n_components> internalFunctionParserCustom::ParserImplementation< n_components >::ParserImplementation
Definition at line 191 of file mu_parser_internal.cc.
~ParserImplementation()
template<int n_components> virtual internalFunctionParserCustom::ParserImplementation< n_components >::~ParserImplementation () virtual default
Member Function Documentation
do_all_values()
template<int n_components> void internalFunctionParserCustom::ParserImplementation< n_components >::do_all_values (const dealii::Tensor< 1, n_components > & p, const double time, dealii::ArrayView< double > & values) const
Evaluation of the function at a specific point for all components.
Parameters
[in] p Evaluation point
[in] time Current time
[out] values Output values
Definition at line 378 of file mu_parser_internal.cc.
References internalFunctionParserCustom::ParserData::parsers, and internalFunctionParserCustom::ParserData::vars.
do_value()
template<int n_components> double internalFunctionParserCustom::ParserImplementation< n_components >::do_value (const dealii::Tensor< 1, n_components > & p, const double time, unsigned int component) const
Evaluation of the function at a specific point.
Parameters
[in] p Evalution point
[in] time Current time
[in] component Component of interest
Returns
Value
Definition at line 337 of file mu_parser_internal.cc.
References internalFunctionParserCustom::ParserData::parsers, and internalFunctionParserCustom::ParserData::vars.
init_muparser()
template<int n_components> void internalFunctionParserCustom::ParserImplementation< n_components >::init_muparser
Actual initialization of the muParser object.
Definition at line 236 of file mu_parser_internal.cc.
References internalFunctionParserCustom::get_function_names(), internalFunctionParserCustom::mu_and(), internalFunctionParserCustom::mu_ceil(), internalFunctionParserCustom::mu_cot(), internalFunctionParserCustom::mu_csc(), internalFunctionParserCustom::mu_erfc(), internalFunctionParserCustom::mu_floor(), internalFunctionParserCustom::mu_if(), internalFunctionParserCustom::mu_int(), internalFunctionParserCustom::mu_log(), internalFunctionParserCustom::mu_or(), internalFunctionParserCustom::mu_pow(), internalFunctionParserCustom::mu_rand(), internalFunctionParserCustom::mu_rand_seed(), internalFunctionParserCustom::mu_sec(), internalFunctionParserCustom::ParserData::parsers, and internalFunctionParserCustom::ParserData::vars.
initialize()
template<int n_components> void internalFunctionParserCustom::ParserImplementation< n_components >::initialize (const std::string & vars, const std::vector< std::string > & expressions, const std::map< std::string, double > & constants, const bool time_dependent = false)
Treat the input and initialize the muParser object.
Parameters
[in] vars Variable names
[in] expressions Expressions
[in] constants Constants
[in] time_dependent Boolean to define if the function is time dependent
Definition at line 198 of file mu_parser_internal.cc.
Member Data Documentation
constants
template<int n_components> std::map<std::string, double> internalFunctionParserCustom::ParserImplementation< n_components >::constants private
Constants.
Definition at line 269 of file mu_parser_internal.h.
expressions
template<int n_components> std::vector<std::string> internalFunctionParserCustom::ParserImplementation< n_components >::expressions
Definition at line 260 of file mu_parser_internal.h.
initialized
template<int n_components> bool internalFunctionParserCustom::ParserImplementation< n_components >::initialized private
Keeps track if the muParser object is initialized.
Definition at line 275 of file mu_parser_internal.h.
n_vars
template<int n_components> unsigned int internalFunctionParserCustom::ParserImplementation< n_components >::n_vars private
Number of variables.
Definition at line 278 of file mu_parser_internal.h.
parser_data
template<int n_components> dealii::Threads::ThreadLocalStorage< ::internalFunctionParserCustom::ParserData> internalFunctionParserCustom::ParserImplementation< n_components >::parser_data mutable private
Thread safe object for using muParser.
Definition at line 266 of file mu_parser_internal.h.
var_names
template<int n_components> std::vector<std::string> internalFunctionParserCustom::ParserImplementation< n_components >::var_names private
Variable name.
Definition at line 272 of file mu_parser_internal.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/mu_parser_internal.h
/home/runner/work/lethe/lethe/source/core/mu_parser_internal.cc