Lethe Open-Source Library: CLSAlgebraicInterfaceReinitialization< dim > Class Template Reference
CLSAlgebraicInterfaceReinitialization< dim > Class Template Reference
#include <cls_algebraic_interface_reinitialization.h>
Public Member Functions
CLSAlgebraicInterfaceReinitialization (const SimulationParameters< dim > &p_simulation_parameters, const ConditionalOStream &p_pcout, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > &p_simulation_control, CLSSubequationsInterface< dim > &p_subequations_interface)
~CLSAlgebraicInterfaceReinitialization ()=default
void setup_dofs () override
void solve () override
GlobalVectorType & get_evaluation_point () override
GlobalVectorType & get_local_evaluation_point () override
GlobalVectorType & get_newton_update () override
GlobalVectorType & get_present_solution () override
GlobalVectorType & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
void output_newton_update_norms () override
double get_residual_rescale_metric () const override
Public Member Functions inherited from PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >
PhysicsNonlinearSubequationsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters, const ConditionalOStream &pcout)
virtual ~PhysicsNonlinearSubequationsSolver ()=default
void setup_preconditioner () override
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
PhysicsSolver ()
virtual ~PhysicsSolver ()
void solve_governing_system ()
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void write_output_results (const unsigned int step)
double compute_diffusivity (const double min_cell_size) const
double compute_time_step ()
void define_zero_constraints ()
void define_non_zero_constraints ()
void set_initial_conditions ()
void assemble_system_matrix () override
void assemble_system_rhs () override
void solve_linear_system () override
bool continue_iterating (const unsigned int step_number)
void check_dependencies_validity ()
Private Attributes
const CLSSubequationsID subequation_id
CLSSubequationsInterface< dim > & subequations_interface
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< SimulationControl > simulation_control
PVDHandler pvdhandler
double current_time_step
std::vector< double > time_step_vector = {0.0}
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< DoFHandler< dim > > dof_handler
std::shared_ptr< FiniteElement< dim > > fe
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType previous_local_evaluation_point
GlobalVectorType newton_update
std::shared_ptr< GlobalVectorType > present_solution
GlobalVectorType previous_solution
GlobalVectorType system_rhs
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
TrilinosWrappers::SparseMatrix system_matrix
const Parameters::Verbosity subequation_verbosity
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Protected Attributes inherited from PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >
const ConditionalOStream pcout
Detailed Description
template<int dim>
class CLSAlgebraicInterfaceReinitialization< dim >
CLS algebraic reinitialization solver.
Template Parameters
dim Number of dimensions of the problem.
Definition at line 34 of file cls_algebraic_interface_reinitialization.h.
Constructor & Destructor Documentation
CLSAlgebraicInterfaceReinitialization()
template<int dim> CLSAlgebraicInterfaceReinitialization< dim >::CLSAlgebraicInterfaceReinitialization (const SimulationParameters< dim > & p_simulation_parameters, const ConditionalOStream & p_pcout, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > & p_simulation_control, CLSSubequationsInterface< dim > & p_subequations_interface) inline
Constructor of the CLS algebraic interface reinitialization.
Parameters
[in] p_simulation_parameters Simulation parameters.
[in] p_pcout Parallel cout used to print the information.
[in] p_triangulation Distributed mesh information.
[in] p_simulation_control SimulationControl object.
[in,out] p_subequations_interface Subequations interface object used to get information from other subequations and store information from the current one.
Definition at line 53 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::cell_quadrature, CLSAlgebraicInterfaceReinitialization< dim >::fe, CLSAlgebraicInterfaceReinitialization< dim >::mapping, PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >::pcout, CLSAlgebraicInterfaceReinitialization< dim >::present_solution, CLSAlgebraicInterfaceReinitialization< dim >::simulation_control, and CLSAlgebraicInterfaceReinitialization< dim >::simulation_parameters.
~CLSAlgebraicInterfaceReinitialization()
template<int dim> CLSAlgebraicInterfaceReinitialization< dim >::~CLSAlgebraicInterfaceReinitialization () default
Default destructor.
Member Function Documentation
assemble_system_matrix()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::assemble_system_matrix () override private virtual
Assemble the matrix.
Implements PhysicsSolver< VectorType >.
Definition at line 203 of file cls_algebraic_interface_reinitialization.cc.
References algebraic_interface_reinitialization, Parameters::SimulationControl::bdf1, calculate_bdf_coefficients(), identify_minimum_cell_size(), and phase_gradient_projection.
assemble_system_rhs()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::assemble_system_rhs () override private virtual
Assemble the right-hand side (rhs).
Implements PhysicsSolver< VectorType >.
Definition at line 369 of file cls_algebraic_interface_reinitialization.cc.
References algebraic_interface_reinitialization, Parameters::SimulationControl::bdf1, calculate_bdf_coefficients(), identify_minimum_cell_size(), and phase_gradient_projection.
check_dependencies_validity()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::check_dependencies_validity () private
Check if the phase gradient and curvature L2 projections have been solved.
Definition at line 776 of file cls_algebraic_interface_reinitialization.cc.
References phase_gradient_projection.
compute_diffusivity()
template<int dim> double CLSAlgebraicInterfaceReinitialization< dim >::compute_diffusivity (const double min_cell_size) const inline private
Computes mesh-dependant diffusivity coefficient value.
Parameters
[in] min_cell_size Smallest cell's measure.
Returns
Constant diffusivity coefficient value for a given mesh.
Definition at line 244 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::simulation_parameters.
compute_time_step()
template<int dim> double CLSAlgebraicInterfaceReinitialization< dim >::compute_time_step () inline private
Computes algebraic reinitialization time step value with user-imposed CFL and minimum cell size.
Returns
Algebraic reinitialization time step.
Definition at line 264 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::cell_quadrature, CLSAlgebraicInterfaceReinitialization< dim >::compute_diffusivity(), CLSAlgebraicInterfaceReinitialization< dim >::dof_handler, identify_minimum_cell_size(), CLSAlgebraicInterfaceReinitialization< dim >::mapping, CLSAlgebraicInterfaceReinitialization< dim >::simulation_control, CLSAlgebraicInterfaceReinitialization< dim >::simulation_parameters, and CLSAlgebraicInterfaceReinitialization< dim >::triangulation.
continue_iterating()
template<int dim> bool CLSAlgebraicInterfaceReinitialization< dim >::continue_iterating (const unsigned int step_number) inline private
Indicate if the algebraic reinitialization should continue by checking if at least one of the two stop criteria (steady-state criterion or maximum number of reinitialization steps) is met.
Parameters
[in] step_number Algebraic interface reinitialization step number.
Returns
Boolean indicating if the algebraic reinitialization should continue
Definition at line 336 of file cls_algebraic_interface_reinitialization.h.
References Parameters::extra_verbose, CLSAlgebraicInterfaceReinitialization< dim >::local_evaluation_point, PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >::pcout, CLSAlgebraicInterfaceReinitialization< dim >::previous_local_evaluation_point, CLSAlgebraicInterfaceReinitialization< dim >::simulation_parameters, and CLSAlgebraicInterfaceReinitialization< dim >::subequation_verbosity.
define_non_zero_constraints()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::define_non_zero_constraints () private
Define the non zero constraints used to solve the problem.
Definition at line 128 of file cls_algebraic_interface_reinitialization.cc.
References BoundaryConditions::cls_dirichlet, and BoundaryConditions::periodic.
define_zero_constraints()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::define_zero_constraints () private
Define the zero constraints used to solve the problem.
Definition at line 86 of file cls_algebraic_interface_reinitialization.cc.
References BoundaryConditions::cls_dirichlet, and BoundaryConditions::periodic.
get_evaluation_point()
template<int dim> GlobalVectorType & CLSAlgebraicInterfaceReinitialization< dim >::get_evaluation_point () inline override virtual
Getter method to access the private attribute evaluation_point for the subequation currently solved.
Returns
The vector in which the evaluation is performed.
Implements PhysicsSolver< VectorType >.
Definition at line 125 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> GlobalVectorType & CLSAlgebraicInterfaceReinitialization< dim >::get_local_evaluation_point () inline override virtual
Getter method to access the private attribute local_evaluation_point for the subequation currently solved.
Returns
The local evaluation point. Ghosts cells are not considered in this evaluation.
Implements PhysicsSolver< VectorType >.
Definition at line 138 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::local_evaluation_point.
get_newton_update()
template<int dim> GlobalVectorType & CLSAlgebraicInterfaceReinitialization< dim >::get_newton_update () inline override virtual
Getter method to access the private attribute newton_update for the subequation currently solved.
Returns
The direction used to perform the newton iteration.
Implements PhysicsSolver< VectorType >.
Definition at line 150 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints< double > & CLSAlgebraicInterfaceReinitialization< dim >::get_nonzero_constraints () inline override virtual
Getter method to access the private attribute nonzero_constraints for the subequation currently solved.
Returns
Container of nonzero constraints that arise from several sources such as boundary conditions and hanging nodes in the mesh. See the deal.II documentation on constraints on degrees of freedom for more information.
Implements PhysicsSolver< VectorType >.
Definition at line 188 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::nonzero_constraints.
get_present_solution()
template<int dim> GlobalVectorType & CLSAlgebraicInterfaceReinitialization< dim >::get_present_solution () inline override virtual
Getter method to access the private attribute present_solution for the subequation currently solved.
Returns
Vector containing all the values of the solution.
Implements PhysicsSolver< VectorType >.
Definition at line 162 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::present_solution.
get_residual_rescale_metric()
template<int dim> double CLSAlgebraicInterfaceReinitialization< dim >::get_residual_rescale_metric () const inline override virtual
Return the metric for residual rescaling. By default, should return 1. If the rescale_residual_by_volume is set to true, the method returns the square root of the global volume of the triangulation.
Returns
Rescale metric.
Implements PhysicsSolver< VectorType >.
Definition at line 214 of file cls_algebraic_interface_reinitialization.h.
References CLS, CLSAlgebraicInterfaceReinitialization< dim >::mapping, CLSAlgebraicInterfaceReinitialization< dim >::simulation_parameters, and CLSAlgebraicInterfaceReinitialization< dim >::triangulation.
get_system_rhs()
template<int dim> GlobalVectorType & CLSAlgebraicInterfaceReinitialization< dim >::get_system_rhs () inline override virtual
Getter method to access the private attribute system_rhs for the subequation currently solved.
Returns
Right-hand side vector.
Implements PhysicsSolver< VectorType >.
Definition at line 174 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::system_rhs.
output_newton_update_norms()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::output_newton_update_norms () inline override virtual
Output the \(L_2\) and \(L_\infty\) norms of the correction vector.
Implements PhysicsSolver< VectorType >.
Definition at line 198 of file cls_algebraic_interface_reinitialization.h.
References CLSAlgebraicInterfaceReinitialization< dim >::newton_update, and PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >::pcout.
set_initial_conditions()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::set_initial_conditions () private
Sets-up the initial conditions associated with the subequation.
Definition at line 171 of file cls_algebraic_interface_reinitialization.cc.
setup_dofs()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::setup_dofs () override virtual
Set up the DofHandler and the degree of freedom associated with the subequation.
Implements PhysicsSubequationsSolverBase.
Definition at line 16 of file cls_algebraic_interface_reinitialization.cc.
References Parameters::quiet.
solve()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::solve () override virtual
Solve interface algebraic reinitialization process until one of the stop criteria is met.
Implements PhysicsSubequationsSolverBase.
Definition at line 642 of file cls_algebraic_interface_reinitialization.cc.
References algebraic_interface_reinitialization, announce_string(), and Parameters::quiet.
solve_linear_system()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::solve_linear_system () override private virtual
Solve the linear system.
Implements PhysicsSolver< VectorType >.
Definition at line 548 of file cls_algebraic_interface_reinitialization.cc.
References algebraic_interface_reinitialization, and Parameters::quiet.
write_output_results()
template<int dim> void CLSAlgebraicInterfaceReinitialization< dim >::write_output_results (const unsigned int step) private
Write parallel VTU files of quantities of interest for the algebraic interface reinitialization process.
Parameters
[in] step Integer indicating the reinitialization step number.
Note
Only the reinitialization steps of the last global time step (simulation time step) ran are outputted.
Definition at line 718 of file cls_algebraic_interface_reinitialization.cc.
References phase_gradient_projection.
Member Data Documentation
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > CLSAlgebraicInterfaceReinitialization< dim >::cell_quadrature private
Definition at line 415 of file cls_algebraic_interface_reinitialization.h.
current_time_step
template<int dim> double CLSAlgebraicInterfaceReinitialization< dim >::current_time_step private
Definition at line 405 of file cls_algebraic_interface_reinitialization.h.
dof_handler
template<int dim> std::shared_ptr<DoFHandler<dim> > CLSAlgebraicInterfaceReinitialization< dim >::dof_handler private
Definition at line 410 of file cls_algebraic_interface_reinitialization.h.
evaluation_point
template<int dim> GlobalVectorType CLSAlgebraicInterfaceReinitialization< dim >::evaluation_point private
Definition at line 420 of file cls_algebraic_interface_reinitialization.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > CLSAlgebraicInterfaceReinitialization< dim >::fe private
Definition at line 411 of file cls_algebraic_interface_reinitialization.h.
local_evaluation_point
template<int dim> GlobalVectorType CLSAlgebraicInterfaceReinitialization< dim >::local_evaluation_point private
Definition at line 421 of file cls_algebraic_interface_reinitialization.h.
locally_owned_dofs
template<int dim> IndexSet CLSAlgebraicInterfaceReinitialization< dim >::locally_owned_dofs private
Definition at line 418 of file cls_algebraic_interface_reinitialization.h.
locally_relevant_dofs
template<int dim> IndexSet CLSAlgebraicInterfaceReinitialization< dim >::locally_relevant_dofs private
Definition at line 419 of file cls_algebraic_interface_reinitialization.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > CLSAlgebraicInterfaceReinitialization< dim >::mapping private
Definition at line 414 of file cls_algebraic_interface_reinitialization.h.
newton_update
template<int dim> GlobalVectorType CLSAlgebraicInterfaceReinitialization< dim >::newton_update private
Definition at line 423 of file cls_algebraic_interface_reinitialization.h.
nonzero_constraints
template<int dim> AffineConstraints<double> CLSAlgebraicInterfaceReinitialization< dim >::nonzero_constraints private
Definition at line 428 of file cls_algebraic_interface_reinitialization.h.
present_solution
template<int dim> std::shared_ptr<GlobalVectorType> CLSAlgebraicInterfaceReinitialization< dim >::present_solution private
Definition at line 424 of file cls_algebraic_interface_reinitialization.h.
previous_local_evaluation_point
template<int dim> GlobalVectorType CLSAlgebraicInterfaceReinitialization< dim >::previous_local_evaluation_point private
Definition at line 422 of file cls_algebraic_interface_reinitialization.h.
previous_solution
template<int dim> GlobalVectorType CLSAlgebraicInterfaceReinitialization< dim >::previous_solution private
Definition at line 425 of file cls_algebraic_interface_reinitialization.h.
pvdhandler
template<int dim> PVDHandler CLSAlgebraicInterfaceReinitialization< dim >::pvdhandler private
Definition at line 402 of file cls_algebraic_interface_reinitialization.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> CLSAlgebraicInterfaceReinitialization< dim >::simulation_control private
Definition at line 399 of file cls_algebraic_interface_reinitialization.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& CLSAlgebraicInterfaceReinitialization< dim >::simulation_parameters private
Definition at line 396 of file cls_algebraic_interface_reinitialization.h.
subequation_id
template<int dim> const CLSSubequationsID CLSAlgebraicInterfaceReinitialization< dim >::subequation_id private
Definition at line 392 of file cls_algebraic_interface_reinitialization.h.
subequation_verbosity
template<int dim> const Parameters::Verbosity CLSAlgebraicInterfaceReinitialization< dim >::subequation_verbosity private
Definition at line 432 of file cls_algebraic_interface_reinitialization.h.
subequations_interface
template<int dim> CLSSubequationsInterface<dim>& CLSAlgebraicInterfaceReinitialization< dim >::subequations_interface private
Definition at line 393 of file cls_algebraic_interface_reinitialization.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix CLSAlgebraicInterfaceReinitialization< dim >::system_matrix private
Definition at line 429 of file cls_algebraic_interface_reinitialization.h.
system_rhs
template<int dim> GlobalVectorType CLSAlgebraicInterfaceReinitialization< dim >::system_rhs private
Definition at line 426 of file cls_algebraic_interface_reinitialization.h.
time_step_vector
template<int dim> std::vector<double> CLSAlgebraicInterfaceReinitialization< dim >::time_step_vector = {0.0} private
Definition at line 406 of file cls_algebraic_interface_reinitialization.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > CLSAlgebraicInterfaceReinitialization< dim >::triangulation private
Definition at line 409 of file cls_algebraic_interface_reinitialization.h.
zero_constraints
template<int dim> AffineConstraints<double> CLSAlgebraicInterfaceReinitialization< dim >::zero_constraints private
Definition at line 427 of file cls_algebraic_interface_reinitialization.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/cls_algebraic_interface_reinitialization.h
/home/runner/work/lethe/lethe/source/solvers/cls_algebraic_interface_reinitialization.cc