Lethe Open-Source Library: MultiphysicsInterface< dim > Class Template Reference
MultiphysicsInterface< dim > Class Template Reference
#include <multiphysics_interface.h>
Public Member Functions
MultiphysicsInterface (const SimulationParameters< dim > &nsparam, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control, ConditionalOStream &p_pcout)
virtual ~MultiphysicsInterface ()=default
std::vector< PhysicsID > get_active_physics ()
void announce_physics (const PhysicsID physics_id)
void solve (const bool fluid_dynamics_has_been_solved, const Parameters::SimulationControl::TimeSteppingMethod time_stepping_method)
void solve_physics (const PhysicsID physics_id, const Parameters::SimulationControl::TimeSteppingMethod time_stepping_method)
void solve_block_physics (const PhysicsID physics_id, const Parameters::SimulationControl::TimeSteppingMethod time_stepping_method)
std::vector< OutputStruct< dim, GlobalVectorType > > gather_output_hook_global_vector ()
std::vector< OutputStruct< dim, GlobalBlockVectorType > > gather_output_hook_global_block_vector ()
void finish_simulation ()
void percolate_time_vectors (const bool fluid_dynamics_has_been_solved)
void update_boundary_conditions ()
void postprocess (bool first_iteration)
void prepare_for_mesh_adaptation ()
void post_mesh_adaptation ()
void setup_dofs ()
void set_initial_conditions ()
void solve_linear_system (const PhysicsID physics_id)
bool fluid_dynamics_is_block () const
const DoFHandler< dim > & get_dof_handler (const PhysicsID physics_id)
const GlobalVectorType & get_solution (const PhysicsID physics_id)
const GlobalVectorType & get_filtered_solution (const PhysicsID physics_id)
const GlobalBlockVectorType & get_block_solution (const PhysicsID physics_id)
const GlobalVectorType & get_time_average_solution (const PhysicsID physics_id)
const GlobalBlockVectorType & get_block_time_average_solution (const PhysicsID physics_id)
const std::vector< std::shared_ptr< SolidBase< dim, dim > > > & get_solids (const int number_solids)
const GlobalVectorType & get_projected_phase_fraction_gradient_solution ()
const GlobalVectorType & get_curvature_solution ()
const DoFHandler< dim > & get_curvature_dof_handler ()
const DoFHandler< dim > & get_projected_phase_fraction_gradient_dof_handler ()
std::shared_ptr< Shape< dim > > get_immersed_solid_shape ()
void set_immersed_solid_shape (const std::shared_ptr< Shape< dim > > &shape)
const std::vector< GlobalVectorType > & get_previous_solutions (const PhysicsID physics_id)
const std::vector< GlobalBlockVectorType > & get_block_previous_solutions (const PhysicsID physics_id)
void set_dof_handler (const PhysicsID physics_id, std::shared_ptr< DoFHandler< dim > > dof_handler)
void set_solid (std::shared_ptr< std::vector< std::shared_ptr< SolidBase< dim, dim > > > > solids_input)
void set_solution (const PhysicsID physics_id, std::shared_ptr< GlobalVectorType > solution_vector)
void set_filtered_solution (const PhysicsID physics_id, std::shared_ptr< GlobalVectorType > filtered_solution_vector)
void set_time_average_solution (const PhysicsID physics_id, std::shared_ptr< GlobalVectorType > solution_vector)
void set_block_solution (const PhysicsID physics_id, std::shared_ptr< GlobalBlockVectorType > solution_vector)
void set_block_time_average_solution (const PhysicsID physics_id, std::shared_ptr< GlobalBlockVectorType > solution_vector)
void set_previous_solutions (const PhysicsID physics_id, std::shared_ptr< std::vector< GlobalVectorType > > previous_solutions_vector)
void set_block_previous_solutions (const PhysicsID physics_id, std::shared_ptr< std::vector< GlobalBlockVectorType > > previous_solutions_vector)
virtual void compute_kelly (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > &ivar, dealii::Vector< float > &estimated_error_per_cell)
virtual void write_checkpoint ()
virtual void read_checkpoint ()
Private Member Functions
void inspect_multiphysics_models_dependencies (const SimulationParameters< dim > &nsparam)
Private Attributes
const Parameters::Multiphysics multiphysics_parameters
std::map< PhysicsID, Parameters::Verbosity > verbosity
ConditionalOStream pcout
std::vector< PhysicsID > active_physics
std::map< PhysicsID, bool > solve_pre_fluid
std::map< PhysicsID, std::shared_ptr< AuxiliaryPhysics< dim, GlobalVectorType > > > physics
std::map< PhysicsID, std::shared_ptr< AuxiliaryPhysics< dim, GlobalBlockVectorType > > > block_physics
std::map< PhysicsID, std::shared_ptr< DoFHandler< dim > > > physics_dof_handler
std::shared_ptr< std::vector< std::shared_ptr< SolidBase< dim, dim > > > > solids
std::map< PhysicsID, std::shared_ptr< GlobalVectorType > > physics_solutions
std::map< PhysicsID, std::shared_ptr< GlobalBlockVectorType > > block_physics_solutions
std::map< PhysicsID, std::shared_ptr< GlobalVectorType > > physics_filtered_solutions
std::map< PhysicsID, std::shared_ptr< GlobalVectorType > > block_physics_filtered_solutions
std::map< PhysicsID, std::shared_ptr< std::vector< GlobalVectorType > > > physics_previous_solutions
std::map< PhysicsID, std::shared_ptr< std::vector< GlobalBlockVectorType > > > block_physics_previous_solutions
std::map< PhysicsID, std::shared_ptr< GlobalVectorType > > physics_time_average_solutions
std::map< PhysicsID, std::shared_ptr< GlobalBlockVectorType > > block_physics_time_average_solutions
std::shared_ptr< Shape< dim > > immersed_solid_shape
std::map< PhysicsID, std::shared_ptr< GlobalVectorType > > physics_solutions_m1
std::map< PhysicsID, std::shared_ptr< GlobalBlockVectorType > > block_physics_solutions_m1
Detailed Description
template<int dim>
class MultiphysicsInterface< dim >
Definition at line 36 of file multiphysics_interface.h.
Constructor & Destructor Documentation
MultiphysicsInterface()
template<int dim> MultiphysicsInterface< dim >::MultiphysicsInterface (const SimulationParameters< dim > & nsparam, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control, ConditionalOStream & p_pcout)
Construct the Multiphysics interface from the simulation parameters. Depending on which multiphysics element is enabled, the appropriate auxiliary physics is instantiated.
Definition at line 70 of file multiphysics_interface.cc.
References MultiphysicsInterface< dim >::active_physics, cahn_hilliard, Parameters::Multiphysics::cahn_hilliard, fluid_dynamics, heat_transfer, Parameters::Multiphysics::heat_transfer, MultiphysicsInterface< dim >::inspect_multiphysics_models_dependencies(), SimulationParameters< dim >::linear_solver, MultiphysicsInterface< dim >::multiphysics_parameters, MultiphysicsInterface< dim >::physics, SimulationParameters< dim >::physics_solving_strategy, Parameters::quiet, tracer, Parameters::Multiphysics::tracer, Parameters::verbose, MultiphysicsInterface< dim >::verbosity, VOF, and Parameters::Multiphysics::VOF.
~MultiphysicsInterface()
template<int dim> virtual MultiphysicsInterface< dim >::~MultiphysicsInterface () virtual default
Default destructor.
Member Function Documentation
announce_physics()
template<int dim> void MultiphysicsInterface< dim >::announce_physics (const PhysicsID physics_id) inline
Write physic solved in the terminal.
Parameters
physics_id number associated with auxiliary physics in multiphysics.h
Definition at line 68 of file multiphysics_interface.h.
References announce_string(), cahn_hilliard, heat_transfer, MultiphysicsInterface< dim >::pcout, tracer, and VOF.
compute_kelly()
template<int dim> virtual void MultiphysicsInterface< dim >::compute_kelly (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > & ivar, dealii::Vector< float > & estimated_error_per_cell) inline virtual
Mesh refinement according to an auxiliary physic parameter.
Parameters
ivar The current element of the map simulation_parameters.mesh_adaptation.variables
estimated_error_per_cell The deal.II vector of estimated_error_per_cell
Definition at line 812 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
finish_simulation()
template<int dim> void MultiphysicsInterface< dim >::finish_simulation () inline
Carry out the operations required to finish a simulation correctly for all auxiliary physics.
Definition at line 229 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
fluid_dynamics_is_block()
template<int dim> bool MultiphysicsInterface< dim >::fluid_dynamics_is_block () const inline
fluid_dynamics_is_block Verify if the fluid dynamics solution is stored as a block vector or not.
Returns
boolean value indicating the fluid dynamics is stored as a block vector
Definition at line 415 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics_solutions, and fluid_dynamics.
gather_output_hook_global_block_vector()
template<int dim> std::vector< OutputStruct< dim, GlobalBlockVectorType > > MultiphysicsInterface< dim >::gather_output_hook_global_block_vector () inline
Gather and return vector of output structs that are particular to some applications.
Returns
Vector of OutputStructs that will be used to write the output results as VTU files. This is a variant for GlobalBlockVectorType.
Definition at line 209 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics.
gather_output_hook_global_vector()
template<int dim> std::vector< OutputStruct< dim, GlobalVectorType > > MultiphysicsInterface< dim >::gather_output_hook_global_vector () inline
Gather and return vector of output structs that are particular to some applications.
Returns
Vector of OutputStructs that will be used to write the output results as VTU files. This is a variant for GlobalVectorType.
Definition at line 189 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::physics.
get_active_physics()
template<int dim> std::vector< PhysicsID > MultiphysicsInterface< dim >::get_active_physics () inline
Definition at line 57 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics.
get_block_previous_solutions()
template<int dim> const std::vector< GlobalBlockVectorType > & MultiphysicsInterface< dim >::get_block_previous_solutions (const PhysicsID physics_id) inline
Request the reference to the vector of previous solutions of a given block physics.
Parameters
[in] physics_id The physics ID of the solution being requested
Definition at line 613 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::block_physics_previous_solutions.
get_block_solution()
template<int dim> const GlobalBlockVectorType & MultiphysicsInterface< dim >::get_block_solution (const PhysicsID physics_id) inline
Request the reference to the present block solution of a given physics.
Parameters
[in] physics_id The physics ID of the solution being requested
Definition at line 485 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::block_physics_solutions.
get_block_time_average_solution()
template<int dim> const GlobalBlockVectorType & MultiphysicsInterface< dim >::get_block_time_average_solution (const PhysicsID physics_id) inline
Request the reference to the present block average solution of a given physics.
Parameters
[in] physics_id The physics ID of the solution being requested
Definition at line 517 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::block_physics_time_average_solutions.
get_curvature_dof_handler()
template<int dim> const DoFHandler< dim > & MultiphysicsInterface< dim >::get_curvature_dof_handler ()
Request the reference to the projected curvature DOF handler.
Definition at line 178 of file multiphysics_interface.cc.
References VOF.
get_curvature_solution()
template<int dim> const GlobalVectorType & MultiphysicsInterface< dim >::get_curvature_solution ()
Request the reference to the present solution of the curvature.
Definition at line 161 of file multiphysics_interface.cc.
References VOF.
get_dof_handler()
template<int dim> const DoFHandler< dim > & MultiphysicsInterface< dim >::get_dof_handler (const PhysicsID physics_id) inline
Request a DOF handler for a given physics ID.
Parameters
physics_id The physics of the DOF handler being requested
Returns
Reference to the DOF handler of the requested physics
Definition at line 431 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_dof_handler.
get_filtered_solution()
template<int dim> const GlobalVectorType & MultiphysicsInterface< dim >::get_filtered_solution (const PhysicsID physics_id) inline
Request the reference to the present filtered solution of a given physics (used in VOF or CahnHilliard physics for STF calculation in the momentum balance)
Parameters
[in] physics_id ID of the physics for which the filtered solution is being requested
Returns
Reference to the requested filtered solution vector.
Definition at line 469 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_filtered_solutions.
get_immersed_solid_shape()
template<int dim> std::shared_ptr< Shape< dim > > MultiphysicsInterface< dim >::get_immersed_solid_shape ()
Request shared pointer to immersed solid shape.
Definition at line 212 of file multiphysics_interface.cc.
get_previous_solutions()
template<int dim> const std::vector< GlobalVectorType > & MultiphysicsInterface< dim >::get_previous_solutions (const PhysicsID physics_id) inline
Request the reference to the vector of previous solutions of a given physics.
Parameters
[in] physics_id The physics ID of the solution being requested
Definition at line 596 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_previous_solutions.
get_projected_phase_fraction_gradient_dof_handler()
template<int dim> const DoFHandler< dim > & MultiphysicsInterface< dim >::get_projected_phase_fraction_gradient_dof_handler ()
Request the reference to the projected phase fraction gradient (PFG) DOF handler.
Definition at line 195 of file multiphysics_interface.cc.
References VOF.
get_projected_phase_fraction_gradient_solution()
template<int dim> const GlobalVectorType & MultiphysicsInterface< dim >::get_projected_phase_fraction_gradient_solution ()
Request the reference to the present solution vector of the projected phase fraction gradient (PFG)
Definition at line 144 of file multiphysics_interface.cc.
References VOF.
get_solids()
template<int dim> const std::vector< std::shared_ptr< SolidBase< dim, dim > > > & MultiphysicsInterface< dim >::get_solids (const int number_solids) inline
Request the solid objects. Used an auxiliary physics needs to apply a boundary condition on a solid through Nitsche immersed boundary method.
Parameters
[in] number_solids The number of solids declared in the parameter file. The value is used to ensure that at least one solid has been declared.
Note
The method is called only in HeatTransfer<dim>::assemble_nitsche_heat_restriction, which is itself called only if number_solids > 0
Definition at line 540 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::solids.
get_solution()
template<int dim> const GlobalVectorType & MultiphysicsInterface< dim >::get_solution (const PhysicsID physics_id) inline
Request the reference to the present solution of a given physics.
Parameters
physics_id The physics ID of the solution being requested
Returns
Reference to the solution vector of the requested physics
Definition at line 449 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_solutions.
get_time_average_solution()
template<int dim> const GlobalVectorType & MultiphysicsInterface< dim >::get_time_average_solution (const PhysicsID physics_id) inline
Request the reference to the time-average solution of a given physics.
Parameters
[in] physics_id The physics ID of the solution being requested
Definition at line 501 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_time_average_solutions.
inspect_multiphysics_models_dependencies()
template<int dim> void MultiphysicsInterface< dim >::inspect_multiphysics_models_dependencies (const SimulationParameters< dim > & nsparam) private
Definition at line 229 of file multiphysics_interface.cc.
References _unused, Parameters::Multiphysics::buoyancy_force, Parameters::VOF_InterfaceSharpening::enable, Parameters::VOF_SurfaceTensionForce::enable, Parameters::VOF_SurfaceTensionForce::enable_marangoni_effect, Parameters::Multiphysics::fluid_dynamics, Parameters::Multiphysics::heat_transfer, SimulationParameters< dim >::multiphysics, Parameters::VOF::regularization_method, Parameters::VOF_RegularizationMethod::sharpening, Parameters::VOF::surface_tension_force, Parameters::Multiphysics::VOF, and Parameters::Multiphysics::vof_parameters.
percolate_time_vectors()
template<int dim> void MultiphysicsInterface< dim >::percolate_time_vectors (const bool fluid_dynamics_has_been_solved) inline
Rearrange vector solution correctly for transient simulations for all auxiliary physics.
Parameters
fluid_dynamics_has_been_solved Boolean that states if the fluid dynamics has been already solved or not. See the map solve_pre_fluid to know which subphysics are solved before the fluid dynamics.
Definition at line 250 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, MultiphysicsInterface< dim >::physics, and MultiphysicsInterface< dim >::solve_pre_fluid.
post_mesh_adaptation()
template<int dim> void MultiphysicsInterface< dim >::post_mesh_adaptation () inline
Interpolate solution onto new mesh.
Definition at line 341 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
postprocess()
template<int dim> void MultiphysicsInterface< dim >::postprocess (bool first_iteration) inline
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
Definition at line 308 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
prepare_for_mesh_adaptation()
template<int dim> void MultiphysicsInterface< dim >::prepare_for_mesh_adaptation () inline
Prepare the auxiliary physics for mesh adaptation.
Definition at line 325 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
read_checkpoint()
template<int dim> virtual void MultiphysicsInterface< dim >::read_checkpoint () inline virtual
Read solution from checkpoint from auxiliary physics.
Definition at line 847 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
set_block_previous_solutions()
template<int dim> void MultiphysicsInterface< dim >::set_block_previous_solutions (const PhysicsID physics_id, std::shared_ptr< std::vector< GlobalBlockVectorType > > previous_solutions_vector) inline
Sets the pointer to the vector of previous solutions of the block physics in the multiphysics interface.
Parameters
[in] physics_id The physics of the DOF handler
[in] previous_solutions_vector The shared pointer to the vector of previous block vector solutions
Definition at line 792 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::block_physics_previous_solutions.
set_block_solution()
template<int dim> void MultiphysicsInterface< dim >::set_block_solution (const PhysicsID physics_id, std::shared_ptr< GlobalBlockVectorType > solution_vector) inline
Sets the reference to the solution of the physics in the multiphysics interface.
Parameters
[in] physics_id The physics ID of the DOF handler being requested
[in] solution_vector The shared pointer to the solution vector of the requested physics
Definition at line 730 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::block_physics_solutions.
set_block_time_average_solution()
template<int dim> void MultiphysicsInterface< dim >::set_block_time_average_solution (const PhysicsID physics_id, std::shared_ptr< GlobalBlockVectorType > solution_vector) inline
Sets the shared pointer to the time-average solution of the block physics in the multiphysics interface.
Parameters
[in] physics_id The physics ID of the time averaged block vector solution being set
[in] solution_vector The shared pointer to the block solution vector of the physics
Definition at line 751 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::block_physics_time_average_solutions.
set_dof_handler()
template<int dim> void MultiphysicsInterface< dim >::set_dof_handler (const PhysicsID physics_id, std::shared_ptr< DoFHandler< dim > > dof_handler) inline
Sets the shared pointer to the DOFHandler of the physics in the multiphysics interface.
Parameters
[in] physics_id The physics of the DOF handler being requested
[in] dof_handler Shared pointer to the dof handler for which the reference is stored
Definition at line 632 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_dof_handler.
set_filtered_solution()
template<int dim> void MultiphysicsInterface< dim >::set_filtered_solution (const PhysicsID physics_id, std::shared_ptr< GlobalVectorType > filtered_solution_vector) inline
Sets the shared pointer to the filtered solution of the physics in the multiphysics interface (used in VOF or CahnHilliard physics for STF calculation in the momentum balance)
Parameters
[in] physics_id ID of the physics for which the filtered solution is being set
[in] filtered_solution_vector Shared pointer to the filtered solution vector of the physics; this was implemented for VOF and CahnHilliard physics
Definition at line 689 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_filtered_solutions.
set_immersed_solid_shape()
template<int dim> void MultiphysicsInterface< dim >::set_immersed_solid_shape (const std::shared_ptr< Shape< dim > > & shape)
Share immersed solid shape.
Parameters
[in] shape The reference to the shared pointer pointing to the immersed solid shape
Definition at line 221 of file multiphysics_interface.cc.
set_initial_conditions()
template<int dim> void MultiphysicsInterface< dim >::set_initial_conditions () inline
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionally support the use of L2 projection or steady-state solutions.
Definition at line 379 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
set_previous_solutions()
template<int dim> void MultiphysicsInterface< dim >::set_previous_solutions (const PhysicsID physics_id, std::shared_ptr< std::vector< GlobalVectorType > > previous_solutions_vector) inline
Sets the pointer to the vector of previous solutions of the physics in the multiphysics interface.
Parameters
[in] physics_id The physics of the DOF handler
[in] previous_solutions_vector The shared pointer to the vector of previous solutions
Definition at line 771 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_previous_solutions.
set_solid()
template<int dim> void MultiphysicsInterface< dim >::set_solid (std::shared_ptr< std::vector< std::shared_ptr< SolidBase< dim, dim > > > > solids_input) inline
Sets the shared pointer to the vector of the SolidBase object. This allows the use of the solid base object in multiple physics at the same time.
Parameters
[in] solids_input Shared pointer to the vector of solidBase object
Definition at line 650 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::solids.
set_solution()
template<int dim> void MultiphysicsInterface< dim >::set_solution (const PhysicsID physics_id, std::shared_ptr< GlobalVectorType > solution_vector) inline
Sets the shared pointer to the solution of the physics in the multiphysics interface.
Parameters
[in] physics_id The physics ID the present solution being set
[in] solution_vector Shared pointer to the solution vector of the physics
Definition at line 666 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_solutions.
set_time_average_solution()
template<int dim> void MultiphysicsInterface< dim >::set_time_average_solution (const PhysicsID physics_id, std::shared_ptr< GlobalVectorType > solution_vector) inline
Sets the shared pointer to the time-average solution of the physics in the multiphysics interface.
Parameters
[in] physics_id The physics ID of the time averaged solution being set
[in] solution_vector The shared pointer to the time averaged solution vector of the physics
Definition at line 711 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics_time_average_solutions.
setup_dofs()
template<int dim> void MultiphysicsInterface< dim >::setup_dofs () inline
Set-up the DofHandler and the degree of freedom associated with the physics.
Definition at line 359 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
solve()
template<int dim> void MultiphysicsInterface< dim >::solve (const bool fluid_dynamics_has_been_solved, const Parameters::SimulationControl::TimeSteppingMethod time_stepping_method) inline
Call for the solution of the physics that should be solved.
Parameters
fluid_dynamics_has_been_solved Boolean that states if the fluid dynamics has been already solved or not. See the map solve_pre_fluid to know which subphysics are solved before the fluid dynamics.
time_stepping_method Time-Stepping method with which the assembly is called
Definition at line 98 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, MultiphysicsInterface< dim >::physics, MultiphysicsInterface< dim >::solve_block_physics(), MultiphysicsInterface< dim >::solve_physics(), and MultiphysicsInterface< dim >::solve_pre_fluid.
solve_block_physics()
template<int dim> void MultiphysicsInterface< dim >::solve_block_physics (const PhysicsID physics_id, const Parameters::SimulationControl::TimeSteppingMethod time_stepping_method) inline
Call for the solution of a single block physic.
Parameters
time_stepping_method Time-Stepping method with which the assembly is called
Definition at line 165 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, MultiphysicsInterface< dim >::announce_physics(), MultiphysicsInterface< dim >::block_physics, Parameters::quiet, and MultiphysicsInterface< dim >::verbosity.
solve_linear_system()
template<int dim> void MultiphysicsInterface< dim >::solve_linear_system (const PhysicsID physics_id) inline
Call for the solution of the linear system of an auxiliary physics.
Definition at line 397 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, and MultiphysicsInterface< dim >::physics.
solve_physics()
template<int dim> void MultiphysicsInterface< dim >::solve_physics (const PhysicsID physics_id, const Parameters::SimulationControl::TimeSteppingMethod time_stepping_method) inline
Call for the solution of a single physic.
Parameters
time_stepping_method Time-Stepping method with which the assembly is called
Definition at line 141 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::active_physics, MultiphysicsInterface< dim >::announce_physics(), MultiphysicsInterface< dim >::physics, Parameters::quiet, and MultiphysicsInterface< dim >::verbosity.
update_boundary_conditions()
template<int dim> void MultiphysicsInterface< dim >::update_boundary_conditions () inline
Parameters
Update the boundary conditions of the auxiliary physics if they are time-dependent
Definition at line 288 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
write_checkpoint()
template<int dim> virtual void MultiphysicsInterface< dim >::write_checkpoint () inline virtual
Prepares auxiliary physics to write simulation checkpoint.
Definition at line 830 of file multiphysics_interface.h.
References MultiphysicsInterface< dim >::block_physics, and MultiphysicsInterface< dim >::physics.
Member Data Documentation
active_physics
template<int dim> std::vector<PhysicsID> MultiphysicsInterface< dim >::active_physics private
Definition at line 865 of file multiphysics_interface.h.
block_physics
template<int dim> std::map<PhysicsID, std::shared_ptr<AuxiliaryPhysics<dim, GlobalBlockVectorType> > > MultiphysicsInterface< dim >::block_physics private
Definition at line 882 of file multiphysics_interface.h.
block_physics_filtered_solutions
template<int dim> std::map<PhysicsID, std::shared_ptr<GlobalVectorType> > MultiphysicsInterface< dim >::block_physics_filtered_solutions private
Map of physics and shared pointers to their respective filtered solutions. Same as MultiphysicsInterface::physics_filtered_solutions, but used with BlockVector.
Definition at line 915 of file multiphysics_interface.h.
block_physics_previous_solutions
template<int dim> std::map<PhysicsID, std::shared_ptr<std::vector<GlobalBlockVectorType> > > MultiphysicsInterface< dim >::block_physics_previous_solutions private
Map of physics and shared pointers to their respective vector of previous solutions. Same as MultiphysicsInterface::physics_previous_solutions, but used with BlockVector.
Definition at line 931 of file multiphysics_interface.h.
block_physics_solutions
template<int dim> std::map<PhysicsID, std::shared_ptr<GlobalBlockVectorType> > MultiphysicsInterface< dim >::block_physics_solutions private
Map of physics and shared pointers to their respective solutions. Same as MultiphysicsInterface::physics_solutions, but used with BlockVector.
Definition at line 899 of file multiphysics_interface.h.
block_physics_solutions_m1
template<int dim> std::map<PhysicsID, std::shared_ptr<GlobalBlockVectorType> > MultiphysicsInterface< dim >::block_physics_solutions_m1 private
Definition at line 958 of file multiphysics_interface.h.
block_physics_time_average_solutions
template<int dim> std::map<PhysicsID, std::shared_ptr<GlobalBlockVectorType> > MultiphysicsInterface< dim >::block_physics_time_average_solutions private
Map of physics and shared pointers to their respective time-averaged solutions. Same as MultiphysicsInterface::physics_time_average_solutions, but used with BlockVector.
Definition at line 947 of file multiphysics_interface.h.
immersed_solid_shape
template<int dim> std::shared_ptr<Shape<dim> > MultiphysicsInterface< dim >::immersed_solid_shape private
Shared pointer to immersed solid shapes to be used by auxiliary physics.
Definition at line 950 of file multiphysics_interface.h.
multiphysics_parameters
template<int dim> const Parameters::Multiphysics MultiphysicsInterface< dim >::multiphysics_parameters private
Definition at line 860 of file multiphysics_interface.h.
pcout
template<int dim> ConditionalOStream MultiphysicsInterface< dim >::pcout private
Definition at line 862 of file multiphysics_interface.h.
physics
template<int dim> std::map<PhysicsID, std::shared_ptr<AuxiliaryPhysics<dim, GlobalVectorType> > > MultiphysicsInterface< dim >::physics private
Definition at line 878 of file multiphysics_interface.h.
physics_dof_handler
template<int dim> std::map<PhysicsID, std::shared_ptr<DoFHandler<dim> > > MultiphysicsInterface< dim >::physics_dof_handler private
Map of physics and shared pointers to their respective DoFHandler.
Definition at line 885 of file multiphysics_interface.h.
physics_filtered_solutions
template<int dim> std::map<PhysicsID, std::shared_ptr<GlobalVectorType> > MultiphysicsInterface< dim >::physics_filtered_solutions private
Map of physics and shared pointers to their respective filtered solutions. These solutions are used with both VOF and Cahn-Hilliard multiphase flow approaches for surface tension force calculation in the momentum equation.
Definition at line 907 of file multiphysics_interface.h.
physics_previous_solutions
template<int dim> std::map<PhysicsID, std::shared_ptr<std::vector<GlobalVectorType> > > MultiphysicsInterface< dim >::physics_previous_solutions private
Map of physics and shared pointers to their respective vector of previous solutions.
Definition at line 922 of file multiphysics_interface.h.
physics_solutions
template<int dim> std::map<PhysicsID, std::shared_ptr<GlobalVectorType> > MultiphysicsInterface< dim >::physics_solutions private
Map of physics and shared pointers to their respective solutions.
Definition at line 891 of file multiphysics_interface.h.
physics_solutions_m1
template<int dim> std::map<PhysicsID, std::shared_ptr<GlobalVectorType> > MultiphysicsInterface< dim >::physics_solutions_m1 private
Map of physics and shared pointers to their respective previous (n-1) solutions.
Definition at line 956 of file multiphysics_interface.h.
physics_time_average_solutions
template<int dim> std::map<PhysicsID, std::shared_ptr<GlobalVectorType> > MultiphysicsInterface< dim >::physics_time_average_solutions private
Map of physics and shared pointers to their respective time-averaged solutions.
Definition at line 938 of file multiphysics_interface.h.
solids
template<int dim> std::shared_ptr<std::vector<std::shared_ptr<SolidBase<dim, dim> > > > MultiphysicsInterface< dim >::solids private
Shared pointer to the vector containing shared pointers to solid objects.
Definition at line 888 of file multiphysics_interface.h.
solve_pre_fluid
template<int dim> std::map<PhysicsID, bool> MultiphysicsInterface< dim >::solve_pre_fluid private
Initial value:
{{fluid_dynamics, false},
                                            {VOF, true},
                                            {heat_transfer, false},
                                            {tracer, false},
                                            {cahn_hilliard, true}}
Definition at line 869 of file multiphysics_interface.h.
verbosity
template<int dim> std::map<PhysicsID, Parameters::Verbosity> MultiphysicsInterface< dim >::verbosity private
Definition at line 861 of file multiphysics_interface.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/multiphysics_interface.h
/home/runner/work/lethe/lethe/source/solvers/multiphysics_interface.cc