Lethe Open-Source Library: GLSVansAssemblerBeetstra< dim > Class Template Reference
GLSVansAssemblerBeetstra< dim > Class Template Reference
#include <vans_assemblers.h>
Public Member Functions
GLSVansAssemblerBeetstra (Parameters::CFDDEM cfd_dem)
virtual void calculate_particle_fluid_interactions (NavierStokesScratchData< dim > &scratch_data) override
Public Attributes
Parameters::CFDDEM cfd_dem
Detailed Description
template<int dim>
class GLSVansAssemblerBeetstra< dim >
Class that assembles the drag force using Beetstra model for the VANS equations where the normalized drag force = 10 * (1 - cell_void_fraction) / (pow(cell_void_fraction, 2)) + pow(cell_void_fraction, 2) * (1 + 1.5 * pow((1 - cell_void_fraction), 0.5)) + 0.413 * re / (24 * pow(cell_void_fraction, 2)) * ((1 / cell_void_fraction) + 3 * (1 - cell_void_fraction) * cell_void_fraction.
8.4 * pow(re, -0.343)) / (1 + pow(10, 3 * (1 - cell_void_fraction)) pow(re, -(1 + 4 * (1 - cell_void_fraction)) * 0.5)); the drag coefficient = normalized_drag_force * 24 / Re_p The reference for this formulation of the Beestra model is given in the article *Complete liquid-solid momentum coupling for unresolved CFD-DEM simulations: https://www.sciencedirect.com/science/article/pii/S0301932220305346
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 361 of file vans_assemblers.h.
Constructor & Destructor Documentation
GLSVansAssemblerBeetstra()
template<int dim> GLSVansAssemblerBeetstra< dim >::GLSVansAssemblerBeetstra (Parameters::CFDDEM cfd_dem) inline
Definition at line 364 of file vans_assemblers.h.
Member Function Documentation
calculate_particle_fluid_interactions()
template<int dim> void GLSVansAssemblerBeetstra< dim >::calculate_particle_fluid_interactions (NavierStokesScratchData< dim > & scratch_data) override virtual
calculate_particle_fluid_interactions calculates the solid_fluid interactions
Parameters
scratch_data (see base class)
copy_data (see base class)
Implements ParticleFluidAssemblerBase< dim >.
Definition at line 1194 of file vans_assemblers.cc.
References NavierStokesScratchData< dim >::beta_drag, NavierStokesScratchData< dim >::cell_void_fraction, NavierStokesScratchData< dim >::cell_volume, PhysicalPropertiesManager::density_is_constant(), DEM::dp, DEM::fem_force_x, NavierStokesScratchData< dim >::fluid_particle_relative_velocity_at_particle_location, PhysicalPropertiesManager::get_density_scale(), PhysicalPropertiesManager::get_kinematic_viscosity_scale(), PhysicalPropertiesManager::is_non_newtonian(), NavierStokesScratchData< dim >::pic, NavierStokesScratchData< dim >::properties_manager, and NavierStokesScratchData< dim >::Re_particle.
Member Data Documentation
cfd_dem
template<int dim> Parameters::CFDDEM GLSVansAssemblerBeetstra< dim >::cfd_dem
Definition at line 376 of file vans_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/vans_assemblers.h
/home/runner/work/lethe/lethe/source/fem-dem/vans_assemblers.cc