Lethe Open-Source Library: MFNavierStokesPreconditionGMG< dim > Class Template Reference
MFNavierStokesPreconditionGMG< dim > Class Template Reference
#include <fluid_dynamics_matrix_free.h>
Public Member Functions
MFNavierStokesPreconditionGMG (const SimulationParameters< dim > &simulation_parameters, const DoFHandler< dim > &dof_handler, const DoFHandler< dim > &dof_handler_fe_q_iso_q1, const std::shared_ptr< Mapping< dim > > &mapping, const std::shared_ptr< Quadrature< dim > > &cell_quadrature, const std::shared_ptr< Function< dim > > forcing_function, const std::shared_ptr< SimulationControl > &simulation_control, const std::shared_ptr< FESystem< dim > > fe)
void initialize (const std::shared_ptr< SimulationControl > &simulation_control, FlowControl< dim > &flow_control, const VectorType &present_solution, const VectorType &time_derivative_previous_solutions)
void vmult (VectorType &dst, const VectorType &src) const
void print_relevant_info () const
const MGLevelObject< std::shared_ptr< OperatorType > > & get_mg_operators () const
const MGLevelObject< std::shared_ptr< PreconditionBase< MGVectorType > > > & get_mg_smoother_preconditioners () const
Public Attributes
TimerOutput mg_setup_timer
TimerOutput mg_vmult_timer
Private Types
using Number = double
using MGNumber = double
using VectorType = LinearAlgebra::distributed::Vector< Number >
using MGVectorType = LinearAlgebra::distributed::Vector< MGNumber >
using TrilinosVectorType = LinearAlgebra::distributed::Vector< double >
using LSTransferType = MGTransferMatrixFree< dim, MGNumber >
using GCTransferType = MGTransferGlobalCoarsening< dim, MGVectorType >
using OperatorType = NavierStokesOperatorBase< dim, MGNumber >
using SmootherPreconditionerType = PreconditionBase< MGVectorType >
using SmootherType = PreconditionRelaxation< OperatorType, SmootherPreconditionerType >
using PreconditionerTypeLS = PreconditionMG< dim, MGVectorType, LSTransferType >
using PreconditionerTypeGC = PreconditionMG< dim, MGVectorType, GCTransferType >
using CoarseGridSolverApply = MGCoarseGridApplyPreconditioner< MGVectorType, PreconditionAdapter< MGVectorType, TrilinosVectorType > >
Private Member Functions
void setup_AMG ()
void setup_ILU ()
Private Attributes
unsigned int minlevel
unsigned int maxlevel
unsigned int intlevel
std::vector< std::shared_ptr< const Triangulation< dim > > > coarse_grid_triangulations
MGLevelObject< DoFHandler< dim > > dof_handlers
MGLevelObject< MGTwoLevelTransfer< dim, MGVectorType > > transfers
MGLevelObject< std::shared_ptr< OperatorType > > mg_operators
std::shared_ptr< mg::Matrix< MGVectorType > > mg_matrix
std::shared_ptr< mg::Matrix< MGVectorType > > mg_interface_matrix_in
MGLevelObject< MatrixFreeOperators::MGInterfaceOperator< OperatorType > > ls_mg_operators
MGLevelObject< MatrixFreeOperators::MGInterfaceOperator< OperatorType > > ls_mg_interface_in
MGLevelObject< std::shared_ptr< PreconditionBase< MGVectorType > > > mg_smoother_preconditioners
std::shared_ptr< MGSmootherPrecondition< OperatorType, SmootherType, MGVectorType > > mg_smoother
MGConstrainedDoFs mg_constrained_dofs
std::shared_ptr< LSTransferType > mg_transfer_ls
std::shared_ptr< GCTransferType > mg_transfer_gc
std::shared_ptr< PreconditionAdapter< MGVectorType, TrilinosVectorType > > coarse_grid_precondition
std::shared_ptr< SolverControl > coarse_grid_solver_control
std::shared_ptr< SolverControl > direct_solver_control
std::shared_ptr< SolverGMRES< TrilinosVectorType > > coarse_grid_solver
std::shared_ptr< MGCoarseGridBase< MGVectorType > > mg_coarse
std::shared_ptr< SolverControl > coarse_grid_solver_control_intermediate
std::shared_ptr< MGCoarseGridBase< MGVectorType > > mg_coarse_intermediate
std::shared_ptr< SolverGMRES< MGVectorType > > coarse_grid_solver_intermediate
std::shared_ptr< Multigrid< MGVectorType > > mg_intermediate
std::shared_ptr< PreconditionMG< dim, MGVectorType, GCTransferType > > gc_multigrid_preconditioner_intermediate
std::shared_ptr< Multigrid< MGVectorType > > mg
std::shared_ptr< PreconditionMG< dim, MGVectorType, LSTransferType > > ls_multigrid_preconditioner
std::shared_ptr< PreconditionMG< dim, MGVectorType, GCTransferType > > gc_multigrid_preconditioner
ConditionalOStream pcout
SimulationParameters< dim > simulation_parameters
const DoFHandler< dim > & dof_handler
const DoFHandler< dim > & dof_handler_fe_q_iso_q1
std::vector< unsigned int > coarse_grid_iterations
Detailed Description
template<int dim>
class MFNavierStokesPreconditionGMG< dim >
A geometric multigrid preconditioner compatible with the matrix-free solver.
Definition at line 44 of file fluid_dynamics_matrix_free.h.
Member Typedef Documentation
CoarseGridSolverApply
template<int dim> using MFNavierStokesPreconditionGMG< dim >::CoarseGridSolverApply = MGCoarseGridApplyPreconditioner< MGVectorType, PreconditionAdapter<MGVectorType, TrilinosVectorType> > private
Definition at line 80 of file fluid_dynamics_matrix_free.h.
GCTransferType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::GCTransferType = MGTransferGlobalCoarsening<dim, MGVectorType> private
Definition at line 65 of file fluid_dynamics_matrix_free.h.
LSTransferType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::LSTransferType = MGTransferMatrixFree<dim, MGNumber> private
Definition at line 64 of file fluid_dynamics_matrix_free.h.
MGNumber
template<int dim> using MFNavierStokesPreconditionGMG< dim >::MGNumber = double private
Definition at line 49 of file fluid_dynamics_matrix_free.h.
MGVectorType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::MGVectorType = LinearAlgebra::distributed::Vector<MGNumber> private
Definition at line 62 of file fluid_dynamics_matrix_free.h.
Number
template<int dim> using MFNavierStokesPreconditionGMG< dim >::Number = double private
Definition at line 46 of file fluid_dynamics_matrix_free.h.
OperatorType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::OperatorType = NavierStokesOperatorBase<dim, MGNumber> private
Definition at line 66 of file fluid_dynamics_matrix_free.h.
PreconditionerTypeGC
template<int dim> using MFNavierStokesPreconditionGMG< dim >::PreconditionerTypeGC = PreconditionMG<dim, MGVectorType, GCTransferType> private
Definition at line 72 of file fluid_dynamics_matrix_free.h.
PreconditionerTypeLS
template<int dim> using MFNavierStokesPreconditionGMG< dim >::PreconditionerTypeLS = PreconditionMG<dim, MGVectorType, LSTransferType> private
Definition at line 70 of file fluid_dynamics_matrix_free.h.
SmootherPreconditionerType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::SmootherPreconditionerType = PreconditionBase<MGVectorType> private
Definition at line 67 of file fluid_dynamics_matrix_free.h.
SmootherType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::SmootherType = PreconditionRelaxation<OperatorType, SmootherPreconditionerType> private
Definition at line 68 of file fluid_dynamics_matrix_free.h.
TrilinosVectorType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::TrilinosVectorType = LinearAlgebra::distributed::Vector<double> private
Definition at line 63 of file fluid_dynamics_matrix_free.h.
VectorType
template<int dim> using MFNavierStokesPreconditionGMG< dim >::VectorType = LinearAlgebra::distributed::Vector<Number> private
Definition at line 61 of file fluid_dynamics_matrix_free.h.
Constructor & Destructor Documentation
MFNavierStokesPreconditionGMG()
template<int dim> MFNavierStokesPreconditionGMG< dim >::MFNavierStokesPreconditionGMG (const SimulationParameters< dim > & simulation_parameters, const DoFHandler< dim > & dof_handler, const DoFHandler< dim > & dof_handler_fe_q_iso_q1, const std::shared_ptr< Mapping< dim > > & mapping, const std::shared_ptr< Quadrature< dim > > & cell_quadrature, const std::shared_ptr< Function< dim > > forcing_function, const std::shared_ptr< SimulationControl > & simulation_control, const std::shared_ptr< FESystem< dim > > fe)
Construct a new precondition GMG object. Sets constraints, operators and transfer objects.
Parameters
[in] simulation_parameters Object containing all parameters specified in input file.
[in] dof_handler Describes the layout of DoFs and the type of FE.
[in] dof_handler_fe_q_iso_q1 Describes the layout of DoFs for FE_Q_iso_Q1 elements.
[in] mapping Describes the transformations from unit to real cell.
[in] cell_quadrature Required for local operations on cells.
[in] forcing_function Function specified in parameter file as source term.
[in] simulation_control Required to get the time stepping method.
[in] fe Describes the FE system for the vector-valued problem.
Definition at line 546 of file fluid_dynamics_matrix_free.cc.
References SimulationParameters< dim >::boundary_conditions, MFNavierStokesPreconditionGMG< dim >::coarse_grid_triangulations, MFNavierStokesPreconditionGMG< dim >::dof_handler, MFNavierStokesPreconditionGMG< dim >::dof_handler_fe_q_iso_q1, MFNavierStokesPreconditionGMG< dim >::dof_handlers, Parameters::extra_verbose, fluid_dynamics, BoundaryConditions::function_weak, Parameters::LinearSolver::gcmg, PhysicalPropertiesManager::get_kinematic_viscosity_scale(), Parameters::LinearSolver::h, Parameters::LinearSolver::hp, MFNavierStokesPreconditionGMG< dim >::intlevel, SimulationParameters< dim >::linear_solver, MFNavierStokesPreconditionGMG< dim >::ls_mg_interface_in, MFNavierStokesPreconditionGMG< dim >::ls_mg_operators, Parameters::LinearSolver::lsmg, MFNavierStokesPreconditionGMG< dim >::maxlevel, MFNavierStokesPreconditionGMG< dim >::mg_constrained_dofs, MFNavierStokesPreconditionGMG< dim >::mg_operators, MFNavierStokesPreconditionGMG< dim >::mg_setup_timer, MFNavierStokesPreconditionGMG< dim >::mg_transfer_gc, MFNavierStokesPreconditionGMG< dim >::mg_transfer_ls, MFNavierStokesPreconditionGMG< dim >::minlevel, BoundaryConditions::outlet, Parameters::LinearSolver::p, BoundaryConditions::partial_slip, MFNavierStokesPreconditionGMG< dim >::pcout, BoundaryConditions::periodic, Parameters::LinearSolver::ph, SimulationParameters< dim >::physical_properties_manager, BoundaryConditions::pressure, pressure, Parameters::quiet, BoundaryConditions::slip, Parameters::Stabilization::stabilization, SimulationParameters< dim >::stabilization, and MFNavierStokesPreconditionGMG< dim >::transfers.
Member Function Documentation
get_mg_operators()
template<int dim> const MGLevelObject< std::shared_ptr< NavierStokesOperatorBase< dim, typename MFNavierStokesPreconditionGMG< dim >::MGNumber > > > & MFNavierStokesPreconditionGMG< dim >::get_mg_operators () const
Getter function for all level operators.
Returns
Multigrid object that contains all level operators.
Definition at line 1830 of file fluid_dynamics_matrix_free.cc.
get_mg_smoother_preconditioners()
template<int dim> const MGLevelObject< std::shared_ptr< PreconditionBase< typename MFNavierStokesPreconditionGMG< dim >::MGVectorType > > > & MFNavierStokesPreconditionGMG< dim >::get_mg_smoother_preconditioners () const
Getter function for all level smoother preconditioners.
Returns
Multigrid object that contains all level smoother preconditioners.
Definition at line 1838 of file fluid_dynamics_matrix_free.cc.
initialize()
template<int dim> void MFNavierStokesPreconditionGMG< dim >::initialize (const std::shared_ptr< SimulationControl > & simulation_control, FlowControl< dim > & flow_control, const VectorType & present_solution, const VectorType & time_derivative_previous_solutions)
Initialize smoother, coarse grid solver and multigrid object needed for the geometric multigrid preconditioner.
Parameters
[in] simulation_control Required to get the time stepping method.
[in] flow_control Required for dynamic flow control.
[in] present_solution Previous solution needed to evaluate the non linear term.
[in] time_derivative_previous_solutions Vector storing time derivatives of previous solutions.
Definition at line 1275 of file fluid_dynamics_matrix_free.cc.
References Parameters::LinearSolver::AdditiveSchwarzMethod, Parameters::LinearSolver::amg, Parameters::LinearSolver::direct, fluid_dynamics, Parameters::LinearSolver::gcmg, FlowControl< dim >::get_beta(), Parameters::LinearSolver::gmres, Parameters::LinearSolver::ilu, is_bdf(), Parameters::LinearSolver::lsmg, and Parameters::quiet.
print_relevant_info()
template<int dim> void MFNavierStokesPreconditionGMG< dim >::print_relevant_info () const
Prints relevant multigrid information.
Definition at line 1802 of file fluid_dynamics_matrix_free.cc.
setup_AMG()
template<int dim> void MFNavierStokesPreconditionGMG< dim >::setup_AMG () private
Set up AMG object needed for coarse-grid solver or preconditioning.
Definition at line 1845 of file fluid_dynamics_matrix_free.cc.
References fluid_dynamics, Parameters::LinearSolver::gcmg, and Parameters::LinearSolver::lsmg.
setup_ILU()
template<int dim> void MFNavierStokesPreconditionGMG< dim >::setup_ILU () private
Set up ILU object needed for coarse-grid solver or preconditioning.
Definition at line 1957 of file fluid_dynamics_matrix_free.cc.
References fluid_dynamics.
vmult()
template<int dim> void MFNavierStokesPreconditionGMG< dim >::vmult (VectorType & dst, const VectorType & src) const
Calls the v cycle function of the multigrid object.
Parameters
[in,out] dst Destination vector holding the result.
[in] src Input source vector.
Definition at line 1781 of file fluid_dynamics_matrix_free.cc.
Member Data Documentation
coarse_grid_iterations
template<int dim> std::vector<unsigned int> MFNavierStokesPreconditionGMG< dim >::coarse_grid_iterations mutable private
Vector holding number of coarse grid iterations.
Definition at line 286 of file fluid_dynamics_matrix_free.h.
coarse_grid_precondition
template<int dim> std::shared_ptr<PreconditionAdapter<MGVectorType, TrilinosVectorType> > MFNavierStokesPreconditionGMG< dim >::coarse_grid_precondition private
Coarse grid solver (algebraic multigrid, ILU, direct solver)
Definition at line 232 of file fluid_dynamics_matrix_free.h.
coarse_grid_solver
template<int dim> std::shared_ptr<SolverGMRES<TrilinosVectorType> > MFNavierStokesPreconditionGMG< dim >::coarse_grid_solver private
GMRES as coarse grid solver.
Definition at line 241 of file fluid_dynamics_matrix_free.h.
coarse_grid_solver_control
template<int dim> std::shared_ptr<SolverControl> MFNavierStokesPreconditionGMG< dim >::coarse_grid_solver_control private
Solver control for the coarse grid solver.
Definition at line 235 of file fluid_dynamics_matrix_free.h.
coarse_grid_solver_control_intermediate
template<int dim> std::shared_ptr<SolverControl> MFNavierStokesPreconditionGMG< dim >::coarse_grid_solver_control_intermediate private
Solver control for the coarse grid solver (intermediate level)
Definition at line 247 of file fluid_dynamics_matrix_free.h.
coarse_grid_solver_intermediate
template<int dim> std::shared_ptr<SolverGMRES<MGVectorType> > MFNavierStokesPreconditionGMG< dim >::coarse_grid_solver_intermediate private
GMRES as coarse grid solver (intermediate level)
Definition at line 253 of file fluid_dynamics_matrix_free.h.
coarse_grid_triangulations
template<int dim> std::vector<std::shared_ptr<const Triangulation<dim> > > MFNavierStokesPreconditionGMG< dim >::coarse_grid_triangulations private
Triangulations for the global coarsening case.
Definition at line 190 of file fluid_dynamics_matrix_free.h.
direct_solver_control
template<int dim> std::shared_ptr<SolverControl> MFNavierStokesPreconditionGMG< dim >::direct_solver_control private
Solver control for the direct solver.
Definition at line 238 of file fluid_dynamics_matrix_free.h.
dof_handler
template<int dim> const DoFHandler<dim>& MFNavierStokesPreconditionGMG< dim >::dof_handler private
Describes the layout of DoFs and the type of FE.
Definition at line 280 of file fluid_dynamics_matrix_free.h.
dof_handler_fe_q_iso_q1
template<int dim> const DoFHandler<dim>& MFNavierStokesPreconditionGMG< dim >::dof_handler_fe_q_iso_q1 private
Describes the layout of DoFs for FE_Q_iso_Q1 elements.
Definition at line 283 of file fluid_dynamics_matrix_free.h.
dof_handlers
template<int dim> MGLevelObject<DoFHandler<dim> > MFNavierStokesPreconditionGMG< dim >::dof_handlers private
DoF handlers for each of the levels of the global coarsening algorithm.
Definition at line 193 of file fluid_dynamics_matrix_free.h.
gc_multigrid_preconditioner
template<int dim> std::shared_ptr<PreconditionMG<dim, MGVectorType, GCTransferType> > MFNavierStokesPreconditionGMG< dim >::gc_multigrid_preconditioner private
Global coarsening multigrid preconditioner object.
Definition at line 271 of file fluid_dynamics_matrix_free.h.
gc_multigrid_preconditioner_intermediate
template<int dim> std::shared_ptr<PreconditionMG<dim, MGVectorType, GCTransferType> > MFNavierStokesPreconditionGMG< dim >::gc_multigrid_preconditioner_intermediate private
Global coarsening multigrid preconditioner object (intermediate level)
Definition at line 260 of file fluid_dynamics_matrix_free.h.
intlevel
template<int dim> unsigned int MFNavierStokesPreconditionGMG< dim >::intlevel private
Intermediate level of the multigrid hierarchy.
Definition at line 186 of file fluid_dynamics_matrix_free.h.
ls_mg_interface_in
template<int dim> MGLevelObject<MatrixFreeOperators::MGInterfaceOperator<OperatorType> > MFNavierStokesPreconditionGMG< dim >::ls_mg_interface_in private
Definition at line 209 of file fluid_dynamics_matrix_free.h.
ls_mg_operators
template<int dim> MGLevelObject<MatrixFreeOperators::MGInterfaceOperator<OperatorType> > MFNavierStokesPreconditionGMG< dim >::ls_mg_operators private
Definition at line 207 of file fluid_dynamics_matrix_free.h.
ls_multigrid_preconditioner
template<int dim> std::shared_ptr<PreconditionMG<dim, MGVectorType, LSTransferType> > MFNavierStokesPreconditionGMG< dim >::ls_multigrid_preconditioner private
Local smoothing multigrid preconditioner object.
Definition at line 267 of file fluid_dynamics_matrix_free.h.
maxlevel
template<int dim> unsigned int MFNavierStokesPreconditionGMG< dim >::maxlevel private
Max level of the multigrid hierarchy.
Definition at line 183 of file fluid_dynamics_matrix_free.h.
mg
template<int dim> std::shared_ptr<Multigrid<MGVectorType> > MFNavierStokesPreconditionGMG< dim >::mg private
Multigrid method.
Definition at line 263 of file fluid_dynamics_matrix_free.h.
mg_coarse
template<int dim> std::shared_ptr<MGCoarseGridBase<MGVectorType> > MFNavierStokesPreconditionGMG< dim >::mg_coarse private
Multigrid wrapper for the coarse grid solver.
Definition at line 244 of file fluid_dynamics_matrix_free.h.
mg_coarse_intermediate
template<int dim> std::shared_ptr<MGCoarseGridBase<MGVectorType> > MFNavierStokesPreconditionGMG< dim >::mg_coarse_intermediate private
Multigrid wrapper for the coarse grid solver (intermediate level)
Definition at line 250 of file fluid_dynamics_matrix_free.h.
mg_constrained_dofs
template<int dim> MGConstrainedDoFs MFNavierStokesPreconditionGMG< dim >::mg_constrained_dofs private
Collection of boundary constraints and refinement edge constrations for the different levels in the local smoothing approach.
Definition at line 222 of file fluid_dynamics_matrix_free.h.
mg_interface_matrix_in
template<int dim> std::shared_ptr<mg::Matrix<MGVectorType> > MFNavierStokesPreconditionGMG< dim >::mg_interface_matrix_in private
Interface edge matrix needed only for local smoothing.
Definition at line 205 of file fluid_dynamics_matrix_free.h.
mg_intermediate
template<int dim> std::shared_ptr<Multigrid<MGVectorType> > MFNavierStokesPreconditionGMG< dim >::mg_intermediate private
Multigrid method (intermediate level)
Definition at line 256 of file fluid_dynamics_matrix_free.h.
mg_matrix
template<int dim> std::shared_ptr<mg::Matrix<MGVectorType> > MFNavierStokesPreconditionGMG< dim >::mg_matrix private
Multigrid level object storing all operators.
Definition at line 202 of file fluid_dynamics_matrix_free.h.
mg_operators
template<int dim> MGLevelObject<std::shared_ptr<OperatorType> > MFNavierStokesPreconditionGMG< dim >::mg_operators private
Level operators for the geometric multigrid.
Definition at line 199 of file fluid_dynamics_matrix_free.h.
mg_setup_timer
template<int dim> TimerOutput MFNavierStokesPreconditionGMG< dim >::mg_setup_timer mutable
Timer for specific geometric multigrid components.
Definition at line 290 of file fluid_dynamics_matrix_free.h.
mg_smoother
template<int dim> std::shared_ptr< MGSmootherPrecondition<OperatorType, SmootherType, MGVectorType> > MFNavierStokesPreconditionGMG< dim >::mg_smoother private
Smoother object.
Definition at line 218 of file fluid_dynamics_matrix_free.h.
mg_smoother_preconditioners
template<int dim> MGLevelObject<std::shared_ptr<PreconditionBase<MGVectorType> > > MFNavierStokesPreconditionGMG< dim >::mg_smoother_preconditioners mutable private
Preconditioners associated to smoothers.
Definition at line 213 of file fluid_dynamics_matrix_free.h.
mg_transfer_gc
template<int dim> std::shared_ptr<GCTransferType> MFNavierStokesPreconditionGMG< dim >::mg_transfer_gc private
Transfer operator for global coarsening.
Definition at line 228 of file fluid_dynamics_matrix_free.h.
mg_transfer_ls
template<int dim> std::shared_ptr<LSTransferType> MFNavierStokesPreconditionGMG< dim >::mg_transfer_ls private
Transfer operator for local smoothing.
Definition at line 225 of file fluid_dynamics_matrix_free.h.
mg_vmult_timer
template<int dim> TimerOutput MFNavierStokesPreconditionGMG< dim >::mg_vmult_timer mutable
Internal timer for vmult timings.
Definition at line 293 of file fluid_dynamics_matrix_free.h.
minlevel
template<int dim> unsigned int MFNavierStokesPreconditionGMG< dim >::minlevel private
Min level of the multigrid hierarchy.
Definition at line 180 of file fluid_dynamics_matrix_free.h.
pcout
template<int dim> ConditionalOStream MFNavierStokesPreconditionGMG< dim >::pcout private
Conditional Ostream.
Definition at line 274 of file fluid_dynamics_matrix_free.h.
simulation_parameters
template<int dim> SimulationParameters<dim> MFNavierStokesPreconditionGMG< dim >::simulation_parameters private
Simulation parameters.
Definition at line 277 of file fluid_dynamics_matrix_free.h.
transfers
template<int dim> MGLevelObject<MGTwoLevelTransfer<dim, MGVectorType> > MFNavierStokesPreconditionGMG< dim >::transfers private
Transfers for each of the levels of the global coarsening algorithm.
Definition at line 196 of file fluid_dynamics_matrix_free.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/fluid_dynamics_matrix_free.h
/home/runner/work/lethe/lethe/source/solvers/fluid_dynamics_matrix_free.cc