Lethe Open-Source Library: TracerScratchData< dim > Class Template Reference
TracerScratchData< dim > Class Template Reference
#include <tracer_scratch_data.h>
Public Member Functions
TracerScratchData (const PhysicalPropertiesManager &properties_manager, const FiniteElement< dim > &fe_tracer, const Quadrature< dim > &quadrature, const Quadrature< dim - 1 > &face_quadrature, const Mapping< dim > &mapping, const FiniteElement< dim > &fe_fd)
TracerScratchData (const TracerScratchData< dim > &sd)
void allocate () override
template<typename VectorType >
void reinit (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const std::vector< VectorType > &previous_solutions, const Function< dim > *source_function)
void reinit_signed_distance (const typename DoFHandler< dim >::active_cell_iterator &cell, std::shared_ptr< Shape< dim > > immersed_solid_shape)
void reinit_signed_distance_at_face (const typename DoFHandler< dim >::active_cell_iterator &cell, const unsigned int &face_no, std::shared_ptr< Shape< dim > > immersed_solid_shape)
template<typename VectorType >
void reinit_velocity (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &velocity_solution, const Parameters::ALE< dim > &ale, std::shared_ptr< Functions::ParsedFunction< dim > > drift_velocity)
template<typename VectorType >
void reinit_internal_face (const typename DoFHandler< dim >::active_cell_iterator &cell, const unsigned int &face_no, const unsigned int &sub_face_no, const typename DoFHandler< dim >::active_cell_iterator &neigh_cell, const unsigned int &neigh_face_no, const unsigned int &neigh_sub_face_no, const VectorType &current_solution)
template<typename VectorType >
void reinit_boundary_face (const typename DoFHandler< dim >::active_cell_iterator &cell, const unsigned int &face_no, const unsigned int &boundary_index, const VectorType &current_solution)
template<typename VectorType >
void reinit_face_velocity (const typename DoFHandler< dim >::active_cell_iterator &velocity_cell, const unsigned int &face_no, const VectorType &velocity_solution, const Parameters::ALE< dim > &ale, std::shared_ptr< Functions::ParsedFunction< dim > > drift_velocity)
void calculate_face_physical_properties ()
void calculate_physical_properties ()
Public Member Functions inherited from PhysicsScratchDataBase
virtual ~PhysicsScratchDataBase ()=default
Public Attributes
PhysicalPropertiesManager properties_manager
std::map< field, std::vector< double > > fields
std::vector< double > tracer_diffusivity
std::vector< double > tracer_diffusivity_face
std::vector< double > tracer_diffusivity_0
std::vector< double > tracer_diffusivity_1
std::vector< double > tracer_reaction_prefactor
std::vector< double > grad_tracer_reaction_prefactor
FEValues< dim > fe_values_tracer
FEInterfaceValues< dim > fe_interface_values_tracer
unsigned int n_dofs
unsigned int n_interface_dofs
unsigned int n_q_points
double cell_size
Table< 1, double > JxW
std::vector< Point< dim > > quadrature_points
std::vector< Point< dim > > face_quadrature_points
std::vector< double > tracer_values
std::vector< Tensor< 1, dim > > tracer_gradients
std::vector< double > tracer_laplacians
std::vector< std::vector< double > > previous_tracer_values
std::vector< Tensor< 1, dim > > previous_tracer_gradients
std::vector< double > values_here
std::vector< double > values_there
std::vector< double > tracer_value_jump
std::vector< Tensor< 1, dim > > gradients_here
std::vector< Tensor< 1, dim > > tracer_average_gradient
double penalty_factor
unsigned int boundary_index
std::vector< double > sdf_values
std::vector< double > source
Table< 2, double > phi
Table< 2, Tensor< 2, dim > > hess_phi
Table< 2, double > laplacian_phi
Table< 2, Tensor< 1, dim > > grad_phi
FEValuesExtractors::Vector velocities
FEValues< dim > fe_values_fd
FEFaceValues< dim > fe_face_values_fd
std::vector< Tensor< 1, dim > > velocity_values
std::vector< double > velocity_divergences
std::vector< Tensor< 1, dim > > face_velocity_values
Detailed Description
template<int dim>
class TracerScratchData< dim >
Class that stores the information required by the assembly procedure for a Tracer advection-diffusion equation. Consequently, this class calculates the tracer (values, gradients, laplacians) and the shape function (values, gradients, laplacians) at all the gauss points for all degrees of freedom and stores it into arrays. Additionnaly, the use can request that this class gathers additional fields for physics which are coupled to the Tracer equation, such as the velocity which is required. This class serves as a seperation between the evaluation at the gauss point of the variables of interest and their use in the assembly, which is carried out by the assembler functions. For more information on this design, the reader can consult deal.II step-9 "https://www.dealii.org/current/doxygen/deal.II/step_9.html". In this latter example, the scratch is a struct instead of a templated class because of the simplicity of step-9.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 43 of file tracer_scratch_data.h.
Constructor & Destructor Documentation
TracerScratchData() [1/2]
template<int dim> TracerScratchData< dim >::TracerScratchData (const PhysicalPropertiesManager & properties_manager, const FiniteElement< dim > & fe_tracer, const Quadrature< dim > & quadrature, const Quadrature< dim - 1 > & face_quadrature, const Mapping< dim > & mapping, const FiniteElement< dim > & fe_fd) inline
Constructor. The constructor creates the fe_values that will be used to fill the member variables of the scratch. It also allocated the necessary memory for all member variables. However, it does not do any evalution, since this needs to be done at the cell level.
Parameters
fe The FESystem used to solve the Navier-Stokes equations
quadrature The quadrature to use for the assembly
mapping The mapping of the domain in which the Navier-Stokes equations are solved
Definition at line 59 of file tracer_scratch_data.h.
References TracerScratchData< dim >::allocate().
TracerScratchData() [2/2]
template<int dim> TracerScratchData< dim >::TracerScratchData (const TracerScratchData< dim > & sd) inline
Copy Constructor. Same as the main constructor. This constructor only uses the other scratch to build the FeValues, it does not copy the content of the other scratch into itself since, by definition of the WorkStream mechanism it is assumed that the content of the scratch will be reset on a cell basis.
Parameters
fe The FESystem used to solve the Navier-Stokes equations
quadrature The quadrature to use for the assembly
mapping The mapping of the domain in which the Navier-Stokes equations are solved
Definition at line 96 of file tracer_scratch_data.h.
References TracerScratchData< dim >::allocate().
Member Function Documentation
allocate()
template<int dim> void TracerScratchData< dim >::allocate () override virtual
Allocates the memory for the scratch.
This function allocates the necessary memory for all members of the scratch
Implements PhysicsScratchDataBase.
Definition at line 10 of file tracer_scratch_data.cc.
References levelset, maximum_number_of_previous_solutions(), and tracer_concentration.
calculate_face_physical_properties()
template<int dim> void TracerScratchData< dim >::calculate_face_physical_properties () inline
Calculates the physical properties at a face.
Definition at line 496 of file tracer_scratch_data.h.
References TracerScratchData< dim >::face_quadrature_points, PhysicalPropertiesManager::field_is_required(), TracerScratchData< dim >::fields, PhysicalPropertiesManager::get_tracer_diffusivity(), levelset, TracerScratchData< dim >::properties_manager, TracerScratchData< dim >::sdf_values, set_field_vector(), and TracerScratchData< dim >::tracer_diffusivity_face.
calculate_physical_properties()
template<int dim> void TracerScratchData< dim >::calculate_physical_properties ()
Calculates the physical properties. This function calculates the physical properties that may be required by the tracer. Namely the diffusivity.
Definition at line 69 of file tracer_scratch_data.cc.
References levelset, set_field_vector(), and tracer_concentration.
reinit()
template<int dim> template<typename VectorType > void TracerScratchData< dim >::reinit (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const std::vector< VectorType > & previous_solutions, const Function< dim > * source_function) inline
Reinitializes the content of the scratch.
Using the FeValues and the content of the solutions and previous solutions, fills all of the class member of the scratch.
Parameters
[in] cell The cell over which the assembly is being carried. This cell must be compatible with the fe which is used to fill the FeValues.
[in] current_solution The present value of the solution.
[in] previous_solutions The solutions at the previous time steps.
[in] source_function The function describing the tracer source term.
Definition at line 147 of file tracer_scratch_data.h.
References TracerScratchData< dim >::boundary_index, TracerScratchData< dim >::cell_size, compute_cell_measure_with_JxW(), TracerScratchData< dim >::fe_values_tracer, TracerScratchData< dim >::grad_phi, TracerScratchData< dim >::hess_phi, TracerScratchData< dim >::JxW, TracerScratchData< dim >::laplacian_phi, TracerScratchData< dim >::n_dofs, TracerScratchData< dim >::n_q_points, TracerScratchData< dim >::phi, TracerScratchData< dim >::previous_tracer_gradients, TracerScratchData< dim >::previous_tracer_values, TracerScratchData< dim >::quadrature_points, TracerScratchData< dim >::source, TracerScratchData< dim >::tracer_gradients, TracerScratchData< dim >::tracer_laplacians, and TracerScratchData< dim >::tracer_values.
reinit_boundary_face()
template<int dim> template<typename VectorType > void TracerScratchData< dim >::reinit_boundary_face (const typename DoFHandler< dim >::active_cell_iterator & cell, const unsigned int & face_no, const unsigned int & boundary_index, const VectorType & current_solution) inline
Reinitializes the content of the scratch for the boundary faces. This is only used for the DG assemblers.
Parameters
[in] cell The cell over which the assembly is being carried.
[in] face The face index associated with the cell
[in] current_solution The present value of the solution. there are any).
Definition at line 402 of file tracer_scratch_data.h.
References TracerScratchData< dim >::boundary_index, TracerScratchData< dim >::face_quadrature_points, TracerScratchData< dim >::fe_interface_values_tracer, TracerScratchData< dim >::fe_values_tracer, get_penalty_factor(), TracerScratchData< dim >::gradients_here, TracerScratchData< dim >::penalty_factor, and TracerScratchData< dim >::values_here.
reinit_face_velocity()
template<int dim> template<typename VectorType > void TracerScratchData< dim >::reinit_face_velocity (const typename DoFHandler< dim >::active_cell_iterator & velocity_cell, const unsigned int & face_no, const VectorType & velocity_solution, const Parameters::ALE< dim > & ale, std::shared_ptr< Functions::ParsedFunction< dim > > drift_velocity) inline
Reinitializes the content of the scratch regarding the velocity for internal/boundary faces. The velocity is inherently assumed to have been solved using a CG scheme.
Parameters
[in] cell The cell over which the assembly is being carried.
[in] face The face index associated with the cell
[in] velocity_solution The present value of the solution. there are any).
Definition at line 440 of file tracer_scratch_data.h.
References Parameters::ALE< dim >::enabled(), TracerScratchData< dim >::face_quadrature_points, TracerScratchData< dim >::face_velocity_values, TracerScratchData< dim >::fe_face_values_fd, TracerScratchData< dim >::velocities, and Parameters::ALE< dim >::velocity.
reinit_internal_face()
template<int dim> template<typename VectorType > void TracerScratchData< dim >::reinit_internal_face (const typename DoFHandler< dim >::active_cell_iterator & cell, const unsigned int & face_no, const unsigned int & sub_face_no, const typename DoFHandler< dim >::active_cell_iterator & neigh_cell, const unsigned int & neigh_face_no, const unsigned int & neigh_sub_face_no, const VectorType & current_solution) inline
Reinitializes the content of the scratch for the internal faces. This is only used for the DG assemblers.
Parameters
[in] cell The cell over which the assembly is being carried.
[in] face_no The face index associated with the cell
[in] sub_face_no The subface index associated with the face
[in] neigh_cell The neighboring cell
[in] neigh_face_no The face index associated with the neighboring cell
[in] neigh_sub_face_no The subface index associated with the neighboring cell
[in] current_solution The present value of the solution.
Definition at line 348 of file tracer_scratch_data.h.
References TracerScratchData< dim >::face_quadrature_points, TracerScratchData< dim >::fe_interface_values_tracer, TracerScratchData< dim >::fe_values_tracer, get_penalty_factor(), TracerScratchData< dim >::n_interface_dofs, TracerScratchData< dim >::penalty_factor, TracerScratchData< dim >::tracer_average_gradient, TracerScratchData< dim >::tracer_value_jump, TracerScratchData< dim >::values_here, and TracerScratchData< dim >::values_there.
reinit_signed_distance()
template<int dim> void TracerScratchData< dim >::reinit_signed_distance (const typename DoFHandler< dim >::active_cell_iterator & cell, std::shared_ptr< Shape< dim > > immersed_solid_shape) inline
Reinitializes the signed distance vector of the scratch.
Parameters
[in] cell The cell over which the assembly is being carried.
[in] immersed_solid_shape Shared pointer to the shape describing the particles (if there are any).
Definition at line 207 of file tracer_scratch_data.h.
References TracerScratchData< dim >::fe_values_tracer, PhysicalPropertiesManager::field_is_required(), levelset, TracerScratchData< dim >::n_q_points, TracerScratchData< dim >::properties_manager, TracerScratchData< dim >::quadrature_points, and TracerScratchData< dim >::sdf_values.
reinit_signed_distance_at_face()
template<int dim> void TracerScratchData< dim >::reinit_signed_distance_at_face (const typename DoFHandler< dim >::active_cell_iterator & cell, const unsigned int & face_no, std::shared_ptr< Shape< dim > > immersed_solid_shape) inline
Reinitializes the signed distance vector of the scratch for a given face.
Parameters
[in] cell The cell over which the assembly is being carried.
[in] face_no The face index associated with the cell
[in] immersed_solid_shape Shared pointer to the shape describing the particles (if there are any).
Definition at line 237 of file tracer_scratch_data.h.
References TracerScratchData< dim >::face_quadrature_points, TracerScratchData< dim >::fe_interface_values_tracer, PhysicalPropertiesManager::field_is_required(), levelset, TracerScratchData< dim >::properties_manager, and TracerScratchData< dim >::sdf_values.
reinit_velocity()
template<int dim> template<typename VectorType > void TracerScratchData< dim >::reinit_velocity (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & velocity_solution, const Parameters::ALE< dim > & ale, std::shared_ptr< Functions::ParsedFunction< dim > > drift_velocity) inline
Reinitialize the velocity, calculated by the fluid dynamics while also taking into account ALE.
Template Parameters
VectorType The Vector type used for the solvers
Parameters
cell The cell for which the velocity is reinitialized This cell must be compatible with the Fluid Dynamics FE
current_solution The present value of the solution for [u,p]
ale The ALE parameters which include the ALE function
drift_velocity Function to calculate the drift velocity
Definition at line 277 of file tracer_scratch_data.h.
References Parameters::ALE< dim >::enabled(), TracerScratchData< dim >::fe_values_fd, TracerScratchData< dim >::n_q_points, TracerScratchData< dim >::quadrature_points, TracerScratchData< dim >::velocities, Parameters::ALE< dim >::velocity, TracerScratchData< dim >::velocity_divergences, and TracerScratchData< dim >::velocity_values.
Member Data Documentation
boundary_index
template<int dim> unsigned int TracerScratchData< dim >::boundary_index
Definition at line 568 of file tracer_scratch_data.h.
cell_size
template<int dim> double TracerScratchData< dim >::cell_size
Definition at line 541 of file tracer_scratch_data.h.
face_quadrature_points
template<int dim> std::vector<Point<dim> > TracerScratchData< dim >::face_quadrature_points
Definition at line 546 of file tracer_scratch_data.h.
face_velocity_values
template<int dim> std::vector<Tensor<1, dim> > TracerScratchData< dim >::face_velocity_values
Definition at line 592 of file tracer_scratch_data.h.
fe_face_values_fd
template<int dim> FEFaceValues<dim> TracerScratchData< dim >::fe_face_values_fd
Definition at line 589 of file tracer_scratch_data.h.
fe_interface_values_tracer
template<int dim> FEInterfaceValues<dim> TracerScratchData< dim >::fe_interface_values_tracer
Definition at line 536 of file tracer_scratch_data.h.
fe_values_fd
template<int dim> FEValues<dim> TracerScratchData< dim >::fe_values_fd
Definition at line 588 of file tracer_scratch_data.h.
fe_values_tracer
template<int dim> FEValues<dim> TracerScratchData< dim >::fe_values_tracer
Definition at line 535 of file tracer_scratch_data.h.
fields
template<int dim> std::map<field, std::vector<double> > TracerScratchData< dim >::fields
Definition at line 522 of file tracer_scratch_data.h.
grad_phi
template<int dim> Table<2, Tensor<1, dim> > TracerScratchData< dim >::grad_phi
Definition at line 580 of file tracer_scratch_data.h.
grad_tracer_reaction_prefactor
template<int dim> std::vector<double> TracerScratchData< dim >::grad_tracer_reaction_prefactor
Definition at line 532 of file tracer_scratch_data.h.
gradients_here
template<int dim> std::vector<Tensor<1, dim> > TracerScratchData< dim >::gradients_here
Definition at line 559 of file tracer_scratch_data.h.
hess_phi
template<int dim> Table<2, Tensor<2, dim> > TracerScratchData< dim >::hess_phi
Definition at line 578 of file tracer_scratch_data.h.
JxW
template<int dim> Table<1, double> TracerScratchData< dim >::JxW
Definition at line 544 of file tracer_scratch_data.h.
laplacian_phi
template<int dim> Table<2, double> TracerScratchData< dim >::laplacian_phi
Definition at line 579 of file tracer_scratch_data.h.
n_dofs
template<int dim> unsigned int TracerScratchData< dim >::n_dofs
Definition at line 538 of file tracer_scratch_data.h.
n_interface_dofs
template<int dim> unsigned int TracerScratchData< dim >::n_interface_dofs
Definition at line 539 of file tracer_scratch_data.h.
n_q_points
template<int dim> unsigned int TracerScratchData< dim >::n_q_points
Definition at line 540 of file tracer_scratch_data.h.
penalty_factor
template<int dim> double TracerScratchData< dim >::penalty_factor
Definition at line 565 of file tracer_scratch_data.h.
phi
template<int dim> Table<2, double> TracerScratchData< dim >::phi
Definition at line 577 of file tracer_scratch_data.h.
previous_tracer_gradients
template<int dim> std::vector<Tensor<1, dim> > TracerScratchData< dim >::previous_tracer_gradients
Definition at line 553 of file tracer_scratch_data.h.
previous_tracer_values
template<int dim> std::vector<std::vector<double> > TracerScratchData< dim >::previous_tracer_values
Definition at line 552 of file tracer_scratch_data.h.
properties_manager
template<int dim> PhysicalPropertiesManager TracerScratchData< dim >::properties_manager
Definition at line 521 of file tracer_scratch_data.h.
quadrature_points
template<int dim> std::vector<Point<dim> > TracerScratchData< dim >::quadrature_points
Definition at line 545 of file tracer_scratch_data.h.
sdf_values
template<int dim> std::vector<double> TracerScratchData< dim >::sdf_values
Definition at line 571 of file tracer_scratch_data.h.
source
template<int dim> std::vector<double> TracerScratchData< dim >::source
Definition at line 574 of file tracer_scratch_data.h.
tracer_average_gradient
template<int dim> std::vector<Tensor<1, dim> > TracerScratchData< dim >::tracer_average_gradient
Definition at line 560 of file tracer_scratch_data.h.
tracer_diffusivity
template<int dim> std::vector<double> TracerScratchData< dim >::tracer_diffusivity
Definition at line 523 of file tracer_scratch_data.h.
tracer_diffusivity_0
template<int dim> std::vector<double> TracerScratchData< dim >::tracer_diffusivity_0
Definition at line 525 of file tracer_scratch_data.h.
tracer_diffusivity_1
template<int dim> std::vector<double> TracerScratchData< dim >::tracer_diffusivity_1
Definition at line 526 of file tracer_scratch_data.h.
tracer_diffusivity_face
template<int dim> std::vector<double> TracerScratchData< dim >::tracer_diffusivity_face
Definition at line 524 of file tracer_scratch_data.h.
tracer_gradients
template<int dim> std::vector<Tensor<1, dim> > TracerScratchData< dim >::tracer_gradients
Definition at line 550 of file tracer_scratch_data.h.
tracer_laplacians
template<int dim> std::vector<double> TracerScratchData< dim >::tracer_laplacians
Definition at line 551 of file tracer_scratch_data.h.
tracer_reaction_prefactor
template<int dim> std::vector<double> TracerScratchData< dim >::tracer_reaction_prefactor
Definition at line 527 of file tracer_scratch_data.h.
tracer_value_jump
template<int dim> std::vector<double> TracerScratchData< dim >::tracer_value_jump
Definition at line 558 of file tracer_scratch_data.h.
tracer_values
template<int dim> std::vector<double> TracerScratchData< dim >::tracer_values
Definition at line 549 of file tracer_scratch_data.h.
values_here
template<int dim> std::vector<double> TracerScratchData< dim >::values_here
Definition at line 556 of file tracer_scratch_data.h.
values_there
template<int dim> std::vector<double> TracerScratchData< dim >::values_there
Definition at line 557 of file tracer_scratch_data.h.
velocities
template<int dim> FEValuesExtractors::Vector TracerScratchData< dim >::velocities
Scratch component for the Navier-Stokes component
Definition at line 586 of file tracer_scratch_data.h.
velocity_divergences
template<int dim> std::vector<double> TracerScratchData< dim >::velocity_divergences
Definition at line 591 of file tracer_scratch_data.h.
velocity_values
template<int dim> std::vector<Tensor<1, dim> > TracerScratchData< dim >::velocity_values
Definition at line 590 of file tracer_scratch_data.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/tracer_scratch_data.h
/home/runner/work/lethe/lethe/source/solvers/tracer_scratch_data.cc