Lethe Open-Source Library: ParticlePointLineForce< dim > Class Template Reference
ParticlePointLineForce< dim > Class Template Reference
#include <particle_point_line_contact_force.h>
Public Member Functions
ParticlePointLineForce ()
void calculate_particle_point_contact_force (const typename DEM::dem_data_structures< dim >::particle_point_in_contact *particle_point_pairs_in_contact, const Parameters::Lagrangian::LagrangianPhysicalProperties &physical_properties, std::vector< Tensor< 1, 3 >> &force)
void calculate_particle_line_contact_force (const typename DEM::dem_data_structures< dim >::particle_line_in_contact *particle_line_pairs_in_contact, const Parameters::Lagrangian::LagrangianPhysicalProperties &physical_properties, std::vector< Tensor< 1, 3 >> &force)
Private Member Functions
Point< 3 > find_projection_point (const Point< 3 > &point_p, const Point< 3 > &point_a, const Point< 3 > &point_b)
Detailed Description
template<int dim>
class ParticlePointLineForce< dim >
Calculate the non-linear particle-point and particle-line contact force using the information obtained from the fine search and physical properties of particles and walls. Since the inputs and the calculation method of particle-point and particle-line contact forces are similar, we only used one function for both tasks.
Definition at line 26 of file particle_point_line_contact_force.h.
Constructor & Destructor Documentation
ParticlePointLineForce()
template<int dim> ParticlePointLineForce< dim >::ParticlePointLineForce () default
Member Function Documentation
calculate_particle_line_contact_force()
template<int dim> void ParticlePointLineForce< dim >::calculate_particle_line_contact_force (const typename DEM::dem_data_structures< dim >::particle_line_in_contact * particle_line_pairs_in_contact, const Parameters::Lagrangian::LagrangianPhysicalProperties & physical_properties, std::vector< Tensor< 1, 3 >> & force)
Calculate of the particle-line contact force using non-linear (Hertzian) model.
Parameters
particle_line_pairs_in_contact Required information for calculation of the particle-line contact force
physical_properties DEM physical_properties declared in the .prm file
force Force acting on particles
Definition at line 142 of file particle_point_line_contact_force.cc.
References DEM::dp, find_projection_point(), DEM::mass, DEM::omega_x, DEM::omega_y, DEM::omega_z, point_nd_to_3d(), Parameters::Lagrangian::LagrangianPhysicalProperties::poisson_ratio_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::restitution_coefficient_wall, DEM::v_x, DEM::v_y, DEM::v_z, and Parameters::Lagrangian::LagrangianPhysicalProperties::youngs_modulus_wall.
calculate_particle_point_contact_force()
template<int dim> void ParticlePointLineForce< dim >::calculate_particle_point_contact_force (const typename DEM::dem_data_structures< dim >::particle_point_in_contact * particle_point_pairs_in_contact, const Parameters::Lagrangian::LagrangianPhysicalProperties & physical_properties, std::vector< Tensor< 1, 3 >> & force)
Calculate of the particle-point contact force using non-linear (Hertzian) model.
Parameters
particle_point_pairs_in_contact Required information for calculation of the particle-point contact force
physical_properties DEM physical_properties declared in the .prm file
force Force acting on particles
Definition at line 18 of file particle_point_line_contact_force.cc.
References DEM::dp, DEM::mass, DEM::omega_x, DEM::omega_y, DEM::omega_z, point_nd_to_3d(), Parameters::Lagrangian::LagrangianPhysicalProperties::poisson_ratio_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::restitution_coefficient_wall, DEM::v_x, DEM::v_y, DEM::v_z, and Parameters::Lagrangian::LagrangianPhysicalProperties::youngs_modulus_wall.
find_projection_point()
template<int dim> Point< 3 > ParticlePointLineForce< dim >::find_projection_point (const Point< 3 > & point_p, const Point< 3 > & point_a, const Point< 3 > & point_b) private
This private function is used to find the projection of point_p on a line with beginning and ending vertices of point_a and point_b, respectively.
Parameters
point_p A point which is going to be projected on the line
point_a Beginning point of the line
point_b Ending point of the line
Returns
The projection of point_p on the line (from point_a to point_b)
Definition at line 274 of file particle_point_line_contact_force.cc.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/particle_point_line_contact_force.h
/home/runner/work/lethe/lethe/source/dem/particle_point_line_contact_force.cc