Lethe Open-Source Library: DEMSolverParameters< dim > Class Template Reference
DEMSolverParameters< dim > Class Template Reference
#include <dem_solver_parameters.h>
Public Member Functions
void declare (ParameterHandler &prm)
void parse (ParameterHandler &prm)
Public Attributes
Parameters::Mesh mesh
Parameters::Testing test
Parameters::Restart restart
Parameters::Timer timer
Parameters::SimulationControl simulation_control
Parameters::Lagrangian::LagrangianPhysicalProperties lagrangian_physical_properties
Parameters::Lagrangian::InsertionInfo insertion_info
Parameters::Lagrangian::ModelParameters model_parameters
Parameters::Lagrangian::FloatingWalls< dim > floating_walls
Parameters::Lagrangian::BCDEM boundary_conditions
Parameters::Lagrangian::FloatingGrid< dim > floating_grid
Parameters::Lagrangian::ForceTorqueOnWall< dim > forces_torques
Parameters::Lagrangian::GridMotion< dim > grid_motion
Parameters::Lagrangian::LagrangianPostProcessing post_processing
std::shared_ptr< Parameters::DEMSolidObjects< dim > > solid_objects
Detailed Description
template<int dim>
class DEMSolverParameters< dim >
Handles all the parameters declared in the parameter handler file.
Definition at line 16 of file dem_solver_parameters.h.
Member Function Documentation
declare()
template<int dim> void DEMSolverParameters< dim >::declare (ParameterHandler & prm) inline
Definition at line 37 of file dem_solver_parameters.h.
References DEMSolverParameters< dim >::boundary_conditions, Parameters::SimulationControl::declare_parameters(), Parameters::Timer::declare_parameters(), Parameters::Mesh::declare_parameters(), Parameters::Testing::declare_parameters(), Parameters::Restart::declare_parameters(), Parameters::Lagrangian::LagrangianPhysicalProperties::declare_parameters(), Parameters::Lagrangian::InsertionInfo::declare_parameters(), Parameters::Lagrangian::ModelParameters::declare_parameters(), Parameters::Lagrangian::BCDEM::declare_parameters(), Parameters::Lagrangian::LagrangianPostProcessing::declare_parameters(), DEMSolverParameters< dim >::floating_grid, DEMSolverParameters< dim >::floating_walls, DEMSolverParameters< dim >::forces_torques, DEMSolverParameters< dim >::grid_motion, DEMSolverParameters< dim >::lagrangian_physical_properties, DEMSolverParameters< dim >::post_processing, and DEMSolverParameters< dim >::solid_objects.
parse()
template<int dim> void DEMSolverParameters< dim >::parse (ParameterHandler & prm) inline
Definition at line 62 of file dem_solver_parameters.h.
References DEMSolverParameters< dim >::boundary_conditions, DEMSolverParameters< dim >::floating_grid, DEMSolverParameters< dim >::floating_walls, DEMSolverParameters< dim >::forces_torques, DEMSolverParameters< dim >::grid_motion, DEMSolverParameters< dim >::insertion_info, DEMSolverParameters< dim >::lagrangian_physical_properties, DEMSolverParameters< dim >::mesh, DEMSolverParameters< dim >::model_parameters, Parameters::SimulationControl::parse_parameters(), Parameters::Timer::parse_parameters(), Parameters::Mesh::parse_parameters(), Parameters::Testing::parse_parameters(), Parameters::Restart::parse_parameters(), Parameters::Lagrangian::LagrangianPhysicalProperties::parse_parameters(), Parameters::Lagrangian::InsertionInfo::parse_parameters(), Parameters::Lagrangian::ModelParameters::parse_parameters(), Parameters::Lagrangian::BCDEM::parse_parameters(), Parameters::Lagrangian::LagrangianPostProcessing::parse_parameters(), DEMSolverParameters< dim >::post_processing, DEMSolverParameters< dim >::restart, DEMSolverParameters< dim >::simulation_control, DEMSolverParameters< dim >::solid_objects, DEMSolverParameters< dim >::test, and DEMSolverParameters< dim >::timer.
Member Data Documentation
boundary_conditions
template<int dim> Parameters::Lagrangian::BCDEM DEMSolverParameters< dim >::boundary_conditions
Definition at line 29 of file dem_solver_parameters.h.
floating_grid
template<int dim> Parameters::Lagrangian::FloatingGrid<dim> DEMSolverParameters< dim >::floating_grid
Definition at line 30 of file dem_solver_parameters.h.
floating_walls
template<int dim> Parameters::Lagrangian::FloatingWalls<dim> DEMSolverParameters< dim >::floating_walls
Definition at line 28 of file dem_solver_parameters.h.
forces_torques
template<int dim> Parameters::Lagrangian::ForceTorqueOnWall<dim> DEMSolverParameters< dim >::forces_torques
Definition at line 31 of file dem_solver_parameters.h.
grid_motion
template<int dim> Parameters::Lagrangian::GridMotion<dim> DEMSolverParameters< dim >::grid_motion
Definition at line 32 of file dem_solver_parameters.h.
insertion_info
template<int dim> Parameters::Lagrangian::InsertionInfo DEMSolverParameters< dim >::insertion_info
Definition at line 26 of file dem_solver_parameters.h.
lagrangian_physical_properties
template<int dim> Parameters::Lagrangian::LagrangianPhysicalProperties DEMSolverParameters< dim >::lagrangian_physical_properties
Definition at line 25 of file dem_solver_parameters.h.
mesh
template<int dim> Parameters::Mesh DEMSolverParameters< dim >::mesh
Definition at line 19 of file dem_solver_parameters.h.
model_parameters
template<int dim> Parameters::Lagrangian::ModelParameters DEMSolverParameters< dim >::model_parameters
Definition at line 27 of file dem_solver_parameters.h.
post_processing
template<int dim> Parameters::Lagrangian::LagrangianPostProcessing DEMSolverParameters< dim >::post_processing
Definition at line 33 of file dem_solver_parameters.h.
restart
template<int dim> Parameters::Restart DEMSolverParameters< dim >::restart
Definition at line 21 of file dem_solver_parameters.h.
simulation_control
template<int dim> Parameters::SimulationControl DEMSolverParameters< dim >::simulation_control
Definition at line 23 of file dem_solver_parameters.h.
solid_objects
template<int dim> std::shared_ptr<Parameters::DEMSolidObjects<dim> > DEMSolverParameters< dim >::solid_objects
Definition at line 34 of file dem_solver_parameters.h.
test
template<int dim> Parameters::Testing DEMSolverParameters< dim >::test
Definition at line 20 of file dem_solver_parameters.h.
timer
template<int dim> Parameters::Timer DEMSolverParameters< dim >::timer
Definition at line 22 of file dem_solver_parameters.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/dem/dem_solver_parameters.h