Lethe Open-Source Library: VANSAssemblerGidaspow< dim > Class Template Reference
VANSAssemblerGidaspow< dim > Class Template Reference
#include <vans_assemblers.h>
Public Member Functions
VANSAssemblerGidaspow (const Parameters::CFDDEM &cfd_dem)
virtual void calculate_particle_fluid_interactions (NavierStokesScratchData< dim > &scratch_data) override
Public Attributes
const Parameters::CFDDEM cfd_dem
Detailed Description
template<int dim>
class VANSAssemblerGidaspow< dim >
Class that assembles the drag force using Gidaspow model for the VANS equations where the momentum_transfer_coefficient is calculated according to the following Marchelli et al. (2020): if (cell_void_fraction > 0.8) { momentum_transfer_coefficient = (18 * pow(cell_void_fraction, -3.65) * (1 + 0.15 * pow(Re_p[particle_number], 0.687))) * (particle_properties[DEM::PropertiesIndex<DEM::SolverType::cfd_dem>::mass] viscosity / (pow(particle_properties[DEM::CFDDEMProperties::PropertiesIndex::dp], 2) * particle_density)); } else { Assuming the sphericity of particles = 1 momentum_transfer_coefficient = (150 * (1 - cell_void_fraction) / pow(cell_void_fraction, 2) + 1.75 * Re_p[particle_number] / pow(cell_void_fraction, 2)) * (particle_properties[DEM::PropertiesIndex<DEM::SolverType::cfd_dem>::mass] viscosity / (pow(particle_properties[DEM::CFDDEMProperties::PropertiesIndex::dp], 2) * particle_density)); }.
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 401 of file vans_assemblers.h.
Constructor & Destructor Documentation
VANSAssemblerGidaspow()
template<int dim> VANSAssemblerGidaspow< dim >::VANSAssemblerGidaspow (const Parameters::CFDDEM & cfd_dem) inline
Definition at line 404 of file vans_assemblers.h.
Member Function Documentation
calculate_particle_fluid_interactions()
template<int dim> void VANSAssemblerGidaspow< dim >::calculate_particle_fluid_interactions (NavierStokesScratchData< dim > & scratch_data) override virtual
calculate_particle_fluid_interactions calculted the solid_fluid interactions
Parameters
scratch_data (see base class)
copy_data (see base class)
Implements ParticleFluidAssemblerBase< dim >.
Definition at line 1289 of file vans_assemblers.cc.
References NavierStokesScratchData< dim >::beta_drag, NavierStokesScratchData< dim >::cell_void_fraction, NavierStokesScratchData< dim >::cell_volume, PhysicalPropertiesManager::density_is_constant(), DEM::CFDDEMProperties::dp, DEM::CFDDEMProperties::fem_force_x, NavierStokesScratchData< dim >::fluid_particle_relative_velocity_at_particle_location, PhysicalPropertiesManager::get_density_scale(), PhysicalPropertiesManager::get_kinematic_viscosity_scale(), PhysicalPropertiesManager::is_non_newtonian(), DEM::CFDDEMProperties::mass, NavierStokesScratchData< dim >::pic, NavierStokesScratchData< dim >::properties_manager, and NavierStokesScratchData< dim >::Re_particle.
Member Data Documentation
cfd_dem
template<int dim> const Parameters::CFDDEM VANSAssemblerGidaspow< dim >::cfd_dem
Definition at line 417 of file vans_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/vans_assemblers.h
/home/runner/work/lethe/lethe/source/fem-dem/vans_assemblers.cc