Lethe Open-Source Library: Parameters::MaterialInteractions Class Reference
Parameters::MaterialInteractions Class Reference
#include <parameters.h>
Public Types
enum class MaterialInteractionsType : std::int8_t { fluid_fluid , fluid_solid }
enum class SurfaceTensionModel : std::int8_t { constant , linear , phase_change }
enum class MobilityCahnHilliardModel : std::int8_t { constant , quartic }
Public Member Functions
MaterialInteractions ()=default
void declare_parameters (ParameterHandler &prm, unsigned int id) const
void parse_parameters (ParameterHandler &prm, const unsigned int id, const Parameters::Dimensionality &dimensions)
Public Attributes
enum Parameters::MaterialInteractions::MaterialInteractionsType material_interaction_type
enum Parameters::MaterialInteractions::SurfaceTensionModel surface_tension_model
SurfaceTensionParameters surface_tension_parameters
enum Parameters::MaterialInteractions::MobilityCahnHilliardModel mobility_cahn_hilliard_model
MobilityCahnHilliardParameters mobility_cahn_hilliard_parameters
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > fluid_fluid_interaction_with_material_interaction_id
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > fluid_solid_interaction_with_material_interaction_id
Detailed Description
MaterialInteractions - Class that defines physical properties due to interactions between two different materials (either fluid-fluid or fluid-solid).
Definition at line 536 of file parameters.h.
Member Enumeration Documentation
MaterialInteractionsType
enum class Parameters::MaterialInteractions::MaterialInteractionsType : std::int8_t strong
Enumerator
fluid_fluid
fluid_solid
Definition at line 541 of file parameters.h.
MobilityCahnHilliardModel
enum class Parameters::MaterialInteractions::MobilityCahnHilliardModel : std::int8_t strong
Enumerator
constant
quartic
Definition at line 557 of file parameters.h.
SurfaceTensionModel
enum class Parameters::MaterialInteractions::SurfaceTensionModel : std::int8_t strong
Enumerator
constant
linear
phase_change
Definition at line 548 of file parameters.h.
Constructor & Destructor Documentation
MaterialInteractions()
Parameters::MaterialInteractions::MaterialInteractions () default
Member Function Documentation
declare_parameters()
void Parameters::MaterialInteractions::declare_parameters (ParameterHandler & prm, unsigned int id) const
Declare the parameters.
Parameters
[in,out] prm The ParameterHandler.
[in] id The material id.
Definition at line 1426 of file parameters.cc.
References Parameters::SurfaceTensionParameters::declare_parameters(), Parameters::MobilityCahnHilliardParameters::declare_parameters(), mobility_cahn_hilliard_parameters, and surface_tension_parameters.
parse_parameters()
void Parameters::MaterialInteractions::parse_parameters (ParameterHandler & prm, const unsigned int id, const Parameters::Dimensionality & dimensions)
Parse the parameters.
Parameters
[in,out] prm The ParameterHandler.
[in] id The material id.
[in] dimensions The Dimensionality object controlling the fundamental dimensions (length, time, mass, temperature) of the problem.
Definition at line 1510 of file parameters.cc.
References constant, fluid_fluid, fluid_fluid_interaction_with_material_interaction_id, fluid_solid, fluid_solid_interaction_with_material_interaction_id, linear, material_interaction_type, mobility_cahn_hilliard_model, mobility_cahn_hilliard_parameters, Parameters::SurfaceTensionParameters::parse_parameters(), Parameters::MobilityCahnHilliardParameters::parse_parameters(), phase_change, quartic, surface_tension_model, and surface_tension_parameters.
Member Data Documentation
fluid_fluid_interaction_with_material_interaction_id
std::pair<std::pair<unsigned int, unsigned int>, unsigned int> Parameters::MaterialInteractions::fluid_fluid_interaction_with_material_interaction_id
Definition at line 565 of file parameters.h.
fluid_solid_interaction_with_material_interaction_id
std::pair<std::pair<unsigned int, unsigned int>, unsigned int> Parameters::MaterialInteractions::fluid_solid_interaction_with_material_interaction_id
Definition at line 567 of file parameters.h.
material_interaction_type
enum Parameters::MaterialInteractions::MaterialInteractionsType Parameters::MaterialInteractions::material_interaction_type
mobility_cahn_hilliard_model
enum Parameters::MaterialInteractions::MobilityCahnHilliardModel Parameters::MaterialInteractions::mobility_cahn_hilliard_model
mobility_cahn_hilliard_parameters
MobilityCahnHilliardParameters Parameters::MaterialInteractions::mobility_cahn_hilliard_parameters
Definition at line 562 of file parameters.h.
surface_tension_model
enum Parameters::MaterialInteractions::SurfaceTensionModel Parameters::MaterialInteractions::surface_tension_model
surface_tension_parameters
SurfaceTensionParameters Parameters::MaterialInteractions::surface_tension_parameters
Definition at line 554 of file parameters.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/parameters.h
/home/runner/work/lethe/lethe/source/core/parameters.cc