Lethe Open-Source Library: CouplingOperatorStokes< dim, Number > Class Template Reference
CouplingOperatorStokes< dim, Number > Class Template Reference
#include <mortar_coupling_manager.h>
Public Types
using FEPointIntegratorU = FEPointEvaluation< dim, dim, dim, Number >
using FEPointIntegratorP = FEPointEvaluation< 1, dim, dim, Number >
using u_value_type = typename FEPointIntegratorU::value_type
Public Types inherited from CouplingOperatorBase< dim, Number >
using VectorType = LinearAlgebra::distributed::Vector< Number >
Public Member Functions
CouplingOperatorStokes (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const AffineConstraints< Number > &constraints, const Quadrature< dim > quadrature, const unsigned int n_subdivisions, const double radius, const double rotate_pi, const unsigned int bid_0, const unsigned int bid_1, const double sip_factor=1.0, const bool do_pressure_gradient_term=true, const bool do_velocity_divergence_term=true)
void local_reinit (const typename Triangulation< dim >::cell_iterator &cell, const ArrayView< const Point< dim, Number > > &points) const override
void local_evaluate (const Vector< Number > &buffer, const unsigned int ptr_q, const unsigned int q_stride, Number *all_value_m) const override
void local_integrate (Vector< Number > &buffer, const unsigned int ptr_q, const unsigned int q_stride, Number *all_value_m, Number *all_value_p) const override
Public Member Functions inherited from CouplingOperatorBase< dim, Number >
CouplingOperatorBase (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const AffineConstraints< Number > &constraints, const Quadrature< dim > quadrature, const unsigned int n_subdivisions, const unsigned int n_components, const unsigned int N, const double radius, const double rotate_pi, const unsigned int bid_0, const unsigned int bid_1, const double sip_factor, const std::vector< unsigned int > relevant_dof_indices, const double penalty_factor_grad)
const AffineConstraints< Number > & get_affine_constraints () const
void vmult_add (VectorType &dst, const VectorType &src) const
void add_diagonal_entries (VectorType &diagonal) const
void add_sparsity_pattern_entries (SparsityPatternBase &dsp) const
void add_system_matrix_entries (TrilinosWrappers::SparseMatrix &system_matrix) const
Static Public Member Functions
static std::vector< unsigned int > get_relevant_dof_indices (const FiniteElement< dim > &fe)
Public Attributes
const FESystem< dim > fe_sub_u
const FESystem< dim > fe_sub_p
FEPointIntegratorU phi_u_m
FEPointIntegratorP phi_p_m
const bool do_pressure_gradient_term
const bool do_velocity_divergence_term
Additional Inherited Members
Protected Attributes inherited from CouplingOperatorBase< dim, Number >
Number penalty_factor
Number penalty_factor_grad
std::shared_ptr< MortarManager< dim > > mortar_manager_q
std::shared_ptr< MortarManager< dim > > mortar_manager_cell
const unsigned int n_components
const unsigned int N
const unsigned int bid_0
const unsigned int bid_1
const std::vector< unsigned int > relevant_dof_indices
const unsigned int n_dofs_per_cell
Utilities::MPI::NoncontiguousPartitioner partitioner
Utilities::MPI::NoncontiguousPartitioner partitioner_cell
std::vector< types::global_dof_index > dof_indices
std::vector< types::global_dof_index > dof_indices_ghost
std::vector< Number > all_penalty_parameter
std::vector< Number > all_weights
std::vector< Point< dim, Number > > all_points_ref
std::vector< Tensor< 1, dim, Number > > all_normals
AffineConstraints< Number > constraints_extended
Detailed Description
template<int dim, typename Number>
class CouplingOperatorStokes< dim, Number >
Definition at line 985 of file mortar_coupling_manager.h.
Member Typedef Documentation
FEPointIntegratorP
template<int dim, typename Number > using CouplingOperatorStokes< dim, Number >::FEPointIntegratorP = FEPointEvaluation<1, dim, dim, Number>
Definition at line 989 of file mortar_coupling_manager.h.
FEPointIntegratorU
template<int dim, typename Number > using CouplingOperatorStokes< dim, Number >::FEPointIntegratorU = FEPointEvaluation<dim, dim, dim, Number>
Definition at line 988 of file mortar_coupling_manager.h.
u_value_type
template<int dim, typename Number > using CouplingOperatorStokes< dim, Number >::u_value_type = typename FEPointIntegratorU::value_type
Definition at line 991 of file mortar_coupling_manager.h.
Constructor & Destructor Documentation
CouplingOperatorStokes()
template<int dim, typename Number > CouplingOperatorStokes< dim, Number >::CouplingOperatorStokes (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const AffineConstraints< Number > & constraints, const Quadrature< dim > quadrature, const unsigned int n_subdivisions, const double radius, const double rotate_pi, const unsigned int bid_0, const unsigned int bid_1, const double sip_factor = 1.0, const bool do_pressure_gradient_term = true, const bool do_velocity_divergence_term = true) inline
Definition at line 993 of file mortar_coupling_manager.h.
Member Function Documentation
get_relevant_dof_indices()
template<int dim, typename Number > static std::vector< unsigned int > CouplingOperatorStokes< dim, Number >::get_relevant_dof_indices (const FiniteElement< dim > & fe) inline static
Definition at line 1033 of file mortar_coupling_manager.h.
local_evaluate()
template<int dim, typename Number > void CouplingOperatorStokes< dim, Number >::local_evaluate (const Vector< Number > & buffer, const unsigned int ptr_q, const unsigned int q_stride, Number * all_value_m) const inline override virtual
Implements CouplingOperatorBase< dim, Number >.
Definition at line 1059 of file mortar_coupling_manager.h.
References CouplingOperatorBase< dim, Number >::all_normals, contract(), CouplingOperatorStokes< dim, Number >::fe_sub_p, CouplingOperatorStokes< dim, Number >::fe_sub_u, CouplingOperatorStokes< dim, Number >::phi_p_m, CouplingOperatorStokes< dim, Number >::phi_u_m, and BufferRW< T >::write().
local_integrate()
template<int dim, typename Number > void CouplingOperatorStokes< dim, Number >::local_integrate (Vector< Number > & buffer, const unsigned int ptr_q, const unsigned int q_stride, Number * all_value_m, Number * all_value_p) const inline override virtual
Implements CouplingOperatorBase< dim, Number >.
Definition at line 1097 of file mortar_coupling_manager.h.
References CouplingOperatorBase< dim, Number >::all_normals, CouplingOperatorBase< dim, Number >::all_penalty_parameter, CouplingOperatorBase< dim, Number >::all_weights, CouplingOperatorStokes< dim, Number >::do_pressure_gradient_term, CouplingOperatorStokes< dim, Number >::do_velocity_divergence_term, CouplingOperatorStokes< dim, Number >::fe_sub_p, CouplingOperatorStokes< dim, Number >::fe_sub_u, outer(), CouplingOperatorBase< dim, Number >::penalty_factor, CouplingOperatorStokes< dim, Number >::phi_p_m, and CouplingOperatorStokes< dim, Number >::phi_u_m.
local_reinit()
template<int dim, typename Number > void CouplingOperatorStokes< dim, Number >::local_reinit (const typename Triangulation< dim >::cell_iterator & cell, const ArrayView< const Point< dim, Number > > & points) const inline override virtual
Implements CouplingOperatorBase< dim, Number >.
Definition at line 1051 of file mortar_coupling_manager.h.
References CouplingOperatorStokes< dim, Number >::phi_p_m, and CouplingOperatorStokes< dim, Number >::phi_u_m.
Member Data Documentation
do_pressure_gradient_term
template<int dim, typename Number > const bool CouplingOperatorStokes< dim, Number >::do_pressure_gradient_term
Definition at line 1191 of file mortar_coupling_manager.h.
do_velocity_divergence_term
template<int dim, typename Number > const bool CouplingOperatorStokes< dim, Number >::do_velocity_divergence_term
Definition at line 1192 of file mortar_coupling_manager.h.
fe_sub_p
template<int dim, typename Number > const FESystem<dim> CouplingOperatorStokes< dim, Number >::fe_sub_p
Definition at line 1187 of file mortar_coupling_manager.h.
fe_sub_u
template<int dim, typename Number > const FESystem<dim> CouplingOperatorStokes< dim, Number >::fe_sub_u
Definition at line 1186 of file mortar_coupling_manager.h.
phi_p_m
template<int dim, typename Number > FEPointIntegratorP CouplingOperatorStokes< dim, Number >::phi_p_m mutable
Definition at line 1189 of file mortar_coupling_manager.h.
phi_u_m
template<int dim, typename Number > FEPointIntegratorU CouplingOperatorStokes< dim, Number >::phi_u_m mutable
Definition at line 1188 of file mortar_coupling_manager.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/mortar_coupling_manager.h