Lethe Open-Source Library: GLSIsothermalCompressibleNavierStokesAssemblerCore< dim > Class Template Reference
GLSIsothermalCompressibleNavierStokesAssemblerCore< dim > Class Template Reference
#include <isothermal_compressible_navier_stokes_assembler.h>
Public Member Functions
GLSIsothermalCompressibleNavierStokesAssemblerCore (const std::shared_ptr< SimulationControl > &simulation_control)
virtual void assemble_matrix (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual void assemble_rhs (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
Public Member Functions inherited from PhysicsAssemblerBase< ScratchDataType, CopyDataType >
virtual void assemble_matrix (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
virtual void assemble_rhs (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
Public Attributes
const std::shared_ptr< SimulationControl > simulation_control
Detailed Description
template<int dim>
class GLSIsothermalCompressibleNavierStokesAssemblerCore< dim >
Class that assembles the core of the isothermal compressible Navier-Stokes equations. According to the following weak form: \(\nabla \cdot (\rho \mathbf{u}) + \rho \mathbf{u} \cdot \nabla \mathbf{u} - \nabla p - \mu \nabla^2 \mathbf{u} = 0\) with a full GLS stabilization including the laplacian of the test function.
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 29 of file isothermal_compressible_navier_stokes_assembler.h.
Constructor & Destructor Documentation
GLSIsothermalCompressibleNavierStokesAssemblerCore()
template<int dim> GLSIsothermalCompressibleNavierStokesAssemblerCore< dim >::GLSIsothermalCompressibleNavierStokesAssemblerCore (const std::shared_ptr< SimulationControl > & simulation_control) inline
Definition at line 33 of file isothermal_compressible_navier_stokes_assembler.h.
Member Function Documentation
assemble_matrix()
template<int dim> void GLSIsothermalCompressibleNavierStokesAssemblerCore< dim >::assemble_matrix (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_matrix Assembles the matrix
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 13 of file isothermal_compressible_navier_stokes_assembler.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::components, NavierStokesScratchData< dim >::density, NavierStokesScratchData< dim >::density_psi, NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::dynamic_viscosity, NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, NavierStokesScratchData< dim >::laplacian_phi_u, StabilizedMethodsTensorCopyData< dim >::local_matrix, NavierStokesScratchData< dim >::mass_source, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_scaling_factor, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_jacobian, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
assemble_rhs()
template<int dim> void GLSIsothermalCompressibleNavierStokesAssemblerCore< dim >::assemble_rhs (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_rhs Assembles the rhs
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 206 of file isothermal_compressible_navier_stokes_assembler.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::density, NavierStokesScratchData< dim >::density_psi, NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::dynamic_viscosity, NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, StabilizedMethodsTensorCopyData< dim >::local_rhs, NavierStokesScratchData< dim >::mass_source, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, pressure, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_values, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_divergences, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
Member Data Documentation
simulation_control
template<int dim> const std::shared_ptr<SimulationControl> GLSIsothermalCompressibleNavierStokesAssemblerCore< dim >::simulation_control
Definition at line 56 of file isothermal_compressible_navier_stokes_assembler.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/isothermal_compressible_navier_stokes_assembler.h
/home/runner/work/lethe/lethe/source/solvers/isothermal_compressible_navier_stokes_assembler.cc