Lethe Open-Source Library: ThermalConductivityPhaseChange Class Reference
ThermalConductivityPhaseChange Class Reference
#include <thermal_conductivity_model.h>
Public Member Functions
ThermalConductivityPhaseChange (const Parameters::PhaseChange phase_change_params)
double value (const std::map< field, double > &fields_value) override
void vector_value (const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &property_vector) override
double jacobian (const std::map< field, double > &field_values, field id) override
void vector_jacobian (const std::map< field, std::vector< double > > &field_vectors, const field id, std::vector< double > &jacobian_vector) override
Public Member Functions inherited from PhysicalPropertyModel
PhysicalPropertyModel ()
bool depends_on (const field &id)
void provide_simulation_control (std::shared_ptr< SimulationControl > &p_simulation_control)
double numerical_jacobian (const std::map< field, double > &field_values, const field id)
void vector_numerical_jacobian (const std::map< field, std::vector< double > > &field_vectors, const field id, std::vector< double > &jacobian_vector)
Private Attributes
Parameters::PhaseChange p_phase_change_params
const double thermal_conductivity_s
const double thermal_conductivity_l
const double T_solidus
const double T_liquidus
Additional Inherited Members
Static Public Member Functions inherited from ThermalConductivityModel
static std::shared_ptr< ThermalConductivityModel > model_cast (const Parameters::Material &material_properties)
Protected Member Functions inherited from PhysicalPropertyModel
std::shared_ptr< SimulationControl > & get_simulation_control ()
Protected Attributes inherited from PhysicalPropertyModel
std::map< field, bool > model_depends_on
Detailed Description
Implements a phase-dependent thermal conductivity.
Definition at line 188 of file thermal_conductivity_model.h.
Constructor & Destructor Documentation
ThermalConductivityPhaseChange()
ThermalConductivityPhaseChange::ThermalConductivityPhaseChange (const Parameters::PhaseChange phase_change_params) inline
Default constructor.
Definition at line 194 of file thermal_conductivity_model.h.
References PhysicalPropertyModel::model_depends_on, and temperature.
Member Function Documentation
jacobian()
double ThermalConductivityPhaseChange::jacobian (const std::map< field, double > & field_values, field id) inline override virtual
jacobian Calculates the jacobian (the partial derivative) of the thermal conductivity with respect to a field
Parameters
field_values Value of the various fields on which the property may depend.
id Indicator of the field with respect to which the jacobian should be calculated
Returns
value of the partial derivative of the thermal conductivity with respect to the field.
Implements PhysicalPropertyModel.
Definition at line 278 of file thermal_conductivity_model.h.
References PhysicalPropertyModel::numerical_jacobian(), and temperature.
value()
double ThermalConductivityPhaseChange::value (const std::map< field, double > & fields_value) inline override virtual
value Calculates the value of the thermal conductivity
Parameters
fields_value Value of the various field on which the thermal conductivity depends.
Returns
value of the thermal conductivity calculated with the fields_value.
Implements PhysicalPropertyModel.
Definition at line 211 of file thermal_conductivity_model.h.
References calculate_liquid_fraction(), p_phase_change_params, T_liquidus, T_solidus, temperature, thermal_conductivity_l, and thermal_conductivity_s.
vector_jacobian()
void ThermalConductivityPhaseChange::vector_jacobian (const std::map< field, std::vector< double > > & field_vectors, const field id, std::vector< double > & jacobian_vector) inline override virtual
vector_jacobian Calculate the derivative of the thermal conductivity with respect to a field
Parameters
field_vectors Vector for the values of the fields used to evaluate the property
id Identifier of the field with respect to which a derivative should be calculated
jacobian Vector of the value of the derivative of the thermal conductivity with respect to the field id
Implements PhysicalPropertyModel.
Definition at line 299 of file thermal_conductivity_model.h.
References temperature, and PhysicalPropertyModel::vector_numerical_jacobian().
vector_value()
void ThermalConductivityPhaseChange::vector_value (const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & property_vector) inline override virtual
vector_value Calculates the vector value of thermal conductivities
Parameters
field_vectors Vector of properties on which the thermal conductivities depend
property_vector Values of the thermal conductivities
Implements PhysicalPropertyModel.
Definition at line 243 of file thermal_conductivity_model.h.
References calculate_liquid_fraction(), p_phase_change_params, T_liquidus, T_solidus, temperature, thermal_conductivity_l, and thermal_conductivity_s.
Member Data Documentation
p_phase_change_params
Parameters::PhaseChange ThermalConductivityPhaseChange::p_phase_change_params private
Definition at line 310 of file thermal_conductivity_model.h.
T_liquidus
const double ThermalConductivityPhaseChange::T_liquidus private
Definition at line 314 of file thermal_conductivity_model.h.
T_solidus
const double ThermalConductivityPhaseChange::T_solidus private
Definition at line 313 of file thermal_conductivity_model.h.
thermal_conductivity_l
const double ThermalConductivityPhaseChange::thermal_conductivity_l private
Definition at line 312 of file thermal_conductivity_model.h.
thermal_conductivity_s
const double ThermalConductivityPhaseChange::thermal_conductivity_s private
Definition at line 311 of file thermal_conductivity_model.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/thermal_conductivity_model.h