Lethe Open-Source Library: Insertion< dim, PropertiesIndex > Class Template Reference
Insertion< dim, PropertiesIndex > Class Template Reference abstract
#include <insertion.h>
Public Member Functions
Insertion (const std::vector< std::shared_ptr< Distribution > > &size_distribution_object_container, const parallel::distributed::Triangulation< dim > &triangulation, const DEMSolverParameters< dim > &dem_parameters)
virtual ~Insertion ()
virtual void insert (Particles::ParticleHandler< dim > &particle_handler, const parallel::distributed::Triangulation< dim > &triangulation, const DEMSolverParameters< dim > &dem_parameters)=0
virtual void serialize (boost::archive::text_oarchive &ar)=0
virtual void deserialize (boost::archive::text_iarchive &ar)=0
Protected Member Functions
void print_insertion_info (const unsigned int &inserted_this_step, const unsigned int &remained_particles, const unsigned int &particle_type, const ConditionalOStream &pcout)
void assign_particle_properties (const DEMSolverParameters< dim > &dem_parameters, const unsigned int &inserted_this_step_this_proc, const unsigned int &current_inserting_particle_type, const std::vector< Point< dim > > &insertion_points, std::vector< std::vector< double > > &particle_properties)
void calculate_insertion_domain_maximum_particle_number (const DEMSolverParameters< dim > &dem_parameters, const ConditionalOStream &pcout)
void find_cells_in_removing_box (const parallel::distributed::Triangulation< dim > &triangulation)
void remove_particles_in_box (Particles::ParticleHandler< dim > &particle_handler)
Protected Attributes
unsigned int inserted_this_step
std::vector< int > number_of_particles_directions
std::vector< double > axis_min
std::vector< double > axis_max
double maximum_diameter
unsigned int inserted_this_step_this_proc
std::vector< std::shared_ptr< Distribution > > distributions_objects
const bool removing_particles_in_region
Point< dim > p_min
Point< dim > p_max
std::set< typename Triangulation< dim >::active_cell_iterator > in_removal_box
std::set< typename Triangulation< dim >::active_cell_iterator > edge_of_removal_box
bool mark_for_update
boost::signals2::connection change_to_triangulation
Private Attributes
std::vector< double > particle_sizes
Detailed Description
template<int dim, typename PropertiesIndex>
class Insertion< dim, PropertiesIndex >
Base interface for classes that carry out the insertion of particles in the system.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Definition at line 33 of file insertion.h.
Constructor & Destructor Documentation
Insertion()
template<int dim, typename PropertiesIndex > Insertion< dim, PropertiesIndex >::Insertion (const std::vector< std::shared_ptr< Distribution > > & size_distribution_object_container, const parallel::distributed::Triangulation< dim > & triangulation, const DEMSolverParameters< dim > & dem_parameters)
Carries out the insertion of particles. This is the base class of volume_insertion, plane_insertion, list_insertion and file_insertion classes.
Parameters
size_distribution_object_container Contains all distribution for each particle type
triangulation Triangulation to access the cells in which the particles are inserted
dem_parameters DEM parameters declared in the .prm file
Definition at line 10 of file insertion.cc.
References Insertion< dim, PropertiesIndex >::change_to_triangulation, Insertion< dim, PropertiesIndex >::distributions_objects, DEMSolverParameters< dim >::insertion_info, Insertion< dim, PropertiesIndex >::mark_for_update, Insertion< dim, PropertiesIndex >::p_max, and Insertion< dim, PropertiesIndex >::p_min.
~Insertion()
template<int dim, typename PropertiesIndex > virtual Insertion< dim, PropertiesIndex >::~Insertion () inline virtual
Carries out the destruction of the insertion class.
Definition at line 55 of file insertion.h.
References Insertion< dim, PropertiesIndex >::change_to_triangulation.
Member Function Documentation
assign_particle_properties()
template<int dim, typename PropertiesIndex > void Insertion< dim, PropertiesIndex >::assign_particle_properties (const DEMSolverParameters< dim > & dem_parameters, const unsigned int & inserted_this_step_this_proc, const unsigned int & current_inserting_particle_type, const std::vector< Point< dim > > & insertion_points, std::vector< std::vector< double > > & particle_properties) protected
Carries out assigning the properties of inserted particles.
Parameters
dem_parameters DEM parameters declared in the prm file.
inserted_this_step_this_proc Number of particles that are inserted. at each insertion step on each processor. This value can change in the last insertion step to reach the desired number of particles.
current_inserting_particle_type Type of inserting particles.
insertion_points Insertion points of all inserted particles at this insertion step.
particle_properties Properties of all inserted particles at this insertion step.
Definition at line 63 of file insertion.cc.
References DEMSolverParameters< dim >::insertion_info, and DEMSolverParameters< dim >::lagrangian_physical_properties.
calculate_insertion_domain_maximum_particle_number()
template<int dim, typename PropertiesIndex > void Insertion< dim, PropertiesIndex >::calculate_insertion_domain_maximum_particle_number (const DEMSolverParameters< dim > & dem_parameters, const ConditionalOStream & pcout) protected
Carries out finding the maximum number of inserted particles based on the insertion box size. If the requested number of particles for insertion in each insertion step is larger than this maximum, it is limited to this value and a warning is printed.
Parameters
dem_parameters DEM parameters declared in the .prm file
pcout Printing in parallel
Definition at line 135 of file insertion.cc.
References DEMSolverParameters< dim >::insertion_info.
deserialize()
template<int dim, typename PropertiesIndex > virtual void Insertion< dim, PropertiesIndex >::deserialize (boost::archive::text_iarchive & ar) pure virtual
Deserialize an input archive to the insertion object. Is being used when restarting a simulation. This function is overridden by volume_insertion, plane_insertion, list_insertion and from_file_insertion classes.
Parameters
ar Input archive where the attributes are stored.
Implemented in InsertionFile< dim, PropertiesIndex >, InsertionList< dim, PropertiesIndex >, InsertionPlane< dim, PropertiesIndex >, and InsertionVolume< dim, PropertiesIndex >.
find_cells_in_removing_box()
template<int dim, typename PropertiesIndex > void Insertion< dim, PropertiesIndex >::find_cells_in_removing_box (const parallel::distributed::Triangulation< dim > & triangulation) protected
Find every cell that are completely and partially inside de the clearing box. For the cell completely inside the box, all the particles will be deleted. For those partially inside, a fine verification is required.
Parameters
triangulation Triangulation to access the cells in which the particles deleted.
Definition at line 237 of file insertion.cc.
References point_nd_to_3d().
insert()
template<int dim, typename PropertiesIndex > virtual void Insertion< dim, PropertiesIndex >::insert (Particles::ParticleHandler< dim > & particle_handler, const parallel::distributed::Triangulation< dim > & triangulation, const DEMSolverParameters< dim > & dem_parameters) pure virtual
This function is overridden by the volume_insertion, plane_insertion, list_insertion and file_insertion classes.
Parameters
particle_handler The particle handler of particles which are being inserted
triangulation Triangulation to access the cells in which the particles are inserted
dem_parameters DEM parameters declared in the .prm file
Implemented in InsertionFile< dim, PropertiesIndex >, InsertionList< dim, PropertiesIndex >, InsertionPlane< dim, PropertiesIndex >, and InsertionVolume< dim, PropertiesIndex >.
print_insertion_info()
template<int dim, typename PropertiesIndex > void Insertion< dim, PropertiesIndex >::print_insertion_info (const unsigned int & inserted_this_step, const unsigned int & remained_particles, const unsigned int & particle_type, const ConditionalOStream & pcout) protected
Print information about the particles that have been inserted during an insertion time step.
Parameters
inserted_this_step Number of particles that are inserted at each insertion step.
remained_particles Number of remained particles going to be inserted in future insertions
particle_type Inserted particle type
pcout Printing in parallel
Definition at line 44 of file insertion.cc.
References announce_string().
remove_particles_in_box()
template<int dim, typename PropertiesIndex > void Insertion< dim, PropertiesIndex >::remove_particles_in_box (Particles::ParticleHandler< dim > & particle_handler) protected
Remove every particle located inside a predefined zone. Currently, the zone is defined by a box.
Parameters
particle_handler The particle handler of particles which are being removed.
Definition at line 289 of file insertion.cc.
References point_nd_to_3d().
serialize()
template<int dim, typename PropertiesIndex > virtual void Insertion< dim, PropertiesIndex >::serialize (boost::archive::text_oarchive & ar) pure virtual
Serialize the insertion object to an output archive. Is being used when checkpointing a simulation. This function is overridden by volume_insertion, plane_insertion, list_insertion and file_insertion classes.
Parameters
ar Output archive where the attributes are stored.
Implemented in InsertionFile< dim, PropertiesIndex >, InsertionList< dim, PropertiesIndex >, InsertionPlane< dim, PropertiesIndex >, and InsertionVolume< dim, PropertiesIndex >.
Member Data Documentation
axis_max
template<int dim, typename PropertiesIndex > std::vector<double> Insertion< dim, PropertiesIndex >::axis_max protected
Definition at line 189 of file insertion.h.
axis_min
template<int dim, typename PropertiesIndex > std::vector<double> Insertion< dim, PropertiesIndex >::axis_min protected
Definition at line 189 of file insertion.h.
change_to_triangulation
template<int dim, typename PropertiesIndex > boost::signals2::connection Insertion< dim, PropertiesIndex >::change_to_triangulation protected
Definition at line 214 of file insertion.h.
distributions_objects
template<int dim, typename PropertiesIndex > std::vector<std::shared_ptr<Distribution> > Insertion< dim, PropertiesIndex >::distributions_objects protected
Definition at line 199 of file insertion.h.
edge_of_removal_box
template<int dim, typename PropertiesIndex > std::set<typename Triangulation<dim>::active_cell_iterator> Insertion< dim, PropertiesIndex >::edge_of_removal_box protected
Definition at line 210 of file insertion.h.
in_removal_box
template<int dim, typename PropertiesIndex > std::set<typename Triangulation<dim>::active_cell_iterator> Insertion< dim, PropertiesIndex >::in_removal_box protected
Definition at line 208 of file insertion.h.
inserted_this_step
template<int dim, typename PropertiesIndex > unsigned int Insertion< dim, PropertiesIndex >::inserted_this_step protected
Definition at line 181 of file insertion.h.
inserted_this_step_this_proc
template<int dim, typename PropertiesIndex > unsigned int Insertion< dim, PropertiesIndex >::inserted_this_step_this_proc protected
Definition at line 195 of file insertion.h.
mark_for_update
template<int dim, typename PropertiesIndex > bool Insertion< dim, PropertiesIndex >::mark_for_update protected
Definition at line 213 of file insertion.h.
maximum_diameter
template<int dim, typename PropertiesIndex > double Insertion< dim, PropertiesIndex >::maximum_diameter protected
Definition at line 192 of file insertion.h.
number_of_particles_directions
template<int dim, typename PropertiesIndex > std::vector<int> Insertion< dim, PropertiesIndex >::number_of_particles_directions protected
Definition at line 184 of file insertion.h.
p_max
template<int dim, typename PropertiesIndex > Point<dim> Insertion< dim, PropertiesIndex >::p_max protected
Definition at line 205 of file insertion.h.
p_min
template<int dim, typename PropertiesIndex > Point<dim> Insertion< dim, PropertiesIndex >::p_min protected
Definition at line 205 of file insertion.h.
particle_sizes
template<int dim, typename PropertiesIndex > std::vector<double> Insertion< dim, PropertiesIndex >::particle_sizes private
Definition at line 218 of file insertion.h.
removing_particles_in_region
template<int dim, typename PropertiesIndex > const bool Insertion< dim, PropertiesIndex >::removing_particles_in_region protected
Definition at line 202 of file insertion.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/insertion.h
/home/runner/work/lethe/lethe/source/dem/insertion.cc