Lethe Open-Source Library: FluidDynamicsVANS< dim > Class Template Reference
FluidDynamicsVANS< dim > Class Template Reference
#include <fluid_dynamics_vans.h>
Public Member Functions
FluidDynamicsVANS (CFDDEMSimulationParameters< dim > &nsparam)
~FluidDynamicsVANS ()
virtual void solve () override
Public Member Functions inherited from FluidDynamicsMatrixBased< dim >
FluidDynamicsMatrixBased (SimulationParameters< dim > &nsparam)
~FluidDynamicsMatrixBased ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Protected Member Functions
virtual void setup_dofs () override
virtual void iterate () override
void initialize_void_fraction ()
void calculate_void_fraction (const double time, bool load_balance_step)
void vertices_cell_mapping ()
virtual void monitor_mass_conservation ()
virtual void finish_time_step_fd ()
void assemble_system_matrix () override
void assemble_system_rhs () override
void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
void setup_assemblers () override
void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data) override
void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual void output_field_hook (DataOut< dim > &data_out) override
void percolate_void_fraction ()
Protected Member Functions inherited from FluidDynamicsMatrixBased< dim >
virtual void setup_dofs_fd () override
virtual void set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart=false) override
virtual void update_multiphysics_time_average_solution () override
void setup_preconditioner () override
void define_dynamic_zero_constraints ()
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Protected Member Functions inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual GlobalVectorType & get_evaluation_point () override
virtual GlobalVectorType & get_local_evaluation_point () override
virtual GlobalVectorType & get_newton_update () override
virtual GlobalVectorType & get_present_solution () override
virtual GlobalVectorType & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart=false)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void postprocess_fd (bool first_iteration)
virtual void update_solutions_for_multiphysics ()
void postprocessing_forces (const GlobalVectorType &evaluation_point)
void postprocessing_torques (const GlobalVectorType &evaluation_point)
virtual void dynamic_flow_control ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
virtual void read_checkpoint ()
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
virtual void write_checkpoint ()
void write_output_results (const GlobalVectorType &solution)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
GlobalVectorType init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes
CFDDEMSimulationParameters< dim > cfd_dem_simulation_parameters
DoFHandler< dim > void_fraction_dof_handler
FE_Q< dim > fe_void_fraction
MappingQGeneric< dim > particle_mapping
IndexSet locally_owned_dofs_voidfraction
IndexSet locally_relevant_dofs_voidfraction
std::vector< GlobalVectorType > previous_void_fraction
GlobalVectorType nodal_void_fraction_relevant
GlobalVectorType nodal_void_fraction_owned
std::vector< std::shared_ptr< ParticleFluidAssemblerBase< dim > > > particle_fluid_assemblers
TrilinosWrappers::SparseMatrix system_matrix_void_fraction
GlobalVectorType system_rhs_void_fraction
TrilinosWrappers::SparseMatrix complete_system_matrix_void_fraction
GlobalVectorType complete_system_rhs_void_fraction
TrilinosWrappers::SparseMatrix mass_matrix
GlobalVectorType diagonal_of_mass_matrix
IndexSet active_set
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
AffineConstraints< double > void_fraction_constraints
const bool PSPG = true
const bool SUPG = true
const double GLS_u_scale = 1
double pressure_drop
bool has_periodic_boundaries
Tensor< 1, dim > periodic_offset
unsigned int periodic_direction
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_cell
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_periodic_cell
Particles::ParticleHandler< dim, dim > particle_handler
Protected Attributes inherited from FluidDynamicsMatrixBased< dim >
TrilinosWrappers::SparseMatrix system_matrix
Protected Attributes inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
GlobalVectorType present_solution
GlobalVectorType system_rhs
std::vector< GlobalVectorType > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, GlobalVectorType, IndexSet > > average_velocities
GlobalVectorType average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Private Member Functions
void assemble_mass_matrix_diagonal (TrilinosWrappers::SparseMatrix &mass_matrix)
void update_solution_and_constraints ()
void particle_centered_method ()
void quadrature_centered_sphere_method (bool load_balance_step)
void satellite_point_method ()
void solve_L2_system_void_fraction ()
void read_dem ()
Tensor< 1, dim > get_periodic_offset_distance (unsigned int boundary_id) const
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class FluidDynamicsVANS< dim >
A solver class for the VANS equation using GLS stabilization
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Author
Toni EL Geitani, 2020
Definition at line 101 of file fluid_dynamics_vans.h.
Constructor & Destructor Documentation
FluidDynamicsVANS()
template<int dim> FluidDynamicsVANS< dim >::FluidDynamicsVANS (CFDDEMSimulationParameters< dim > & nsparam)
Definition at line 16 of file fluid_dynamics_vans.cc.
References FluidDynamicsVANS< dim >::cfd_dem_simulation_parameters, FluidDynamicsVANS< dim >::has_periodic_boundaries, maximum_number_of_previous_solutions(), BoundaryConditions::periodic, FluidDynamicsVANS< dim >::previous_void_fraction, and DEM::type.
~FluidDynamicsVANS()
template<int dim> FluidDynamicsVANS< dim >::~FluidDynamicsVANS
Definition at line 49 of file fluid_dynamics_vans.cc.
Member Function Documentation
assemble_local_system_matrix()
template<int dim> void FluidDynamicsVANS< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override protected virtual
Assembles the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 1628 of file fluid_dynamics_vans.cc.
References NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_particle_fluid_interactions(), NavierStokesScratchData< dim >::reinit_void_fraction(), and StabilizedMethodsTensorCopyData< dim >::reset().
assemble_local_system_rhs()
template<int dim> void FluidDynamicsVANS< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override protected virtual
Assembles the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 1736 of file fluid_dynamics_vans.cc.
References NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_particle_fluid_interactions(), NavierStokesScratchData< dim >::reinit_void_fraction(), and StabilizedMethodsTensorCopyData< dim >::reset().
assemble_mass_matrix_diagonal()
template<int dim> void FluidDynamicsVANS< dim >::assemble_mass_matrix_diagonal (TrilinosWrappers::SparseMatrix & mass_matrix) private
Definition at line 298 of file fluid_dynamics_vans.cc.
assemble_system_matrix()
template<int dim> void FluidDynamicsVANS< dim >::assemble_system_matrix override protected virtual
Assembles the matrix associated with the solver.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 1589 of file fluid_dynamics_vans.cc.
References FluidDynamicsVANS< dim >::assemble_local_system_matrix(), and FluidDynamicsVANS< dim >::copy_local_matrix_to_global_matrix().
assemble_system_rhs()
template<int dim> void FluidDynamicsVANS< dim >::assemble_system_rhs override protected virtual
Assembles the rhs associated with the solver.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 1694 of file fluid_dynamics_vans.cc.
References FluidDynamicsVANS< dim >::assemble_local_system_rhs(), and FluidDynamicsVANS< dim >::copy_local_rhs_to_global_rhs().
calculate_void_fraction()
template<int dim> void FluidDynamicsVANS< dim >::calculate_void_fraction (const double time, bool load_balance_step) protected
Definition at line 255 of file fluid_dynamics_vans.cc.
References announce_string(), Parameters::function, Parameters::pcm, Parameters::qcm, and Parameters::spm.
copy_local_matrix_to_global_matrix()
template<int dim> void FluidDynamicsVANS< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > & copy_data) override protected virtual
Copies local cell information to global matrix.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 1680 of file fluid_dynamics_vans.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void FluidDynamicsVANS< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > & copy_data) override protected virtual
Copies local cell rhs information to global rhs.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 1789 of file fluid_dynamics_vans.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_rhs.
finish_time_step_fd()
template<int dim> void FluidDynamicsVANS< dim >::finish_time_step_fd protected virtual
finish_time_step Finishes the time step Post-processing and time stepping
Definition at line 166 of file fluid_dynamics_vans.cc.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::finish_time_step().
get_periodic_offset_distance()
template<int dim> Tensor<1, dim> FluidDynamicsVANS< dim >::get_periodic_offset_distance (unsigned int boundary_id) const inline private
This function calculates and returns the periodic offset distance of the domain which is needed for the periodic boundary conditions using the QCM or SPM for void fraction with the GLS VANS/CFD-DEM solver. The distance is based on one of the periodic boundaries and all particle location shifted by this distance is according to this periodic boundary.
Parameters
boundary_id The id of one of the periodic boundaries
Returns
The periodic offset distance
Definition at line 145 of file fluid_dynamics_vans.h.
initialize_void_fraction()
template<int dim> void FluidDynamicsVANS< dim >::initialize_void_fraction protected
Definition at line 246 of file fluid_dynamics_vans.cc.
iterate()
template<int dim> void FluidDynamicsVANS< dim >::iterate override protected virtual
iterate Do a regular CFD iteration
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 1411 of file fluid_dynamics_vans.cc.
References announce_string(), and PhysicsSolver< VectorType >::solve_non_linear_system().
monitor_mass_conservation()
template<int dim> void FluidDynamicsVANS< dim >::monitor_mass_conservation protected virtual
Definition at line 1812 of file fluid_dynamics_vans.cc.
References Parameters::SimulationControl::bdf1, Parameters::SimulationControl::bdf2, Parameters::SimulationControl::bdf3, and Parameters::SimulationControl::steady.
output_field_hook()
template<int dim> void FluidDynamicsVANS< dim >::output_field_hook (DataOut< dim > & data_out) override protected virtual
a function for adding data vectors to the data_out object for post_processing additional results
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 1803 of file fluid_dynamics_vans.cc.
particle_centered_method()
template<int dim> void FluidDynamicsVANS< dim >::particle_centered_method private
Definition at line 457 of file fluid_dynamics_vans.cc.
References compute_cell_measure_with_JxW(), and DEM::dp.
percolate_void_fraction()
template<int dim> void FluidDynamicsVANS< dim >::percolate_void_fraction protected
Definition at line 155 of file fluid_dynamics_vans.cc.
quadrature_centered_sphere_method()
template<int dim> void FluidDynamicsVANS< dim >::quadrature_centered_sphere_method (bool load_balance_step) private
Definition at line 551 of file fluid_dynamics_vans.cc.
References compute_cell_measure_with_JxW(), DEM::dp, particle_circle_intersection_2d(), particle_sphere_intersection_3d(), and DEM::volumetric_contribution.
read_dem()
template<int dim> void FluidDynamicsVANS< dim >::read_dem private
Definition at line 177 of file fluid_dynamics_vans.cc.
satellite_point_method()
template<int dim> void FluidDynamicsVANS< dim >::satellite_point_method private
Definition at line 1096 of file fluid_dynamics_vans.cc.
References compute_cell_measure_with_JxW(), and DEM::dp.
setup_assemblers()
template<int dim> void FluidDynamicsVANS< dim >::setup_assemblers override protected virtual
sets up the vector of assembler functions
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 1422 of file fluid_dynamics_vans.cc.
References Parameters::beetstra, Parameters::dallavalle, Parameters::difelice, BoundaryConditions::function_weak, Parameters::gidaspow, is_bdf(), Parameters::kochhill, Parameters::modelA, Parameters::modelB, BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::pressure, and Parameters::rong.
setup_dofs()
template<int dim> void FluidDynamicsVANS< dim >::setup_dofs override protected virtual
associates the degrees of freedom to each vertex of the finite elements and initialize the void fraction
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 57 of file fluid_dynamics_vans.cc.
References BoundaryConditions::periodic, Parameters::qcm, NavierStokesBase< dim, GlobalVectorType, IndexSet >::setup_dofs(), Parameters::spm, and DEM::type.
solve()
template<int dim> void FluidDynamicsVANS< dim >::solve override virtual
solve Solves the Navier-Stokes problem
This functions solves the problem defined by the Navier-Stokes parameter by iterating through time or through the mesh refinements.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Reimplemented in CFDDEMSolver< dim >.
Definition at line 1985 of file fluid_dynamics_vans.cc.
References read_mesh_and_manifolds(), NavierStokesBase< dim, VectorType, DofsType >::refine_mesh(), and LetheGridTools::vertices_cell_mapping().
solve_L2_system_void_fraction()
template<int dim> void FluidDynamicsVANS< dim >::solve_L2_system_void_fraction private
Definition at line 1336 of file fluid_dynamics_vans.cc.
References fluid_dynamics, and Parameters::quiet.
update_solution_and_constraints()
template<int dim> void FluidDynamicsVANS< dim >::update_solution_and_constraints private
Definition at line 330 of file fluid_dynamics_vans.cc.
References BoundaryConditions::periodic, Parameters::qcm, Parameters::spm, and DEM::type.
vertices_cell_mapping()
template<int dim> void FluidDynamicsVANS< dim >::vertices_cell_mapping protected
Definition at line 442 of file fluid_dynamics_vans.cc.
References LetheGridTools::vertices_cell_mapping(), and LetheGridTools::vertices_cell_mapping_with_periodic_boundaries().
Member Data Documentation
active_set
template<int dim> IndexSet FluidDynamicsVANS< dim >::active_set protected
Definition at line 339 of file fluid_dynamics_vans.h.
cfd_dem_simulation_parameters
template<int dim> CFDDEMSimulationParameters<dim> FluidDynamicsVANS< dim >::cfd_dem_simulation_parameters protected
Member Variables
Definition at line 313 of file fluid_dynamics_vans.h.
complete_system_matrix_void_fraction
template<int dim> TrilinosWrappers::SparseMatrix FluidDynamicsVANS< dim >::complete_system_matrix_void_fraction protected
Definition at line 335 of file fluid_dynamics_vans.h.
complete_system_rhs_void_fraction
template<int dim> GlobalVectorType FluidDynamicsVANS< dim >::complete_system_rhs_void_fraction protected
Definition at line 336 of file fluid_dynamics_vans.h.
diagonal_of_mass_matrix
template<int dim> GlobalVectorType FluidDynamicsVANS< dim >::diagonal_of_mass_matrix protected
Definition at line 338 of file fluid_dynamics_vans.h.
fe_void_fraction
template<int dim> FE_Q<dim> FluidDynamicsVANS< dim >::fe_void_fraction protected
Definition at line 316 of file fluid_dynamics_vans.h.
GLS_u_scale
template<int dim> const double FluidDynamicsVANS< dim >::GLS_u_scale = 1 protected
Definition at line 346 of file fluid_dynamics_vans.h.
has_periodic_boundaries
template<int dim> bool FluidDynamicsVANS< dim >::has_periodic_boundaries protected
Definition at line 349 of file fluid_dynamics_vans.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> FluidDynamicsVANS< dim >::ilu_preconditioner protected
Definition at line 341 of file fluid_dynamics_vans.h.
locally_owned_dofs_voidfraction
template<int dim> IndexSet FluidDynamicsVANS< dim >::locally_owned_dofs_voidfraction protected
Definition at line 320 of file fluid_dynamics_vans.h.
locally_relevant_dofs_voidfraction
template<int dim> IndexSet FluidDynamicsVANS< dim >::locally_relevant_dofs_voidfraction protected
Definition at line 321 of file fluid_dynamics_vans.h.
mass_matrix
template<int dim> TrilinosWrappers::SparseMatrix FluidDynamicsVANS< dim >::mass_matrix protected
Definition at line 337 of file fluid_dynamics_vans.h.
nodal_void_fraction_owned
template<int dim> GlobalVectorType FluidDynamicsVANS< dim >::nodal_void_fraction_owned protected
Definition at line 327 of file fluid_dynamics_vans.h.
nodal_void_fraction_relevant
template<int dim> GlobalVectorType FluidDynamicsVANS< dim >::nodal_void_fraction_relevant protected
Definition at line 326 of file fluid_dynamics_vans.h.
particle_fluid_assemblers
template<int dim> std::vector<std::shared_ptr<ParticleFluidAssemblerBase<dim> > > FluidDynamicsVANS< dim >::particle_fluid_assemblers protected
Definition at line 331 of file fluid_dynamics_vans.h.
particle_handler
template<int dim> Particles::ParticleHandler<dim, dim> FluidDynamicsVANS< dim >::particle_handler protected
Definition at line 361 of file fluid_dynamics_vans.h.
particle_mapping
template<int dim> MappingQGeneric<dim> FluidDynamicsVANS< dim >::particle_mapping protected
Definition at line 318 of file fluid_dynamics_vans.h.
periodic_direction
template<int dim> unsigned int FluidDynamicsVANS< dim >::periodic_direction protected
Definition at line 351 of file fluid_dynamics_vans.h.
periodic_offset
template<int dim> Tensor<1, dim> FluidDynamicsVANS< dim >::periodic_offset protected
Definition at line 350 of file fluid_dynamics_vans.h.
pressure_drop
template<int dim> double FluidDynamicsVANS< dim >::pressure_drop protected
Definition at line 347 of file fluid_dynamics_vans.h.
previous_void_fraction
template<int dim> std::vector<GlobalVectorType> FluidDynamicsVANS< dim >::previous_void_fraction protected
Definition at line 324 of file fluid_dynamics_vans.h.
PSPG
template<int dim> const bool FluidDynamicsVANS< dim >::PSPG = true protected
Definition at line 344 of file fluid_dynamics_vans.h.
SUPG
template<int dim> const bool FluidDynamicsVANS< dim >::SUPG = true protected
Definition at line 345 of file fluid_dynamics_vans.h.
system_matrix_void_fraction
template<int dim> TrilinosWrappers::SparseMatrix FluidDynamicsVANS< dim >::system_matrix_void_fraction protected
Definition at line 333 of file fluid_dynamics_vans.h.
system_rhs_void_fraction
template<int dim> GlobalVectorType FluidDynamicsVANS< dim >::system_rhs_void_fraction protected
Definition at line 334 of file fluid_dynamics_vans.h.
vertices_to_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > FluidDynamicsVANS< dim >::vertices_to_cell protected
Definition at line 355 of file fluid_dynamics_vans.h.
vertices_to_periodic_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > FluidDynamicsVANS< dim >::vertices_to_periodic_cell protected
Definition at line 358 of file fluid_dynamics_vans.h.
void_fraction_constraints
template<int dim> AffineConstraints<double> FluidDynamicsVANS< dim >::void_fraction_constraints protected
Definition at line 342 of file fluid_dynamics_vans.h.
void_fraction_dof_handler
template<int dim> DoFHandler<dim> FluidDynamicsVANS< dim >::void_fraction_dof_handler protected
Definition at line 315 of file fluid_dynamics_vans.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/fluid_dynamics_vans.h
/home/runner/work/lethe/lethe/source/fem-dem/fluid_dynamics_vans.cc