Lethe Open-Source Library: PhaseChangeRheology Class Reference
PhaseChangeRheology Class Reference
#include <rheological_model.h>
Public Member Functions
PhaseChangeRheology (const Parameters::PhaseChange p_phase_change_parameters)
double value (const std::map< field, double > &) override
void vector_value (const std::map< field, std::vector< double > > &, std::vector< double > &property_vector) override
double jacobian (const std::map< field, double > &, field) override
void vector_jacobian (const std::map< field, std::vector< double > > &, const field, std::vector< double > &jacobian_vector) override
double get_kinematic_viscosity_scale () const override
double get_dynamic_viscosity (const double &p_density_ref, const std::map< field, double > &field_values) const override
void get_dynamic_viscosity_vector (const double &p_density_ref, const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &property_vector) override
double get_kinematic_viscosity_for_stabilization (const std::map< field, double > &) override
void get_kinematic_viscosity_for_stabilization_vector (const std::map< field, std::vector< double > > &, std::vector< double > &property_vector) override
virtual double get_dynamic_viscosity_for_stabilization (const double &p_density_ref, const std::map< field, double > &) override
virtual void get_dynamic_viscosity_for_stabilization_vector (const double &p_density_ref, const std::map< field, std::vector< double > > &, std::vector< double > &property_vector) override
Public Member Functions inherited from RheologicalModel
RheologicalModel ()
virtual double get_n () const
virtual void set_n (const double &)
virtual double get_kinematic_viscosity () const
virtual void set_kinematic_viscosity (const double &)
virtual void set_dynamic_viscosity (const double &)
bool is_non_newtonian_rheological_model () const
bool is_phase_change_rheological_model () const
Public Member Functions inherited from PhysicalPropertyModel
PhysicalPropertyModel ()
virtual ~PhysicalPropertyModel ()
bool depends_on (const field &id)
void provide_simulation_control (std::shared_ptr< SimulationControl > &p_simulation_control)
double numerical_jacobian (const std::map< field, double > &field_values, const field id)
void vector_numerical_jacobian (const std::map< field, std::vector< double > > &field_vectors, const field id, std::vector< double > &jacobian_vector)
Private Member Functions
double kinematic_viscosity (const double T) const
Private Attributes
Parameters::PhaseChange param
Additional Inherited Members
Static Public Member Functions inherited from RheologicalModel
static std::shared_ptr< RheologicalModel > model_cast (const Parameters::Material &material_properties)
Protected Member Functions inherited from PhysicalPropertyModel
std::shared_ptr< SimulationControl > & get_simulation_control ()
Protected Attributes inherited from RheologicalModel
bool non_newtonian_rheological_model = false
bool phase_change_rheological_model = false
Protected Attributes inherited from PhysicalPropertyModel
std::map< field, bool > model_depends_on
Detailed Description
Definition at line 697 of file rheological_model.h.
Constructor & Destructor Documentation
PhaseChangeRheology()
PhaseChangeRheology::PhaseChangeRheology (const Parameters::PhaseChange p_phase_change_parameters) inline
Parameter constructor.
Parameters
p_phase_change parameters The parameters needed by the phase change rheology
Definition at line 706 of file rheological_model.h.
References PhysicalPropertyModel::model_depends_on, RheologicalModel::phase_change_rheological_model, and temperature.
Member Function Documentation
get_dynamic_viscosity()
double PhaseChangeRheology::get_dynamic_viscosity (const double & p_density_ref, const std::map< field, double > & field_values) const inline override virtual
Calculates the dynamic viscosity, if a kinematic viscosity and a reference density value is specified.
Parameters
p_density_ref The density of the fluid at the reference state
field_values Value of the various fields on which the property may depend.
Implements RheologicalModel.
Definition at line 776 of file rheological_model.h.
References kinematic_viscosity(), and temperature.
get_dynamic_viscosity_for_stabilization()
double PhaseChangeRheology::get_dynamic_viscosity_for_stabilization (const double & p_density_ref, const std::map< field, double > &) override virtual
Calculates the dynamic viscosity used in PSPG and SUPG stabilization terms.
Calculates the dynamic viscosity used in PSPG and SUPG stabilizations.
Parameters
[in] p_density_ref The density of the fluid at the reference state
[in] field_values Value of the various fields on which the property may depend.
Reimplemented from RheologicalModel.
Definition at line 244 of file rheological_model.cc.
References Parameters::PhaseChange::kinematic_viscosity_l, and param.
get_dynamic_viscosity_for_stabilization_vector()
void PhaseChangeRheology::get_dynamic_viscosity_for_stabilization_vector (const double & p_density_ref, const std::map< field, std::vector< double > > & , std::vector< double > & property_vector) override virtual
Calculates the vector values of the dynamic viscosity used in PSPG and SUPG stabilization terms.
Calculates the vector values of the dynamic viscosity used in PSPG and SUPG stabilizations.
Parameters
[in] p_density_ref The density of the fluid at the reference state
[in] field_vectors Value of the fields on which the property may depend on.
[out] property_vector Vector of computed viscosities.
Reimplemented from RheologicalModel.
Definition at line 259 of file rheological_model.cc.
References Parameters::PhaseChange::kinematic_viscosity_l, and param.
get_dynamic_viscosity_vector()
void PhaseChangeRheology::get_dynamic_viscosity_vector (const double & p_density_ref, const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & property_vector) inline override virtual
Calculates the vector values of the dynamic viscosity.
Parameters
p_density_ref The density of the fluid at the reference state
field_vectors Values of the field on which the dynamic viscosity may depend on.
Implements RheologicalModel.
Definition at line 794 of file rheological_model.h.
References kinematic_viscosity(), and temperature.
get_kinematic_viscosity_for_stabilization()
double PhaseChangeRheology::get_kinematic_viscosity_for_stabilization (const std::map< field, double > &) override virtual
Calculates the kinematic viscosity used in PSPG and SUPG stabilization terms.
Calculates the kinematic viscosity used in PSPG and SUPG stabilizations.
Parameters
[in] field_values Value of the various fields on which the property may depend.
Reimplemented from RheologicalModel.
Definition at line 215 of file rheological_model.cc.
References Parameters::PhaseChange::kinematic_viscosity_l, and param.
get_kinematic_viscosity_for_stabilization_vector()
void PhaseChangeRheology::get_kinematic_viscosity_for_stabilization_vector (const std::map< field, std::vector< double > > & , std::vector< double > & property_vector) override virtual
Calculates the vector values of the kinematic viscosity used in PSPG and SUPG stabilization terms.
Calculates the vector values of the kinematic viscosity used in PSPG and SUPG stabilizations.
Parameters
[in] field_vectors Value of the fields on which the property may depend on.
[out] property_vector Vector of computed viscosities.
Reimplemented from RheologicalModel.
Definition at line 228 of file rheological_model.cc.
References Parameters::PhaseChange::kinematic_viscosity_l, and param.
get_kinematic_viscosity_scale()
double PhaseChangeRheology::get_kinematic_viscosity_scale () const inline override virtual
Returns the kinematic viscosity scale.
Reimplemented from RheologicalModel.
Definition at line 770 of file rheological_model.h.
References Parameters::PhaseChange::kinematic_viscosity_l, and param.
jacobian()
double PhaseChangeRheology::jacobian (const std::map< field, double > & field_values, field id) override virtual
jacobian Calculates the jacobian (the partial derivative) of the kinematic viscosity with respect to a field
Parameters
field_values Value of the various fields on which the property may depend. The constant kinematic viscosity does not depend on anything.
id Indicator of the field with respect to which the jacobian should be calculated
Returns
value of the partial derivative of the kinematic viscosity with respect to the field.
Implements PhysicalPropertyModel.
Definition at line 183 of file rheological_model.cc.
References PhysicalPropertyModel::numerical_jacobian(), and temperature.
kinematic_viscosity()
double PhaseChangeRheology::kinematic_viscosity (const double T) const inline private
kinematic_viscosity Calculates the kinematic viscosity from the temperature using the liquid fraction
Parameters
T value of the temperature
Returns
value of the kinematic viscosity
Definition at line 863 of file rheological_model.h.
References Parameters::PhaseChange::kinematic_viscosity_l, Parameters::PhaseChange::kinematic_viscosity_s, param, Parameters::PhaseChange::T_liquidus, and Parameters::PhaseChange::T_solidus.
value()
double PhaseChangeRheology::value (const std::map< field, double > & field_values) override virtual
Returns the kinematic viscosity.
Parameters
field_values Values of the field on which the kinematic viscosity may depend on. For the constant kinematic viscosity, the kinematic viscosity does not depend on anything.
Implements PhysicalPropertyModel.
Definition at line 155 of file rheological_model.cc.
References kinematic_viscosity(), and temperature.
vector_jacobian()
void PhaseChangeRheology::vector_jacobian (const std::map< field, std::vector< double > > & field_vectors, const field id, std::vector< double > & jacobian_vector) override virtual
vector_jacobian Calculate the derivative of the with respect to a field
Parameters
field_vectors Vector for the values of the fields used to evaluate the property
id Identifier of the field with respect to which a derivative should be calculated
jacobian Vector of the value of the derivative of the kinematic viscosity with respect to the field id
Implements PhysicalPropertyModel.
Definition at line 198 of file rheological_model.cc.
References temperature, and PhysicalPropertyModel::vector_numerical_jacobian().
vector_value()
void PhaseChangeRheology::vector_value (const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & property_vector) override virtual
vector_value Calculates the vector values of the kinematic viscosity.
Parameters
field_vectors Values of the field on which the kinematic viscosity may depend on. These are not used for the constant kinematic viscosity.
Implements PhysicalPropertyModel.
Definition at line 166 of file rheological_model.cc.
References kinematic_viscosity(), and temperature.
Member Data Documentation
param
Parameters::PhaseChange PhaseChangeRheology::param private
Definition at line 875 of file rheological_model.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/rheological_model.h
/home/runner/work/lethe/lethe/source/core/rheological_model.cc