Lethe Open-Source Library: IBParticlesDEM< dim > Class Template Reference
IBParticlesDEM< dim > Class Template Reference
#include <ib_particles_dem.h>
Classes
struct BoundaryCellsInfo
struct ContactInfo
struct DefaultDBL_MAX
struct DefaultUINT_MAX
struct ObjectProperties
Public Member Functions
void initialize (const std::shared_ptr< Parameters::IBParticles< dim > > &p_nsparam, const std::shared_ptr< Parameters::Lagrangian::FloatingWalls< dim > > floating_walls_parameters, const MPI_Comm &mpi_communicator_input, const std::vector< IBParticle< dim > > &particles)
void update_particles (const std::vector< IBParticle< dim > > &particles, double time)
void integrate_particles_motion (const double dt, const double h_max, const double h_min, const double rho, const double mu)
void calculate_pp_contact_force (const double dt_dem, std::vector< Tensor< 1, 3 > > &contact_force, std::vector< Tensor< 1, 3 > > &contact_torque)
void update_contact_candidates ()
void calculate_pw_contact_force (const double dt_dem, std::vector< Tensor< 1, 3 > > &contact_force, std::vector< Tensor< 1, 3 > > &contact_torque)
void calculate_force_model (const double normal_overlap, ContactInfo &contact_info, Point< 3 > &contact_point, Tensor< 1, 3 > &contact_normal, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &rolling_resistance_torque, Point< dim > &particle_one_position, Tensor< 1, 3 > &particle_one_velocity, Tensor< 1, 3 > &particle_one_omega, const ObjectProperties particle_one_properties, Point< dim > &particle_two_position, Tensor< 1, 3 > &particle_two_velocity, Tensor< 1, 3 > &particle_two_omega, const ObjectProperties particle_two_properties, const double dt)
void calculate_pp_lubrication_force (const double dt_dem, const double h_max, const double h_min, const double mu, std::vector< Tensor< 1, 3 > > &lubrication_force, std::vector< Tensor< 1, 3 > > &lubrication_torque)
void calculate_pw_lubrication_force (const double dt_dem, const double h_max, const double h_min, const double mu, std::vector< Tensor< 1, 3 > > &lubrication_force, std::vector< Tensor< 1, 3 > > &lubrication_torque)
void update_particles_boundary_contact (std::vector< IBParticle< dim > > &particles, const DoFHandler< dim > &dof_handler, const Quadrature< dim - 1 > &face_quadrature_formula, const Mapping< dim > &mapping)
Public Attributes
std::vector< IBParticle< dim > > dem_particles
Private Types
enum lowest_floating_wall_indices { lowest_floating_wall_indices = 1000000 }
Private Attributes
std::shared_ptr< Parameters::IBParticles< dim > > parameters
std::shared_ptr< Parameters::Lagrangian::FloatingWalls< dim > > floating_walls_parameters
DEMSolverParameters< dim > dem_parameters {}
MPI_Comm mpi_communicator
std::vector< std::set< unsigned int > > particles_contact_candidates
std::map< unsigned int, std::map< unsigned int, Point< dim > > > previous_wall_contact_point
std::map< unsigned int, std::map< unsigned int, Point< dim > > > previous_particle_particle_contact_point
std::map< unsigned int, std::map< unsigned int, ContactInfo > > pp_contact_map
std::map< unsigned int, std::map< unsigned int, ContactInfo > > pw_contact_map
std::vector< std::map< unsigned int, BoundaryCellsInfo > > boundary_cells
double cfd_time
Detailed Description
template<int dim>
class IBParticlesDEM< dim >
A solver class for the DEM used in conjunction with IB particles and fluid_dynamics_sharp. This class defines and uses some functions of the DEM class that have been modified and simplified to be compatible with IB_particles.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 34 of file ib_particles_dem.h.
Member Enumeration Documentation
lowest_floating_wall_indices
template<int dim> enum IBParticlesDEM::lowest_floating_wall_indices private
Enumerator
lowest_floating_wall_indices
Definition at line 305 of file ib_particles_dem.h.
Member Function Documentation
calculate_force_model()
template<int dim> void IBParticlesDEM< dim >::calculate_force_model (const double normal_overlap, ContactInfo & contact_info, Point< 3 > & contact_point, Tensor< 1, 3 > & contact_normal, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & rolling_resistance_torque, Point< dim > & particle_one_position, Tensor< 1, 3 > & particle_one_velocity, Tensor< 1, 3 > & particle_one_omega, const ObjectProperties particle_one_properties, Point< dim > & particle_two_position, Tensor< 1, 3 > & particle_two_velocity, Tensor< 1, 3 > & particle_two_omega, const ObjectProperties particle_two_properties, const double dt)
Calculates non-linear (Hertzian) force between two objects. Take into input the physical properties and contact state of the two objects.
Parameters
normal_overlap Contact normal overlap
contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact
contact_point The contact point between the two objects
contact_normal Contact normal unit vector
normal_force Contact normal force
tangential_force Contact tangential force
rolling_resistance_torque Contact rolling resistance torque
particle_one_position the position of particle one
particle_one_velocity the velocity of particle one
particle_one_omega the angular velocity of particle one
particle_one_properties the physical properties of particle one
particle_two_position the position of particle two
particle_two_velocity the velocity of particle two
particle_two_omega the angular velocity of particle two
particle_two_properties the physical properties of particle two
dt the dem time step.
Definition at line 942 of file ib_particles_dem.cc.
References harmonic_mean(), IBParticlesDEM< dim >::ObjectProperties::object_friction_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_mass, IBParticlesDEM< dim >::ObjectProperties::object_poisson_ratio, IBParticlesDEM< dim >::ObjectProperties::object_radius, IBParticlesDEM< dim >::ObjectProperties::object_restitution_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_rolling_friction_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_youngs_modulus, point_nd_to_3d(), IBParticlesDEM< dim >::ContactInfo::tangential_displacement, and IBParticlesDEM< dim >::ContactInfo::tangential_relative_velocity.
calculate_pp_contact_force()
template<int dim> void IBParticlesDEM< dim >::calculate_pp_contact_force (const double dt_dem, std::vector< Tensor< 1, 3 > > & contact_force, std::vector< Tensor< 1, 3 > > & contact_torque)
Calculates non-linear (Hertzian) particle-particle contact force.
Parameters
dt_dem The sub time stepping time step.
contact_force a vector containing the contact force between particles
contact_force a vector containing the contact torques between particles
Definition at line 103 of file ib_particles_dem.cc.
References IBParticlesDEM< dim >::ObjectProperties::object_friction_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_mass, IBParticlesDEM< dim >::ObjectProperties::object_poisson_ratio, IBParticlesDEM< dim >::ObjectProperties::object_radius, IBParticlesDEM< dim >::ObjectProperties::object_restitution_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_rolling_friction_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_youngs_modulus, point_nd_to_3d(), IBParticlesDEM< dim >::ContactInfo::rolling_resistance_spring_torque, IBParticlesDEM< dim >::ContactInfo::tangential_displacement, and tensor_nd_to_3d().
calculate_pp_lubrication_force()
template<int dim> void IBParticlesDEM< dim >::calculate_pp_lubrication_force (const double dt_dem, const double h_max, const double h_min, const double mu, std::vector< Tensor< 1, 3 > > & lubrication_force, std::vector< Tensor< 1, 3 > > & lubrication_torque)
Calculates particle-particle lubrication force. The force is based on the formula from Microhydrodynamics: Principles and Selected Applications by Kim, Sangtae; Karrila, Seppo J. ISBN 13: 9780750691734.
Parameters
dt_dem The sub time stepping time step.
h_max The gap between the two particle.
h_min The minimal gap distance considered in the force calculation to avoid the singularity of the model.
mu The fluid viscosity.
lubrication_force a vector containing the lubrication force on the particles.
lubrication_torque a vector containing the lubrication torques on the particles.
Definition at line 326 of file ib_particles_dem.cc.
References tensor_nd_to_3d().
calculate_pw_contact_force()
template<int dim> void IBParticlesDEM< dim >::calculate_pw_contact_force (const double dt_dem, std::vector< Tensor< 1, 3 > > & contact_force, std::vector< Tensor< 1, 3 > > & contact_torque)
Calculates non-linear (Hertzian) particle-wall contact force.
Parameters
dt_dem The sub time stepping time step.
contact_force a vector containing the contact force between particles
contact_force a vector containing the contact torques between particles
Definition at line 505 of file ib_particles_dem.cc.
References IBParticlesDEM< dim >::ContactInfo::normal_overlap, IBParticlesDEM< dim >::ContactInfo::normal_relative_velocity, IBParticlesDEM< dim >::BoundaryCellsInfo::normal_vector, IBParticlesDEM< dim >::ObjectProperties::object_friction_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_mass, IBParticlesDEM< dim >::ObjectProperties::object_poisson_ratio, IBParticlesDEM< dim >::ObjectProperties::object_radius, IBParticlesDEM< dim >::ObjectProperties::object_restitution_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_rolling_friction_coefficient, IBParticlesDEM< dim >::ObjectProperties::object_youngs_modulus, point_nd_to_3d(), IBParticlesDEM< dim >::BoundaryCellsInfo::point_on_boundary, IBParticlesDEM< dim >::ContactInfo::rolling_resistance_spring_torque, IBParticlesDEM< dim >::ContactInfo::tangential_displacement, IBParticlesDEM< dim >::ContactInfo::tangential_relative_velocity, and tensor_nd_to_3d().
calculate_pw_lubrication_force()
template<int dim> void IBParticlesDEM< dim >::calculate_pw_lubrication_force (const double dt_dem, const double h_max, const double h_min, const double mu, std::vector< Tensor< 1, 3 > > & lubrication_force, std::vector< Tensor< 1, 3 > > & lubrication_torque)
Calculates particle-wall lubrication force.
Parameters
dt_dem The sub time stepping time step.
h_max The gap between particle and the wall below which we evaluate the force.
h_min The minimal gap distance considered in the force calculation to avoid the singularity of the model.
mu The fluid viscosity.
lubrication_force a vector containing the lubrication force on the particles.
lubrication_torque a vector containing the lubrication torques on the particles.
Definition at line 805 of file ib_particles_dem.cc.
References IBParticlesDEM< dim >::BoundaryCellsInfo::normal_vector, point_nd_to_3d(), IBParticlesDEM< dim >::BoundaryCellsInfo::point_on_boundary, and tensor_nd_to_3d().
initialize()
template<int dim> void IBParticlesDEM< dim >::initialize (const std::shared_ptr< Parameters::IBParticles< dim > > & p_nsparam, const std::shared_ptr< Parameters::Lagrangian::FloatingWalls< dim > > floating_walls_parameters, const MPI_Comm & mpi_communicator_input, const std::vector< IBParticle< dim > > & particles)
Initialize the IBParticlesDEM object with the parameters, the mpi communicator and the particles.
Parameters
p_nsparam The parameters for the immersed boundary particles
dem_parameters
mpi_communicator_input The mpi communicator of the simulation.
particles The particles vector containing all the IB particles.
Definition at line 14 of file ib_particles_dem.cc.
integrate_particles_motion()
template<int dim> void IBParticlesDEM< dim >::integrate_particles_motion (const double dt, const double h_max, const double h_min, const double rho, const double mu)
Integrates the dynamics of the IB_particle taking into account the contact between particles and between particles and walls.
Parameters
dt The CFD time step.
h_max The gap between the two particle.
h_min The minimal gap distance considered in the force calculation to avoid the singularity of the model.
rho The fluid density.
mu The fluid viscosity.
Definition at line 1137 of file ib_particles_dem.cc.
References DEM::omega, and DEM::velocity.
update_contact_candidates()
template<int dim> void IBParticlesDEM< dim >::update_contact_candidates ()
Updates the contact candidates of all the particles.
Definition at line 41 of file ib_particles_dem.cc.
References point_nd_to_3d().
update_particles()
template<int dim> void IBParticlesDEM< dim >::update_particles (const std::vector< IBParticle< dim > > & particles, double time)
Updates the boundary cells that are contact candidates for each of the particles.
Parameters
particles The particles vector containing all the IB particles.
time The current CFD time.
Definition at line 31 of file ib_particles_dem.cc.
update_particles_boundary_contact()
template<int dim> void IBParticlesDEM< dim >::update_particles_boundary_contact (std::vector< IBParticle< dim > > & particles, const DoFHandler< dim > & dof_handler, const Quadrature< dim - 1 > & face_quadrature_formula, const Mapping< dim > & mapping)
Updates the boundary cells that are contact candidates for each of the particles.The force is based on the formula from Microhydrodynamics: Principles and Selected Applications by Kim, Sangtae; Karrila, Seppo J. ISBN 13: 9780750691734.
Parameters
particles The particles vector containing all the IB particles.
dof_handler The dof handler of the mesh used for the fluid simulation.
face_quadrature_formula The face quadrature formula used in the elements.
mapping The FEM mapping of the face element.
Definition at line 402 of file ib_particles_dem.cc.
References IBParticlesDEM< dim >::BoundaryCellsInfo::boundary_index, LetheGridTools::find_boundary_cells_in_sphere(), IBParticlesDEM< dim >::BoundaryCellsInfo::normal_vector, and IBParticlesDEM< dim >::BoundaryCellsInfo::point_on_boundary.
Member Data Documentation
boundary_cells
template<int dim> std::vector<std::map<unsigned int, BoundaryCellsInfo> > IBParticlesDEM< dim >::boundary_cells private
Definition at line 329 of file ib_particles_dem.h.
cfd_time
template<int dim> double IBParticlesDEM< dim >::cfd_time private
Definition at line 331 of file ib_particles_dem.h.
dem_parameters
template<int dim> DEMSolverParameters<dim> IBParticlesDEM< dim >::dem_parameters {} private
Definition at line 313 of file ib_particles_dem.h.
dem_particles
template<int dim> std::vector<IBParticle<dim> > IBParticlesDEM< dim >::dem_particles
Definition at line 268 of file ib_particles_dem.h.
floating_walls_parameters
template<int dim> std::shared_ptr<Parameters::Lagrangian::FloatingWalls<dim> > IBParticlesDEM< dim >::floating_walls_parameters private
Definition at line 312 of file ib_particles_dem.h.
mpi_communicator
template<int dim> MPI_Comm IBParticlesDEM< dim >::mpi_communicator private
Definition at line 314 of file ib_particles_dem.h.
parameters
template<int dim> std::shared_ptr<Parameters::IBParticles<dim> > IBParticlesDEM< dim >::parameters private
Definition at line 310 of file ib_particles_dem.h.
particles_contact_candidates
template<int dim> std::vector<std::set<unsigned int> > IBParticlesDEM< dim >::particles_contact_candidates private
Definition at line 316 of file ib_particles_dem.h.
pp_contact_map
template<int dim> std::map<unsigned int, std::map<unsigned int, ContactInfo> > IBParticlesDEM< dim >::pp_contact_map private
Definition at line 325 of file ib_particles_dem.h.
previous_particle_particle_contact_point
template<int dim> std::map<unsigned int, std::map<unsigned int, Point<dim> > > IBParticlesDEM< dim >::previous_particle_particle_contact_point private
Definition at line 322 of file ib_particles_dem.h.
previous_wall_contact_point
template<int dim> std::map<unsigned int, std::map<unsigned int, Point<dim> > > IBParticlesDEM< dim >::previous_wall_contact_point private
Definition at line 320 of file ib_particles_dem.h.
pw_contact_map
template<int dim> std::map<unsigned int, std::map<unsigned int, ContactInfo> > IBParticlesDEM< dim >::pw_contact_map private
Definition at line 326 of file ib_particles_dem.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/ib_particles_dem.h
/home/runner/work/lethe/lethe/source/fem-dem/ib_particles_dem.cc