Lethe Open-Source Library: MortarManager< dim > Class Template Reference
MortarManager< dim > Class Template Reference
#include <mortar_coupling_manager.h>
Public Member Functions
MortarManager (const unsigned int n_subdivisions, const unsigned int n_quadrature_points, const double radius, const double rotate_pi)
bool is_mesh_aligned () const
unsigned int get_n_points () const
unsigned int get_n_points (const double &rad) const
std::vector< unsigned int > get_indices (const double &rad) const
std::vector< Point< dim > > get_points (const double rad) const
std::vector< Point< 1 > > get_points_ref (const double rad) const
std::vector< double > get_weights (const double &rad) const
std::vector< Tensor< 1, dim, double > > get_normals (const double &rad) const
Private Member Functions
std::pair< unsigned int, unsigned int > get_config (const double &rad) const
Private Attributes
const unsigned int n_subdivisions
const unsigned int n_quadrature_points
const double radius
const double rotate_pi
QGauss< 1 > quadrature
Detailed Description
template<int dim>
class MortarManager< dim >
Base class for the mortar manager.
Parameters
n_subdivisions Number of cells at the interface between inner and outer domains
n_quadrature_points Number of quadrature points per cell
radius Radius at the interface between inner and outer domains
rotate_pi Rotation angle for the inner domain
Definition at line 33 of file mortar_coupling_manager.h.
Constructor & Destructor Documentation
MortarManager()
template<int dim> MortarManager< dim >::MortarManager (const unsigned int n_subdivisions, const unsigned int n_quadrature_points, const double radius, const double rotate_pi) inline
Definition at line 36 of file mortar_coupling_manager.h.
Member Function Documentation
get_config()
template<int dim> std::pair< unsigned int, unsigned int > MortarManager< dim >::get_config (const double & rad) const inline private
Returns the mesh alignement type and cell index.
Parameters
[in] rad Angular coordinate of cell center
Returns
type Cell configuration type at the interface type = 0: mesh aligned type = 1: mesh not aligned, inner domain (allows rotation) type = 2: mesh not aligned, outer domain (fixed)
id Index of the cell in which lies the rotated cell center
Definition at line 350 of file mortar_coupling_manager.h.
References delta(), MortarManager< dim >::is_mesh_aligned(), MortarManager< dim >::n_subdivisions, and MortarManager< dim >::rotate_pi.
get_indices()
template<int dim> std::vector< unsigned int > MortarManager< dim >::get_indices (const double & rad) const inline
Returns the indices of all quadrature points at both sides of the interface.
Parameters
[in] rad Angular coordinate of cell center
Definition at line 100 of file mortar_coupling_manager.h.
References MortarManager< dim >::get_config(), MortarManager< dim >::get_n_points(), and MortarManager< dim >::n_quadrature_points.
get_n_points() [1/2]
template<int dim> unsigned int MortarManager< dim >::get_n_points () const inline
Returns the total number of quadrature points at the inner/outer boundary interface.
Definition at line 64 of file mortar_coupling_manager.h.
References MortarManager< dim >::is_mesh_aligned(), MortarManager< dim >::n_quadrature_points, and MortarManager< dim >::n_subdivisions.
get_n_points() [2/2]
template<int dim> unsigned int MortarManager< dim >::get_n_points (const double & rad) const inline
Returns the number of quadrature points at each inner/outer cell matching pair.
Parameters
[in] rad Angular coordinate of cell center
Definition at line 81 of file mortar_coupling_manager.h.
References MortarManager< dim >::is_mesh_aligned(), and MortarManager< dim >::n_quadrature_points.
get_normals()
template<int dim> std::vector< Tensor< 1, dim, double > > MortarManager< dim >::get_normals (const double & rad) const inline
Returns the normal vector for the quadrature points.
Parameters
[in] rad Angular coordinate of cell center
Returns
result Normal vectors of the cell quadrature points
Definition at line 325 of file mortar_coupling_manager.h.
References MortarManager< dim >::get_points().
get_points()
template<int dim> std::vector< Point< dim > > MortarManager< dim >::get_points (const double rad) const inline
Returns the coordinates of the quadrature points at both sides of the inerface.
Parameters
[in] rad Angular coordinate of cell center
[out] points Coordinate of quadrature points of the cell
Definition at line 160 of file mortar_coupling_manager.h.
References delta(), MortarManager< dim >::get_config(), MortarManager< dim >::n_quadrature_points, MortarManager< dim >::n_subdivisions, MortarManager< dim >::quadrature, MortarManager< dim >::radius, and MortarManager< dim >::rotate_pi.
get_points_ref()
template<int dim> std::vector< Point< 1 > > MortarManager< dim >::get_points_ref (const double rad) const inline
Definition at line 217 of file mortar_coupling_manager.h.
References delta(), MortarManager< dim >::get_config(), MortarManager< dim >::n_quadrature_points, MortarManager< dim >::n_subdivisions, MortarManager< dim >::quadrature, and MortarManager< dim >::rotate_pi.
get_weights()
template<int dim> std::vector< double > MortarManager< dim >::get_weights (const double & rad) const inline
Returns the weights of the quadrature points at both sides of the interface.
Parameters
[in] rad Angular coordinate of cell center
Returns
points Angular weights of quadrature points of the cell
Definition at line 271 of file mortar_coupling_manager.h.
References delta(), MortarManager< dim >::get_config(), MortarManager< dim >::n_quadrature_points, MortarManager< dim >::n_subdivisions, MortarManager< dim >::quadrature, and MortarManager< dim >::rotate_pi.
is_mesh_aligned()
template<int dim> bool MortarManager< dim >::is_mesh_aligned () const inline
Verify if cells of the inner and outer domains are aligned.
Definition at line 51 of file mortar_coupling_manager.h.
References delta(), MortarManager< dim >::n_subdivisions, and MortarManager< dim >::rotate_pi.
Member Data Documentation
n_quadrature_points
template<int dim> const unsigned int MortarManager< dim >::n_quadrature_points private
Definition at line 383 of file mortar_coupling_manager.h.
n_subdivisions
template<int dim> const unsigned int MortarManager< dim >::n_subdivisions private
Definition at line 382 of file mortar_coupling_manager.h.
quadrature
template<int dim> QGauss<1> MortarManager< dim >::quadrature private
Definition at line 386 of file mortar_coupling_manager.h.
radius
template<int dim> const double MortarManager< dim >::radius private
Definition at line 384 of file mortar_coupling_manager.h.
rotate_pi
template<int dim> const double MortarManager< dim >::rotate_pi private
Definition at line 385 of file mortar_coupling_manager.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/mortar_coupling_manager.h