Lethe Open-Source Library: EvaporationModelTemperature Class Reference
EvaporationModelTemperature Class Reference
#include <evaporation_model.h>
Public Member Functions
EvaporationModelTemperature (const Parameters::Evaporation &p_evaporation)
double saturation_pressure (const std::map< field, double > &field_values)
void saturation_pressure (const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &saturation_pressure_vector)
double mass_flux (const std::map< field, double > &field_values) override
void mass_flux (const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &mass_flux_vector) override
double heat_flux (const std::map< field, double > &field_values) override
void heat_flux (const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &heat_flux_vector) override
double heat_flux_jacobian (const std::map< field, double > &field_values, const field id) override
void heat_flux_jacobian (const std::map< field, std::vector< double > > &field_vectors, const field id, std::vector< double > &jacobian_vector) override
double momentum_flux (const std::map< field, double > &field_values) override
void momentum_flux (const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &momentum_flux_vector) override
double momentum_flux_jacobian (const std::map< field, double > &, const field) override
void momentum_flux_jacobian (const std::map< field, std::vector< double > > &, const field, std::vector< double > &jacobian_vector) override
Public Member Functions inherited from EvaporationModel
EvaporationModel ()
bool depends_on (const field &id)
Private Attributes
const double evaporation_coefficient
const double recoil_pressure_coefficient
const double molar_mass
const double boiling_temperature_inv
const double latent_heat_evaporation
const double ambient_pressure
const double ambient_gas_density_inv
const double liquid_density_inv
const double universal_gas_constant
Additional Inherited Members
Static Public Member Functions inherited from EvaporationModel
static std::shared_ptr< EvaporationModel > model_cast (const Parameters::Evaporation &evaporation_parameters)
Protected Attributes inherited from EvaporationModel
std::map< field, bool > model_depends_on
Detailed Description
EvaporationModelTemperature. Class that allows to calculate the evaporation mass, heat, and momentum fluxes when a temperature-dependent mass flux is considered.
Parameters
p_evaporation Evaporation model parameters.
Definition at line 390 of file evaporation_model.h.
Constructor & Destructor Documentation
EvaporationModelTemperature()
EvaporationModelTemperature::EvaporationModelTemperature (const Parameters::Evaporation & p_evaporation) inline
Definition at line 393 of file evaporation_model.h.
References EvaporationModel::model_depends_on, and temperature.
Member Function Documentation
heat_flux() [1/2]
double EvaporationModelTemperature::heat_flux (const std::map< field, double > & field_values) inline override virtual
heat_flux Calculates the value of the evaporation heat flux.
Parameters
field_values Map storing the values of the various fields on which the heat flux may depend.
Returns
Value of the heat flux calculated with the field_values.
Implements EvaporationModel.
Definition at line 534 of file evaporation_model.h.
References latent_heat_evaporation, and mass_flux().
heat_flux() [2/2]
void EvaporationModelTemperature::heat_flux (const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & heat_flux_vector) inline override virtual
heat_flux Calculates the values of the evaporation heat flux for multiple points.
Parameters
field_vectors Map storing the vectors of the values for each field on which the heat flux may depend. Each vector contains the field values at the points of interest.
heat_flux_vector Vector of heat flux values.
Implements EvaporationModel.
Definition at line 550 of file evaporation_model.h.
References latent_heat_evaporation, and mass_flux().
heat_flux_jacobian() [1/2]
double EvaporationModelTemperature::heat_flux_jacobian (const std::map< field, double > & field_values, const field id) inline override virtual
heat_flux_jacobian Calculates the jacobian (the partial derivative) of the evaporation heat flux with respect to a field.
Parameters
field_values Map storing the values of the various fields on which the heat flux evaluated at a point may depend.
id Identifier of the field with respect to which the jacobian should be calculated.
Returns
Value of the partial derivative of the heat flux with respect to the field.
Implements EvaporationModel.
Definition at line 575 of file evaporation_model.h.
References ambient_pressure, boiling_temperature_inv, evaporation_coefficient, latent_heat_evaporation, molar_mass, temperature, and universal_gas_constant.
heat_flux_jacobian() [2/2]
void EvaporationModelTemperature::heat_flux_jacobian (const std::map< field, std::vector< double > > & field_vectors, const field id, std::vector< double > & jacobian_vector) inline override virtual
heat_flux_jacobian Calculates the derivative of the evaporation heat flux with respect to a field.
Parameters
field_vectors Map storing the vectors of the values for each field on which heat flux evaluated at a point may depend. Each vector contains the field values at the points of interest.
id Identifier of the field with respect to which a derivative should be calculated.
jacobian_vector Vector of the values of the derivative of the heat flux with respect to the field.
Implements EvaporationModel.
Definition at line 612 of file evaporation_model.h.
References ambient_pressure, boiling_temperature_inv, evaporation_coefficient, latent_heat_evaporation, molar_mass, temperature, and universal_gas_constant.
mass_flux() [1/2]
double EvaporationModelTemperature::mass_flux (const std::map< field, double > & field_values) inline override virtual
mass_flux Calculates the value of the evaporation mass flux.
Parameters
field_values Map storing the values of the various fields on which the evaporation mass flux may depend.
Returns
Value of the evaporation mass flux calculated with the field_values.
Implements EvaporationModel.
Definition at line 475 of file evaporation_model.h.
References evaporation_coefficient, molar_mass, saturation_pressure(), temperature, and universal_gas_constant.
mass_flux() [2/2]
void EvaporationModelTemperature::mass_flux (const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & mass_flux_vector) inline override virtual
mass_flux Calculates the values of the evaporation mass flux for multiple points.
Parameters
field_vectors Map storing the vectors of the values for each field on which the evaporation mass flux may depend. Each vector contains the field values at the points of interest.
mass_flux_vector Vector of mass flux values.
Implements EvaporationModel.
Definition at line 500 of file evaporation_model.h.
References evaporation_coefficient, molar_mass, saturation_pressure(), temperature, and universal_gas_constant.
momentum_flux() [1/2]
double EvaporationModelTemperature::momentum_flux (const std::map< field, double > & field_values) inline override virtual
momentum_flux Calculates the value of the evaporation momentum flux.
Parameters
field_values Map storing the values of the various fields on which the momentum flux may depend.
Returns
Value of the momentum flux calculated with the field_values
Implements EvaporationModel.
Definition at line 655 of file evaporation_model.h.
References ambient_pressure, pressure, recoil_pressure_coefficient, and saturation_pressure().
momentum_flux() [2/2]
void EvaporationModelTemperature::momentum_flux (const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & momentum_flux_vector) inline override virtual
momentum_flux Calculates the values of the evaporation momentum flux for multiple points.
Parameters
field_vectors Map storing the vectors of the values for each field on which the momentum flux may depend. Each vector contains the field values at the points of interest.
momentum_flux_vector Vectors of the momentum flux values.
Implements EvaporationModel.
Definition at line 673 of file evaporation_model.h.
References ambient_pressure, recoil_pressure_coefficient, and saturation_pressure().
momentum_flux_jacobian() [1/2]
double EvaporationModelTemperature::momentum_flux_jacobian (const std::map< field, double > & , const field) inline override virtual
momentum_flux_jacobian Calculates the jacobian (the partial derivative) of the evaporation momentum flux with respect to a field.
Parameters
field_values Map storing the values of the various fields on which the momentum flux may depend.
id Identifier of the field with respect to which the jacobian should be calculated
Returns
Value of the partial derivative of the momentum flux with respect to the field.
Implements EvaporationModel.
Definition at line 699 of file evaporation_model.h.
momentum_flux_jacobian() [2/2]
void EvaporationModelTemperature::momentum_flux_jacobian (const std::map< field, std::vector< double > > & , const field , std::vector< double > & jacobian_vector) inline override virtual
momentum_flux_jacobian Calculates the derivative of the evaporation momentum flux with respect to a field.
Parameters
field_vectors Map storing the vectors of the values for each field flux may depend. Each vector contains the field values at the points of interest.
id Identifier of the field with respect to which a derivative should be calculated.
jacobian_vector Vector of the values of the derivative of the momentum flux with respect to the field.
Implements EvaporationModel.
Definition at line 717 of file evaporation_model.h.
saturation_pressure() [1/2]
double EvaporationModelTemperature::saturation_pressure (const std::map< field, double > & field_values) inline
saturation_pressure Calculates the value of the saturation pressure.
Parameters
field_values Map storing the values of the various field on which the saturated vapor pressure evaluated at a point may depend.
Returns
Value of the saturation pressure calculated with the field_values.
Definition at line 414 of file evaporation_model.h.
References ambient_pressure, boiling_temperature_inv, latent_heat_evaporation, molar_mass, temperature, and universal_gas_constant.
saturation_pressure() [2/2]
void EvaporationModelTemperature::saturation_pressure (const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & saturation_pressure_vector) inline
mass_flux Calculates the values of the saturation pressure for multiple points.
Parameters
field_vectors Map storing the vectors of the values for each field on which the saturated vapor pressure may depend. Each vector contains the field values at the points of interest.
saturation_pressure_vector Vector of the saturation pressure values.
Definition at line 441 of file evaporation_model.h.
References ambient_pressure, boiling_temperature_inv, latent_heat_evaporation, molar_mass, temperature, and universal_gas_constant.
Member Data Documentation
ambient_gas_density_inv
const double EvaporationModelTemperature::ambient_gas_density_inv private
Definition at line 733 of file evaporation_model.h.
ambient_pressure
const double EvaporationModelTemperature::ambient_pressure private
Definition at line 732 of file evaporation_model.h.
boiling_temperature_inv
const double EvaporationModelTemperature::boiling_temperature_inv private
Definition at line 730 of file evaporation_model.h.
evaporation_coefficient
const double EvaporationModelTemperature::evaporation_coefficient private
Definition at line 726 of file evaporation_model.h.
latent_heat_evaporation
const double EvaporationModelTemperature::latent_heat_evaporation private
Definition at line 731 of file evaporation_model.h.
liquid_density_inv
const double EvaporationModelTemperature::liquid_density_inv private
Definition at line 734 of file evaporation_model.h.
molar_mass
const double EvaporationModelTemperature::molar_mass private
Definition at line 729 of file evaporation_model.h.
recoil_pressure_coefficient
const double EvaporationModelTemperature::recoil_pressure_coefficient private
Definition at line 727 of file evaporation_model.h.
universal_gas_constant
const double EvaporationModelTemperature::universal_gas_constant private
Definition at line 736 of file evaporation_model.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/evaporation_model.h