Lethe Open-Source Library: FluidDynamicsVANSMatrixFree< dim > Class Template Reference
FluidDynamicsVANSMatrixFree< dim > Class Template Reference
#include <fluid_dynamics_vans_matrix_free.h>
Public Member Functions
FluidDynamicsVANSMatrixFree (CFDDEMSimulationParameters< dim > &param)
virtual void solve () override
Public Member Functions inherited from FluidDynamicsMatrixFree< dim >
FluidDynamicsMatrixFree (SimulationParameters< dim > &nsparam)
~FluidDynamicsMatrixFree ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Protected Member Functions
void read_dem ()
virtual void setup_dofs () override
virtual void finish_time_step_fd ()
virtual void output_field_hook (DataOut< dim > &data_out) override
void create_GMG () override
void initialize_GMG () override
Protected Member Functions inherited from FluidDynamicsMatrixFree< dim >
virtual void setup_dofs_fd () override
virtual void set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false) override
virtual void assemble_system_matrix () override
virtual void assemble_system_rhs () override
virtual void update_multiphysics_time_average_solution () override
virtual void update_solutions_for_multiphysics () override
virtual void update_solutions_for_fluid_dynamics () override
void calculate_time_derivative_previous_solutions ()
void setup_preconditioner () override
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
void print_mg_setup_times ()
Protected Member Functions inherited from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual LinearAlgebra::distributed::Vector< double > & get_evaluation_point () override
virtual LinearAlgebra::distributed::Vector< double > & get_local_evaluation_point () override
virtual LinearAlgebra::distributed::Vector< double > & get_newton_update () override
virtual LinearAlgebra::distributed::Vector< double > & get_present_solution () override
virtual LinearAlgebra::distributed::Vector< double > & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void set_initial_condition (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void postprocess_fd (bool first_iteration)
void postprocessing_forces (const LinearAlgebra::distributed::Vector< double > &evaluation_point)
void postprocessing_torques (const LinearAlgebra::distributed::Vector< double > &evaluation_point)
virtual void dynamic_flow_control ()
virtual void iterate ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
void transfer_solution (SolutionTransfer< dim, LinearAlgebra::distributed::Vector< double > > &solution_transfer, std::vector< SolutionTransfer< dim, LinearAlgebra::distributed::Vector< double > > > &previous_solutions_transfer)
virtual void read_checkpoint ()
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void update_mortar_configuration ()
void reinit_mortar ()
std::shared_ptr< Mapping< dim > > get_mapping ()
void rotate_rotor_mapping (const bool is_first)
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
virtual void write_checkpoint ()
void write_output_results (const LinearAlgebra::distributed::Vector< double > &solution)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
LinearAlgebra::distributed::Vector< double > init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes
CFDDEMSimulationParameters< dim > cfd_dem_simulation_parameters
MappingQGeneric< dim > particle_mapping
Particles::ParticleHandler< dim, dim > particle_handler
VoidFractionBase< dim > void_fraction_manager
bool has_periodic_boundaries
Tensor< 1, dim > periodic_offset
unsigned int periodic_direction
Protected Attributes inherited from FluidDynamicsMatrixFree< dim >
std::shared_ptr< NavierStokesOperatorBase< dim, double > > system_operator
std::shared_ptr< MFNavierStokesPreconditionGMGBase< dim > > gmg_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
VectorType time_derivative_previous_solutions
DoFHandler< dim > dof_handler_fe_q_iso_q1
TrilinosWrappers::MPI::Vector multiphysics_average_velocities
TrilinosWrappers::MPI::Vector multiphysics_present_solution
std::vector< TrilinosWrappers::MPI::Vector > multiphysics_previous_solutions
VectorType temperature_present_solution
std::shared_ptr< PhysicalPropertiesManager > physical_properties_manager
Protected Attributes inherited from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
LinearAlgebra::distributed::Vector< double > evaluation_point
LinearAlgebra::distributed::Vector< double > local_evaluation_point
LinearAlgebra::distributed::Vector< double > newton_update
LinearAlgebra::distributed::Vector< double > present_solution
LinearAlgebra::distributed::Vector< double > system_rhs
std::vector< LinearAlgebra::distributed::Vector< double > > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::shared_ptr< MortarManagerCircle< dim > > mortar_manager
std::shared_ptr< CouplingOperator< dim, double > > mortar_coupling_operator
std::shared_ptr< NavierStokesCouplingEvaluation< dim, double > > mortar_coupling_evaluator
std::shared_ptr< MappingQCache< dim > > mapping_cache
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, LinearAlgebra::distributed::Vector< double >, IndexSet > > average_velocities
LinearAlgebra::distributed::Vector< double > average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class FluidDynamicsVANSMatrixFree< dim >
A solver for the Volume-Averaged incompressible Navier-Stokes equations implemented in a matrix-free fashion.
A matrix-free stabilized solver for the Volume-Averaged incompressible Navier-Stokes (VANS) equations implemented in a matrix-free fashion with a sum-factorization approach. It uses a continuous Galerkin discretization and solves the fully-coupled discretized problem in a monolithic way using multigrid preconditioners. This class greatly inherits from the matrix-free implementation of the Navier-Stokes equations.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved.
Definition at line 102 of file fluid_dynamics_vans_matrix_free.h.
Constructor & Destructor Documentation
FluidDynamicsVANSMatrixFree()
template<int dim> FluidDynamicsVANSMatrixFree< dim >::FluidDynamicsVANSMatrixFree (CFDDEMSimulationParameters< dim > & param)
Constructor that sets the finite element degree and system operator according to simulation parameters. It initializes the CFD-DEM parameters, the particle mapping, the particle handler, and the void fraction manager. It also checks whether there are periodic boundaries.
Parameters
[in] param Relevant parameters for the solver.
Definition at line 130 of file fluid_dynamics_vans_matrix_free.cc.
References FluidDynamicsVANSMatrixFree< dim >::cfd_dem_simulation_parameters, FluidDynamicsVANSMatrixFree< dim >::has_periodic_boundaries, BoundaryConditions::periodic, and FluidDynamicsMatrixFree< dim >::system_operator.
Member Function Documentation
create_GMG()
template<int dim> void FluidDynamicsVANSMatrixFree< dim >::create_GMG () override protected virtual
Create geometric multigrid preconditioner.
Reimplemented from FluidDynamicsMatrixFree< dim >.
Definition at line 390 of file fluid_dynamics_vans_matrix_free.cc.
finish_time_step_fd()
template<int dim> void FluidDynamicsVANSMatrixFree< dim >::finish_time_step_fd () protected virtual
Finish the time-step and manage the time-step end for the void fraction.
Definition at line 268 of file fluid_dynamics_vans_matrix_free.cc.
References NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::finish_time_step().
initialize_GMG()
template<int dim> void FluidDynamicsVANSMatrixFree< dim >::initialize_GMG () override protected virtual
Initializes (or re-initializes) geometric multigrid preconditioner
Reimplemented from FluidDynamicsMatrixFree< dim >.
Definition at line 408 of file fluid_dynamics_vans_matrix_free.cc.
output_field_hook()
template<int dim> void FluidDynamicsVANSMatrixFree< dim >::output_field_hook (DataOut< dim > & data_out) override protected virtual
Add data vectors to the data_out object for post_processing additional results. In this case, the void fraction field is added.
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 279 of file fluid_dynamics_vans_matrix_free.cc.
read_dem()
template<int dim> void FluidDynamicsVANSMatrixFree< dim >::read_dem () protected
Read particles arising from a DEM simulation.
Definition at line 187 of file fluid_dynamics_vans_matrix_free.cc.
References convert_particle_handler(), and DEM::DEMProperties::n_properties.
setup_dofs()
template<int dim> void FluidDynamicsVANSMatrixFree< dim >::setup_dofs () override protected virtual
Setup the degree of freedom of the flow solver and the degrees of freedom and constraints for the void fraction.
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 176 of file fluid_dynamics_vans_matrix_free.cc.
References NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::setup_dofs().
solve()
template<int dim> void FluidDynamicsVANSMatrixFree< dim >::solve () override virtual
Solve the problem defined by simulation parameters by iterating through time or through the mesh refinements.
Reimplemented from FluidDynamicsMatrixFree< dim >.
Definition at line 288 of file fluid_dynamics_vans_matrix_free.cc.
References Parameters::Timer::end, is_bdf(), Parameters::Timer::iteration, and read_mesh_and_manifolds().
Member Data Documentation
cfd_dem_simulation_parameters
template<int dim> CFDDEMSimulationParameters<dim> FluidDynamicsVANSMatrixFree< dim >::cfd_dem_simulation_parameters protected
Simulation parameters for CFD-DEM simulations.
Definition at line 163 of file fluid_dynamics_vans_matrix_free.h.
has_periodic_boundaries
template<int dim> bool FluidDynamicsVANSMatrixFree< dim >::has_periodic_boundaries protected
Member variables which are used to manage boundary conditions.
Definition at line 176 of file fluid_dynamics_vans_matrix_free.h.
particle_handler
template<int dim> Particles::ParticleHandler<dim, dim> FluidDynamicsVANSMatrixFree< dim >::particle_handler protected
Particle-handler used to store particles in CFD-DEM simulations.
Definition at line 169 of file fluid_dynamics_vans_matrix_free.h.
particle_mapping
template<int dim> MappingQGeneric<dim> FluidDynamicsVANSMatrixFree< dim >::particle_mapping protected
Mapping used for the particles.
Definition at line 166 of file fluid_dynamics_vans_matrix_free.h.
periodic_direction
template<int dim> unsigned int FluidDynamicsVANSMatrixFree< dim >::periodic_direction protected
Definition at line 178 of file fluid_dynamics_vans_matrix_free.h.
periodic_offset
template<int dim> Tensor<1, dim> FluidDynamicsVANSMatrixFree< dim >::periodic_offset protected
Definition at line 177 of file fluid_dynamics_vans_matrix_free.h.
void_fraction_manager
template<int dim> VoidFractionBase<dim> FluidDynamicsVANSMatrixFree< dim >::void_fraction_manager protected
Object that manages the void fraction calculation from functions or from parameters.
Definition at line 173 of file fluid_dynamics_vans_matrix_free.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/fluid_dynamics_vans_matrix_free.h
/home/runner/work/lethe/lethe/source/fem-dem/fluid_dynamics_vans_matrix_free.cc