Lethe Open-Source Library: Tracer< dim > Class Template Reference
Tracer< dim > Class Template Reference
#include <tracer.h>
Public Member Functions
Tracer (MultiphysicsInterface< dim > *multiphysics_interface, const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control)
void attach_solution_to_output (DataOut< dim > &data_out) override
double calculate_L2_error ()
void finish_simulation () override
void percolate_time_vectors () override
void postprocess (bool first_iteration) override
void pre_mesh_adaptation () override
void post_mesh_adaptation () override
void compute_kelly (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > &, dealii::Vector< float > &estimated_error_per_cell) override
void write_checkpoint () override
void read_checkpoint () override
const DoFHandler< dim > & get_dof_handler () override
void setup_dofs () override
void set_initial_conditions () override
void update_boundary_conditions () override
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
GlobalVectorType & get_evaluation_point () override
GlobalVectorType & get_local_evaluation_point () override
GlobalVectorType & get_newton_update () override
GlobalVectorType & get_present_solution () override
GlobalVectorType & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
void output_newton_update_norms (const unsigned int display_precision) override
template<typename VectorType >
std::map< types::boundary_id, double > postprocess_tracer_flow_rate (const VectorType &current_solution_fd)
Public Member Functions inherited from AuxiliaryPhysics< dim, GlobalVectorType >
AuxiliaryPhysics (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~AuxiliaryPhysics ()
virtual void modify_solution ()
void setup_preconditioner () override
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void verify_consistency_of_boundary_conditions ()
void assemble_system_matrix () override
void assemble_system_matrix_cg ()
void assemble_system_matrix_dg ()
void assemble_system_rhs () override
void assemble_system_rhs_cg ()
void assemble_system_rhs_dg ()
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, TracerScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, TracerScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
virtual void setup_assemblers ()
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData &copy_data)
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData &copy_data)
void calculate_tracer_statistics ()
template<typename GlobalVectorType >
std::map< types::boundary_id, double > postprocess_tracer_flow_rate (const GlobalVectorType &current_solution_fd)
void write_tracer_flow_rates (const std::map< types::boundary_id, double > &tracer_flow_rate_vector)
void write_tracer_statistics ()
void reinit_face_velocity_with_adequate_solution (const typename DoFHandler< dim >::active_cell_iterator &velocity_cell, const unsigned int &face_no, TracerScratchData< dim > &scratch_data)
Private Attributes
MultiphysicsInterface< dim > * multiphysics
TimerOutput computing_timer
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< SimulationControl > simulation_control
DoFHandler< dim > dof_handler
std::shared_ptr< FiniteElement< dim > > fe
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
ConvergenceTable error_table
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
GlobalVectorType present_solution
GlobalVectorType system_rhs
AffineConstraints< double > nonzero_constraints
AffineConstraints< double > zero_constraints
TrilinosWrappers::SparseMatrix system_matrix
std::vector< GlobalVectorType > previous_solutions
std::shared_ptr< parallel::distributed::SolutionTransfer< dim, GlobalVectorType > > solution_transfer
std::vector< parallel::distributed::SolutionTransfer< dim, GlobalVectorType > > previous_solutions_transfer
std::vector< std::shared_ptr< TracerAssemblerBase< dim > > > assemblers
std::shared_ptr< TracerAssemblerSIPG< dim > > inner_face_assembler
std::shared_ptr< TracerAssemblerBoundaryNitsche< dim > > boundary_face_assembler
TableHandler statistics_table
TableHandler tracer_flow_rate_table
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class Tracer< dim >
Definition at line 47 of file tracer.h.
Constructor & Destructor Documentation
Tracer()
template<int dim> Tracer< dim >::Tracer (MultiphysicsInterface< dim > * multiphysics_interface, const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control) inline
Definition at line 50 of file tracer.h.
References Tracer< dim >::cell_quadrature, Tracer< dim >::computing_timer, Tracer< dim >::dof_handler, Tracer< dim >::face_quadrature, Tracer< dim >::fe, Tracer< dim >::mapping, maximum_number_of_previous_solutions(), Parameters::Timer::none, Tracer< dim >::previous_solutions, Tracer< dim >::previous_solutions_transfer, Tracer< dim >::simulation_parameters, and Tracer< dim >::solution_transfer.
Member Function Documentation
assemble_local_system_matrix()
template<int dim> void Tracer< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, TracerScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for TracerScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 257 of file tracer.cc.
References Parameters::average_velocity_profile, TracerScratchData< dim >::calculate_physical_properties(), StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, TracerScratchData< dim >::reinit(), TracerScratchData< dim >::reinit_signed_distance(), TracerScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_local_system_rhs()
template<int dim> void Tracer< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, TracerScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for TracerScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 541 of file tracer.cc.
References Parameters::average_velocity_profile, TracerScratchData< dim >::calculate_physical_properties(), StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, TracerScratchData< dim >::reinit(), TracerScratchData< dim >::reinit_signed_distance(), TracerScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_system_matrix()
template<int dim> void Tracer< dim >::assemble_system_matrix () override private virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 75 of file tracer.cc.
assemble_system_matrix_cg()
template<int dim> void Tracer< dim >::assemble_system_matrix_cg () private
Assembles the matrix associated with the solver when CG elements are used. This uses the WorkStream paradigm.
Definition at line 94 of file tracer.cc.
References Tracer< dim >::assemble_local_system_matrix(), Tracer< dim >::copy_local_matrix_to_global_matrix(), and fluid_dynamics.
assemble_system_matrix_dg()
template<int dim> void Tracer< dim >::assemble_system_matrix_dg () private
Assembles the matrix associated with the solver when DG elements are used. This uses the MeshWorker paradigm instead of the WorkStream paradigm. This is because the DG system matrix is assembled in a different way and requires face and boundary integrals.
Definition at line 122 of file tracer.cc.
References StabilizedDGMethodsCopyData::face_data, and fluid_dynamics.
assemble_system_rhs()
template<int dim> void Tracer< dim >::assemble_system_rhs () override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 362 of file tracer.cc.
assemble_system_rhs_cg()
template<int dim> void Tracer< dim >::assemble_system_rhs_cg () private
Assembles the matrix associated with the solver when CG elements are used. This uses the WorkStream paradigm.
Definition at line 385 of file tracer.cc.
References Tracer< dim >::assemble_local_system_rhs(), Tracer< dim >::copy_local_rhs_to_global_rhs(), and fluid_dynamics.
assemble_system_rhs_dg()
template<int dim> void Tracer< dim >::assemble_system_rhs_dg () private
Assembles the rhs associated with the solver when DG elements are used. This uses the MeshWorker paradigm instead of the WorkStream paradigm This is because the DG system matrix is assembled in a different way and requires face and boundary integrals.
Definition at line 412 of file tracer.cc.
References StabilizedDGMethodsCopyData::face_data, and fluid_dynamics.
attach_solution_to_output()
template<int dim> void Tracer< dim >::attach_solution_to_output (DataOut< dim > & data_out) override virtual
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 648 of file tracer.cc.
calculate_L2_error()
template<int dim> double Tracer< dim >::calculate_L2_error ()
Calculates the L2 error of the solution.
Definition at line 655 of file tracer.cc.
calculate_tracer_statistics()
template<int dim> void Tracer< dim >::calculate_tracer_statistics () private
Calculate tracer statistics : Max, min, average and standard-deviation.
Definition at line 801 of file tracer.cc.
References Parameters::verbose.
compute_kelly()
template<int dim> void Tracer< dim >::compute_kelly (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > & ivar, dealii::Vector< float > & estimated_error_per_cell) override virtual
Compute the Kelly error estimator for mesh refinement. NB : not implemented for the tracer parameter for now.
Parameters
ivar The current element of the map simulation_parameters.mesh_adaptation.variables
estimated_error_per_cell The deal.II vector of estimated_error_per_cell
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1396 of file tracer.cc.
References tracer.
copy_local_matrix_to_global_matrix()
template<int dim> void Tracer< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell information to global matrix.
Definition at line 348 of file tracer.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void Tracer< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell rhs information to global rhs.
Definition at line 634 of file tracer.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_rhs.
finish_simulation()
template<int dim> void Tracer< dim >::finish_simulation () override virtual
Carry out the operations required to finish a simulation correctly.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 700 of file tracer.cc.
References Parameters::SimulationControl::steady, and Parameters::verbose.
get_dof_handler()
template<int dim> const DoFHandler< dim > & Tracer< dim >::get_dof_handler () inline override virtual
Returns the dof_handler of the tracer physics.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 202 of file tracer.h.
References Tracer< dim >::dof_handler.
get_evaluation_point()
template<int dim> GlobalVectorType & Tracer< dim >::get_evaluation_point () inline override virtual
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
Implements PhysicsSolver< VectorType >.
Definition at line 246 of file tracer.h.
References Tracer< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> GlobalVectorType & Tracer< dim >::get_local_evaluation_point () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 251 of file tracer.h.
References Tracer< dim >::local_evaluation_point.
get_newton_update()
template<int dim> GlobalVectorType & Tracer< dim >::get_newton_update () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 256 of file tracer.h.
References Tracer< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints< double > & Tracer< dim >::get_nonzero_constraints () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 271 of file tracer.h.
References Tracer< dim >::nonzero_constraints.
get_present_solution()
template<int dim> GlobalVectorType & Tracer< dim >::get_present_solution () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 261 of file tracer.h.
References Tracer< dim >::present_solution.
get_system_rhs()
template<int dim> GlobalVectorType & Tracer< dim >::get_system_rhs () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 266 of file tracer.h.
References Tracer< dim >::system_rhs.
output_newton_update_norms()
template<int dim> void Tracer< dim >::output_newton_update_norms (const unsigned int display_precision) inline override virtual
Output the L2 and Linfty norms of the correction vector.
Parameters
[in] display_precision Number of outputted digits.
Implements PhysicsSolver< VectorType >.
Definition at line 283 of file tracer.h.
References Tracer< dim >::newton_update, and PhysicsSolver< VectorType >::pcout.
percolate_time_vectors()
template<int dim> void Tracer< dim >::percolate_time_vectors () override virtual
Rearrange vector solution correctly for transient simulations.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 727 of file tracer.cc.
post_mesh_adaptation()
template<int dim> void Tracer< dim >::post_mesh_adaptation () override virtual
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1088 of file tracer.cc.
postprocess()
template<int dim> void Tracer< dim >::postprocess (bool first_iteration) override virtual
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 738 of file tracer.cc.
References announce_string(), calculate_L2_error(), fluid_dynamics, Parameters::Timer::iteration, and Parameters::verbose.
postprocess_tracer_flow_rate() [1/2]
template<int dim> template<typename GlobalVectorType > std::map< types::boundary_id, double > Tracer< dim >::postprocess_tracer_flow_rate (const GlobalVectorType & current_solution_fd) private
Post-processing. Calculate the tracer flow rate at every boundary.
Parameters
current_solution_fd current solution for the fluid dynamics, parsed by postprocess
Returns
values of the tracer flow rate at each boundary
Template Parameters
GlobalVectorType The type of the global vector used for the tracer physic
postprocess_tracer_flow_rate() [2/2]
template<int dim> template<typename VectorType > std::map< types::boundary_id, double > Tracer< dim >::postprocess_tracer_flow_rate (const VectorType & current_solution_fd)
Definition at line 897 of file tracer.cc.
References fluid_dynamics, levelset, and set_field_vector().
pre_mesh_adaptation()
template<int dim> void Tracer< dim >::pre_mesh_adaptation () override virtual
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1075 of file tracer.cc.
read_checkpoint()
template<int dim> void Tracer< dim >::read_checkpoint () override virtual
Allows tracer physics to set-up solution vector from checkpoint file;.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1150 of file tracer.cc.
References deserialize_table().
reinit_face_velocity_with_adequate_solution()
template<int dim> void Tracer< dim >::reinit_face_velocity_with_adequate_solution (const typename DoFHandler< dim >::active_cell_iterator & velocity_cell, const unsigned int & face_no, TracerScratchData< dim > & scratch_data) inline private
Helper function to reinit the face velocity with the adequate solution. This prevents code duplication throughout the tracer. The function looks at the multiphysics interface to decide if the velocity is a block velocity or a regular velocity. Furthermore, it also checks if a time-averaged solution is required. Otherwise the code here would be copied four times.
Parameters
[in] velocity_cell the iterator to the cell where the velocity is to be reinitialized.
[in] face_no the number of the face where the velocity is to be reinitialized.
[in,out] scratch_data the scratch data to be used for the reinitialization.
Definition at line 474 of file tracer.h.
References Parameters::average_velocity_profile, fluid_dynamics, Tracer< dim >::multiphysics, TracerScratchData< dim >::reinit_face_velocity(), Tracer< dim >::simulation_control, and Tracer< dim >::simulation_parameters.
set_initial_conditions()
template<int dim> void Tracer< dim >::set_initial_conditions () override virtual
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionnaly support the use of L2 projection or steady-state solutions.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1382 of file tracer.cc.
setup_assemblers()
template<int dim> void Tracer< dim >::setup_assemblers () private virtual
sets up the vector of assembler functions
Definition at line 38 of file tracer.cc.
References is_bdf().
setup_dofs()
template<int dim> void Tracer< dim >::setup_dofs () override virtual
Sets-up the DofHandler and the degree of freedom associated with the physics.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1196 of file tracer.cc.
References BoundaryConditions::periodic, tracer, and BoundaryConditions::tracer_dirichlet.
solve_linear_system()
template<int dim> void Tracer< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override virtual
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
Parameters
initial_step Provides the linear solver with indication if this solution is the first one for the system of equation or not
renewed_matrix Indicates to the linear solve if the system matrix has been recalculated or not
Implements PhysicsSolver< VectorType >.
Definition at line 1418 of file tracer.cc.
References Parameters::quiet, and tracer.
update_boundary_conditions()
template<int dim> void Tracer< dim >::update_boundary_conditions () override virtual
Update non zero constraints if the boundary is time-dependent.
Reimplemented from AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1337 of file tracer.cc.
References BoundaryConditions::periodic, and BoundaryConditions::tracer_dirichlet.
verify_consistency_of_boundary_conditions()
template<int dim> void Tracer< dim >::verify_consistency_of_boundary_conditions () inline private
Verify consistency of the input parameters for boundary conditions to ensure that for every boundary condition within the triangulation, a boundary condition has been specified in the input file.
Definition at line 299 of file tracer.h.
References Tracer< dim >::simulation_parameters, and Tracer< dim >::triangulation.
write_checkpoint()
template<int dim> void Tracer< dim >::write_checkpoint () override virtual
Prepares Heat Transfer to write checkpoint.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1117 of file tracer.cc.
References serialize_table().
write_tracer_flow_rates()
template<int dim> void Tracer< dim >::write_tracer_flow_rates (const std::map< types::boundary_id, double > & tracer_flow_rate_vector) private
Writes the tracer flow rates to an output file.
Definition at line 1015 of file tracer.cc.
References Parameters::verbose.
write_tracer_statistics()
template<int dim> void Tracer< dim >::write_tracer_statistics () private
Writes the tracer statistics to an output file.
Definition at line 1057 of file tracer.cc.
Member Data Documentation
assemblers
template<int dim> std::vector<std::shared_ptr<TracerAssemblerBase<dim> > > Tracer< dim >::assemblers private
Definition at line 588 of file tracer.h.
boundary_face_assembler
template<int dim> std::shared_ptr<TracerAssemblerBoundaryNitsche<dim> > Tracer< dim >::boundary_face_assembler private
Definition at line 591 of file tracer.h.
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > Tracer< dim >::cell_quadrature private
Definition at line 558 of file tracer.h.
computing_timer
template<int dim> TimerOutput Tracer< dim >::computing_timer private
Definition at line 543 of file tracer.h.
dof_handler
template<int dim> DoFHandler<dim> Tracer< dim >::dof_handler private
Definition at line 551 of file tracer.h.
error_table
template<int dim> ConvergenceTable Tracer< dim >::error_table private
Definition at line 562 of file tracer.h.
evaluation_point
template<int dim> GlobalVectorType Tracer< dim >::evaluation_point private
Definition at line 568 of file tracer.h.
face_quadrature
template<int dim> std::shared_ptr<Quadrature<dim - 1> > Tracer< dim >::face_quadrature private
Definition at line 559 of file tracer.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > Tracer< dim >::fe private
Definition at line 554 of file tracer.h.
inner_face_assembler
template<int dim> std::shared_ptr<TracerAssemblerSIPG<dim> > Tracer< dim >::inner_face_assembler private
Definition at line 590 of file tracer.h.
local_evaluation_point
template<int dim> GlobalVectorType Tracer< dim >::local_evaluation_point private
Definition at line 569 of file tracer.h.
locally_owned_dofs
template<int dim> IndexSet Tracer< dim >::locally_owned_dofs private
Definition at line 565 of file tracer.h.
locally_relevant_dofs
template<int dim> IndexSet Tracer< dim >::locally_relevant_dofs private
Definition at line 566 of file tracer.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > Tracer< dim >::mapping private
Definition at line 557 of file tracer.h.
multiphysics
template<int dim> MultiphysicsInterface<dim>* Tracer< dim >::multiphysics private
Definition at line 541 of file tracer.h.
newton_update
template<int dim> GlobalVectorType Tracer< dim >::newton_update private
Definition at line 570 of file tracer.h.
nonzero_constraints
template<int dim> AffineConstraints<double> Tracer< dim >::nonzero_constraints private
Definition at line 573 of file tracer.h.
present_solution
template<int dim> GlobalVectorType Tracer< dim >::present_solution private
Definition at line 571 of file tracer.h.
previous_solutions
template<int dim> std::vector<GlobalVectorType> Tracer< dim >::previous_solutions private
Definition at line 578 of file tracer.h.
previous_solutions_transfer
template<int dim> std::vector<parallel::distributed::SolutionTransfer<dim, GlobalVectorType> > Tracer< dim >::previous_solutions_transfer private
Definition at line 585 of file tracer.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> Tracer< dim >::simulation_control private
Definition at line 550 of file tracer.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& Tracer< dim >::simulation_parameters private
Definition at line 545 of file tracer.h.
solution_transfer
template<int dim> std::shared_ptr< parallel::distributed::SolutionTransfer<dim, GlobalVectorType> > Tracer< dim >::solution_transfer private
Definition at line 583 of file tracer.h.
statistics_table
template<int dim> TableHandler Tracer< dim >::statistics_table private
Definition at line 594 of file tracer.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix Tracer< dim >::system_matrix private
Definition at line 575 of file tracer.h.
system_rhs
template<int dim> GlobalVectorType Tracer< dim >::system_rhs private
Definition at line 572 of file tracer.h.
tracer_flow_rate_table
template<int dim> TableHandler Tracer< dim >::tracer_flow_rate_table private
Definition at line 595 of file tracer.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > Tracer< dim >::triangulation private
Definition at line 549 of file tracer.h.
zero_constraints
template<int dim> AffineConstraints<double> Tracer< dim >::zero_constraints private
Definition at line 574 of file tracer.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/tracer.h
/home/runner/work/lethe/lethe/source/solvers/tracer.cc