Lethe Open-Source Library: SimulationControlTransient Class Reference
SimulationControlTransient Class Reference
#include <simulation_control.h>
Public Member Functions
SimulationControlTransient (const Parameters::SimulationControl &param)
virtual void print_progression (const ConditionalOStream &pcout) override
virtual bool integrate () override
virtual bool is_at_end () override
virtual bool is_output_iteration () override
void save (const std::string &prefix) override
void read (const std::string &prefix) override
Public Member Functions inherited from SimulationControl
SimulationControl (const Parameters::SimulationControl &param)
void add_time_step (double p_timestep)
bool is_at_start ()
bool is_steady ()
bool is_bdf ()
bool output_enabled () const
bool get_output_boundaries ()
virtual bool is_verbose_iteration ()
virtual bool is_first_assembly ()
void update_assembly_method ()
void set_CFL (const double p_CFL)
void set_current_time_step (const double new_time_step)
void set_suggested_time_step (const double new_time_step)
void provide_residual (const double new_residual)
double get_time_step () const
std::string get_output_name () const
std::string get_output_path () const
unsigned int get_group_files () const
unsigned int get_log_precision () const
double get_current_time () const
double get_previous_time () const
std::vector< double > get_time_steps_vector () const
double get_CFL () const
unsigned int get_step_number () const
unsigned int get_number_subdivision () const
unsigned int get_log_frequency () const
Parameters::SimulationControl::TimeSteppingMethod get_assembly_method () const
void set_assembly_method (Parameters::SimulationControl::TimeSteppingMethod method)
unsigned int get_number_of_previous_solution_in_assembly () const
std::vector< double > get_simulation_times () const
Vector< double > const & get_bdf_coefficients ()
std::vector< double > get_checkpointed_simulation_control_info (const std::string &prefix)
Protected Member Functions
virtual double calculate_time_step () override
Protected Member Functions inherited from SimulationControl
void update_bdf_coefficients ()
Protected Attributes
bool adapt
double adaptative_time_step_scaling
double max_dt
double time_last_output
double output_time_frequency
std::vector< double > output_times_vector
unsigned int output_times_counter
bool no_more_output_times
std::vector< double > output_time_interval
Parameters::SimulationControl::OutputControl output_control
Protected Attributes inherited from SimulationControl
Parameters::SimulationControl::TimeSteppingMethod method
Parameters::SimulationControl::TimeSteppingMethod assembly_method
double current_time
double previous_time
double time_step
double initial_time_step
double end_time
bool time_step_independent_of_end_time
std::vector< double > time_step_vector
unsigned int iteration_number
unsigned int number_mesh_adapt
double CFL
double max_CFL
double residual
double stop_tolerance
unsigned int output_iteration_frequency
unsigned int log_frequency
unsigned int log_precision
unsigned int subdivision
unsigned int group_files
std::string output_name
std::string output_path
bool output_boundaries
bool first_assembly
Parameters::SimulationControl::BDFStartupMethods bdf_start_method
double startup_timestep_scaling
Vector< double > bdf_coefs
Additional Inherited Members
Static Protected Attributes inherited from SimulationControl
static const unsigned int n_previous_time_steps = 4
Detailed Description
Definition at line 483 of file simulation_control.h.
Constructor & Destructor Documentation
SimulationControlTransient()
SimulationControlTransient::SimulationControlTransient (const Parameters::SimulationControl & param)
Definition at line 212 of file simulation_control.cc.
Member Function Documentation
calculate_time_step()
double SimulationControlTransient::calculate_time_step () override protected virtual
Calculates the next value of the time step. If adaptation is enabled, the time step is calculated in order to ensure that the CFL condition is bound by the maximal CFL value. The new time step is equal to adaptative_time_step_scaling * the previous time step. If the time_step_independent_of_end_time is set to false, the time step is asjusted to meet exactly the end time; the default is to not modify the time step.
Reimplemented from SimulationControl.
Definition at line 276 of file simulation_control.cc.
References adapt, adaptative_time_step_scaling, SimulationControl::CFL, SimulationControl::current_time, SimulationControl::end_time, SimulationControl::iteration_number, SimulationControl::max_CFL, max_dt, SimulationControl::time_step, and SimulationControl::time_step_independent_of_end_time.
integrate()
bool SimulationControlTransient::integrate () override virtual
Proceeds with the simulation until the end condition is reached.
Implements SimulationControl.
Definition at line 248 of file simulation_control.cc.
References SimulationControl::add_time_step(), calculate_time_step(), SimulationControl::current_time, SimulationControl::first_assembly, is_at_end(), SimulationControl::is_bdf(), SimulationControl::iteration_number, SimulationControl::previous_time, SimulationControl::time_step, SimulationControl::update_assembly_method(), and SimulationControl::update_bdf_coefficients().
is_at_end()
bool SimulationControlTransient::is_at_end () override virtual
Ends the simulation when the end time is reached.
Implements SimulationControl.
Reimplemented in SimulationControlAdjointSteady.
Definition at line 269 of file simulation_control.cc.
References SimulationControl::current_time, SimulationControl::end_time, and SimulationControl::time_step.
is_output_iteration()
bool SimulationControlTransient::is_output_iteration () override virtual
Output iterations are calculated based on the value of the output time or the output interval and the output frequency within the interval.
Reimplemented from SimulationControl.
Definition at line 303 of file simulation_control.cc.
References calculate_time_step(), SimulationControl::current_time, SimulationControl::get_current_time(), SimulationControl::get_step_number(), is_at_end(), Parameters::SimulationControl::iteration, no_more_output_times, output_control, SimulationControl::output_iteration_frequency, output_time_frequency, output_time_interval, output_times_counter, output_times_vector, SimulationControl::previous_time, and time_last_output.
print_progression()
void SimulationControlTransient::print_progression (const ConditionalOStream & pcout) override virtual
print_progress Function that prints the current progress status of the simulation
Parameters
pcout the ConditionalOSStream that is use to write
Implements SimulationControl.
Reimplemented in SimulationControlAdjointSteady, and SimulationControlTransientDEM.
Definition at line 227 of file simulation_control.cc.
References announce_string(), SimulationControl::current_time, SimulationControl::get_CFL(), SimulationControl::is_verbose_iteration(), SimulationControl::iteration_number, SimulationControl::log_precision, and SimulationControl::time_step.
read()
void SimulationControlTransient::read (const std::string & prefix) override virtual
Reads the simulation control information from the checkpoint file and updates the time step vector, the CFL value, the time, the iteration number and the index of the output times vector if time control is used.
Parameters
prefix The prefix of the checkpoint of the simulation
Reimplemented from SimulationControl.
Definition at line 425 of file simulation_control.cc.
References output_control, output_times_counter, SimulationControl::read(), and Parameters::SimulationControl::time.
save()
void SimulationControlTransient::save (const std::string & prefix) override virtual
Save the simulation control information from the checkpoint file and updates the time step vector, the CFL value, the time, the iteration number and the index of the output times vector if time control is used.
Parameters
prefix The prefix of the checkpoint of the simulation
Reimplemented from SimulationControl.
Definition at line 412 of file simulation_control.cc.
References output_control, output_times_counter, SimulationControl::save(), and Parameters::SimulationControl::time.
Member Data Documentation
adapt
bool SimulationControlTransient::adapt protected
Definition at line 487 of file simulation_control.h.
adaptative_time_step_scaling
double SimulationControlTransient::adaptative_time_step_scaling protected
Definition at line 490 of file simulation_control.h.
max_dt
double SimulationControlTransient::max_dt protected
Definition at line 493 of file simulation_control.h.
no_more_output_times
bool SimulationControlTransient::no_more_output_times protected
Definition at line 509 of file simulation_control.h.
output_control
Parameters::SimulationControl::OutputControl SimulationControlTransient::output_control protected
Definition at line 516 of file simulation_control.h.
output_time_frequency
double SimulationControlTransient::output_time_frequency protected
Definition at line 499 of file simulation_control.h.
output_time_interval
std::vector<double> SimulationControlTransient::output_time_interval protected
Definition at line 513 of file simulation_control.h.
output_times_counter
unsigned int SimulationControlTransient::output_times_counter protected
Definition at line 505 of file simulation_control.h.
output_times_vector
std::vector<double> SimulationControlTransient::output_times_vector protected
Definition at line 502 of file simulation_control.h.
time_last_output
double SimulationControlTransient::time_last_output protected
Definition at line 496 of file simulation_control.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/simulation_control.h
/home/runner/work/lethe/lethe/source/core/simulation_control.cc