Lethe Open-Source Library: CLSSubequationsInterface< dim > Class Template Reference
CLSSubequationsInterface< dim > Class Template Reference
#include <cls_subequations_interface.h>
Public Member Functions
CLSSubequationsInterface (const SimulationParameters< dim > &p_simulation_parameters, const ConditionalOStream &p_pcout, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > &p_simulation_control)
~CLSSubequationsInterface ()=default
void initialize_subequations (const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > &p_simulation_control)
void setup_dofs ()
void setup_specific_subequation_dofs (const CLSSubequationsID &subequation_id)
void solve ()
void solve_specific_subequation (const CLSSubequationsID &subequation_id)
std::vector< CLSSubequationsID > get_active_subequations ()
const DoFHandler< dim > & get_dof_handler (const CLSSubequationsID &subequation_id)
const DoFHandler< dim > & get_cls_dof_handler ()
const GlobalVectorType & get_solution (const CLSSubequationsID &subequation_id)
const GlobalVectorType & get_cls_solution ()
bool get_solution_validity (const CLSSubequationsID &subequation_id)
std::string get_subequation_string (const CLSSubequationsID &subequation_id)
void set_dof_handler (const CLSSubequationsID &subequation_id, std::shared_ptr< DoFHandler< dim > > dof_handler)
void set_solution (const CLSSubequationsID &subequation_id, std::shared_ptr< GlobalVectorType > solution_vector)
void set_cls_solution_and_dof_handler (const GlobalVectorType &cls_solution_vector, const DoFHandler< dim > &dof_handler_cls)
void set_solution_valid (const CLSSubequationsID &subequation_id)
bool validity_map_has_been_reset ()
Private Member Functions
void reset_subequations_solutions_validity ()
Private Attributes
const ConditionalOStream pcout
std::optional< std::reference_wrapper< const DoFHandler< dim > > > dof_handler_cls
std::optional< std::reference_wrapper< const GlobalVectorType > > cls_solution_vector
std::vector< CLSSubequationsID > active_subequations
std::map< CLSSubequationsID, std::shared_ptr< PhysicsSubequationsSolverBase > > subequations
std::map< CLSSubequationsID, std::shared_ptr< DoFHandler< dim > > > subequations_dof_handler
std::map< CLSSubequationsID, std::shared_ptr< GlobalVectorType > > subequations_solutions
std::map< CLSSubequationsID, bool > subequations_solutions_validity
Detailed Description
template<int dim>
class CLSSubequationsInterface< dim >
Interface for secondary equations (subequations) solved within the CLS auxiliary physics.
Template Parameters
dim Number of dimensions of the problem.
Definition at line 44 of file cls_subequations_interface.h.
Constructor & Destructor Documentation
CLSSubequationsInterface()
template<int dim> CLSSubequationsInterface< dim >::CLSSubequationsInterface (const SimulationParameters< dim > & p_simulation_parameters, const ConditionalOStream & p_pcout, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > & p_simulation_control) inline
Constructor of an interface for subequations that require the use of a solver within the span of the CLS auxiliary physics' resolution.
Parameters
[in] p_simulation_parameters Simulation parameters.
[in] p_pcout Parallel cout used to print the information.
[in] p_triangulation Distributed mesh information.
[in] p_simulation_control SimulationControl object.
Definition at line 59 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::initialize_subequations().
~CLSSubequationsInterface()
template<int dim> CLSSubequationsInterface< dim >::~CLSSubequationsInterface () default
Default destructor.
Member Function Documentation
get_active_subequations()
template<int dim> std::vector< CLSSubequationsID > CLSSubequationsInterface< dim >::get_active_subequations () inline
Get vector of active subequations.
Returns
Vector of active subequations identifiers.
Definition at line 160 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations.
get_cls_dof_handler()
template<int dim> const DoFHandler< dim > & CLSSubequationsInterface< dim >::get_cls_dof_handler () inline
Get a reference to the DoFHandler of the CLS auxiliary physics.
Returns
Reference to the DoFHandler of the CLS auxiliary physics associated to the set CLS solution field.
Definition at line 191 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::dof_handler_cls.
get_cls_solution()
template<int dim> const GlobalVectorType & CLSSubequationsInterface< dim >::get_cls_solution () inline
Get a reference to the phase indicator solution vector.
Returns
Reference to the phase indicator solution vector.
Definition at line 220 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::cls_solution_vector.
get_dof_handler()
template<int dim> const DoFHandler< dim > & CLSSubequationsInterface< dim >::get_dof_handler (const CLSSubequationsID & subequation_id) inline
Get a reference to the DoFHandler of a specific subequation.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Returns
Reference to the DoFHandler of the specified subequation.
Definition at line 174 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, and CLSSubequationsInterface< dim >::subequations_dof_handler.
get_solution()
template<int dim> const GlobalVectorType & CLSSubequationsInterface< dim >::get_solution (const CLSSubequationsID & subequation_id) inline
Get a reference to the solution vector of a specific subequation.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Returns
Reference to the solution vector of the specified subequation.
Definition at line 205 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::get_solution_validity(), CLSSubequationsInterface< dim >::get_subequation_string(), and CLSSubequationsInterface< dim >::subequations_solutions.
get_solution_validity()
template<int dim> bool CLSSubequationsInterface< dim >::get_solution_validity (const CLSSubequationsID & subequation_id) inline
Check and return a boolean indicating if the solution of the subequation has been solved for the corresponding dof_handler_cls and/or cls_solution_vector previously set with CLSSubequationsInterface<dim>::set_cls_solution_and_dof_handler.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Returns
true if the solution of the subequation corresponds to the set dof_handler_cls and/or cls_solution_vector.
Otherwise, false.
Definition at line 240 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, and CLSSubequationsInterface< dim >::subequations_solutions_validity.
get_subequation_string()
template<int dim> std::string CLSSubequationsInterface< dim >::get_subequation_string (const CLSSubequationsID & subequation_id) inline
Get the string associated with a specific subequation.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Returns
String associated with the specified subequation.
Note
This is used for printing purposes.
Definition at line 260 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, curvature_projection, pde_based_interface_reinitialization, and phase_gradient_projection.
initialize_subequations()
template<int dim> void CLSSubequationsInterface< dim >::initialize_subequations (const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > & p_simulation_control)
Initialize subequations necessary for the simulation and reset subeqaution validation map.
Parameters
[in] p_simulation_parameters Simulation parameters.
[in] p_triangulation Distributed mesh information.
[in] p_simulation_control SimulationControl object.
Definition at line 12 of file cls_subequations_interface.cc.
References curvature_projection, SimulationParameters< dim >::multiphysics, pde_based_interface_reinitialization, and phase_gradient_projection.
reset_subequations_solutions_validity()
template<int dim> void CLSSubequationsInterface< dim >::reset_subequations_solutions_validity () inline private
Reset all boolean in the validity associated with active subequations to false.
Definition at line 390 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, and CLSSubequationsInterface< dim >::subequations_solutions_validity.
set_cls_solution_and_dof_handler()
template<int dim> void CLSSubequationsInterface< dim >::set_cls_solution_and_dof_handler (const GlobalVectorType & cls_solution_vector, const DoFHandler< dim > & dof_handler_cls) inline
Set a new CLS solution vector and DoFHandler for the subequations to be solved and reset their validity.
Parameters
[in] cls_solution_vector CLS solution vector associated with the subequations to be solved.
[in] dof_handler_cls Reference to the DoFHandler associated with the specified CLS solution.
Definition at line 338 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::cls_solution_vector, CLSSubequationsInterface< dim >::dof_handler_cls, and CLSSubequationsInterface< dim >::reset_subequations_solutions_validity().
set_dof_handler()
template<int dim> void CLSSubequationsInterface< dim >::set_dof_handler (const CLSSubequationsID & subequation_id, std::shared_ptr< DoFHandler< dim > > dof_handler) inline
Set the DoFHandler associated with a specific subequation in the interface.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
[in] dof_handler Shared pointer to the DoFHandler of a specific subequation.
Definition at line 296 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, and CLSSubequationsInterface< dim >::subequations_dof_handler.
set_solution()
template<int dim> void CLSSubequationsInterface< dim >::set_solution (const CLSSubequationsID & subequation_id, std::shared_ptr< GlobalVectorType > solution_vector) inline
Set the solution associated with a specific subequation in the interface.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
[in] solution_vector Shared pointer to the solution vector of a specific subequation.
Definition at line 317 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, and CLSSubequationsInterface< dim >::subequations_solutions.
set_solution_valid()
template<int dim> void CLSSubequationsInterface< dim >::set_solution_valid (const CLSSubequationsID & subequation_id) inline
Set the solution as valid after solving it.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Definition at line 356 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, and CLSSubequationsInterface< dim >::subequations_solutions_validity.
setup_dofs()
template<int dim> void CLSSubequationsInterface< dim >::setup_dofs () inline
Setup the DofHandler and the degree of freedom associated with the subequations.
Definition at line 99 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::subequations.
setup_specific_subequation_dofs()
template<int dim> void CLSSubequationsInterface< dim >::setup_specific_subequation_dofs (const CLSSubequationsID & subequation_id) inline
Setup the DofHandler and the degree of freedom associated with the physics.
Parameters
[in] subequation_id Identifier associated with the subequation wished to solve.
Definition at line 115 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, and CLSSubequationsInterface< dim >::subequations.
solve()
template<int dim> void CLSSubequationsInterface< dim >::solve () inline
Call solving method of active subequations.
Definition at line 129 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::subequations.
solve_specific_subequation()
template<int dim> void CLSSubequationsInterface< dim >::solve_specific_subequation (const CLSSubequationsID & subequation_id) inline
Call solving method for a specific subequation.
Parameters
[in] subequation_id Identifier associated with the subequation wished to solve.
Definition at line 144 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::active_subequations, and CLSSubequationsInterface< dim >::subequations.
validity_map_has_been_reset()
template<int dim> bool CLSSubequationsInterface< dim >::validity_map_has_been_reset () inline
Check if all booleans in subequations_solutions_validity have been reset to false.
Returns
true if all booleans in the map are set to false or;
false if at least one of the booleans is set to true
Definition at line 374 of file cls_subequations_interface.h.
References CLSSubequationsInterface< dim >::subequations_solutions_validity.
Member Data Documentation
active_subequations
template<int dim> std::vector<CLSSubequationsID> CLSSubequationsInterface< dim >::active_subequations private
Data structure that stores all enabled subequations.
Definition at line 410 of file cls_subequations_interface.h.
cls_solution_vector
template<int dim> std::optional<std::reference_wrapper<const GlobalVectorType> > CLSSubequationsInterface< dim >::cls_solution_vector private
CLS solution field associated with solved equations
Note
Serves as initial condition in PDE-based reinitialization
Definition at line 407 of file cls_subequations_interface.h.
dof_handler_cls
template<int dim> std::optional<std::reference_wrapper<const DoFHandler<dim> > > CLSSubequationsInterface< dim >::dof_handler_cls private
CLS DoFHandler associated with solved equations.
Definition at line 402 of file cls_subequations_interface.h.
pcout
template<int dim> const ConditionalOStream CLSSubequationsInterface< dim >::pcout private
Parallel consol output object.
Definition at line 399 of file cls_subequations_interface.h.
subequations
template<int dim> std::map<CLSSubequationsID, std::shared_ptr<PhysicsSubequationsSolverBase> > CLSSubequationsInterface< dim >::subequations private
Subequations are stored within a map of shared pointer to ensure proper memory management
Definition at line 415 of file cls_subequations_interface.h.
subequations_dof_handler
template<int dim> std::map<CLSSubequationsID, std::shared_ptr<DoFHandler<dim> > > CLSSubequationsInterface< dim >::subequations_dof_handler private
Map of DoFHandler of subequations.
Definition at line 419 of file cls_subequations_interface.h.
subequations_solutions
template<int dim> std::map<CLSSubequationsID, std::shared_ptr<GlobalVectorType> > CLSSubequationsInterface< dim >::subequations_solutions private
Present solutions map.
Definition at line 423 of file cls_subequations_interface.h.
subequations_solutions_validity
template<int dim> std::map<CLSSubequationsID, bool> CLSSubequationsInterface< dim >::subequations_solutions_validity private
Booleans indicating if the subequation has been solved with the set CLS solution vector. The CLS solution vector is set with CLSSubequationsInterface<dim>::set_cls_solution_and_dof_handler.
During initialization (CLSSubequationsInterface<dim>::initialize_subequations), all boolean are set to false.
We start by setting a CLS solution and DOFHandler (CLSSubequationsInterface<dim>::set_cls_solution_and_dof_handler), and then start solving equations making sure that dependencies are met (CLSPhaseGradientProjection<dim>::check_dependencies_validity, CLSCurvatureProjection<dim>::check_dependencies_validity, and CLSPDEBasedInterfaceReinitialization<dim>::check_dependencies_validity). For instance, to solve the curvature projection subequation, the phase gradient projection subequation has to be solved before as the projected phase gradient is used in the curvature projection subequation.
A subequation in the validity map is to true only when it is solved, and it remains valid until a new CLS solution and/or DOFHandler are set through CLSSubequationsInterface<dim>::set_cls_solution_and_dof_handler.
This validation mechanism allows, to check if:
A new CLS solution has been set;
All dependencies of the subequation have been solved;
The current solution of the subequation is valid, and avoid unnecessarily solving it once more.
Note
CLSSubequationsInterface<dim>::set_cls_solution_and_dof_handler also resets the validity map values to false.
Definition at line 459 of file cls_subequations_interface.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/cls_subequations_interface.h
/home/runner/work/lethe/lethe/source/solvers/cls_subequations_interface.cc