Lethe Open-Source Library: CahnHilliard< dim > Class Template Reference
CahnHilliard< dim > Class Template Reference
#include <cahn_hilliard.h>
Public Member Functions
CahnHilliard (MultiphysicsInterface< dim > *multiphysics_interface, const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control)
void attach_solution_to_output (DataOut< dim > &data_out) override
std::pair< double, double > calculate_L2_error ()
void finish_simulation () override
void percolate_time_vectors () override
void modify_solution () override
void postprocess (bool first_iteration) override
void pre_mesh_adaptation () override
void post_mesh_adaptation () override
void compute_kelly (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > &ivar, dealii::Vector< float > &estimated_error_per_cell) override
void write_checkpoint () override
void read_checkpoint () override
const DoFHandler< dim > & get_dof_handler () override
void setup_dofs () override
void set_initial_conditions () override
void update_boundary_conditions () override
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
GlobalVectorType & get_evaluation_point () override
GlobalVectorType & get_local_evaluation_point () override
GlobalVectorType & get_newton_update () override
GlobalVectorType & get_present_solution () override
GlobalVectorType & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
void output_newton_update_norms (const unsigned int display_precision) override
Public Member Functions inherited from AuxiliaryPhysics< dim, GlobalVectorType >
AuxiliaryPhysics (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~AuxiliaryPhysics ()
void setup_preconditioner () override
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void verify_consistency_of_boundary_conditions ()
void assemble_system_matrix () override
void assemble_system_rhs () override
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, CahnHilliardScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, CahnHilliardScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
virtual void setup_assemblers ()
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData &copy_data)
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData &copy_data)
void calculate_phase_statistics ()
void write_phase_statistics ()
void calculate_phase_energy ()
void write_phase_energy ()
template<typename VectorType >
std::pair< Tensor< 1, dim >, Tensor< 1, dim > > calculate_barycenter (const GlobalVectorType &solution, const VectorType &current_solution_fd)
void apply_phase_filter ()
Private Attributes
MultiphysicsInterface< dim > * multiphysics
TimerOutput computing_timer
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< SimulationControl > simulation_control
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
ConvergenceTable error_table
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
GlobalVectorType present_solution
GlobalVectorType system_rhs
AffineConstraints< double > nonzero_constraints
AffineConstraints< double > zero_constraints
TrilinosWrappers::SparseMatrix system_matrix
GlobalVectorType filtered_solution
std::vector< GlobalVectorType > previous_solutions
std::shared_ptr< parallel::distributed::SolutionTransfer< dim, GlobalVectorType > > solution_transfer
std::vector< parallel::distributed::SolutionTransfer< dim, GlobalVectorType > > previous_solutions_transfer
std::vector< std::shared_ptr< CahnHilliardAssemblerBase< dim > > > assemblers
TableHandler barycenter_table
TableHandler statistics_table
TableHandler phase_energy_table
std::shared_ptr< CahnHilliardFilterBase > filter
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class CahnHilliard< dim >
Definition at line 54 of file cahn_hilliard.h.
Constructor & Destructor Documentation
CahnHilliard()
template<int dim> CahnHilliard< dim >::CahnHilliard (MultiphysicsInterface< dim > * multiphysics_interface, const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control) inline
Definition at line 57 of file cahn_hilliard.h.
References CahnHilliard< dim >::cell_quadrature, CahnHilliard< dim >::computing_timer, CahnHilliard< dim >::dof_handler, CahnHilliard< dim >::face_quadrature, CahnHilliard< dim >::fe, CahnHilliard< dim >::mapping, maximum_number_of_previous_solutions(), Parameters::Timer::none, CahnHilliard< dim >::previous_solutions, CahnHilliard< dim >::previous_solutions_transfer, CahnHilliard< dim >::simulation_parameters, and CahnHilliard< dim >::solution_transfer.
Member Function Documentation
apply_phase_filter()
template<int dim> void CahnHilliard< dim >::apply_phase_filter () private
Applies filter on phase fraction values.
Definition at line 1419 of file cahn_hilliard.cc.
References CahnHilliardFilterBase::model_cast(), and Parameters::verbose.
assemble_local_system_matrix()
template<int dim> void CahnHilliard< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, CahnHilliardScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for CahnHilliardScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 122 of file cahn_hilliard.cc.
References CahnHilliardScratchData< dim >::calculate_physical_properties(), StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, CahnHilliardScratchData< dim >::reinit(), CahnHilliardScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_local_system_rhs()
template<int dim> void CahnHilliard< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, CahnHilliardScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for CahnHilliardScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 219 of file cahn_hilliard.cc.
References CahnHilliardScratchData< dim >::calculate_physical_properties(), StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, CahnHilliardScratchData< dim >::reinit(), CahnHilliardScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_system_matrix()
template<int dim> void CahnHilliard< dim >::assemble_system_matrix () override private virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 90 of file cahn_hilliard.cc.
References CahnHilliard< dim >::assemble_local_system_matrix(), CahnHilliard< dim >::copy_local_matrix_to_global_matrix(), and fluid_dynamics.
assemble_system_rhs()
template<int dim> void CahnHilliard< dim >::assemble_system_rhs () override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 187 of file cahn_hilliard.cc.
References CahnHilliard< dim >::assemble_local_system_rhs(), CahnHilliard< dim >::copy_local_rhs_to_global_rhs(), and fluid_dynamics.
attach_solution_to_output()
template<int dim> void CahnHilliard< dim >::attach_solution_to_output (DataOut< dim > & data_out) override virtual
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 284 of file cahn_hilliard.cc.
calculate_barycenter()
template<int dim> template<typename VectorType > template std::pair< Tensor< 1, 3 >, Tensor< 1, 3 > > CahnHilliard< dim >::calculate_barycenter< GlobalBlockVectorType > (const GlobalVectorType & solution, const VectorType & current_solution_fd) private
Calculates the barycenter of fluid 1 and its velocity.
Parameters
solution Cahn-Hilliard solution
current_solution_fd Fluid dynamics solution
Definition at line 1328 of file cahn_hilliard.cc.
References fluid_dynamics, CahnHilliardFilterBase::model_cast(), and velocity.
calculate_L2_error()
template<int dim> std::pair< double, double > CahnHilliard< dim >::calculate_L2_error ()
Calculates the L2 error of the solution.
Definition at line 315 of file cahn_hilliard.cc.
calculate_phase_energy()
template<int dim> void CahnHilliard< dim >::calculate_phase_energy () private
Calculate the phase energies : bulk energy, interface energy and total energy.
Definition at line 495 of file cahn_hilliard.cc.
References announce_string(), Parameters::manual, and Parameters::verbose.
calculate_phase_statistics()
template<int dim> void CahnHilliard< dim >::calculate_phase_statistics () private
Calculate phase statistics for monitoring purposes.
Definition at line 389 of file cahn_hilliard.cc.
References announce_string(), and Parameters::verbose.
compute_kelly()
template<int dim> void CahnHilliard< dim >::compute_kelly (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > & ivar, dealii::Vector< float > & estimated_error_per_cell) override virtual
Compute the Kelly error estimator for mesh refinement. NB : not implemented for the cahn_hilliard equations for now.
Parameters
ivar The current element of the map simulation_parameters.mesh_adaptation.variables
estimated_error_per_cell The deal.II vector of estimated_error_per_cell
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 900 of file cahn_hilliard.cc.
References chemical_potential_cahn_hilliard, and phase_cahn_hilliard.
copy_local_matrix_to_global_matrix()
template<int dim> void CahnHilliard< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell information to global matrix.
Definition at line 173 of file cahn_hilliard.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void CahnHilliard< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell rhs information to global rhs.
Definition at line 270 of file cahn_hilliard.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_rhs.
finish_simulation()
template<int dim> void CahnHilliard< dim >::finish_simulation () override virtual
Carry out the operations required to finish a simulation correctly.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 599 of file cahn_hilliard.cc.
References Parameters::SimulationControl::steady, and Parameters::verbose.
get_dof_handler()
template<int dim> const DoFHandler< dim > & CahnHilliard< dim >::get_dof_handler () inline override virtual
Returns the dof_handler of the Cahn-Hilliard physics.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 232 of file cahn_hilliard.h.
References CahnHilliard< dim >::dof_handler.
get_evaluation_point()
template<int dim> GlobalVectorType & CahnHilliard< dim >::get_evaluation_point () inline override virtual
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
Implements PhysicsSolver< VectorType >.
Definition at line 276 of file cahn_hilliard.h.
References CahnHilliard< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> GlobalVectorType & CahnHilliard< dim >::get_local_evaluation_point () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 281 of file cahn_hilliard.h.
References CahnHilliard< dim >::local_evaluation_point.
get_newton_update()
template<int dim> GlobalVectorType & CahnHilliard< dim >::get_newton_update () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 286 of file cahn_hilliard.h.
References CahnHilliard< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints< double > & CahnHilliard< dim >::get_nonzero_constraints () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 301 of file cahn_hilliard.h.
References CahnHilliard< dim >::nonzero_constraints.
get_present_solution()
template<int dim> GlobalVectorType & CahnHilliard< dim >::get_present_solution () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 291 of file cahn_hilliard.h.
References CahnHilliard< dim >::present_solution.
get_system_rhs()
template<int dim> GlobalVectorType & CahnHilliard< dim >::get_system_rhs () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 296 of file cahn_hilliard.h.
References CahnHilliard< dim >::system_rhs.
modify_solution()
template<int dim> void CahnHilliard< dim >::modify_solution () override virtual
Carry out modifications on the auxiliary physic solution.
Reimplemented from AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 640 of file cahn_hilliard.cc.
output_newton_update_norms()
template<int dim> void CahnHilliard< dim >::output_newton_update_norms (const unsigned int display_precision) override virtual
Output the L2 and Linfty norms of the correction vector.
Parameters
[in] display_precision Number of outputted digits.
Implements PhysicsSolver< VectorType >.
Definition at line 1495 of file cahn_hilliard.cc.
percolate_time_vectors()
template<int dim> void CahnHilliard< dim >::percolate_time_vectors () override virtual
Rearrange vector solution correctly for transient simulations.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 629 of file cahn_hilliard.cc.
post_mesh_adaptation()
template<int dim> void CahnHilliard< dim >::post_mesh_adaptation () override virtual
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 871 of file cahn_hilliard.cc.
postprocess()
template<int dim> void CahnHilliard< dim >::postprocess (bool first_iteration) override virtual
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 648 of file cahn_hilliard.cc.
References announce_string(), Parameters::average_velocity_profile, calculate_L2_error(), fluid_dynamics, Parameters::Timer::iteration, make_table_scalars_tensors(), and Parameters::verbose.
pre_mesh_adaptation()
template<int dim> void CahnHilliard< dim >::pre_mesh_adaptation () override virtual
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 858 of file cahn_hilliard.cc.
read_checkpoint()
template<int dim> void CahnHilliard< dim >::read_checkpoint () override virtual
Allows Cahn-Hilliard physics to set-up solution vector from checkpoint file;.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 968 of file cahn_hilliard.cc.
References deserialize_table().
set_initial_conditions()
template<int dim> void CahnHilliard< dim >::set_initial_conditions () override virtual
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionally support the use of L2 projection or steady-state solutions.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1217 of file cahn_hilliard.cc.
setup_assemblers()
template<int dim> void CahnHilliard< dim >::setup_assemblers () private virtual
sets up the vector of assembler functions
Definition at line 34 of file cahn_hilliard.cc.
References is_bdf(), and Parameters::manual.
setup_dofs()
template<int dim> void CahnHilliard< dim >::setup_dofs () override virtual
Sets-up the DofHandler and the degree of freedom associated with the physics.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1014 of file cahn_hilliard.cc.
References cahn_hilliard, and BoundaryConditions::periodic.
solve_linear_system()
template<int dim> void CahnHilliard< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override virtual
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
Parameters
initial_step Provides the linear solver with indication if this solution is the first one for the system of equation or not
renewed_matrix Indicates to the linear solve if the system matrix has been recalculated or not
Implements PhysicsSolver< VectorType >.
Definition at line 1246 of file cahn_hilliard.cc.
References cahn_hilliard, and Parameters::quiet.
update_boundary_conditions()
template<int dim> void CahnHilliard< dim >::update_boundary_conditions () override virtual
Update non zero constraints if the boundary is time-dependent.
Reimplemented from AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1159 of file cahn_hilliard.cc.
References BoundaryConditions::cahn_hilliard_dirichlet_phase_order, and BoundaryConditions::periodic.
verify_consistency_of_boundary_conditions()
template<int dim> void CahnHilliard< dim >::verify_consistency_of_boundary_conditions () inline private
Verify consistency of the input parameters for boundary conditions to ensure that for every boundary condition within the triangulation, a boundary condition has been specified in the input file.
Definition at line 322 of file cahn_hilliard.h.
References CahnHilliard< dim >::simulation_parameters, and CahnHilliard< dim >::triangulation.
write_checkpoint()
template<int dim> void CahnHilliard< dim >::write_checkpoint () override virtual
Prepares Cahn-Hilliard to write checkpoint.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 935 of file cahn_hilliard.cc.
References serialize_table().
write_phase_energy()
template<int dim> void CahnHilliard< dim >::write_phase_energy () private
Definition at line 578 of file cahn_hilliard.cc.
write_phase_statistics()
template<int dim> void CahnHilliard< dim >::write_phase_statistics () private
Writes the phase statistics to an output file.
Definition at line 478 of file cahn_hilliard.cc.
Member Data Documentation
assemblers
template<int dim> std::vector<std::shared_ptr<CahnHilliardAssemblerBase<dim> > > CahnHilliard< dim >::assemblers private
Definition at line 507 of file cahn_hilliard.h.
barycenter_table
template<int dim> TableHandler CahnHilliard< dim >::barycenter_table private
Definition at line 510 of file cahn_hilliard.h.
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > CahnHilliard< dim >::cell_quadrature private
Definition at line 475 of file cahn_hilliard.h.
computing_timer
template<int dim> TimerOutput CahnHilliard< dim >::computing_timer private
Definition at line 461 of file cahn_hilliard.h.
dof_handler
template<int dim> DoFHandler<dim> CahnHilliard< dim >::dof_handler private
Definition at line 469 of file cahn_hilliard.h.
error_table
template<int dim> ConvergenceTable CahnHilliard< dim >::error_table private
Definition at line 479 of file cahn_hilliard.h.
evaluation_point
template<int dim> GlobalVectorType CahnHilliard< dim >::evaluation_point private
Definition at line 485 of file cahn_hilliard.h.
face_quadrature
template<int dim> std::shared_ptr<Quadrature<dim - 1> > CahnHilliard< dim >::face_quadrature private
Definition at line 476 of file cahn_hilliard.h.
fe
template<int dim> std::shared_ptr<FESystem<dim> > CahnHilliard< dim >::fe private
Definition at line 472 of file cahn_hilliard.h.
filter
template<int dim> std::shared_ptr<CahnHilliardFilterBase> CahnHilliard< dim >::filter private
Definition at line 519 of file cahn_hilliard.h.
filtered_solution
template<int dim> GlobalVectorType CahnHilliard< dim >::filtered_solution private
Definition at line 493 of file cahn_hilliard.h.
local_evaluation_point
template<int dim> GlobalVectorType CahnHilliard< dim >::local_evaluation_point private
Definition at line 486 of file cahn_hilliard.h.
locally_owned_dofs
template<int dim> IndexSet CahnHilliard< dim >::locally_owned_dofs private
Definition at line 482 of file cahn_hilliard.h.
locally_relevant_dofs
template<int dim> IndexSet CahnHilliard< dim >::locally_relevant_dofs private
Definition at line 483 of file cahn_hilliard.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > CahnHilliard< dim >::mapping private
Definition at line 474 of file cahn_hilliard.h.
multiphysics
template<int dim> MultiphysicsInterface<dim>* CahnHilliard< dim >::multiphysics private
Definition at line 459 of file cahn_hilliard.h.
newton_update
template<int dim> GlobalVectorType CahnHilliard< dim >::newton_update private
Definition at line 487 of file cahn_hilliard.h.
nonzero_constraints
template<int dim> AffineConstraints<double> CahnHilliard< dim >::nonzero_constraints private
Definition at line 490 of file cahn_hilliard.h.
phase_energy_table
template<int dim> TableHandler CahnHilliard< dim >::phase_energy_table private
Definition at line 516 of file cahn_hilliard.h.
present_solution
template<int dim> GlobalVectorType CahnHilliard< dim >::present_solution private
Definition at line 488 of file cahn_hilliard.h.
previous_solutions
template<int dim> std::vector<GlobalVectorType> CahnHilliard< dim >::previous_solutions private
Definition at line 497 of file cahn_hilliard.h.
previous_solutions_transfer
template<int dim> std::vector<parallel::distributed::SolutionTransfer<dim, GlobalVectorType> > CahnHilliard< dim >::previous_solutions_transfer private
Definition at line 504 of file cahn_hilliard.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> CahnHilliard< dim >::simulation_control private
Definition at line 468 of file cahn_hilliard.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& CahnHilliard< dim >::simulation_parameters private
Definition at line 463 of file cahn_hilliard.h.
solution_transfer
template<int dim> std::shared_ptr< parallel::distributed::SolutionTransfer<dim, GlobalVectorType> > CahnHilliard< dim >::solution_transfer private
Definition at line 502 of file cahn_hilliard.h.
statistics_table
template<int dim> TableHandler CahnHilliard< dim >::statistics_table private
Definition at line 513 of file cahn_hilliard.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix CahnHilliard< dim >::system_matrix private
Definition at line 492 of file cahn_hilliard.h.
system_rhs
template<int dim> GlobalVectorType CahnHilliard< dim >::system_rhs private
Definition at line 489 of file cahn_hilliard.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > CahnHilliard< dim >::triangulation private
Definition at line 467 of file cahn_hilliard.h.
zero_constraints
template<int dim> AffineConstraints<double> CahnHilliard< dim >::zero_constraints private
Definition at line 491 of file cahn_hilliard.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/cahn_hilliard.h
/home/runner/work/lethe/lethe/source/solvers/cahn_hilliard.cc