Lethe Open-Source Library: LinearSolverStrategy< VectorType > Class Template Reference
LinearSolverStrategy< VectorType > Class Template Reference
#include <linear_solver_strategy.h>
Public Member Functions
LinearSolverStrategy (PhysicsSolver< VectorType > *physics_solver)
void solve () override
Public Member Functions inherited from PhysicsSolverStrategy< VectorType >
PhysicsSolverStrategy (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &params)
PhysicsSolverStrategy (PhysicsSolver< VectorType > *physics_solver)
virtual ~PhysicsSolverStrategy ()
unsigned int get_current_newton_iteration () const
Additional Inherited Members
Protected Attributes inherited from PhysicsSolverStrategy< VectorType >
PhysicsSolver< VectorType > * physics_solver
Parameters::NonLinearSolver params
unsigned int outer_iteration
Detailed Description
template<typename VectorType>
class LinearSolverStrategy< VectorType >
The linear solver strategy class is used to solve the physics as a linear problem.
Definition at line 13 of file linear_solver_strategy.h.
Constructor & Destructor Documentation
LinearSolverStrategy()
template<typename VectorType > LinearSolverStrategy< VectorType >::LinearSolverStrategy (PhysicsSolver< VectorType > * physics_solver)
Constructor for the linear solver strategy.
Parameters
[in] physics_solver A pointer to the physics solver to which the solving strategy is attached.
Definition at line 34 of file linear_solver_strategy.h.
Member Function Documentation
solve()
template<typename VectorType > void LinearSolverStrategy< VectorType >::solve () override virtual
Solve the linear system of equations.
Implements PhysicsSolverStrategy< VectorType >.
Definition at line 41 of file linear_solver_strategy.h.
References PhysicsSolver< VectorType >::assemble_system_matrix(), PhysicsSolver< VectorType >::assemble_system_rhs(), PhysicsSolver< VectorType >::setup_preconditioner(), and PhysicsSolver< VectorType >::solve_linear_system().
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/linear_solver_strategy.h