Lethe Open-Source Library: NewtonNonLinearSolverStrategy< VectorType > Class Template Reference
NewtonNonLinearSolverStrategy< VectorType > Class Template Reference
#include <newton_non_linear_solver_strategy.h>
Public Member Functions
NewtonNonLinearSolverStrategy (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &param)
void solve () override
Public Member Functions inherited from PhysicsSolverStrategy< VectorType >
PhysicsSolverStrategy (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &params)
PhysicsSolverStrategy (PhysicsSolver< VectorType > *physics_solver)
virtual ~PhysicsSolverStrategy ()
unsigned int get_current_newton_iteration () const
Additional Inherited Members
Protected Attributes inherited from PhysicsSolverStrategy< VectorType >
PhysicsSolver< VectorType > * physics_solver
Parameters::NonLinearSolver params
unsigned int outer_iteration
Detailed Description
template<typename VectorType>
class NewtonNonLinearSolverStrategy< VectorType >
Non-linear solver for non-linear systems of equations which uses a Newton method with \(\alpha\) relaxation to ensure that the residual is monotonically decreasing.
Definition at line 15 of file newton_non_linear_solver_strategy.h.
Constructor & Destructor Documentation
NewtonNonLinearSolverStrategy()
template<typename VectorType > NewtonNonLinearSolverStrategy< VectorType >::NewtonNonLinearSolverStrategy (PhysicsSolver< VectorType > * physics_solver, const Parameters::NonLinearSolver & param)
Constructor.
Parameters
[in] physics_solver A pointer to the physics solver to which the non-linear solver is attached.
[in] param Non-linear solver parameters as specified in the simulation parameter file.
Definition at line 41 of file newton_non_linear_solver_strategy.h.
Member Function Documentation
solve()
template<typename VectorType > void NewtonNonLinearSolverStrategy< VectorType >::solve () override virtual
Solve the non-linear system of equations.
Implements PhysicsSolverStrategy< VectorType >.
Definition at line 49 of file newton_non_linear_solver_strategy.h.
References PhysicsSolver< VectorType >::apply_constraints(), PhysicsSolver< VectorType >::assemble_system_matrix(), PhysicsSolver< VectorType >::assemble_system_rhs(), PhysicsSolver< VectorType >::get_current_residual(), PhysicsSolver< VectorType >::get_evaluation_point(), PhysicsSolver< VectorType >::get_local_evaluation_point(), PhysicsSolver< VectorType >::get_newton_update(), PhysicsSolver< VectorType >::get_present_solution(), PhysicsSolver< VectorType >::get_residual_rescale_metric(), PhysicsSolver< VectorType >::get_system_rhs(), PhysicsSolver< VectorType >::output_newton_update_norms(), PhysicsSolver< VectorType >::pcout, Parameters::quiet, PhysicsSolver< VectorType >::setup_preconditioner(), and PhysicsSolver< VectorType >::solve_linear_system().
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/newton_non_linear_solver_strategy.h