Lethe Open-Source Library: CahnHilliardScratchData< dim > Class Template Reference
CahnHilliardScratchData< dim > Class Template Reference
#include <cahn_hilliard_scratch_data.h>
Public Member Functions
CahnHilliardScratchData (const PhysicalPropertiesManager &properties_manager, const FESystem< dim > &fe_cahn_hilliard, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const FiniteElement< dim > &fe_fd, const Quadrature< dim - 1 > &face_quadrature)
CahnHilliardScratchData (const CahnHilliardScratchData< dim > &sd)
void allocate () override
template<typename VectorType >
void reinit (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const std::vector< VectorType > &previous_solutions, Function< dim > *source_function)
template<typename VectorType >
void reinit_velocity (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const Parameters::ALE< dim > &ale)
void calculate_physical_properties ()
Public Attributes
PhysicalPropertiesManager properties_manager
std::map< field, std::vector< double > > fields
dealii::types::material_id material_id
std::vector< double > density
std::vector< double > kinematic_viscosity
std::vector< double > surface_tension
std::vector< double > mobility_cahn_hilliard
std::vector< double > mobility_cahn_hilliard_gradient
FEValuesExtractors::Scalar phase_order
FEValuesExtractors::Scalar chemical_potential
FEValues< dim > fe_values_cahn_hilliard
unsigned int n_dofs
unsigned int n_q_points
double cell_size
std::vector< double > JxW
std::vector< Point< dim > > quadrature_points
std::vector< double > phase_order_values
std::vector< Tensor< 1, dim > > phase_order_gradients
std::vector< double > phase_order_laplacians
std::vector< std::vector< double > > previous_phase_order_values
std::vector< double > chemical_potential_values
std::vector< Tensor< 1, dim > > chemical_potential_gradients
std::vector< double > chemical_potential_laplacians
std::vector< std::vector< double > > previous_chemical_potential_values
std::vector< double > source_phase_order
std::vector< double > source_chemical_potential
std::vector< std::vector< double > > phi_phase
std::vector< std::vector< Tensor< 2, dim > > > hess_phi_phase
std::vector< std::vector< double > > laplacian_phi_phase
std::vector< std::vector< Tensor< 1, dim > > > grad_phi_phase
std::vector< std::vector< double > > phi_potential
std::vector< std::vector< Tensor< 2, dim > > > hess_phi_potential
std::vector< std::vector< double > > laplacian_phi_potential
std::vector< std::vector< Tensor< 1, dim > > > grad_phi_potential
FEValuesExtractors::Vector velocities
FEValues< dim > fe_values_fd
std::vector< Tensor< 1, dim > > velocity_values
std::vector< std::vector< Tensor< 1, dim > > > previous_velocity_values
std::vector< Tensor< 2, dim > > velocity_gradient_values
FEFaceValues< dim > fe_face_values_cahn_hilliard
std::vector< std::vector< double > > face_JxW
unsigned int n_faces
unsigned int n_faces_q_points
bool is_boundary_cell
std::vector< bool > is_boundary_face
std::vector< unsigned int > boundary_face_id
std::vector< std::vector< std::vector< Tensor< 1, dim > > > > grad_phi_face_phase
std::vector< std::vector< Tensor< 1, dim > > > face_phase_grad_values
std::vector< std::vector< Tensor< 1, dim > > > face_normal
Detailed Description
template<int dim>
class CahnHilliardScratchData< dim >
Class that stores the information required by the assembly procedure for the Cahn-Hilliard equations. Consequently, this class calculates the phase field parameter Phi (values, gradients, laplacians), the chemical potential eta (values, gradients, laplacians) and the shape function (values, gradients, laplacians) at all the Gauss points for all degrees of freedom and stores it into arrays. Additionally, the user can request that this class gathers additional fields for physics which are coupled to the Cahn-Hilliard equations, such as the velocity which is required. This class serves as a separation between the evaluation at the Gauss point of the variables of interest and their use in the assembly, which is carried out by the assembler functions. For more information on this design, the reader can consult deal.II step-9 "https://www.dealii.org/current/doxygen/deal.II/step_9.html". In this latter example, the scratch is a struct instead of a templated class because of the simplicity of step-9.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 52 of file cahn_hilliard_scratch_data.h.
Constructor & Destructor Documentation
CahnHilliardScratchData() [1/2]
template<int dim> CahnHilliardScratchData< dim >::CahnHilliardScratchData (const PhysicalPropertiesManager & properties_manager, const FESystem< dim > & fe_cahn_hilliard, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const FiniteElement< dim > & fe_fd, const Quadrature< dim - 1 > & face_quadrature) inline
Constructor. The constructor creates the fe_values that will be used to fill the member variables of the scratch. It also allocated the necessary memory for all member variables. However, it does not do any evaluation, since this needs to be done at the cell level.
Parameters
properties_manager The physical properties manager (see physical_properties_manager.h)
fe_cahn_hilliard The FESystem used to solve the Cahn-Hilliard equations
quadrature The quadrature to use for the assembly
mapping The mapping of the domain in which the Cahn-Hilliard equations are solved
fe_fd The FESystem used to solve the Fluid Dynamics equations
Definition at line 72 of file cahn_hilliard_scratch_data.h.
References CahnHilliardScratchData< dim >::allocate().
CahnHilliardScratchData() [2/2]
template<int dim> CahnHilliardScratchData< dim >::CahnHilliardScratchData (const CahnHilliardScratchData< dim > & sd) inline
Copy Constructor. Same as the main constructor. This constructor only uses the other scratch to build the FeValues, it does not copy the content of the other scratch into itself since, by definition of the WorkStream mechanism it is assumed that the content of the scratch will be reset on a cell basis.
Parameters
fe The FESystem used to solve the Navier-Stokes equations
quadrature The quadrature to use for the assembly
mapping The mapping of the domain in which the Navier-Stokes equations are solved
Definition at line 109 of file cahn_hilliard_scratch_data.h.
References CahnHilliardScratchData< dim >::allocate().
Member Function Documentation
allocate()
template<int dim> void CahnHilliardScratchData< dim >::allocate () override virtual
Allocates the memory for the scratch.
This function allocates the necessary memory for all members of the scratch
Implements PhysicsScratchDataBase.
Definition at line 9 of file cahn_hilliard_scratch_data.cc.
References maximum_number_of_previous_solutions(), phase_order_cahn_hilliard, and phase_order_cahn_hilliard_filtered.
calculate_physical_properties()
template<int dim> void CahnHilliardScratchData< dim >::calculate_physical_properties ()
Calculates the physical properties that may be required by the Cahn-Hilliard problem. Namely the surface tension and the Cahn-Hilliard mobility.
Definition at line 87 of file cahn_hilliard_scratch_data.cc.
References fluid_fluid, phase_order_cahn_hilliard, and set_field_vector().
reinit()
template<int dim> template<typename VectorType > void CahnHilliardScratchData< dim >::reinit (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const std::vector< VectorType > & previous_solutions, Function< dim > * source_function) inline
Reinitializes the content of the scratch.
Using the FeValues and the content of the solutions and previous solutions, fills all of the class member of the scratch.
Parameters
[in] cell The cell over which the assembly is being carried. This cell must be compatible with the fe which is used to fill the FeValues.
[in] current_solution The present value of the solution for [Phi,eta]
[in] previous_solutions The solutions at the previous time steps.
[in] source_function The function describing the source term in Cahn-Hilliard equations.
Definition at line 160 of file cahn_hilliard_scratch_data.h.
References CahnHilliardScratchData< dim >::boundary_face_id, CahnHilliardScratchData< dim >::cell_size, CahnHilliardScratchData< dim >::chemical_potential, CahnHilliardScratchData< dim >::chemical_potential_gradients, CahnHilliardScratchData< dim >::chemical_potential_laplacians, CahnHilliardScratchData< dim >::chemical_potential_values, compute_cell_measure_with_JxW(), CahnHilliardScratchData< dim >::face_JxW, CahnHilliardScratchData< dim >::face_normal, CahnHilliardScratchData< dim >::face_phase_grad_values, CahnHilliardScratchData< dim >::fe_face_values_cahn_hilliard, CahnHilliardScratchData< dim >::fe_values_cahn_hilliard, CahnHilliardScratchData< dim >::grad_phi_face_phase, CahnHilliardScratchData< dim >::grad_phi_phase, CahnHilliardScratchData< dim >::grad_phi_potential, CahnHilliardScratchData< dim >::hess_phi_phase, CahnHilliardScratchData< dim >::hess_phi_potential, CahnHilliardScratchData< dim >::is_boundary_cell, CahnHilliardScratchData< dim >::is_boundary_face, CahnHilliardScratchData< dim >::JxW, CahnHilliardScratchData< dim >::laplacian_phi_phase, CahnHilliardScratchData< dim >::laplacian_phi_potential, CahnHilliardScratchData< dim >::n_dofs, CahnHilliardScratchData< dim >::n_faces, CahnHilliardScratchData< dim >::n_faces_q_points, CahnHilliardScratchData< dim >::n_q_points, CahnHilliardScratchData< dim >::phase_order, CahnHilliardScratchData< dim >::phase_order_gradients, CahnHilliardScratchData< dim >::phase_order_laplacians, CahnHilliardScratchData< dim >::phase_order_values, CahnHilliardScratchData< dim >::phi_phase, CahnHilliardScratchData< dim >::phi_potential, CahnHilliardScratchData< dim >::previous_chemical_potential_values, CahnHilliardScratchData< dim >::previous_phase_order_values, CahnHilliardScratchData< dim >::quadrature_points, CahnHilliardScratchData< dim >::source_chemical_potential, and CahnHilliardScratchData< dim >::source_phase_order.
reinit_velocity()
template<int dim> template<typename VectorType > void CahnHilliardScratchData< dim >::reinit_velocity (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const Parameters::ALE< dim > & ale) inline
Definition at line 301 of file cahn_hilliard_scratch_data.h.
References Parameters::ALE< dim >::enabled(), CahnHilliardScratchData< dim >::fe_values_fd, CahnHilliardScratchData< dim >::n_q_points, CahnHilliardScratchData< dim >::quadrature_points, CahnHilliardScratchData< dim >::velocities, Parameters::ALE< dim >::velocity, and CahnHilliardScratchData< dim >::velocity_values.
Member Data Documentation
boundary_face_id
template<int dim> std::vector<unsigned int> CahnHilliardScratchData< dim >::boundary_face_id
Definition at line 410 of file cahn_hilliard_scratch_data.h.
cell_size
template<int dim> double CahnHilliardScratchData< dim >::cell_size
Definition at line 360 of file cahn_hilliard_scratch_data.h.
chemical_potential
template<int dim> FEValuesExtractors::Scalar CahnHilliardScratchData< dim >::chemical_potential
Definition at line 354 of file cahn_hilliard_scratch_data.h.
chemical_potential_gradients
template<int dim> std::vector<Tensor<1, dim> > CahnHilliardScratchData< dim >::chemical_potential_gradients
Definition at line 372 of file cahn_hilliard_scratch_data.h.
chemical_potential_laplacians
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::chemical_potential_laplacians
Definition at line 373 of file cahn_hilliard_scratch_data.h.
chemical_potential_values
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::chemical_potential_values
Definition at line 371 of file cahn_hilliard_scratch_data.h.
density
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::density
Definition at line 346 of file cahn_hilliard_scratch_data.h.
face_JxW
template<int dim> std::vector<std::vector<double> > CahnHilliardScratchData< dim >::face_JxW
Definition at line 402 of file cahn_hilliard_scratch_data.h.
face_normal
template<int dim> std::vector<std::vector<Tensor<1, dim> > > CahnHilliardScratchData< dim >::face_normal
Definition at line 417 of file cahn_hilliard_scratch_data.h.
face_phase_grad_values
template<int dim> std::vector<std::vector<Tensor<1, dim> > > CahnHilliardScratchData< dim >::face_phase_grad_values
Definition at line 415 of file cahn_hilliard_scratch_data.h.
fe_face_values_cahn_hilliard
template<int dim> FEFaceValues<dim> CahnHilliardScratchData< dim >::fe_face_values_cahn_hilliard
Definition at line 401 of file cahn_hilliard_scratch_data.h.
fe_values_cahn_hilliard
template<int dim> FEValues<dim> CahnHilliardScratchData< dim >::fe_values_cahn_hilliard
Definition at line 357 of file cahn_hilliard_scratch_data.h.
fe_values_fd
template<int dim> FEValues<dim> CahnHilliardScratchData< dim >::fe_values_fd
Definition at line 395 of file cahn_hilliard_scratch_data.h.
fields
template<int dim> std::map<field, std::vector<double> > CahnHilliardScratchData< dim >::fields
Definition at line 344 of file cahn_hilliard_scratch_data.h.
grad_phi_face_phase
template<int dim> std::vector<std::vector<std::vector<Tensor<1, dim> > > > CahnHilliardScratchData< dim >::grad_phi_face_phase
Definition at line 413 of file cahn_hilliard_scratch_data.h.
grad_phi_phase
template<int dim> std::vector<std::vector<Tensor<1, dim> > > CahnHilliardScratchData< dim >::grad_phi_phase
Definition at line 384 of file cahn_hilliard_scratch_data.h.
grad_phi_potential
template<int dim> std::vector<std::vector<Tensor<1, dim> > > CahnHilliardScratchData< dim >::grad_phi_potential
Definition at line 388 of file cahn_hilliard_scratch_data.h.
hess_phi_phase
template<int dim> std::vector<std::vector<Tensor<2, dim> > > CahnHilliardScratchData< dim >::hess_phi_phase
Definition at line 382 of file cahn_hilliard_scratch_data.h.
hess_phi_potential
template<int dim> std::vector<std::vector<Tensor<2, dim> > > CahnHilliardScratchData< dim >::hess_phi_potential
Definition at line 386 of file cahn_hilliard_scratch_data.h.
is_boundary_cell
template<int dim> bool CahnHilliardScratchData< dim >::is_boundary_cell
Definition at line 408 of file cahn_hilliard_scratch_data.h.
is_boundary_face
template<int dim> std::vector<bool> CahnHilliardScratchData< dim >::is_boundary_face
Definition at line 409 of file cahn_hilliard_scratch_data.h.
JxW
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::JxW
Definition at line 363 of file cahn_hilliard_scratch_data.h.
kinematic_viscosity
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::kinematic_viscosity
Definition at line 347 of file cahn_hilliard_scratch_data.h.
laplacian_phi_phase
template<int dim> std::vector<std::vector<double> > CahnHilliardScratchData< dim >::laplacian_phi_phase
Definition at line 383 of file cahn_hilliard_scratch_data.h.
laplacian_phi_potential
template<int dim> std::vector<std::vector<double> > CahnHilliardScratchData< dim >::laplacian_phi_potential
Definition at line 387 of file cahn_hilliard_scratch_data.h.
material_id
template<int dim> dealii::types::material_id CahnHilliardScratchData< dim >::material_id
Definition at line 345 of file cahn_hilliard_scratch_data.h.
mobility_cahn_hilliard
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::mobility_cahn_hilliard
Definition at line 349 of file cahn_hilliard_scratch_data.h.
mobility_cahn_hilliard_gradient
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::mobility_cahn_hilliard_gradient
Definition at line 350 of file cahn_hilliard_scratch_data.h.
n_dofs
template<int dim> unsigned int CahnHilliardScratchData< dim >::n_dofs
Definition at line 358 of file cahn_hilliard_scratch_data.h.
n_faces
template<int dim> unsigned int CahnHilliardScratchData< dim >::n_faces
Definition at line 404 of file cahn_hilliard_scratch_data.h.
n_faces_q_points
template<int dim> unsigned int CahnHilliardScratchData< dim >::n_faces_q_points
Definition at line 405 of file cahn_hilliard_scratch_data.h.
n_q_points
template<int dim> unsigned int CahnHilliardScratchData< dim >::n_q_points
Definition at line 359 of file cahn_hilliard_scratch_data.h.
phase_order
template<int dim> FEValuesExtractors::Scalar CahnHilliardScratchData< dim >::phase_order
Definition at line 353 of file cahn_hilliard_scratch_data.h.
phase_order_gradients
template<int dim> std::vector<Tensor<1, dim> > CahnHilliardScratchData< dim >::phase_order_gradients
Definition at line 368 of file cahn_hilliard_scratch_data.h.
phase_order_laplacians
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::phase_order_laplacians
Definition at line 369 of file cahn_hilliard_scratch_data.h.
phase_order_values
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::phase_order_values
Definition at line 367 of file cahn_hilliard_scratch_data.h.
phi_phase
template<int dim> std::vector<std::vector<double> > CahnHilliardScratchData< dim >::phi_phase
Definition at line 381 of file cahn_hilliard_scratch_data.h.
phi_potential
template<int dim> std::vector<std::vector<double> > CahnHilliardScratchData< dim >::phi_potential
Definition at line 385 of file cahn_hilliard_scratch_data.h.
previous_chemical_potential_values
template<int dim> std::vector<std::vector<double> > CahnHilliardScratchData< dim >::previous_chemical_potential_values
Definition at line 374 of file cahn_hilliard_scratch_data.h.
previous_phase_order_values
template<int dim> std::vector<std::vector<double> > CahnHilliardScratchData< dim >::previous_phase_order_values
Definition at line 370 of file cahn_hilliard_scratch_data.h.
previous_velocity_values
template<int dim> std::vector<std::vector<Tensor<1, dim> > > CahnHilliardScratchData< dim >::previous_velocity_values
Definition at line 397 of file cahn_hilliard_scratch_data.h.
properties_manager
template<int dim> PhysicalPropertiesManager CahnHilliardScratchData< dim >::properties_manager
Definition at line 343 of file cahn_hilliard_scratch_data.h.
quadrature_points
template<int dim> std::vector<Point<dim> > CahnHilliardScratchData< dim >::quadrature_points
Definition at line 364 of file cahn_hilliard_scratch_data.h.
source_chemical_potential
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::source_chemical_potential
Definition at line 378 of file cahn_hilliard_scratch_data.h.
source_phase_order
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::source_phase_order
Definition at line 377 of file cahn_hilliard_scratch_data.h.
surface_tension
template<int dim> std::vector<double> CahnHilliardScratchData< dim >::surface_tension
Definition at line 348 of file cahn_hilliard_scratch_data.h.
velocities
template<int dim> FEValuesExtractors::Vector CahnHilliardScratchData< dim >::velocities
Scratch component for the Navier-Stokes component
Definition at line 393 of file cahn_hilliard_scratch_data.h.
velocity_gradient_values
template<int dim> std::vector<Tensor<2, dim> > CahnHilliardScratchData< dim >::velocity_gradient_values
Definition at line 398 of file cahn_hilliard_scratch_data.h.
velocity_values
template<int dim> std::vector<Tensor<1, dim> > CahnHilliardScratchData< dim >::velocity_values
Definition at line 396 of file cahn_hilliard_scratch_data.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/cahn_hilliard_scratch_data.h
/home/runner/work/lethe/lethe/source/solvers/cahn_hilliard_scratch_data.cc