Lethe Open-Source Library: NewtonNonLinearSolver< VectorType > Class Template Reference
NewtonNonLinearSolver< VectorType > Class Template Reference
#include <newton_non_linear_solver.h>
Public Member Functions
NewtonNonLinearSolver (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &param)
void solve (const bool is_initial_step) override
Public Member Functions inherited from NonLinearSolver< VectorType >
NonLinearSolver (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &params)
virtual ~NonLinearSolver ()
unsigned int get_current_newton_iteration () const
Additional Inherited Members
Protected Attributes inherited from NonLinearSolver< VectorType >
PhysicsSolver< VectorType > * physics_solver
Parameters::NonLinearSolver params
unsigned int outer_iteration
Detailed Description
template<typename VectorType>
class NewtonNonLinearSolver< VectorType >
Non-linear solver for non-linear systems of equations which uses a Newton method with \(\alpha\) relaxation to ensure that the residual is monotonically decreasing.
Definition at line 15 of file newton_non_linear_solver.h.
Constructor & Destructor Documentation
NewtonNonLinearSolver()
template<typename VectorType > NewtonNonLinearSolver< VectorType >::NewtonNonLinearSolver (PhysicsSolver< VectorType > * physics_solver, const Parameters::NonLinearSolver & param)
Constructor.
Parameters
[in] physics_solver A pointer to the physics solver to which the non-linear solver is attached.
[in] param Non-linear solver parameters as specified in the simulation parameter file.
Definition at line 44 of file newton_non_linear_solver.h.
Member Function Documentation
solve()
template<typename VectorType > void NewtonNonLinearSolver< VectorType >::solve (const bool is_initial_step) override virtual
Solve the non-linear system of equations.
Parameters
[in] is_initial_step Boolean variable that controls which constraints are going to be applied to the equations depending on the time step.
Implements NonLinearSolver< VectorType >.
Definition at line 52 of file newton_non_linear_solver.h.
References PhysicsSolver< VectorType >::apply_constraints(), PhysicsSolver< VectorType >::assemble_system_matrix(), PhysicsSolver< VectorType >::assemble_system_rhs(), PhysicsSolver< VectorType >::get_current_residual(), PhysicsSolver< VectorType >::get_evaluation_point(), PhysicsSolver< VectorType >::get_local_evaluation_point(), PhysicsSolver< VectorType >::get_newton_update(), PhysicsSolver< VectorType >::get_present_solution(), PhysicsSolver< VectorType >::get_system_rhs(), PhysicsSolver< VectorType >::output_newton_update_norms(), PhysicsSolver< VectorType >::pcout, Parameters::quiet, PhysicsSolver< VectorType >::setup_preconditioner(), and PhysicsSolver< VectorType >::solve_linear_system().
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/newton_non_linear_solver.h