Lethe Open-Source Library: FluidDynamicsBlock< dim > Class Template Reference
FluidDynamicsBlock< dim > Class Template Reference
#include <fluid_dynamics_block.h>
Public Member Functions
FluidDynamicsBlock (SimulationParameters< dim > &nsparam)
~FluidDynamicsBlock ()
void solve ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void assemble_system_matrix () override
void assemble_system_rhs () override
void setup_preconditioner () override
virtual void update_multiphysics_time_average_solution () override
void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
void setup_assemblers ()
void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data)
void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data)
template<bool assemble_matrix, Parameters::SimulationControl::TimeSteppingMethod scheme>
void assembleGD ()
void assemble_L2_projection ()
virtual void setup_dofs_fd () override
virtual void set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false) override
void set_solution_vector (double value)
void solve_L2_system (bool initial_step, double relative_residual, double minimum_residual)
void solve_linear_system (const bool initial_step, const bool renewed_matrix) override
void solve_system_GMRES (const bool initial_step, const double relative_residual, const double minimum_residual, const bool renewed_matrix)
void setup_AMG ()
void setup_ILU ()
Private Attributes
TrilinosWrappers::BlockSparsityPattern sparsity_pattern
TrilinosWrappers::BlockSparseMatrix system_matrix
TrilinosWrappers::SparseMatrix pressure_mass_matrix
std::vector< types::global_dof_index > dofs_per_block
std::shared_ptr< TrilinosWrappers::PreconditionILU > velocity_ilu_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionAMG > velocity_amg_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionILU > pressure_ilu_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionAMG > pressure_amg_preconditioner
std::shared_ptr< BlockSchurPreconditioner< TrilinosWrappers::PreconditionILU > > system_ilu_preconditioner
std::shared_ptr< BlockSchurPreconditioner< TrilinosWrappers::PreconditionAMG > > system_amg_preconditioner
const double gamma = 1
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Protected Member Functions inherited from NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual GlobalBlockVectorType & get_evaluation_point () override
virtual GlobalBlockVectorType & get_local_evaluation_point () override
virtual GlobalBlockVectorType & get_newton_update () override
virtual GlobalBlockVectorType & get_present_solution () override
virtual GlobalBlockVectorType & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void setup_dofs ()
virtual void set_initial_condition (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void postprocess_fd (bool first_iteration)
virtual void update_solutions_for_multiphysics ()
virtual void update_solutions_for_fluid_dynamics ()
void postprocessing_forces (const GlobalBlockVectorType &evaluation_point)
void postprocessing_torques (const GlobalBlockVectorType &evaluation_point)
virtual void dynamic_flow_control ()
virtual void multi_stage_preresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method)
virtual void multi_stage_postresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method, double time_step)
virtual void update_multi_stage_solution (double time_step)
virtual void iterate ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
void transfer_solution (SolutionTransfer< dim, GlobalBlockVectorType > &solution_transfer, std::vector< SolutionTransfer< dim, GlobalBlockVectorType > > &previous_solutions_transfer)
virtual void read_checkpoint ()
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void reinit_mortar_operators ()
std::shared_ptr< Mapping< dim > > get_mapping ()
void rotate_rotor_mapping (const bool is_first)
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
virtual void write_checkpoint ()
void gather_output_results (const GlobalBlockVectorType &solution, std::vector< OutputStruct< dim, GlobalBlockVectorType > > &solution_output_structs)
void write_output_results (const GlobalBlockVectorType &solution)
virtual void output_field_hook (DataOut< dim > &)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
GlobalBlockVectorType init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes inherited from NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >
std::vector< IndexSet > locally_owned_dofs
std::vector< IndexSet > locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
GlobalBlockVectorType evaluation_point
GlobalBlockVectorType local_evaluation_point
GlobalBlockVectorType newton_update
GlobalBlockVectorType present_solution
GlobalBlockVectorType system_rhs
std::vector< GlobalBlockVectorType > previous_solutions
SDIRKVectors sdirk_vectors
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::shared_ptr< MortarManagerCircle< dim > > mortar_manager
std::shared_ptr< CouplingOperator< dim, double > > mortar_coupling_operator
std::shared_ptr< NavierStokesCouplingEvaluation< dim, double > > mortar_coupling_evaluator
std::shared_ptr< MappingQCache< dim > > mapping_cache
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, GlobalBlockVectorType, std::vector< IndexSet > > > average_velocities
GlobalBlockVectorType average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Detailed Description
template<int dim>
class FluidDynamicsBlock< dim >
A solver class for the Navier-Stokes equation using Grad-Div stabilization
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Author
Bruno Blais, 2019
Definition at line 62 of file fluid_dynamics_block.h.
Constructor & Destructor Documentation
FluidDynamicsBlock()
template<int dim> FluidDynamicsBlock< dim >::FluidDynamicsBlock (SimulationParameters< dim > & nsparam)
Definition at line 30 of file fluid_dynamics_block.cc.
~FluidDynamicsBlock()
template<int dim> FluidDynamicsBlock< dim >::~FluidDynamicsBlock ()
Definition at line 37 of file fluid_dynamics_block.cc.
Member Function Documentation
assemble_L2_projection()
template<int dim> void FluidDynamicsBlock< dim >::assemble_L2_projection () private
Definition at line 460 of file fluid_dynamics_block.cc.
References pressure.
assemble_local_system_matrix()
template<int dim> void FluidDynamicsBlock< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) private
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 244 of file fluid_dynamics_block.cc.
References NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, NavierStokesScratchData< dim >::enable_heat_transfer(), heat_transfer, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), and VOF.
assemble_local_system_rhs()
template<int dim> void FluidDynamicsBlock< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) private
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 377 of file fluid_dynamics_block.cc.
References NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, heat_transfer, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_heat_transfer(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), and VOF.
assemble_system_matrix()
template<int dim> void FluidDynamicsBlock< dim >::assemble_system_matrix () override private virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 186 of file fluid_dynamics_block.cc.
References FluidDynamicsBlock< dim >::assemble_local_system_matrix(), FluidDynamicsBlock< dim >::copy_local_matrix_to_global_matrix(), and VOF.
assemble_system_rhs()
template<int dim> void FluidDynamicsBlock< dim >::assemble_system_rhs () override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 317 of file fluid_dynamics_block.cc.
References FluidDynamicsBlock< dim >::assemble_local_system_rhs(), FluidDynamicsBlock< dim >::copy_local_rhs_to_global_rhs(), heat_transfer, and VOF.
assembleGD()
template<int dim> template<bool assemble_matrix, Parameters::SimulationControl::TimeSteppingMethod scheme> void FluidDynamicsBlock< dim >::assembleGD () private
copy_local_matrix_to_global_matrix()
template<int dim> void FluidDynamicsBlock< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > & copy_data) private
Copy local cell information to global matrix.
Definition at line 302 of file fluid_dynamics_block.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void FluidDynamicsBlock< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > & copy_data) private
Copy local cell rhs information to global rhs.
Definition at line 444 of file fluid_dynamics_block.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_rhs.
set_initial_condition_fd()
template<int dim> void FluidDynamicsBlock< dim >::set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart = false) override private virtual
Set the initial condition using a L2 or a viscous solver
Implements NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >.
Definition at line 734 of file fluid_dynamics_block.cc.
References Parameters::L2projection, Parameters::nodal, read_checkpoint(), PhysicsSolver< VectorType >::solve_non_linear_system(), Parameters::SimulationControl::steady, and Parameters::viscous.
set_solution_vector()
template<int dim> void FluidDynamicsBlock< dim >::set_solution_vector (double value) private
Definition at line 723 of file fluid_dynamics_block.cc.
setup_AMG()
template<int dim> void FluidDynamicsBlock< dim >::setup_AMG () private
Set-up AMG preconditioner
Definition at line 862 of file fluid_dynamics_block.cc.
References fluid_dynamics, and pressure.
setup_assemblers()
template<int dim> void FluidDynamicsBlock< dim >::setup_assemblers () private
sets up the vector of assembler functions
Definition at line 44 of file fluid_dynamics_block.cc.
References Parameters::Stabilization::grad_div, is_bdf(), Parameters::VelocitySource::phase_change, and Parameters::VelocitySource::srf.
setup_dofs_fd()
template<int dim> void FluidDynamicsBlock< dim >::setup_dofs_fd () override private virtual
Initialize the dofs for fluid dynamics.
Implements NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >.
Definition at line 545 of file fluid_dynamics_block.cc.
References fluid_dynamics, BoundaryConditions::function_weak, Parameters::MeshAdaptation::none, BoundaryConditions::partial_slip, and BoundaryConditions::pressure.
setup_ILU()
template<int dim> void FluidDynamicsBlock< dim >::setup_ILU () private
Set-up ILU preconditioner
Definition at line 819 of file fluid_dynamics_block.cc.
References fluid_dynamics.
setup_preconditioner()
template<int dim> void FluidDynamicsBlock< dim >::setup_preconditioner () override private virtual
Set up preconditioner. Not used for this solver but needed for other physics solvers.
Implements PhysicsSolver< VectorType >.
Definition at line 372 of file fluid_dynamics_block.cc.
solve()
template<int dim> void FluidDynamicsBlock< dim >::solve ()
Definition at line 1154 of file fluid_dynamics_block.cc.
References read_mesh_and_manifolds().
solve_L2_system()
template<int dim> void FluidDynamicsBlock< dim >::solve_L2_system (bool initial_step, double relative_residual, double minimum_residual) private
Solver for the L2 Projection linear system
Definition at line 1077 of file fluid_dynamics_block.cc.
References fluid_dynamics, and Parameters::quiet.
solve_linear_system()
template<int dim> void FluidDynamicsBlock< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix) override private virtual
Solver for the NS linear system of equations
Implements PhysicsSolver< VectorType >.
Definition at line 792 of file fluid_dynamics_block.cc.
References fluid_dynamics, and Parameters::LinearSolver::gmres.
solve_system_GMRES()
template<int dim> void FluidDynamicsBlock< dim >::solve_system_GMRES (const bool initial_step, const double relative_residual, const double minimum_residual, const bool renewed_matrix) private
GMRES solver with ILU preconditioning or AMG preconditioning
Definition at line 985 of file fluid_dynamics_block.cc.
References Parameters::LinearSolver::amg, fluid_dynamics, Parameters::LinearSolver::ilu, and Parameters::quiet.
update_multiphysics_time_average_solution()
template<int dim> void FluidDynamicsBlock< dim >::update_multiphysics_time_average_solution () override private virtual
Update the average velocity field solution in the multiphysics interface.
Implements NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >.
Definition at line 174 of file fluid_dynamics_block.cc.
References fluid_dynamics.
Member Data Documentation
dofs_per_block
template<int dim> std::vector<types::global_dof_index> FluidDynamicsBlock< dim >::dofs_per_block private
Definition at line 228 of file fluid_dynamics_block.h.
gamma
template<int dim> const double FluidDynamicsBlock< dim >::gamma = 1 private
Definition at line 245 of file fluid_dynamics_block.h.
pressure_amg_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionAMG> FluidDynamicsBlock< dim >::pressure_amg_preconditioner private
Definition at line 237 of file fluid_dynamics_block.h.
pressure_ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> FluidDynamicsBlock< dim >::pressure_ilu_preconditioner private
Definition at line 235 of file fluid_dynamics_block.h.
pressure_mass_matrix
template<int dim> TrilinosWrappers::SparseMatrix FluidDynamicsBlock< dim >::pressure_mass_matrix private
Definition at line 226 of file fluid_dynamics_block.h.
sparsity_pattern
template<int dim> TrilinosWrappers::BlockSparsityPattern FluidDynamicsBlock< dim >::sparsity_pattern private
Members
Definition at line 224 of file fluid_dynamics_block.h.
system_amg_preconditioner
template<int dim> std::shared_ptr<BlockSchurPreconditioner<TrilinosWrappers::PreconditionAMG> > FluidDynamicsBlock< dim >::system_amg_preconditioner private
Definition at line 243 of file fluid_dynamics_block.h.
system_ilu_preconditioner
template<int dim> std::shared_ptr<BlockSchurPreconditioner<TrilinosWrappers::PreconditionILU> > FluidDynamicsBlock< dim >::system_ilu_preconditioner private
Definition at line 240 of file fluid_dynamics_block.h.
system_matrix
template<int dim> TrilinosWrappers::BlockSparseMatrix FluidDynamicsBlock< dim >::system_matrix private
Definition at line 225 of file fluid_dynamics_block.h.
velocity_amg_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionAMG> FluidDynamicsBlock< dim >::velocity_amg_preconditioner private
Definition at line 233 of file fluid_dynamics_block.h.
velocity_ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> FluidDynamicsBlock< dim >::velocity_ilu_preconditioner private
Definition at line 231 of file fluid_dynamics_block.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/fluid_dynamics_block.h
/home/runner/work/lethe/lethe/source/solvers/fluid_dynamics_block.cc