Lethe Open-Source Library: Parameters::InitialConditions< dim > Class Template Reference
Parameters::InitialConditions< dim > Class Template Reference
#include <initial_conditions.h>
Public Member Functions
InitialConditions ()
void declare_parameters (ParameterHandler &prm)
void parse_parameters (ParameterHandler &prm)
Public Attributes
InitialConditionType type
Functions::ParsedFunction< dim > uvwp
double kinematic_viscosity
Functions::ParsedFunction< dim > temperature
Functions::ParsedFunction< dim > tracer
Functions::ParsedFunction< dim > VOF
bool enable_projection_step
double projection_step_diffusion_factor
Ramp ramp
Functions::ParsedFunction< dim > cahn_hilliard
std::string average_velocity_folder
std::string average_velocity_file_name
Detailed Description
template<int dim>
class Parameters::InitialConditions< dim >
Definition at line 77 of file initial_conditions.h.
Constructor & Destructor Documentation
InitialConditions()
template<int dim> Parameters::InitialConditions< dim >::InitialConditions () inline
Definition at line 80 of file initial_conditions.h.
Member Function Documentation
declare_parameters()
template<int dim> void Parameters::InitialConditions< dim >::declare_parameters (ParameterHandler & prm)
Definition at line 124 of file initial_conditions.h.
References cahn_hilliard, Parameters::VOF::declare_parameters(), Parameters::InitialConditions< dim >::declare_parameters(), Parameters::ramp, temperature, and tracer.
parse_parameters()
template<int dim> void Parameters::InitialConditions< dim >::parse_parameters (ParameterHandler & prm)
Definition at line 192 of file initial_conditions.h.
References cahn_hilliard, Parameters::VOF::parse_parameters(), Parameters::ramp, temperature, tracer, and DEM::type.
Member Data Documentation
average_velocity_file_name
template<int dim> std::string Parameters::InitialConditions< dim >::average_velocity_file_name
Definition at line 114 of file initial_conditions.h.
average_velocity_folder
template<int dim> std::string Parameters::InitialConditions< dim >::average_velocity_folder
Definition at line 113 of file initial_conditions.h.
cahn_hilliard
template<int dim> Functions::ParsedFunction<dim> Parameters::InitialConditions< dim >::cahn_hilliard
Initial value:
=
      Functions::ParsedFunction<dim>(2)
Definition at line 109 of file initial_conditions.h.
enable_projection_step
template<int dim> bool Parameters::InitialConditions< dim >::enable_projection_step
Definition at line 102 of file initial_conditions.h.
kinematic_viscosity
template<int dim> double Parameters::InitialConditions< dim >::kinematic_viscosity
Definition at line 90 of file initial_conditions.h.
projection_step_diffusion_factor
template<int dim> double Parameters::InitialConditions< dim >::projection_step_diffusion_factor
Definition at line 103 of file initial_conditions.h.
ramp
template<int dim> Ramp Parameters::InitialConditions< dim >::ramp
Definition at line 106 of file initial_conditions.h.
temperature
template<int dim> Functions::ParsedFunction<dim> Parameters::InitialConditions< dim >::temperature
Definition at line 93 of file initial_conditions.h.
tracer
template<int dim> Functions::ParsedFunction<dim> Parameters::InitialConditions< dim >::tracer
Definition at line 96 of file initial_conditions.h.
type
template<int dim> InitialConditionType Parameters::InitialConditions< dim >::type
Definition at line 84 of file initial_conditions.h.
uvwp
template<int dim> Functions::ParsedFunction<dim> Parameters::InitialConditions< dim >::uvwp
Definition at line 87 of file initial_conditions.h.
VOF
template<int dim> Functions::ParsedFunction<dim> Parameters::InitialConditions< dim >::VOF
Definition at line 99 of file initial_conditions.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/solvers/initial_conditions.h