Lethe Open-Source Library: VoidFractionBase< dim > Class Template Reference
VoidFractionBase< dim > Class Template Reference
#include <void_fraction.h>
Public Member Functions
VoidFractionBase (parallel::DistributedTriangulationBase< dim > *triangulation, std::shared_ptr< Parameters::VoidFractionParameters< dim > > input_parameters, const Parameters::LinearSolver &linear_solver_parameters, Particles::ParticleHandler< dim > *particle_handler, const unsigned int fe_degree, const bool simplex, const ConditionalOStream &pcout)
void setup_dofs () override
void setup_constraints (const BoundaryConditions::NSBoundaryConditions< dim > &boundary_conditions)
void calculate_void_fraction (const double time)
void solve () override
void percolate_void_fraction ()
void initialize_void_fraction (const double time)
Public Member Functions inherited from PhysicsLinearSubequationsSolver
PhysicsLinearSubequationsSolver (const ConditionalOStream &pcout)
virtual ~PhysicsLinearSubequationsSolver ()=default
Public Attributes
DoFHandler< dim > dof_handler
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > quadrature
std::vector< GlobalVectorType > previous_void_fraction
GlobalVectorType void_fraction_locally_relevant
std::shared_ptr< FiniteElement< dim > > fe
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
AffineConstraints< double > void_fraction_constraints
std::shared_ptr< Parameters::VoidFractionParameters< dim > > void_fraction_parameters
Private Member Functions
void calculate_void_fraction_function (const double time)
void calculate_void_fraction_particle_centered_method ()
void calculate_void_fraction_satellite_point_method ()
void calculate_void_fraction_quadrature_centered_method ()
virtual void solve_linear_system_and_update_solution () override
Tensor< 1, dim > get_periodic_offset_distance (unsigned int boundary_id) const
Private Attributes
parallel::DistributedTriangulationBase< dim > * triangulation
const Parameters::LinearSolver linear_solver_parameters
Particles::ParticleHandler< dim > * particle_handler
GlobalVectorType void_fraction_locally_owned
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
TrilinosWrappers::SparseMatrix system_matrix_void_fraction
GlobalVectorType system_rhs_void_fraction
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_cell
bool has_periodic_boundaries
Tensor< 1, dim > periodic_offset
unsigned int periodic_direction
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_periodic_cell
const double l2_smoothing_factor
Additional Inherited Members
Protected Attributes inherited from PhysicsLinearSubequationsSolver
const ConditionalOStream pcout
Detailed Description
template<int dim>
class VoidFractionBase< dim >
Void fraction calculator. This class manages the calculation of the void fraction which is used as an auxiliary field for the solvers that solve the Volume-Averaged Navier-Stokes equations. The present architecture of the class support all of the different void fraction calculation methods within a single class instead of building a class hierarchy. This is because there are only a few void fraction calculation strategies.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
Definition at line 98 of file void_fraction.h.
Constructor & Destructor Documentation
VoidFractionBase()
template<int dim> VoidFractionBase< dim >::VoidFractionBase (parallel::DistributedTriangulationBase< dim > * triangulation, std::shared_ptr< Parameters::VoidFractionParameters< dim > > input_parameters, const Parameters::LinearSolver & linear_solver_parameters, Particles::ParticleHandler< dim > * particle_handler, const unsigned int fe_degree, const bool simplex, const ConditionalOStream & pcout) inline
Constructor for the void fraction calculator.
Parameters
triangulation The triangulation on which the simulation is being done.
input_parameters The parameters for the void fraction calculation.
linear_solver_parameters The parameters for the linear solver. This is used to solve the L2 projection of the void fraction
particle_handler The particle handler used to manage the particles in the simulation. This object must be provided even if the particles are not used to establish the void fraction.
fe_degree The finite element degree used to interpolate the void fraction.
simplex A flag to indicate if the simulations are being done with simplex elements.
pcout The ConditionalOStream used to print the information.
Definition at line 112 of file void_fraction.h.
References VoidFractionBase< dim >::fe, Parameters::gauss, Parameters::gauss_lobatto, VoidFractionBase< dim >::mapping, VoidFractionBase< dim >::quadrature, and VoidFractionBase< dim >::void_fraction_parameters.
Member Function Documentation
calculate_void_fraction()
template<int dim> void VoidFractionBase< dim >::calculate_void_fraction (const double time)
Calculate the void fraction.
Parameters
[in] time Current time for which the void fraction is to be calculated.
Definition at line 155 of file void_fraction.cc.
References announce_string(), Parameters::function, Parameters::pcm, Parameters::qcm, and Parameters::spm.
calculate_void_fraction_function()
template<int dim> void VoidFractionBase< dim >::calculate_void_fraction_function (const double time) private
Calculate the void fraction using a function. This is a straightforward usage of VectorTools.
Parameters
[in] time Current time for which the void fraction is to be calculated.
Definition at line 188 of file void_fraction.cc.
calculate_void_fraction_particle_centered_method()
template<int dim> void VoidFractionBase< dim >::calculate_void_fraction_particle_centered_method () private
Calculate the void fraction using the particle centered method.
Definition at line 208 of file void_fraction.cc.
References DEM::CFDDEMProperties::dp.
calculate_void_fraction_quadrature_centered_method()
template<int dim> void VoidFractionBase< dim >::calculate_void_fraction_quadrature_centered_method () private
Calculate the void fraction using the Quadrature-Centered Method (QCM).
Definition at line 547 of file void_fraction.cc.
References DEM::CFDDEMProperties::dp, particle_circle_intersection_2d(), particle_sphere_intersection_3d(), and DEM::CFDDEMProperties::volumetric_contribution.
calculate_void_fraction_satellite_point_method()
template<int dim> void VoidFractionBase< dim >::calculate_void_fraction_satellite_point_method () private
Calculate the void fraction using the satellite point method.
Definition at line 307 of file void_fraction.cc.
References DEM::CFDDEMProperties::dp.
get_periodic_offset_distance()
template<int dim> Tensor< 1, dim > VoidFractionBase< dim >::get_periodic_offset_distance (unsigned int boundary_id) const inline private
Calculate and return the periodic offset distance vector of the domain which is needed for the periodic boundary conditions using the QCM or SPM for void fraction with the GLS VANS/CFD-DEM solver. The distance is based on one of the periodic boundaries. This periodic boundary is then used as the reference for all particle locations shifted by this offset vector.
Parameters
[in] boundary_id The ID of one of the periodic boundaries
Returns
The periodic offset vector.
Definition at line 315 of file void_fraction.h.
References VoidFractionBase< dim >::triangulation.
initialize_void_fraction()
template<int dim> void VoidFractionBase< dim >::initialize_void_fraction (const double time) inline
Initialize the void fraction at the beginning of a simulation.
Parameters
[in] time The current time. This is used for time-dependent functions.
Definition at line 224 of file void_fraction.h.
References VoidFractionBase< dim >::calculate_void_fraction(), VoidFractionBase< dim >::previous_void_fraction, and VoidFractionBase< dim >::void_fraction_locally_relevant.
percolate_void_fraction()
template<int dim> void VoidFractionBase< dim >::percolate_void_fraction () inline
Percolate the time vector for the void fraction. This operation is called at the end of a time-step.
Definition at line 207 of file void_fraction.h.
References VoidFractionBase< dim >::previous_void_fraction, and VoidFractionBase< dim >::void_fraction_locally_relevant.
setup_constraints()
template<int dim> void VoidFractionBase< dim >::setup_constraints (const BoundaryConditions::NSBoundaryConditions< dim > & boundary_conditions)
Establish the constraints of the void fraction systems.
Parameters
[in] boundary_conditions The boundary conditions of fluid dynamics. This is used to establish periodic boundary conditions for the void fraction.
Definition at line 90 of file void_fraction.cc.
References BoundaryConditions::periodic, BoundaryConditions::BoundaryConditions::periodic_direction, BoundaryConditions::BoundaryConditions::periodic_neighbor_id, Parameters::qcm, Parameters::spm, BoundaryConditions::BoundaryConditions::type, and LetheGridTools::vertices_cell_mapping_with_periodic_boundaries().
setup_dofs()
template<int dim> void VoidFractionBase< dim >::setup_dofs () override virtual
Setup the degrees of freedom.
Implements PhysicsSubequationsSolverBase.
Definition at line 25 of file void_fraction.cc.
References maximum_number_of_previous_solutions(), and LetheGridTools::vertices_cell_mapping().
solve()
template<int dim> void VoidFractionBase< dim >::solve () inline override virtual
Assemble and solve the system.
Implements PhysicsSubequationsSolverBase.
Definition at line 198 of file void_fraction.h.
solve_linear_system_and_update_solution()
template<int dim> void VoidFractionBase< dim >::solve_linear_system_and_update_solution () override private virtual
Solve the linear system resulting from the assemblies.
Implements PhysicsLinearSubequationsSolver.
Definition at line 1105 of file void_fraction.cc.
References Parameters::quiet.
Member Data Documentation
dof_handler
template<int dim> DoFHandler<dim> VoidFractionBase< dim >::dof_handler
DoFHandler that manages the void fraction.
Definition at line 232 of file void_fraction.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > VoidFractionBase< dim >::fe
Finite element for the void fraction.
Definition at line 248 of file void_fraction.h.
has_periodic_boundaries
template<int dim> bool VoidFractionBase< dim >::has_periodic_boundaries private
Boolean to indicate if the mesh has periodic boundaries.
Definition at line 402 of file void_fraction.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> VoidFractionBase< dim >::ilu_preconditioner private
Preconditioner used for the solution of the smoothed L2 projection of the void fraction
Definition at line 385 of file void_fraction.h.
l2_smoothing_factor
template<int dim> const double VoidFractionBase< dim >::l2_smoothing_factor private
Initial value:
=
    Utilities::fixed_power<2>(void_fraction_parameters->l2_smoothing_length)
Definition at line 417 of file void_fraction.h.
linear_solver_parameters
template<int dim> const Parameters::LinearSolver VoidFractionBase< dim >::linear_solver_parameters private
Linear solvers for the calculation of the void fraction.
Definition at line 375 of file void_fraction.h.
locally_owned_dofs
template<int dim> IndexSet VoidFractionBase< dim >::locally_owned_dofs
Index set for the locally owned degree of freedoms.
Definition at line 251 of file void_fraction.h.
locally_relevant_dofs
template<int dim> IndexSet VoidFractionBase< dim >::locally_relevant_dofs
Index set for the locally relevant degree of freedoms.
Definition at line 254 of file void_fraction.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > VoidFractionBase< dim >::mapping
Mapping for the void fraction.
Definition at line 235 of file void_fraction.h.
particle_handler
template<int dim> Particles::ParticleHandler<dim>* VoidFractionBase< dim >::particle_handler private
Particle handler used when the void fraction depends on particles.
Definition at line 378 of file void_fraction.h.
periodic_direction
template<int dim> unsigned int VoidFractionBase< dim >::periodic_direction private
Direction associated with the periodic boundary condition.
Definition at line 408 of file void_fraction.h.
periodic_offset
template<int dim> Tensor<1, dim> VoidFractionBase< dim >::periodic_offset private
Offset for the periodic boundary condition.
Definition at line 405 of file void_fraction.h.
previous_void_fraction
template<int dim> std::vector<GlobalVectorType> VoidFractionBase< dim >::previous_void_fraction
The solutions are made public instead of using getters Solution of the void fraction at previous time steps
Definition at line 242 of file void_fraction.h.
quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > VoidFractionBase< dim >::quadrature
Quadrature for the void fraction.
Definition at line 238 of file void_fraction.h.
system_matrix_void_fraction
template<int dim> TrilinosWrappers::SparseMatrix VoidFractionBase< dim >::system_matrix_void_fraction private
System matrix used to assemble the smoothed L2 projection of the void fraction
Definition at line 389 of file void_fraction.h.
system_rhs_void_fraction
template<int dim> GlobalVectorType VoidFractionBase< dim >::system_rhs_void_fraction private
Right-hand side used to assemble the smoothed L2 projection of the void fraction
Definition at line 393 of file void_fraction.h.
triangulation
template<int dim> parallel::DistributedTriangulationBase<dim>* VoidFractionBase< dim >::triangulation private
Triangulation.
Definition at line 362 of file void_fraction.h.
vertices_to_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > VoidFractionBase< dim >::vertices_to_cell private
Vertices to cell map, this is used in the QCM and the satellite point method to access the neighboring cells of a cell.
Definition at line 399 of file void_fraction.h.
vertices_to_periodic_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > VoidFractionBase< dim >::vertices_to_periodic_cell private
Vertices to periodic cell map, this is used in the QCM and the satellite point method to access the neighboring cells of a cell.
Definition at line 414 of file void_fraction.h.
void_fraction_constraints
template<int dim> AffineConstraints<double> VoidFractionBase< dim >::void_fraction_constraints
Constraints used for the boundary conditions of the void fraction. Currently, this is only used to establish periodic void fractions. This object has to be made public because the boundary conditions are set outside of the object for now.
Definition at line 260 of file void_fraction.h.
void_fraction_locally_owned
template<int dim> GlobalVectorType VoidFractionBase< dim >::void_fraction_locally_owned private
Locally owned solution of the void fraction.
Definition at line 381 of file void_fraction.h.
void_fraction_locally_relevant
template<int dim> GlobalVectorType VoidFractionBase< dim >::void_fraction_locally_relevant
Fully distributed (including locally relevant) solution.
Definition at line 245 of file void_fraction.h.
void_fraction_parameters
template<int dim> std::shared_ptr<Parameters::VoidFractionParameters<dim> > VoidFractionBase< dim >::void_fraction_parameters
TODO: To move to private Parameters for the calculation of the void fraction Right now this is used for the VANS matrix-free solver to directly calculate the void fraction from the function itself. The function will be removed back to private in a future PR.
Definition at line 371 of file void_fraction.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/void_fraction.h
/home/runner/work/lethe/lethe/source/fem-dem/void_fraction.cc