Lethe Open-Source Library: PhysicsSolver< VectorType > Class Template Reference
PhysicsSolver< VectorType > Class Template Reference abstract
#include <physics_solver.h>
Public Member Functions
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
virtual void assemble_system_matrix ()=0
virtual void assemble_system_rhs ()=0
virtual void setup_preconditioner ()=0
virtual void solve_linear_system (const bool initial_step, const bool renewed_matrix=true)=0
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual VectorType & get_evaluation_point ()=0
virtual VectorType & get_local_evaluation_point ()=0
virtual VectorType & get_newton_update ()=0
virtual VectorType & get_present_solution ()=0
virtual VectorType & get_system_rhs ()=0
virtual AffineConstraints< double > & get_nonzero_constraints ()=0
virtual void output_newton_update_norms (const unsigned int display_precision)=0
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Public Attributes
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Private Attributes
NonLinearSolver< VectorType > * non_linear_solver
Detailed Description
template<typename VectorType>
class PhysicsSolver< VectorType >
Contain all the common elements of a physics solver. It creates the non-linear solver as specified by the user using the parameters file and provides all the necessary elements needed by the solver to solve a physics problem.
Parameters
[in] non_linear_solver_parameters Set of parameters that will be used to construct the non-linear solver.
Definition at line 26 of file physics_solver.h.
Constructor & Destructor Documentation
PhysicsSolver()
template<typename VectorType > PhysicsSolver< VectorType >::PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
Definition at line 143 of file physics_solver.h.
References Parameters::NonLinearSolver::inexact_newton, Parameters::NonLinearSolver::kinsol_newton, Parameters::NonLinearSolver::newton, PhysicsSolver< VectorType >::non_linear_solver, and Parameters::NonLinearSolver::solver.
~PhysicsSolver()
template<typename VectorType > virtual PhysicsSolver< VectorType >::~PhysicsSolver () inline virtual
Definition at line 31 of file physics_solver.h.
References PhysicsSolver< VectorType >::non_linear_solver.
Member Function Documentation
apply_constraints()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::apply_constraints () inline virtual
Applies constraints to a local_evaluation_point.
Definition at line 81 of file physics_solver.h.
References PhysicsSolver< VectorType >::get_local_evaluation_point(), and PhysicsSolver< VectorType >::get_nonzero_constraints().
assemble_system_matrix()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::assemble_system_matrix () pure virtual
Assemble the matrix.
Implemented in FluidDynamicsSharp< dim >, FluidDynamicsVANS< dim >, CahnHilliard< dim >, FluidDynamicsBlock< dim >, FluidDynamicsMatrixBased< dim >, FluidDynamicsMatrixFree< dim >, FluidDynamicsNitsche< dim, spacedim >, HeatTransfer< dim >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
assemble_system_rhs()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::assemble_system_rhs () pure virtual
Assemble the right-hand side (rhs).
Implemented in FluidDynamicsSharp< dim >, FluidDynamicsVANS< dim >, CahnHilliard< dim >, FluidDynamicsBlock< dim >, FluidDynamicsMatrixBased< dim >, FluidDynamicsMatrixFree< dim >, FluidDynamicsNitsche< dim, spacedim >, HeatTransfer< dim >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
get_current_newton_iteration()
template<typename VectorType > unsigned int PhysicsSolver< VectorType >::get_current_newton_iteration () const inline
Return the current newton iteration of this physics solver.
Definition at line 130 of file physics_solver.h.
References PhysicsSolver< VectorType >::non_linear_solver.
get_current_residual()
template<typename VectorType > virtual double PhysicsSolver< VectorType >::get_current_residual () inline virtual
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Reimplemented in FluidDynamicsSharp< dim >.
Definition at line 120 of file physics_solver.h.
References PhysicsSolver< VectorType >::get_system_rhs().
get_evaluation_point()
template<typename VectorType > virtual VectorType & PhysicsSolver< VectorType >::get_evaluation_point () pure virtual
Getter methods that give access to the private attributes of the physics being solved. These methods must be provided by the physics as they are the key to solve a problem using Lethe.
Implemented in CahnHilliard< dim >, HeatTransfer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >, NavierStokesBase< dim, GlobalVectorType, IndexSet >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
get_local_evaluation_point()
template<typename VectorType > virtual VectorType & PhysicsSolver< VectorType >::get_local_evaluation_point () pure virtual
Implemented in CahnHilliard< dim >, HeatTransfer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >, NavierStokesBase< dim, GlobalVectorType, IndexSet >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
get_newton_update()
template<typename VectorType > virtual VectorType & PhysicsSolver< VectorType >::get_newton_update () pure virtual
Implemented in CahnHilliard< dim >, HeatTransfer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >, NavierStokesBase< dim, GlobalVectorType, IndexSet >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
get_nonzero_constraints()
template<typename VectorType > virtual AffineConstraints< double > & PhysicsSolver< VectorType >::get_nonzero_constraints () pure virtual
Implemented in CahnHilliard< dim >, HeatTransfer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >, NavierStokesBase< dim, GlobalVectorType, IndexSet >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
get_present_solution()
template<typename VectorType > virtual VectorType & PhysicsSolver< VectorType >::get_present_solution () pure virtual
Implemented in CahnHilliard< dim >, HeatTransfer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >, NavierStokesBase< dim, GlobalVectorType, IndexSet >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
get_system_rhs()
template<typename VectorType > virtual VectorType & PhysicsSolver< VectorType >::get_system_rhs () pure virtual
Implemented in CahnHilliard< dim >, HeatTransfer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >, NavierStokesBase< dim, GlobalVectorType, IndexSet >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
output_newton_update_norms()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::output_newton_update_norms (const unsigned int display_precision) pure virtual
Output the L2 and Linfty norms of the correction vector.
Parameters
[in] display_precision Number of outputted digits.
Implemented in CahnHilliard< dim >, HeatTransfer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, GlobalBlockVectorType, std::vector< IndexSet > >, NavierStokesBase< dim, GlobalVectorType, IndexSet >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
setup_preconditioner()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::setup_preconditioner () pure virtual
Set up the preconditioner.
Implemented in AuxiliaryPhysics< dim, VectorType >, AuxiliaryPhysics< dim, GlobalVectorType >, FluidDynamicsBlock< dim >, FluidDynamicsMatrixBased< dim >, FluidDynamicsMatrixFree< dim >, PhysicsNonlinearSubequationsSolver< dim, VectorType >, and PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >.
solve_linear_system()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) pure virtual
Solve the linear system of equations.
Parameters
[in] initial_step Provides the linear solver with indication if this solution is the first one for the system of equation or not.
[in] renewed_matrix Indicates to the linear solve if the system matrix has been recalculated or not.
Implemented in FluidDynamicsBlock< dim >, CahnHilliard< dim >, FluidDynamicsMatrixBased< dim >, FluidDynamicsMatrixFree< dim >, HeatTransfer< dim >, Tracer< dim >, VolumeOfFluid< dim >, and VOFAlgebraicInterfaceReinitialization< dim >.
solve_non_linear_system()
template<typename VectorType > void PhysicsSolver< VectorType >::solve_non_linear_system (const bool first_iteration)
Solve the non linear system of equations.
Parameters
[in] first_iteration Indicates whether it is the first iteration of the non-linear solver or not.
Definition at line 169 of file physics_solver.h.
Member Data Documentation
non_linear_solver
template<typename VectorType > NonLinearSolver<VectorType>* PhysicsSolver< VectorType >::non_linear_solver private
Definition at line 139 of file physics_solver.h.
pcout
template<typename VectorType > ConditionalOStream PhysicsSolver< VectorType >::pcout
Definition at line 135 of file physics_solver.h.
time_stepping_method
template<typename VectorType > Parameters::SimulationControl::TimeSteppingMethod PhysicsSolver< VectorType >::time_stepping_method
Definition at line 136 of file physics_solver.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/non_linear_solver.h
/home/runner/work/lethe/lethe/include/core/physics_solver.h