Lethe Open-Source Library: ParticleWallLinearForce< dim, PropertiesIndex > Class Template Reference
ParticleWallLinearForce< dim, PropertiesIndex > Class Template Reference
#include <particle_wall_linear_force.h>
Public Member Functions
ParticleWallLinearForce (const DEMSolverParameters< dim > &dem_parameters, const std::vector< types::boundary_id > &boundary_index={})
virtual void calculate_particle_wall_contact_force (typename DEM::dem_data_structures< dim >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double dt, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force) override
virtual void calculate_particle_floating_wall_contact_force (typename DEM::dem_data_structures< dim >::particle_floating_mesh_in_contact &particle_floating_mesh_in_contact, const double dt, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force, const std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > &solids) override
Public Member Functions inherited from ParticleWallContactForce< dim, PropertiesIndex >
ParticleWallContactForce (const DEMSolverParameters< dim > &dem_parameters)
virtual ~ParticleWallContactForce ()
std::map< types::boundary_id, Tensor< 1, 3 > > get_force ()
std::map< types::boundary_id, Tensor< 1, 3 > > get_torque ()
Tensor< 1, 3 > find_projection (const Tensor< 1, 3 > &vector_a, const Tensor< 1, 3 > &vector_b)
Private Types
using FuncPtrType = Tensor< 1, 3 >(ParticleWallLinearForce< dim, PropertiesIndex >::*)(const ArrayView< const double > &, const double, const double, const double, const double, const double, const Tensor< 1, 3 > &, Tensor< 1, 3 > &)
Private Member Functions
Tensor< 1, 3 > no_resistance (const ArrayView< const double > &, const double, const double, const double, const double, const double, const Tensor< 1, 3 > &, Tensor< 1, 3 > &)
Tensor< 1, 3 > constant_resistance (const ArrayView< const double > &particle_properties, const double effective_rolling_friction_coefficient, const double, const double normal_force_norm, const double, const double, const Tensor< 1, 3 > &, Tensor< 1, 3 > &)
Tensor< 1, 3 > viscous_resistance (const ArrayView< const double > &particle_properties, const double effective_rolling_friction_coefficient, const double, const double normal_force_norm, const double, const double, const Tensor< 1, 3 > &normal_unit_vector, Tensor< 1, 3 > &)
Tensor< 1, 3 > epsd_resistance (const ArrayView< const double > &particle_properties, const double effective_rolling_friction_coefficient, const double effective_rolling_viscous_damping_coefficient, const double normal_force_norm, const double dt, const double normal_spring_constant, const Tensor< 1, 3 > &normal_unit_vector, Tensor< 1, 3 > &cumulative_rolling_resistance_spring_torque)
std::tuple< Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 > > calculate_linear_contact_force_and_torque (const double dt, particle_wall_contact_info< dim > &contact_info, const ArrayView< const double > &particle_properties)
Private Attributes
FuncPtrType calculate_rolling_resistance_torque
const double f_coefficient_epsd
Additional Inherited Members
Protected Member Functions inherited from ParticleWallContactForce< dim, PropertiesIndex >
void update_contact_information (particle_wall_contact_info< dim > &contact_pair_information, const Point< 3 > &particle_position, const ArrayView< const double > &particle_properties, const double dt)
void update_particle_floating_wall_contact_information (particle_wall_contact_info< dim > &contact_pair_information, const ArrayView< const double > &particle_properties, const double dt, const Tensor< 1, 3 > &cut_cell_translational_velocity, const Tensor< 1, 3 > &cut_cell_rotational_velocity, const double center_of_rotation_particle_distance)
void apply_force_and_torque (const std::tuple< Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 > > &forces_and_torques, Tensor< 1, 3 > &particle_torque, Tensor< 1, 3 > &particle_force, const Point< 3 > &point_on_boundary, int boundary_id=0)
void calculate_force_and_torque_on_boundary (const unsigned int boundary_id, Tensor< 1, 3 > add_force, const Point< 3 > point_contact)
std::map< unsigned int, Tensor< 1, 3 > > initialize ()
void mpi_correction_over_calculation_of_forces_and_torques ()
Protected Attributes inherited from ParticleWallContactForce< dim, PropertiesIndex >
double effective_radius
std::unordered_map< unsigned int, Tensor< 1, 3 > > boundary_translational_velocity_map
std::unordered_map< unsigned int, double > boundary_rotational_speed_map
std::unordered_map< unsigned int, Tensor< 1, 3 > > boundary_rotational_vector
std::unordered_map< unsigned int, Point< 3 > > point_on_rotation_vector
unsigned int n_particle_types
std::vector< double > effective_youngs_modulus
std::vector< double > effective_shear_modulus
std::vector< double > effective_coefficient_of_restitution
std::vector< double > effective_coefficient_of_friction
std::vector< double > effective_coefficient_of_rolling_friction
std::vector< double > effective_coefficient_of_rolling_viscous_damping
std::vector< double > effective_surface_energy
std::vector< double > effective_hamaker_constant
std::vector< double > model_parameter_beta
std::map< unsigned int, Tensor< 1, 3 > > force_on_walls
std::map< unsigned int, Tensor< 1, 3 > > torque_on_walls
bool calculate_force_torque_on_boundary
Point< 3 > center_mass_container
std::vector< types::boundary_id > boundary_index
const unsigned int vertices_per_triangle = 3
Detailed Description
template<int dim, typename PropertiesIndex>
class ParticleWallLinearForce< dim, PropertiesIndex >
Calculate particle-wall contact force using the information obtained from the fine search and physical properties of particles and walls.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Definition at line 24 of file particle_wall_linear_force.h.
Member Typedef Documentation
FuncPtrType
template<int dim, typename PropertiesIndex > using ParticleWallLinearForce< dim, PropertiesIndex >::FuncPtrType = Tensor<1, 3> (ParticleWallLinearForce<dim, PropertiesIndex>::*)(const ArrayView<const double> &, const double, const double, const double, const double, const double, const Tensor<1, 3> &, Tensor<1, 3> &) private
Definition at line 27 of file particle_wall_linear_force.h.
Constructor & Destructor Documentation
ParticleWallLinearForce()
template<int dim, typename PropertiesIndex > ParticleWallLinearForce< dim, PropertiesIndex >::ParticleWallLinearForce (const DEMSolverParameters< dim > & dem_parameters, const std::vector< types::boundary_id > & boundary_index = {})
Definition at line 11 of file particle_wall_linear_force.cc.
References ParticleWallContactForce< dim, PropertiesIndex >::boundary_index, ParticleWallContactForce< dim, PropertiesIndex >::calculate_force_torque_on_boundary, ParticleWallLinearForce< dim, PropertiesIndex >::calculate_rolling_resistance_torque, ParticleWallContactForce< dim, PropertiesIndex >::center_mass_container, Parameters::Lagrangian::constant_resistance, ParticleWallContactForce< dim, PropertiesIndex >::effective_coefficient_of_friction, ParticleWallContactForce< dim, PropertiesIndex >::effective_coefficient_of_restitution, ParticleWallContactForce< dim, PropertiesIndex >::effective_coefficient_of_rolling_friction, ParticleWallContactForce< dim, PropertiesIndex >::effective_coefficient_of_rolling_viscous_damping, ParticleWallContactForce< dim, PropertiesIndex >::effective_youngs_modulus, Parameters::Lagrangian::epsd_resistance, ParticleWallContactForce< dim, PropertiesIndex >::force_on_walls, DEMSolverParameters< dim >::forces_torques, Parameters::Lagrangian::LagrangianPhysicalProperties::friction_coefficient_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::friction_coefficient_wall, ParticleWallContactForce< dim, PropertiesIndex >::initialize(), DEMSolverParameters< dim >::lagrangian_physical_properties, ParticleWallContactForce< dim, PropertiesIndex >::model_parameter_beta, DEMSolverParameters< dim >::model_parameters, Parameters::Lagrangian::no_resistance, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number, Parameters::Lagrangian::LagrangianPhysicalProperties::poisson_ratio_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::poisson_ratio_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::restitution_coefficient_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::restitution_coefficient_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_friction_coefficient_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_friction_wall, Parameters::Lagrangian::ModelParameters::rolling_resistance_method, Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_viscous_damping_coefficient_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_viscous_damping_wall, ParticleWallContactForce< dim, PropertiesIndex >::torque_on_walls, Parameters::Lagrangian::viscous_resistance, Parameters::Lagrangian::LagrangianPhysicalProperties::youngs_modulus_particle, and Parameters::Lagrangian::LagrangianPhysicalProperties::youngs_modulus_wall.
Member Function Documentation
calculate_linear_contact_force_and_torque()
template<int dim, typename PropertiesIndex > std::tuple< Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 > > ParticleWallLinearForce< dim, PropertiesIndex >::calculate_linear_contact_force_and_torque (const double dt, particle_wall_contact_info< dim > & contact_info, const ArrayView< const double > & particle_properties) private
Calculate the particle-particle linear contact force and torques based on the updated values in contact_info.
Parameters
[in] dt DEM time step.
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact
[in] particle_properties Properties of particle one in contact
Returns
A tuple which contains: 1, normal force, 2, tangential force, 3, tangential torque and 4, rolling resistance torque of a contact pair
Definition at line 397 of file particle_wall_linear_force.cc.
References particle_wall_contact_info< dim >::normal_overlap, particle_wall_contact_info< dim >::normal_relative_velocity, particle_wall_contact_info< dim >::normal_vector, particle_wall_contact_info< dim >::rolling_resistance_spring_torque, particle_wall_contact_info< dim >::tangential_overlap, and particle_wall_contact_info< dim >::tangential_relative_velocity.
calculate_particle_floating_wall_contact_force()
template<int dim, typename PropertiesIndex > void ParticleWallLinearForce< dim, PropertiesIndex >::calculate_particle_floating_wall_contact_force (typename DEM::dem_data_structures< dim >::particle_floating_mesh_in_contact & particle_floating_mesh_in_contact, const double dt, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force, const std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > & solids) override virtual
Calculate particle-floating mesh contact force using linear (Hooekan) model.
Parameters
particle_floating_mesh_in_contact A container that stores the information of particle-floating mesh contact
dt DEM time step
torque Torque acting on particles
force Force acting on particles
solids Floating solids
Implements ParticleWallContactForce< dim, PropertiesIndex >.
Definition at line 234 of file particle_wall_linear_force.cc.
References point_nd_to_3d().
calculate_particle_wall_contact_force()
template<int dim, typename PropertiesIndex > void ParticleWallLinearForce< dim, PropertiesIndex >::calculate_particle_wall_contact_force (typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double dt, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force) override virtual
Calculate the particle-wall contact force using linear (Hookean) model.
Parameters
particle_wall_pairs_in_contact Required information for calculation of the particle-wall contact force. This information was obtained in the fine search
dt DEM time step
torque Torque acting on particle
force Force acting on particles
Implements ParticleWallContactForce< dim, PropertiesIndex >.
Definition at line 132 of file particle_wall_linear_force.cc.
References ParticleWallContactForce< dim, PropertiesIndex >::initialize(), and point_nd_to_3d().
constant_resistance()
template<int dim, typename PropertiesIndex > Tensor< 1, 3 > ParticleWallLinearForce< dim, PropertiesIndex >::constant_resistance (const ArrayView< const double > & particle_properties, const double effective_rolling_friction_coefficient, const double , const double normal_force_norm, const double , const double , const Tensor< 1, 3 > & , Tensor< 1, 3 > &) inline private
Calculation of the rolling resistance torque model using the physical properties and the constant model.
Parameters
[in] particle_properties Particle one properties.
[in] effective_rolling_friction_coefficient Effective rolling friction coefficient.
[in] normal_force_norm Normal force norm.
Returns
Rolling resistance torque
Definition at line 118 of file particle_wall_linear_force.h.
epsd_resistance()
template<int dim, typename PropertiesIndex > Tensor< 1, 3 > ParticleWallLinearForce< dim, PropertiesIndex >::epsd_resistance (const ArrayView< const double > & particle_properties, const double effective_rolling_friction_coefficient, const double effective_rolling_viscous_damping_coefficient, const double normal_force_norm, const double dt, const double normal_spring_constant, const Tensor< 1, 3 > & normal_unit_vector, Tensor< 1, 3 > & cumulative_rolling_resistance_spring_torque) inline private
Calculation of the rolling resistance torque model using the physical properties and the elastic-plastic spring-dashpot model.
Parameters
[in] particle_properties Particle one properties.
[in] effective_rolling_friction_coefficient Effective rolling friction coefficient.
[in] effective_rolling_viscous_damping_coefficient Effective rolling viscous damping coefficient.
[in] normal_force_norm Normal force norm.
[in] dt DEM time step.
[in] normal_spring_constant Normal spring constant.
[in] normal_unit_vector Normal unit contact vector between the particle and the wall.
[in,out] cumulative_rolling_resistance_spring_torque Cumulative rolling resistance torque for the EPSD rolling resistance model.
Returns
Elasto-platique spring-dashpot rolling resistance torque
Definition at line 229 of file particle_wall_linear_force.h.
References ParticleWallLinearForce< dim, PropertiesIndex >::f_coefficient_epsd.
no_resistance()
template<int dim, typename PropertiesIndex > Tensor< 1, 3 > ParticleWallLinearForce< dim, PropertiesIndex >::no_resistance (const ArrayView< const double > & , const double , const double , const double , const double , const double , const Tensor< 1, 3 > & , Tensor< 1, 3 > &) inline private
No rolling resistance torque model.
Returns
Rolling resistance torque equal to the zero vector.
Definition at line 93 of file particle_wall_linear_force.h.
viscous_resistance()
template<int dim, typename PropertiesIndex > Tensor< 1, 3 > ParticleWallLinearForce< dim, PropertiesIndex >::viscous_resistance (const ArrayView< const double > & particle_properties, const double effective_rolling_friction_coefficient, const double , const double normal_force_norm, const double , const double , const Tensor< 1, 3 > & normal_unit_vector, Tensor< 1, 3 > &) inline private
Calculation of the rolling resistance torque model using the physical properties and the viscous model.
Parameters
[in] particle_properties Particle one properties.
[in] effective_rolling_friction_coefficient Effective rolling friction coefficient.
[in] normal_force_norm Normal force norm.
[in] normal_unit_vector Normal unit contact vector between the particle and the wall.
Returns
rolling resistance torque
Definition at line 168 of file particle_wall_linear_force.h.
Member Data Documentation
calculate_rolling_resistance_torque
template<int dim, typename PropertiesIndex > FuncPtrType ParticleWallLinearForce< dim, PropertiesIndex >::calculate_rolling_resistance_torque private
Definition at line 37 of file particle_wall_linear_force.h.
f_coefficient_epsd
template<int dim, typename PropertiesIndex > const double ParticleWallLinearForce< dim, PropertiesIndex >::f_coefficient_epsd private
Definition at line 328 of file particle_wall_linear_force.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/particle_wall_linear_force.h
/home/runner/work/lethe/lethe/source/dem/particle_wall_linear_force.cc