Lethe Open-Source Library: RayTracingSolverParameters< dim > Class Template Reference
RayTracingSolverParameters< dim > Class Template Reference
#include <ray_tracing_solver_parameters.h>
Public Member Functions
void declare (ParameterHandler &prm)
void parse (ParameterHandler &prm)
Public Attributes
Parameters::Mesh mesh
Parameters::Testing test
Parameters::Timer timer
Parameters::SimulationControl simulation_control
Parameters::Lagrangian::InsertionInfo< dim > particle_insertion_info
Parameters::Lagrangian::ParticleRayTracing< dim > ray_tracing_info
Parameters::Lagrangian::ModelParameters< dim > model_parameters
Detailed Description
template<int dim>
class RayTracingSolverParameters< dim >
Handles all the parameters declared in the parameter handler file.
Definition at line 15 of file ray_tracing_solver_parameters.h.
Member Function Documentation
declare()
template<int dim> void RayTracingSolverParameters< dim >::declare (ParameterHandler & prm) inline
Handles all the parameters declared in the parameter handler file.
Definition at line 30 of file ray_tracing_solver_parameters.h.
References Parameters::SimulationControl::declare_parameters(), Parameters::Timer::declare_parameters(), Parameters::Mesh::declare_parameters(), Parameters::Testing::declare_parameters(), Parameters::Lagrangian::InsertionInfo< dim >::declare_parameters(), Parameters::Lagrangian::ModelParameters< dim >::declare_parameters(), and Parameters::Lagrangian::ParticleRayTracing< dim >::declare_parameters().
parse()
template<int dim> void RayTracingSolverParameters< dim >::parse (ParameterHandler & prm) inline
Handles the parsing of all the parameters in the parameter handler file.
Definition at line 56 of file ray_tracing_solver_parameters.h.
References RayTracingSolverParameters< dim >::mesh, RayTracingSolverParameters< dim >::model_parameters, Parameters::SimulationControl::parse_parameters(), Parameters::Timer::parse_parameters(), Parameters::Mesh::parse_parameters(), Parameters::Testing::parse_parameters(), RayTracingSolverParameters< dim >::particle_insertion_info, RayTracingSolverParameters< dim >::ray_tracing_info, RayTracingSolverParameters< dim >::simulation_control, RayTracingSolverParameters< dim >::test, and RayTracingSolverParameters< dim >::timer.
Member Data Documentation
mesh
template<int dim> Parameters::Mesh RayTracingSolverParameters< dim >::mesh
Definition at line 18 of file ray_tracing_solver_parameters.h.
model_parameters
template<int dim> Parameters::Lagrangian::ModelParameters<dim> RayTracingSolverParameters< dim >::model_parameters
Definition at line 24 of file ray_tracing_solver_parameters.h.
particle_insertion_info
template<int dim> Parameters::Lagrangian::InsertionInfo<dim> RayTracingSolverParameters< dim >::particle_insertion_info
Definition at line 22 of file ray_tracing_solver_parameters.h.
ray_tracing_info
template<int dim> Parameters::Lagrangian::ParticleRayTracing<dim> RayTracingSolverParameters< dim >::ray_tracing_info
Definition at line 23 of file ray_tracing_solver_parameters.h.
simulation_control
template<int dim> Parameters::SimulationControl RayTracingSolverParameters< dim >::simulation_control
Definition at line 21 of file ray_tracing_solver_parameters.h.
test
template<int dim> Parameters::Testing RayTracingSolverParameters< dim >::test
Definition at line 19 of file ray_tracing_solver_parameters.h.
timer
template<int dim> Parameters::Timer RayTracingSolverParameters< dim >::timer
Definition at line 20 of file ray_tracing_solver_parameters.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/dem/ray_tracing_solver_parameters.h