Lethe Open-Source Library: NavierStokesScratchData< dim > Class Template Reference
NavierStokesScratchData< dim > Class Template Reference
#include <navier_stokes_scratch_data.h>
Public Member Functions
NavierStokesScratchData (const std::shared_ptr< SimulationControl > &simulation_control, const PhysicalPropertiesManager &properties_manager, const FESystem< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const Quadrature< dim - 1 > &face_quadrature)
NavierStokesScratchData (const NavierStokesScratchData< dim > &sd)
void allocate () override
template<typename VectorType >
void reinit (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const std::vector< VectorType > &previous_solutions, const VectorType &sum_over_previous_stages, std::shared_ptr< Function< dim > > forcing_function, Tensor< 1, dim > beta_force, const double pressure_scaling_factor)
void enable_vof (const FiniteElement< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const Parameters::VOF_PhaseFilter &phase_filter_parameters)
void enable_vof (const FiniteElement< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const std::shared_ptr< VolumeOfFluidFilterBase > &filter)
void enable_projected_phase_fraction_gradient (const FiniteElement< dim > &fe_projected_phase_fraction_gradient, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping)
void enable_curvature (const FiniteElement< dim > &fe_curvature, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping)
template<typename VectorType >
void reinit_vof (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const VectorType &current_filtered_solution, const std::vector< VectorType > &previous_solutions)
template<typename VectorType >
void reinit_projected_phase_fraction_gradient (const typename DoFHandler< dim >::active_cell_iterator &projected_phase_fraction_gradient_cell, const VectorType &current_projected_phase_fraction_gradient_solution)
template<typename VectorType >
void reinit_curvature (const typename DoFHandler< dim >::active_cell_iterator &curvature_cell, const VectorType &current_curvature_solution)
void enable_void_fraction (const FiniteElement< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping)
void enable_particle_field_projection (const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const FiniteElement< dim > &fe_particle_drag_proj, const FiniteElement< dim > &fe_particle_two_way_coupling_force_proj, const FiniteElement< dim > &fe_particle_velocity_proj)
template<typename VectorType >
void reinit_void_fraction (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const std::vector< VectorType > &previous_solutions)
void enable_particle_fluid_interactions (const unsigned int n_global_max_particles_per_cell, const bool enable_void_fraction_interpolation)
void reinit_particle_fluid_forces ()
void extract_particle_properties ()
void calculate_cell_void_fraction (const double &total_particle_volume)
Quadrature< dim > gather_particles_reference_location ()
template<typename VectorType >
void calculate_fluid_fields_at_particle_location (const Quadrature< dim > &q_particles_location, const typename DoFHandler< dim >::active_cell_iterator &velocity_cell, const VectorType &present_velocity_pressure_solution, const VectorType &previous_velocity_pressure_solution, const Parameters::DragCoupling &drag_coupling)
template<typename VectorType >
void calculate_void_fraction_at_particle_location (const Quadrature< dim > &q_particles_location, const typename DoFHandler< dim >::active_cell_iterator &void_fraction_cell, const VectorType &void_fraction_solution)
void calculate_fluid_properties_at_particle_location ()
void calculate_force_parameters_at_particle_location ()
template<typename VectorType >
void calculate_vof_at_particle_location (const Quadrature< dim > &q_particles_location, const typename DoFHandler< dim >::active_cell_iterator &phase_cell, const VectorType &current_filtered_solution)
template<typename VectorType >
void reinit_particle_fluid_interactions (const typename DoFHandler< dim >::active_cell_iterator &velocity_cell, const typename DoFHandler< dim >::active_cell_iterator &void_fraction_cell, const VectorType &present_velocity_pressure_solution, const VectorType &previous_velocity_pressure_solution, const VectorType &void_fraction_solution, const Particles::ParticleHandler< dim > &particle_handler, const Parameters::DragCoupling &drag_coupling)
template<typename VectorType >
void reinit_particle_fluid_interactions (const typename DoFHandler< dim >::active_cell_iterator &velocity_cell, const typename DoFHandler< dim >::active_cell_iterator &void_fraction_cell, const typename DoFHandler< dim >::active_cell_iterator &phase_cell, const VectorType &present_velocity_pressure_solution, const VectorType &previous_velocity_pressure_solution, const VectorType &void_fraction_solution, const Particles::ParticleHandler< dim > &particle_handler, const Parameters::DragCoupling &drag_coupling, const VectorType &current_filtered_VOF_solution)
void enable_heat_transfer (const FiniteElement< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping)
template<typename VectorType >
void reinit_heat_transfer (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const std::vector< VectorType > &previous_solutions)
void enable_cahn_hilliard (const FiniteElement< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const Parameters::CahnHilliard &cahn_hilliard_parameters)
void enable_cahn_hilliard (const FiniteElement< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const std::shared_ptr< CahnHilliardFilterBase > &cahn_hilliard_filter)
template<typename VectorType >
void reinit_cahn_hilliard (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const VectorType &current_filtered_solution)
void enable_mortar ()
void reinit_mortar (const typename DoFHandler< dim >::active_cell_iterator &cell, const Parameters::Mortar< dim > &mortar_parameters, const double &radius)
void calculate_physical_properties ()
template<typename VectorType >
void calculate_particle_fields_values (const typename DoFHandler< dim >::active_cell_iterator &particle_drag_cell, const typename DoFHandler< dim >::active_cell_iterator &particle_two_way_coupling_force_cell, const typename DoFHandler< dim >::active_cell_iterator &particle_velocity_cell, const VectorType &particle_fluid_drag, const VectorType &particle_fluid_force_two_way_coupling, const VectorType &particle_velocity, const Parameters::DragCoupling &drag_coupling)
Public Member Functions inherited from PhysicsScratchDataBase
virtual ~PhysicsScratchDataBase ()=default
Public Attributes
const std::shared_ptr< SimulationControl > simulation_control
const PhysicalPropertiesManager properties_manager
std::map< field, std::vector< double > > fields
std::vector< double > density
double density_ref
double density_psi
std::vector< double > dynamic_viscosity
std::vector< double > kinematic_viscosity
double kinematic_viscosity_scale
std::vector< double > kinematic_viscosity_for_stabilization
std::vector< double > dynamic_viscosity_for_stabilization
std::vector< double > thermal_expansion
std::vector< double > grad_kinematic_viscosity_shear_rate
std::vector< std::vector< double > > previous_density
double pressure_scaling_factor
std::vector< double > density_0
std::vector< double > density_1
double density_ref_0
double density_ref_1
double density_psi_0
double density_psi_1
double density_scale
std::vector< double > density_at_particle_location
std::vector< double > compressibility_multiplier
std::vector< double > dynamic_viscosity_0
std::vector< double > dynamic_viscosity_1
std::vector< double > kinematic_viscosity_0
std::vector< double > kinematic_viscosity_1
double kinematic_viscosity_scale_0
double kinematic_viscosity_scale_1
std::vector< double > kinematic_viscosity_at_particle_location
std::vector< double > dynamic_viscosity_for_stabilization_0
std::vector< double > dynamic_viscosity_for_stabilization_1
std::vector< double > thermal_expansion_0
std::vector< double > thermal_expansion_1
std::vector< double > surface_tension
std::vector< double > surface_tension_gradient
FEValues< dim > fe_values
unsigned int n_dofs
unsigned int n_q_points
double cell_size
FEValuesExtractors::Vector velocities
FEValuesExtractors::Scalar pressure
std::vector< Vector< double > > rhs_force
Tensor< 1, dim > beta_force
std::vector< Tensor< 1, dim > > force
std::vector< double > mass_source
Table< 1, double > JxW
std::vector< Point< dim > > quadrature_points
std::vector< unsigned int > components
std::vector< Tensor< 1, dim > > velocity_values
std::vector< double > velocity_divergences
std::vector< Tensor< 2, dim > > velocity_gradients
std::vector< Tensor< 1, dim > > velocity_laplacians
std::vector< Tensor< 3, dim > > velocity_hessians
std::vector< Tensor< 1, dim > > velocity_for_stabilization
std::vector< double > shear_rate
std::vector< double > pressure_values
std::vector< Tensor< 1, dim > > pressure_gradients
std::vector< std::vector< double > > previous_pressure_values
std::vector< std::vector< Tensor< 1, dim > > > previous_velocity_values
std::vector< Tensor< 1, dim > > sdirk_stage_sum
Table< 2, double > div_phi_u
Table< 2, Tensor< 1, dim > > phi_u
Table< 2, Tensor< 3, dim > > hess_phi_u
Table< 2, Tensor< 1, dim > > laplacian_phi_u
Table< 2, Tensor< 2, dim > > grad_phi_u
Table< 2, double > phi_p
Table< 2, Tensor< 1, dim > > grad_phi_p
bool gather_vof
unsigned int n_dofs_vof
std::vector< double > phase_values
std::vector< double > filtered_phase_values
std::vector< double > filtered_phase_values_at_particle_location
std::vector< std::vector< double > > previous_phase_values
std::vector< Tensor< 1, dim > > filtered_phase_gradient_values
std::vector< Tensor< 1, dim > > phase_gradient_values
std::shared_ptr< FEValues< dim > > fe_values_vof
std::shared_ptr< VolumeOfFluidFilterBase > filter
bool gather_projected_phase_fraction_gradient
bool gather_curvature
std::shared_ptr< FEValues< dim > > fe_values_projected_phase_fraction_gradient
std::shared_ptr< FEValues< dim > > fe_values_curvature
std::vector< Tensor< 1, dim > > projected_phase_fraction_gradient_values
std::vector< double > curvature_values
bool gather_void_fraction
unsigned int n_dofs_void_fraction
std::vector< double > void_fraction_values
std::vector< std::vector< double > > previous_void_fraction_values
std::vector< Tensor< 1, dim > > void_fraction_gradient_values
std::shared_ptr< FEValues< dim > > fe_values_void_fraction
bool gather_particles_information
bool interpolated_void_fraction
std::shared_ptr< FEValues< dim > > fe_values_particle_drag
std::shared_ptr< FEValues< dim > > fe_values_particle_two_way_coupling_force
std::shared_ptr< FEValues< dim > > fe_values_particle_velocity
bool gather_particle_field_project
std::vector< Tensor< 1, dim > > particle_velocity
std::vector< Tensor< 1, dim > > particle_velocity_values
std::vector< Tensor< 1, dim > > particle_drag_values
std::vector< Tensor< 1, dim > > particle_two_way_coupling_force_values
Tensor< 1, dim > average_particle_velocity
std::vector< Tensor< 1, dim > > fluid_velocity_at_particle_location
std::vector< Tensor< 1, dim > > fluid_particle_relative_velocity_at_particle_location
Tensor< 1, dim > average_fluid_particle_relative_velocity
std::vector< Tensor< 1, dim > > fluid_pressure_gradients_at_particle_location
std::vector< Tensor< 1, dim > > fluid_velocity_laplacian_at_particle_location
std::vector< Tensor< 1, 1 > > fluid_velocity_curls_at_particle_location_2d
std::vector< Tensor< 1, 3 > > fluid_velocity_curls_at_particle_location_3d
std::vector< Point< dim > > particle_reference_location
std::vector< double > particle_weights
std::vector< double > cell_void_fraction
std::vector< double > Re_particle
unsigned int max_number_of_particles_per_cell
unsigned int number_of_particles
Particles::ParticleHandler< dim >::particle_iterator_range pic
double total_particle_volume
double cell_volume
double beta_drag
Tensor< 1, dim > explicit_particle_volumetric_acceleration_on_fluid
bool gather_temperature
unsigned int n_dofs_heat_transfer
std::vector< double > temperature_values
std::vector< std::vector< double > > previous_temperature_values
std::vector< Tensor< 1, dim > > temperature_gradients
std::vector< std::vector< Tensor< 1, dim > > > previous_temperature_gradients
std::shared_ptr< FEValues< dim > > fe_values_temperature
bool gather_cahn_hilliard
unsigned int n_dofs_cahn_hilliard
std::vector< double > phase_order_cahn_hilliard_values
std::vector< double > filtered_phase_order_cahn_hilliard_values
std::vector< Tensor< 1, dim > > phase_order_cahn_hilliard_gradients
std::vector< double > chemical_potential_cahn_hilliard_values
std::shared_ptr< CahnHilliardFilterBase > cahn_hilliard_filter
std::shared_ptr< FEValues< dim > > fe_values_cahn_hilliard
FEValuesExtractors::Scalar phase_order
FEValuesExtractors::Scalar chemical_potential
bool gather_mortar
std::vector< Tensor< 1, dim > > rotor_linear_velocity_values
bool is_boundary_cell
bool gather_hessian
FEFaceValues< dim > fe_face_values
unsigned int n_faces
unsigned int n_faces_q_points
unsigned int face_n_dofs
std::vector< bool > is_boundary_face
std::vector< unsigned int > boundary_face_id
Table< 2, double > face_JxW
std::vector< std::vector< Point< dim > > > face_quadrature_points
Table< 2, Tensor< 1, dim > > face_normal
std::vector< std::vector< Tensor< 1, dim > > > face_velocity_values
std::vector< std::vector< double > > face_velocity_divergences
std::vector< std::vector< Tensor< 2, dim > > > face_velocity_gradients
std::vector< std::vector< Tensor< 1, dim > > > face_velocity_laplacians
std::vector< std::vector< double > > face_pressure_values
std::vector< std::vector< Tensor< 1, dim > > > face_pressure_gradients
Table< 3, double > face_div_phi_u
Table< 3, Tensor< 1, dim > > face_phi_u
Table< 3, Tensor< 3, dim > > face_hess_phi_u
Table< 3, Tensor< 1, dim > > face_laplacian_phi_u
Table< 3, Tensor< 2, dim > > face_grad_phi_u
Table< 3, double > face_phi_p
Table< 3, Tensor< 1, dim > > face_grad_phi_p
SDIRKTable sdirk_table
Detailed Description
template<int dim>
class NavierStokesScratchData< dim >
Class that stores the information required by the assembly procedure for a Navier-Stokes equation. Consequently, this class calculates the velocity (values, gradients, laplacians) and the shape function (values, gradients, laplacians) at all the gauss points for all degrees of freedom and stores it into arrays. Additionally, the use can request that this class gathers additional fields for physics which are coupled to the Navier-Stokes equation, such as the VOF. This class serves as a separation between the evaluation at the gauss point of the variables of interest and their use in the assembly, which is carried out by the assembler functions. For more information on this design, the reader can consult deal.II step-9 "https://www.dealii.org/current/doxygen/deal.II/step_9.html". In this latter example, the scratch is a struct instead of a templated class because of the simplicity of step-9.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 55 of file navier_stokes_scratch_data.h.
Constructor & Destructor Documentation
NavierStokesScratchData() [1/2]
template<int dim> NavierStokesScratchData< dim >::NavierStokesScratchData (const std::shared_ptr< SimulationControl > & simulation_control, const PhysicalPropertiesManager & properties_manager, const FESystem< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const Quadrature< dim - 1 > & face_quadrature) inline
Constructor. The constructor creates the fe_values that will be used to fill the member variables of the scratch. It also allocated the necessary memory for all member variables. However, it does not do any evaluation, since this needs to be done at the cell level.
Parameters
simulation_control The SimulationControl object that holds information related to the control of the steady-state or transient simulation. This is used to extrapolate auxiliary physics solutions in time for transient simulation.
properties_manager The PhysicalPropertiesManager object that stores physical property models.
fe The FESystem used to solve the Navier-Stokes equations
quadrature The quadrature to use for the assembly
mapping The mapping of the domain in which the Navier-Stokes equations are solved
Definition at line 79 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::allocate(), NavierStokesScratchData< dim >::gather_cahn_hilliard, NavierStokesScratchData< dim >::gather_curvature, NavierStokesScratchData< dim >::gather_hessian, NavierStokesScratchData< dim >::gather_mortar, NavierStokesScratchData< dim >::gather_particle_field_project, NavierStokesScratchData< dim >::gather_particles_information, NavierStokesScratchData< dim >::gather_projected_phase_fraction_gradient, NavierStokesScratchData< dim >::gather_temperature, NavierStokesScratchData< dim >::gather_vof, NavierStokesScratchData< dim >::gather_void_fraction, PhysicalPropertiesManager::is_non_newtonian(), and NavierStokesScratchData< dim >::properties_manager.
NavierStokesScratchData() [2/2]
template<int dim> NavierStokesScratchData< dim >::NavierStokesScratchData (const NavierStokesScratchData< dim > & sd) inline
Copy Constructor. Same as the main constructor. This constructor only uses the other scratch to build the FeValues, it does not copy the content of the other scratch into itself since, by definition of the WorkStream mechanism it is assumed that the content of the scratch will be reset on a cell basis.
Parameters
sd The scratch data to be copied
Definition at line 129 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::allocate(), NavierStokesScratchData< dim >::cahn_hilliard_filter, NavierStokesScratchData< dim >::enable_cahn_hilliard(), NavierStokesScratchData< dim >::enable_curvature(), NavierStokesScratchData< dim >::enable_heat_transfer(), NavierStokesScratchData< dim >::enable_mortar(), NavierStokesScratchData< dim >::enable_particle_field_projection(), NavierStokesScratchData< dim >::enable_particle_fluid_interactions(), NavierStokesScratchData< dim >::enable_projected_phase_fraction_gradient(), NavierStokesScratchData< dim >::enable_vof(), NavierStokesScratchData< dim >::enable_void_fraction(), NavierStokesScratchData< dim >::fe_values, NavierStokesScratchData< dim >::fe_values_cahn_hilliard, NavierStokesScratchData< dim >::fe_values_curvature, NavierStokesScratchData< dim >::fe_values_particle_drag, NavierStokesScratchData< dim >::fe_values_particle_two_way_coupling_force, NavierStokesScratchData< dim >::fe_values_particle_velocity, NavierStokesScratchData< dim >::fe_values_projected_phase_fraction_gradient, NavierStokesScratchData< dim >::fe_values_temperature, NavierStokesScratchData< dim >::fe_values_vof, NavierStokesScratchData< dim >::fe_values_void_fraction, NavierStokesScratchData< dim >::filter, NavierStokesScratchData< dim >::gather_cahn_hilliard, NavierStokesScratchData< dim >::gather_curvature, NavierStokesScratchData< dim >::gather_hessian, NavierStokesScratchData< dim >::gather_mortar, NavierStokesScratchData< dim >::gather_particle_field_project, NavierStokesScratchData< dim >::gather_particles_information, NavierStokesScratchData< dim >::gather_projected_phase_fraction_gradient, NavierStokesScratchData< dim >::gather_temperature, NavierStokesScratchData< dim >::gather_vof, NavierStokesScratchData< dim >::gather_void_fraction, NavierStokesScratchData< dim >::interpolated_void_fraction, PhysicalPropertiesManager::is_non_newtonian(), NavierStokesScratchData< dim >::max_number_of_particles_per_cell, and NavierStokesScratchData< dim >::properties_manager.
Member Function Documentation
allocate()
template<int dim> void NavierStokesScratchData< dim >::allocate () override virtual
Allocates the memory for the scratch.
This function allocates the necessary memory for all members of the scratch
Implements PhysicsScratchDataBase.
Definition at line 11 of file navier_stokes_scratch_data.cc.
References maximum_number_of_previous_solutions(), pressure, and shear_rate.
calculate_cell_void_fraction()
template<int dim> void NavierStokesScratchData< dim >::calculate_cell_void_fraction (const double & total_particle_volume)
Computes the cell void fraction.
Parameters
[in] total_particle_volume The total volume of the particles in the cell
Definition at line 766 of file navier_stokes_scratch_data.cc.
References compute_cell_measure_with_JxW().
calculate_fluid_fields_at_particle_location()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::calculate_fluid_fields_at_particle_location (const Quadrature< dim > & q_particles_location, const typename DoFHandler< dim >::active_cell_iterator & velocity_cell, const VectorType & present_velocity_pressure_solution, const VectorType & previous_velocity_pressure_solution, const Parameters::DragCoupling & drag_coupling) inline
Interpolates the velocity and pressure of the fluid, as well as the pressure gradient, and the laplacian, curl and gradient of the velocity, at the locations of the particles.
Parameters
[in] q_particles_location Quadrature type object that contains the location of the particles relative to the cell's frame of reference.
[in] velocity_cell The active cell associated with the velocity and pressure DoFHandler
[in] present_velocity_pressure_solution The solution (velocity and pressure) at the current time step. This solution is used in the implicit coupling to establish the particle-fluid force.
[in] previous_velocity_pressure_solution The solution (velocity and pressure) at the previous time step. This solution is used in the explicit and semi-implicit coupling to calculate the particle-fluid force.
[in] drag_coupling Indicator for the type of coupling that is used. This parameter essentially decides which velocity_pressure solution is interpolated at the location of the particles.
Definition at line 742 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::fe_values, NavierStokesScratchData< dim >::fluid_pressure_gradients_at_particle_location, NavierStokesScratchData< dim >::fluid_velocity_at_particle_location, NavierStokesScratchData< dim >::fluid_velocity_curls_at_particle_location_2d, NavierStokesScratchData< dim >::fluid_velocity_curls_at_particle_location_3d, NavierStokesScratchData< dim >::fluid_velocity_laplacian_at_particle_location, Parameters::fully_implicit, NavierStokesScratchData< dim >::number_of_particles, NavierStokesScratchData< dim >::pressure, and NavierStokesScratchData< dim >::velocities.
calculate_fluid_properties_at_particle_location()
template<int dim> void NavierStokesScratchData< dim >::calculate_fluid_properties_at_particle_location () inline
Calculates the properties of the fluid at the locations of the particles. At the moment, only constant properties within the same fluid are supported. When two fluids are present and VOF is used, the properties are calculated based on the filtered VOF solution interpolated at the location of the particles. These properties are used in the forces calculations in the VANS equations.
Definition at line 848 of file navier_stokes_scratch_data.h.
References calculate_point_property(), NavierStokesScratchData< dim >::density_at_particle_location, PhysicalPropertiesManager::density_is_constant(), NavierStokesScratchData< dim >::density_ref_0, NavierStokesScratchData< dim >::density_ref_1, NavierStokesScratchData< dim >::density_scale, NavierStokesScratchData< dim >::filtered_phase_values_at_particle_location, NavierStokesScratchData< dim >::gather_vof, PhysicalPropertiesManager::get_rheology(), NavierStokesScratchData< dim >::kinematic_viscosity_at_particle_location, NavierStokesScratchData< dim >::kinematic_viscosity_scale, NavierStokesScratchData< dim >::kinematic_viscosity_scale_0, NavierStokesScratchData< dim >::kinematic_viscosity_scale_1, NavierStokesScratchData< dim >::number_of_particles, and NavierStokesScratchData< dim >::properties_manager.
calculate_force_parameters_at_particle_location()
template<int dim> void NavierStokesScratchData< dim >::calculate_force_parameters_at_particle_location () inline
Calculates the velocity of the fluid relative to that of the particle and the particle Reynolds number at the location of the particles. These will be used in forces calculations in the vans equations.
Definition at line 906 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::average_fluid_particle_relative_velocity, NavierStokesScratchData< dim >::cell_void_fraction, DEM::CFDDEMProperties::dp, NavierStokesScratchData< dim >::fluid_particle_relative_velocity_at_particle_location, NavierStokesScratchData< dim >::fluid_velocity_at_particle_location, NavierStokesScratchData< dim >::kinematic_viscosity_at_particle_location, NavierStokesScratchData< dim >::particle_velocity, NavierStokesScratchData< dim >::pic, and NavierStokesScratchData< dim >::Re_particle.
calculate_particle_fields_values()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::calculate_particle_fields_values (const typename DoFHandler< dim >::active_cell_iterator & particle_drag_cell, const typename DoFHandler< dim >::active_cell_iterator & particle_two_way_coupling_force_cell, const typename DoFHandler< dim >::active_cell_iterator & particle_velocity_cell, const VectorType & particle_fluid_drag, const VectorType & particle_fluid_force_two_way_coupling, const VectorType & particle_velocity, const Parameters::DragCoupling & drag_coupling) inline
Calculates the particle forces and velocities that were projected on the fluid dofs at the quadrature points of the velocity and pressure FE. The values are stored in the corresponding variables in scratch data.
Parameters
[in] particle_drag_cell Iterator pointing to the current active cell using the particle drag force DoFHandler
[in] particle_two_way_coupling_force Iterator pointing to the current active cell using the particle two-way coupling force DoFHandler
[in] particle_velocity_cell Iterator pointing to the current active cell using the particle velocity DoFHandler
[in] particle_fluid_drag Object containing the projection of the particle drag onto the fluid dofs
[in] particle_two_way_coupling_force Object containing the projection of the two-way coupling force projected from the particles onto the fluid dofs
[in] particle_velocity Object containing the projection of the particle velocities onto the fluid dofs
Definition at line 1335 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::fe_values_particle_drag, NavierStokesScratchData< dim >::fe_values_particle_two_way_coupling_force, NavierStokesScratchData< dim >::fe_values_particle_velocity, Parameters::fully_explicit, NavierStokesScratchData< dim >::particle_drag_values, NavierStokesScratchData< dim >::particle_two_way_coupling_force_values, NavierStokesScratchData< dim >::particle_velocity, and NavierStokesScratchData< dim >::particle_velocity_values.
calculate_physical_properties()
template<int dim> void NavierStokesScratchData< dim >::calculate_physical_properties ()
Calculates the physical properties. This function calculates the physical properties that may be required by the fluid dynamics problem. Namely the kinematic viscosity and, when required, the density.
Definition at line 464 of file navier_stokes_scratch_data.cc.
References calculate_point_property(), calculate_point_property_cahn_hilliard(), calculate_shear_rate_magnitude(), fluid_fluid, pressure, set_field_vector(), shear_rate, and temperature.
calculate_vof_at_particle_location()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::calculate_vof_at_particle_location (const Quadrature< dim > & q_particles_location, const typename DoFHandler< dim >::active_cell_iterator & phase_cell, const VectorType & current_filtered_solution) inline
Interpolates the filtered VOF solution at the location of the particles. The latter values are used in calculating the density and viscosity of the fluid at the particles' locations when VOF is used.
Parameters
[in] q_particles_location Quadrature type object that contains the location of the particles relative to the cell's frame of reference.
[in] phase_cell The active cell associated with the VOF DoFHandler
[in] current_filtered_solution The present value of the filtered VOF solution
Definition at line 954 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::fe_values_vof, NavierStokesScratchData< dim >::filtered_phase_values_at_particle_location, NavierStokesScratchData< dim >::gather_vof, and NavierStokesScratchData< dim >::number_of_particles.
calculate_void_fraction_at_particle_location()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::calculate_void_fraction_at_particle_location (const Quadrature< dim > & q_particles_location, const typename DoFHandler< dim >::active_cell_iterator & void_fraction_cell, const VectorType & void_fraction_solution) inline
Interpolates the void fraction at the locations of the particles.
Parameters
[in] q_particles_location Quadrature type object that contains the location of the particles relative to the cell's frame of reference.
[in] void_fraction_cell The active cell associated with the void fraction DoFHandler
[in] void_fraction_solution The void fraction calculated with one of the methods of the VoidFractionBase class.
Definition at line 813 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::cell_void_fraction, NavierStokesScratchData< dim >::fe_values_void_fraction, and NavierStokesScratchData< dim >::gather_void_fraction.
enable_cahn_hilliard() [1/2]
template<int dim> void NavierStokesScratchData< dim >::enable_cahn_hilliard (const FiniteElement< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const Parameters::CahnHilliard & cahn_hilliard_parameters)
enable_cahn_hilliard Enables the collection of the CahnHilliard data by the scratch
Parameters
fe FiniteElement associated with the CahnHilliard physics
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
Definition at line 178 of file navier_stokes_scratch_data.cc.
References CahnHilliardFilterBase::model_cast(), phase_order_cahn_hilliard, and phase_order_cahn_hilliard_filtered.
enable_cahn_hilliard() [2/2]
template<int dim> void NavierStokesScratchData< dim >::enable_cahn_hilliard (const FiniteElement< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const std::shared_ptr< CahnHilliardFilterBase > & cahn_hilliard_filter)
Enables the collection of the CahnHilliard data by the scratch.
Parameters
fe FiniteElement associated with the CahnHilliard physics
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
Definition at line 226 of file navier_stokes_scratch_data.cc.
References phase_order_cahn_hilliard, and phase_order_cahn_hilliard_filtered.
enable_curvature()
template<int dim> void NavierStokesScratchData< dim >::enable_curvature (const FiniteElement< dim > & fe_curvature, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping)
Definition at line 295 of file navier_stokes_scratch_data.cc.
enable_heat_transfer()
template<int dim> void NavierStokesScratchData< dim >::enable_heat_transfer (const FiniteElement< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping)
enable_heat_transfer Enables the collection of the heat transfer data (Temperature field) by the scratch
Parameters
fe FiniteElement associated with the heat transfer.
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
Definition at line 440 of file navier_stokes_scratch_data.cc.
References maximum_number_of_previous_solutions(), and temperature.
enable_mortar()
template<int dim> void NavierStokesScratchData< dim >::enable_mortar ()
enable_mortar Enables the calculation of the rotor rotation angle
Definition at line 390 of file navier_stokes_scratch_data.cc.
enable_particle_field_projection()
template<int dim> void NavierStokesScratchData< dim >::enable_particle_field_projection (const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const FiniteElement< dim > & fe_particle_drag_proj, const FiniteElement< dim > & fe_particle_two_way_coupling_force_proj, const FiniteElement< dim > & fe_particle_velocity_proj)
enable_particle_field_projection Enables the collection of the particle fields projection data by the scratch
Parameters
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
fe_particle_drag_proj FiniteElement associated with the projected particle drag force
fe_particle_two_way_coupling_force_proj FiniteElement associated with the projected particle two-way coupling force
fe_particle_velocity_proj FiniteElement associated with the projected particle velocity
Definition at line 337 of file navier_stokes_scratch_data.cc.
enable_particle_fluid_interactions()
template<int dim> void NavierStokesScratchData< dim >::enable_particle_fluid_interactions (const unsigned int n_global_max_particles_per_cell, const bool enable_void_fraction_interpolation)
enable_particle_fluid_interactions Enables the calculation of the fluid information at the particle location for the scratch.
Parameters
fe FiniteElement associated with the void fraction
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
Definition at line 365 of file navier_stokes_scratch_data.cc.
enable_projected_phase_fraction_gradient()
template<int dim> void NavierStokesScratchData< dim >::enable_projected_phase_fraction_gradient (const FiniteElement< dim > & fe_projected_phase_fraction_gradient, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping)
Definition at line 275 of file navier_stokes_scratch_data.cc.
enable_vof() [1/2]
template<int dim> void NavierStokesScratchData< dim >::enable_vof (const FiniteElement< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const Parameters::VOF_PhaseFilter & phase_filter_parameters)
enable_vof Enables the collection of the VOF data by the scratch
Parameters
fe FiniteElement associated with the VOF.
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
phase_filter_parameters Parameters for phase fraction filtering
Definition at line 96 of file navier_stokes_scratch_data.cc.
References maximum_number_of_previous_solutions(), and VolumeOfFluidFilterBase::model_cast().
enable_vof() [2/2]
template<int dim> void NavierStokesScratchData< dim >::enable_vof (const FiniteElement< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const std::shared_ptr< VolumeOfFluidFilterBase > & filter)
enable_vof Enables the collection of the VOF data by the scratch - function overload used in the copy constructor of NavierStokesScratchData
Parameters
fe FiniteElement associated with the VOF.
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
filter Filter that is applied on the phase fraction
Definition at line 137 of file navier_stokes_scratch_data.cc.
References maximum_number_of_previous_solutions().
enable_void_fraction()
template<int dim> void NavierStokesScratchData< dim >::enable_void_fraction (const FiniteElement< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping)
enable_void_fraction Enables the collection of the void fraction data by the scratch
Parameters
fe FiniteElement associated with the void fraction
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
Definition at line 311 of file navier_stokes_scratch_data.cc.
References maximum_number_of_previous_solutions().
extract_particle_properties()
template<int dim> void NavierStokesScratchData< dim >::extract_particle_properties ()
Extracts the velocity of the particles and calculates their total volume in the cell. Both outcomes are stored as members of the scratch data class.
Definition at line 727 of file navier_stokes_scratch_data.cc.
References DEM::CFDDEMProperties::dp, DEM::CFDDEMProperties::v_x, DEM::CFDDEMProperties::v_y, and DEM::CFDDEMProperties::v_z.
gather_particles_reference_location()
template<int dim> Quadrature< dim > NavierStokesScratchData< dim >::gather_particles_reference_location ()
Creates an object of type Quadrature<dim> that contains the particle reference location. This object can be used to interpolate any function known at the dofs at the location of the particles.
Returns
Quadrature type object that contains the location of the particles relative to the cell's frame of reference.
Definition at line 792 of file navier_stokes_scratch_data.cc.
reinit()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const std::vector< VectorType > & previous_solutions, const VectorType & sum_over_previous_stages, std::shared_ptr< Function< dim > > forcing_function, Tensor< 1, dim > beta_force, const double pressure_scaling_factor) inline
Reinitializes the content of the scratch.
Using the FeValues and the content of the solutions and previous solutions, fills all of the class member of the scratch.
Parameters
[in] cell The cell over which the assembly is being carried. This cell must be compatible with the FE which is used to fill the FeValues.
[in] current_solution The present value of the solution for [u,p].
[in] previous_solutions The solutions at the previous time steps.
[in] forcing_function The function describing the momentum/mass source term.
[in] beta_force The additional force for flow control. TODO : Deprecate this argument and pass it to the constructor of the assembler
Definition at line 237 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::beta_force, NavierStokesScratchData< dim >::boundary_face_id, NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::components, compute_cell_measure_with_JxW(), PhysicalPropertiesManager::density_is_constant(), NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::face_div_phi_u, NavierStokesScratchData< dim >::face_grad_phi_p, NavierStokesScratchData< dim >::face_grad_phi_u, NavierStokesScratchData< dim >::face_hess_phi_u, NavierStokesScratchData< dim >::face_JxW, NavierStokesScratchData< dim >::face_laplacian_phi_u, NavierStokesScratchData< dim >::face_normal, NavierStokesScratchData< dim >::face_phi_p, NavierStokesScratchData< dim >::face_phi_u, NavierStokesScratchData< dim >::face_pressure_gradients, NavierStokesScratchData< dim >::face_pressure_values, NavierStokesScratchData< dim >::face_quadrature_points, NavierStokesScratchData< dim >::face_velocity_divergences, NavierStokesScratchData< dim >::face_velocity_gradients, NavierStokesScratchData< dim >::face_velocity_laplacians, NavierStokesScratchData< dim >::face_velocity_values, NavierStokesScratchData< dim >::fe_face_values, NavierStokesScratchData< dim >::fe_values, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::gather_hessian, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::hess_phi_u, NavierStokesScratchData< dim >::is_boundary_cell, NavierStokesScratchData< dim >::is_boundary_face, NavierStokesScratchData< dim >::JxW, NavierStokesScratchData< dim >::laplacian_phi_u, NavierStokesScratchData< dim >::mass_source, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_faces, NavierStokesScratchData< dim >::n_faces_q_points, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, NavierStokesScratchData< dim >::pressure, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_scaling_factor, NavierStokesScratchData< dim >::pressure_values, NavierStokesScratchData< dim >::previous_pressure_values, NavierStokesScratchData< dim >::previous_velocity_values, NavierStokesScratchData< dim >::properties_manager, NavierStokesScratchData< dim >::quadrature_points, NavierStokesScratchData< dim >::rhs_force, NavierStokesScratchData< dim >::sdirk_stage_sum, NavierStokesScratchData< dim >::simulation_control, NavierStokesScratchData< dim >::velocities, NavierStokesScratchData< dim >::velocity_divergences, NavierStokesScratchData< dim >::velocity_for_stabilization, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_hessians, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
reinit_cahn_hilliard()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit_cahn_hilliard (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const VectorType & current_filtered_solution) inline
Reinitialize the content of the scratch for CH.
Parameters
cell The cell over which the assembly is being carried. This cell must be compatible with the CH FE and not the Navier-Stokes FE
current_solution The present value of the solution for [phi]
Definition at line 1252 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::chemical_potential, NavierStokesScratchData< dim >::chemical_potential_cahn_hilliard_values, NavierStokesScratchData< dim >::fe_values_cahn_hilliard, NavierStokesScratchData< dim >::filtered_phase_order_cahn_hilliard_values, NavierStokesScratchData< dim >::phase_order, NavierStokesScratchData< dim >::phase_order_cahn_hilliard_gradients, and NavierStokesScratchData< dim >::phase_order_cahn_hilliard_values.
reinit_curvature()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit_curvature (const typename DoFHandler< dim >::active_cell_iterator & curvature_cell, const VectorType & current_curvature_solution) inline
Definition at line 570 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::curvature_values, NavierStokesScratchData< dim >::fe_values_curvature, and NavierStokesScratchData< dim >::gather_curvature.
reinit_heat_transfer()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit_heat_transfer (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const std::vector< VectorType > & previous_solutions) inline
Reinitialize the content of the scratch for the heat transfer auxiliary physic.
Parameters
cell The cell over which the assembly is being carried. This cell must be compatible with the heat transfer FE and not the Navier-Stokes FE
current_solution The present value of the solution for temperature
previous_solutions Vector of \(n\) VectorType containers of previous temperature solutions. \(n\) depends on the BDF scheme selected for time-stepping.
Definition at line 1166 of file navier_stokes_scratch_data.h.
References bdf_extrapolate(), NavierStokesScratchData< dim >::fe_values_temperature, number_of_previous_solutions(), NavierStokesScratchData< dim >::previous_temperature_gradients, NavierStokesScratchData< dim >::previous_temperature_values, NavierStokesScratchData< dim >::simulation_control, NavierStokesScratchData< dim >::temperature_gradients, NavierStokesScratchData< dim >::temperature_values, and time_stepping_is_bdf().
reinit_mortar()
template<int dim> void NavierStokesScratchData< dim >::reinit_mortar (const typename DoFHandler< dim >::active_cell_iterator & cell, const Parameters::Mortar< dim > & mortar_parameters, const double & radius)
Renitialize the content of the scratch data for mortar.
Parameters
[in] cell The cell over which the assembly is being carried. This cell must be compatible with the FE which is used to fill the FeValues.
[in] mortar_parameters Parameters for the mortar method
[in] radius Radius of the rotor domain
Definition at line 397 of file navier_stokes_scratch_data.cc.
References Parameters::Mortar< dim >::center_of_rotation, and Parameters::Mortar< dim >::rotor_angular_velocity.
reinit_particle_fluid_forces()
template<int dim> void NavierStokesScratchData< dim >::reinit_particle_fluid_forces ()
Reinitializes the fluid forces and torques on the particles in the cell to zero.
Definition at line 702 of file navier_stokes_scratch_data.cc.
References DEM::CFDDEMProperties::fem_drag_x, and DEM::CFDDEMProperties::fem_torque_x.
reinit_particle_fluid_interactions() [1/2]
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit_particle_fluid_interactions (const typename DoFHandler< dim >::active_cell_iterator & velocity_cell, const typename DoFHandler< dim >::active_cell_iterator & void_fraction_cell, const typename DoFHandler< dim >::active_cell_iterator & phase_cell, const VectorType & present_velocity_pressure_solution, const VectorType & previous_velocity_pressure_solution, const VectorType & void_fraction_solution, const Particles::ParticleHandler< dim > & particle_handler, const Parameters::DragCoupling & drag_coupling, const VectorType & current_filtered_VOF_solution) inline
Calculates the variables needed to compute the particle fluid interactions in the VANS equations.This version of the function is used when VOF is used with CFD-DEM.
Parameters
[in] velocity_cell The active cell associated with the velocity and pressure DoFHandler.
[in] void_fraction_cell The active cell associated with the void fraction DoFHandler.
[in] phase_cell The active cell associated with the VOF DoFHandler.
[in] present_velocity_pressure_solution The solution (velocity and pressure) at the current time step. This solution is used in the implicit coupling to establish the particle-fluid force.
[in] previous_velocity_pressure_solution The solution (velocity and pressure) at the previous time step. This solution is used in the explicit and semi-implicit coupling to calculate the particle-fluid force.
[in] void_fraction_solution The void fraction value calculated with one of the methods of the VoidFractionBase class.
[in] particle_handler The particle handler object that stores and manages the particles in the simulations.
[in] current_filtered_VOF_solution The present value of the VOF solution.
[in] drag_coupling Indicator for the type of coupling that is used. This parameter essentially decides which velocity_pressure solution is interpolated at the location of the particles.
Definition at line 1091 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::calculate_cell_void_fraction(), NavierStokesScratchData< dim >::calculate_fluid_fields_at_particle_location(), NavierStokesScratchData< dim >::calculate_fluid_properties_at_particle_location(), NavierStokesScratchData< dim >::calculate_force_parameters_at_particle_location(), NavierStokesScratchData< dim >::calculate_vof_at_particle_location(), NavierStokesScratchData< dim >::calculate_void_fraction_at_particle_location(), NavierStokesScratchData< dim >::extract_particle_properties(), NavierStokesScratchData< dim >::gather_particles_reference_location(), NavierStokesScratchData< dim >::interpolated_void_fraction, NavierStokesScratchData< dim >::number_of_particles, NavierStokesScratchData< dim >::pic, NavierStokesScratchData< dim >::reinit_particle_fluid_forces(), and NavierStokesScratchData< dim >::total_particle_volume.
reinit_particle_fluid_interactions() [2/2]
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit_particle_fluid_interactions (const typename DoFHandler< dim >::active_cell_iterator & velocity_cell, const typename DoFHandler< dim >::active_cell_iterator & void_fraction_cell, const VectorType & present_velocity_pressure_solution, const VectorType & previous_velocity_pressure_solution, const VectorType & void_fraction_solution, const Particles::ParticleHandler< dim > & particle_handler, const Parameters::DragCoupling & drag_coupling) inline
Calculates the variables needed to compute the particle fluid interactions in the VANS equations.
Parameters
[in] velocity_cell The active cell associated with the velocity and pressure DoFHandler
[in] void_fraction_cell The active cell associated with the void fraction DoFHandler
[in] present_velocity_pressure_solution The solution (velocity and pressure) at the current time step. This solution is used in the implicit coupling to establish the particle-fluid force.
[in] previous_velocity_pressure_solution The solution (velocity and pressure) at the previous time step. This solution is used in the explicit and semi-implicit coupling to calculate the particle-fluid force.
[in] void_fraction_solution The void fraction value calculated with one of the methods of the VoidFractionBase class.
[in] particle_handler The particle handler object that stores and manages the particles in the simulations
[in] drag_coupling Indicator for the type of coupling that is used. This parameter essentially decides which velocity_pressure solution is interpolated at the location of the particles.
Definition at line 1010 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::calculate_cell_void_fraction(), NavierStokesScratchData< dim >::calculate_fluid_fields_at_particle_location(), NavierStokesScratchData< dim >::calculate_fluid_properties_at_particle_location(), NavierStokesScratchData< dim >::calculate_force_parameters_at_particle_location(), NavierStokesScratchData< dim >::calculate_void_fraction_at_particle_location(), NavierStokesScratchData< dim >::extract_particle_properties(), NavierStokesScratchData< dim >::gather_particles_information, NavierStokesScratchData< dim >::gather_particles_reference_location(), NavierStokesScratchData< dim >::interpolated_void_fraction, NavierStokesScratchData< dim >::number_of_particles, NavierStokesScratchData< dim >::pic, NavierStokesScratchData< dim >::reinit_particle_fluid_forces(), and NavierStokesScratchData< dim >::total_particle_volume.
reinit_projected_phase_fraction_gradient()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit_projected_phase_fraction_gradient (const typename DoFHandler< dim >::active_cell_iterator & projected_phase_fraction_gradient_cell, const VectorType & current_projected_phase_fraction_gradient_solution) inline
Definition at line 553 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::fe_values_projected_phase_fraction_gradient, and NavierStokesScratchData< dim >::projected_phase_fraction_gradient_values.
reinit_vof()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit_vof (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const VectorType & current_filtered_solution, const std::vector< VectorType > & previous_solutions) inline
Reinitialize the content of the scratch for the vof.
Parameters
cell The cell over which the assembly is being carried. This cell must be compatible with the VOF FE and not the Navier-Stokes FE
current_solution The present value of the solution for [alpha]
current_filtered_solution The present value of the solution for [alpha]_filtered
previous_solutions The solutions at the previous time steps for [alpha]
Definition at line 522 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::fe_values_vof, NavierStokesScratchData< dim >::filtered_phase_gradient_values, NavierStokesScratchData< dim >::filtered_phase_values, NavierStokesScratchData< dim >::gather_vof, NavierStokesScratchData< dim >::phase_gradient_values, NavierStokesScratchData< dim >::phase_values, and NavierStokesScratchData< dim >::previous_phase_values.
reinit_void_fraction()
template<int dim> template<typename VectorType > void NavierStokesScratchData< dim >::reinit_void_fraction (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const std::vector< VectorType > & previous_solutions) inline
Reinitialize the content of the scratch for the void fraction.
Parameters
cell The cell over which the assembly is being carried. This cell must be compatible with the void fraction FE and not the Navier-Stokes FE
current_solution The present value of the solution for [epsilon]
previous_solutions The solutions at the previous time steps for [epsilon]
Definition at line 639 of file navier_stokes_scratch_data.h.
References NavierStokesScratchData< dim >::fe_values_void_fraction, NavierStokesScratchData< dim >::gather_void_fraction, NavierStokesScratchData< dim >::previous_void_fraction_values, NavierStokesScratchData< dim >::void_fraction_gradient_values, and NavierStokesScratchData< dim >::void_fraction_values.
Member Data Documentation
average_fluid_particle_relative_velocity
template<int dim> Tensor<1, dim> NavierStokesScratchData< dim >::average_fluid_particle_relative_velocity
Definition at line 1524 of file navier_stokes_scratch_data.h.
average_particle_velocity
template<int dim> Tensor<1, dim> NavierStokesScratchData< dim >::average_particle_velocity
Definition at line 1520 of file navier_stokes_scratch_data.h.
beta_drag
template<int dim> double NavierStokesScratchData< dim >::beta_drag
Definition at line 1538 of file navier_stokes_scratch_data.h.
beta_force
template<int dim> Tensor<1, dim> NavierStokesScratchData< dim >::beta_force
Definition at line 1438 of file navier_stokes_scratch_data.h.
boundary_face_id
template<int dim> std::vector<unsigned int> NavierStokesScratchData< dim >::boundary_face_id
Definition at line 1594 of file navier_stokes_scratch_data.h.
cahn_hilliard_filter
template<int dim> std::shared_ptr<CahnHilliardFilterBase> NavierStokesScratchData< dim >::cahn_hilliard_filter
Definition at line 1565 of file navier_stokes_scratch_data.h.
cell_size
template<int dim> double NavierStokesScratchData< dim >::cell_size
Definition at line 1433 of file navier_stokes_scratch_data.h.
cell_void_fraction
template<int dim> std::vector<double> NavierStokesScratchData< dim >::cell_void_fraction
Definition at line 1531 of file navier_stokes_scratch_data.h.
cell_volume
template<int dim> double NavierStokesScratchData< dim >::cell_volume
Definition at line 1537 of file navier_stokes_scratch_data.h.
chemical_potential
template<int dim> FEValuesExtractors::Scalar NavierStokesScratchData< dim >::chemical_potential
Definition at line 1570 of file navier_stokes_scratch_data.h.
chemical_potential_cahn_hilliard_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::chemical_potential_cahn_hilliard_values
Definition at line 1562 of file navier_stokes_scratch_data.h.
components
template<int dim> std::vector<unsigned int> NavierStokesScratchData< dim >::components
Definition at line 1447 of file navier_stokes_scratch_data.h.
compressibility_multiplier
template<int dim> std::vector<double> NavierStokesScratchData< dim >::compressibility_multiplier
Definition at line 1406 of file navier_stokes_scratch_data.h.
curvature_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::curvature_values
Definition at line 1492 of file navier_stokes_scratch_data.h.
density
template<int dim> std::vector<double> NavierStokesScratchData< dim >::density
Definition at line 1376 of file navier_stokes_scratch_data.h.
density_0
template<int dim> std::vector<double> NavierStokesScratchData< dim >::density_0
Definition at line 1396 of file navier_stokes_scratch_data.h.
density_1
template<int dim> std::vector<double> NavierStokesScratchData< dim >::density_1
Definition at line 1397 of file navier_stokes_scratch_data.h.
density_at_particle_location
template<int dim> std::vector<double> NavierStokesScratchData< dim >::density_at_particle_location
Definition at line 1405 of file navier_stokes_scratch_data.h.
density_psi
template<int dim> double NavierStokesScratchData< dim >::density_psi
Definition at line 1378 of file navier_stokes_scratch_data.h.
density_psi_0
template<int dim> double NavierStokesScratchData< dim >::density_psi_0
Definition at line 1400 of file navier_stokes_scratch_data.h.
density_psi_1
template<int dim> double NavierStokesScratchData< dim >::density_psi_1
Definition at line 1401 of file navier_stokes_scratch_data.h.
density_ref
template<int dim> double NavierStokesScratchData< dim >::density_ref
Definition at line 1377 of file navier_stokes_scratch_data.h.
density_ref_0
template<int dim> double NavierStokesScratchData< dim >::density_ref_0
Definition at line 1398 of file navier_stokes_scratch_data.h.
density_ref_1
template<int dim> double NavierStokesScratchData< dim >::density_ref_1
Definition at line 1399 of file navier_stokes_scratch_data.h.
density_scale
template<int dim> double NavierStokesScratchData< dim >::density_scale
Definition at line 1402 of file navier_stokes_scratch_data.h.
div_phi_u
template<int dim> Table<2, double> NavierStokesScratchData< dim >::div_phi_u
Definition at line 1464 of file navier_stokes_scratch_data.h.
dynamic_viscosity
template<int dim> std::vector<double> NavierStokesScratchData< dim >::dynamic_viscosity
Definition at line 1379 of file navier_stokes_scratch_data.h.
dynamic_viscosity_0
template<int dim> std::vector<double> NavierStokesScratchData< dim >::dynamic_viscosity_0
Definition at line 1407 of file navier_stokes_scratch_data.h.
dynamic_viscosity_1
template<int dim> std::vector<double> NavierStokesScratchData< dim >::dynamic_viscosity_1
Definition at line 1408 of file navier_stokes_scratch_data.h.
dynamic_viscosity_for_stabilization
template<int dim> std::vector<double> NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization
Values of the dynamic viscosity used in the SUPG and PSPG stabilizations.
Definition at line 1386 of file navier_stokes_scratch_data.h.
dynamic_viscosity_for_stabilization_0
template<int dim> std::vector<double> NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization_0
Values of the dynamic viscosity used in the SUPG and PSPG stabilizations for fluid 0.
Definition at line 1420 of file navier_stokes_scratch_data.h.
dynamic_viscosity_for_stabilization_1
template<int dim> std::vector<double> NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization_1
Values of the dynamic viscosity used in the SUPG and PSPG stabilizations for fluid 1.
Definition at line 1423 of file navier_stokes_scratch_data.h.
explicit_particle_volumetric_acceleration_on_fluid
template<int dim> Tensor<1, dim> NavierStokesScratchData< dim >::explicit_particle_volumetric_acceleration_on_fluid
Definition at line 1539 of file navier_stokes_scratch_data.h.
face_div_phi_u
template<int dim> Table<3, double> NavierStokesScratchData< dim >::face_div_phi_u
Definition at line 1612 of file navier_stokes_scratch_data.h.
face_grad_phi_p
template<int dim> Table<3, Tensor<1, dim> > NavierStokesScratchData< dim >::face_grad_phi_p
Definition at line 1618 of file navier_stokes_scratch_data.h.
face_grad_phi_u
template<int dim> Table<3, Tensor<2, dim> > NavierStokesScratchData< dim >::face_grad_phi_u
Definition at line 1616 of file navier_stokes_scratch_data.h.
face_hess_phi_u
template<int dim> Table<3, Tensor<3, dim> > NavierStokesScratchData< dim >::face_hess_phi_u
Definition at line 1614 of file navier_stokes_scratch_data.h.
face_JxW
template<int dim> Table<2, double> NavierStokesScratchData< dim >::face_JxW
Definition at line 1597 of file navier_stokes_scratch_data.h.
face_laplacian_phi_u
template<int dim> Table<3, Tensor<1, dim> > NavierStokesScratchData< dim >::face_laplacian_phi_u
Definition at line 1615 of file navier_stokes_scratch_data.h.
face_n_dofs
template<int dim> unsigned int NavierStokesScratchData< dim >::face_n_dofs
Definition at line 1590 of file navier_stokes_scratch_data.h.
face_normal
template<int dim> Table<2, Tensor<1, dim> > NavierStokesScratchData< dim >::face_normal
Definition at line 1599 of file navier_stokes_scratch_data.h.
face_phi_p
template<int dim> Table<3, double> NavierStokesScratchData< dim >::face_phi_p
Definition at line 1617 of file navier_stokes_scratch_data.h.
face_phi_u
template<int dim> Table<3, Tensor<1, dim> > NavierStokesScratchData< dim >::face_phi_u
Definition at line 1613 of file navier_stokes_scratch_data.h.
face_pressure_gradients
template<int dim> std::vector<std::vector<Tensor<1, dim> > > NavierStokesScratchData< dim >::face_pressure_gradients
Definition at line 1608 of file navier_stokes_scratch_data.h.
face_pressure_values
template<int dim> std::vector<std::vector<double> > NavierStokesScratchData< dim >::face_pressure_values
Definition at line 1607 of file navier_stokes_scratch_data.h.
face_quadrature_points
template<int dim> std::vector<std::vector<Point<dim> > > NavierStokesScratchData< dim >::face_quadrature_points
Definition at line 1598 of file navier_stokes_scratch_data.h.
face_velocity_divergences
template<int dim> std::vector<std::vector<double> > NavierStokesScratchData< dim >::face_velocity_divergences
Definition at line 1604 of file navier_stokes_scratch_data.h.
face_velocity_gradients
template<int dim> std::vector<std::vector<Tensor<2, dim> > > NavierStokesScratchData< dim >::face_velocity_gradients
Definition at line 1605 of file navier_stokes_scratch_data.h.
face_velocity_laplacians
template<int dim> std::vector<std::vector<Tensor<1, dim> > > NavierStokesScratchData< dim >::face_velocity_laplacians
Definition at line 1606 of file navier_stokes_scratch_data.h.
face_velocity_values
template<int dim> std::vector<std::vector<Tensor<1, dim> > > NavierStokesScratchData< dim >::face_velocity_values
Definition at line 1603 of file navier_stokes_scratch_data.h.
fe_face_values
template<int dim> FEFaceValues<dim> NavierStokesScratchData< dim >::fe_face_values
Definition at line 1586 of file navier_stokes_scratch_data.h.
fe_values
template<int dim> FEValues<dim> NavierStokesScratchData< dim >::fe_values
Definition at line 1430 of file navier_stokes_scratch_data.h.
fe_values_cahn_hilliard
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_cahn_hilliard
Definition at line 1568 of file navier_stokes_scratch_data.h.
fe_values_curvature
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_curvature
Definition at line 1490 of file navier_stokes_scratch_data.h.
fe_values_particle_drag
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_particle_drag
Definition at line 1511 of file navier_stokes_scratch_data.h.
fe_values_particle_two_way_coupling_force
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_particle_two_way_coupling_force
Definition at line 1512 of file navier_stokes_scratch_data.h.
fe_values_particle_velocity
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_particle_velocity
Definition at line 1513 of file navier_stokes_scratch_data.h.
fe_values_projected_phase_fraction_gradient
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_projected_phase_fraction_gradient
Definition at line 1489 of file navier_stokes_scratch_data.h.
fe_values_temperature
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_temperature
Definition at line 1552 of file navier_stokes_scratch_data.h.
fe_values_vof
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_vof
Definition at line 1484 of file navier_stokes_scratch_data.h.
fe_values_void_fraction
template<int dim> std::shared_ptr<FEValues<dim> > NavierStokesScratchData< dim >::fe_values_void_fraction
Definition at line 1503 of file navier_stokes_scratch_data.h.
fields
template<int dim> std::map<field, std::vector<double> > NavierStokesScratchData< dim >::fields
Definition at line 1375 of file navier_stokes_scratch_data.h.
filter
template<int dim> std::shared_ptr<VolumeOfFluidFilterBase> NavierStokesScratchData< dim >::filter
Definition at line 1485 of file navier_stokes_scratch_data.h.
filtered_phase_gradient_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::filtered_phase_gradient_values
Definition at line 1481 of file navier_stokes_scratch_data.h.
filtered_phase_order_cahn_hilliard_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::filtered_phase_order_cahn_hilliard_values
Definition at line 1560 of file navier_stokes_scratch_data.h.
filtered_phase_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::filtered_phase_values
Definition at line 1478 of file navier_stokes_scratch_data.h.
filtered_phase_values_at_particle_location
template<int dim> std::vector<double> NavierStokesScratchData< dim >::filtered_phase_values_at_particle_location
Definition at line 1479 of file navier_stokes_scratch_data.h.
fluid_particle_relative_velocity_at_particle_location
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::fluid_particle_relative_velocity_at_particle_location
Definition at line 1523 of file navier_stokes_scratch_data.h.
fluid_pressure_gradients_at_particle_location
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::fluid_pressure_gradients_at_particle_location
Definition at line 1525 of file navier_stokes_scratch_data.h.
fluid_velocity_at_particle_location
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::fluid_velocity_at_particle_location
Definition at line 1521 of file navier_stokes_scratch_data.h.
fluid_velocity_curls_at_particle_location_2d
template<int dim> std::vector<Tensor<1, 1> > NavierStokesScratchData< dim >::fluid_velocity_curls_at_particle_location_2d
Definition at line 1527 of file navier_stokes_scratch_data.h.
fluid_velocity_curls_at_particle_location_3d
template<int dim> std::vector<Tensor<1, 3> > NavierStokesScratchData< dim >::fluid_velocity_curls_at_particle_location_3d
Definition at line 1528 of file navier_stokes_scratch_data.h.
fluid_velocity_laplacian_at_particle_location
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::fluid_velocity_laplacian_at_particle_location
Definition at line 1526 of file navier_stokes_scratch_data.h.
force
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::force
Definition at line 1439 of file navier_stokes_scratch_data.h.
gather_cahn_hilliard
template<int dim> bool NavierStokesScratchData< dim >::gather_cahn_hilliard
Scratch component for the CahnHilliard auxiliary physics
Definition at line 1557 of file navier_stokes_scratch_data.h.
gather_curvature
template<int dim> bool NavierStokesScratchData< dim >::gather_curvature
Definition at line 1488 of file navier_stokes_scratch_data.h.
gather_hessian
template<int dim> bool NavierStokesScratchData< dim >::gather_hessian
Definition at line 1584 of file navier_stokes_scratch_data.h.
gather_mortar
template<int dim> bool NavierStokesScratchData< dim >::gather_mortar
Scratch component for the mortar method
Definition at line 1575 of file navier_stokes_scratch_data.h.
gather_particle_field_project
template<int dim> bool NavierStokesScratchData< dim >::gather_particle_field_project
Definition at line 1515 of file navier_stokes_scratch_data.h.
gather_particles_information
template<int dim> bool NavierStokesScratchData< dim >::gather_particles_information
Scratch component for the particle fluid interaction auxiliary physics
Definition at line 1508 of file navier_stokes_scratch_data.h.
gather_projected_phase_fraction_gradient
template<int dim> bool NavierStokesScratchData< dim >::gather_projected_phase_fraction_gradient
Definition at line 1487 of file navier_stokes_scratch_data.h.
gather_temperature
template<int dim> bool NavierStokesScratchData< dim >::gather_temperature
Scratch component for the heat transfer
Definition at line 1545 of file navier_stokes_scratch_data.h.
gather_vof
template<int dim> bool NavierStokesScratchData< dim >::gather_vof
Scratch component for the VOF auxiliary physics
Definition at line 1475 of file navier_stokes_scratch_data.h.
gather_void_fraction
template<int dim> bool NavierStokesScratchData< dim >::gather_void_fraction
Scratch component for the void fraction auxiliary physics
Definition at line 1497 of file navier_stokes_scratch_data.h.
grad_kinematic_viscosity_shear_rate
template<int dim> std::vector<double> NavierStokesScratchData< dim >::grad_kinematic_viscosity_shear_rate
Definition at line 1388 of file navier_stokes_scratch_data.h.
grad_phi_p
template<int dim> Table<2, Tensor<1, dim> > NavierStokesScratchData< dim >::grad_phi_p
Definition at line 1470 of file navier_stokes_scratch_data.h.
grad_phi_u
template<int dim> Table<2, Tensor<2, dim> > NavierStokesScratchData< dim >::grad_phi_u
Definition at line 1468 of file navier_stokes_scratch_data.h.
hess_phi_u
template<int dim> Table<2, Tensor<3, dim> > NavierStokesScratchData< dim >::hess_phi_u
Definition at line 1466 of file navier_stokes_scratch_data.h.
interpolated_void_fraction
template<int dim> bool NavierStokesScratchData< dim >::interpolated_void_fraction
Definition at line 1509 of file navier_stokes_scratch_data.h.
is_boundary_cell
template<int dim> bool NavierStokesScratchData< dim >::is_boundary_cell
Is boundary cell indicator
Definition at line 1581 of file navier_stokes_scratch_data.h.
is_boundary_face
template<int dim> std::vector<bool> NavierStokesScratchData< dim >::is_boundary_face
Definition at line 1593 of file navier_stokes_scratch_data.h.
JxW
template<int dim> Table<1, double> NavierStokesScratchData< dim >::JxW
Definition at line 1443 of file navier_stokes_scratch_data.h.
kinematic_viscosity
template<int dim> std::vector<double> NavierStokesScratchData< dim >::kinematic_viscosity
Definition at line 1380 of file navier_stokes_scratch_data.h.
kinematic_viscosity_0
template<int dim> std::vector<double> NavierStokesScratchData< dim >::kinematic_viscosity_0
Definition at line 1409 of file navier_stokes_scratch_data.h.
kinematic_viscosity_1
template<int dim> std::vector<double> NavierStokesScratchData< dim >::kinematic_viscosity_1
Definition at line 1410 of file navier_stokes_scratch_data.h.
kinematic_viscosity_at_particle_location
template<int dim> std::vector<double> NavierStokesScratchData< dim >::kinematic_viscosity_at_particle_location
Kinematic viscosity at the particles locations. This is used to calculate the Reynolds number and the forces between the fluid and the particles.
Definition at line 1417 of file navier_stokes_scratch_data.h.
kinematic_viscosity_for_stabilization
template<int dim> std::vector<double> NavierStokesScratchData< dim >::kinematic_viscosity_for_stabilization
Values of the kinematic viscosity used in the SUPG and PSPG stabilizations.
Definition at line 1384 of file navier_stokes_scratch_data.h.
kinematic_viscosity_scale
template<int dim> double NavierStokesScratchData< dim >::kinematic_viscosity_scale
Definition at line 1381 of file navier_stokes_scratch_data.h.
kinematic_viscosity_scale_0
template<int dim> double NavierStokesScratchData< dim >::kinematic_viscosity_scale_0
Scale of the kinematic viscosity for fluid 0.
Definition at line 1412 of file navier_stokes_scratch_data.h.
kinematic_viscosity_scale_1
template<int dim> double NavierStokesScratchData< dim >::kinematic_viscosity_scale_1
Scale of the kinematic viscosity for fluid 1.
Definition at line 1414 of file navier_stokes_scratch_data.h.
laplacian_phi_u
template<int dim> Table<2, Tensor<1, dim> > NavierStokesScratchData< dim >::laplacian_phi_u
Definition at line 1467 of file navier_stokes_scratch_data.h.
mass_source
template<int dim> std::vector<double> NavierStokesScratchData< dim >::mass_source
Definition at line 1440 of file navier_stokes_scratch_data.h.
max_number_of_particles_per_cell
template<int dim> unsigned int NavierStokesScratchData< dim >::max_number_of_particles_per_cell
Definition at line 1533 of file navier_stokes_scratch_data.h.
n_dofs
template<int dim> unsigned int NavierStokesScratchData< dim >::n_dofs
Definition at line 1431 of file navier_stokes_scratch_data.h.
n_dofs_cahn_hilliard
template<int dim> unsigned int NavierStokesScratchData< dim >::n_dofs_cahn_hilliard
Definition at line 1558 of file navier_stokes_scratch_data.h.
n_dofs_heat_transfer
template<int dim> unsigned int NavierStokesScratchData< dim >::n_dofs_heat_transfer
Definition at line 1546 of file navier_stokes_scratch_data.h.
n_dofs_vof
template<int dim> unsigned int NavierStokesScratchData< dim >::n_dofs_vof
Definition at line 1476 of file navier_stokes_scratch_data.h.
n_dofs_void_fraction
template<int dim> unsigned int NavierStokesScratchData< dim >::n_dofs_void_fraction
Definition at line 1498 of file navier_stokes_scratch_data.h.
n_faces
template<int dim> unsigned int NavierStokesScratchData< dim >::n_faces
Definition at line 1588 of file navier_stokes_scratch_data.h.
n_faces_q_points
template<int dim> unsigned int NavierStokesScratchData< dim >::n_faces_q_points
Definition at line 1589 of file navier_stokes_scratch_data.h.
n_q_points
template<int dim> unsigned int NavierStokesScratchData< dim >::n_q_points
Definition at line 1432 of file navier_stokes_scratch_data.h.
number_of_particles
template<int dim> unsigned int NavierStokesScratchData< dim >::number_of_particles
Definition at line 1534 of file navier_stokes_scratch_data.h.
particle_drag_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::particle_drag_values
Definition at line 1518 of file navier_stokes_scratch_data.h.
particle_reference_location
template<int dim> std::vector<Point<dim> > NavierStokesScratchData< dim >::particle_reference_location
Definition at line 1529 of file navier_stokes_scratch_data.h.
particle_two_way_coupling_force_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::particle_two_way_coupling_force_values
Definition at line 1519 of file navier_stokes_scratch_data.h.
particle_velocity
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::particle_velocity
Definition at line 1516 of file navier_stokes_scratch_data.h.
particle_velocity_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::particle_velocity_values
Definition at line 1517 of file navier_stokes_scratch_data.h.
particle_weights
template<int dim> std::vector<double> NavierStokesScratchData< dim >::particle_weights
Definition at line 1530 of file navier_stokes_scratch_data.h.
phase_gradient_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::phase_gradient_values
Definition at line 1482 of file navier_stokes_scratch_data.h.
phase_order
template<int dim> FEValuesExtractors::Scalar NavierStokesScratchData< dim >::phase_order
Definition at line 1569 of file navier_stokes_scratch_data.h.
phase_order_cahn_hilliard_gradients
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::phase_order_cahn_hilliard_gradients
Definition at line 1561 of file navier_stokes_scratch_data.h.
phase_order_cahn_hilliard_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::phase_order_cahn_hilliard_values
Definition at line 1559 of file navier_stokes_scratch_data.h.
phase_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::phase_values
Definition at line 1477 of file navier_stokes_scratch_data.h.
phi_p
template<int dim> Table<2, double> NavierStokesScratchData< dim >::phi_p
Definition at line 1469 of file navier_stokes_scratch_data.h.
phi_u
template<int dim> Table<2, Tensor<1, dim> > NavierStokesScratchData< dim >::phi_u
Definition at line 1465 of file navier_stokes_scratch_data.h.
pic
template<int dim> Particles::ParticleHandler<dim>::particle_iterator_range NavierStokesScratchData< dim >::pic
Definition at line 1535 of file navier_stokes_scratch_data.h.
pressure
template<int dim> FEValuesExtractors::Scalar NavierStokesScratchData< dim >::pressure
Definition at line 1435 of file navier_stokes_scratch_data.h.
pressure_gradients
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::pressure_gradients
Definition at line 1458 of file navier_stokes_scratch_data.h.
pressure_scaling_factor
template<int dim> double NavierStokesScratchData< dim >::pressure_scaling_factor
Definition at line 1393 of file navier_stokes_scratch_data.h.
pressure_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::pressure_values
Definition at line 1457 of file navier_stokes_scratch_data.h.
previous_density
template<int dim> std::vector<std::vector<double> > NavierStokesScratchData< dim >::previous_density
Definition at line 1389 of file navier_stokes_scratch_data.h.
previous_phase_values
template<int dim> std::vector<std::vector<double> > NavierStokesScratchData< dim >::previous_phase_values
Definition at line 1480 of file navier_stokes_scratch_data.h.
previous_pressure_values
template<int dim> std::vector<std::vector<double> > NavierStokesScratchData< dim >::previous_pressure_values
Definition at line 1459 of file navier_stokes_scratch_data.h.
previous_temperature_gradients
template<int dim> std::vector<std::vector<Tensor<1, dim> > > NavierStokesScratchData< dim >::previous_temperature_gradients
Definition at line 1550 of file navier_stokes_scratch_data.h.
previous_temperature_values
template<int dim> std::vector<std::vector<double> > NavierStokesScratchData< dim >::previous_temperature_values
Definition at line 1548 of file navier_stokes_scratch_data.h.
previous_velocity_values
template<int dim> std::vector<std::vector<Tensor<1, dim> > > NavierStokesScratchData< dim >::previous_velocity_values
Definition at line 1460 of file navier_stokes_scratch_data.h.
previous_void_fraction_values
template<int dim> std::vector<std::vector<double> > NavierStokesScratchData< dim >::previous_void_fraction_values
Definition at line 1500 of file navier_stokes_scratch_data.h.
projected_phase_fraction_gradient_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::projected_phase_fraction_gradient_values
Definition at line 1491 of file navier_stokes_scratch_data.h.
properties_manager
template<int dim> const PhysicalPropertiesManager NavierStokesScratchData< dim >::properties_manager
Definition at line 1374 of file navier_stokes_scratch_data.h.
quadrature_points
template<int dim> std::vector<Point<dim> > NavierStokesScratchData< dim >::quadrature_points
Definition at line 1444 of file navier_stokes_scratch_data.h.
Re_particle
template<int dim> std::vector<double> NavierStokesScratchData< dim >::Re_particle
Definition at line 1532 of file navier_stokes_scratch_data.h.
rhs_force
template<int dim> std::vector<Vector<double> > NavierStokesScratchData< dim >::rhs_force
Definition at line 1437 of file navier_stokes_scratch_data.h.
rotor_linear_velocity_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::rotor_linear_velocity_values
Definition at line 1576 of file navier_stokes_scratch_data.h.
sdirk_stage_sum
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::sdirk_stage_sum
Definition at line 1461 of file navier_stokes_scratch_data.h.
sdirk_table
template<int dim> SDIRKTable NavierStokesScratchData< dim >::sdirk_table
SDIRK Butcher table with coefficients for the SDIRK time-stepping method.
Definition at line 1621 of file navier_stokes_scratch_data.h.
shear_rate
template<int dim> std::vector<double> NavierStokesScratchData< dim >::shear_rate
Definition at line 1456 of file navier_stokes_scratch_data.h.
simulation_control
template<int dim> const std::shared_ptr<SimulationControl> NavierStokesScratchData< dim >::simulation_control
Definition at line 1371 of file navier_stokes_scratch_data.h.
surface_tension
template<int dim> std::vector<double> NavierStokesScratchData< dim >::surface_tension
Definition at line 1426 of file navier_stokes_scratch_data.h.
surface_tension_gradient
template<int dim> std::vector<double> NavierStokesScratchData< dim >::surface_tension_gradient
Definition at line 1427 of file navier_stokes_scratch_data.h.
temperature_gradients
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::temperature_gradients
Definition at line 1549 of file navier_stokes_scratch_data.h.
temperature_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::temperature_values
Definition at line 1547 of file navier_stokes_scratch_data.h.
thermal_expansion
template<int dim> std::vector<double> NavierStokesScratchData< dim >::thermal_expansion
Definition at line 1387 of file navier_stokes_scratch_data.h.
thermal_expansion_0
template<int dim> std::vector<double> NavierStokesScratchData< dim >::thermal_expansion_0
Definition at line 1424 of file navier_stokes_scratch_data.h.
thermal_expansion_1
template<int dim> std::vector<double> NavierStokesScratchData< dim >::thermal_expansion_1
Definition at line 1425 of file navier_stokes_scratch_data.h.
total_particle_volume
template<int dim> double NavierStokesScratchData< dim >::total_particle_volume
Definition at line 1536 of file navier_stokes_scratch_data.h.
velocities
template<int dim> FEValuesExtractors::Vector NavierStokesScratchData< dim >::velocities
Definition at line 1434 of file navier_stokes_scratch_data.h.
velocity_divergences
template<int dim> std::vector<double> NavierStokesScratchData< dim >::velocity_divergences
Definition at line 1451 of file navier_stokes_scratch_data.h.
velocity_for_stabilization
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::velocity_for_stabilization
Definition at line 1455 of file navier_stokes_scratch_data.h.
velocity_gradients
template<int dim> std::vector<Tensor<2, dim> > NavierStokesScratchData< dim >::velocity_gradients
Definition at line 1452 of file navier_stokes_scratch_data.h.
velocity_hessians
template<int dim> std::vector<Tensor<3, dim> > NavierStokesScratchData< dim >::velocity_hessians
Definition at line 1454 of file navier_stokes_scratch_data.h.
velocity_laplacians
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::velocity_laplacians
Definition at line 1453 of file navier_stokes_scratch_data.h.
velocity_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::velocity_values
Definition at line 1450 of file navier_stokes_scratch_data.h.
void_fraction_gradient_values
template<int dim> std::vector<Tensor<1, dim> > NavierStokesScratchData< dim >::void_fraction_gradient_values
Definition at line 1501 of file navier_stokes_scratch_data.h.
void_fraction_values
template<int dim> std::vector<double> NavierStokesScratchData< dim >::void_fraction_values
Definition at line 1499 of file navier_stokes_scratch_data.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/navier_stokes_scratch_data.h
/home/runner/work/lethe/lethe/source/solvers/navier_stokes_scratch_data.cc