Lethe Open-Source Library: VOFScratchData< dim > Class Template Reference
VOFScratchData< dim > Class Template Reference
#include <vof_scratch_data.h>
Public Member Functions
VOFScratchData (const std::shared_ptr< SimulationControl > &simulation_control, const PhysicalPropertiesManager &properties_manager, const FiniteElement< dim > &fe_vof, const Quadrature< dim > &quadrature, const Quadrature< dim - 1 > &face_quadrature, const Mapping< dim > &mapping, const FiniteElement< dim > &fe_fd)
VOFScratchData (const VOFScratchData< dim > &sd)
void allocate () override
template<typename VectorType >
void reinit (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const std::vector< VectorType > &previous_solutions)
template<typename VectorType >
void reinit_internal_face (const typename DoFHandler< dim >::active_cell_iterator &cell, const unsigned int &face_no, const unsigned int &sub_face_no, const typename DoFHandler< dim >::active_cell_iterator &neighbor_cell, const unsigned int &neighbor_face_no, const unsigned int &neighbor_sub_face_no, const VectorType &current_solution)
template<typename VectorType >
void reinit_velocity (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const std::vector< VectorType > &previous_solutions, const Parameters::ALE< dim > &ale)
template<typename VectorType >
void reinit_face_velocity (const typename DoFHandler< dim >::active_cell_iterator &velocity_cell, const unsigned int &face_no, const VectorType &velocity_solution, const Parameters::ALE< dim > &ale)
Public Attributes
const std::shared_ptr< SimulationControl > simulation_control
const PhysicalPropertiesManager properties_manager
std::map< field, std::vector< double > > fields
FEValues< dim > fe_values_vof
FEInterfaceValues< dim > fe_interface_values_vof
unsigned int n_dofs
unsigned int n_interface_dofs
unsigned int n_q_points
double cell_size
std::vector< double > JxW
std::vector< Point< dim > > quadrature_points
std::vector< Point< dim > > face_quadrature_points
std::vector< double > present_phase_values
std::vector< Tensor< 1, dim > > phase_gradients
std::vector< Tensor< 1, dim > > previous_phase_gradients
std::vector< double > phase_laplacians
std::vector< std::vector< double > > previous_phase_values
std::vector< double > values_here
std::vector< double > values_there
std::vector< double > phase_value_jump
std::vector< std::vector< double > > phi
std::vector< std::vector< Tensor< 1, dim > > > grad_phi
std::vector< std::vector< Tensor< 2, dim > > > hess_phi
std::vector< std::vector< double > > laplacian_phi
FEValues< dim > fe_values_fd
FEFaceValues< dim > fe_face_values_fd
FEValuesExtractors::Vector velocities_fd
std::vector< Tensor< 1, dim > > velocity_values
std::vector< std::vector< Tensor< 1, dim > > > previous_velocity_values
std::vector< Tensor< 2, dim > > velocity_gradient_values
std::vector< double > velocity_divergences
std::vector< Tensor< 1, dim > > face_velocity_values
Detailed Description
template<int dim>
class VOFScratchData< dim >
Store the information required by the assembly procedure for a VOF free surface equation. Consequently, this class calculates the phase values (values, gradients, laplacians) and the shape method (values, gradients, laplacians) at all the gauss points for all degrees of freedom and stores it into arrays. This class serves as a separation between the evaluation at the gauss point of the variables of interest and their use in the assembly, which is carried out by the assembler methods.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 38 of file vof_scratch_data.h.
Constructor & Destructor Documentation
VOFScratchData() [1/2]
template<int dim> VOFScratchData< dim >::VOFScratchData (const std::shared_ptr< SimulationControl > & simulation_control, const PhysicalPropertiesManager & properties_manager, const FiniteElement< dim > & fe_vof, const Quadrature< dim > & quadrature, const Quadrature< dim - 1 > & face_quadrature, const Mapping< dim > & mapping, const FiniteElement< dim > & fe_fd) inline
Constructor. The constructor creates the fe_values that will be used to fill the member variables of the scratch. It also allocated the necessary memory for all member variables. However, it does not do any evaluation, since this needs to be done at the cell level.
Parameters
simulation_control The SimulationControl object that holds information related to the control of the steady-state or transient simulation. This is used to extrapolate velocity solutions in time for transient simulation.
properties_manager Manager to calculate the physical properties.
fe_vof The FESystem used to solve the VOF equations.
quadrature The quadrature to use for the assembly within the cells.
face_quadrature The quadrature to use for the assembly on faces.
mapping The mapping of the domain in which the Navier-Stokes equations are solved.
fe_fd The FESystem used to solve the Fluid Dynamics equations.
Definition at line 66 of file vof_scratch_data.h.
References VOFScratchData< dim >::allocate().
VOFScratchData() [2/2]
template<int dim> VOFScratchData< dim >::VOFScratchData (const VOFScratchData< dim > & sd) inline
Copy Constructor. Same as the main constructor. This constructor only uses the other scratch to build the FeValues, it does not copy the content of the other scratch into itself since, by definition of the WorkStream mechanism it is assumed that the content of the scratch will be reset on a cell basis.
Parameters
sd The scratch data to be copied
Definition at line 101 of file vof_scratch_data.h.
References VOFScratchData< dim >::allocate().
Member Function Documentation
allocate()
template<int dim> void VOFScratchData< dim >::allocate () override virtual
Allocates the memory for the scratch.
This method allocates the necessary memory for all members of the scratch
Implements PhysicsScratchDataBase.
Definition at line 10 of file vof_scratch_data.cc.
References maximum_number_of_previous_solutions().
reinit()
template<int dim> template<typename VectorType > void VOFScratchData< dim >::reinit (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const std::vector< VectorType > & previous_solutions) inline
Reinitialize the content of the scratch.
Using the FeValues and the content of the solutions and previous solutions, fills all of the class member of the scratch
Template Parameters
VectorType The Vector type used for the solvers
Parameters
[in] cell The cell over which the assembly is being carried. This cell must be compatible with the FE which is used to fill the FeValues.
[in] current_solution The present value of the solution for the VOF.
[in] previous_solutions The solutions at the previous time steps.
Definition at line 154 of file vof_scratch_data.h.
References VOFScratchData< dim >::cell_size, compute_cell_measure_with_JxW(), VOFScratchData< dim >::fe_values_vof, VOFScratchData< dim >::grad_phi, VOFScratchData< dim >::hess_phi, VOFScratchData< dim >::JxW, VOFScratchData< dim >::laplacian_phi, VOFScratchData< dim >::n_dofs, VOFScratchData< dim >::n_q_points, VOFScratchData< dim >::phase_gradients, VOFScratchData< dim >::phase_laplacians, VOFScratchData< dim >::phi, VOFScratchData< dim >::present_phase_values, VOFScratchData< dim >::previous_phase_gradients, VOFScratchData< dim >::previous_phase_values, and VOFScratchData< dim >::quadrature_points.
reinit_face_velocity()
template<int dim> template<typename VectorType > void VOFScratchData< dim >::reinit_face_velocity (const typename DoFHandler< dim >::active_cell_iterator & velocity_cell, const unsigned int & face_no, const VectorType & velocity_solution, const Parameters::ALE< dim > & ale) inline
Reinitialize the content of the scratch regarding the velocity for internal/boundary faces. The velocity is inherently assumed to have been solved using a CG scheme.
Parameters
[in] cell The cell over which the assembly is being carried.
[in] face_no The face index associated with the cell
[in] velocity_solution The present value of the velocity solution.
Definition at line 349 of file vof_scratch_data.h.
References Parameters::ALE< dim >::enabled(), VOFScratchData< dim >::face_quadrature_points, VOFScratchData< dim >::face_velocity_values, VOFScratchData< dim >::fe_face_values_fd, VOFScratchData< dim >::velocities_fd, and Parameters::ALE< dim >::velocity.
reinit_internal_face()
template<int dim> template<typename VectorType > void VOFScratchData< dim >::reinit_internal_face (const typename DoFHandler< dim >::active_cell_iterator & cell, const unsigned int & face_no, const unsigned int & sub_face_no, const typename DoFHandler< dim >::active_cell_iterator & neighbor_cell, const unsigned int & neighbor_face_no, const unsigned int & neighbor_sub_face_no, const VectorType & current_solution) inline
Reinitialize the content of the scratch for the internal faces. This is only used for the DG assemblers.
Parameters
[in] cell The cell over which the assembly is being carried.
[in] face_no The face index associated with the cell
[in] sub_face_no The subface index associated with the face
[in] neighbor_cell The neighboring cell
[in] neighbor_face_no The face index associated with the neighboring cell
[in] neighbor_sub_face_no The subface index associated with the neighboring cell
[in] current_solution The present value of the solution.
Definition at line 220 of file vof_scratch_data.h.
References VOFScratchData< dim >::face_quadrature_points, VOFScratchData< dim >::fe_interface_values_vof, VOFScratchData< dim >::n_interface_dofs, VOFScratchData< dim >::phase_value_jump, VOFScratchData< dim >::values_here, and VOFScratchData< dim >::values_there.
reinit_velocity()
template<int dim> template<typename VectorType > void VOFScratchData< dim >::reinit_velocity (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const std::vector< VectorType > & previous_solutions, const Parameters::ALE< dim > & ale) inline
Reinitialize the velocity, calculated by the Fluid Dynamics.
Template Parameters
VectorType The Vector type used for the solvers
Parameters
cell The cell for which the velocity is reinitialized This cell must be compatible with the Fluid Dynamics FE
current_solution The present value of the solution for \([u,p]\)
previous_solutions Vector of \(n\) VectorType containers of previous fluid dynamic solutions (\([u,p]\)). \(n\) depends on the BDF scheme selected for time-stepping.
ale ALE parameters
Definition at line 272 of file vof_scratch_data.h.
References bdf_extrapolate(), Parameters::ALE< dim >::enabled(), VOFScratchData< dim >::fe_values_fd, is_bdf(), VOFScratchData< dim >::n_q_points, number_of_previous_solutions(), VOFScratchData< dim >::previous_velocity_values, VOFScratchData< dim >::quadrature_points, VOFScratchData< dim >::simulation_control, VOFScratchData< dim >::velocities_fd, Parameters::ALE< dim >::velocity, VOFScratchData< dim >::velocity_divergences, VOFScratchData< dim >::velocity_gradient_values, and VOFScratchData< dim >::velocity_values.
Member Data Documentation
cell_size
template<int dim> double VOFScratchData< dim >::cell_size
Definition at line 397 of file vof_scratch_data.h.
face_quadrature_points
template<int dim> std::vector<Point<dim> > VOFScratchData< dim >::face_quadrature_points
Definition at line 402 of file vof_scratch_data.h.
face_velocity_values
template<int dim> std::vector<Tensor<1, dim> > VOFScratchData< dim >::face_velocity_values
Definition at line 438 of file vof_scratch_data.h.
fe_face_values_fd
template<int dim> FEFaceValues<dim> VOFScratchData< dim >::fe_face_values_fd
Definition at line 428 of file vof_scratch_data.h.
fe_interface_values_vof
template<int dim> FEInterfaceValues<dim> VOFScratchData< dim >::fe_interface_values_vof
Definition at line 393 of file vof_scratch_data.h.
fe_values_fd
template<int dim> FEValues<dim> VOFScratchData< dim >::fe_values_fd
Scratch component for the Navier-Stokes component
Definition at line 427 of file vof_scratch_data.h.
fe_values_vof
template<int dim> FEValues<dim> VOFScratchData< dim >::fe_values_vof
Definition at line 392 of file vof_scratch_data.h.
fields
template<int dim> std::map<field, std::vector<double> > VOFScratchData< dim >::fields
Definition at line 389 of file vof_scratch_data.h.
grad_phi
template<int dim> std::vector<std::vector<Tensor<1, dim> > > VOFScratchData< dim >::grad_phi
Definition at line 419 of file vof_scratch_data.h.
hess_phi
template<int dim> std::vector<std::vector<Tensor<2, dim> > > VOFScratchData< dim >::hess_phi
Definition at line 420 of file vof_scratch_data.h.
JxW
template<int dim> std::vector<double> VOFScratchData< dim >::JxW
Definition at line 400 of file vof_scratch_data.h.
laplacian_phi
template<int dim> std::vector<std::vector<double> > VOFScratchData< dim >::laplacian_phi
Definition at line 421 of file vof_scratch_data.h.
n_dofs
template<int dim> unsigned int VOFScratchData< dim >::n_dofs
Definition at line 394 of file vof_scratch_data.h.
n_interface_dofs
template<int dim> unsigned int VOFScratchData< dim >::n_interface_dofs
Definition at line 395 of file vof_scratch_data.h.
n_q_points
template<int dim> unsigned int VOFScratchData< dim >::n_q_points
Definition at line 396 of file vof_scratch_data.h.
phase_gradients
template<int dim> std::vector<Tensor<1, dim> > VOFScratchData< dim >::phase_gradients
Definition at line 406 of file vof_scratch_data.h.
phase_laplacians
template<int dim> std::vector<double> VOFScratchData< dim >::phase_laplacians
Definition at line 409 of file vof_scratch_data.h.
phase_value_jump
template<int dim> std::vector<double> VOFScratchData< dim >::phase_value_jump
Definition at line 415 of file vof_scratch_data.h.
phi
template<int dim> std::vector<std::vector<double> > VOFScratchData< dim >::phi
Definition at line 418 of file vof_scratch_data.h.
present_phase_values
template<int dim> std::vector<double> VOFScratchData< dim >::present_phase_values
Definition at line 405 of file vof_scratch_data.h.
previous_phase_gradients
template<int dim> std::vector<Tensor<1, dim> > VOFScratchData< dim >::previous_phase_gradients
Definition at line 407 of file vof_scratch_data.h.
previous_phase_values
template<int dim> std::vector<std::vector<double> > VOFScratchData< dim >::previous_phase_values
Definition at line 410 of file vof_scratch_data.h.
previous_velocity_values
template<int dim> std::vector<std::vector<Tensor<1, dim> > > VOFScratchData< dim >::previous_velocity_values
Definition at line 433 of file vof_scratch_data.h.
properties_manager
template<int dim> const PhysicalPropertiesManager VOFScratchData< dim >::properties_manager
Definition at line 388 of file vof_scratch_data.h.
quadrature_points
template<int dim> std::vector<Point<dim> > VOFScratchData< dim >::quadrature_points
Definition at line 401 of file vof_scratch_data.h.
simulation_control
template<int dim> const std::shared_ptr<SimulationControl> VOFScratchData< dim >::simulation_control
Definition at line 385 of file vof_scratch_data.h.
values_here
template<int dim> std::vector<double> VOFScratchData< dim >::values_here
Definition at line 413 of file vof_scratch_data.h.
values_there
template<int dim> std::vector<double> VOFScratchData< dim >::values_there
Definition at line 414 of file vof_scratch_data.h.
velocities_fd
template<int dim> FEValuesExtractors::Vector VOFScratchData< dim >::velocities_fd
Definition at line 430 of file vof_scratch_data.h.
velocity_divergences
template<int dim> std::vector<double> VOFScratchData< dim >::velocity_divergences
Definition at line 435 of file vof_scratch_data.h.
velocity_gradient_values
template<int dim> std::vector<Tensor<2, dim> > VOFScratchData< dim >::velocity_gradient_values
Definition at line 434 of file vof_scratch_data.h.
velocity_values
template<int dim> std::vector<Tensor<1, dim> > VOFScratchData< dim >::velocity_values
Definition at line 432 of file vof_scratch_data.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/vof_scratch_data.h
/home/runner/work/lethe/lethe/source/solvers/vof_scratch_data.cc