Lethe Open-Source Library: FluidDynamicsNitsche< dim, spacedim > Class Template Reference
FluidDynamicsNitsche< dim, spacedim > Class Template Reference
#include <fluid_dynamics_nitsche.h>
Public Member Functions
FluidDynamicsNitsche (SimulationParameters< spacedim > &nsparam)
virtual void solve () override
Public Member Functions inherited from FluidDynamicsMatrixBased< dim >
FluidDynamicsMatrixBased (SimulationParameters< dim > &nsparam)
~FluidDynamicsMatrixBased ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
template<bool assemble_matrix>
void assemble_nitsche_restriction ()
Tensor< 1, spacedim > calculate_forces_on_solid (const unsigned int i_solid)
Tensor< 1, 3 > calculate_torque_on_solid (const unsigned int i_solid)
Tensor< 1, 3 > calculate_torque_on_solid ()
void postprocess_solid_forces (const unsigned int i_solid, bool first_solid_forces)
void postprocess_solid_torques (const unsigned int i_solid, bool first_solid_torques)
virtual void assemble_system_matrix () override
virtual void assemble_system_rhs () override
void assemble_matrix_and_rhs ()
void assemble_rhs ()
void output_solid_particles (const unsigned int i_solid)
void output_solid_triangulation (const unsigned int i_solid)
virtual void refine_mesh () override
virtual void write_checkpoint () override
virtual void read_checkpoint () override
Tensor< 1, 3 > calculate_forces_on_solid (const unsigned int i_solid)
Private Attributes
std::vector< std::shared_ptr< SolidBase< dim, spacedim > > > solids
std::vector< PVDHandler > pvdhandler_solid_triangulation
std::vector< PVDHandler > pvdhandler_solid_particles
std::vector< TableHandler > solid_forces_table
std::vector< TableHandler > solid_torques_table
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Protected Member Functions inherited from FluidDynamicsMatrixBased< dim >
virtual void setup_dofs_fd () override
virtual void set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false) override
virtual void update_multiphysics_time_average_solution () override
void setup_preconditioner () override
void define_dynamic_zero_constraints ()
void update_mortar_configuration ()
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
virtual void setup_assemblers ()
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data)
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data)
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Protected Member Functions inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual GlobalVectorType & get_evaluation_point () override
virtual GlobalVectorType & get_local_evaluation_point () override
virtual GlobalVectorType & get_newton_update () override
virtual GlobalVectorType & get_present_solution () override
virtual GlobalVectorType & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void setup_dofs ()
virtual void set_initial_condition (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void postprocess_fd (bool first_iteration)
virtual void update_solutions_for_multiphysics ()
virtual void update_solutions_for_fluid_dynamics ()
void postprocessing_forces (const GlobalVectorType &evaluation_point)
void postprocessing_torques (const GlobalVectorType &evaluation_point)
virtual void dynamic_flow_control ()
virtual void multi_stage_preresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method)
virtual void multi_stage_postresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method, double time_step)
virtual void update_multi_stage_solution (double time_step)
virtual void iterate ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
void refine_mesh_kelly ()
void refine_mesh_uniform ()
void transfer_solution (SolutionTransfer< dim, GlobalVectorType > &solution_transfer, std::vector< SolutionTransfer< dim, GlobalVectorType > > &previous_solutions_transfer)
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void reinit_mortar_operators ()
std::shared_ptr< Mapping< dim > > get_mapping ()
void rotate_rotor_mapping (const bool is_first)
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
void gather_output_results (const GlobalVectorType &solution, std::vector< OutputStruct< dim, GlobalVectorType > > &solution_output_structs)
void write_output_results (const GlobalVectorType &solution)
virtual void output_field_hook (DataOut< dim > &)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
GlobalVectorType init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes inherited from FluidDynamicsMatrixBased< dim >
TrilinosWrappers::SparseMatrix system_matrix
Protected Attributes inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
GlobalVectorType present_solution
GlobalVectorType system_rhs
std::vector< GlobalVectorType > previous_solutions
SDIRKVectors sdirk_vectors
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::shared_ptr< MortarManagerCircle< dim > > mortar_manager
std::shared_ptr< CouplingOperator< dim, double > > mortar_coupling_operator
std::shared_ptr< NavierStokesCouplingEvaluation< dim, double > > mortar_coupling_evaluator
std::shared_ptr< MappingQCache< dim > > mapping_cache
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, GlobalVectorType, IndexSet > > average_velocities
GlobalVectorType average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Detailed Description
template<int dim, int spacedim = dim>
class FluidDynamicsNitsche< dim, spacedim >
A solver class for the Navier-Stokes equation using GLS stabilization and Nitsche immersed boundary method
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Author
Bruno Blais, 2019
Definition at line 28 of file fluid_dynamics_nitsche.h.
Constructor & Destructor Documentation
FluidDynamicsNitsche()
template<int dim, int spacedim> FluidDynamicsNitsche< dim, spacedim >::FluidDynamicsNitsche (SimulationParameters< spacedim > & nsparam)
Definition at line 24 of file fluid_dynamics_nitsche.cc.
References FluidDynamicsNitsche< dim, spacedim >::pvdhandler_solid_particles, FluidDynamicsNitsche< dim, spacedim >::pvdhandler_solid_triangulation, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, FluidDynamicsNitsche< dim, spacedim >::solid_forces_table, FluidDynamicsNitsche< dim, spacedim >::solid_torques_table, and FluidDynamicsNitsche< dim, spacedim >::solids.
Member Function Documentation
assemble_matrix_and_rhs()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::assemble_matrix_and_rhs () private
Same as in fluid_dynamics_matrix_based, but calls assemble_nitsche_restriction() when global matrix and rhs are assembled.
Deprecated:
This function is to be deprecated when the new assembly mechanism is integrated to this solver
Definition at line 893 of file fluid_dynamics_nitsche.cc.
References FluidDynamicsMatrixBased< dim >::assemble_system_matrix(), and FluidDynamicsMatrixBased< dim >::assemble_system_rhs().
assemble_nitsche_restriction()
template<int dim, int spacedim> template<bool assemble_matrix> void FluidDynamicsNitsche< dim, spacedim >::assemble_nitsche_restriction () private
Adds the nitsche restriction to the global matrix and global rhs on the cells surrounding the immersed solid.
Definition at line 50 of file fluid_dynamics_nitsche.cc.
References Parameters::SimulationControl::steady, and velocity.
assemble_rhs()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::assemble_rhs () private
Same as in fluid_dynamics_matrix_based, but calls assemble_nitsche_restriction() when rhs is assembled.
Deprecated:
This function is to be deprecated when the new assembly mechanism is integrated to this solver
Definition at line 904 of file fluid_dynamics_nitsche.cc.
References FluidDynamicsMatrixBased< dim >::assemble_system_rhs().
assemble_system_matrix()
template<int dim, int spacedim = dim> virtual void FluidDynamicsNitsche< dim, spacedim >::assemble_system_matrix () inline override private virtual
Call for the assembly of the matrix.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 87 of file fluid_dynamics_nitsche.h.
References FluidDynamicsNitsche< dim, spacedim >::assemble_matrix_and_rhs().
assemble_system_rhs()
template<int dim, int spacedim = dim> virtual void FluidDynamicsNitsche< dim, spacedim >::assemble_system_rhs () inline override private virtual
Call for the assembly of the right-hand side.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 96 of file fluid_dynamics_nitsche.h.
References FluidDynamicsNitsche< dim, spacedim >::assemble_rhs().
calculate_forces_on_solid() [1/2]
template<int dim, int spacedim> Tensor< 1, spacedim > FluidDynamicsNitsche< dim, spacedim >::calculate_forces_on_solid (const unsigned int i_solid) private
Calculates the force due to the fluid motion on the solid.
Returns
Tensor of forces on the solid
Definition at line 309 of file fluid_dynamics_nitsche.cc.
References velocity.
calculate_forces_on_solid() [2/2]
Tensor< 1, 3 > FluidDynamicsNitsche< 2, 3 >::calculate_forces_on_solid (const unsigned int i_solid) private
Definition at line 222 of file fluid_dynamics_nitsche.cc.
References pressure.
calculate_torque_on_solid() [1/2]
template<int dim, int spacedim = dim> Tensor< 1, 3 > FluidDynamicsNitsche< dim, spacedim >::calculate_torque_on_solid () private
Calculates the torque due to the fluid motion on the solid.
Returns
Tensor of torque on the solid. This is always a 3D tensor even in 2D
calculate_torque_on_solid() [2/2]
template<int dim, int spacedim> Tensor< 1, 3 > FluidDynamicsNitsche< dim, spacedim >::calculate_torque_on_solid (const unsigned int i_solid) private
Calculates the torque due to the fluid motion on the solid.
Returns
Tensor of torque on the solid. This is always a 3D tensor even in 2D
Definition at line 384 of file fluid_dynamics_nitsche.cc.
References velocity.
output_solid_particles()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::output_solid_particles (const unsigned int i_solid) private
Outputs a vtu file for each output frequency of the particles.
Definition at line 776 of file fluid_dynamics_nitsche.cc.
output_solid_triangulation()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::output_solid_triangulation (const unsigned int i_solid) private
Outputs a vtu file for each output frequency of the solid triangulation.
Definition at line 804 of file fluid_dynamics_nitsche.cc.
postprocess_solid_forces()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::postprocess_solid_forces (const unsigned int i_solid, bool first_solid_forces) private
Post-process for forces on solid after an iteration.
Parameters
i_solid is the solid index
first_solid_forces is a boolean set to true for the first call of this method, used for table output formatting
Definition at line 481 of file fluid_dynamics_nitsche.cc.
References make_table_scalars_tensors(), and Parameters::verbose.
postprocess_solid_torques()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::postprocess_solid_torques (const unsigned int i_solid, bool first_solid_torques) private
Post-process for torques on solid after an iteration.
Parameters
i_solid is the solid index
first_solid_torques is a boolean set to true for the first call of this method, used for table output formatting
Definition at line 566 of file fluid_dynamics_nitsche.cc.
References make_table_scalars_tensors(), and Parameters::verbose.
read_checkpoint()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::read_checkpoint () override private virtual
Read a gls_nitsche simulation checkpoint and initiate simulation restart.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 954 of file fluid_dynamics_nitsche.cc.
References fill_table_from_file(), and NavierStokesBase< dim, GlobalVectorType, IndexSet >::read_checkpoint().
refine_mesh()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::refine_mesh () override private virtual
Allow the refinement of the mesh according to one of the 2 methods proposed. Overrides the regular mesh adaptation by ensuring that the Nitsche solids are prepared for adaptation.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 852 of file fluid_dynamics_nitsche.cc.
References Parameters::MeshAdaptation::kelly, Parameters::MeshAdaptation::none, and Parameters::MeshAdaptation::uniform.
solve()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::solve () override virtual
solve Solves the Navier-Stokes problem
This functions solves the problem defined by the Navier-Stokes parameter by iterating through time or through the mesh refinements.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 650 of file fluid_dynamics_nitsche.cc.
References read_mesh_and_manifolds().
write_checkpoint()
template<int dim, int spacedim> void FluidDynamicsNitsche< dim, spacedim >::write_checkpoint () override private virtual
Write a gls_nitsche simulation checkpointing to allow for gls_nitsche simulation restart.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 913 of file fluid_dynamics_nitsche.cc.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::write_checkpoint().
Member Data Documentation
pvdhandler_solid_particles
template<int dim, int spacedim = dim> std::vector<PVDHandler> FluidDynamicsNitsche< dim, spacedim >::pvdhandler_solid_particles private
Definition at line 152 of file fluid_dynamics_nitsche.h.
pvdhandler_solid_triangulation
template<int dim, int spacedim = dim> std::vector<PVDHandler> FluidDynamicsNitsche< dim, spacedim >::pvdhandler_solid_triangulation private
Definition at line 151 of file fluid_dynamics_nitsche.h.
solid_forces_table
template<int dim, int spacedim = dim> std::vector<TableHandler> FluidDynamicsNitsche< dim, spacedim >::solid_forces_table private
Definition at line 154 of file fluid_dynamics_nitsche.h.
solid_torques_table
template<int dim, int spacedim = dim> std::vector<TableHandler> FluidDynamicsNitsche< dim, spacedim >::solid_torques_table private
Definition at line 155 of file fluid_dynamics_nitsche.h.
solids
template<int dim, int spacedim = dim> std::vector<std::shared_ptr<SolidBase<dim, spacedim> > > FluidDynamicsNitsche< dim, spacedim >::solids private
Definition at line 150 of file fluid_dynamics_nitsche.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/fluid_dynamics_nitsche.h
/home/runner/work/lethe/lethe/source/solvers/fluid_dynamics_nitsche.cc