Lethe Open-Source Library: SimulationParameters< dim > Class Template Reference
SimulationParameters< dim > Class Template Reference
#include <simulation_parameters.h>
Public Member Functions
void declare (ParameterHandler &prm, Parameters::SizeOfSubsections size_of_subsections)
void parse (ParameterHandler &prm)
bool no_fluid_fluid_interaction_error (std::vector< Parameters::MaterialInteractions > &material_interactions)
bool is_constant_surface_tension_model (std::vector< Parameters::MaterialInteractions > &material_interactions)
Public Attributes
Parameters::Testing test
std::map< PhysicsID, Parameters::LinearSolver > linear_solver
std::map< PhysicsID, Parameters::NonLinearSolver > non_linear_solver
Parameters::MeshAdaptation mesh_adaptation
Parameters::Mesh mesh
Parameters::Dimensionality dimensionality
std::shared_ptr< Parameters::MeshBoxRefinement > mesh_box_refinement
std::shared_ptr< Parameters::Nitsche< dim > > nitsche
Parameters::SimulationControl simulation_control
Parameters::Timer timer
Parameters::FEM fem_parameters
Parameters::Forces forces_parameters
std::shared_ptr< Parameters::Laser< dim > > laser_parameters
Parameters::PostProcessing post_processing
Parameters::Restart restart_parameters
Parameters::Manifolds manifolds_parameters
BoundaryConditions::NSBoundaryConditions< dim > boundary_conditions
BoundaryConditions::HTBoundaryConditions< dim > boundary_conditions_ht
BoundaryConditions::TracerBoundaryConditions< dim > boundary_conditions_tracer
BoundaryConditions::VOFBoundaryConditions< dim > boundary_conditions_vof
BoundaryConditions::CahnHilliardBoundaryConditions< dim > boundary_conditions_cahn_hilliard
Parameters::InitialConditions< dim > * initial_condition
AnalyticalSolutions::AnalyticalSolution< dim > * analytical_solution
SourceTerms::SourceTerm< dim > source_term
Parameters::VelocitySource velocity_sources
std::shared_ptr< Parameters::IBParticles< dim > > particlesParameters
Parameters::DynamicFlowControl flow_control
Parameters::Multiphysics multiphysics
Parameters::ConstrainSolidDomain< dim > constrain_solid_domain
Parameters::Stabilization stabilization
Parameters::ALE< dim > ale
Parameters::Evaporation evaporation
Parameters::TracerDriftVelocity< dim > tracer_drift_velocity
PhysicalPropertiesManager physical_properties_manager
Private Attributes
Parameters::PhysicalProperties physical_properties
std::vector< std::string > physics_names
Detailed Description
template<int dim>
class SimulationParameters< dim >
Definition at line 22 of file simulation_parameters.h.
Member Function Documentation
declare()
template<int dim> void SimulationParameters< dim >::declare (ParameterHandler & prm, Parameters::SizeOfSubsections size_of_subsections) inline
Definition at line 65 of file simulation_parameters.h.
References SimulationParameters< dim >::ale, SimulationParameters< dim >::analytical_solution, Parameters::SizeOfSubsections::boundary_conditions, SimulationParameters< dim >::boundary_conditions, SimulationParameters< dim >::boundary_conditions_cahn_hilliard, SimulationParameters< dim >::boundary_conditions_ht, SimulationParameters< dim >::boundary_conditions_tracer, SimulationParameters< dim >::boundary_conditions_vof, SimulationParameters< dim >::constrain_solid_domain, Parameters::Dimensionality::declare_parameters(), Parameters::SimulationControl::declare_parameters(), Parameters::PhysicalProperties::declare_parameters(), Parameters::Stabilization::declare_parameters(), Parameters::Timer::declare_parameters(), Parameters::Forces::declare_parameters(), Parameters::PostProcessing::declare_parameters(), Parameters::FEM::declare_parameters(), Parameters::Mesh::declare_parameters(), Parameters::MeshAdaptation::declare_parameters(), Parameters::Testing::declare_parameters(), Parameters::Restart::declare_parameters(), Parameters::VelocitySource::declare_parameters(), Parameters::DynamicFlowControl::declare_parameters(), Parameters::Evaporation::declare_parameters(), Parameters::Multiphysics::declare_parameters(), Parameters::NonLinearSolver::declare_parameters(), Parameters::LinearSolver::declare_parameters(), Parameters::Manifolds::declare_parameters(), SimulationParameters< dim >::dimensionality, SimulationParameters< dim >::initial_condition, SimulationParameters< dim >::laser_parameters, Parameters::SizeOfSubsections::manifolds, SimulationParameters< dim >::manifolds_parameters, SimulationParameters< dim >::mesh_box_refinement, SimulationParameters< dim >::multiphysics, SimulationParameters< dim >::nitsche, SimulationParameters< dim >::particlesParameters, SimulationParameters< dim >::physical_properties, SimulationParameters< dim >::physics_names, SimulationParameters< dim >::source_term, and SimulationParameters< dim >::tracer_drift_velocity.
is_constant_surface_tension_model()
template<int dim> bool SimulationParameters< dim >::is_constant_surface_tension_model (std::vector< Parameters::MaterialInteractions > & material_interactions) inline
Definition at line 447 of file simulation_parameters.h.
References Parameters::MaterialInteractions::constant.
no_fluid_fluid_interaction_error()
template<int dim> bool SimulationParameters< dim >::no_fluid_fluid_interaction_error (std::vector< Parameters::MaterialInteractions > & material_interactions) inline
Definition at line 430 of file simulation_parameters.h.
References fluid_fluid.
parse()
template<int dim> void SimulationParameters< dim >::parse (ParameterHandler & prm) inline
Definition at line 135 of file simulation_parameters.h.
References SimulationParameters< dim >::ale, SimulationParameters< dim >::analytical_solution, SimulationParameters< dim >::boundary_conditions, SimulationParameters< dim >::boundary_conditions_cahn_hilliard, SimulationParameters< dim >::boundary_conditions_ht, SimulationParameters< dim >::boundary_conditions_tracer, SimulationParameters< dim >::boundary_conditions_vof, Parameters::Multiphysics::cahn_hilliard, SimulationParameters< dim >::constrain_solid_domain, SimulationParameters< dim >::dimensionality, Parameters::VOF_SurfaceTensionForce::enable, Parameters::VOF_SurfaceTensionForce::enable_marangoni_effect, SimulationParameters< dim >::evaporation, SimulationParameters< dim >::fem_parameters, SimulationParameters< dim >::flow_control, Parameters::fluid1, SimulationParameters< dim >::forces_parameters, PhysicalPropertiesManager::get_number_of_fluids(), get_physics_id(), Parameters::Multiphysics::heat_transfer, SimulationParameters< dim >::initial_condition, PhysicalPropertiesManager::initialize(), SimulationParameters< dim >::is_constant_surface_tension_model(), SimulationParameters< dim >::laser_parameters, SimulationParameters< dim >::linear_solver, SimulationParameters< dim >::manifolds_parameters, Parameters::PhysicalProperties::material_interactions, SimulationParameters< dim >::mesh, SimulationParameters< dim >::mesh_adaptation, SimulationParameters< dim >::mesh_box_refinement, SimulationParameters< dim >::multiphysics, SimulationParameters< dim >::nitsche, SimulationParameters< dim >::no_fluid_fluid_interaction_error(), SimulationParameters< dim >::non_linear_solver, Parameters::PhysicalProperties::number_of_fluids, Parameters::PhysicalProperties::number_of_material_interactions, Parameters::Dimensionality::parse_parameters(), Parameters::Manifolds::parse_parameters(), Parameters::SimulationControl::parse_parameters(), Parameters::Stabilization::parse_parameters(), Parameters::Timer::parse_parameters(), Parameters::Forces::parse_parameters(), Parameters::PostProcessing::parse_parameters(), Parameters::FEM::parse_parameters(), Parameters::Mesh::parse_parameters(), Parameters::MeshAdaptation::parse_parameters(), Parameters::Testing::parse_parameters(), Parameters::Restart::parse_parameters(), Parameters::VelocitySource::parse_parameters(), Parameters::DynamicFlowControl::parse_parameters(), Parameters::Evaporation::parse_parameters(), Parameters::Multiphysics::parse_parameters(), Parameters::PhysicalProperties::parse_parameters(), SimulationParameters< dim >::particlesParameters, SimulationParameters< dim >::physical_properties, SimulationParameters< dim >::physical_properties_manager, SimulationParameters< dim >::physics_names, SimulationParameters< dim >::post_processing, Parameters::PostProcessing::postprocessed_fluid, SimulationParameters< dim >::restart_parameters, SimulationParameters< dim >::simulation_control, SimulationParameters< dim >::source_term, SimulationParameters< dim >::stabilization, Parameters::VOF::surface_tension_force, SimulationParameters< dim >::test, SimulationParameters< dim >::timer, SimulationParameters< dim >::tracer_drift_velocity, SimulationParameters< dim >::velocity_sources, Parameters::Multiphysics::VOF, and Parameters::Multiphysics::vof_parameters.
Member Data Documentation
ale
template<int dim> Parameters::ALE<dim> SimulationParameters< dim >::ale
Definition at line 56 of file simulation_parameters.h.
analytical_solution
template<int dim> AnalyticalSolutions::AnalyticalSolution<dim>* SimulationParameters< dim >::analytical_solution
Definition at line 48 of file simulation_parameters.h.
boundary_conditions
template<int dim> BoundaryConditions::NSBoundaryConditions<dim> SimulationParameters< dim >::boundary_conditions
Definition at line 41 of file simulation_parameters.h.
boundary_conditions_cahn_hilliard
template<int dim> BoundaryConditions::CahnHilliardBoundaryConditions<dim> SimulationParameters< dim >::boundary_conditions_cahn_hilliard
Definition at line 46 of file simulation_parameters.h.
boundary_conditions_ht
template<int dim> BoundaryConditions::HTBoundaryConditions<dim> SimulationParameters< dim >::boundary_conditions_ht
Definition at line 42 of file simulation_parameters.h.
boundary_conditions_tracer
template<int dim> BoundaryConditions::TracerBoundaryConditions<dim> SimulationParameters< dim >::boundary_conditions_tracer
Definition at line 43 of file simulation_parameters.h.
boundary_conditions_vof
template<int dim> BoundaryConditions::VOFBoundaryConditions<dim> SimulationParameters< dim >::boundary_conditions_vof
Definition at line 44 of file simulation_parameters.h.
constrain_solid_domain
template<int dim> Parameters::ConstrainSolidDomain<dim> SimulationParameters< dim >::constrain_solid_domain
Definition at line 54 of file simulation_parameters.h.
dimensionality
template<int dim> Parameters::Dimensionality SimulationParameters< dim >::dimensionality
Definition at line 30 of file simulation_parameters.h.
evaporation
template<int dim> Parameters::Evaporation SimulationParameters< dim >::evaporation
Definition at line 57 of file simulation_parameters.h.
fem_parameters
template<int dim> Parameters::FEM SimulationParameters< dim >::fem_parameters
Definition at line 35 of file simulation_parameters.h.
flow_control
template<int dim> Parameters::DynamicFlowControl SimulationParameters< dim >::flow_control
Definition at line 52 of file simulation_parameters.h.
forces_parameters
template<int dim> Parameters::Forces SimulationParameters< dim >::forces_parameters
Definition at line 36 of file simulation_parameters.h.
initial_condition
template<int dim> Parameters::InitialConditions<dim>* SimulationParameters< dim >::initial_condition
Definition at line 47 of file simulation_parameters.h.
laser_parameters
template<int dim> std::shared_ptr<Parameters::Laser<dim> > SimulationParameters< dim >::laser_parameters
Definition at line 37 of file simulation_parameters.h.
linear_solver
template<int dim> std::map<PhysicsID, Parameters::LinearSolver> SimulationParameters< dim >::linear_solver
Definition at line 26 of file simulation_parameters.h.
manifolds_parameters
template<int dim> Parameters::Manifolds SimulationParameters< dim >::manifolds_parameters
Definition at line 40 of file simulation_parameters.h.
mesh
template<int dim> Parameters::Mesh SimulationParameters< dim >::mesh
Definition at line 29 of file simulation_parameters.h.
mesh_adaptation
template<int dim> Parameters::MeshAdaptation SimulationParameters< dim >::mesh_adaptation
Definition at line 28 of file simulation_parameters.h.
mesh_box_refinement
template<int dim> std::shared_ptr<Parameters::MeshBoxRefinement> SimulationParameters< dim >::mesh_box_refinement
Definition at line 31 of file simulation_parameters.h.
multiphysics
template<int dim> Parameters::Multiphysics SimulationParameters< dim >::multiphysics
Definition at line 53 of file simulation_parameters.h.
nitsche
template<int dim> std::shared_ptr<Parameters::Nitsche<dim> > SimulationParameters< dim >::nitsche
Definition at line 32 of file simulation_parameters.h.
non_linear_solver
template<int dim> std::map<PhysicsID, Parameters::NonLinearSolver> SimulationParameters< dim >::non_linear_solver
Definition at line 27 of file simulation_parameters.h.
particlesParameters
template<int dim> std::shared_ptr<Parameters::IBParticles<dim> > SimulationParameters< dim >::particlesParameters
Definition at line 51 of file simulation_parameters.h.
physical_properties
template<int dim> Parameters::PhysicalProperties SimulationParameters< dim >::physical_properties private
Definition at line 463 of file simulation_parameters.h.
physical_properties_manager
template<int dim> PhysicalPropertiesManager SimulationParameters< dim >::physical_properties_manager
Definition at line 62 of file simulation_parameters.h.
physics_names
template<int dim> std::vector<std::string> SimulationParameters< dim >::physics_names private
Initial value:
= {"fluid dynamics",
                                            "heat transfer",
                                            "tracer",
                                            "VOF",
                                            "cahn hilliard"}
Definition at line 465 of file simulation_parameters.h.
post_processing
template<int dim> Parameters::PostProcessing SimulationParameters< dim >::post_processing
Definition at line 38 of file simulation_parameters.h.
restart_parameters
template<int dim> Parameters::Restart SimulationParameters< dim >::restart_parameters
Definition at line 39 of file simulation_parameters.h.
simulation_control
template<int dim> Parameters::SimulationControl SimulationParameters< dim >::simulation_control
Definition at line 33 of file simulation_parameters.h.
source_term
template<int dim> SourceTerms::SourceTerm<dim> SimulationParameters< dim >::source_term
Definition at line 49 of file simulation_parameters.h.
stabilization
template<int dim> Parameters::Stabilization SimulationParameters< dim >::stabilization
Definition at line 55 of file simulation_parameters.h.
test
template<int dim> Parameters::Testing SimulationParameters< dim >::test
Definition at line 25 of file simulation_parameters.h.
timer
template<int dim> Parameters::Timer SimulationParameters< dim >::timer
Definition at line 34 of file simulation_parameters.h.
tracer_drift_velocity
template<int dim> Parameters::TracerDriftVelocity<dim> SimulationParameters< dim >::tracer_drift_velocity
Definition at line 58 of file simulation_parameters.h.
velocity_sources
template<int dim> Parameters::VelocitySource SimulationParameters< dim >::velocity_sources
Definition at line 50 of file simulation_parameters.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/solvers/simulation_parameters.h