Lethe Open-Source Library: FluidDynamicsMatrixBased< dim > Class Template Reference
FluidDynamicsMatrixBased< dim > Class Template Reference
#include <fluid_dynamics_matrix_based.h>
Public Member Functions
FluidDynamicsMatrixBased (SimulationParameters< dim > &nsparam)
~FluidDynamicsMatrixBased ()
virtual void solve ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Protected Member Functions
virtual void setup_dofs_fd () override
virtual void set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart=false) override
virtual void assemble_system_matrix () override
virtual void assemble_system_rhs () override
virtual void update_multiphysics_time_average_solution () override
void setup_preconditioner () override
void define_dynamic_zero_constraints ()
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
virtual void setup_assemblers ()
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data)
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data)
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Protected Member Functions inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual GlobalVectorType & get_evaluation_point () override
virtual GlobalVectorType & get_local_evaluation_point () override
virtual GlobalVectorType & get_newton_update () override
virtual GlobalVectorType & get_present_solution () override
virtual GlobalVectorType & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void setup_dofs ()
virtual void set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart=false)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void postprocess_fd (bool first_iteration)
virtual void update_solutions_for_multiphysics ()
void postprocessing_forces (const GlobalVectorType &evaluation_point)
void postprocessing_torques (const GlobalVectorType &evaluation_point)
virtual void dynamic_flow_control ()
virtual void iterate ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
virtual void read_checkpoint ()
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
virtual void write_checkpoint ()
void write_output_results (const GlobalVectorType &solution)
virtual void output_field_hook (DataOut< dim > &)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
GlobalVectorType init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes
TrilinosWrappers::SparseMatrix system_matrix
Protected Attributes inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
GlobalVectorType present_solution
GlobalVectorType system_rhs
std::vector< GlobalVectorType > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, GlobalVectorType, IndexSet > > average_velocities
GlobalVectorType average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Private Member Functions
void assemble_L2_projection ()
void solve_system_GMRES (const bool initial_step, const double absolute_residual, const double relative_residual)
void solve_system_BiCGStab (const bool initial_step, const double absolute_residual, const double relative_residual)
void solve_system_direct (const bool initial_step, const double absolute_residual, const double relative_residual)
void setup_AMG ()
void setup_ILU ()
Private Attributes
SparsityPattern sparsity_pattern
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionAMG > amg_preconditioner
int current_preconditioner_fill_level
int initial_preconditioner_fill_level
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class FluidDynamicsMatrixBased< dim >
A solver class for the Navier-Stokes equation using GLS stabilization.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 32 of file fluid_dynamics_matrix_based.h.
Constructor & Destructor Documentation
FluidDynamicsMatrixBased()
template<int dim> FluidDynamicsMatrixBased< dim >::FluidDynamicsMatrixBased (SimulationParameters< dim > & nsparam)
Definition at line 37 of file fluid_dynamics_matrix_based.cc.
References Parameters::LinearSolver::amg, fluid_dynamics, FluidDynamicsMatrixBased< dim >::initial_preconditioner_fill_level, and NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters.
~FluidDynamicsMatrixBased()
template<int dim> FluidDynamicsMatrixBased< dim >::~FluidDynamicsMatrixBased
Definition at line 51 of file fluid_dynamics_matrix_based.cc.
Member Function Documentation
assemble_L2_projection()
template<int dim> void FluidDynamicsMatrixBased< dim >::assemble_L2_projection private
Assembles an L2_projection matrix for the velocity and the pressure. This L2 projection matrix can be used to set the initial condition for the Navier-Stokes problem.
Definition at line 1095 of file fluid_dynamics_matrix_based.cc.
References pressure.
assemble_local_system_matrix()
template<int dim> void FluidDynamicsMatrixBased< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) protected virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented in FluidDynamicsVANS< dim >, and FluidDynamicsSharp< dim >.
Definition at line 551 of file fluid_dynamics_matrix_based.cc.
References cahn_hilliard, NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, heat_transfer, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_cahn_hilliard(), NavierStokesScratchData< dim >::reinit_curvature(), NavierStokesScratchData< dim >::reinit_heat_transfer(), NavierStokesScratchData< dim >::reinit_projected_phase_fraction_gradient(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), and VOF.
assemble_local_system_rhs()
template<int dim> void FluidDynamicsMatrixBased< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) protected virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented in FluidDynamicsVANS< dim >, and FluidDynamicsSharp< dim >.
Definition at line 769 of file fluid_dynamics_matrix_based.cc.
References cahn_hilliard, NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, heat_transfer, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_cahn_hilliard(), NavierStokesScratchData< dim >::reinit_curvature(), NavierStokesScratchData< dim >::reinit_heat_transfer(), NavierStokesScratchData< dim >::reinit_projected_phase_fraction_gradient(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), and VOF.
assemble_system_matrix()
template<int dim> void FluidDynamicsMatrixBased< dim >::assemble_system_matrix override protected virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Reimplemented in FluidDynamicsNitsche< dim, spacedim >, FluidDynamicsVANS< dim >, and FluidDynamicsSharp< dim >.
Definition at line 474 of file fluid_dynamics_matrix_based.cc.
References FluidDynamicsMatrixBased< dim >::assemble_local_system_matrix(), cahn_hilliard, FluidDynamicsMatrixBased< dim >::copy_local_matrix_to_global_matrix(), heat_transfer, and VOF.
assemble_system_rhs()
template<int dim> void FluidDynamicsMatrixBased< dim >::assemble_system_rhs override protected virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Reimplemented in FluidDynamicsNitsche< dim, spacedim >, FluidDynamicsVANS< dim >, and FluidDynamicsSharp< dim >.
Definition at line 686 of file fluid_dynamics_matrix_based.cc.
References FluidDynamicsMatrixBased< dim >::assemble_local_system_rhs(), cahn_hilliard, FluidDynamicsMatrixBased< dim >::copy_local_rhs_to_global_rhs(), heat_transfer, and VOF.
copy_local_matrix_to_global_matrix()
template<int dim> void FluidDynamicsMatrixBased< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > & copy_data) protected virtual
Copy local cell information to global matrix.
Reimplemented in FluidDynamicsVANS< dim >, and FluidDynamicsSharp< dim >.
Definition at line 668 of file fluid_dynamics_matrix_based.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void FluidDynamicsMatrixBased< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > & copy_data) protected virtual
Copy local cell rhs information to global rhs.
Reimplemented in FluidDynamicsVANS< dim >, and FluidDynamicsSharp< dim >.
Definition at line 885 of file fluid_dynamics_matrix_based.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_rhs.
define_dynamic_zero_constraints()
template<int dim> void FluidDynamicsMatrixBased< dim >::define_dynamic_zero_constraints protected
Define the zero constraints used to solved the problem that change with other physics' solutions.
It differs from FluidDynamicsMatrixBased::define_zero_constraints as it changes in time depending on the physics' solutions. Currently, it is only used to constraint solid with the temperature's evolution.
Definition at line 174 of file fluid_dynamics_matrix_based.cc.
References heat_transfer, and VOF.
set_initial_condition_fd()
template<int dim> void FluidDynamicsMatrixBased< dim >::set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart = false) override protected virtual
Sets the initial condition for the solver.
If the simulation is restarted from a checkpoint, the initial solution setting is bypassed and the checkpoint is instead read.
Parameters
initial_condition_type The type of initial condition to be set
restart A boolean that indicates if the simulation is being restarted. if set to true, the initial conditions are never set, but are instead overridden by the read_checkpoint functionality.
Set the initial condition using a L2 or a viscous solver
Implements NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 905 of file fluid_dynamics_matrix_based.cc.
References announce_string(), Parameters::average_velocity_profile, fluid_dynamics, Parameters::LinearSolver::gmres, Parameters::L2projection, Parameters::nodal, Parameters::Timer::none, Parameters::ramp, read_checkpoint(), PhysicsSolver< VectorType >::solve_non_linear_system(), Parameters::SimulationControl::steady, and Parameters::viscous.
setup_AMG()
template<int dim> void FluidDynamicsMatrixBased< dim >::setup_AMG private
Set-up AMG preconditioner.
Definition at line 1261 of file fluid_dynamics_matrix_based.cc.
References fluid_dynamics.
setup_assemblers()
template<int dim> void FluidDynamicsMatrixBased< dim >::setup_assemblers protected virtual
sets up the vector of assembler functions
Reimplemented in FluidDynamicsVANS< dim >, and FluidDynamicsSharp< dim >.
Definition at line 215 of file fluid_dynamics_matrix_based.cc.
References BoundaryConditions::function_weak, Parameters::Stabilization::gls, is_bdf(), BoundaryConditions::outlet, BoundaryConditions::partial_slip, Parameters::VelocitySource::phase_change, BoundaryConditions::pressure, Parameters::Stabilization::pspg_supg, and Parameters::VelocitySource::srf.
setup_dofs_fd()
template<int dim> void FluidDynamicsMatrixBased< dim >::setup_dofs_fd override protected virtual
setup_dofs_fd Setup the degree of freedom, system matrix and solution vectors Navier-Stokes problem
Implements NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 58 of file fluid_dynamics_matrix_based.cc.
References Parameters::average_velocity_profile, and fluid_dynamics.
setup_ILU()
template<int dim> void FluidDynamicsMatrixBased< dim >::setup_ILU private
Set-up ILU preconditioner.
Definition at line 1241 of file fluid_dynamics_matrix_based.cc.
References fluid_dynamics.
setup_preconditioner()
template<int dim> void FluidDynamicsMatrixBased< dim >::setup_preconditioner override protected virtual
Set-up the appropriate preconditioner.
Implements PhysicsSolver< VectorType >.
Definition at line 1216 of file fluid_dynamics_matrix_based.cc.
References Parameters::LinearSolver::amg, fluid_dynamics, and Parameters::LinearSolver::ilu.
solve()
template<int dim> void FluidDynamicsMatrixBased< dim >::solve virtual
solve Solves the Navier-Stokes problem
This functions solves the problem defined by the Navier-Stokes parameter by iterating through time or through the mesh refinements.
Reimplemented in FluidDynamicsNitsche< dim, spacedim >, FluidDynamicsVANS< dim >, FluidDynamicsSharp< dim >, and CFDDEMSolver< dim >.
Definition at line 1624 of file fluid_dynamics_matrix_based.cc.
References read_mesh_and_manifolds(), and NavierStokesBase< dim, VectorType, DofsType >::refine_mesh().
solve_linear_system()
template<int dim> void FluidDynamicsMatrixBased< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override protected virtual
Call for the assembly of the linear system of equation.
Parameters
initial_step Indicates if this is the first solution of the linear system. If this is the case, the non_zero version of the constraints are used for the Dirichlet boundary conditions
renewed_matrix Indicates if the matrix has been reassembled, and thus the preconditioner needs to be reassembled.
//TODO the renewed_matrix parameters needs to be deprecated
Implements PhysicsSolver< VectorType >.
Definition at line 1178 of file fluid_dynamics_matrix_based.cc.
References Parameters::LinearSolver::bicgstab, Parameters::LinearSolver::direct, fluid_dynamics, and Parameters::LinearSolver::gmres.
solve_system_BiCGStab()
template<int dim> void FluidDynamicsMatrixBased< dim >::solve_system_BiCGStab (const bool initial_step, const double absolute_residual, const double relative_residual) private
BiCGStab solver with ILU(N) preconditioning.
Definition at line 1479 of file fluid_dynamics_matrix_based.cc.
References Parameters::extra_verbose, fluid_dynamics, Parameters::LinearSolver::ilu, and Parameters::quiet.
solve_system_direct()
template<int dim> void FluidDynamicsMatrixBased< dim >::solve_system_direct (const bool initial_step, const double absolute_residual, const double relative_residual) private
Direct solver using TrilinosWrappers::SolverDirect The use of this solver should be avoided for 3D problems.
Definition at line 1586 of file fluid_dynamics_matrix_based.cc.
References fluid_dynamics.
solve_system_GMRES()
template<int dim> void FluidDynamicsMatrixBased< dim >::solve_system_GMRES (const bool initial_step, const double absolute_residual, const double relative_residual) private
GMRES solver with ILU(N) preconditioning or AMG preconditioning.
Definition at line 1334 of file fluid_dynamics_matrix_based.cc.
References Parameters::LinearSolver::amg, Parameters::extra_verbose, fluid_dynamics, Parameters::LinearSolver::ilu, and Parameters::quiet.
update_multiphysics_time_average_solution()
template<int dim> void FluidDynamicsMatrixBased< dim >::update_multiphysics_time_average_solution override protected virtual
Updates the average velocity field solution in the multiphyscics interface.
Implements NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 159 of file fluid_dynamics_matrix_based.cc.
References Parameters::average_velocity_profile, and fluid_dynamics.
Member Data Documentation
amg_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionAMG> FluidDynamicsMatrixBased< dim >::amg_preconditioner private
Definition at line 249 of file fluid_dynamics_matrix_based.h.
current_preconditioner_fill_level
template<int dim> int FluidDynamicsMatrixBased< dim >::current_preconditioner_fill_level private
Definition at line 250 of file fluid_dynamics_matrix_based.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> FluidDynamicsMatrixBased< dim >::ilu_preconditioner private
Definition at line 248 of file fluid_dynamics_matrix_based.h.
initial_preconditioner_fill_level
template<int dim> int FluidDynamicsMatrixBased< dim >::initial_preconditioner_fill_level private
Definition at line 251 of file fluid_dynamics_matrix_based.h.
sparsity_pattern
template<int dim> SparsityPattern FluidDynamicsMatrixBased< dim >::sparsity_pattern private
Definition at line 247 of file fluid_dynamics_matrix_based.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix FluidDynamicsMatrixBased< dim >::system_matrix protected
Members
Definition at line 244 of file fluid_dynamics_matrix_based.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/fluid_dynamics_matrix_based.h
/home/runner/work/lethe/lethe/source/solvers/fluid_dynamics_matrix_based.cc