Lethe Open-Source Library: GLSNavierStokesVOFAssemblerNonNewtonianCore< dim > Class Template Reference
GLSNavierStokesVOFAssemblerNonNewtonianCore< dim > Class Template Reference
#include <navier_stokes_vof_assemblers.h>
Public Member Functions
GLSNavierStokesVOFAssemblerNonNewtonianCore (const std::shared_ptr< SimulationControl > &simulation_control, const SimulationParameters< dim > &nsparam)
Tensor< 1, dim > get_kinematic_viscosity_gradient (const Tensor< 2, dim > &velocity_gradient, const Tensor< 3, dim > &velocity_hessians, const double shear_rate_magnitude, const double grad_kinematic_viscosity_shear_rate) const
virtual void assemble_matrix (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual void assemble_rhs (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
Public Member Functions inherited from PhysicsAssemblerBase< ScratchDataType, CopyDataType >
virtual void assemble_matrix (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
virtual void assemble_rhs (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
Public Attributes
const bool SUPG = true
const std::shared_ptr< SimulationControl > simulation_control
const Parameters::VOF vof_parameters
Detailed Description
template<int dim>
class GLSNavierStokesVOFAssemblerNonNewtonianCore< dim >
Assembles the core of the Navier-Stokes equation using a Rheological model to predict non-Newtonian behaviors.
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 315 of file navier_stokes_vof_assemblers.h.
Constructor & Destructor Documentation
GLSNavierStokesVOFAssemblerNonNewtonianCore()
template<int dim> GLSNavierStokesVOFAssemblerNonNewtonianCore< dim >::GLSNavierStokesVOFAssemblerNonNewtonianCore (const std::shared_ptr< SimulationControl > & simulation_control, const SimulationParameters< dim > & nsparam) inline
Definition at line 319 of file navier_stokes_vof_assemblers.h.
Member Function Documentation
assemble_matrix()
template<int dim> void GLSNavierStokesVOFAssemblerNonNewtonianCore< dim >::assemble_matrix (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_matrix Assembles the matrix
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 857 of file navier_stokes_vof_assemblers.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), calculate_shear_rate_magnitude(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::density, PhysicalPropertiesManager::density_is_constant(), NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::dynamic_viscosity, NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_kinematic_viscosity_shear_rate, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, NavierStokesScratchData< dim >::laplacian_phi_u, StabilizedMethodsTensorCopyData< dim >::local_matrix, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_scaling_factor, NavierStokesScratchData< dim >::properties_manager, shear_rate, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_jacobian, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_hessians, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
assemble_rhs()
template<int dim> void GLSNavierStokesVOFAssemblerNonNewtonianCore< dim >::assemble_rhs (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_rhs Assembles the rhs
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 1060 of file navier_stokes_vof_assemblers.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), calculate_shear_rate_magnitude(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::density, PhysicalPropertiesManager::density_is_constant(), NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::dynamic_viscosity, NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_kinematic_viscosity_shear_rate, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, StabilizedMethodsTensorCopyData< dim >::local_rhs, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, pressure, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_values, NavierStokesScratchData< dim >::properties_manager, shear_rate, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_divergences, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_hessians, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
get_kinematic_viscosity_gradient()
template<int dim> Tensor<1, dim> GLSNavierStokesVOFAssemblerNonNewtonianCore< dim >::get_kinematic_viscosity_gradient (const Tensor< 2, dim > & velocity_gradient, const Tensor< 3, dim > & velocity_hessians, const double shear_rate_magnitude, const double grad_kinematic_viscosity_shear_rate) const inline
Calculates an approximation of the gradient of the viscosity.
Parameters
velocity_gradient The velocity gradient tensor on the quadrature point
velocity_hessians The velocity hessian tensor on the quadrture point
non_newtonian_viscosity The viscosity at which the gradient is calculated
d_gamma_dot Th difference in the shear rate magnitude to approximate the viscosity variation with a slight change in the shear_rate magnitude
Definition at line 335 of file navier_stokes_vof_assemblers.h.
Member Data Documentation
simulation_control
template<int dim> const std::shared_ptr<SimulationControl> GLSNavierStokesVOFAssemblerNonNewtonianCore< dim >::simulation_control
Definition at line 402 of file navier_stokes_vof_assemblers.h.
SUPG
template<int dim> const bool GLSNavierStokesVOFAssemblerNonNewtonianCore< dim >::SUPG = true
Enables SUPG stabilization for the Navier-Stokes formulation. We have not found any scenarios where it is relevant not to use SUPG stabilization yet.
Definition at line 400 of file navier_stokes_vof_assemblers.h.
vof_parameters
template<int dim> const Parameters::VOF GLSNavierStokesVOFAssemblerNonNewtonianCore< dim >::vof_parameters
Definition at line 403 of file navier_stokes_vof_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/navier_stokes_vof_assemblers.h
/home/runner/work/lethe/lethe/source/solvers/navier_stokes_vof_assemblers.cc