Lethe Open-Source Library: VOFSubequationsInterface< dim > Class Template Reference
VOFSubequationsInterface< dim > Class Template Reference
#include <vof_subequations_interface.h>
Public Member Functions
VOFSubequationsInterface (const SimulationParameters< dim > &p_simulation_parameters, const ConditionalOStream &p_pcout, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > &p_simulation_control)
~VOFSubequationsInterface ()=default
void initialize_subequations (const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > &p_simulation_control)
void setup_dofs ()
void setup_specific_subequation_dofs (const VOFSubequationsID &subequation_id)
void solve ()
void solve_specific_subequation (const VOFSubequationsID &subequation_id)
std::vector< VOFSubequationsID > get_active_subequations ()
const DoFHandler< dim > & get_dof_handler (const VOFSubequationsID &subequation_id)
const DoFHandler< dim > & get_vof_dof_handler ()
const GlobalVectorType & get_solution (const VOFSubequationsID &subequation_id)
const GlobalVectorType & get_vof_filtered_solution ()
const GlobalVectorType & get_vof_solution ()
bool get_solution_validity (const VOFSubequationsID &subequation_id)
std::string get_subequation_string (const VOFSubequationsID &subequation_id)
void set_dof_handler (const VOFSubequationsID &subequation_id, std::shared_ptr< DoFHandler< dim > > dof_handler)
void set_solution (const VOFSubequationsID &subequation_id, std::shared_ptr< GlobalVectorType > solution_vector)
void set_vof_filtered_solution_and_dof_handler (const GlobalVectorType &vof_filtered_solution_vector, const DoFHandler< dim > &dof_handler_vof)
void set_vof_solution (const GlobalVectorType &vof_solution_vector)
void set_solution_valid (const VOFSubequationsID &subequation_id)
bool validity_map_has_been_reset ()
Private Member Functions
void reset_subequations_solutions_validity ()
Private Attributes
const ConditionalOStream pcout
std::optional< std::reference_wrapper< const DoFHandler< dim > > > dof_handler_vof
std::optional< std::reference_wrapper< const GlobalVectorType > > vof_filtered_solution_vector
std::optional< std::reference_wrapper< const GlobalVectorType > > vof_solution_vector
std::vector< VOFSubequationsID > active_subequations
std::map< VOFSubequationsID, std::shared_ptr< PhysicsSubequationsSolverBase > > subequations
std::map< VOFSubequationsID, std::shared_ptr< DoFHandler< dim > > > subequations_dof_handler
std::map< VOFSubequationsID, std::shared_ptr< GlobalVectorType > > subequations_solutions
std::map< VOFSubequationsID, bool > subequations_solutions_validity
Detailed Description
template<int dim>
class VOFSubequationsInterface< dim >
Interface for secondary equations (subequations) solved within the VOF auxiliary physics.
Template Parameters
dim Number of dimensions of the problem.
Definition at line 44 of file vof_subequations_interface.h.
Constructor & Destructor Documentation
VOFSubequationsInterface()
template<int dim> VOFSubequationsInterface< dim >::VOFSubequationsInterface (const SimulationParameters< dim > & p_simulation_parameters, const ConditionalOStream & p_pcout, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > & p_simulation_control) inline
Constructor of an interface for subequations that require the use of a solver within the span of the VOF auxiliary physics' resolution.
Parameters
[in] p_simulation_parameters Simulation parameters.
[in] p_pcout Parallel cout used to print the information.
[in] p_triangulation Distributed mesh information.
[in] p_simulation_control SimulationControl object.
Definition at line 59 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::initialize_subequations().
~VOFSubequationsInterface()
template<int dim> VOFSubequationsInterface< dim >::~VOFSubequationsInterface () default
Default destructor.
Member Function Documentation
get_active_subequations()
template<int dim> std::vector< VOFSubequationsID > VOFSubequationsInterface< dim >::get_active_subequations () inline
Get vector of active subequations.
Returns
Vector of active subequations identifiers.
Definition at line 160 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations.
get_dof_handler()
template<int dim> const DoFHandler< dim > & VOFSubequationsInterface< dim >::get_dof_handler (const VOFSubequationsID & subequation_id) inline
Get a reference to the DoFHandler of a specific subequation.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Returns
Reference to the DoFHandler of the specified subequation.
Definition at line 174 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, and VOFSubequationsInterface< dim >::subequations_dof_handler.
get_solution()
template<int dim> const GlobalVectorType & VOFSubequationsInterface< dim >::get_solution (const VOFSubequationsID & subequation_id) inline
Get a reference to the solution vector of a specific subequation.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Returns
Reference to the solution vector of the specified subequation.
Definition at line 205 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::get_solution_validity(), VOFSubequationsInterface< dim >::get_subequation_string(), and VOFSubequationsInterface< dim >::subequations_solutions.
get_solution_validity()
template<int dim> bool VOFSubequationsInterface< dim >::get_solution_validity (const VOFSubequationsID & subequation_id) inline
Check and return a boolean indicating if the solution of the subequation has been solved for the corresponding dof_handler_vof, vof_filtered_solution_vector and/or vof_solution_vector previously set with VOFSubequationsInterface<dim>::set_vof_filtered_solution_and_dof_handler and VOFSubequationsInterface<dim>::set_vof_solution.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Returns
true if the solution of the subequation corresponds to the set dof_handler_vof, vof_filtered_solution_vector and/or vof_solution_vector.
Otherwise, false.
Definition at line 254 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, and VOFSubequationsInterface< dim >::subequations_solutions_validity.
get_subequation_string()
template<int dim> std::string VOFSubequationsInterface< dim >::get_subequation_string (const VOFSubequationsID & subequation_id) inline
Get the string associated with a specific subequation.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Returns
String associated with the specified subequation.
Note
This is used for printing purposes.
Definition at line 274 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, algebraic_interface_reinitialization, curvature_projection, and phase_gradient_projection.
get_vof_dof_handler()
template<int dim> const DoFHandler< dim > & VOFSubequationsInterface< dim >::get_vof_dof_handler () inline
Get a reference to the DoFHandler of the VOF auxiliary physics.
Returns
Reference to the DoFHandler of the VOF auxiliary physics associated to the set Filtered VOF solution field.
Definition at line 191 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::dof_handler_vof.
get_vof_filtered_solution()
template<int dim> const GlobalVectorType & VOFSubequationsInterface< dim >::get_vof_filtered_solution () inline
Get a reference to the filtered phase fraction solution vector.
Returns
Reference to the filtered phase fraction solution vector.
Definition at line 220 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::vof_filtered_solution_vector.
get_vof_solution()
template<int dim> const GlobalVectorType & VOFSubequationsInterface< dim >::get_vof_solution () inline
Get a reference to the phase fraction solution vector.
Returns
Reference to the phase fraction solution vector.
Definition at line 231 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::vof_solution_vector.
initialize_subequations()
template<int dim> void VOFSubequationsInterface< dim >::initialize_subequations (const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, const std::shared_ptr< SimulationControl > & p_simulation_control)
Initialize subequations necessary for the simulation and reset subeqaution validation map.
Parameters
[in] p_simulation_parameters Simulation parameters.
[in] p_triangulation Distributed mesh information.
[in] p_simulation_control SimulationControl object.
Definition at line 12 of file vof_subequations_interface.cc.
References Parameters::VOF_RegularizationMethod::algebraic_interface_reinitialization, algebraic_interface_reinitialization, curvature_projection, Parameters::VOF_SurfaceTensionForce::enable, Parameters::VOF_AlgebraicInterfaceReinitialization::enable, SimulationParameters< dim >::multiphysics, phase_gradient_projection, Parameters::VOF::regularization_method, Parameters::VOF::surface_tension_force, and Parameters::Multiphysics::vof_parameters.
reset_subequations_solutions_validity()
template<int dim> void VOFSubequationsInterface< dim >::reset_subequations_solutions_validity () inline private
Reset all boolean in the validity associated with active subequations to false.
Definition at line 428 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, and VOFSubequationsInterface< dim >::subequations_solutions_validity.
set_dof_handler()
template<int dim> void VOFSubequationsInterface< dim >::set_dof_handler (const VOFSubequationsID & subequation_id, std::shared_ptr< DoFHandler< dim > > dof_handler) inline
Set the DoFHandler associated with a specific subequation in the interface.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
[in] dof_handler Shared pointer to the DoFHandler of a specific subequation.
Definition at line 310 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, and VOFSubequationsInterface< dim >::subequations_dof_handler.
set_solution()
template<int dim> void VOFSubequationsInterface< dim >::set_solution (const VOFSubequationsID & subequation_id, std::shared_ptr< GlobalVectorType > solution_vector) inline
Set the solution associated with a specific subequation in the interface.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
[in] solution_vector Shared pointer to the solution vector of a specific subequation.
Definition at line 331 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, and VOFSubequationsInterface< dim >::subequations_solutions.
set_solution_valid()
template<int dim> void VOFSubequationsInterface< dim >::set_solution_valid (const VOFSubequationsID & subequation_id) inline
Set the solution as valid after solving it.
Parameters
[in] subequation_id Identifier associated with a specific subequation.
Definition at line 394 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, and VOFSubequationsInterface< dim >::subequations_solutions_validity.
set_vof_filtered_solution_and_dof_handler()
template<int dim> void VOFSubequationsInterface< dim >::set_vof_filtered_solution_and_dof_handler (const GlobalVectorType & vof_filtered_solution_vector, const DoFHandler< dim > & dof_handler_vof) inline
Set a new VOF filtered solution vector and DoFHandler for the subequations to be solved and reset their validity.
Parameters
[in] vof_filtered_solution_vector Reference to the filtered VOF solution vector associated with the subequations to be solved.
[in] dof_handler_vof Reference to the DoFHandler associated with the specified VOF filtered solution.
Note
At the moment, the VOF filtered solution is only used in VOFPhaseGradientProjection.
Definition at line 355 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::dof_handler_vof, VOFSubequationsInterface< dim >::reset_subequations_solutions_validity(), and VOFSubequationsInterface< dim >::vof_filtered_solution_vector.
set_vof_solution()
template<int dim> void VOFSubequationsInterface< dim >::set_vof_solution (const GlobalVectorType & vof_solution_vector) inline
Set a new VOF solution vector and DoFHandler for the subequations to be solved.
Parameters
[in] vof_solution_vector VOF solution vector associated with the subequations to be solved.
Note
At the moment, the VOF unfiltered solution is only used in VOFAlgebraicInterfaceReinitialization.
Definition at line 379 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::validity_map_has_been_reset(), and VOFSubequationsInterface< dim >::vof_solution_vector.
setup_dofs()
template<int dim> void VOFSubequationsInterface< dim >::setup_dofs () inline
Setup the DofHandler and the degree of freedom associated with the subequations.
Definition at line 99 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::subequations.
setup_specific_subequation_dofs()
template<int dim> void VOFSubequationsInterface< dim >::setup_specific_subequation_dofs (const VOFSubequationsID & subequation_id) inline
Setup the DofHandler and the degree of freedom associated with the physics.
Parameters
[in] subequation_id Identifier associated with the subequation wished to solve.
Definition at line 115 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, and VOFSubequationsInterface< dim >::subequations.
solve()
template<int dim> void VOFSubequationsInterface< dim >::solve () inline
Call solving method of active subequations.
Definition at line 129 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::subequations.
solve_specific_subequation()
template<int dim> void VOFSubequationsInterface< dim >::solve_specific_subequation (const VOFSubequationsID & subequation_id) inline
Call solving method for a specific subequation.
Parameters
[in] subequation_id Identifier associated with the subequation wished to solve.
Definition at line 144 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::active_subequations, and VOFSubequationsInterface< dim >::subequations.
validity_map_has_been_reset()
template<int dim> bool VOFSubequationsInterface< dim >::validity_map_has_been_reset () inline
Check if all booleans in subequations_solutions_validity have been reset to false.
Returns
true if all booleans in the map are set to false or;
false if at least one of the booleans is set to true
Definition at line 412 of file vof_subequations_interface.h.
References VOFSubequationsInterface< dim >::subequations_solutions_validity.
Member Data Documentation
active_subequations
template<int dim> std::vector<VOFSubequationsID> VOFSubequationsInterface< dim >::active_subequations private
Data structure that stores all enabled subequations.
Definition at line 453 of file vof_subequations_interface.h.
dof_handler_vof
template<int dim> std::optional<std::reference_wrapper<const DoFHandler<dim> > > VOFSubequationsInterface< dim >::dof_handler_vof private
VOF DoFHandler associated with solved equations.
Definition at line 440 of file vof_subequations_interface.h.
pcout
template<int dim> const ConditionalOStream VOFSubequationsInterface< dim >::pcout private
Parallel consol output object.
Definition at line 437 of file vof_subequations_interface.h.
subequations
template<int dim> std::map<VOFSubequationsID, std::shared_ptr<PhysicsSubequationsSolverBase> > VOFSubequationsInterface< dim >::subequations private
Subequations are stored within a map of shared pointer to ensure proper memory management
Definition at line 458 of file vof_subequations_interface.h.
subequations_dof_handler
template<int dim> std::map<VOFSubequationsID, std::shared_ptr<DoFHandler<dim> > > VOFSubequationsInterface< dim >::subequations_dof_handler private
Map of DoFHandler of subequations.
Definition at line 462 of file vof_subequations_interface.h.
subequations_solutions
template<int dim> std::map<VOFSubequationsID, std::shared_ptr<GlobalVectorType> > VOFSubequationsInterface< dim >::subequations_solutions private
Present solutions map.
Definition at line 466 of file vof_subequations_interface.h.
subequations_solutions_validity
template<int dim> std::map<VOFSubequationsID, bool> VOFSubequationsInterface< dim >::subequations_solutions_validity private
Booleans indicating if the subequation has been solved with the set VOF filtered and unfiltered solution vectors set respectively with VOFSubequationsInterface<dim>::set_vof_filtered_solution_and_dof_handler and VOFSubequationsInterface<dim>::set_vof_solution.
During initialization (VOFSubequationsInterface<dim>::initialize_subequations), all boolean are set to false.
We start by setting a VOF filtered solution and DOFHandler (VOFSubequationsInterface<dim>::set_vof_filtered_solution_and_dof_handler), and then start solving equations making sure that dependencies are met (VOFPhaseGradientProjection<dim>::check_dependencies_validity, VOFCurvatureProjection<dim>::check_dependencies_validity, and VOFAlgebraicInterfaceReinitialization<dim>::check_dependencies_validity). For instance, to solve the curvature projection subequation, the phase gradient projection subequation has to be solved before as the projected phase gradient is used in the curvature projection subequation.
A subequation in the validity map is to true only when it is solved and it remains valid until a new VOF filtered solution and/or DOFHandler are set through VOFSubequationsInterface<dim>::set_vof_filtered_solution_and_dof_handler.
This validation mechanism allows, to check if:
A new VOF filtered/unfiltered solution has been set;
All dependencies of the subequation have been solved;
The current solution of the subequation is valid and avoid unnecessarily solving it once more.
Note
VOFSubequationsInterface<dim>::set_vof_filtered_solution_and_dof_handler also resets the validity map values to false.
VOFAlgebraicInterfaceReinitialization also requires a VOF unfiltered solution. The solution is set by calling VOFSubequationsInterface<dim>::set_vof_solution, right after VOFSubequationsInterface<dim>::set_vof_filtered_solution_and_dof_handler.
Definition at line 508 of file vof_subequations_interface.h.
vof_filtered_solution_vector
template<int dim> std::optional<std::reference_wrapper<const GlobalVectorType> > VOFSubequationsInterface< dim >::vof_filtered_solution_vector private
Filtered VOF solution field associated with solved equations
Note
Used in the computation of VOF phase gradient projection
Definition at line 445 of file vof_subequations_interface.h.
vof_solution_vector
template<int dim> std::optional<std::reference_wrapper<const GlobalVectorType> > VOFSubequationsInterface< dim >::vof_solution_vector private
VOF solution field associated with solved equations
Note
Serves as initial condition in algebraic reinitialization
Definition at line 450 of file vof_subequations_interface.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/vof_subequations_interface.h
/home/runner/work/lethe/lethe/source/solvers/vof_subequations_interface.cc