Lethe Open-Source Library: Carreau Class Reference
Carreau Class Reference
#include <rheological_model.h>
Public Member Functions
Carreau (const double p_kinematic_viscosity_0, const double p_kinematicviscosity_inf, const double p_lambda, const double p_a, const double p_n)
double value (const std::map< field, double > &) override
void vector_value (const std::map< field, std::vector< double > > &, std::vector< double > &property_vector) override
double jacobian (const std::map< field, double > &, field) override
void vector_jacobian (const std::map< field, std::vector< double > > &, const field, std::vector< double > &jacobian_vector) override
double get_n () const override
void set_n (const double &p_n) override
double get_kinematic_viscosity () const override
double get_kinematic_viscosity_scale () const override
void set_kinematic_viscosity (const double &p_kinematic_viscosity) override
double get_dynamic_viscosity (const double &p_density_ref, const std::map< field, double > &field_values) const override
void get_dynamic_viscosity_vector (const double &p_density_ref, const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &property_vector) override
Public Member Functions inherited from RheologicalModel
RheologicalModel ()
virtual void set_dynamic_viscosity (const double &)
virtual double get_kinematic_viscosity_for_stabilization (const std::map< field, double > &field_values)
virtual void get_kinematic_viscosity_for_stabilization_vector (const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &property_vector)
virtual double get_dynamic_viscosity_for_stabilization (const double &p_density_ref, const std::map< field, double > &field_values)
virtual void get_dynamic_viscosity_for_stabilization_vector (const double &p_density_ref, const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &property_vector)
bool is_non_newtonian_rheological_model () const
bool is_phase_change_rheological_model () const
Public Member Functions inherited from PhysicalPropertyModel
PhysicalPropertyModel ()
virtual ~PhysicalPropertyModel ()
bool depends_on (const field &id)
void provide_simulation_control (std::shared_ptr< SimulationControl > &p_simulation_control)
double numerical_jacobian (const std::map< field, double > &field_values, const field id)
void vector_numerical_jacobian (const std::map< field, std::vector< double > > &field_vectors, const field id, std::vector< double > &jacobian_vector)
Private Member Functions
double calculate_kinematic_viscosity (const double shear_rate_magnitude) const
Private Attributes
double kinematic_viscosity_0
double kinematic_viscosity_inf
double lambda
double a
double n
Additional Inherited Members
Static Public Member Functions inherited from RheologicalModel
static std::shared_ptr< RheologicalModel > model_cast (const Parameters::Material &material_properties)
Protected Member Functions inherited from PhysicalPropertyModel
std::shared_ptr< SimulationControl > & get_simulation_control ()
Protected Attributes inherited from RheologicalModel
bool non_newtonian_rheological_model = false
bool phase_change_rheological_model = false
Protected Attributes inherited from PhysicalPropertyModel
std::map< field, bool > model_depends_on
Detailed Description
Definition at line 516 of file rheological_model.h.
Constructor & Destructor Documentation
Carreau()
Carreau::Carreau (const double p_kinematic_viscosity_0, const double p_kinematicviscosity_inf, const double p_lambda, const double p_a, const double p_n) inline
Parameter constructor.
Parameters
non_newtonian_parameters The non newtonian parameters
Definition at line 524 of file rheological_model.h.
References PhysicalPropertyModel::model_depends_on, RheologicalModel::non_newtonian_rheological_model, and shear_rate.
Member Function Documentation
calculate_kinematic_viscosity()
double Carreau::calculate_kinematic_viscosity (const double shear_rate_magnitude) const inline private
Definition at line 660 of file rheological_model.h.
References a, kinematic_viscosity_0, kinematic_viscosity_inf, lambda, and n.
get_dynamic_viscosity()
double Carreau::get_dynamic_viscosity (const double & p_density_ref, const std::map< field, double > & field_values) const inline override virtual
Calculates the dynamic viscosity, if a kinematic viscosity and a reference density value is specified.
Parameters
p_density_ref The density of the fluid at the reference state
field_values Value of the various fields on which the property may depend.
Implements RheologicalModel.
Definition at line 626 of file rheological_model.h.
References calculate_kinematic_viscosity(), and shear_rate.
get_dynamic_viscosity_vector()
void Carreau::get_dynamic_viscosity_vector (const double & p_density_ref, const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & property_vector) inline override virtual
Calculates the vector values of the dynamic viscosity.
Parameters
p_density_ref The density of the fluid at the reference state
field_vectors Values of the field on which the dynamic viscosity may depend on.
Implements RheologicalModel.
Definition at line 643 of file rheological_model.h.
References calculate_kinematic_viscosity(), and shear_rate.
get_kinematic_viscosity()
double Carreau::get_kinematic_viscosity () const inline override virtual
Returns the value of the kinematic viscosity, if the model has one.
Reimplemented from RheologicalModel.
Definition at line 606 of file rheological_model.h.
References kinematic_viscosity_0.
get_kinematic_viscosity_scale()
double Carreau::get_kinematic_viscosity_scale () const inline override virtual
Returns the kinematic viscosity scale. This is used to get the kinematic viscosity scale in the problem when it's not constant. This is useful for weak boundary conditions.
Reimplemented from RheologicalModel.
Definition at line 612 of file rheological_model.h.
References a, kinematic_viscosity_0, kinematic_viscosity_inf, lambda, and n.
get_n()
double Carreau::get_n () const inline override virtual
Returns the value of the n parameters of the model, if the model has one.
Reimplemented from RheologicalModel.
Definition at line 594 of file rheological_model.h.
References n.
jacobian()
double Carreau::jacobian (const std::map< field, double > & field_values, field id) override virtual
jacobian Calculates the jacobian (the partial derivative) of the viscosity with respect to a field
Parameters
field_values Value of the various fields on which the property may depend. The constant viscosity does not depend on anything
id Indicator of the field with respect to which the jacobian should be calculated
Returns
value of the partial derivative of the viscosity with respect to the field.
Implements PhysicalPropertyModel.
Definition at line 122 of file rheological_model.cc.
References PhysicalPropertyModel::numerical_jacobian(), and shear_rate.
set_kinematic_viscosity()
void Carreau::set_kinematic_viscosity (const double &) inline override virtual
Sets a new kinematic viscosity value, if the models has one.
Parameters
p_kinematic_viscosity The kinematic viscosity value
Reimplemented from RheologicalModel.
Definition at line 620 of file rheological_model.h.
References kinematic_viscosity_0.
set_n()
void Carreau::set_n (const double &) inline override virtual
Sets a new value to the n parameter, if the models has one.
Reimplemented from RheologicalModel.
Definition at line 600 of file rheological_model.h.
References n.
value()
double Carreau::value (const std::map< field, double > & field_values) override virtual
Returns the non-newtonian viscosity.
Parameters
field_values The values of the field on which the viscosity may depend on. For this model, it only depends on the magnitude of the shear rate tensor.
Source : Morrison, F. A. (2001). No Memory: Generalized Newtonian Fluids. Understanding Rheology. Raymond F. Boyer Librabry Collection, Oxford University Press.
Implements PhysicalPropertyModel.
Definition at line 97 of file rheological_model.cc.
References calculate_kinematic_viscosity(), and shear_rate.
vector_jacobian()
void Carreau::vector_jacobian (const std::map< field, std::vector< double > > & field_vectors, const field id, std::vector< double > & jacobian_vector) override virtual
vector_jacobian Calculate the derivative of the with respect to a field
Parameters
field_vectors Vector for the values of the fields used to evaluate the property
id Identifier of the field with respect to which a derivative should be calculated
jacobian Vector of the value of the derivative of the viscosity with respect to the field id
Implements PhysicalPropertyModel.
Definition at line 135 of file rheological_model.cc.
References shear_rate, and PhysicalPropertyModel::vector_numerical_jacobian().
vector_value()
void Carreau::vector_value (const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & property_vector) override virtual
vector_value Calculates the vector values of the viscosity.
Parameters
field_vectors Values of the field on which the viscosity may depend on. The power-law viscosity depends on the shear rate.
Implements PhysicalPropertyModel.
Definition at line 107 of file rheological_model.cc.
References calculate_kinematic_viscosity(), and shear_rate.
Member Data Documentation
a
double Carreau::a private
Definition at line 671 of file rheological_model.h.
kinematic_viscosity_0
double Carreau::kinematic_viscosity_0 private
Definition at line 668 of file rheological_model.h.
kinematic_viscosity_inf
double Carreau::kinematic_viscosity_inf private
Definition at line 669 of file rheological_model.h.
lambda
double Carreau::lambda private
Definition at line 670 of file rheological_model.h.
n
double Carreau::n private
Definition at line 672 of file rheological_model.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/rheological_model.h
/home/runner/work/lethe/lethe/source/core/rheological_model.cc