Lethe Open-Source Library: MortarManagerBase< dim > Class Template Reference
MortarManagerBase< dim > Class Template Reference abstract
#include <mortar_coupling_manager.h>
Public Member Functions
template<int dim2>
MortarManagerBase (unsigned int n_subdivisions, double radius, const Quadrature< dim2 > &quadrature, const double rotation_angle)
bool is_mesh_aligned () const
unsigned int get_n_total_mortars () const
unsigned int get_n_mortars () const
std::vector< unsigned int > get_mortar_indices (const Point< dim > &face_center) const
unsigned int get_n_total_points () const
unsigned int get_n_points () const
std::vector< Point< dim > > get_points (const Point< dim > &face_center) const
std::vector< Point< 1 > > get_points_ref (const Point< dim > &face_center) const
std::vector< double > get_weights (const Point< dim > &face_center) const
std::vector< Tensor< 1, dim, double > > get_normals (const Point< dim > &face_center) const
Public Attributes
unsigned int n_subdivisions
double radius
Protected Member Functions
std::pair< unsigned int, unsigned int > get_config (const Point< dim > &face_center) const
virtual Point< dim > from_1D (const double radiant) const =0
virtual double to_1D (const Point< dim > &point) const =0
virtual Tensor< 1, dim, double > get_normal (const Point< dim > &point) const =0
Protected Attributes
Quadrature< 1 > quadrature
const unsigned int n_quadrature_points
const double rotation_angle
Detailed Description
template<int dim>
class MortarManagerBase< dim >
Base class for the mortar manager.
Definition at line 27 of file mortar_coupling_manager.h.
Constructor & Destructor Documentation
MortarManagerBase()
template<int dim> template<int dim2> MortarManagerBase< dim >::MortarManagerBase (unsigned int n_subdivisions, double radius, const Quadrature< dim2 > & quadrature, const double rotation_angle)
Definition at line 231 of file mortar_coupling_manager.h.
Member Function Documentation
from_1D()
template<int dim> virtual Point< dim > MortarManagerBase< dim >::from_1D (const double radiant) const protected pure virtual
Convert radiant to quadrature point in real space.
Implemented in MortarManagerCircle< dim >.
get_config()
template<int dim> std::pair< unsigned int, unsigned int > MortarManagerBase< dim >::get_config (const Point< dim > & face_center) const protected
Returns the mesh alignment type and cell index.
Parameters
[in] face_center Face center
Returns
type Cell configuration type at the interface type = 0: mesh aligned type = 1: mesh not aligned, inner domain (allows rotation) type = 2: mesh not aligned, outer domain (fixed)
id Index of the cell in which lies the rotated cell center
Definition at line 333 of file mortar_coupling_manager.cc.
References delta().
get_mortar_indices()
template<int dim> std::vector< unsigned int > MortarManagerBase< dim >::get_mortar_indices (const Point< dim > & face_center) const
Returns the indices of all mortars at both sides of the interface.
Parameters
[in] face_center Face center
Definition at line 64 of file mortar_coupling_manager.cc.
get_n_mortars()
template<int dim> unsigned int MortarManagerBase< dim >::get_n_mortars () const
Returns the number of mortars per face.
Definition at line 47 of file mortar_coupling_manager.cc.
get_n_points()
template<int dim> unsigned int MortarManagerBase< dim >::get_n_points () const
Returns the coordinates of the quadrature points at both sides of the interface.
Definition at line 135 of file mortar_coupling_manager.cc.
get_n_total_mortars()
template<int dim> unsigned int MortarManagerBase< dim >::get_n_total_mortars () const
Returns the total number of mortars.
Definition at line 30 of file mortar_coupling_manager.cc.
get_n_total_points()
template<int dim> unsigned int MortarManagerBase< dim >::get_n_total_points () const
Returns the total number of quadrature points at the inner/outer boundary interface.
Definition at line 118 of file mortar_coupling_manager.cc.
get_normal()
template<int dim> virtual Tensor< 1, dim, double > MortarManagerBase< dim >::get_normal (const Point< dim > & point) const protected pure virtual
Return the normal for a given quadrature point.
Implemented in MortarManagerCircle< dim >.
get_normals()
template<int dim> std::vector< Tensor< 1, dim, double > > MortarManagerBase< dim >::get_normals (const Point< dim > & face_center) const
Returns the normal vector for the quadrature points.
Parameters
[in] face_center Face center
Returns
result Normal vectors of the cell quadrature points
Definition at line 316 of file mortar_coupling_manager.cc.
get_points()
template<int dim> std::vector< Point< dim > > MortarManagerBase< dim >::get_points (const Point< dim > & face_center) const
Returns the coordinates of the quadrature points at both sides of the interface.
Parameters
[in] face_center Face center
Returns
points Coordinate of quadrature points of the cell
Definition at line 152 of file mortar_coupling_manager.cc.
References delta().
get_points_ref()
template<int dim> std::vector< Point< 1 > > MortarManagerBase< dim >::get_points_ref (const Point< dim > & face_center) const
Returns the coordinates of the quadrature points at the interface.
Parameters
[in] face_center Face center
Returns
points Coordinate of quadrature points of the cell
Definition at line 211 of file mortar_coupling_manager.cc.
References delta().
get_weights()
template<int dim> std::vector< double > MortarManagerBase< dim >::get_weights (const Point< dim > & face_center) const
Returns the weights of the quadrature points at both sides of the interface.
Parameters
[in] face_center Face center
Returns
points Angular weights of quadrature points of the cell
Definition at line 263 of file mortar_coupling_manager.cc.
References delta().
is_mesh_aligned()
template<int dim> bool MortarManagerBase< dim >::is_mesh_aligned () const
Verify if cells of the inner and outer domains are aligned.
Definition at line 17 of file mortar_coupling_manager.cc.
References delta().
to_1D()
template<int dim> virtual double MortarManagerBase< dim >::to_1D (const Point< dim > & point) const protected pure virtual
Convert quadrature point in real space to radiant.
Implemented in MortarManagerCircle< dim >.
Member Data Documentation
n_quadrature_points
template<int dim> const unsigned int MortarManagerBase< dim >::n_quadrature_points protected
Number of quadrature points per cell.
Definition at line 155 of file mortar_coupling_manager.h.
n_subdivisions
template<int dim> unsigned int MortarManagerBase< dim >::n_subdivisions
Number of cells at the interface between inner and outer domains.
Definition at line 115 of file mortar_coupling_manager.h.
quadrature
template<int dim> Quadrature<1> MortarManagerBase< dim >::quadrature protected
Mortar quadrature.
Definition at line 153 of file mortar_coupling_manager.h.
radius
template<int dim> double MortarManagerBase< dim >::radius
Radius at the interface between inner and outer domains.
Definition at line 117 of file mortar_coupling_manager.h.
rotation_angle
template<int dim> const double MortarManagerBase< dim >::rotation_angle protected
Rotation angle for the inner domain.
Definition at line 157 of file mortar_coupling_manager.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/mortar_coupling_manager.h
/home/runner/work/lethe/lethe/source/core/mortar_coupling_manager.cc