Lethe Open-Source Library: Parameters::Material Class Reference
Parameters::Material Class Reference
#include <parameters.h>
Public Types
enum class RheologicalModel : std::int8_t { powerlaw , carreau , newtonian , phase_change }
enum class DensityModel : std::int8_t { constant , isothermal_ideal_gas }
enum class SpecificHeatModel : std::int8_t { constant , phase_change }
enum class ThermalConductivityModel : std::int8_t { constant , linear , phase_change }
enum class ThermalExpansionModel : std::int8_t { constant , phase_change }
enum class TracerDiffusivityModel : std::int8_t { constant , immersed_boundary_tanh , immersed_boundary_gaussian }
enum class TracerReactionPrefactorModel : std::int8_t { none , constant , immersed_boundary_tanh , immersed_boundary_gaussian }
Public Member Functions
Material ()=default
void declare_parameters (ParameterHandler &prm, const std::string &material_prefix, unsigned int id) const
void parse_parameters (ParameterHandler &prm, const std::string &material_prefix, const unsigned int id, const Dimensionality &dimensions)
Public Attributes
double kinematic_viscosity
double density
double specific_heat
double thermal_conductivity
double thermal_expansion
double tracer_diffusivity
double tracer_reaction_constant
double tracer_reaction_order
PhaseChange phase_change_parameters
enum Parameters::Material::RheologicalModel rheological_model
NonNewtonian non_newtonian_parameters
enum Parameters::Material::DensityModel density_model
IsothermalIdealGasDensityParameters isothermal_ideal_gas_density_parameters
enum Parameters::Material::SpecificHeatModel specific_heat_model
enum Parameters::Material::ThermalConductivityModel thermal_conductivity_model
enum Parameters::Material::ThermalExpansionModel thermal_expansion_model
enum Parameters::Material::TracerDiffusivityModel tracer_diffusivity_model
enum Parameters::Material::TracerReactionPrefactorModel tracer_reaction_prefactor_model
ImmersedSolidTanhParameters immersed_solid_tanh_parameters
ImmersedSolidGaussianParameters immersed_solid_gaussian_parameters
double k_A0
double k_A1
Detailed Description
Material - Class that defines the physical property of a material. Generally a material will be a fluid, but for conjugated heat transfer, this may also be a solid.
Definition at line 425 of file parameters.h.
Member Enumeration Documentation
DensityModel
enum class Parameters::Material::DensityModel : std::int8_t strong
Enumerator
constant
isothermal_ideal_gas
Definition at line 472 of file parameters.h.
RheologicalModel
enum class Parameters::Material::RheologicalModel : std::int8_t strong
Enumerator
powerlaw
carreau
newtonian
phase_change
Definition at line 463 of file parameters.h.
SpecificHeatModel
enum class Parameters::Material::SpecificHeatModel : std::int8_t strong
Enumerator
constant
phase_change
Definition at line 479 of file parameters.h.
ThermalConductivityModel
enum class Parameters::Material::ThermalConductivityModel : std::int8_t strong
Enumerator
constant
linear
phase_change
Definition at line 485 of file parameters.h.
ThermalExpansionModel
enum class Parameters::Material::ThermalExpansionModel : std::int8_t strong
Enumerator
constant
phase_change
Definition at line 492 of file parameters.h.
TracerDiffusivityModel
enum class Parameters::Material::TracerDiffusivityModel : std::int8_t strong
Enumerator
constant
immersed_boundary_tanh
immersed_boundary_gaussian
Definition at line 498 of file parameters.h.
TracerReactionPrefactorModel
enum class Parameters::Material::TracerReactionPrefactorModel : std::int8_t strong
Enumerator
none
constant
immersed_boundary_tanh
immersed_boundary_gaussian
Definition at line 505 of file parameters.h.
Constructor & Destructor Documentation
Material()
Parameters::Material::Material () default
Member Function Documentation
declare_parameters()
void Parameters::Material::declare_parameters (ParameterHandler & prm, const std::string & material_prefix, unsigned int id) const
Definition at line 1117 of file parameters.cc.
References Parameters::PhaseChange::declare_parameters(), Parameters::ImmersedSolidTanhParameters::declare_parameters(), Parameters::ImmersedSolidGaussianParameters::declare_parameters(), Parameters::IsothermalIdealGasDensityParameters::declare_parameters(), Parameters::NonNewtonian::declare_parameters(), immersed_solid_gaussian_parameters, immersed_solid_tanh_parameters, isothermal_ideal_gas_density_parameters, non_newtonian_parameters, and phase_change_parameters.
parse_parameters()
void Parameters::Material::parse_parameters (ParameterHandler & prm, const std::string & material_prefix, const unsigned int id, const Dimensionality & dimensions)
Definition at line 1249 of file parameters.cc.
References carreau, constant, density, density_model, Parameters::Dimensionality::density_scaling, Parameters::Dimensionality::diffusivity_scaling, immersed_boundary_gaussian, immersed_boundary_tanh, immersed_solid_gaussian_parameters, immersed_solid_tanh_parameters, isothermal_ideal_gas, isothermal_ideal_gas_density_parameters, k_A0, k_A1, kinematic_viscosity, linear, newtonian, non_newtonian_parameters, none, Parameters::PhaseChange::parse_parameters(), Parameters::NonNewtonian::parse_parameters(), Parameters::ImmersedSolidTanhParameters::parse_parameters(), Parameters::ImmersedSolidGaussianParameters::parse_parameters(), Parameters::IsothermalIdealGasDensityParameters::parse_parameters(), phase_change, phase_change_parameters, powerlaw, rheological_model, specific_heat, specific_heat_model, Parameters::Dimensionality::specific_heat_scaling, Parameters::Dimensionality::temperature, thermal_conductivity, thermal_conductivity_model, Parameters::Dimensionality::thermal_conductivity_scaling, thermal_expansion, thermal_expansion_model, tracer_diffusivity, tracer_diffusivity_model, tracer_reaction_constant, tracer_reaction_order, tracer_reaction_prefactor_model, and Parameters::Dimensionality::viscosity_scaling.
Member Data Documentation
density
double Parameters::Material::density
Definition at line 443 of file parameters.h.
density_model
enum Parameters::Material::DensityModel Parameters::Material::density_model
immersed_solid_gaussian_parameters
ImmersedSolidGaussianParameters Parameters::Material::immersed_solid_gaussian_parameters
Definition at line 519 of file parameters.h.
immersed_solid_tanh_parameters
ImmersedSolidTanhParameters Parameters::Material::immersed_solid_tanh_parameters
Definition at line 515 of file parameters.h.
isothermal_ideal_gas_density_parameters
IsothermalIdealGasDensityParameters Parameters::Material::isothermal_ideal_gas_density_parameters
Definition at line 477 of file parameters.h.
k_A0
double Parameters::Material::k_A0
Definition at line 522 of file parameters.h.
k_A1
double Parameters::Material::k_A1
Definition at line 523 of file parameters.h.
kinematic_viscosity
double Parameters::Material::kinematic_viscosity
Definition at line 441 of file parameters.h.
non_newtonian_parameters
NonNewtonian Parameters::Material::non_newtonian_parameters
Definition at line 470 of file parameters.h.
phase_change_parameters
PhaseChange Parameters::Material::phase_change_parameters
Definition at line 460 of file parameters.h.
rheological_model
enum Parameters::Material::RheologicalModel Parameters::Material::rheological_model
specific_heat
double Parameters::Material::specific_heat
Definition at line 445 of file parameters.h.
specific_heat_model
enum Parameters::Material::SpecificHeatModel Parameters::Material::specific_heat_model
thermal_conductivity
double Parameters::Material::thermal_conductivity
Definition at line 447 of file parameters.h.
thermal_conductivity_model
enum Parameters::Material::ThermalConductivityModel Parameters::Material::thermal_conductivity_model
thermal_expansion
double Parameters::Material::thermal_expansion
Definition at line 449 of file parameters.h.
thermal_expansion_model
enum Parameters::Material::ThermalExpansionModel Parameters::Material::thermal_expansion_model
tracer_diffusivity
double Parameters::Material::tracer_diffusivity
Definition at line 452 of file parameters.h.
tracer_diffusivity_model
enum Parameters::Material::TracerDiffusivityModel Parameters::Material::tracer_diffusivity_model
tracer_reaction_constant
double Parameters::Material::tracer_reaction_constant
Definition at line 455 of file parameters.h.
tracer_reaction_order
double Parameters::Material::tracer_reaction_order
Definition at line 457 of file parameters.h.
tracer_reaction_prefactor_model
enum Parameters::Material::TracerReactionPrefactorModel Parameters::Material::tracer_reaction_prefactor_model
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/parameters.h
/home/runner/work/lethe/lethe/source/core/parameters.cc