Lethe Open-Source Library: InterfaceTools::SignedDistanceSolver< dim, VectorType > Class Template Reference
InterfaceTools::SignedDistanceSolver< dim, VectorType > Class Template Reference
#include <interface_tools.h>
Public Member Functions
SignedDistanceSolver (std::shared_ptr< parallel::DistributedTriangulationBase< dim > > background_triangulation, std::shared_ptr< FiniteElement< dim > > background_fe, const double p_max_distance, const double p_iso_level, const double p_scaling, const Parameters::Verbosity p_verbosity)
void setup_dofs ()
void set_level_set_from_background_mesh (const DoFHandler< dim > &background_dof_handler, const VectorType &background_level_set_vector)
void solve ()
VectorType & get_signed_distance ()
void output_interface_reconstruction (const std::string &output_name, const std::string &output_path, const double time, const unsigned int it)
void output_signed_distance (const std::string &output_name, const std::string &output_path, const double time, const unsigned int it)
std::vector< OutputStruct< dim, GlobalVectorType > > gather_output_hook ()
Public Attributes
DoFHandler< dim > dof_handler
Private Member Functions
void zero_out_ghost_values () const
void update_ghost_values () const
void exchange_distance ()
void initialize_distance ()
void compute_first_neighbors_distance ()
void compute_second_neighbors_distance ()
void compute_signed_distance_from_distance ()
void compute_cell_wise_volume_correction ()
void conserve_global_volume ()
void get_dof_opposite_faces (unsigned int local_dof_id, std::vector< unsigned int > &local_opposite_faces)
void set_face_opposite_dofs_map ()
void set_face_dofs_map ()
void get_face_opposite_dofs (unsigned int local_face_id, std::vector< unsigned int > &local_opposite_dofs)
void get_face_local_dofs (unsigned int local_face_id, std::vector< unsigned int > &local_dofs)
void get_face_transformation_jacobian (const DerivativeForm< 1, dim, dim > &cell_transformation_jac, const unsigned int local_face_id, LAPACKFullMatrix< double > &face_transformation_jac)
Point< dim > transform_ref_face_point_to_ref_cell (const Point< dim - 1 > &x_ref_face, const unsigned int local_face_id)
void compute_residual (const Tensor< 1, dim > &x_n_to_x_I_real, const Tensor< 1, dim > &distance_gradient, const LAPACKFullMatrix< double > &transformation_jac, Tensor< 1, dim - 1 > &residual_ref)
void compute_numerical_jacobian_stencil (const Point< dim > x_ref, const unsigned int local_face_id, const double perturbation, std::vector< Point< dim > > &stencil)
Tensor< 1, dim > transform_ref_face_correction_to_ref_cell (const Vector< double > &correction_ref_face, const unsigned int local_face_id)
void compute_analytical_jacobian (const Tensor< 1, dim > &x_n_to_x_I_real_p1, const LAPACKFullMatrix< double > &transformation_jacobian, const std::vector< double > &face_local_dof_values, LAPACKFullMatrix< double > &jacobian_matrix)
double compute_distance (const Tensor< 1, dim > &x_n_to_x_I_real, const double distance)
Private Attributes
std::shared_ptr< FiniteElement< dim > > fe
std::shared_ptr< MappingQ< dim > > mapping
const double max_distance
const double iso_level
const double scaling
const Parameters::Verbosity verbosity
ConditionalOStream pcout
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
IndexSet locally_active_dofs
VectorType level_set
LinearAlgebra::distributed::Vector< double > signed_distance
GlobalVectorType signed_distance_output
LinearAlgebra::distributed::Vector< double > signed_distance_with_ghost
LinearAlgebra::distributed::Vector< double > distance
LinearAlgebra::distributed::Vector< double > distance_with_ghost
LinearAlgebra::distributed::Vector< double > volume_correction
AffineConstraints< double > constraints
std::map< types::global_cell_index, std::vector< Point< dim > > > interface_reconstruction_vertices
std::map< types::global_cell_index, std::vector< CellData< dim - 1 > > > interface_reconstruction_cells
std::set< types::global_dof_index > intersected_dofs
PVDHandler pvd_handler_reconstruction
PVDHandler pvd_handler_signed_distance
std::map< unsigned int, std::vector< unsigned int > > face_opposite_dofs_map
std::map< unsigned int, std::vector< unsigned int > > face_dofs_map
LAPACKFullMatrix< double > hessian_matrix
LAPACKFullMatrix< double > H_x_transformation_jacobian
Detailed Description
template<int dim, typename VectorType>
class InterfaceTools::SignedDistanceSolver< dim, VectorType >
Solver to compute the signed distance from a given level of a level-set field. It is based on the method proposed in the following article: Ausas, R.F., Dari, E.A. and Buscaglia, G.C. (2011), A geometric mass-preserving redistancing scheme for the level set function. Int. J. Numer. Meth. Fluids, 65: 989-1010. https://doi.org/10.1002/fld.2227.
Template Parameters
dim An integer that denotes the dimension of the space in which the problem is solved.
VectorType The vector type of the level-set vector.
Definition at line 383 of file interface_tools.h.
Constructor & Destructor Documentation
SignedDistanceSolver()
template<int dim, typename VectorType > InterfaceTools::SignedDistanceSolver< dim, VectorType >::SignedDistanceSolver (std::shared_ptr< parallel::DistributedTriangulationBase< dim > > background_triangulation, std::shared_ptr< FiniteElement< dim > > background_fe, const double p_max_distance, const double p_iso_level, const double p_scaling, const Parameters::Verbosity p_verbosity) inline
Base constructor.
Parameters
[in] background_triangulation Shared pointer to the triangulation of the domain
[in] background_fe Shared pointer to the finite element discretizing the domain
[in] p_max_distance Maximum reinitialization distance value
[in] p_iso_level Iso-level (before scaling) from which the signed distance is computed
[in] p_scaling Scaling factor to apply to the input level-set field. It is used to switch the inside and outside subdomains, if needed.
[in] p_verbosity Verbosity level
Definition at line 406 of file interface_tools.h.
References InterfaceTools::SignedDistanceSolver< dim, VectorType >::fe, InterfaceTools::SignedDistanceSolver< dim, VectorType >::H_x_transformation_jacobian, InterfaceTools::SignedDistanceSolver< dim, VectorType >::hessian_matrix, InterfaceTools::SignedDistanceSolver< dim, VectorType >::mapping, InterfaceTools::SignedDistanceSolver< dim, VectorType >::set_face_dofs_map(), and InterfaceTools::SignedDistanceSolver< dim, VectorType >::set_face_opposite_dofs_map().
Member Function Documentation
compute_analytical_jacobian()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::compute_analytical_jacobian (const Tensor< 1, dim > & x_n_to_x_I_real_p1, const LAPACKFullMatrix< double > & transformation_jacobian, const std::vector< double > & face_local_dof_values, LAPACKFullMatrix< double > & jacobian_matrix) inline private
Compute the analytical jacobian at the point x_n of the distance minimization problem for the DoF x_I in the reference face space (dim - 1): J_R = J^T*H*J, where J is the face transformation jacobian, and H is the Hessian matrix in the real space (H = H(d) + H(||x_I - x_n||)).
Parameters
[in] transformation_jacobian face transformation jacobian
[in] face_local_dof_values values of the DoFs of the face
[out] jacobian_matrix jacobian matrix of the minimization problem
Definition at line 890 of file interface_tools.h.
References InterfaceTools::SignedDistanceSolver< dim, VectorType >::H_x_transformation_jacobian, and InterfaceTools::SignedDistanceSolver< dim, VectorType >::hessian_matrix.
compute_cell_wise_volume_correction()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::compute_cell_wise_volume_correction () private
Compute the cell-wise volume correction to match the volume englobed by the given level of the level_set field in each element.
Definition at line 992 of file interface_tools.cc.
References InterfaceTools::compute_cell_wise_volume().
compute_distance()
template<int dim, typename VectorType > double InterfaceTools::SignedDistanceSolver< dim, VectorType >::compute_distance (const Tensor< 1, dim > & x_n_to_x_I_real, const double distance) inline private
Compute the distance according to: d(x_I) = d(x_n) + ||x_I - x_n||.
Parameters
[in] x_n_to_x_I_real vector from x_n to x_I in the real space
[in] distance value of the distance at the point x_n
Returns
distance between x_I and the interface
Definition at line 975 of file interface_tools.h.
References InterfaceTools::SignedDistanceSolver< dim, VectorType >::distance.
compute_first_neighbors_distance()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::compute_first_neighbors_distance () private
Compute the geometric distance (brute force) between the interface reconstruction and the DoFs of the intersected cells (first neighbors)
Definition at line 477 of file interface_tools.cc.
References LetheGridTools::find_point_triangle_distance().
compute_numerical_jacobian_stencil()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::compute_numerical_jacobian_stencil (const Point< dim > x_ref, const unsigned int local_face_id, const double perturbation, std::vector< Point< dim > > & stencil) inline private
Compute the stencil for the numerical jacobian of the distance minimization problem in the face where the problem is solved.
Parameters
[in] x_ref point in the reference cell space where the jacobian is evaluated
[in] local_face_id local id of the face in which the numerical jacobian is required
[in] perturbation value of the perturbation use for the numerical jacobian computation
Returns
vector containing the 2*dim - 1 stencil point. The entries of the vector are the following: 4
1 0 2
 3
The entry 0 is the current evaluation point x_ref
Definition at line 810 of file interface_tools.h.
compute_residual()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::compute_residual (const Tensor< 1, dim > & x_n_to_x_I_real, const Tensor< 1, dim > & distance_gradient, const LAPACKFullMatrix< double > & transformation_jac, Tensor< 1, dim - 1 > & residual_ref) inline private
Compute the residual at the point x_n of the distance minimization problem for the DoF x_I in the reference face space (dim - 1). In the real space the residual correspond to: R = grad(d) - (x_I - x_n)/||x_I - x_n||.
Parameters
[in] x_n_to_x_I_real vector from x_n to x_I in the real space
[in] distance_gradient gradient of the distance at the point x_n
[in] transformation_jac transformation jacobian of the face
[out] residual_ref residual in the reference face space
Definition at line 774 of file interface_tools.h.
compute_second_neighbors_distance()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::compute_second_neighbors_distance () private
Compute the geometric distance (marching method) between the interface reconstruction and the rest of the DoFs (second neighbors)
Definition at line 544 of file interface_tools.cc.
References Parameters::quiet, and LetheGridTools::vertices_cell_mapping().
compute_signed_distance_from_distance()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::compute_signed_distance_from_distance () private
Compute the signed_distance from the distance vector and the sign of the signed_distance vector entries.
Definition at line 961 of file interface_tools.cc.
References sgn().
conserve_global_volume()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::conserve_global_volume () private
Correct the global volume to match the volume englobed by the given level of the level_set field.
Definition at line 1168 of file interface_tools.cc.
References InterfaceTools::compute_surface_and_volume(), and Parameters::quiet.
exchange_distance()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::exchange_distance () private
Exchange the distance and set it to the minimum value across the processors by using the compress(VectorOperation::min) function.
Definition at line 448 of file interface_tools.cc.
gather_output_hook()
template<int dim, typename VectorType > std::vector< OutputStruct< dim, GlobalVectorType > > InterfaceTools::SignedDistanceSolver< dim, VectorType >::gather_output_hook ()
Gather and return vector of output structs that are particular to some applications.
Returns
Vector of OutputStructs that will be used to write the output results as VTU files.
Definition at line 1367 of file interface_tools.cc.
References convert_vector_dealii_to_trilinos().
get_dof_opposite_faces()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::get_dof_opposite_faces (unsigned int local_dof_id, std::vector< unsigned int > & local_opposite_faces) inline private
Return the local id of the opposite faces to the given local Dof (works for quad only).
Parameters
[in] local_dof_id Local id of the DoF in the cell
[out] local_opposite_faces The vector containing the id of the opposite faces
Definition at line 597 of file interface_tools.h.
get_face_local_dofs()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::get_face_local_dofs (unsigned int local_face_id, std::vector< unsigned int > & local_dofs) inline private
Return the local id of the face DoFs (works for quad only).
Parameters
[in] local_face_id Local id of the face in the cell
[out] local_dofs The vector containing the id of the local DoFs
Definition at line 685 of file interface_tools.h.
References InterfaceTools::SignedDistanceSolver< dim, VectorType >::face_dofs_map.
get_face_opposite_dofs()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::get_face_opposite_dofs (unsigned int local_face_id, std::vector< unsigned int > & local_opposite_dofs) inline private
Return the local id of the opposite DoFs to the given face (works for quad only).
Parameters
[in] local_face_id Local id of the face in the cell
[out] local_opposite_dofs The vector containing the id of the opposite DoFs
Definition at line 670 of file interface_tools.h.
References InterfaceTools::SignedDistanceSolver< dim, VectorType >::face_opposite_dofs_map.
get_face_transformation_jacobian()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::get_face_transformation_jacobian (const DerivativeForm< 1, dim, dim > & cell_transformation_jac, const unsigned int local_face_id, LAPACKFullMatrix< double > & face_transformation_jac) inline private
Return the face transformation jacobian (dim-1 x dim-1). This is required because the distance minimization problem is resolved in the reference face space (dim-1).
Parameters
[in] cell_transformation_jac transformation jacobian of the cell (dim x dim)
[in] local_face_id local id of the face
[out] face_transformation_jac face transformation jacobian (dim-1 x dim-1) faces
Definition at line 705 of file interface_tools.h.
get_signed_distance()
template<int dim, typename VectorType > VectorType & InterfaceTools::SignedDistanceSolver< dim, VectorType >::get_signed_distance ()
Get the computed signed distance field.
Returns
Reference to the vector storing the computed signed distance values.
Definition at line 400 of file interface_tools.cc.
initialize_distance()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::initialize_distance () private
Initialize the distance solution vectors to the given max_distance.
Definition at line 381 of file interface_tools.cc.
References sgn().
output_interface_reconstruction()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::output_interface_reconstruction (const std::string & output_name, const std::string & output_path, const double time, const unsigned int it)
Output the interface reconstruction used for signed distance computations.
This function writes the reconstructed interface vertices and cells to VTU files for visualization purposes.
Parameters
[in] output_name Name of the output file.
[in] output_path Path to the output directory.
[in] time Current simulation time.
[in] it Iteration number for file naming.
Definition at line 1318 of file interface_tools.cc.
References InterfaceTools::InterfaceReconstructionDataOut< dim >::build_patches(), and write_vtu_and_pvd().
output_signed_distance()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::output_signed_distance (const std::string & output_name, const std::string & output_path, const double time, const unsigned int it)
Output the signed distance field for visualization.
This function writes the computed signed distance field to VTU files for post-processing and visualization.
Parameters
[in] output_name Name of the output file.
[in] output_path Path to the output directory.
[in] time Current simulation time.
[in] it Iteration number for file naming.
Definition at line 1341 of file interface_tools.cc.
References write_vtu_and_pvd().
set_face_dofs_map()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::set_face_dofs_map () inline private
Set the map of local id of the face DoFs (works for quad only).
Definition at line 639 of file interface_tools.h.
References InterfaceTools::SignedDistanceSolver< dim, VectorType >::face_dofs_map.
set_face_opposite_dofs_map()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::set_face_opposite_dofs_map () inline private
Set the map of local id of the opposite DoFs to the given face (works for quad only).
Definition at line 614 of file interface_tools.h.
References InterfaceTools::SignedDistanceSolver< dim, VectorType >::face_opposite_dofs_map.
set_level_set_from_background_mesh()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::set_level_set_from_background_mesh (const DoFHandler< dim > & background_dof_handler, const VectorType & background_level_set_vector)
Set the level-set field from the background mesh solver.
This function transfers the level-set field from the main solver to the signed distance solver. For example, when using geometric redistanciation of the VOF phase fraction, the level-set field comes from the VOF solver.
Parameters
[in] background_dof_handler DoFHandler corresponding to the level-set field solver.
[in] background_level_set_vector Level-set solution vector from the background solver.
Definition at line 308 of file interface_tools.cc.
setup_dofs()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::setup_dofs ()
Initialize the degrees of freedom and associated memory.
This function sets up the DoF handler, initializes the solution vectors, and configures the constraints for the signed distance solver.
Definition at line 269 of file interface_tools.cc.
solve()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::solve ()
Solve for the signed distance from the given level of the level-set vector.
This function computes the signed distance field using the method described in Ausas et al. (2011). The algorithm preserves the interface location while computing accurate distances throughout the domain.
Definition at line 330 of file interface_tools.cc.
References announce_string(), Parameters::quiet, and InterfaceTools::reconstruct_interface().
transform_ref_face_correction_to_ref_cell()
template<int dim, typename VectorType > Tensor< 1, dim > InterfaceTools::SignedDistanceSolver< dim, VectorType >::transform_ref_face_correction_to_ref_cell (const Vector< double > & correction_ref_face, const unsigned int local_face_id) inline private
Transform the Newton correction in a reference face to a tensor (dim) in the reference cell. This is required because the distance minimization problem is resolved in the reference face space (dim-1).
Parameters
[in] correction_ref_face Newton correction in the reference face
[in] local_face_id local id of the face
Returns
tensor dim in the reference cell
Definition at line 855 of file interface_tools.h.
transform_ref_face_point_to_ref_cell()
template<int dim, typename VectorType > Point< dim > InterfaceTools::SignedDistanceSolver< dim, VectorType >::transform_ref_face_point_to_ref_cell (const Point< dim - 1 > & x_ref_face, const unsigned int local_face_id) inline private
Transform a point dim-1 in a reference face to a point dim in the reference cell. This is required because the distance minimization problem is resolved in the reference face space (dim-1).
Parameters
[in] x_ref_face point dim-1 in the reference face
[in] local_face_id local id of the face
Returns
Point dim in the reference cell
Definition at line 738 of file interface_tools.h.
update_ghost_values()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::update_ghost_values () const private
Update the ghost DoFs entries of the solution vectors to gain read access to the ghost elements.
Definition at line 434 of file interface_tools.cc.
zero_out_ghost_values()
template<int dim, typename VectorType > void InterfaceTools::SignedDistanceSolver< dim, VectorType >::zero_out_ghost_values () const private
Zero the ghost DoFs entries of the solution vectors to gain write access to the ghost elements.
Definition at line 420 of file interface_tools.cc.
Member Data Documentation
constraints
template<int dim, typename VectorType > AffineConstraints<double> InterfaceTools::SignedDistanceSolver< dim, VectorType >::constraints private
Hanging node constraints.
Definition at line 1037 of file interface_tools.h.
distance
template<int dim, typename VectorType > LinearAlgebra::distributed::Vector<double> InterfaceTools::SignedDistanceSolver< dim, VectorType >::distance private
Solution vector of the distance (write only)
Definition at line 1026 of file interface_tools.h.
distance_with_ghost
template<int dim, typename VectorType > LinearAlgebra::distributed::Vector<double> InterfaceTools::SignedDistanceSolver< dim, VectorType >::distance_with_ghost private
Solution vector of the distance with ghost values (read-only version of distance)
Definition at line 1030 of file interface_tools.h.
dof_handler
template<int dim, typename VectorType > DoFHandler<dim> InterfaceTools::SignedDistanceSolver< dim, VectorType >::dof_handler
DoFHandler describing the problem.
Definition at line 522 of file interface_tools.h.
face_dofs_map
template<int dim, typename VectorType > std::map<unsigned int, std::vector<unsigned int> > InterfaceTools::SignedDistanceSolver< dim, VectorType >::face_dofs_map private
Definition at line 1060 of file interface_tools.h.
face_opposite_dofs_map
template<int dim, typename VectorType > std::map<unsigned int, std::vector<unsigned int> > InterfaceTools::SignedDistanceSolver< dim, VectorType >::face_opposite_dofs_map private
Definition at line 1058 of file interface_tools.h.
fe
template<int dim, typename VectorType > std::shared_ptr<FiniteElement<dim> > InterfaceTools::SignedDistanceSolver< dim, VectorType >::fe private
Finite element discretizing the problem.
Definition at line 982 of file interface_tools.h.
H_x_transformation_jacobian
template<int dim, typename VectorType > LAPACKFullMatrix<double> InterfaceTools::SignedDistanceSolver< dim, VectorType >::H_x_transformation_jacobian private
Definition at line 1063 of file interface_tools.h.
hessian_matrix
template<int dim, typename VectorType > LAPACKFullMatrix<double> InterfaceTools::SignedDistanceSolver< dim, VectorType >::hessian_matrix private
Definition at line 1062 of file interface_tools.h.
interface_reconstruction_cells
template<int dim, typename VectorType > std::map<types::global_cell_index, std::vector<CellData<dim - 1> > > InterfaceTools::SignedDistanceSolver< dim, VectorType >::interface_reconstruction_cells private
Surface cells of the interface reconstruction stored in a cell-wise map (volume cell)
Definition at line 1047 of file interface_tools.h.
interface_reconstruction_vertices
template<int dim, typename VectorType > std::map<types::global_cell_index, std::vector<Point<dim> > > InterfaceTools::SignedDistanceSolver< dim, VectorType >::interface_reconstruction_vertices private
Surface vertices of the interface reconstruction stored in a cell-wise map (volume cell)
Definition at line 1042 of file interface_tools.h.
intersected_dofs
template<int dim, typename VectorType > std::set<types::global_dof_index> InterfaceTools::SignedDistanceSolver< dim, VectorType >::intersected_dofs private
Set of DoFs belonging to intersected cells.
Definition at line 1050 of file interface_tools.h.
iso_level
template<int dim, typename VectorType > const double InterfaceTools::SignedDistanceSolver< dim, VectorType >::iso_level private
Iso-level describing the interface from which the signed distance is computed (after scaling!!)
Definition at line 992 of file interface_tools.h.
level_set
template<int dim, typename VectorType > VectorType InterfaceTools::SignedDistanceSolver< dim, VectorType >::level_set private
Level-set field coming from the main solver.
Definition at line 1013 of file interface_tools.h.
locally_active_dofs
template<int dim, typename VectorType > IndexSet InterfaceTools::SignedDistanceSolver< dim, VectorType >::locally_active_dofs private
Set of locally active DoFs.
Definition at line 1010 of file interface_tools.h.
locally_owned_dofs
template<int dim, typename VectorType > IndexSet InterfaceTools::SignedDistanceSolver< dim, VectorType >::locally_owned_dofs private
Set of locally owned DoFs.
Definition at line 1004 of file interface_tools.h.
locally_relevant_dofs
template<int dim, typename VectorType > IndexSet InterfaceTools::SignedDistanceSolver< dim, VectorType >::locally_relevant_dofs private
Set of locally relevant DoFs.
Definition at line 1007 of file interface_tools.h.
mapping
template<int dim, typename VectorType > std::shared_ptr<MappingQ<dim> > InterfaceTools::SignedDistanceSolver< dim, VectorType >::mapping private
Mapping between the real and reference space.
Definition at line 985 of file interface_tools.h.
max_distance
template<int dim, typename VectorType > const double InterfaceTools::SignedDistanceSolver< dim, VectorType >::max_distance private
Maximum redistanciation distance.
Definition at line 988 of file interface_tools.h.
pcout
template<int dim, typename VectorType > ConditionalOStream InterfaceTools::SignedDistanceSolver< dim, VectorType >::pcout private
Parallel output stream.
Definition at line 1001 of file interface_tools.h.
pvd_handler_reconstruction
template<int dim, typename VectorType > PVDHandler InterfaceTools::SignedDistanceSolver< dim, VectorType >::pvd_handler_reconstruction private
PVDHandler for interface reconstruction.
Definition at line 1053 of file interface_tools.h.
pvd_handler_signed_distance
template<int dim, typename VectorType > PVDHandler InterfaceTools::SignedDistanceSolver< dim, VectorType >::pvd_handler_signed_distance private
PVDHandler for signed distance.
Definition at line 1056 of file interface_tools.h.
scaling
template<int dim, typename VectorType > const double InterfaceTools::SignedDistanceSolver< dim, VectorType >::scaling private
Scaling factor to apply to the input level-set field.
Definition at line 995 of file interface_tools.h.
signed_distance
template<int dim, typename VectorType > LinearAlgebra::distributed::Vector<double> InterfaceTools::SignedDistanceSolver< dim, VectorType >::signed_distance private
Solution vector of the signed distance (write only)
Definition at line 1016 of file interface_tools.h.
signed_distance_output
template<int dim, typename VectorType > GlobalVectorType InterfaceTools::SignedDistanceSolver< dim, VectorType >::signed_distance_output private
Solution vector of the signed distance as used for output only.
Definition at line 1019 of file interface_tools.h.
signed_distance_with_ghost
template<int dim, typename VectorType > LinearAlgebra::distributed::Vector<double> InterfaceTools::SignedDistanceSolver< dim, VectorType >::signed_distance_with_ghost private
Solution vector of the signed distance with ghost values (read-only version of signed_distance)
Definition at line 1023 of file interface_tools.h.
verbosity
template<int dim, typename VectorType > const Parameters::Verbosity InterfaceTools::SignedDistanceSolver< dim, VectorType >::verbosity private
Verbosity level.
Definition at line 998 of file interface_tools.h.
volume_correction
template<int dim, typename VectorType > LinearAlgebra::distributed::Vector<double> InterfaceTools::SignedDistanceSolver< dim, VectorType >::volume_correction private
Value of the correction to apply to the signed_distance to match the cell-wise volume encompassed by the level 0 of level_set
Definition at line 1034 of file interface_tools.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/interface_tools.h
/home/runner/work/lethe/lethe/source/core/interface_tools.cc