Lethe Open-Source Library: ParticleWallDMTForce< dim, PropertiesIndex > Class Template Reference
ParticleWallDMTForce< dim, PropertiesIndex > Class Template Reference
#include <particle_wall_dmt_force.h>
Public Member Functions
ParticleWallDMTForce (const DEMSolverParameters< dim > &dem_parameters, const std::vector< types::boundary_id > &boundary_index={})
virtual void calculate_particle_wall_contact_force (typename DEM::dem_data_structures< dim >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double dt, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force) override
virtual void calculate_particle_floating_wall_contact_force (typename DEM::dem_data_structures< dim >::particle_floating_mesh_in_contact &particle_floating_mesh_in_contact, const double dt, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force, const std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > &solids) override
Public Member Functions inherited from ParticleWallNonLinearForce< dim, PropertiesIndex >
ParticleWallNonLinearForce (const DEMSolverParameters< dim > &dem_parameters, const std::vector< types::boundary_id > &boundary_index={})
Public Member Functions inherited from ParticleWallContactForce< dim, PropertiesIndex >
ParticleWallContactForce (const DEMSolverParameters< dim > &dem_parameters)
virtual ~ParticleWallContactForce ()
std::map< types::boundary_id, Tensor< 1, 3 > > get_force ()
std::map< types::boundary_id, Tensor< 1, 3 > > get_torque ()
Tensor< 1, 3 > find_projection (const Tensor< 1, 3 > &vector_a, const Tensor< 1, 3 > &vector_b)
Private Types
using FuncPtrType = Tensor< 1, 3 >(ParticleWallDMTForce< dim, PropertiesIndex >::*)(const ArrayView< const double > &, const double, const double, const Tensor< 1, 3 > &)
Private Member Functions
Tensor< 1, 3 > no_resistance (const ArrayView< const double > &, const double, const double, const Tensor< 1, 3 > &)
Tensor< 1, 3 > constant_resistance (const ArrayView< const double > &particle_properties, const double effective_rolling_friction_coefficient, const double normal_force_norm, const Tensor< 1, 3 > &)
Tensor< 1, 3 > viscous_resistance (const ArrayView< const double > &particle_properties, const double effective_rolling_friction_coefficient, const double normal_force_norm, const Tensor< 1, 3 > &normal_contact_vector)
void initialize_particle_wall_properties (const DEMSolverParameters< dim > &dem_parameters)
double set_dmt_cut_off_distance ()
Private Attributes
FuncPtrType calculate_rolling_resistance_torque
const double dmt_cut_off_threshold
Additional Inherited Members
Protected Member Functions inherited from ParticleWallNonLinearForce< dim, PropertiesIndex >
std::tuple< Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 > > calculate_nonlinear_contact_force_and_torque (const double dt, particle_wall_contact_info< dim > &contact_info, const ArrayView< const double > &particle_properties)
Protected Member Functions inherited from ParticleWallContactForce< dim, PropertiesIndex >
void update_contact_information (particle_wall_contact_info< dim > &contact_pair_information, const Point< 3 > &particle_position, const ArrayView< const double > &particle_properties, const double dt)
void update_particle_floating_wall_contact_information (particle_wall_contact_info< dim > &contact_pair_information, const ArrayView< const double > &particle_properties, const double dt, const Tensor< 1, 3 > &cut_cell_translational_velocity, const Tensor< 1, 3 > &cut_cell_rotational_velocity, const double center_of_rotation_particle_distance)
void apply_force_and_torque (const std::tuple< Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 >, Tensor< 1, 3 > > &forces_and_torques, Tensor< 1, 3 > &particle_torque, Tensor< 1, 3 > &particle_force, const Point< 3 > &point_on_boundary, int boundary_id=0)
void calculate_force_and_torque_on_boundary (const unsigned int boundary_id, Tensor< 1, 3 > add_force, const Point< 3 > point_contact)
std::map< unsigned int, Tensor< 1, 3 > > initialize ()
void mpi_correction_over_calculation_of_forces_and_torques ()
Protected Attributes inherited from ParticleWallNonLinearForce< dim, PropertiesIndex >
const double f_coefficient_epsd
Protected Attributes inherited from ParticleWallContactForce< dim, PropertiesIndex >
double effective_radius
std::unordered_map< unsigned int, Tensor< 1, 3 > > boundary_translational_velocity_map
std::unordered_map< unsigned int, double > boundary_rotational_speed_map
std::unordered_map< unsigned int, Tensor< 1, 3 > > boundary_rotational_vector
std::unordered_map< unsigned int, Point< 3 > > point_on_rotation_vector
unsigned int n_particle_types
std::vector< double > effective_youngs_modulus
std::vector< double > effective_shear_modulus
std::vector< double > effective_coefficient_of_restitution
std::vector< double > effective_coefficient_of_friction
std::vector< double > effective_coefficient_of_rolling_friction
std::vector< double > effective_coefficient_of_rolling_viscous_damping
std::vector< double > effective_surface_energy
std::vector< double > effective_hamaker_constant
std::vector< double > model_parameter_beta
std::map< unsigned int, Tensor< 1, 3 > > force_on_walls
std::map< unsigned int, Tensor< 1, 3 > > torque_on_walls
bool calculate_force_torque_on_boundary
Point< 3 > center_mass_container
std::vector< types::boundary_id > boundary_index
const unsigned int vertices_per_triangle = 3
Detailed Description
template<int dim, typename PropertiesIndex>
class ParticleWallDMTForce< dim, PropertiesIndex >
Calculation of the DMT particle-wall contact force using the information obtained from the fine search and physical properties of particles and walls.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Definition at line 29 of file particle_wall_dmt_force.h.
Member Typedef Documentation
FuncPtrType
template<int dim, typename PropertiesIndex > using ParticleWallDMTForce< dim, PropertiesIndex >::FuncPtrType = Tensor<1, 3> (ParticleWallDMTForce<dim, PropertiesIndex>::*)(const ArrayView<const double> &, const double, const double, const Tensor<1, 3> &) private
Definition at line 32 of file particle_wall_dmt_force.h.
Constructor & Destructor Documentation
ParticleWallDMTForce()
template<int dim, typename PropertiesIndex > ParticleWallDMTForce< dim, PropertiesIndex >::ParticleWallDMTForce (const DEMSolverParameters< dim > & dem_parameters, const std::vector< types::boundary_id > & boundary_index = {})
Definition at line 11 of file particle_wall_dmt_force.cc.
References ParticleWallContactForce< dim, PropertiesIndex >::boundary_index, ParticleWallContactForce< dim, PropertiesIndex >::calculate_force_torque_on_boundary, ParticleWallDMTForce< dim, PropertiesIndex >::calculate_rolling_resistance_torque, ParticleWallContactForce< dim, PropertiesIndex >::center_mass_container, Parameters::Lagrangian::constant_resistance, ParticleWallContactForce< dim, PropertiesIndex >::force_on_walls, DEMSolverParameters< dim >::forces_torques, ParticleWallContactForce< dim, PropertiesIndex >::initialize(), ParticleWallDMTForce< dim, PropertiesIndex >::initialize_particle_wall_properties(), DEMSolverParameters< dim >::model_parameters, Parameters::Lagrangian::no_resistance, Parameters::Lagrangian::ModelParameters::rolling_resistance_method, ParticleWallContactForce< dim, PropertiesIndex >::torque_on_walls, and Parameters::Lagrangian::viscous_resistance.
Member Function Documentation
calculate_particle_floating_wall_contact_force()
template<int dim, typename PropertiesIndex > void ParticleWallDMTForce< dim, PropertiesIndex >::calculate_particle_floating_wall_contact_force (typename DEM::dem_data_structures< dim >::particle_floating_mesh_in_contact & particle_floating_mesh_in_contact, const double dt, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force, const std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > & solids) override virtual
Carries out the calculation of particle-floating mesh contact force using DMT model.
Parameters
particle_floating_mesh_in_contact A container that stores the information of particle-floating mesh contact
dt DEM time step
torque Torque acting on particles
force Force acting on particles
solids Floating solids
Reimplemented from ParticleWallNonLinearForce< dim, PropertiesIndex >.
Definition at line 242 of file particle_wall_dmt_force.cc.
References point_nd_to_3d().
calculate_particle_wall_contact_force()
template<int dim, typename PropertiesIndex > void ParticleWallDMTForce< dim, PropertiesIndex >::calculate_particle_wall_contact_force (typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double dt, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force) override virtual
Carries out the calculation of the particle-wall contact force using DMT model.
Parameters
particle_wall_pairs_in_contact Required information for the calculation of the particle-wall contact force. These information were obtained in the fine search
dt DEM time step
torque Torque acting on particles
force Force acting on particles
Reimplemented from ParticleWallNonLinearForce< dim, PropertiesIndex >.
Definition at line 46 of file particle_wall_dmt_force.cc.
References ParticleWallContactForce< dim, PropertiesIndex >::initialize(), and point_nd_to_3d().
constant_resistance()
template<int dim, typename PropertiesIndex > Tensor< 1, 3 > ParticleWallDMTForce< dim, PropertiesIndex >::constant_resistance (const ArrayView< const double > & particle_properties, const double effective_rolling_friction_coefficient, const double normal_force_norm, const Tensor< 1, 3 > &) inline private
Carries out calculation of the rolling resistance torque using the constant model.
Parameters
particle_properties Particle properties
effective_rolling_friction_coefficient Effective rolling friction coefficient
normal_force_norm Normal force norm
Returns
rolling resistance torque
Definition at line 116 of file particle_wall_dmt_force.h.
initialize_particle_wall_properties()
template<int dim, typename PropertiesIndex > void ParticleWallDMTForce< dim, PropertiesIndex >::initialize_particle_wall_properties (const DEMSolverParameters< dim > & dem_parameters) inline private
Initialize every particle-wall properties required for the force calculation. This function is required for the DMT force model, since the dmt_cut_off_distance attribute needs the be set to const. To do so, the effective surface energy and of the effective hamaker contant need to be initialized before hand. For code clarity, we also initialized every other parameter, otherwise the initialization would take place at two different places in the code.
Parameters
[in] dem_parameters DEM parameters declared in the .prm file
Definition at line 205 of file particle_wall_dmt_force.h.
References ParticleWallContactForce< dim, PropertiesIndex >::effective_coefficient_of_friction, ParticleWallContactForce< dim, PropertiesIndex >::effective_coefficient_of_restitution, ParticleWallContactForce< dim, PropertiesIndex >::effective_coefficient_of_rolling_friction, ParticleWallContactForce< dim, PropertiesIndex >::effective_coefficient_of_rolling_viscous_damping, ParticleWallContactForce< dim, PropertiesIndex >::effective_hamaker_constant, ParticleWallContactForce< dim, PropertiesIndex >::effective_shear_modulus, ParticleWallContactForce< dim, PropertiesIndex >::effective_surface_energy, ParticleWallContactForce< dim, PropertiesIndex >::effective_youngs_modulus, Parameters::Lagrangian::LagrangianPhysicalProperties::friction_coefficient_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::friction_coefficient_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::hamaker_constant_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::hamaker_constant_wall, DEMSolverParameters< dim >::lagrangian_physical_properties, ParticleWallContactForce< dim, PropertiesIndex >::model_parameter_beta, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number, Parameters::Lagrangian::LagrangianPhysicalProperties::poisson_ratio_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::poisson_ratio_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::restitution_coefficient_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::restitution_coefficient_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_friction_coefficient_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_friction_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_viscous_damping_coefficient_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_viscous_damping_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::surface_energy_particle, Parameters::Lagrangian::LagrangianPhysicalProperties::surface_energy_wall, Parameters::Lagrangian::LagrangianPhysicalProperties::youngs_modulus_particle, and Parameters::Lagrangian::LagrangianPhysicalProperties::youngs_modulus_wall.
no_resistance()
template<int dim, typename PropertiesIndex > Tensor< 1, 3 > ParticleWallDMTForce< dim, PropertiesIndex >::no_resistance (const ArrayView< const double > & , const double , const double , const Tensor< 1, 3 > &) inline private
Carries out calculation of the rolling resistance torque using the no resistance model.
Parameters
particle_properties Particle properties
effective_rolling_friction_coefficient Effective rolling friction coefficient
normal_force_norm Normal force norm
Returns
rolling resistance torque
Definition at line 96 of file particle_wall_dmt_force.h.
set_dmt_cut_off_distance()
template<int dim, typename PropertiesIndex > double ParticleWallDMTForce< dim, PropertiesIndex >::set_dmt_cut_off_distance () inline private
This function uses the effective surface energy and effective hamaker constant to compute the cut off distance for the force calculation.
Parameters
[in] dem_parameters DEM parameters declared in the .prm file
Returns
Cut off distance for the force calculation.
Definition at line 322 of file particle_wall_dmt_force.h.
References ParticleWallDMTForce< dim, PropertiesIndex >::dmt_cut_off_threshold, ParticleWallContactForce< dim, PropertiesIndex >::effective_hamaker_constant, and ParticleWallContactForce< dim, PropertiesIndex >::effective_surface_energy.
viscous_resistance()
template<int dim, typename PropertiesIndex > Tensor< 1, 3 > ParticleWallDMTForce< dim, PropertiesIndex >::viscous_resistance (const ArrayView< const double > & particle_properties, const double effective_rolling_friction_coefficient, const double normal_force_norm, const Tensor< 1, 3 > & normal_contact_vector) inline private
Carries out calculation of the rolling resistance torque using the viscous model.
Parameters
particle_properties Particle properties
effective_rolling_friction_coefficient Effective rolling friction coefficient
normal_force_norm Normal force norm
Returns
rolling resistance torque
Definition at line 157 of file particle_wall_dmt_force.h.
Member Data Documentation
calculate_rolling_resistance_torque
template<int dim, typename PropertiesIndex > FuncPtrType ParticleWallDMTForce< dim, PropertiesIndex >::calculate_rolling_resistance_torque private
Definition at line 38 of file particle_wall_dmt_force.h.
dmt_cut_off_threshold
template<int dim, typename PropertiesIndex > const double ParticleWallDMTForce< dim, PropertiesIndex >::dmt_cut_off_threshold private
Definition at line 341 of file particle_wall_dmt_force.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/particle_wall_dmt_force.h
/home/runner/work/lethe/lethe/source/dem/particle_wall_dmt_force.cc