Lethe Open-Source Library: RPTCalculatingParameters Class Reference
RPTCalculatingParameters Class Reference
#include <rpt_calculating_parameters.h>
Public Member Functions
RPTCalculatingParameters ()
void declare (ParameterHandler &prm)
void parse (ParameterHandler &prm)
Public Attributes
Parameters::RPTParameters rpt_param
Parameters::RPTTuningParameters tuning_param
Parameters::DetectorParameters detector_param
Parameters::RPTReconstructionParameters reconstruction_param
Parameters::RPTFEMReconstructionParameters fem_reconstruction_param
Detailed Description
Handles all the parameters declared in the parameter handler file for the RPT.
Definition at line 18 of file rpt_calculating_parameters.h.
Constructor & Destructor Documentation
RPTCalculatingParameters()
RPTCalculatingParameters::RPTCalculatingParameters () inline
Definition at line 21 of file rpt_calculating_parameters.h.
Member Function Documentation
declare()
void RPTCalculatingParameters::declare (ParameterHandler & prm)
Definition at line 7 of file rpt_calculating_parameters.cc.
References Parameters::RPTParameters::declare_parameters(), Parameters::RPTTuningParameters::declare_parameters(), Parameters::DetectorParameters::declare_parameters(), Parameters::RPTReconstructionParameters::declare_parameters(), and Parameters::RPTFEMReconstructionParameters::declare_parameters().
parse()
void RPTCalculatingParameters::parse (ParameterHandler & prm)
Definition at line 23 of file rpt_calculating_parameters.cc.
References detector_param, fem_reconstruction_param, Parameters::RPTParameters::parse_parameters(), Parameters::RPTTuningParameters::parse_parameters(), Parameters::DetectorParameters::parse_parameters(), Parameters::RPTReconstructionParameters::parse_parameters(), Parameters::RPTFEMReconstructionParameters::parse_parameters(), reconstruction_param, rpt_param, and tuning_param.
Member Data Documentation
detector_param
Parameters::DetectorParameters RPTCalculatingParameters::detector_param
Definition at line 32 of file rpt_calculating_parameters.h.
fem_reconstruction_param
Parameters::RPTFEMReconstructionParameters RPTCalculatingParameters::fem_reconstruction_param
Definition at line 34 of file rpt_calculating_parameters.h.
reconstruction_param
Parameters::RPTReconstructionParameters RPTCalculatingParameters::reconstruction_param
Definition at line 33 of file rpt_calculating_parameters.h.
rpt_param
Parameters::RPTParameters RPTCalculatingParameters::rpt_param
Definition at line 30 of file rpt_calculating_parameters.h.
tuning_param
Parameters::RPTTuningParameters RPTCalculatingParameters::tuning_param
Definition at line 31 of file rpt_calculating_parameters.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/rpt/rpt_calculating_parameters.h
/home/runner/work/lethe/lethe/source/rpt/rpt_calculating_parameters.cc