Lethe Open-Source Library: HeatTransferScratchData< dim > Class Template Reference
HeatTransferScratchData< dim > Class Template Reference
#include <heat_transfer_scratch_data.h>
Public Member Functions
HeatTransferScratchData (const PhysicalPropertiesManager properties_manager, const FiniteElement< dim > &fe_ht, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const FiniteElement< dim > &fe_fd, const Quadrature< dim - 1 > &face_quadrature, const double delta_T_ref)
HeatTransferScratchData (const HeatTransferScratchData< dim > &sd)
void allocate () override
template<typename VectorType >
void reinit (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const std::vector< GlobalVectorType > &previous_solutions, Function< dim > *source_function)
template<typename VectorType >
void reinit_fluid_dynamics (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_solution, const Parameters::ALE< dim > &ale)
template<typename VectorType >
void reinit_velocity_gradient (const VectorType &current_solution)
void enable_vof (const FiniteElement< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const Parameters::VOF_PhaseFilter &phase_filter_parameters)
void enable_vof (const FiniteElement< dim > &fe, const Quadrature< dim > &quadrature, const Mapping< dim > &mapping, const std::shared_ptr< VolumeOfFluidFilterBase > &filter)
template<typename VectorType >
void reinit_vof (const typename DoFHandler< dim >::active_cell_iterator &cell, const VectorType &current_filtered_solution)
void calculate_physical_properties ()
Public Attributes
PhysicalPropertiesManager properties_manager
std::map< field, std::vector< double > > fields
dealii::types::material_id material_id
std::vector< double > specific_heat
std::vector< double > thermal_conductivity
std::vector< double > density
std::vector< double > dynamic_viscosity
std::vector< double > grad_specific_heat_temperature
std::vector< double > specific_heat_0
std::vector< double > thermal_conductivity_0
std::vector< double > density_0
std::vector< double > dynamic_viscosity_0
std::vector< double > grad_specific_heat_temperature_0
std::vector< double > specific_heat_1
std::vector< double > thermal_conductivity_1
std::vector< double > density_1
std::vector< double > dynamic_viscosity_1
std::vector< double > grad_specific_heat_temperature_1
FEValues< dim > fe_values_T
unsigned int n_dofs
unsigned int n_q_points
double cell_size
std::vector< double > JxW
std::vector< Point< dim > > quadrature_points
std::vector< double > present_temperature_values
std::vector< Tensor< 1, dim > > temperature_gradients
std::vector< double > present_temperature_laplacians
std::vector< double > present_face_temperature_values
std::vector< std::vector< double > > previous_temperature_values
std::vector< std::vector< Tensor< 1, dim > > > previous_temperature_gradients
double global_delta_T_ref
std::vector< std::vector< double > > phi_T
std::vector< std::vector< Tensor< 1, dim > > > grad_phi_T
std::vector< std::vector< Tensor< 2, dim > > > hess_phi_T
std::vector< std::vector< double > > laplacian_phi_T
std::vector< double > source
bool gather_vof
unsigned int n_dofs_vof
std::vector< double > filtered_phase_values
std::vector< Tensor< 1, dim > > filtered_phase_gradient_values
std::shared_ptr< FEValues< dim > > fe_values_vof
std::shared_ptr< VolumeOfFluidFilterBase > filter
const FEValuesExtractors::Vector velocities
const FEValuesExtractors::Scalar pressure
FEValues< dim > fe_values_fd
std::vector< Tensor< 1, dim > > velocity_values
std::vector< Tensor< 2, dim > > velocity_gradient_values
std::vector< double > shear_rate_values
std::vector< double > pressure_values
FEFaceValues< dim > fe_face_values_ht
std::vector< std::vector< double > > face_JxW
unsigned int n_faces
unsigned int n_faces_q_points
bool is_boundary_cell
std::vector< bool > is_boundary_face
std::vector< unsigned int > boundary_face_id
std::vector< std::vector< std::vector< double > > > phi_face_T
std::vector< std::vector< double > > temperature_face_value
Detailed Description
template<int dim>
class HeatTransferScratchData< dim >
Class that stores the information required by the assembly procedure for a heat transfer advection-diffusion equation. Consequently, this class calculates the heat transfer (values, gradients, laplacians) and the shape function (values, gradients, laplacians) at all the gauss points for all degrees of freedom and stores it into arrays. Additionally, the user can request that this class gathers additional fields for physics which are coupled to the heat transfer equation, such as the velocity which is required. This class serves as a separation between the evaluation at the gauss point of the variables of interest and their use in the assembly, which is carried out by the assembler methods. For more information on this design, the reader can consult deal.II step-9 "https://www.dealii.org/current/doxygen/deal.II/step_9.html". In this latter example, the scratch is a struct instead of a templated class because of the simplicity of step-9.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 56 of file heat_transfer_scratch_data.h.
Constructor & Destructor Documentation
HeatTransferScratchData() [1/2]
template<int dim> HeatTransferScratchData< dim >::HeatTransferScratchData (const PhysicalPropertiesManager properties_manager, const FiniteElement< dim > & fe_ht, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const FiniteElement< dim > & fe_fd, const Quadrature< dim - 1 > & face_quadrature, const double delta_T_ref) inline
Constructor. The constructor creates the fe_values that will be used to fill the member variables of the scratch. It also allocated the necessary memory for all member variables. However, it does not do any evaluation, since this needs to be done at the cell level.
Parameters
properties_manager The physical properties Manager (see physical_properties_manager.h)
fe_ht The FESystem used to solve the Heat Transfer equations
quadrature The quadrature to use for the assembly
mapping The mapping of the domain in which the Navier-Stokes equations are solved
fe_fd The FESystem used to solve the Fluid Dynamics equations
face_quadrature_formula The face quadrature formula
Definition at line 78 of file heat_transfer_scratch_data.h.
References HeatTransferScratchData< dim >::allocate(), and HeatTransferScratchData< dim >::gather_vof.
HeatTransferScratchData() [2/2]
template<int dim> HeatTransferScratchData< dim >::HeatTransferScratchData (const HeatTransferScratchData< dim > & sd) inline
Copy Constructor. Same as the main constructor. This constructor only uses the other scratch to build the FeValues, it does not copy the content of the other scratch into itself since, by definition of the WorkStream mechanism, it is assumed that the content of the scratch will be reset on a cell basis.
Parameters
sd The scratch data
Definition at line 119 of file heat_transfer_scratch_data.h.
References HeatTransferScratchData< dim >::allocate(), HeatTransferScratchData< dim >::enable_vof(), HeatTransferScratchData< dim >::fe_values_vof, HeatTransferScratchData< dim >::filter, HeatTransferScratchData< dim >::gather_vof, and HeatTransferScratchData< dim >::global_delta_T_ref.
Member Function Documentation
allocate()
template<int dim> void HeatTransferScratchData< dim >::allocate () override virtual
Allocates the memory for the scratch.
This method allocates the necessary memory for all members of the scratch
Implements PhysicsScratchDataBase.
Definition at line 12 of file heat_transfer_scratch_data.cc.
References maximum_number_of_previous_solutions(), pressure, shear_rate, temperature, temperature_p1, and temperature_p2.
calculate_physical_properties()
template<int dim> void HeatTransferScratchData< dim >::calculate_physical_properties ()
Calculates the physical properties. This method calculates the physical properties that may be required by the heat transfer problem. Namely the density, specific heat, thermal conductivity and viscosity (for viscous dissipation).
Definition at line 147 of file heat_transfer_scratch_data.cc.
References calculate_point_property(), calculate_shear_rate_magnitude(), pressure, set_field_vector(), shear_rate, temperature, temperature_p1, and temperature_p2.
enable_vof() [1/2]
template<int dim> void HeatTransferScratchData< dim >::enable_vof (const FiniteElement< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const Parameters::VOF_PhaseFilter & phase_filter_parameters)
enable_vof Enables the collection of the VOF data by the scratch.
Parameters
fe FiniteElement associated with the VOF.
quadrature Quadrature rule of the Navier-Stokes problem assembly.
mapping Mapping used for the Navier-Stokes problem assembly
phase_filter_parameters Parameters for phase fraction filtering.
Definition at line 79 of file heat_transfer_scratch_data.cc.
References VolumeOfFluidFilterBase::model_cast().
enable_vof() [2/2]
template<int dim> void HeatTransferScratchData< dim >::enable_vof (const FiniteElement< dim > & fe, const Quadrature< dim > & quadrature, const Mapping< dim > & mapping, const std::shared_ptr< VolumeOfFluidFilterBase > & filter)
enable_vof Enables the collection of the VOF data by the scratch - function overload used in the copy constructor of HeatTransferScratchData
Parameters
fe FiniteElement associated with the VOF.
quadrature Quadrature rule of the Navier-Stokes problem assembly
mapping Mapping used for the Navier-Stokes problem assembly
filter Filter that is applied on the phase fraction
Definition at line 113 of file heat_transfer_scratch_data.cc.
reinit()
template<int dim> template<typename VectorType > void HeatTransferScratchData< dim >::reinit (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const std::vector< GlobalVectorType > & previous_solutions, Function< dim > * source_function) inline
Reinitializes the content of the scratch.
Using the FeValues and the content of the solutions, previous solutions, fills all of the class member of the scratch.
Template Parameters
VectorType The Vector type used for the solvers.
Parameters
[in] cell The cell over which the assembly is being carried. This cell must be compatible with the FE which is used to fill the FeValues.
[in] current_solution The present value of the solution for the Heat Transfer.
[in] previous_solutions The solutions at the previous time steps.
[in] source_function The function describing the Heat Transfer source term.
Definition at line 183 of file heat_transfer_scratch_data.h.
References HeatTransferScratchData< dim >::boundary_face_id, HeatTransferScratchData< dim >::cell_size, compute_cell_measure_with_JxW(), HeatTransferScratchData< dim >::face_JxW, HeatTransferScratchData< dim >::fe_face_values_ht, HeatTransferScratchData< dim >::fe_values_T, HeatTransferScratchData< dim >::grad_phi_T, HeatTransferScratchData< dim >::hess_phi_T, HeatTransferScratchData< dim >::is_boundary_cell, HeatTransferScratchData< dim >::is_boundary_face, HeatTransferScratchData< dim >::JxW, HeatTransferScratchData< dim >::laplacian_phi_T, HeatTransferScratchData< dim >::material_id, HeatTransferScratchData< dim >::n_dofs, HeatTransferScratchData< dim >::n_faces, HeatTransferScratchData< dim >::n_faces_q_points, HeatTransferScratchData< dim >::n_q_points, HeatTransferScratchData< dim >::phi_face_T, HeatTransferScratchData< dim >::phi_T, HeatTransferScratchData< dim >::present_temperature_laplacians, HeatTransferScratchData< dim >::present_temperature_values, HeatTransferScratchData< dim >::previous_temperature_gradients, HeatTransferScratchData< dim >::previous_temperature_values, HeatTransferScratchData< dim >::quadrature_points, HeatTransferScratchData< dim >::source, HeatTransferScratchData< dim >::temperature_face_value, and HeatTransferScratchData< dim >::temperature_gradients.
reinit_fluid_dynamics()
template<int dim> template<typename VectorType > void HeatTransferScratchData< dim >::reinit_fluid_dynamics (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_solution, const Parameters::ALE< dim > & ale) inline
Reinitialize cell's velocity and pressure values with values calculated in the Fluid Dynamics (FD) physic while also taking into account ALE for the velocity.
Template Parameters
VectorType Type of vector used for storing fluid dynamics solutions.
Parameters
[in] cell Pointer to an active cell for which the velocity and pressure are reinitialized.This cell must be compatible with the FD FiniteElement.
[in] current_solution Solution vector from FD containing velocity components and pressure values.
[in] ale The ALE parameters which include the ALE function
Definition at line 303 of file heat_transfer_scratch_data.h.
References PhysicalPropertiesManager::density_is_constant(), Parameters::ALE< dim >::enabled(), HeatTransferScratchData< dim >::fe_values_fd, HeatTransferScratchData< dim >::n_q_points, HeatTransferScratchData< dim >::pressure, HeatTransferScratchData< dim >::pressure_values, HeatTransferScratchData< dim >::properties_manager, HeatTransferScratchData< dim >::quadrature_points, HeatTransferScratchData< dim >::velocities, Parameters::ALE< dim >::velocity, and HeatTransferScratchData< dim >::velocity_values.
reinit_velocity_gradient()
template<int dim> template<typename VectorType > void HeatTransferScratchData< dim >::reinit_velocity_gradient (const VectorType & current_solution) inline
Reinitialize the velocity gradient, calculated by the Fluid Dynamics.
Template Parameters
VectorType The Vector type used for the solvers
Parameters
current_solution The present value of the solution for [u,p]
Definition at line 347 of file heat_transfer_scratch_data.h.
References HeatTransferScratchData< dim >::fe_values_fd, HeatTransferScratchData< dim >::velocities, and HeatTransferScratchData< dim >::velocity_gradient_values.
reinit_vof()
template<int dim> template<typename VectorType > void HeatTransferScratchData< dim >::reinit_vof (const typename DoFHandler< dim >::active_cell_iterator & cell, const VectorType & current_filtered_solution) inline
Reinitialize the content of the scratch for VOF.
Template Parameters
VectorType The Vector type used for the solvers
Parameters
cell The cell over which the assembly is being carried. This cell must be compatible with the VOF FE and not the Fluid Dynamics FE
current_solution The present solution for the phase value
NB: the previous_solutions are not used in heat_transfer_assemblers, contrary to navier_stokes_assemblers
Definition at line 405 of file heat_transfer_scratch_data.h.
References HeatTransferScratchData< dim >::fe_values_vof, HeatTransferScratchData< dim >::filtered_phase_gradient_values, and HeatTransferScratchData< dim >::filtered_phase_values.
Member Data Documentation
boundary_face_id
template<int dim> std::vector<unsigned int> HeatTransferScratchData< dim >::boundary_face_id
Definition at line 516 of file heat_transfer_scratch_data.h.
cell_size
template<int dim> double HeatTransferScratchData< dim >::cell_size
Definition at line 457 of file heat_transfer_scratch_data.h.
density
template<int dim> std::vector<double> HeatTransferScratchData< dim >::density
Definition at line 433 of file heat_transfer_scratch_data.h.
density_0
template<int dim> std::vector<double> HeatTransferScratchData< dim >::density_0
Definition at line 443 of file heat_transfer_scratch_data.h.
density_1
template<int dim> std::vector<double> HeatTransferScratchData< dim >::density_1
Definition at line 449 of file heat_transfer_scratch_data.h.
dynamic_viscosity
template<int dim> std::vector<double> HeatTransferScratchData< dim >::dynamic_viscosity
Definition at line 434 of file heat_transfer_scratch_data.h.
dynamic_viscosity_0
template<int dim> std::vector<double> HeatTransferScratchData< dim >::dynamic_viscosity_0
Definition at line 444 of file heat_transfer_scratch_data.h.
dynamic_viscosity_1
template<int dim> std::vector<double> HeatTransferScratchData< dim >::dynamic_viscosity_1
Definition at line 450 of file heat_transfer_scratch_data.h.
face_JxW
template<int dim> std::vector<std::vector<double> > HeatTransferScratchData< dim >::face_JxW
Definition at line 508 of file heat_transfer_scratch_data.h.
fe_face_values_ht
template<int dim> FEFaceValues<dim> HeatTransferScratchData< dim >::fe_face_values_ht
Definition at line 507 of file heat_transfer_scratch_data.h.
fe_values_fd
template<int dim> FEValues<dim> HeatTransferScratchData< dim >::fe_values_fd
Definition at line 499 of file heat_transfer_scratch_data.h.
fe_values_T
template<int dim> FEValues<dim> HeatTransferScratchData< dim >::fe_values_T
Definition at line 454 of file heat_transfer_scratch_data.h.
fe_values_vof
template<int dim> std::shared_ptr<FEValues<dim> > HeatTransferScratchData< dim >::fe_values_vof
Definition at line 490 of file heat_transfer_scratch_data.h.
fields
template<int dim> std::map<field, std::vector<double> > HeatTransferScratchData< dim >::fields
Definition at line 429 of file heat_transfer_scratch_data.h.
filter
template<int dim> std::shared_ptr<VolumeOfFluidFilterBase> HeatTransferScratchData< dim >::filter
Definition at line 491 of file heat_transfer_scratch_data.h.
filtered_phase_gradient_values
template<int dim> std::vector<Tensor<1, dim> > HeatTransferScratchData< dim >::filtered_phase_gradient_values
Definition at line 488 of file heat_transfer_scratch_data.h.
filtered_phase_values
template<int dim> std::vector<double> HeatTransferScratchData< dim >::filtered_phase_values
Definition at line 487 of file heat_transfer_scratch_data.h.
gather_vof
template<int dim> bool HeatTransferScratchData< dim >::gather_vof
Scratch component for the VOF auxiliary physics
Definition at line 485 of file heat_transfer_scratch_data.h.
global_delta_T_ref
template<int dim> double HeatTransferScratchData< dim >::global_delta_T_ref
Definition at line 471 of file heat_transfer_scratch_data.h.
grad_phi_T
template<int dim> std::vector<std::vector<Tensor<1, dim> > > HeatTransferScratchData< dim >::grad_phi_T
Definition at line 475 of file heat_transfer_scratch_data.h.
grad_specific_heat_temperature
template<int dim> std::vector<double> HeatTransferScratchData< dim >::grad_specific_heat_temperature
Definition at line 438 of file heat_transfer_scratch_data.h.
grad_specific_heat_temperature_0
template<int dim> std::vector<double> HeatTransferScratchData< dim >::grad_specific_heat_temperature_0
Definition at line 445 of file heat_transfer_scratch_data.h.
grad_specific_heat_temperature_1
template<int dim> std::vector<double> HeatTransferScratchData< dim >::grad_specific_heat_temperature_1
Definition at line 451 of file heat_transfer_scratch_data.h.
hess_phi_T
template<int dim> std::vector<std::vector<Tensor<2, dim> > > HeatTransferScratchData< dim >::hess_phi_T
Definition at line 476 of file heat_transfer_scratch_data.h.
is_boundary_cell
template<int dim> bool HeatTransferScratchData< dim >::is_boundary_cell
Definition at line 514 of file heat_transfer_scratch_data.h.
is_boundary_face
template<int dim> std::vector<bool> HeatTransferScratchData< dim >::is_boundary_face
Definition at line 515 of file heat_transfer_scratch_data.h.
JxW
template<int dim> std::vector<double> HeatTransferScratchData< dim >::JxW
Definition at line 461 of file heat_transfer_scratch_data.h.
laplacian_phi_T
template<int dim> std::vector<std::vector<double> > HeatTransferScratchData< dim >::laplacian_phi_T
Definition at line 477 of file heat_transfer_scratch_data.h.
material_id
template<int dim> dealii::types::material_id HeatTransferScratchData< dim >::material_id
Definition at line 430 of file heat_transfer_scratch_data.h.
n_dofs
template<int dim> unsigned int HeatTransferScratchData< dim >::n_dofs
Definition at line 455 of file heat_transfer_scratch_data.h.
n_dofs_vof
template<int dim> unsigned int HeatTransferScratchData< dim >::n_dofs_vof
Definition at line 486 of file heat_transfer_scratch_data.h.
n_faces
template<int dim> unsigned int HeatTransferScratchData< dim >::n_faces
Definition at line 510 of file heat_transfer_scratch_data.h.
n_faces_q_points
template<int dim> unsigned int HeatTransferScratchData< dim >::n_faces_q_points
Definition at line 511 of file heat_transfer_scratch_data.h.
n_q_points
template<int dim> unsigned int HeatTransferScratchData< dim >::n_q_points
Definition at line 456 of file heat_transfer_scratch_data.h.
phi_face_T
template<int dim> std::vector<std::vector<std::vector<double> > > HeatTransferScratchData< dim >::phi_face_T
Definition at line 520 of file heat_transfer_scratch_data.h.
phi_T
template<int dim> std::vector<std::vector<double> > HeatTransferScratchData< dim >::phi_T
Definition at line 474 of file heat_transfer_scratch_data.h.
present_face_temperature_values
template<int dim> std::vector<double> HeatTransferScratchData< dim >::present_face_temperature_values
Definition at line 468 of file heat_transfer_scratch_data.h.
present_temperature_laplacians
template<int dim> std::vector<double> HeatTransferScratchData< dim >::present_temperature_laplacians
Definition at line 467 of file heat_transfer_scratch_data.h.
present_temperature_values
template<int dim> std::vector<double> HeatTransferScratchData< dim >::present_temperature_values
Definition at line 465 of file heat_transfer_scratch_data.h.
pressure
template<int dim> const FEValuesExtractors::Scalar HeatTransferScratchData< dim >::pressure
Definition at line 497 of file heat_transfer_scratch_data.h.
pressure_values
template<int dim> std::vector<double> HeatTransferScratchData< dim >::pressure_values
Pressure field for physical property models requiring them.
Definition at line 504 of file heat_transfer_scratch_data.h.
previous_temperature_gradients
template<int dim> std::vector<std::vector<Tensor<1, dim> > > HeatTransferScratchData< dim >::previous_temperature_gradients
Definition at line 470 of file heat_transfer_scratch_data.h.
previous_temperature_values
template<int dim> std::vector<std::vector<double> > HeatTransferScratchData< dim >::previous_temperature_values
Definition at line 469 of file heat_transfer_scratch_data.h.
properties_manager
template<int dim> PhysicalPropertiesManager HeatTransferScratchData< dim >::properties_manager
Definition at line 428 of file heat_transfer_scratch_data.h.
quadrature_points
template<int dim> std::vector<Point<dim> > HeatTransferScratchData< dim >::quadrature_points
Definition at line 462 of file heat_transfer_scratch_data.h.
shear_rate_values
template<int dim> std::vector<double> HeatTransferScratchData< dim >::shear_rate_values
Definition at line 502 of file heat_transfer_scratch_data.h.
source
template<int dim> std::vector<double> HeatTransferScratchData< dim >::source
Definition at line 480 of file heat_transfer_scratch_data.h.
specific_heat
template<int dim> std::vector<double> HeatTransferScratchData< dim >::specific_heat
Definition at line 431 of file heat_transfer_scratch_data.h.
specific_heat_0
template<int dim> std::vector<double> HeatTransferScratchData< dim >::specific_heat_0
Definition at line 441 of file heat_transfer_scratch_data.h.
specific_heat_1
template<int dim> std::vector<double> HeatTransferScratchData< dim >::specific_heat_1
Definition at line 447 of file heat_transfer_scratch_data.h.
temperature_face_value
template<int dim> std::vector<std::vector<double> > HeatTransferScratchData< dim >::temperature_face_value
Definition at line 522 of file heat_transfer_scratch_data.h.
temperature_gradients
template<int dim> std::vector<Tensor<1, dim> > HeatTransferScratchData< dim >::temperature_gradients
Definition at line 466 of file heat_transfer_scratch_data.h.
thermal_conductivity
template<int dim> std::vector<double> HeatTransferScratchData< dim >::thermal_conductivity
Definition at line 432 of file heat_transfer_scratch_data.h.
thermal_conductivity_0
template<int dim> std::vector<double> HeatTransferScratchData< dim >::thermal_conductivity_0
Definition at line 442 of file heat_transfer_scratch_data.h.
thermal_conductivity_1
template<int dim> std::vector<double> HeatTransferScratchData< dim >::thermal_conductivity_1
Definition at line 448 of file heat_transfer_scratch_data.h.
velocities
template<int dim> const FEValuesExtractors::Vector HeatTransferScratchData< dim >::velocities
Scratch component for the Navier-Stokes components
Definition at line 496 of file heat_transfer_scratch_data.h.
velocity_gradient_values
template<int dim> std::vector<Tensor<2, dim> > HeatTransferScratchData< dim >::velocity_gradient_values
Definition at line 501 of file heat_transfer_scratch_data.h.
velocity_values
template<int dim> std::vector<Tensor<1, dim> > HeatTransferScratchData< dim >::velocity_values
Definition at line 500 of file heat_transfer_scratch_data.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/heat_transfer_scratch_data.h
/home/runner/work/lethe/lethe/source/solvers/heat_transfer_scratch_data.cc