Lethe Open-Source Library: ConservativeLevelSet< dim > Class Template Reference
ConservativeLevelSet< dim > Class Template Reference
#include <cls.h>
Public Member Functions
ConservativeLevelSet (MultiphysicsInterface< dim > *multiphysics_interface, const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control)
~ConservativeLevelSet ()=default
void assemble_rhs ()
virtual std::vector< OutputStruct< dim, GlobalVectorType > > gather_output_hook () override
double calculate_L2_error ()
template<typename VectorType >
void calculate_volume_and_mass (const GlobalVectorType &solution, const VectorType &current_solution_fd, const Parameters::FluidIndicator monitored_fluid)
template<typename VectorType >
Tensor< 1, dim > calculate_momentum (const GlobalVectorType &solution, const VectorType &current_solution_fd, const Parameters::FluidIndicator monitored_fluid)
template<typename VectorType >
std::pair< Tensor< 1, dim >, Tensor< 1, dim > > calculate_barycenter (const GlobalVectorType &solution, const VectorType &current_solution_fd)
double compute_capillary_time_step_constraint (const bool pressure_dependent, const bool temperature_dependent)
void finish_simulation () override
void percolate_time_vectors () override
void modify_solution () override
void postprocess (bool first_iteration) override
void pre_mesh_adaptation () override
void post_mesh_adaptation () override
void compute_error_estimate (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > &ivar, dealii::Vector< float > &estimated_error_per_cell) override
void compute_kelly (dealii::Vector< float > &estimated_error_per_cell, const ComponentMask &component_mask)
void write_checkpoint () override
void read_checkpoint () override
std::vector< OutputStructTableHandler > gather_tables () override
void setup_dofs () override
void define_zero_constraints ()
void define_non_zero_constraints ()
void set_initial_conditions () override
void update_boundary_conditions () override
void solve_linear_system () override
const DoFHandler< dim > & get_dof_handler () override
GlobalVectorType & get_evaluation_point () override
GlobalVectorType & get_local_evaluation_point () override
GlobalVectorType & get_newton_update () override
GlobalVectorType & get_present_solution () override
GlobalVectorType & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
const DoFHandler< dim > & get_projected_phase_indicator_gradient_dof_handler ()
const DoFHandler< dim > & get_curvature_dof_handler ()
const GlobalVectorType & get_projected_phase_indicator_gradient_solution ()
const GlobalVectorType & get_curvature_solution ()
void output_newton_update_norms () override
double get_residual_rescale_metric () const override
Public Member Functions inherited from AuxiliaryPhysics< dim, GlobalVectorType >
AuxiliaryPhysics (const Parameters::NonLinearSolver non_linear_solver_parameters)
AuxiliaryPhysics ()
virtual ~AuxiliaryPhysics ()
void setup_preconditioner () override
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
PhysicsSolver ()
virtual ~PhysicsSolver ()
void solve_governing_system ()
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void verify_consistency_of_boundary_conditions ()
void assemble_system_matrix () override
void assemble_system_matrix_cg ()
void assemble_system_matrix_dg ()
void assemble_system_rhs () override
void assemble_system_rhs_cg ()
void assemble_system_rhs_dg ()
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, CLSScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, CLSScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
virtual void setup_assemblers ()
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData &copy_data)
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData &copy_data)
void update_solution_and_constraints (GlobalVectorType &solution)
void assemble_L2_projection_interface_sharpening (GlobalVectorType &solution, const double sharpening_threshold)
void solve_interface_sharpening (GlobalVectorType &solution)
void assemble_mass_matrix (TrilinosWrappers::SparseMatrix &mass_matrix)
void handle_interface_sharpening ()
double find_sharpening_threshold ()
double calculate_mass_deviation (const Parameters::FluidIndicator monitored_fluid, const double sharpening_threshold)
void sharpen_interface (GlobalVectorType &solution, const double sharpening_threshold, const bool sharpen_previous_solutions)
void smooth_phase_indicator (GlobalVectorType &solution)
void assemble_projection_phase_indicator (GlobalVectorType &solution)
void solve_projection_phase_indicator (GlobalVectorType &solution)
void apply_phase_filter (const GlobalVectorType &original_solution, GlobalVectorType &filtered_solution)
void reinitialize_interface_with_pde_based_method ()
void compute_level_set_from_phase_indicator (const GlobalVectorType &solution, GlobalVectorType &level_set_solution)
void compute_phase_indicator_from_level_set (const GlobalVectorType &level_set_solution, GlobalVectorType &phase_indicator_solution)
void reinitialize_interface_with_geometric_method ()
void reinit_face_velocity_with_adequate_solution (const typename DoFHandler< dim >::active_cell_iterator &velocity_cell, const unsigned int &face_no, CLSScratchData< dim > &scratch_data)
Private Attributes
GlobalVectorType nodal_phase_indicator_owned
MultiphysicsInterface< dim > * multiphysics
TimerOutput computing_timer
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< SimulationControl > simulation_control
std::shared_ptr< DoFHandler< dim > > dof_handler
std::shared_ptr< FiniteElement< dim > > fe
ConvergenceTable error_table
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
std::shared_ptr< GlobalVectorType > present_solution
GlobalVectorType system_rhs
AffineConstraints< double > nonzero_constraints
AffineConstraints< double > bounding_constraints
AffineConstraints< double > zero_constraints
TrilinosWrappers::SparseMatrix system_matrix
std::shared_ptr< GlobalVectorType > filtered_solution
GlobalVectorType level_set
std::shared_ptr< std::vector< GlobalVectorType > > previous_solutions
std::shared_ptr< SolutionTransfer< dim, GlobalVectorType > > solution_transfer
std::vector< SolutionTransfer< dim, GlobalVectorType > > previous_solutions_transfer
TrilinosWrappers::SparseMatrix system_matrix_phase_indicator
TrilinosWrappers::SparseMatrix complete_system_matrix_phase_indicator
GlobalVectorType system_rhs_phase_indicator
GlobalVectorType complete_system_rhs_phase_indicator
TrilinosWrappers::SparseMatrix mass_matrix_phase_indicator
std::shared_ptr< CLSSubequationsInterface< dim > > cls_subequations_interface
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
const double phase_upper_bound = 1.0
const double phase_lower_bound = 0.0
TableHandler table_monitoring_cls
double volume_monitored
double mass_monitored
double mass_first_iteration
double sharpening_threshold
TableHandler table_barycenter
std::vector< std::shared_ptr< CLSAssemblerBase< dim > > > assemblers
std::shared_ptr< CLSAssemblerSIPG< dim > > inner_face_assembler
std::shared_ptr< ConservativeLevelSetFilterBase > filter
std::shared_ptr< InterfaceTools::SignedDistanceSolver< dim, GlobalVectorType > > signed_distance_solver
std::shared_ptr< SignedDistanceTransformationBase > signed_distance_transformation
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class ConservativeLevelSet< dim >
Definition at line 60 of file cls.h.
Constructor & Destructor Documentation
ConservativeLevelSet()
template<int dim> ConservativeLevelSet< dim >::ConservativeLevelSet (MultiphysicsInterface< dim > * multiphysics_interface, const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control)
CLS - Base constructor.
Definition at line 21 of file cls.cc.
References ConservativeLevelSet< dim >::cell_quadrature, ConservativeLevelSet< dim >::cls_subequations_interface, ConservativeLevelSet< dim >::face_quadrature, ConservativeLevelSet< dim >::fe, ConservativeLevelSet< dim >::filtered_solution, Parameters::geometric, ConservativeLevelSet< dim >::mapping, maximum_number_of_previous_solutions(), SignedDistanceTransformationBase::model_cast(), Parameters::none, PhysicsSolver< VectorType >::pcout, ConservativeLevelSet< dim >::present_solution, ConservativeLevelSet< dim >::previous_solutions, ConservativeLevelSet< dim >::previous_solutions_transfer, ConservativeLevelSet< dim >::signed_distance_solver, ConservativeLevelSet< dim >::signed_distance_transformation, ConservativeLevelSet< dim >::simulation_control, ConservativeLevelSet< dim >::simulation_parameters, ConservativeLevelSet< dim >::solution_transfer, and ConservativeLevelSet< dim >::triangulation.
~ConservativeLevelSet()
template<int dim> ConservativeLevelSet< dim >::~ConservativeLevelSet () default
CLS - Base destructor. At the present moment this is an interface with nothing.
Member Function Documentation
apply_phase_filter()
template<int dim> void ConservativeLevelSet< dim >::apply_phase_filter (const GlobalVectorType & original_solution, GlobalVectorType & filtered_solution) private
Apply filter on phase indicator values.
Parameters
[in] original_solution CLS solution vector to which the filter is to be applied.
[out] filtered_solution Solution vector with filtered phase indicator values.
Definition at line 3196 of file cls.cc.
References ConservativeLevelSetFilterBase::model_cast(), and Parameters::verbose.
assemble_L2_projection_interface_sharpening()
template<int dim> void ConservativeLevelSet< dim >::assemble_L2_projection_interface_sharpening (GlobalVectorType & solution, const double sharpening_threshold) private
Assemble the system for interface sharpening.
This function assembles the weak form of: \(\Phi = c ^ {(1 - \alpha)} * (\phi ^ \alpha)\) if \(0 <= \phi <= c \ \) \(\Phi = 1 - (1 - c) ^ {(1 - \alpha)} * (1 - \phi) ^ \alpha \) if \(c < \phi <= 1 \) Reference for sharpening method https://www.sciencedirect.com/science/article/pii/S0045782500002000
Parameters
solution CLS solution (phase indicator)
sharpening_threshold Interface sharpening threshold that represents the mass conservation level
Definition at line 3000 of file cls.cc.
assemble_local_system_matrix()
template<int dim> void ConservativeLevelSet< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, CLSScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for CLSScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 371 of file cls.cc.
References StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, CLSScratchData< dim >::reinit(), CLSScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_local_system_rhs()
template<int dim> void ConservativeLevelSet< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, CLSScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for CLSScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 616 of file cls.cc.
References StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, CLSScratchData< dim >::reinit(), CLSScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_mass_matrix()
template<int dim> void ConservativeLevelSet< dim >::assemble_mass_matrix (TrilinosWrappers::SparseMatrix & mass_matrix) private
Assembles a mass_matrix which is used in update_solution_and_constraints function to limit the phase indicators of cells in the range of [0,1] before sharpening the interface. More information can be found in step_41 of deal.II tutorials: https://www.dealii.org/current/doxygen/deal.II/step_41.html.
Parameters
mass_matrix
Definition at line 3161 of file cls.cc.
assemble_projection_phase_indicator()
template<int dim> void ConservativeLevelSet< dim >::assemble_projection_phase_indicator (GlobalVectorType & solution) private
Assembles the matrix and rhs for calculation of a smooth phase indicator using a projection.
Parameters
solution CLS solution (phase indicator)
Definition at line 2143 of file cls.cc.
References compute_cell_measure_with_JxW().
assemble_rhs()
template<int dim> void ConservativeLevelSet< dim >::assemble_rhs ()
Call for the assembly of the right-hand side.
Deprecated:
This function is to be deprecated when the new assembly mechanism is integrated to this solver
Definition at line 173 of file cls.cc.
assemble_system_matrix()
template<int dim> void ConservativeLevelSet< dim >::assemble_system_matrix () override private virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 224 of file cls.cc.
assemble_system_matrix_cg()
template<int dim> void ConservativeLevelSet< dim >::assemble_system_matrix_cg () private
Assemble the matrix associated with the solver when CG elements are used.
Definition at line 239 of file cls.cc.
References ConservativeLevelSet< dim >::assemble_local_system_matrix(), ConservativeLevelSet< dim >::copy_local_matrix_to_global_matrix(), and fluid_dynamics.
assemble_system_matrix_dg()
template<int dim> void ConservativeLevelSet< dim >::assemble_system_matrix_dg () private
Assemble the matrix associated with the solver when DG elements are used.
Definition at line 268 of file cls.cc.
References StabilizedDGMethodsCopyData::face_data, and fluid_dynamics.
assemble_system_rhs()
template<int dim> void ConservativeLevelSet< dim >::assemble_system_rhs () override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 472 of file cls.cc.
assemble_system_rhs_cg()
template<int dim> void ConservativeLevelSet< dim >::assemble_system_rhs_cg () private
Assemble the rhs associated with the solver when CG elements are used.
Definition at line 489 of file cls.cc.
References ConservativeLevelSet< dim >::assemble_local_system_rhs(), ConservativeLevelSet< dim >::copy_local_rhs_to_global_rhs(), and fluid_dynamics.
assemble_system_rhs_dg()
template<int dim> void ConservativeLevelSet< dim >::assemble_system_rhs_dg () private
Assemble the rhs associated with the solver when DG elements are used.
Definition at line 517 of file cls.cc.
References StabilizedDGMethodsCopyData::face_data, and fluid_dynamics.
calculate_barycenter()
template<int dim> template<typename VectorType > template std::pair< Tensor< 1, 3 >, Tensor< 1, 3 > > ConservativeLevelSet< dim >::calculate_barycenter< GlobalBlockVectorType > (const GlobalVectorType & solution, const VectorType & current_solution_fd)
Calculates the barycenter of the fluid and its velocity.
Parameters
[in] solution CLS solution
[in] current_solution_fd Fluid dynamics solution
Definition at line 865 of file cls.cc.
References fluid_dynamics, ConservativeLevelSetFilterBase::model_cast(), and velocity.
calculate_L2_error()
template<int dim> double ConservativeLevelSet< dim >::calculate_L2_error ()
Calculates the L2 error of the solution.
Definition at line 819 of file cls.cc.
calculate_mass_deviation()
template<int dim> double ConservativeLevelSet< dim >::calculate_mass_deviation (const Parameters::FluidIndicator monitored_fluid, const double sharpening_threshold) private
Calculate the mass deviation of the monitored fluid, between the current iteration and the mass at first iteration (mass_first_iteration). Used to test multiple sharpening threshold in the binary search algorithm (adaptive sharpening).
Parameters
monitored_fluid Fluid indicator (fluid0 or fluid1) corresponding to the phase of interest.
sharpening_threshold Interface sharpening threshold that represents the mass conservation level
Definition at line 2069 of file cls.cc.
References fluid_dynamics.
calculate_momentum()
template<int dim> template<typename VectorType > Tensor< 1, dim > ConservativeLevelSet< dim >::calculate_momentum (const GlobalVectorType & solution, const VectorType & current_solution_fd, const Parameters::FluidIndicator monitored_fluid)
Calculates the momentum for a given fluid phase. Used for conservation monitoring.
Parameters
[in] solution CLS solution (phase indicator)
[in] current_solution_fd current solution for the fluid dynamics
[in] monitored_fluid Fluid indicator (fluid0 or fluid1) corresponding to the phase of interest.
Returns
A tensor<1,dim> corresponding to the entry_string in the prm file.
Definition at line 1077 of file cls.cc.
References Parameters::fluid0, Parameters::fluid1, fluid_dynamics, pressure, set_field_vector(), and velocity.
calculate_volume_and_mass()
template<int dim> template<typename VectorType > void ConservativeLevelSet< dim >::calculate_volume_and_mass (const GlobalVectorType & solution, const VectorType & current_solution_fd, const Parameters::FluidIndicator monitored_fluid)
Calculates the volume and mass for a given fluid phase. Used for conservation monitoring.
Parameters
solution CLS solution (phase indicator)
current_solution_fd current solution for the fluid dynamics
monitored_fluid Fluid indicator (fluid0 or fluid1) corresponding to the phase of interest.
Definition at line 973 of file cls.cc.
References Parameters::fluid0, Parameters::fluid1, fluid_dynamics, pressure, and set_field_vector().
compute_capillary_time_step_constraint()
template<int dim> double ConservativeLevelSet< dim >::compute_capillary_time_step_constraint (const bool pressure_dependent, const bool temperature_dependent)
Computes the capillary time-step constraint.
The time-step constraint for capillary-driven multiphase flows is computed according to [1]:
\[ \Delta t_\sigma = \sqrt{\frac{(\rho_0 + \rho_1) h^3}{2 \pi \sigma}} \]
Parameters
[in] pressure_dependent Boolean indicating if the pressure field is required. The DensityIsothermalIdealGas model requires the pressure field to compute the density.
[in] temperature_dependent Boolean indicating if the temperature field is required. The SurfaceTensionLinear and SurfaceTensionPhaseChange models depend on the temperature field.
Returns
Computed value of the capillary time-step constraint
Reference:
[1] F. Denner, F. Evrard, and B. van Wachem, “Breaching the capillary time-step constraint using a coupled VOF method with implicit surface tension,” J. Comput. Phys., vol. 459, p. 111128, Jun. 2022, doi: 10.1016/j.jcp.2022.111128
Definition at line 1181 of file cls.cc.
References compute_cell_measure_with_JxW(), fluid_dynamics, heat_transfer, pressure, set_field_vector(), and temperature.
compute_error_estimate()
template<int dim> void ConservativeLevelSet< dim >::compute_error_estimate (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > & ivar, dealii::Vector< float > & estimated_error_per_cell) override virtual
Compute the error estimator for mesh refinement.
Parameters
[in] ivar The current element of the map simulation_parameters.mesh_adaptation.variables
[in,out] estimated_error_per_cell The deal.II vector of estimated_error_per_cell
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2349 of file cls.cc.
References Parameters::MultipleAdaptationParameters::kelly, and phase.
compute_kelly()
template<int dim> void ConservativeLevelSet< dim >::compute_kelly (dealii::Vector< float > & estimated_error_per_cell, const ComponentMask & component_mask)
Compute the Kelly error estimator on the phase variable for mesh refinement. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
Parameters
[in,out] estimated_error_per_cell The deal.II vector of estimated_error_per_cell
[in] component_mask The component mask corresponding to the phase variable
Definition at line 2372 of file cls.cc.
compute_level_set_from_phase_indicator()
template<int dim> void ConservativeLevelSet< dim >::compute_level_set_from_phase_indicator (const GlobalVectorType & solution, GlobalVectorType & level_set_solution) private
Compute level-set field from the phase indicator field using an inverse tanh-based transformation.
Parameters
[in] solution Phase indicator solution field
[out] level_set_solution Level-set solution field
Definition at line 3294 of file cls.cc.
References phase.
compute_phase_indicator_from_level_set()
template<int dim> void ConservativeLevelSet< dim >::compute_phase_indicator_from_level_set (const GlobalVectorType & level_set_solution, GlobalVectorType & phase_indicator_solution) private
Compute the phase indicator field from level-set field using a tanh-based transformation.
Parameters
[in] level_set_solution Level-set solution field
[out] phase_indicator_solution Phase indicator solution field
Definition at line 3315 of file cls.cc.
copy_local_matrix_to_global_matrix()
template<int dim> void ConservativeLevelSet< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell information to global matrix.
Definition at line 458 of file cls.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void ConservativeLevelSet< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell rhs information to global rhs.
Definition at line 703 of file cls.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_rhs.
define_non_zero_constraints()
template<int dim> void ConservativeLevelSet< dim >::define_non_zero_constraints ()
defined the non zero constraints used to solve the problem.
Definition at line 2701 of file cls.cc.
References BoundaryConditions::cls_dirichlet, and BoundaryConditions::periodic.
define_zero_constraints()
template<int dim> void ConservativeLevelSet< dim >::define_zero_constraints ()
defined the zero constraints used to solve the problem.
Definition at line 2662 of file cls.cc.
References BoundaryConditions::cls_dirichlet, and BoundaryConditions::periodic.
find_sharpening_threshold()
template<int dim> double ConservativeLevelSet< dim >::find_sharpening_threshold () private
Find the sharpening threshold to ensure mass conservation of the fluid monitored, as given in the prm (CLS, subsection monitoring), by binary search.
Definition at line 1943 of file cls.cc.
References Parameters::quiet.
finish_simulation()
template<int dim> void ConservativeLevelSet< dim >::finish_simulation () override virtual
Carry out the operations required to finish a simulation correctly.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1334 of file cls.cc.
References announce_string(), Parameters::Timer::end, Parameters::SimulationControl::steady, and Parameters::verbose.
gather_output_hook()
template<int dim> std::vector< OutputStruct< dim, GlobalVectorType > > ConservativeLevelSet< dim >::gather_output_hook () override virtual
Gather and return vector of output structs that are particular to some applications.
Returns
Vector of OutputStructs that will be used to write the output results as VTU files.
Reimplemented from AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 717 of file cls.cc.
References curvature_projection, and phase_gradient_projection.
gather_tables()
template<int dim> std::vector< OutputStructTableHandler > ConservativeLevelSet< dim >::gather_tables () override virtual
Returns a vector of references to TableHandler objects that needs to be serialized/deserialized for the CLS solver.
Returns
Structure containing a vector of references to TableHandler objects that needs to be serialized/deserialized for the CLS solver, and their corresponding file names.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2388 of file cls.cc.
get_curvature_dof_handler()
template<int dim> const DoFHandler< dim > & ConservativeLevelSet< dim >::get_curvature_dof_handler () inline
Definition at line 374 of file cls.h.
References ConservativeLevelSet< dim >::cls_subequations_interface, and curvature_projection.
get_curvature_solution()
template<int dim> const GlobalVectorType & ConservativeLevelSet< dim >::get_curvature_solution () inline
Definition at line 388 of file cls.h.
References ConservativeLevelSet< dim >::cls_subequations_interface, and curvature_projection.
get_dof_handler()
template<int dim> const DoFHandler< dim > & ConservativeLevelSet< dim >::get_dof_handler () inline override virtual
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 325 of file cls.h.
References ConservativeLevelSet< dim >::dof_handler.
get_evaluation_point()
template<int dim> GlobalVectorType & ConservativeLevelSet< dim >::get_evaluation_point () inline override virtual
Getter methods that give access to the private attributes of the physics being solved. These methods must be provided by the physics as they are the key to solve a problem using Lethe.
Implements PhysicsSolver< VectorType >.
Definition at line 331 of file cls.h.
References ConservativeLevelSet< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> GlobalVectorType & ConservativeLevelSet< dim >::get_local_evaluation_point () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 337 of file cls.h.
References ConservativeLevelSet< dim >::local_evaluation_point.
get_newton_update()
template<int dim> GlobalVectorType & ConservativeLevelSet< dim >::get_newton_update () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 343 of file cls.h.
References ConservativeLevelSet< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints< double > & ConservativeLevelSet< dim >::get_nonzero_constraints () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 361 of file cls.h.
References ConservativeLevelSet< dim >::nonzero_constraints.
get_present_solution()
template<int dim> GlobalVectorType & ConservativeLevelSet< dim >::get_present_solution () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 349 of file cls.h.
References ConservativeLevelSet< dim >::present_solution.
get_projected_phase_indicator_gradient_dof_handler()
template<int dim> const DoFHandler< dim > & ConservativeLevelSet< dim >::get_projected_phase_indicator_gradient_dof_handler () inline
Definition at line 367 of file cls.h.
References ConservativeLevelSet< dim >::cls_subequations_interface, and phase_gradient_projection.
get_projected_phase_indicator_gradient_solution()
template<int dim> const GlobalVectorType & ConservativeLevelSet< dim >::get_projected_phase_indicator_gradient_solution () inline
Definition at line 381 of file cls.h.
References ConservativeLevelSet< dim >::cls_subequations_interface, and phase_gradient_projection.
get_residual_rescale_metric()
template<int dim> double ConservativeLevelSet< dim >::get_residual_rescale_metric () const inline override virtual
Return the metric for residual rescaling. By default, should return 1. If the rescale_residual_by_volume is set to true, the method returns the square root of the global volume of the triangulation.
Returns
Rescale metric.
Implements PhysicsSolver< VectorType >.
Definition at line 413 of file cls.h.
References CLS, ConservativeLevelSet< dim >::mapping, ConservativeLevelSet< dim >::simulation_parameters, and ConservativeLevelSet< dim >::triangulation.
get_system_rhs()
template<int dim> GlobalVectorType & ConservativeLevelSet< dim >::get_system_rhs () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 355 of file cls.h.
References ConservativeLevelSet< dim >::system_rhs.
handle_interface_sharpening()
template<int dim> void ConservativeLevelSet< dim >::handle_interface_sharpening () private
Carries out interface sharpening. It is called in the modify solution function. Launches sharpen_interface with the possibility to ensure conservation and handles output messages.
Definition at line 1901 of file cls.cc.
References Parameters::adaptive, and Parameters::quiet.
modify_solution()
template<int dim> void ConservativeLevelSet< dim >::modify_solution () override virtual
Carry out modifications on the auxiliary physic solution.
Reimplemented from AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1844 of file cls.cc.
References curvature_projection, and phase_gradient_projection.
output_newton_update_norms()
template<int dim> void ConservativeLevelSet< dim >::output_newton_update_norms () inline override virtual
Output the L2 and Linfty norms of the correction vector.
Implements PhysicsSolver< VectorType >.
Definition at line 397 of file cls.h.
References ConservativeLevelSet< dim >::newton_update, and PhysicsSolver< VectorType >::pcout.
percolate_time_vectors()
template<int dim> void ConservativeLevelSet< dim >::percolate_time_vectors () override virtual
Carry out the operations required to rearrange the values of the previous solution at the end of a time step.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1367 of file cls.cc.
post_mesh_adaptation()
template<int dim> void ConservativeLevelSet< dim >::post_mesh_adaptation () override virtual
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2317 of file cls.cc.
postprocess()
template<int dim> void ConservativeLevelSet< dim >::postprocess (bool first_iteration) override virtual
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1378 of file cls.cc.
References announce_string(), calculate_L2_error(), InterfaceTools::compute_surface_and_volume(), Parameters::fluid0, Parameters::fluid1, fluid_dynamics, Parameters::Timer::iteration, make_table_scalars_tensors(), make_table_scalars_vectors(), pressure, Parameters::SimulationControl::steady, temperature, and Parameters::verbose.
pre_mesh_adaptation()
template<int dim> void ConservativeLevelSet< dim >::pre_mesh_adaptation () override virtual
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2302 of file cls.cc.
read_checkpoint()
template<int dim> void ConservativeLevelSet< dim >::read_checkpoint () override virtual
Set solution vector of Auxiliary Physics using checkpoint.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2447 of file cls.cc.
References Parameters::adaptive, deserialize_tables_vector(), and fluid_dynamics.
reinit_face_velocity_with_adequate_solution()
template<int dim> void ConservativeLevelSet< dim >::reinit_face_velocity_with_adequate_solution (const typename DoFHandler< dim >::active_cell_iterator & velocity_cell, const unsigned int & face_no, CLSScratchData< dim > & scratch_data) inline private
Helper function to reinit the face velocity with the adequate solution. This prevents code duplication throughout the CLS class. The function looks at the multiphysics interface to decide if the velocity is a block velocity or a regular velocity. Furthermore, it also checks if a time-averaged solution is required. Otherwise, the code here would be copied four times.
Parameters
[in] velocity_cell the iterator of the cell where the velocity is to be reinitialized.
[in] face_no the face index where the velocity is to be reinitialized.
[in,out] scratch_data the scratch data to be used for the reinitialization.
Definition at line 733 of file cls.h.
References fluid_dynamics, ConservativeLevelSet< dim >::multiphysics, and CLSScratchData< dim >::reinit_face_velocity().
reinitialize_interface_with_geometric_method()
template<int dim> void ConservativeLevelSet< dim >::reinitialize_interface_with_geometric_method () private
Reinitialize the interface between fluids using the geometric approach.
Definition at line 3336 of file cls.cc.
References announce_string(), and Parameters::quiet.
reinitialize_interface_with_pde_based_method()
template<int dim> void ConservativeLevelSet< dim >::reinitialize_interface_with_pde_based_method () private
Reinitialize the interface between fluids using the PDE-based approach.
Definition at line 3232 of file cls.cc.
References pde_based_interface_reinitialization, and phase_gradient_projection.
set_initial_conditions()
template<int dim> void ConservativeLevelSet< dim >::set_initial_conditions () override virtual
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionally support the use of L2 projection or steady-state solutions.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2742 of file cls.cc.
References Parameters::adaptive, create_output_folder(), curvature_projection, delete_output_folder(), Parameters::diffusive, fluid_dynamics, Parameters::geometric, phase_gradient_projection, pressure, Parameters::SimulationControl::steady, and temperature.
setup_assemblers()
template<int dim> void ConservativeLevelSet< dim >::setup_assemblers () private virtual
sets up the vector of assembler functions
Definition at line 181 of file cls.cc.
References time_stepping_is_bdf(), and time_stepping_is_sdirk().
setup_dofs()
template<int dim> void ConservativeLevelSet< dim >::setup_dofs () override virtual
Sets-up the DofHandler and the degree of freedom associated with the physics.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2504 of file cls.cc.
References CLS.
sharpen_interface()
template<int dim> void ConservativeLevelSet< dim >::sharpen_interface (GlobalVectorType & solution, const double sharpening_threshold, const bool sharpen_previous_solutions) private
Carries out interface sharpening. It is called in the modify solution function.
Parameters
solution CLS solution (phase indicator)
sharpening_threshold Interface sharpening threshold that represents the mass conservation level
sharpen_previous_solutions Boolean true if sharpening is applied on the present and past solutions, false if the sharpening is applied on the given solution vector only. Used to determine the sharpening threshold by binary search.
Definition at line 2094 of file cls.cc.
smooth_phase_indicator()
template<int dim> void ConservativeLevelSet< dim >::smooth_phase_indicator (GlobalVectorType & solution) private
Carries out the smoothing phase indicator with a projection step (to avoid a staircase interface).
Definition at line 2134 of file cls.cc.
solve_interface_sharpening()
template<int dim> void ConservativeLevelSet< dim >::solve_interface_sharpening (GlobalVectorType & solution) private
Solves the assembled system to sharpen the interface. The linear_solver_tolerance is hardcoded = 1e-15, and an ILU Preconditioner is used. After solving the system, this function overwrites the solution with the sharpened solution.
Parameters
solution CLS solution (phase indicator)
Definition at line 3093 of file cls.cc.
References CLS, and Parameters::extra_verbose.
solve_linear_system()
template<int dim> void ConservativeLevelSet< dim >::solve_linear_system () override virtual
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
Implements PhysicsSolver< VectorType >.
Definition at line 2849 of file cls.cc.
References CLS, and Parameters::quiet.
solve_projection_phase_indicator()
template<int dim> void ConservativeLevelSet< dim >::solve_projection_phase_indicator (GlobalVectorType & solution) private
Solves smooth phase indicator system.
Parameters
solution CLS solution (phase indicator)
Definition at line 2248 of file cls.cc.
References CLS, and Parameters::quiet.
update_boundary_conditions()
template<int dim> void ConservativeLevelSet< dim >::update_boundary_conditions () override virtual
Update non zero constraints if the boundary is time dependent.
Reimplemented from AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2640 of file cls.cc.
References BoundaryConditions::cls_dirichlet.
update_solution_and_constraints()
template<int dim> void ConservativeLevelSet< dim >::update_solution_and_constraints (GlobalVectorType & solution) private
Limit the phase indicators between 0 and 1. This is necessary before interface sharpening. More information can be found in step_41 of deal.II tutorials: https://www.dealii.org/current/doxygen/deal.II/step_41.html.
Definition at line 2925 of file cls.cc.
verify_consistency_of_boundary_conditions()
template<int dim> void ConservativeLevelSet< dim >::verify_consistency_of_boundary_conditions () inline private
Verify consistency of the input parameters for boundary conditions to ensure that for every boundary condition within the triangulation, a boundary condition has been specified in the input file.
Definition at line 429 of file cls.h.
References ConservativeLevelSet< dim >::simulation_parameters, and ConservativeLevelSet< dim >::triangulation.
write_checkpoint()
template<int dim> void ConservativeLevelSet< dim >::write_checkpoint () override virtual
Prepares auxiliary physics to write checkpoint.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 2422 of file cls.cc.
References serialize_tables_vector().
Member Data Documentation
assemblers
template<int dim> std::vector<std::shared_ptr<CLSAssemblerBase<dim> > > ConservativeLevelSet< dim >::assemblers private
Definition at line 832 of file cls.h.
bounding_constraints
template<int dim> AffineConstraints<double> ConservativeLevelSet< dim >::bounding_constraints private
Definition at line 787 of file cls.h.
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > ConservativeLevelSet< dim >::cell_quadrature private
Definition at line 774 of file cls.h.
cls_subequations_interface
template<int dim> std::shared_ptr<CLSSubequationsInterface<dim> > ConservativeLevelSet< dim >::cls_subequations_interface private
Definition at line 813 of file cls.h.
complete_system_matrix_phase_indicator
template<int dim> TrilinosWrappers::SparseMatrix ConservativeLevelSet< dim >::complete_system_matrix_phase_indicator private
Definition at line 806 of file cls.h.
complete_system_rhs_phase_indicator
template<int dim> GlobalVectorType ConservativeLevelSet< dim >::complete_system_rhs_phase_indicator private
Definition at line 808 of file cls.h.
computing_timer
template<int dim> TimerOutput ConservativeLevelSet< dim >::computing_timer private
Definition at line 761 of file cls.h.
dof_handler
template<int dim> std::shared_ptr<DoFHandler<dim> > ConservativeLevelSet< dim >::dof_handler private
Definition at line 768 of file cls.h.
error_table
template<int dim> ConvergenceTable ConservativeLevelSet< dim >::error_table private
Definition at line 770 of file cls.h.
evaluation_point
template<int dim> GlobalVectorType ConservativeLevelSet< dim >::evaluation_point private
Definition at line 781 of file cls.h.
face_quadrature
template<int dim> std::shared_ptr<Quadrature<dim - 1> > ConservativeLevelSet< dim >::face_quadrature private
Definition at line 775 of file cls.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > ConservativeLevelSet< dim >::fe private
Definition at line 769 of file cls.h.
filter
template<int dim> std::shared_ptr<ConservativeLevelSetFilterBase> ConservativeLevelSet< dim >::filter private
Definition at line 838 of file cls.h.
filtered_solution
template<int dim> std::shared_ptr<GlobalVectorType> ConservativeLevelSet< dim >::filtered_solution private
Definition at line 790 of file cls.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> ConservativeLevelSet< dim >::ilu_preconditioner private
Definition at line 815 of file cls.h.
inner_face_assembler
template<int dim> std::shared_ptr<CLSAssemblerSIPG<dim> > ConservativeLevelSet< dim >::inner_face_assembler private
Definition at line 835 of file cls.h.
level_set
template<int dim> GlobalVectorType ConservativeLevelSet< dim >::level_set private
Level-set field obtained from the phase indicator field using a tanh-based transformation
Definition at line 794 of file cls.h.
local_evaluation_point
template<int dim> GlobalVectorType ConservativeLevelSet< dim >::local_evaluation_point private
Definition at line 782 of file cls.h.
locally_owned_dofs
template<int dim> IndexSet ConservativeLevelSet< dim >::locally_owned_dofs private
Definition at line 778 of file cls.h.
locally_relevant_dofs
template<int dim> IndexSet ConservativeLevelSet< dim >::locally_relevant_dofs private
Definition at line 779 of file cls.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > ConservativeLevelSet< dim >::mapping private
Definition at line 773 of file cls.h.
mass_first_iteration
template<int dim> double ConservativeLevelSet< dim >::mass_first_iteration private
Definition at line 825 of file cls.h.
mass_matrix_phase_indicator
template<int dim> TrilinosWrappers::SparseMatrix ConservativeLevelSet< dim >::mass_matrix_phase_indicator private
Definition at line 809 of file cls.h.
mass_monitored
template<int dim> double ConservativeLevelSet< dim >::mass_monitored private
Definition at line 824 of file cls.h.
multiphysics
template<int dim> MultiphysicsInterface<dim>* ConservativeLevelSet< dim >::multiphysics private
Definition at line 759 of file cls.h.
newton_update
template<int dim> GlobalVectorType ConservativeLevelSet< dim >::newton_update private
Definition at line 783 of file cls.h.
nodal_phase_indicator_owned
template<int dim> GlobalVectorType ConservativeLevelSet< dim >::nodal_phase_indicator_owned private
Definition at line 757 of file cls.h.
nonzero_constraints
template<int dim> AffineConstraints<double> ConservativeLevelSet< dim >::nonzero_constraints private
Definition at line 786 of file cls.h.
phase_lower_bound
template<int dim> const double ConservativeLevelSet< dim >::phase_lower_bound = 0.0 private
Definition at line 819 of file cls.h.
phase_upper_bound
template<int dim> const double ConservativeLevelSet< dim >::phase_upper_bound = 1.0 private
Definition at line 818 of file cls.h.
present_solution
template<int dim> std::shared_ptr<GlobalVectorType> ConservativeLevelSet< dim >::present_solution private
Definition at line 784 of file cls.h.
previous_solutions
template<int dim> std::shared_ptr<std::vector<GlobalVectorType> > ConservativeLevelSet< dim >::previous_solutions private
Definition at line 797 of file cls.h.
previous_solutions_transfer
template<int dim> std::vector<SolutionTransfer<dim, GlobalVectorType> > ConservativeLevelSet< dim >::previous_solutions_transfer private
Definition at line 802 of file cls.h.
sharpening_threshold
template<int dim> double ConservativeLevelSet< dim >::sharpening_threshold private
Definition at line 826 of file cls.h.
signed_distance_solver
template<int dim> std::shared_ptr<InterfaceTools::SignedDistanceSolver<dim, GlobalVectorType> > ConservativeLevelSet< dim >::signed_distance_solver private
Definition at line 842 of file cls.h.
signed_distance_transformation
template<int dim> std::shared_ptr<SignedDistanceTransformationBase> ConservativeLevelSet< dim >::signed_distance_transformation private
Definition at line 846 of file cls.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> ConservativeLevelSet< dim >::simulation_control private
Definition at line 767 of file cls.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& ConservativeLevelSet< dim >::simulation_parameters private
Definition at line 763 of file cls.h.
solution_transfer
template<int dim> std::shared_ptr<SolutionTransfer<dim, GlobalVectorType> > ConservativeLevelSet< dim >::solution_transfer private
Definition at line 800 of file cls.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix ConservativeLevelSet< dim >::system_matrix private
Definition at line 789 of file cls.h.
system_matrix_phase_indicator
template<int dim> TrilinosWrappers::SparseMatrix ConservativeLevelSet< dim >::system_matrix_phase_indicator private
Definition at line 805 of file cls.h.
system_rhs
template<int dim> GlobalVectorType ConservativeLevelSet< dim >::system_rhs private
Definition at line 785 of file cls.h.
system_rhs_phase_indicator
template<int dim> GlobalVectorType ConservativeLevelSet< dim >::system_rhs_phase_indicator private
Definition at line 807 of file cls.h.
table_barycenter
template<int dim> TableHandler ConservativeLevelSet< dim >::table_barycenter private
Definition at line 829 of file cls.h.
table_monitoring_cls
template<int dim> TableHandler ConservativeLevelSet< dim >::table_monitoring_cls private
Definition at line 822 of file cls.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > ConservativeLevelSet< dim >::triangulation private
Definition at line 766 of file cls.h.
volume_monitored
template<int dim> double ConservativeLevelSet< dim >::volume_monitored private
Definition at line 823 of file cls.h.
zero_constraints
template<int dim> AffineConstraints<double> ConservativeLevelSet< dim >::zero_constraints private
Definition at line 788 of file cls.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/cls.h
/home/runner/work/lethe/lethe/source/solvers/cls.cc