Lethe Open-Source Library: KinsolNewtonNonLinearSolver< VectorType > Class Template Reference
KinsolNewtonNonLinearSolver< VectorType > Class Template Reference
#include <kinsol_newton_non_linear_solver.h>
Public Member Functions
KinsolNewtonNonLinearSolver (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &param)
void solve (const bool is_initial_step) override
Public Member Functions inherited from NonLinearSolver< VectorType >
NonLinearSolver (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &params)
virtual ~NonLinearSolver ()
unsigned int get_current_newton_iteration () const
Additional Inherited Members
Protected Attributes inherited from NonLinearSolver< VectorType >
PhysicsSolver< VectorType > * physics_solver
Parameters::NonLinearSolver params
unsigned int outer_iteration
Detailed Description
template<typename VectorType>
class KinsolNewtonNonLinearSolver< VectorType >
Non-linear Newton solver for non-linear systems of equations implemented in the SUNDIALS suite, specifically the KINSOL package. This solver has internal algorithms to determine the time step and decide whether to reassemble the Jacobian matrix or not.
Definition at line 19 of file kinsol_newton_non_linear_solver.h.
Constructor & Destructor Documentation
KinsolNewtonNonLinearSolver()
template<typename VectorType > KinsolNewtonNonLinearSolver< VectorType >::KinsolNewtonNonLinearSolver (PhysicsSolver< VectorType > * physics_solver, const Parameters::NonLinearSolver & param)
Constructor.
Parameters
[in] physics_solver A pointer to the physics solver to which the non-linear solver is attached.
[in] param Non-linear solver parameters as specified in the simulation parameter file.
Definition at line 48 of file kinsol_newton_non_linear_solver.h.
Member Function Documentation
solve()
template<typename VectorType > void KinsolNewtonNonLinearSolver< VectorType >::solve (const bool is_initial_step) override virtual
Solve the non-linear system of equations.
Parameters
[in] is_initial_step Boolean variable that controls which constraints are going to be applied to the equations depending on the time step.
Implements NonLinearSolver< VectorType >.
Definition at line 56 of file kinsol_newton_non_linear_solver.h.
References PhysicsSolver< VectorType >::apply_constraints(), PhysicsSolver< VectorType >::assemble_system_matrix(), PhysicsSolver< VectorType >::assemble_system_rhs(), PhysicsSolver< VectorType >::get_evaluation_point(), PhysicsSolver< VectorType >::get_local_evaluation_point(), PhysicsSolver< VectorType >::get_newton_update(), PhysicsSolver< VectorType >::get_present_solution(), PhysicsSolver< VectorType >::get_system_rhs(), Parameters::NonLinearSolver::line_search, Parameters::NonLinearSolver::normal_newton, PhysicsSolver< VectorType >::pcout, Parameters::NonLinearSolver::picard, PhysicsSolver< VectorType >::setup_preconditioner(), and PhysicsSolver< VectorType >::solve_linear_system().
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/kinsol_newton_non_linear_solver.h