Lethe Open-Source Library: DEMSolver< dim, PropertiesIndex > Class Template Reference
DEMSolver< dim, PropertiesIndex > Class Template Reference
#include <dem.h>
Public Member Functions
DEMSolver (DEMSolverParameters< dim > dem_parameters)
void solve ()
Private Member Functions
void setup_parameters ()
void setup_distribution_type ()
void setup_solid_objects ()
void setup_functions_and_pointers ()
std::function< void()> set_contact_search_iteration_function ()
std::shared_ptr< Insertion< dim, PropertiesIndex > > set_insertion_type ()
std::shared_ptr< Integrator< dim, PropertiesIndex > > set_integrator_type ()
void setup_triangulation_dependent_parameters ()
void setup_background_dofs ()
void load_balance ()
void check_contact_search_iteration_constant ()
void check_contact_search_iteration_dynamic ()
void insert_particles ()
void particle_wall_contact_force ()
void move_solid_objects ()
void update_temperature_solid_objects ()
void finish_simulation ()
void write_output_results ()
void post_process_results ()
void report_statistics ()
void sort_particles_into_subdomains_and_cells ()
Private Attributes
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
ConditionalOStream pcout
DEMSolverParameters< dim > parameters
CheckpointControl checkpoint_controller
parallel::distributed::Triangulation< dim > triangulation
MappingQGeneric< dim > mapping
Particles::ParticleHandler< dim, dim > particle_handler
DEMActionManager * action_manager
TimerOutput computing_timer
DEM::ParticleProperties< dim, PropertiesIndex > properties_class
Tensor< 1, 3 > g
double smallest_contact_search_criterion
double smallest_solid_object_mapping_criterion
double neighborhood_threshold_squared
double maximum_particle_diameter
unsigned int contact_build_number
DEMContactManager< dim, PropertiesIndex > contact_manager
LagrangianLoadBalancing< dim, PropertiesIndex > load_balancing
std::shared_ptr< SimulationControl > simulation_control
BoundaryCellsInformation< dim > boundary_cell_object
std::shared_ptr< GridMotion< dim > > grid_motion_object
std::shared_ptr< ParticleParticleContactForceBase< dim, PropertiesIndex > > particle_particle_contact_force_object
std::shared_ptr< ParticleWallContactForceBase< dim, PropertiesIndex > > particle_wall_contact_force_object
ParticlePointLineForce< dim, PropertiesIndex > particle_point_line_contact_force_object
std::shared_ptr< ParticlesForceChainsBase< dim, PropertiesIndex > > particles_force_chains_object
std::shared_ptr< Integrator< dim, PropertiesIndex > > integrator_object
std::shared_ptr< Insertion< dim, PropertiesIndex > > insertion_object
Visualization< dim, PropertiesIndex > visualization_object
PVDHandler particles_pvdhandler
PVDHandler particles_pvdhandler_force_chains
ParticleInteractionOutcomes< PropertiesIndex > contact_outcome
std::vector< Tensor< 1, 3 > > & torque = contact_outcome.torque
std::vector< Tensor< 1, 3 > > & force = contact_outcome.force
OngoingCollisionLog< dim > ongoing_collision_log
CompletedCollisionLog< dim > collision_event_log
std::vector< double > displacement
std::vector< double > MOI
dem_data_structures< dim >::solid_surfaces_mesh_information solid_surfaces_mesh_info
dem_data_structures< dim >::solid_volumes_mesh_info solid_volumes_mesh_info
dem_data_structures< dim >::boundary_points_and_normal_vectors updated_boundary_points_and_normal_vectors
dem_data_structures< dim >::vector_on_boundary forces_boundary_information
dem_data_structures< dim >::vector_on_boundary torques_boundary_information
DEM::dem_data_structures< dim >::periodic_boundaries_cells_info periodic_boundaries_cells_information
PeriodicBoundariesManipulator< dim > periodic_boundaries_object
DoFHandler< dim > background_dh
PVDHandler grid_pvdhandler
statistics contact_list
std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > solid_surfaces
std::vector< std::shared_ptr< SerialSolid< dim, dim > > > solid_volumes
std::vector< std::shared_ptr< Distribution > > size_distribution_object_container
AdaptiveSparseContacts< dim, PropertiesIndex > sparse_contacts_object
AffineConstraints< double > background_constraints
std::function< bool()> load_balance_iteration_check_function
std::function< void()> contact_detection_iteration_check_function
bool disable_position_integration
Detailed Description
template<int dim, typename PropertiesIndex>
class DEMSolver< dim, PropertiesIndex >
Solver using the soft-sphere model of the discrete element method (DEM) to simulate granular systems.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Definition at line 55 of file dem.h.
Constructor & Destructor Documentation
DEMSolver()
template<int dim, typename PropertiesIndex > DEMSolver< dim, PropertiesIndex >::DEMSolver (DEMSolverParameters< dim > dem_parameters)
Definition at line 35 of file dem.cc.
Member Function Documentation
check_contact_search_iteration_constant()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::check_contact_search_iteration_constant () inline private
Establish if this is a contact detection iteration using the constant contact detection frequency. If the iteration number is a multiple of the frequency, this iteration is considered to be a contact detection iteration.
Definition at line 497 of file dem.cc.
check_contact_search_iteration_dynamic()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::check_contact_search_iteration_dynamic () inline private
Establish if this is a contact detection iteration using the maximal displacement of the particles. If this particle displacement surpasses a threshold, this iteration is a contact detection iteration.
Definition at line 481 of file dem.cc.
finish_simulation()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::finish_simulation () private
Execute the last post-processing at the end of the simulation and output test results if necessary.
Definition at line 616 of file dem.cc.
References Parameters::Timer::end, Parameters::Testing::mobility_status, Parameters::Testing::particles, Parameters::Testing::subdomain, and write_forces_torques_output_results().
insert_particles()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::insert_particles () private
Check if particles have to be inserted at this iteration and perform it if necessary.
Definition at line 506 of file dem.cc.
load_balance()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::load_balance () private
Check if a load balancing is required according to the load balancing method and perform it if necessary.
Definition at line 417 of file dem.cc.
move_solid_objects()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::move_solid_objects () private
Move all solid objects.
Definition at line 571 of file dem.cc.
particle_wall_contact_force()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::particle_wall_contact_force () private
Calculates particles-wall contact forces.
Definition at line 525 of file dem.cc.
post_process_results()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::post_process_results () private
Calculate average velocity and other post-processed quantities that need to be outputted to files.
Definition at line 745 of file dem.cc.
report_statistics()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::report_statistics () private
Calculate statistics on the particles and report them to the terminal. This function is notably used to monitor the time min, max and total performed contact searches, and the instant min, max, avg and total values of the linear velocity, angular velocity, linear kinetic energy and angular kinetic.
Definition at line 764 of file dem.cc.
References add_statistics_to_table_handler(), DEM::calculate_granular_statistics(), Parameters::Timer::iteration, DEM::omega, DEM::rotational_kinetic_energy, DEM::translational_kinetic_energy, and DEM::velocity.
set_contact_search_iteration_function()
template<int dim, typename PropertiesIndex > std::function< void()> DEMSolver< dim, PropertiesIndex >::set_contact_search_iteration_function () inline private
Set the iteration check function according to the chosen contact detection method.
Returns
Contact detection method function.
Definition at line 256 of file dem.cc.
set_insertion_type()
template<int dim, typename PropertiesIndex > std::shared_ptr< Insertion< dim, PropertiesIndex > > DEMSolver< dim, PropertiesIndex >::set_insertion_type () private
Set the insertion method.
Returns
The pointer to the insertion object
Definition at line 276 of file dem.cc.
set_integrator_type()
template<int dim, typename PropertiesIndex > std::shared_ptr< Integrator< dim, PropertiesIndex > > DEMSolver< dim, PropertiesIndex >::set_integrator_type () private
Set the integration method.
Returns
The pointer to the integration object
Definition at line 314 of file dem.cc.
setup_background_dofs()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::setup_background_dofs () private
Set up the background degree of freedom used for parallel grid output or mapping of periodic dofs when using periodic boundaries.
Definition at line 381 of file dem.cc.
setup_distribution_type()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::setup_distribution_type () private
Initialize the distribution type for the particles, and sets the maximum particle diameter and the neighborhood threshold squared in the process.
Definition at line 159 of file dem.cc.
References Parameters::Lagrangian::LagrangianPhysicalProperties::distribution_type, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_average_diameter, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_custom_diameter, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_custom_probability, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_size_std, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number, and Parameters::Lagrangian::LagrangianPhysicalProperties::seed_for_distributions.
setup_functions_and_pointers()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::setup_functions_and_pointers () private
Set up the pointers to the functions and classes according to the parameters.
Definition at line 237 of file dem.cc.
setup_parameters()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::setup_parameters () private
Set the parameters for the DEM simulation.
Definition at line 58 of file dem.cc.
References announce_string(), create_output_folder(), DEMActionManager::get_action_manager(), input_parameter_inspection(), Parameters::Timer::none, and Parameters::Lagrangian::BCDEM::periodic.
setup_solid_objects()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::setup_solid_objects () private
Set up the solid object containers with serial objects. TODO: Modify this set up once the solid volumes are fully implemented.
Definition at line 205 of file dem.cc.
setup_triangulation_dependent_parameters()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::setup_triangulation_dependent_parameters () private
Set up the triangulation dependent parameters after the reading of the mesh and/or the simulation restart.
Definition at line 335 of file dem.cc.
solve()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::solve ()
Engine of the DEM solver. Calls all the necessary functions to set parameters, solve the simulation, and finish the simulation.
Definition at line 878 of file dem.cc.
References find_floating_mesh_mapping_step(), read_checkpoint(), read_mesh(), Parameters::verbose, write_checkpoint(), write_collision_stats(), and write_forces_torques_output_locally().
sort_particles_into_subdomains_and_cells()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::sort_particles_into_subdomains_and_cells () inline private
Execute the sorting of particle into subdomains and cells, and reinitialize the containers dependent on the local particle ids.
Definition at line 842 of file dem.cc.
update_temperature_solid_objects()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::update_temperature_solid_objects () private
Update solid objects temperatures.
Definition at line 591 of file dem.cc.
write_output_results()
template<int dim, typename PropertiesIndex > void DEMSolver< dim, PropertiesIndex >::write_output_results () private
Generate VTU file with particles information for visualization.
Definition at line 678 of file dem.cc.
References Visualization< dim, PropertiesIndex >::build_patches().
Member Data Documentation
action_manager
template<int dim, typename PropertiesIndex > DEMActionManager* DEMSolver< dim, PropertiesIndex >::action_manager private
The action manager that manages the actions triggered by events.
Definition at line 272 of file dem.h.
background_constraints
template<int dim, typename PropertiesIndex > AffineConstraints<double> DEMSolver< dim, PropertiesIndex >::background_constraints private
The constraints for the background grid needed for the adaptive sparse.
Definition at line 523 of file dem.h.
background_dh
template<int dim, typename PropertiesIndex > DoFHandler<dim> DEMSolver< dim, PropertiesIndex >::background_dh private
The background degree of freedom handler uses for parallel grid processing.
Definition at line 487 of file dem.h.
boundary_cell_object
template<int dim, typename PropertiesIndex > BoundaryCellsInformation<dim> DEMSolver< dim, PropertiesIndex >::boundary_cell_object private
The boundary cells object.
Definition at line 345 of file dem.h.
checkpoint_controller
template<int dim, typename PropertiesIndex > CheckpointControl DEMSolver< dim, PropertiesIndex >::checkpoint_controller private
The checkpoint controller of the DEM simulation.
Definition at line 251 of file dem.h.
collision_event_log
template<int dim, typename PropertiesIndex > CompletedCollisionLog<dim> DEMSolver< dim, PropertiesIndex >::collision_event_log private
Class object to store the complete collision events (start and end).
Definition at line 424 of file dem.h.
computing_timer
template<int dim, typename PropertiesIndex > TimerOutput DEMSolver< dim, PropertiesIndex >::computing_timer private
The timer that keeps track of the time spent in some functions. Currently theses functions are: load balancing and VTU output.
Definition at line 278 of file dem.h.
contact_build_number
template<int dim, typename PropertiesIndex > unsigned int DEMSolver< dim, PropertiesIndex >::contact_build_number private
The counter to keep track of the number of contact search.
Definition at line 325 of file dem.h.
contact_detection_iteration_check_function
template<int dim, typename PropertiesIndex > std::function<void()> DEMSolver< dim, PropertiesIndex >::contact_detection_iteration_check_function private
The pointer to the contact detection function that checks if a contact search is required.
Definition at line 535 of file dem.h.
contact_list
template<int dim, typename PropertiesIndex > statistics DEMSolver< dim, PropertiesIndex >::contact_list private
The storage of statistics about time and contact lists.
Definition at line 497 of file dem.h.
contact_manager
template<int dim, typename PropertiesIndex > DEMContactManager<dim, PropertiesIndex> DEMSolver< dim, PropertiesIndex >::contact_manager private
The manager of all the contact search operations.
Definition at line 330 of file dem.h.
contact_outcome
template<int dim, typename PropertiesIndex > ParticleInteractionOutcomes<PropertiesIndex> DEMSolver< dim, PropertiesIndex >::contact_outcome private
Class object to store the vectors of force, torque and heat transfer rate applied to particles.
Definition at line 404 of file dem.h.
disable_position_integration
template<int dim, typename PropertiesIndex > bool DEMSolver< dim, PropertiesIndex >::disable_position_integration private
Disable position integration, useful for multiphysic simulations with a packed bed, loaded with another prm.
Definition at line 541 of file dem.h.
displacement
template<int dim, typename PropertiesIndex > std::vector<double> DEMSolver< dim, PropertiesIndex >::displacement private
The displacement tracking of particles for the dynamic contact detection.
Definition at line 430 of file dem.h.
force
template<int dim, typename PropertiesIndex > std::vector<Tensor<1, 3> >& DEMSolver< dim, PropertiesIndex >::force = contact_outcome.force private
The vector of force of particles.
Definition at line 414 of file dem.h.
forces_boundary_information
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::vector_on_boundary DEMSolver< dim, PropertiesIndex >::forces_boundary_information private
The boundary information of the forces.
Definition at line 462 of file dem.h.
g
template<int dim, typename PropertiesIndex > Tensor<1, 3> DEMSolver< dim, PropertiesIndex >::g private
The acceleration acting on the particles.
Definition at line 290 of file dem.h.
grid_motion_object
template<int dim, typename PropertiesIndex > std::shared_ptr<GridMotion<dim> > DEMSolver< dim, PropertiesIndex >::grid_motion_object private
The grid motion object.
Definition at line 350 of file dem.h.
grid_pvdhandler
template<int dim, typename PropertiesIndex > PVDHandler DEMSolver< dim, PropertiesIndex >::grid_pvdhandler private
The grid PVD handler.
Definition at line 492 of file dem.h.
insertion_object
template<int dim, typename PropertiesIndex > std::shared_ptr<Insertion<dim, PropertiesIndex> > DEMSolver< dim, PropertiesIndex >::insertion_object private
The insertion object.
Definition at line 384 of file dem.h.
integrator_object
template<int dim, typename PropertiesIndex > std::shared_ptr<Integrator<dim, PropertiesIndex> > DEMSolver< dim, PropertiesIndex >::integrator_object private
The integrator object.
Definition at line 379 of file dem.h.
load_balance_iteration_check_function
template<int dim, typename PropertiesIndex > std::function<bool()> DEMSolver< dim, PropertiesIndex >::load_balance_iteration_check_function private
The pointer to the function that checks if a load balancing is required.
Definition at line 529 of file dem.h.
load_balancing
template<int dim, typename PropertiesIndex > LagrangianLoadBalancing<dim, PropertiesIndex> DEMSolver< dim, PropertiesIndex >::load_balancing private
The load balancing handler.
Definition at line 335 of file dem.h.
mapping
template<int dim, typename PropertiesIndex > MappingQGeneric<dim> DEMSolver< dim, PropertiesIndex >::mapping private
The polynomial mapping. The mapping is first order in DEM simulations.
Definition at line 262 of file dem.h.
maximum_particle_diameter
template<int dim, typename PropertiesIndex > double DEMSolver< dim, PropertiesIndex >::maximum_particle_diameter private
The maximum particle diameter.
Definition at line 320 of file dem.h.
MOI
template<int dim, typename PropertiesIndex > std::vector<double> DEMSolver< dim, PropertiesIndex >::MOI private
The moment of inertia of particles.
Definition at line 435 of file dem.h.
mpi_communicator
template<int dim, typename PropertiesIndex > MPI_Comm DEMSolver< dim, PropertiesIndex >::mpi_communicator private
The MPI communicator used for the parallel simulation.
Definition at line 225 of file dem.h.
n_mpi_processes
template<int dim, typename PropertiesIndex > const unsigned int DEMSolver< dim, PropertiesIndex >::n_mpi_processes private
The number of MPI processes used for the parallel simulation.
Definition at line 230 of file dem.h.
neighborhood_threshold_squared
template<int dim, typename PropertiesIndex > double DEMSolver< dim, PropertiesIndex >::neighborhood_threshold_squared private
The neighborhood threshold squared. \((\text{neighborhood_threshold} * D_{p,max})^2\).
Definition at line 315 of file dem.h.
ongoing_collision_log
template<int dim, typename PropertiesIndex > OngoingCollisionLog<dim> DEMSolver< dim, PropertiesIndex >::ongoing_collision_log private
Class object to store the particle id, boundary id, velocity tensor, omega tensor and time of ongoing collisions.
Definition at line 419 of file dem.h.
parameters
template<int dim, typename PropertiesIndex > DEMSolverParameters<dim> DEMSolver< dim, PropertiesIndex >::parameters private
The parameters of the DEM simulation.
Definition at line 246 of file dem.h.
particle_handler
template<int dim, typename PropertiesIndex > Particles::ParticleHandler<dim, dim> DEMSolver< dim, PropertiesIndex >::particle_handler private
The particle handler that manages the particles.
Definition at line 267 of file dem.h.
particle_particle_contact_force_object
template<int dim, typename PropertiesIndex > std::shared_ptr<ParticleParticleContactForceBase<dim, PropertiesIndex> > DEMSolver< dim, PropertiesIndex >::particle_particle_contact_force_object private
The particle-particle contact force object.
Definition at line 356 of file dem.h.
particle_point_line_contact_force_object
template<int dim, typename PropertiesIndex > ParticlePointLineForce<dim, PropertiesIndex> DEMSolver< dim, PropertiesIndex >::particle_point_line_contact_force_object private
The particle-point-line contact force object.
Definition at line 368 of file dem.h.
particle_wall_contact_force_object
template<int dim, typename PropertiesIndex > std::shared_ptr<ParticleWallContactForceBase<dim, PropertiesIndex> > DEMSolver< dim, PropertiesIndex >::particle_wall_contact_force_object private
The particle-wall contact force object.
Definition at line 362 of file dem.h.
particles_force_chains_object
template<int dim, typename PropertiesIndex > std::shared_ptr<ParticlesForceChainsBase<dim, PropertiesIndex> > DEMSolver< dim, PropertiesIndex >::particles_force_chains_object private
The particle force chains post-processing object.
Definition at line 374 of file dem.h.
particles_pvdhandler
template<int dim, typename PropertiesIndex > PVDHandler DEMSolver< dim, PropertiesIndex >::particles_pvdhandler private
The particle PVD handler.
Definition at line 394 of file dem.h.
particles_pvdhandler_force_chains
template<int dim, typename PropertiesIndex > PVDHandler DEMSolver< dim, PropertiesIndex >::particles_pvdhandler_force_chains private
The force chains PVD handler.
Definition at line 399 of file dem.h.
pcout
template<int dim, typename PropertiesIndex > ConditionalOStream DEMSolver< dim, PropertiesIndex >::pcout private
The output stream used for the parallel simulation, only used by the process 0.
Definition at line 241 of file dem.h.
periodic_boundaries_cells_information
template<int dim, typename PropertiesIndex > DEM::dem_data_structures<dim>::periodic_boundaries_cells_info DEMSolver< dim, PropertiesIndex >::periodic_boundaries_cells_information private
The periodic boundaries cells information map. Only used with a simulation with periodic boundaries.
Definition at line 475 of file dem.h.
periodic_boundaries_object
template<int dim, typename PropertiesIndex > PeriodicBoundariesManipulator<dim> DEMSolver< dim, PropertiesIndex >::periodic_boundaries_object private
The periodic boundaries manipulator. Only used with a simulation with periodic boundaries.
Definition at line 481 of file dem.h.
properties_class
template<int dim, typename PropertiesIndex > DEM::ParticleProperties<dim, PropertiesIndex> DEMSolver< dim, PropertiesIndex >::properties_class private
The properties of the DEM simulation.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Definition at line 285 of file dem.h.
simulation_control
template<int dim, typename PropertiesIndex > std::shared_ptr<SimulationControl> DEMSolver< dim, PropertiesIndex >::simulation_control private
The simulation control (DEM Transient).
Definition at line 340 of file dem.h.
size_distribution_object_container
template<int dim, typename PropertiesIndex > std::vector<std::shared_ptr<Distribution> > DEMSolver< dim, PropertiesIndex >::size_distribution_object_container private
The container of the distribution objects.
Definition at line 512 of file dem.h.
smallest_contact_search_criterion
template<int dim, typename PropertiesIndex > double DEMSolver< dim, PropertiesIndex >::smallest_contact_search_criterion private
The contact search frequency criterion for the dynamic contact detection method. The value is the smallest value between those two quantities:
The diameter of the smallest active cell of a triangulation minus the largest particle radius. \(D_{c,min} - D_{p,max} / 2\)
A security factor on the neighboring threshold times the largest particle radius. \(factor * (neighborhood_threshold - 1) * D_{p,max} / 2\)
Definition at line 303 of file dem.h.
smallest_solid_object_mapping_criterion
template<int dim, typename PropertiesIndex > double DEMSolver< dim, PropertiesIndex >::smallest_solid_object_mapping_criterion private
The smallest solid object mapping criterion. The value is \(2^-0.5 * D_{c,min}\).
Definition at line 309 of file dem.h.
solid_surfaces
template<int dim, typename PropertiesIndex > std::vector<std::shared_ptr<SerialSolid<dim - 1, dim> > > DEMSolver< dim, PropertiesIndex >::solid_surfaces private
The container of the solid surfaces.
Definition at line 502 of file dem.h.
solid_surfaces_mesh_info
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::solid_surfaces_mesh_information DEMSolver< dim, PropertiesIndex >::solid_surfaces_mesh_info private
The vector of vector of pairs of the mapping of the background mesh to the solid surface.
Definition at line 442 of file dem.h.
solid_volumes
template<int dim, typename PropertiesIndex > std::vector<std::shared_ptr<SerialSolid<dim, dim> > > DEMSolver< dim, PropertiesIndex >::solid_volumes private
The container of the solid volumes.
Definition at line 507 of file dem.h.
solid_volumes_mesh_info
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::solid_volumes_mesh_info DEMSolver< dim, PropertiesIndex >::solid_volumes_mesh_info private
The vector of vector of pairs of the mapping of the background mesh to the solid volume.
Definition at line 449 of file dem.h.
sparse_contacts_object
template<int dim, typename PropertiesIndex > AdaptiveSparseContacts<dim, PropertiesIndex> DEMSolver< dim, PropertiesIndex >::sparse_contacts_object private
The object handling the adaptive sparse contacts (ASC). Only used with the ASC method.
Definition at line 518 of file dem.h.
this_mpi_process
template<int dim, typename PropertiesIndex > const unsigned int DEMSolver< dim, PropertiesIndex >::this_mpi_process private
The rank of the current MPI process.
Definition at line 235 of file dem.h.
torque
template<int dim, typename PropertiesIndex > std::vector<Tensor<1, 3> >& DEMSolver< dim, PropertiesIndex >::torque = contact_outcome.torque private
The vector of torque of particles.
Definition at line 409 of file dem.h.
torques_boundary_information
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::vector_on_boundary DEMSolver< dim, PropertiesIndex >::torques_boundary_information private
The torques boundary information.
Definition at line 468 of file dem.h.
triangulation
template<int dim, typename PropertiesIndex > parallel::distributed::Triangulation<dim> DEMSolver< dim, PropertiesIndex >::triangulation private
The distributed triangulation used for the DEM simulation.
Definition at line 256 of file dem.h.
updated_boundary_points_and_normal_vectors
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::boundary_points_and_normal_vectors DEMSolver< dim, PropertiesIndex >::updated_boundary_points_and_normal_vectors private
The map of the point and normal vector of grid. Only used with grid motion.
Definition at line 456 of file dem.h.
visualization_object
template<int dim, typename PropertiesIndex > Visualization<dim, PropertiesIndex> DEMSolver< dim, PropertiesIndex >::visualization_object private
The visualization object.
Definition at line 389 of file dem.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/dem.h
/home/runner/work/lethe/lethe/source/dem/dem.cc