Lethe Open-Source Library: ParticleWallFineSearch< dim > Class Template Reference
ParticleWallFineSearch< dim > Class Template Reference
#include <particle_wall_fine_search.h>
Public Member Functions
ParticleWallFineSearch ()
void particle_wall_fine_search (const typename DEM::dem_data_structures< dim >::particle_wall_candidates &particle_wall_contact_pair_candidates, typename DEM::dem_data_structures< dim >::particle_wall_in_contact &particle_wall_pairs_in_contact)
void particle_floating_wall_fine_search (const typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates &particle_floating_wall_contact_candidates, const Parameters::Lagrangian::FloatingWalls< dim > &floating_wall_properties, const double simulation_time, typename DEM::dem_data_structures< dim >::particle_wall_in_contact &particle_floating_wall_in_contact)
void particle_floating_mesh_fine_search (const typename DEM::dem_data_structures< dim >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, typename DEM::dem_data_structures< dim >::particle_floating_mesh_in_contact &particle_floating_mesh_in_contact)
Detailed Description
template<int dim>
class ParticleWallFineSearch< dim >
This class is used for fine particle-wall contact search. Fine search is used to find all the particles which are physically in contact with system boundaries and obtain all the required information for calculation of the corresponding particle-wall contact force
Note
Author
Shahab Golshan, Polytechnique Montreal 2019-
Definition at line 48 of file particle_wall_fine_search.h.
Constructor & Destructor Documentation
ParticleWallFineSearch()
template<int dim> ParticleWallFineSearch< dim >::ParticleWallFineSearch
Definition at line 11 of file particle_wall_fine_search.cc.
Member Function Documentation
particle_floating_mesh_fine_search()
template<int dim> void ParticleWallFineSearch< dim >::particle_floating_mesh_fine_search (const typename DEM::dem_data_structures< dim >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, typename DEM::dem_data_structures< dim >::particle_floating_mesh_in_contact & particle_floating_mesh_in_contact)
Iterates over the contact candidates from particle-floating mesh broad search (particle_floating_mesh_contact_candidates) to add new contact pairs to the particle_floating_mesh_in_contact container
Parameters
particle_floating_mesh_contact_candidates The output of particle-floating mesh broad search which shows contact pair candidates
particle_floating_mesh_in_contact An map of maps which stores all the particle-floating mesh pairs which are in contact
Definition at line 163 of file particle_wall_fine_search.cc.
particle_floating_wall_fine_search()
template<int dim> void ParticleWallFineSearch< dim >::particle_floating_wall_fine_search (const typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates & particle_floating_wall_contact_candidates, const Parameters::Lagrangian::FloatingWalls< dim > & floating_wall_properties, const double simulation_time, typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_floating_wall_in_contact)
Iterates over the contact candidates from particle-floating wall broad search (particle_floating_wall_candidates) to add new contact pairs to the particle_floating_wall_pairs_in_contact container
Parameters
particle_floating_wall_pair_candidates The output of particle-floating wall broad search which shows contact pair candidates
floating_wall_properties Properties of floating walls defined in the parameter handler
simulation_time Simulation time
particle_floating_wall_pairs_in_contact An unordered_map of maps which stores all the particle-floating wall pairs which are in contact, and the contact information in a struct. Note that the size of this unordered map is equal to the number of particles
Definition at line 69 of file particle_wall_fine_search.cc.
References Parameters::Lagrangian::FloatingWalls< dim >::floating_walls_normal_vectors, point_nd_to_3d(), Parameters::Lagrangian::FloatingWalls< dim >::points_on_walls, tensor_nd_to_3d(), Parameters::Lagrangian::FloatingWalls< dim >::time_end, and Parameters::Lagrangian::FloatingWalls< dim >::time_start.
particle_wall_fine_search()
template<int dim> void ParticleWallFineSearch< dim >::particle_wall_fine_search (const typename DEM::dem_data_structures< dim >::particle_wall_candidates & particle_wall_contact_pair_candidates, typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_wall_pairs_in_contact)
Iterates over the contact candidates from particle-wall broad search (particle_wall_contact_pair_candidates) to add new contact pairs to the particle_wall_pairs_in_contact container
Parameters
particle_wall_contact_pair_candidates The output of particle-wall broad search which shows contact pair candidates
particle_wall_pairs_in_contact An unordered_map of maps which stores all the particle-wall pairs which are physically in contact, and the contact information in a struct. Note that the size of this unordered map is equal to the number of particles
Definition at line 16 of file particle_wall_fine_search.cc.
References point_nd_to_3d(), and tensor_nd_to_3d().
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/particle_wall_fine_search.h
/home/runner/work/lethe/lethe/source/dem/particle_wall_fine_search.cc