Lethe Open-Source Library: VANSAssemblerRong< dim > Class Template Reference
VANSAssemblerRong< dim > Class Template Reference
#include <vans_assemblers.h>
Public Member Functions
VANSAssemblerRong (const Parameters::CFDDEM &cfd_dem)
virtual void calculate_particle_fluid_interactions (NavierStokesScratchData< dim > &scratch_data) override
Public Attributes
const Parameters::CFDDEM cfd_dem
Detailed Description
template<int dim>
class VANSAssemblerRong< dim >
Class that assembles the drag force using Rong model for the VANS equations where the drag coefficient c_d = pow((0.63 + 4.8 / sqrt(re)), 2) * pow(cell_void_fraction, -(2.65 * (cell_void_fraction + 1) - (5.3 - (3.5 * cell_void_fraction)) * pow(cell_void_fraction, 2) * exp(-pow(1.5 - log10(re), 2) / 2))) and the momentum exchange coefficient beta =(0.5 * c_d * M_PI * pow(particle_properties[DEM::PropertiesIndex::dp], 2) / 4) * relative_velocity.norm()
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 226 of file vans_assemblers.h.
Constructor & Destructor Documentation
VANSAssemblerRong()
template<int dim> VANSAssemblerRong< dim >::VANSAssemblerRong (const Parameters::CFDDEM & cfd_dem) inline
Definition at line 229 of file vans_assemblers.h.
Member Function Documentation
calculate_particle_fluid_interactions()
template<int dim> void VANSAssemblerRong< dim >::calculate_particle_fluid_interactions (NavierStokesScratchData< dim > & scratch_data) override virtual
calculate_particle_fluid_interactions calculated the solid_fluid interactions
Parameters
scratch_data (see base class)
copy_data (see base class)
Implements ParticleFluidAssemblerBase< dim >.
Definition at line 977 of file vans_assemblers.cc.
References NavierStokesScratchData< dim >::beta_drag, NavierStokesScratchData< dim >::cell_void_fraction, NavierStokesScratchData< dim >::cell_volume, PhysicalPropertiesManager::density_is_constant(), DEM::dp, DEM::fem_force_x, NavierStokesScratchData< dim >::fluid_particle_relative_velocity_at_particle_location, PhysicalPropertiesManager::get_density_scale(), PhysicalPropertiesManager::is_non_newtonian(), NavierStokesScratchData< dim >::pic, NavierStokesScratchData< dim >::properties_manager, and NavierStokesScratchData< dim >::Re_particle.
Member Data Documentation
cfd_dem
template<int dim> const Parameters::CFDDEM VANSAssemblerRong< dim >::cfd_dem
Definition at line 242 of file vans_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/vans_assemblers.h
/home/runner/work/lethe/lethe/source/fem-dem/vans_assemblers.cc