Lethe Open-Source Library: VANSAssemblerSaffmanMei< dim > Class Template Reference
VANSAssemblerSaffmanMei< dim > Class Template Reference
#include <vans_assemblers.h>
Public Member Functions
VANSAssemblerSaffmanMei (Parameters::Lagrangian::LagrangianPhysicalProperties lagrangian_physical_properties)
virtual void calculate_particle_fluid_interactions (NavierStokesScratchData< dim > &scratch_data) override
Public Attributes
Parameters::Lagrangian::LagrangianPhysicalProperties lagrangian_physical_properties
Detailed Description
template<int dim>
class VANSAssemblerSaffmanMei< dim >
Class that assembles the Lift force using Saffman-Mei model.
This implementation follows the formulation in the book "Multiphase Flows with Droplets and Particles" by Crowe et al. (2011) and the brief communication article "An approximate expression for the shear lift force on a spherical particle at finite reynolds number" by Mei (1992)
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 436 of file vans_assemblers.h.
Constructor & Destructor Documentation
VANSAssemblerSaffmanMei()
template<int dim> VANSAssemblerSaffmanMei< dim >::VANSAssemblerSaffmanMei (Parameters::Lagrangian::LagrangianPhysicalProperties lagrangian_physical_properties) inline
Definition at line 439 of file vans_assemblers.h.
Member Function Documentation
calculate_particle_fluid_interactions()
template<int dim> void VANSAssemblerSaffmanMei< dim >::calculate_particle_fluid_interactions (NavierStokesScratchData< dim > & scratch_data) override virtual
calculate_particle_fluid_interactions calculates the buoyancy force
Parameters
scratch_data (see base class)
copy_data (see base class)
Implements ParticleFluidAssemblerBase< dim >.
Definition at line 1393 of file vans_assemblers.cc.
References NavierStokesScratchData< dim >::cell_volume, PhysicalPropertiesManager::density_is_constant(), DEM::CFDDEMProperties::dp, DEM::CFDDEMProperties::fem_force_x, NavierStokesScratchData< dim >::fluid_particle_relative_velocity_at_particle_location, NavierStokesScratchData< dim >::fluid_velocity_curls_at_particle_location_2d, NavierStokesScratchData< dim >::fluid_velocity_curls_at_particle_location_3d, PhysicalPropertiesManager::get_density_scale(), PhysicalPropertiesManager::get_kinematic_viscosity_scale(), PhysicalPropertiesManager::is_non_newtonian(), NavierStokesScratchData< dim >::pic, NavierStokesScratchData< dim >::properties_manager, NavierStokesScratchData< dim >::Re_particle, and NavierStokesScratchData< dim >::undisturbed_flow_force.
Member Data Documentation
lagrangian_physical_properties
template<int dim> Parameters::Lagrangian::LagrangianPhysicalProperties VANSAssemblerSaffmanMei< dim >::lagrangian_physical_properties
Definition at line 455 of file vans_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/vans_assemblers.h
/home/runner/work/lethe/lethe/source/fem-dem/vans_assemblers.cc