Lethe Open-Source Library: ScalarCouplingEvaluationSIPG< dim, n_components, Number > Class Template Reference
ScalarCouplingEvaluationSIPG< dim, n_components, Number > Class Template Reference
#include <mortar_coupling_manager.h>
Public Types
using FEPointIntegrator = FEPointEvaluation< n_components, dim, dim, Number >
using value_type = typename FEPointIntegrator::value_type
Public Member Functions
ScalarCouplingEvaluationSIPG (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const unsigned int first_selected_component=0)
unsigned int data_size () const override
const std::vector< unsigned int > & get_relevant_dof_indices () const override
void local_reinit (const typename Triangulation< dim >::cell_iterator &cell, const ArrayView< const Point< dim, Number > > &points) const override
void local_evaluate (const CouplingEvaluationData< dim, Number > &data, const Vector< Number > &buffer, const unsigned int ptr_q, const unsigned int q_stride, Number *all_value_m) const override
void local_integrate (const CouplingEvaluationData< dim, Number > &data, Vector< Number > &buffer, const unsigned int ptr_q, const unsigned int q_stride, Number *all_value_m, Number *all_value_p) const override
Public Member Functions inherited from CouplingEvaluationBase< dim, Number >
virtual ~CouplingEvaluationBase ()=default
Public Attributes
const FESystem< dim > fe_sub
FEPointIntegrator phi_m
std::vector< unsigned int > relevant_dof_indices
Detailed Description
template<int dim, int n_components, typename Number>
class ScalarCouplingEvaluationSIPG< dim, n_components, Number >
Definition at line 1101 of file mortar_coupling_manager.h.
Member Typedef Documentation
FEPointIntegrator
template<int dim, int n_components, typename Number > using ScalarCouplingEvaluationSIPG< dim, n_components, Number >::FEPointIntegrator = FEPointEvaluation<n_components, dim, dim, Number>
Definition at line 1104 of file mortar_coupling_manager.h.
value_type
template<int dim, int n_components, typename Number > using ScalarCouplingEvaluationSIPG< dim, n_components, Number >::value_type = typename FEPointIntegrator::value_type
Definition at line 1105 of file mortar_coupling_manager.h.
Constructor & Destructor Documentation
ScalarCouplingEvaluationSIPG()
template<int dim, int n_components, typename Number > ScalarCouplingEvaluationSIPG< dim, n_components, Number >::ScalarCouplingEvaluationSIPG (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const unsigned int first_selected_component = 0)
Definition at line 1770 of file mortar_coupling_manager.cc.
References ScalarCouplingEvaluationSIPG< dim, n_components, Number >::relevant_dof_indices.
Member Function Documentation
data_size()
template<int dim, int n_components, typename Number > unsigned int ScalarCouplingEvaluationSIPG< dim, n_components, Number >::data_size () const override virtual
Number of data points of type Number associated to a quadrature point.
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1791 of file mortar_coupling_manager.cc.
get_relevant_dof_indices()
template<int dim, int n_components, typename Number > const std::vector< unsigned int > & ScalarCouplingEvaluationSIPG< dim, n_components, Number >::get_relevant_dof_indices () const override virtual
Return relevant dof indices.
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1798 of file mortar_coupling_manager.cc.
local_evaluate()
template<int dim, int n_components, typename Number > void ScalarCouplingEvaluationSIPG< dim, n_components, Number >::local_evaluate (const CouplingEvaluationData< dim, Number > & data, const Vector< Number > & buffer, const unsigned int ptr_q, const unsigned int q_stride, Number * all_value_m) const override virtual
Evaluate values and gradients at the coupling entries.
Parameters
[in] data Coupling evaluation data containing values of normals, weights, and penalty parameters at each integration point
[in,out] buffer Temporary vector where data is stored before being passes to the system matrix
[in] ptr_q Pointer for the quadrature point index related to the rotor-stator interface
[in] q_stride Pointer for the cell index in which the quadrature point lies in
[in] all_value_m Number of values stored in the mortar side of the interface
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1815 of file mortar_coupling_manager.cc.
References CouplingEvaluationData< dim, Number >::all_normals, contract(), and BufferRW< T >::write().
local_integrate()
template<int dim, int n_components, typename Number > void ScalarCouplingEvaluationSIPG< dim, n_components, Number >::local_integrate (const CouplingEvaluationData< dim, Number > & data, Vector< Number > & buffer, const unsigned int ptr_q, const unsigned int q_stride, Number * all_value_m, Number * all_value_p) const override virtual
Perform integral of mortar elements at the rotor-stator interface.
Parameters
[in] data Coupling evaluation data containing values of normals, weights, and penalty parameters at each integration point
[in] buffer Temporary vector where data is stored before being passes to the system matrix
[in] ptr_q Pointer for the quadrature point index related to the rotor-stator interface
[in] q_stride Pointer for the cell index in which the quadrature point lies in
[in] all_value_m Number of values stored in the mortar side of the interface
[in] all_value_p Number of values stored in the non-mortar side of the interface
Notation referring to quantities on both mortar sides: {{.}} = avg(.), and [.] = jump(.) *
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1847 of file mortar_coupling_manager.cc.
References CouplingEvaluationData< dim, Number >::all_normals, CouplingEvaluationData< dim, Number >::all_penalty_parameter, CouplingEvaluationData< dim, Number >::all_weights, contract(), outer(), and CouplingEvaluationData< dim, Number >::penalty_factor.
local_reinit()
template<int dim, int n_components, typename Number > void ScalarCouplingEvaluationSIPG< dim, n_components, Number >::local_reinit (const typename Triangulation< dim >::cell_iterator & cell, const ArrayView< const Point< dim, Number > > & points) const override virtual
Set up mapping information.
Parameters
[in] cell Cell iterator
[in] points List of points where FEPointIntegrator should be evaluated
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1806 of file mortar_coupling_manager.cc.
Member Data Documentation
fe_sub
template<int dim, int n_components, typename Number > const FESystem<dim> ScalarCouplingEvaluationSIPG< dim, n_components, Number >::fe_sub
Finite element that matches the components n_components components starting at component with index first_selected_component
Definition at line 1139 of file mortar_coupling_manager.h.
phi_m
template<int dim, int n_components, typename Number > FEPointIntegrator ScalarCouplingEvaluationSIPG< dim, n_components, Number >::phi_m mutable
Interface to the evaluation of mortar coupling interpolated solution.
Definition at line 1142 of file mortar_coupling_manager.h.
relevant_dof_indices
template<int dim, int n_components, typename Number > std::vector<unsigned int> ScalarCouplingEvaluationSIPG< dim, n_components, Number >::relevant_dof_indices
Relevant dof indices.
Definition at line 1145 of file mortar_coupling_manager.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/mortar_coupling_manager.h
/home/runner/work/lethe/lethe/source/core/mortar_coupling_manager.cc