Lethe Open-Source Library: FluidDynamicsMatrixFree< dim > Class Template Reference
FluidDynamicsMatrixFree< dim > Class Template Reference
#include <fluid_dynamics_matrix_free.h>
Public Member Functions
FluidDynamicsMatrixFree (SimulationParameters< dim > &nsparam)
~FluidDynamicsMatrixFree ()
virtual void solve ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Protected Member Functions
virtual void setup_dofs_fd () override
virtual void set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart=false) override
virtual void assemble_system_matrix () override
virtual void assemble_system_rhs () override
virtual void update_multiphysics_time_average_solution () override
virtual void update_solutions_for_multiphysics () override
virtual void update_solutions_for_fluid_dynamics () override
void calculate_time_derivative_previous_solutions ()
void setup_preconditioner () override
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
void print_mg_setup_times ()
Protected Member Functions inherited from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual LinearAlgebra::distributed::Vector< double > & get_evaluation_point () override
virtual LinearAlgebra::distributed::Vector< double > & get_local_evaluation_point () override
virtual LinearAlgebra::distributed::Vector< double > & get_newton_update () override
virtual LinearAlgebra::distributed::Vector< double > & get_present_solution () override
virtual LinearAlgebra::distributed::Vector< double > & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void setup_dofs ()
virtual void set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart=false)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void postprocess_fd (bool first_iteration)
void postprocessing_forces (const LinearAlgebra::distributed::Vector< double > &evaluation_point)
void postprocessing_torques (const LinearAlgebra::distributed::Vector< double > &evaluation_point)
virtual void dynamic_flow_control ()
virtual void iterate ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
virtual void read_checkpoint ()
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
virtual void write_checkpoint ()
void write_output_results (const LinearAlgebra::distributed::Vector< double > &solution)
virtual void output_field_hook (DataOut< dim > &)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
LinearAlgebra::distributed::Vector< double > init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes
std::shared_ptr< NavierStokesOperatorBase< dim, double > > system_operator
std::shared_ptr< MFNavierStokesPreconditionGMGBase< dim > > gmg_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
VectorType time_derivative_previous_solutions
DoFHandler< dim > dof_handler_fe_q_iso_q1
TrilinosWrappers::MPI::Vector multiphysics_average_velocities
TrilinosWrappers::MPI::Vector multiphysics_present_solution
std::vector< TrilinosWrappers::MPI::Vector > multiphysics_previous_solutions
VectorType temperature_present_solution
std::shared_ptr< PhysicalPropertiesManager > physical_properties_manager
Protected Attributes inherited from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
LinearAlgebra::distributed::Vector< double > evaluation_point
LinearAlgebra::distributed::Vector< double > local_evaluation_point
LinearAlgebra::distributed::Vector< double > newton_update
LinearAlgebra::distributed::Vector< double > present_solution
LinearAlgebra::distributed::Vector< double > system_rhs
std::vector< LinearAlgebra::distributed::Vector< double > > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::shared_ptr< Mapping< dim > > previous_mapping
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, LinearAlgebra::distributed::Vector< double >, IndexSet > > average_velocities
LinearAlgebra::distributed::Vector< double > average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Private Types
using VectorType = LinearAlgebra::distributed::Vector< double >
Private Member Functions
void assemble_L2_projection ()
void solve_system_GMRES (const bool initial_step, const double absolute_residual, const double relative_residual)
virtual void create_GMG ()
virtual void initialize_GMG ()
void setup_GMG ()
void setup_ILU ()
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class FluidDynamicsMatrixFree< dim >
A solver for the incompressible Navier-Stokes equations implemented in a matrix-free fashion.
A matrix-free stabilized solver for the incompressible Navier-Stokes equations implemented in a matrix-free fashion with a sum-factorization approach. It uses a continuous Galerkin discretization and solves the fully-coupled discretized problem in a monolithic way using multigrid preconditioners.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved.
Definition at line 391 of file fluid_dynamics_matrix_free.h.
Member Typedef Documentation
VectorType
template<int dim> using FluidDynamicsMatrixFree< dim >::VectorType = LinearAlgebra::distributed::Vector<double> private
Definition at line 396 of file fluid_dynamics_matrix_free.h.
Constructor & Destructor Documentation
FluidDynamicsMatrixFree()
template<int dim> FluidDynamicsMatrixFree< dim >::FluidDynamicsMatrixFree (SimulationParameters< dim > & nsparam)
Constructor that sets the finite element degree and system operator according to simulation parameters.
Parameters
[in] nsparam Relevant parameters for the solver.
Definition at line 2105 of file fluid_dynamics_matrix_free.cc.
References NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::fe, SimulationParameters< dim >::fem_parameters, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::forcing_function, FluidDynamicsMatrixFree< dim >::physical_properties_manager, Parameters::FEM::pressure_order, Parameters::Stabilization::pspg_supg, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::simulation_parameters, FluidDynamicsMatrixFree< dim >::system_operator, and Parameters::FEM::velocity_order.
~FluidDynamicsMatrixFree()
template<int dim> FluidDynamicsMatrixFree< dim >::~FluidDynamicsMatrixFree ()
Destructor.
Definition at line 2142 of file fluid_dynamics_matrix_free.cc.
Member Function Documentation
assemble_L2_projection()
template<int dim> void FluidDynamicsMatrixFree< dim >::assemble_L2_projection () private
Assemble a L2 projection matrix for the velocity and the pressure, which can be used to set the initial condition for the Navier-Stokes problem. Currently not implemented for this solver.
Definition at line 2862 of file fluid_dynamics_matrix_free.cc.
assemble_system_matrix()
template<int dim> void FluidDynamicsMatrixFree< dim >::assemble_system_matrix () override protected virtual
Assemble the matrix associated with the solver. Only required for compilation and it is not used for the matrix free solver.
Implements PhysicsSolver< VectorType >.
Definition at line 2505 of file fluid_dynamics_matrix_free.cc.
assemble_system_rhs()
template<int dim> void FluidDynamicsMatrixFree< dim >::assemble_system_rhs () override protected virtual
Assemble the system right hand side associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 2513 of file fluid_dynamics_matrix_free.cc.
calculate_time_derivative_previous_solutions()
template<int dim> void FluidDynamicsMatrixFree< dim >::calculate_time_derivative_previous_solutions () protected
Calculate and store time derivatives of previous solutions according to time-stepping scheme to use them in the operator.
Definition at line 2566 of file fluid_dynamics_matrix_free.cc.
References number_of_previous_solutions().
create_GMG()
template<int dim> void FluidDynamicsMatrixFree< dim >::create_GMG () private virtual
Create the geometric multigrid preconditioner.
Reimplemented in FluidDynamicsVANSMatrixFree< dim >.
Definition at line 2585 of file fluid_dynamics_matrix_free.cc.
initialize_GMG()
template<int dim> void FluidDynamicsMatrixFree< dim >::initialize_GMG () private virtual
Intialize the geometric multigrid preconditioner.
Reimplemented in FluidDynamicsVANSMatrixFree< dim >.
Definition at line 2602 of file fluid_dynamics_matrix_free.cc.
References heat_transfer.
print_mg_setup_times()
template<int dim> void FluidDynamicsMatrixFree< dim >::print_mg_setup_times () protected
Prints the setup times for the geometric multigrid preconditioner.
Definition at line 2657 of file fluid_dynamics_matrix_free.cc.
References announce_string(), Parameters::extra_verbose, and fluid_dynamics.
set_initial_condition_fd()
template<int dim> void FluidDynamicsMatrixFree< dim >::set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart = false) override protected virtual
Set the initial conditions for the solver. If the simulation is restarted from a checkpoint, the initial solution setting is bypassed and the checkpoint is instead read.
Parameters
[in] initial_condition_type The type of initial condition to be set.
[in] restart A boolean that indicates if the simulation is being restarted. If set to true, the initial conditions are never set, but are instead overriden by the read_checkpoint functionality.
Implements NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 2379 of file fluid_dynamics_matrix_free.cc.
References Parameters::nodal, Parameters::Timer::none, Parameters::ramp, read_checkpoint(), Parameters::SimulationControl::steady, and Parameters::viscous.
setup_dofs_fd()
template<int dim> void FluidDynamicsMatrixFree< dim >::setup_dofs_fd () override protected virtual
Setup the degrees of freedom, system constraints, system operator and solution vectors.
Implements NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 2233 of file fluid_dynamics_matrix_free.cc.
References fluid_dynamics, Parameters::LinearSolver::lsmg, BoundaryConditions::partial_slip, and BoundaryConditions::pressure.
setup_GMG()
template<int dim> void FluidDynamicsMatrixFree< dim >::setup_GMG () private
Setup the geometric multigrid preconditioner.
Definition at line 2620 of file fluid_dynamics_matrix_free.cc.
setup_ILU()
template<int dim> void FluidDynamicsMatrixFree< dim >::setup_ILU () private
Setup the implicit LU preconditioner and call the solve function of the linear solver. Attention: an actual matrix needs to be constructed using the matrix-free operator.
Definition at line 2632 of file fluid_dynamics_matrix_free.cc.
References fluid_dynamics.
setup_preconditioner()
template<int dim> void FluidDynamicsMatrixFree< dim >::setup_preconditioner () override protected virtual
Set up appropriate preconditioner.
Implements PhysicsSolver< VectorType >.
Definition at line 2804 of file fluid_dynamics_matrix_free.cc.
References Parameters::LinearSolver::amg, fluid_dynamics, Parameters::LinearSolver::gcmg, Parameters::LinearSolver::ilu, and Parameters::LinearSolver::lsmg.
solve()
template<int dim> void FluidDynamicsMatrixFree< dim >::solve () virtual
Solve the problem defined by simulation parameters by iterating through time or through the mesh refinements.
Reimplemented in FluidDynamicsVANSMatrixFree< dim >.
Definition at line 2149 of file fluid_dynamics_matrix_free.cc.
References Parameters::Timer::end, heat_transfer, is_bdf(), Parameters::Timer::iteration, read_mesh_and_manifolds(), and NavierStokesBase< dim, VectorType, DofsType >::refine_mesh().
solve_linear_system()
template<int dim> void FluidDynamicsMatrixFree< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override protected virtual
Solve the linear system of equations using the method specified in the simulation parameters.
Parameters
[in] initial_step Indicates if this is the first solution of the linear system. If this is the case, the non_zero version of the constraints are used for the Dirichlet boundary conditions.
[in] renewed_matrix Indicates if the matrix has been reassembled, and thus the preconditioner needs to be reassembled.
Implements PhysicsSolver< VectorType >.
Definition at line 2841 of file fluid_dynamics_matrix_free.cc.
References fluid_dynamics, and Parameters::LinearSolver::gmres.
solve_system_GMRES()
template<int dim> void FluidDynamicsMatrixFree< dim >::solve_system_GMRES (const bool initial_step, const double absolute_residual, const double relative_residual) private
GMRES solver with preconditioning.
Parameters
[in] initial_step Indicates if this is the first solution of the linear system. If this is the case, the non_zero version of the constraints are used for the Dirichlet boundary conditions
[in] absolute_residual Used to define the linear solver tolerance.
[in] relative_residual Used to define the linear solver tolerance.
Definition at line 2869 of file fluid_dynamics_matrix_free.cc.
References fluid_dynamics, Parameters::LinearSolver::gcmg, Parameters::LinearSolver::ilu, Parameters::LinearSolver::lsmg, and Parameters::quiet.
update_multiphysics_time_average_solution()
template<int dim> void FluidDynamicsMatrixFree< dim >::update_multiphysics_time_average_solution () override protected virtual
Update the average velocity field solution in the multiphyscics interface.
Implements NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 2539 of file fluid_dynamics_matrix_free.cc.
References convert_vector_dealii_to_trilinos(), and fluid_dynamics.
update_solutions_for_fluid_dynamics()
template<int dim> void FluidDynamicsMatrixFree< dim >::update_solutions_for_fluid_dynamics () override protected virtual
Provide present multiphysics solutions from the multiphysics interface to the fluid dynamics.
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 2766 of file fluid_dynamics_matrix_free.cc.
References convert_vector_trilinos_to_dealii(), and heat_transfer.
update_solutions_for_multiphysics()
template<int dim> void FluidDynamicsMatrixFree< dim >::update_solutions_for_multiphysics () override protected virtual
Provide present and previous flow solutions to the multiphysics interface. These solutions can be accessed through the multiphysics interface by the different physics.
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 2709 of file fluid_dynamics_matrix_free.cc.
References convert_vector_dealii_to_trilinos(), fluid_dynamics, and number_of_previous_solutions().
Member Data Documentation
dof_handler_fe_q_iso_q1
template<int dim> DoFHandler<dim> FluidDynamicsMatrixFree< dim >::dof_handler_fe_q_iso_q1 protected
Describes the layout of DoFs for FE_Q_iso_Q1 elements.
Definition at line 601 of file fluid_dynamics_matrix_free.h.
gmg_preconditioner
template<int dim> std::shared_ptr<MFNavierStokesPreconditionGMGBase<dim> > FluidDynamicsMatrixFree< dim >::gmg_preconditioner protected
Geometric multigrid preconditioner.
Definition at line 582 of file fluid_dynamics_matrix_free.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> FluidDynamicsMatrixFree< dim >::ilu_preconditioner protected
Implicit LU preconditioner.
Definition at line 588 of file fluid_dynamics_matrix_free.h.
multiphysics_average_velocities
template<int dim> TrilinosWrappers::MPI::Vector FluidDynamicsMatrixFree< dim >::multiphysics_average_velocities protected
Trilinos vector storing the average velocities that are provided to other physics.
Definition at line 608 of file fluid_dynamics_matrix_free.h.
multiphysics_present_solution
template<int dim> TrilinosWrappers::MPI::Vector FluidDynamicsMatrixFree< dim >::multiphysics_present_solution protected
Trilinos vector storing the present solution that is provided to other physics.
Definition at line 614 of file fluid_dynamics_matrix_free.h.
multiphysics_previous_solutions
template<int dim> std::vector<TrilinosWrappers::MPI::Vector> FluidDynamicsMatrixFree< dim >::multiphysics_previous_solutions protected
Vector storing trilinos vectors containing the previous solutions that are provided to other physics.
Definition at line 621 of file fluid_dynamics_matrix_free.h.
physical_properties_manager
template<int dim> std::shared_ptr<PhysicalPropertiesManager> FluidDynamicsMatrixFree< dim >::physical_properties_manager protected
Pointer to the physical properties object.
Definition at line 633 of file fluid_dynamics_matrix_free.h.
system_operator
template<int dim> std::shared_ptr<NavierStokesOperatorBase<dim, double> > FluidDynamicsMatrixFree< dim >::system_operator protected
Matrix-free operator in used for all the matrix-vector multiplications calls (vmult).
Definition at line 576 of file fluid_dynamics_matrix_free.h.
temperature_present_solution
template<int dim> VectorType FluidDynamicsMatrixFree< dim >::temperature_present_solution protected
Vector storing the present temperature solution from the heat transfer solver.
Definition at line 627 of file fluid_dynamics_matrix_free.h.
time_derivative_previous_solutions
template<int dim> VectorType FluidDynamicsMatrixFree< dim >::time_derivative_previous_solutions protected
Vector to store the time derivatives of the previous solutions at the end of each time step for time-dependent simulations.
Definition at line 595 of file fluid_dynamics_matrix_free.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/fluid_dynamics_matrix_free.h
/home/runner/work/lethe/lethe/source/solvers/fluid_dynamics_matrix_free.cc