Lethe Open-Source Library: HeatTransfer< dim > Class Template Reference
HeatTransfer< dim > Class Template Reference
#include <heat_transfer.h>
Public Member Functions
HeatTransfer (MultiphysicsInterface< dim > *multiphysics_interface, const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control)
void assemble_matrix_and_rhs ()
void assemble_rhs ()
void assemble_nitsche_heat_restriction (const bool assemble_matrix)
void attach_solution_to_output (DataOut< dim > &data_out) override
double calculate_delta_T_ref (double minimum_delta_T_ref=1.)
double calculate_L2_error ()
void finish_simulation () override
void percolate_time_vectors () override
void postprocess (bool first_iteration) override
void pre_mesh_adaptation () override
void post_mesh_adaptation () override
void compute_kelly (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > &ivar, dealii::Vector< float > &estimated_error_per_cell) override
void write_checkpoint () override
void read_checkpoint () override
void setup_dofs () override
void set_initial_conditions () override
void update_boundary_conditions () override
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
const DoFHandler< dim > & get_dof_handler () override
GlobalVectorType & get_evaluation_point () override
GlobalVectorType & get_local_evaluation_point () override
GlobalVectorType & get_newton_update () override
GlobalVectorType & get_present_solution () override
GlobalVectorType & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
void output_newton_update_norms (const unsigned int display_precision) override
Public Member Functions inherited from AuxiliaryPhysics< dim, GlobalVectorType >
AuxiliaryPhysics (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~AuxiliaryPhysics ()
virtual void modify_solution ()
void setup_preconditioner () override
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void verify_consistency_of_boundary_conditions ()
void assemble_system_matrix () override
void assemble_system_rhs () override
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, HeatTransferScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, HeatTransferScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
virtual void setup_assemblers ()
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData &copy_data)
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData &copy_data)
void postprocess_temperature_statistics (const bool gather_vof, const Parameters::FluidIndicator monitored_fluid, const std::string domain_name, const bool time_average)
void write_temperature_statistics (const std::string domain_name)
void postprocess_liquid_fraction (const bool gather_vof)
void write_liquid_fraction ()
template<typename VectorType >
void postprocess_heat_flux_on_bc (const bool gather_vof, const VectorType &current_solution_fd)
void postprocess_heat_flux_on_nitsche_ib ()
template<typename VectorType >
void postprocess_thermal_energy_in_fluid (const bool gather_vof, const Parameters::FluidIndicator monitored_fluid, const std::string domain_name, const VectorType &current_solution_fd)
void write_heat_flux (const std::string domain_name)
std::pair< double, bool > set_phase_coefficient (const bool gather_vof, const Parameters::FluidIndicator monitored_fluid, const double phase_value_q)
Private Attributes
MultiphysicsInterface< dim > * multiphysics
TimerOutput computing_timer
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< SimulationControl > simulation_control
DoFHandler< dim > dof_handler
std::shared_ptr< FiniteElement< dim > > fe
ConvergenceTable error_table
std::shared_ptr< Mapping< dim > > temperature_mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
GlobalVectorType present_solution
GlobalVectorType system_rhs
AffineConstraints< double > nonzero_constraints
AffineConstraints< double > zero_constraints
TrilinosWrappers::SparseMatrix system_matrix
std::vector< GlobalVectorType > previous_solutions
std::shared_ptr< SolutionTransfer< dim, GlobalVectorType > > solution_transfer
std::vector< SolutionTransfer< dim, GlobalVectorType > > previous_solutions_transfer
const bool GGLS = true
std::vector< std::shared_ptr< HeatTransferAssemblerBase< dim > > > assemblers
TableHandler statistics_table
TableHandler heat_flux_table
std::vector< std::shared_ptr< ThermalConductivityModel > > thermal_conductivity_models
std::shared_ptr< AverageScalar< dim > > average_temperature
GlobalVectorType average_temperature_to_output
std::vector< HeatFluxPostprocessor< dim > > heat_flux_postprocessors
std::vector< HeatFluxPostprocessor< dim > > average_heat_flux_postprocessors
TableHandler liquid_fraction_table
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class HeatTransfer< dim >
Implementation of heat transfer as an auxiliary physics. The heat equation is weakly coupled to the velocity field. Equation solved: \(\rho C_p \cdot \left(\frac{dT}{dt} + u \cdot \nabla T \right) = k \cdot \nabla^2 T + \tau : \nabla u \).
Definition at line 50 of file heat_transfer.h.
Constructor & Destructor Documentation
HeatTransfer()
template<int dim> HeatTransfer< dim >::HeatTransfer (MultiphysicsInterface< dim > * multiphysics_interface, const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control) inline
Constructor of the HeatTransfer object.
Parameters
multiphysics_interface Map of the auxiliary physics that will be solved on top of a computational fluid dynamic simulation.
p_simulation_parameters Contain the simulation parameter file information.
p_triangulation Contain the mesh information. In a parallel::DistributedTriangulationBase<dim> not every detail may be known on each processor. The mesh is distributed between the processors.
p_simulation_control Object responsible for the control of steady-state and transient simulations. Contains all the information related to time stepping and the stopping criteria.
Definition at line 71 of file heat_transfer.h.
References HeatTransfer< dim >::average_temperature, HeatTransfer< dim >::cell_quadrature, HeatTransfer< dim >::computing_timer, HeatTransfer< dim >::dof_handler, HeatTransfer< dim >::face_quadrature, HeatTransfer< dim >::fe, maximum_number_of_previous_solutions(), Parameters::Timer::none, HeatTransfer< dim >::previous_solutions, HeatTransfer< dim >::previous_solutions_transfer, HeatTransfer< dim >::simulation_parameters, HeatTransfer< dim >::solution_transfer, and HeatTransfer< dim >::temperature_mapping.
Member Function Documentation
assemble_local_system_matrix()
template<int dim> void HeatTransfer< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, HeatTransferScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local matrix for a given cell.
Use the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for HeatTransferScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 452 of file heat_transfer.cc.
References HeatTransferScratchData< dim >::calculate_physical_properties(), StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, HeatTransferScratchData< dim >::reinit(), HeatTransferScratchData< dim >::reinit_fluid_dynamics(), HeatTransferScratchData< dim >::reinit_vof(), StabilizedMethodsCopyData::reset(), and VOF.
assemble_local_system_rhs()
template<int dim> void HeatTransfer< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, HeatTransferScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for HeatTransferScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 623 of file heat_transfer.cc.
References HeatTransferScratchData< dim >::calculate_physical_properties(), StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, HeatTransferScratchData< dim >::reinit(), HeatTransferScratchData< dim >::reinit_fluid_dynamics(), HeatTransferScratchData< dim >::reinit_velocity_gradient(), HeatTransferScratchData< dim >::reinit_vof(), StabilizedMethodsCopyData::reset(), and VOF.
assemble_matrix_and_rhs()
template<int dim> void HeatTransfer< dim >::assemble_matrix_and_rhs ()
Call for the assembly of the matrix and the right-hand side.
Deprecated:
This function is to be deprecated when the new assembly mechanism is integrated to this solver.
Definition at line 32 of file heat_transfer.cc.
assemble_nitsche_heat_restriction()
template<int dim> void HeatTransfer< dim >::assemble_nitsche_heat_restriction (const bool assemble_matrix)
Call for the assembly of the matrix and the right-hand side of the Nitsche restriction for the heat transfert equation.
Parameters
assemble_matrix Boolean that is true for matrix assembly, and false for rhs assembly.
std::pow(h_cell * h_cell, double(dim) / double(dim));
Definition at line 53 of file heat_transfer.cc.
assemble_rhs()
template<int dim> void HeatTransfer< dim >::assemble_rhs ()
Call for the assembly of the right-hand side.
Deprecated:
This function is to be deprecated when the new assembly mechanism is integrated to this solver.
Definition at line 44 of file heat_transfer.cc.
assemble_system_matrix()
template<int dim> void HeatTransfer< dim >::assemble_system_matrix () override private virtual
Assemble the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 403 of file heat_transfer.cc.
References HeatTransfer< dim >::assemble_local_system_matrix(), HeatTransfer< dim >::copy_local_matrix_to_global_matrix(), fluid_dynamics, and VOF.
assemble_system_rhs()
template<int dim> void HeatTransfer< dim >::assemble_system_rhs () override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 574 of file heat_transfer.cc.
References HeatTransfer< dim >::assemble_local_system_rhs(), HeatTransfer< dim >::copy_local_rhs_to_global_rhs(), fluid_dynamics, and VOF.
attach_solution_to_output()
template<int dim> void HeatTransfer< dim >::attach_solution_to_output (DataOut< dim > & data_out) override virtual
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
Parameters
data_out Provide output of data described by finite element fields defined on a collection of cells.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 747 of file heat_transfer.cc.
calculate_delta_T_ref()
template<int dim> double HeatTransfer< dim >::calculate_delta_T_ref (double minimum_delta_T_ref = 1.)
Calculate delta_T_ref for the DCDD shock capture mechanism. delta_T_ref = T_max - T_min.
Parameters
minimum_delta_T_ref Minimum temperature value acceptable as reference to calculate the DCDD shock capture stabilization term. DCDD shock capture elements are divided by delta_T_ref. Limiting delta_T_ref prevents overestimation of the virtual diffusivity at simulations with low differences between minimum and maximum temperatures.
Returns
The difference between the maximal temperature and the minimal temperature in the whole domain.
Definition at line 841 of file heat_transfer.cc.
References is_steady().
calculate_L2_error()
template<int dim> double HeatTransfer< dim >::calculate_L2_error ()
Calculate the L2 error of the solution.
Definition at line 867 of file heat_transfer.cc.
compute_kelly()
template<int dim> void HeatTransfer< dim >::compute_kelly (const std::pair< const Variable, Parameters::MultipleAdaptationParameters > & ivar, dealii::Vector< float > & estimated_error_per_cell) override virtual
Compute the Kelly error estimator for mesh refinement.
Parameters
ivar The current element of the map simulation_parameters.mesh_adaptation.variables.
estimated_error_per_cell The deal.II vector of estimated_error_per_cell.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1146 of file heat_transfer.cc.
References temperature.
copy_local_matrix_to_global_matrix()
template<int dim> void HeatTransfer< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell information to global matrix.
Definition at line 559 of file heat_transfer.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void HeatTransfer< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell rhs information to global rhs.
Definition at line 733 of file heat_transfer.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_rhs.
finish_simulation()
template<int dim> void HeatTransfer< dim >::finish_simulation () override virtual
Carry out the operations required to finish a simulation correctly.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 912 of file heat_transfer.cc.
References Parameters::quiet, and Parameters::SimulationControl::steady.
get_dof_handler()
template<int dim> const DoFHandler< dim > & HeatTransfer< dim >::get_dof_handler () inline override virtual
Getter method to access the private attribute dof_handler for the physic currently solved. NB : dof_handler is now passed to the multiphysics interface at the end of the setup_dofs method.
Returns
A list of the indices of the degrees of freedom.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 297 of file heat_transfer.h.
References HeatTransfer< dim >::dof_handler.
get_evaluation_point()
template<int dim> GlobalVectorType & HeatTransfer< dim >::get_evaluation_point () inline override virtual
Getter method to access the private attribute evaluation_point for the physic currently solved.
Returns
The vector at which the evaluation is performed.
Implements PhysicsSolver< VectorType >.
Definition at line 309 of file heat_transfer.h.
References HeatTransfer< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> GlobalVectorType & HeatTransfer< dim >::get_local_evaluation_point () inline override virtual
Getter method to access the private attribute local_evaluation_point for the physic currently solved.
Returns
The local evaluation point. Ghosts cells are not considered in this evaluation.
Implements PhysicsSolver< VectorType >.
Definition at line 322 of file heat_transfer.h.
References HeatTransfer< dim >::local_evaluation_point.
get_newton_update()
template<int dim> GlobalVectorType & HeatTransfer< dim >::get_newton_update () inline override virtual
Getter method to access the private attribute newton_update for the physic currently solved.
Returns
The direction used to perform the newton iteration.
Implements PhysicsSolver< VectorType >.
Definition at line 334 of file heat_transfer.h.
References HeatTransfer< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints< double > & HeatTransfer< dim >::get_nonzero_constraints () inline override virtual
Getter method to access the private attribute nonzero_constraints for the physic currently solved.
Returns
Store the nonzero constraints that arise from several sources such as boundary conditions and hanging nodes in the mesh. See the deal.II documentation on constraints on degrees of freedom for more information.
Implements PhysicsSolver< VectorType >.
Definition at line 374 of file heat_transfer.h.
References HeatTransfer< dim >::nonzero_constraints.
get_present_solution()
template<int dim> GlobalVectorType & HeatTransfer< dim >::get_present_solution () inline override virtual
Getter method to access the private attribute present_solution for the physic currently solved. NB : present_solution is now passed to the multiphysics interface at the end of the setup_dofs method.
Returns
A vector containing all the values of the solution.
Implements PhysicsSolver< VectorType >.
Definition at line 348 of file heat_transfer.h.
References HeatTransfer< dim >::present_solution.
get_system_rhs()
template<int dim> GlobalVectorType & HeatTransfer< dim >::get_system_rhs () inline override virtual
Getter method to access the private attribute system_rhs for the physic currently solved.
Returns
Right hand side vector.
Implements PhysicsSolver< VectorType >.
Definition at line 360 of file heat_transfer.h.
References HeatTransfer< dim >::system_rhs.
output_newton_update_norms()
template<int dim> void HeatTransfer< dim >::output_newton_update_norms (const unsigned int display_precision) inline override virtual
Output the L2 and Linfty norms of the correction vector.
Parameters
[in] display_precision Number of outputted digits.
Implements PhysicsSolver< VectorType >.
Definition at line 385 of file heat_transfer.h.
References HeatTransfer< dim >::newton_update, and PhysicsSolver< VectorType >::pcout.
percolate_time_vectors()
template<int dim> void HeatTransfer< dim >::percolate_time_vectors () override virtual
Rearrange vector solution correctly for transient simulations.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 940 of file heat_transfer.cc.
post_mesh_adaptation()
template<int dim> void HeatTransfer< dim >::post_mesh_adaptation () override virtual
Interpolate the auxiliary physics variables to the new mesh.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1113 of file heat_transfer.cc.
postprocess()
template<int dim> void HeatTransfer< dim >::postprocess (bool first_iteration) override virtual
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 951 of file heat_transfer.cc.
References announce_string(), calculate_L2_error(), Parameters::fluid0, Parameters::fluid1, fluid_dynamics, Parameters::Timer::iteration, and Parameters::verbose.
postprocess_heat_flux_on_bc()
template<int dim> template<typename VectorType > template void HeatTransfer< dim >::postprocess_heat_flux_on_bc< GlobalBlockVectorType > (const bool gather_vof, const VectorType & current_solution_fd) private
Post-processing. Calculate the heat flux at heat transfer boundary conditions.
Parameters
gather_vof boolean true when VOF=true (multiphase flow), used to gather VOF information
current_solution_fd current solution for the fluid dynamics, parsed by postprocess
Definition at line 1999 of file heat_transfer.cc.
References calculate_point_property(), fluid_dynamics, Parameters::verbose, and VOF.
postprocess_heat_flux_on_nitsche_ib()
template<int dim> void HeatTransfer< dim >::postprocess_heat_flux_on_nitsche_ib () private
Post-processing. Calculate the heat flux in the Nitsche immersed boundary.
Definition at line 174 of file heat_transfer.cc.
References Parameters::verbose.
postprocess_liquid_fraction()
template<int dim> void HeatTransfer< dim >::postprocess_liquid_fraction (const bool gather_vof) private
Post-processing. Calculate liquid fraction on the domain.
Parameters
gather_vof boolean true when VOF=true (multiphase flow), used to gather VOF information
Definition at line 1842 of file heat_transfer.cc.
References calculate_liquid_fraction(), Parameters::Material::phase_change, Parameters::verbose, and VOF.
postprocess_temperature_statistics()
template<int dim> void HeatTransfer< dim >::postprocess_temperature_statistics (const bool gather_vof, const Parameters::FluidIndicator monitored_fluid, const std::string domain_name, const bool time_average) private
Post-processing. Calculate temperature statistics on the domain : Max, min, average and standard-deviation.
Parameters
gather_vof Boolean true when VOF=true (multiphase flow), used to gather VOF information.
monitored_fluid Fluid indicator (fluid0 or fluid1 or both) corresponding to the phase of interest.
domain_name String indicating the monitored_fluid in the output filename.
time_average Boolean true when calculating the spacial average of the time-averaged temperature solution.
Definition at line 1618 of file heat_transfer.cc.
References Parameters::verbose, and VOF.
postprocess_thermal_energy_in_fluid()
template<int dim> template<typename VectorType > template void HeatTransfer< dim >::postprocess_thermal_energy_in_fluid< GlobalBlockVectorType > (const bool gather_vof, const Parameters::FluidIndicator monitored_fluid, const std::string domain_name, const VectorType & current_solution_fd) private
Post-processing. Calculate the thermal energy \((\rho \cdot C_p \cdot T) \) in a fluid domain.
Parameters
gather_vof Boolean true when VOF=true (multiphase flow), used to gather VOF information.
monitored_fluid Fluid indicator (fluid0 or fluid1 or both) corresponding to the phase of interest.
domain_name String indicating the monitored_fluid in the console output, table and filename.
current_solution_fd Current solution for the fluid dynamics, parsed by postprocess.
Definition at line 2277 of file heat_transfer.cc.
References calculate_point_property(), fluid_dynamics, Parameters::verbose, and VOF.
pre_mesh_adaptation()
template<int dim> void HeatTransfer< dim >::pre_mesh_adaptation () override virtual
Prepare the auxiliary physics variables for a mesh refinement/coarsening.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1097 of file heat_transfer.cc.
read_checkpoint()
template<int dim> void HeatTransfer< dim >::read_checkpoint () override virtual
Allow Heat Transfer to set up solution vector from checkpoint file.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1230 of file heat_transfer.cc.
References deserialize_table().
set_initial_conditions()
template<int dim> void HeatTransfer< dim >::set_initial_conditions () override virtual
Set up the initial conditions associated with the physics. heat_transfer allows a temperature function initial condition over the the domain.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1524 of file heat_transfer.cc.
set_phase_coefficient()
template<int dim> std::pair< double, bool > HeatTransfer< dim >::set_phase_coefficient (const bool gather_vof, const Parameters::FluidIndicator monitored_fluid, const double phase_value_q) private
Set a phase_coefficient that is used in the postprocessing, to account for multiphase flow.
Returns
a double: phase_coefficient from 0 to 1, see the documentation on VOF for more information,
a boolean: point_is_in_postprocessed_fluid, true if the quadrature point is in the postprocessed_fluid (used for min_max_temperature calculation)
Parameters
gather_vof boolean true when VOF=true (multiphase flow), used to gather VOF information
monitored_fluid Fluid indicator (fluid0 or fluid1 or both) corresponding to the phase of interest.
phase_value_q double corresponding to the phase value at this quadrature point
Definition at line 2503 of file heat_transfer.cc.
References Parameters::fluid0, and Parameters::fluid1.
setup_assemblers()
template<int dim> void HeatTransfer< dim >::setup_assemblers () private virtual
Set up the vector of assembler functions.
Definition at line 276 of file heat_transfer.cc.
References is_bdf().
setup_dofs()
template<int dim> void HeatTransfer< dim >::setup_dofs () override virtual
Set up the DofHandler and the degrees of freedom associated with the physics.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1324 of file heat_transfer.cc.
References heat_transfer, BoundaryConditions::periodic, and BoundaryConditions::temperature.
solve_linear_system()
template<int dim> void HeatTransfer< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override virtual
Call for the solution of the linear system of equation using ILU or GMRES.
Parameters
initial_step Provide the linear solver with indication if this solution is the first one for the system of equation or not.
renewed_matrix Indicate to the linear solve if the system matrix has been recalculated or not.
Implements PhysicsSolver< VectorType >.
Definition at line 1537 of file heat_transfer.cc.
References heat_transfer, and Parameters::quiet.
update_boundary_conditions()
template<int dim> void HeatTransfer< dim >::update_boundary_conditions () override virtual
Update non zero constraints if the boundary is time-dependent.
Reimplemented from AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1464 of file heat_transfer.cc.
References BoundaryConditions::periodic, and BoundaryConditions::temperature.
verify_consistency_of_boundary_conditions()
template<int dim> void HeatTransfer< dim >::verify_consistency_of_boundary_conditions () inline private
Verify consistency of the input parameters for boundary conditions to ensure that for every boundary condition within the triangulation, a boundary condition has been specified in the input file.
Definition at line 401 of file heat_transfer.h.
References HeatTransfer< dim >::simulation_parameters, and HeatTransfer< dim >::triangulation.
write_checkpoint()
template<int dim> void HeatTransfer< dim >::write_checkpoint () override virtual
Prepare Heat Transfer to write checkpoint.
Implements AuxiliaryPhysics< dim, GlobalVectorType >.
Definition at line 1168 of file heat_transfer.cc.
References serialize_table().
write_heat_flux()
template<int dim> void HeatTransfer< dim >::write_heat_flux (const std::string domain_name) private
Post-processing. Write the heat transfer values to an output file.
Parameters
domain_name string indicating the postprocessed_fluid in the console output, table and filename.
Definition at line 2485 of file heat_transfer.cc.
write_liquid_fraction()
template<int dim> void HeatTransfer< dim >::write_liquid_fraction () private
Post-processing. Write the liquid fraction to an output file.
Definition at line 1978 of file heat_transfer.cc.
write_temperature_statistics()
template<int dim> void HeatTransfer< dim >::write_temperature_statistics (const std::string domain_name) private
Post-processing. Write the temperature statistics to an output file.
Parameters
domain_name string indicating the postprocessed_fluid in the console output, table and filename.
Definition at line 1824 of file heat_transfer.cc.
Member Data Documentation
assemblers
template<int dim> std::vector<std::shared_ptr<HeatTransferAssemblerBase<dim> > > HeatTransfer< dim >::assemblers private
Assemblers for the matrix and the right hand side (RHS).
Definition at line 774 of file heat_transfer.h.
average_heat_flux_postprocessors
template<int dim> std::vector<HeatFluxPostprocessor<dim> > HeatTransfer< dim >::average_heat_flux_postprocessors private
Compute local average heat flux quantities from temperature field and material properties.
Definition at line 819 of file heat_transfer.h.
average_temperature
template<int dim> std::shared_ptr<AverageScalar<dim> > HeatTransfer< dim >::average_temperature private
Compute the average temperature in time.
Definition at line 802 of file heat_transfer.h.
average_temperature_to_output
template<int dim> GlobalVectorType HeatTransfer< dim >::average_temperature_to_output private
Locally owned average temperature calculated using the AverageScalar object.
Definition at line 807 of file heat_transfer.h.
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > HeatTransfer< dim >::cell_quadrature private
Approximate an integral by evaluating the integrand at specific points and summing the point values with specific weights.
Definition at line 683 of file heat_transfer.h.
computing_timer
template<int dim> TimerOutput HeatTransfer< dim >::computing_timer private
Store information related to the the computing time such as CPU times or wall time.
Definition at line 632 of file heat_transfer.h.
dof_handler
template<int dim> DoFHandler<dim> HeatTransfer< dim >::dof_handler private
Given a triangulation and a description of a finite element, this class enumerates degrees of freedom on all vertices, edges, faces, and cells of the triangulation.
Definition at line 659 of file heat_transfer.h.
error_table
template<int dim> ConvergenceTable HeatTransfer< dim >::error_table private
Store some convergence data, such as residuals of the cg-method, or some evaluated L2-errors of discrete solutions. Evaluate convergence rates or orders.
Definition at line 670 of file heat_transfer.h.
evaluation_point
template<int dim> GlobalVectorType HeatTransfer< dim >::evaluation_point private
The point at which the evaluation is performed.
Definition at line 707 of file heat_transfer.h.
face_quadrature
template<int dim> std::shared_ptr<Quadrature<dim - 1> > HeatTransfer< dim >::face_quadrature private
Approximate an integral by evaluating the integrand at specific points and summing the point values with specific weights.
Definition at line 688 of file heat_transfer.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > HeatTransfer< dim >::fe private
The base class for finite element.
Definition at line 663 of file heat_transfer.h.
GGLS
template<int dim> const bool HeatTransfer< dim >::GGLS = true private
Reference for GGLS https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.2324 Warning, this GGLS implementation is valid only for Linear elements Quad elements will be lacking the third derivative of the diffusion operator Whether this affects or not the final result is unclear to me at the moment. Additionnaly, this formulation does not use the gradient of the source term. The same applies, I have no clue if this is detrimental or not to the solution since anyway the GGLS term scales as h^(order+1).
Definition at line 769 of file heat_transfer.h.
heat_flux_postprocessors
template<int dim> std::vector<HeatFluxPostprocessor<dim> > HeatTransfer< dim >::heat_flux_postprocessors private
Compute local heat flux quantities from temperature field and material properties.
Definition at line 813 of file heat_transfer.h.
heat_flux_table
template<int dim> TableHandler HeatTransfer< dim >::heat_flux_table private
Contain heat flux information used for post-processing:
the total fluxes on a boundary: \((-k \nabla T + u \rho C_p) \cdot n \)
the convective heat flux on a boundary: \(h(T-T_{inf}) \)
the total fluxes on the nitsche immersed boundaries (if active)
Definition at line 788 of file heat_transfer.h.
liquid_fraction_table
template<int dim> TableHandler HeatTransfer< dim >::liquid_fraction_table private
Liquid fraction in the domain.
Definition at line 830 of file heat_transfer.h.
local_evaluation_point
template<int dim> GlobalVectorType HeatTransfer< dim >::local_evaluation_point private
The local evaluation point. Ghosts cells are not considered in this evaluation.
Definition at line 712 of file heat_transfer.h.
locally_owned_dofs
template<int dim> IndexSet HeatTransfer< dim >::locally_owned_dofs private
Store a subset of the DoF indices that are stored on a particular processor on a distributed architecture.
Definition at line 697 of file heat_transfer.h.
locally_relevant_dofs
template<int dim> IndexSet HeatTransfer< dim >::locally_relevant_dofs private
Store a subset of the DoF indices that contains both the locally_owned_dofs and the DoF indices on ghost cells.
Definition at line 702 of file heat_transfer.h.
multiphysics
template<int dim> MultiphysicsInterface<dim>* HeatTransfer< dim >::multiphysics private
Definition at line 626 of file heat_transfer.h.
newton_update
template<int dim> GlobalVectorType HeatTransfer< dim >::newton_update private
The direction \(\delta u^n \) used to perform the newton iteration in \(u^{n+1} = u^n + \alpha ^n \delta u ^n \). Where \(\alpha ^n \) is the size of the step.
Definition at line 718 of file heat_transfer.h.
nonzero_constraints
template<int dim> AffineConstraints<double> HeatTransfer< dim >::nonzero_constraints private
Store the nonzero constraints that arise from several sources such as boundary conditions and hanging nodes in the mesh. See the deal.II documentation on constraints on degrees of freedom for more information.
Definition at line 732 of file heat_transfer.h.
present_solution
template<int dim> GlobalVectorType HeatTransfer< dim >::present_solution private
A vector containing all the values of the solution.
Definition at line 722 of file heat_transfer.h.
previous_solutions
template<int dim> std::vector<GlobalVectorType> HeatTransfer< dim >::previous_solutions private
Previous solution vector.
Definition at line 743 of file heat_transfer.h.
previous_solutions_transfer
template<int dim> std::vector<SolutionTransfer<dim, GlobalVectorType> > HeatTransfer< dim >::previous_solutions_transfer private
previous_solutions_transfer occupies the same role as solution_transfer but for solutions at previous time steps.
Definition at line 758 of file heat_transfer.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> HeatTransfer< dim >::simulation_control private
Responsible for the control of steady-state and transient simulations. Contains all the information related to time stepping and the stopping criteria. See simulation_control abstract class for more information.
Definition at line 653 of file heat_transfer.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& HeatTransfer< dim >::simulation_parameters private
Contain the simulation parameter file information.
Definition at line 637 of file heat_transfer.h.
solution_transfer
template<int dim> std::shared_ptr<SolutionTransfer<dim, GlobalVectorType> > HeatTransfer< dim >::solution_transfer private
SolutionTransfer<dim, GlobalVectorType>> is used to implement the transfer of a discrete FE function (e.g. a solution vector) from one mesh to another. This Deal.ii class is used for mesh_refinement and simulation restarts.
Definition at line 751 of file heat_transfer.h.
statistics_table
template<int dim> TableHandler HeatTransfer< dim >::statistics_table private
Temperature statistics table used for post-processing. It contains the minimum , maximum, average and standard deviation of the temperature.
Definition at line 780 of file heat_transfer.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix HeatTransfer< dim >::system_matrix private
The system matrix.
Definition at line 737 of file heat_transfer.h.
system_rhs
template<int dim> GlobalVectorType HeatTransfer< dim >::system_rhs private
The right hand side vector.
Definition at line 726 of file heat_transfer.h.
temperature_mapping
template<int dim> std::shared_ptr<Mapping<dim> > HeatTransfer< dim >::temperature_mapping private
Transformation which maps point in the reference cell to points in the actual grid cell.
Definition at line 678 of file heat_transfer.h.
thermal_conductivity_models
template<int dim> std::vector<std::shared_ptr<ThermalConductivityModel> > HeatTransfer< dim >::thermal_conductivity_models private
Abstract class that allows to calculate the thermal conductivity on each quadrature point using the temperature of the fluid.
Definition at line 797 of file heat_transfer.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > HeatTransfer< dim >::triangulation private
Collection of cells that cover the domain on which one wants to solve a partial differential equation.
Definition at line 646 of file heat_transfer.h.
zero_constraints
template<int dim> AffineConstraints<double> HeatTransfer< dim >::zero_constraints private
Definition at line 733 of file heat_transfer.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/heat_transfer.h
/home/runner/work/lethe/lethe/source/solvers/heat_transfer.cc