Lethe Open-Source Library: GLSNavierStokesAssemblerCore< dim > Class Template Reference
GLSNavierStokesAssemblerCore< dim > Class Template Reference
#include <navier_stokes_assemblers.h>
Public Member Functions
GLSNavierStokesAssemblerCore (const std::shared_ptr< SimulationControl > &simulation_control)
virtual void assemble_matrix (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual void assemble_rhs (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
Public Member Functions inherited from PhysicsAssemblerBase< ScratchDataType, CopyDataType >
virtual void assemble_matrix (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
virtual void assemble_rhs (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
Public Attributes
const std::shared_ptr< SimulationControl > simulation_control
Detailed Description
template<int dim>
class GLSNavierStokesAssemblerCore< dim >
Class that assembles the core of the Navier-Stokes equation. According to the following weak form: \(\mathbf{u} \cdot \nabla \mathbf{u} - \nabla p - \nu \nabla^2 \mathbf{u} =0 \) with a full GLS stabilization including the laplacian of the test function.
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 96 of file navier_stokes_assemblers.h.
Constructor & Destructor Documentation
GLSNavierStokesAssemblerCore()
template<int dim> GLSNavierStokesAssemblerCore< dim >::GLSNavierStokesAssemblerCore (const std::shared_ptr< SimulationControl > & simulation_control) inline
Definition at line 99 of file navier_stokes_assemblers.h.
Member Function Documentation
assemble_matrix()
template<int dim> void GLSNavierStokesAssemblerCore< dim >::assemble_matrix (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_matrix Assembles the matrix
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 307 of file navier_stokes_assemblers.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::components, NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, NavierStokesScratchData< dim >::kinematic_viscosity, NavierStokesScratchData< dim >::kinematic_viscosity_for_stabilization, NavierStokesScratchData< dim >::laplacian_phi_u, StabilizedMethodsTensorCopyData< dim >::local_matrix, NavierStokesScratchData< dim >::mass_source, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_scaling_factor, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_jacobian, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
assemble_rhs()
template<int dim> void GLSNavierStokesAssemblerCore< dim >::assemble_rhs (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_rhs Assembles the rhs
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 491 of file navier_stokes_assemblers.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, NavierStokesScratchData< dim >::kinematic_viscosity, NavierStokesScratchData< dim >::kinematic_viscosity_for_stabilization, NavierStokesScratchData< dim >::laplacian_phi_u, StabilizedMethodsTensorCopyData< dim >::local_rhs, NavierStokesScratchData< dim >::mass_source, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, pressure, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_values, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_divergences, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
Member Data Documentation
simulation_control
template<int dim> const std::shared_ptr<SimulationControl> GLSNavierStokesAssemblerCore< dim >::simulation_control
Definition at line 122 of file navier_stokes_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/navier_stokes_assemblers.h
/home/runner/work/lethe/lethe/source/solvers/navier_stokes_assemblers.cc