Lethe Open-Source Library: GLSNavierStokesCahnHilliardAssemblerCore< dim > Class Template Reference
GLSNavierStokesCahnHilliardAssemblerCore< dim > Class Template Reference
#include <navier_stokes_cahn_hilliard_assemblers.h>
Public Member Functions
GLSNavierStokesCahnHilliardAssemblerCore (const std::shared_ptr< SimulationControl > &simulation_control, const SimulationParameters< dim > &nsparam)
virtual void assemble_matrix (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual void assemble_rhs (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
Public Member Functions inherited from PhysicsAssemblerBase< ScratchDataType, CopyDataType >
virtual void assemble_matrix (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
virtual void assemble_rhs (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
Public Attributes
const bool SUPG = true
const std::shared_ptr< SimulationControl > simulation_control
const Parameters::CahnHilliard cahn_hilliard_parameters
Detailed Description
template<int dim>
class GLSNavierStokesCahnHilliardAssemblerCore< dim >
Class that assembles the core of the Navier-Stokes equation with free surface using Cahn-Hilliard modeling. According to the following weak form: \(\nabla \cdot \mathbf{u} + \rho \mathbf{u} \cdot \nabla \mathbf{u} + \nabla p - \mu \nabla\cdot (\nabla \mathbf{u} + (\nabla \mathbf{u})^T)=0 \) with an SUPG and PSPG stabilization.
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 28 of file navier_stokes_cahn_hilliard_assemblers.h.
Constructor & Destructor Documentation
GLSNavierStokesCahnHilliardAssemblerCore()
template<int dim> GLSNavierStokesCahnHilliardAssemblerCore< dim >::GLSNavierStokesCahnHilliardAssemblerCore (const std::shared_ptr< SimulationControl > & simulation_control, const SimulationParameters< dim > & nsparam) inline
Definition at line 32 of file navier_stokes_cahn_hilliard_assemblers.h.
Member Function Documentation
assemble_matrix()
template<int dim> void GLSNavierStokesCahnHilliardAssemblerCore< dim >::assemble_matrix (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_matrix Assembles the matrix
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 14 of file navier_stokes_cahn_hilliard_assemblers.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::chemical_potential_cahn_hilliard_values, NavierStokesScratchData< dim >::density, PhysicalPropertiesManager::density_is_constant(), NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::dynamic_viscosity, NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, NavierStokesScratchData< dim >::laplacian_phi_u, StabilizedMethodsTensorCopyData< dim >::local_matrix, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phase_order_cahn_hilliard_gradients, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_scaling_factor, NavierStokesScratchData< dim >::properties_manager, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_jacobian, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_hessians, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
assemble_rhs()
template<int dim> void GLSNavierStokesCahnHilliardAssemblerCore< dim >::assemble_rhs (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_rhs Assembles the rhs
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 192 of file navier_stokes_cahn_hilliard_assemblers.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::chemical_potential_cahn_hilliard_values, NavierStokesScratchData< dim >::density, PhysicalPropertiesManager::density_is_constant(), NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::dynamic_viscosity, NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, StabilizedMethodsTensorCopyData< dim >::local_rhs, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phase_order_cahn_hilliard_gradients, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, pressure, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_values, NavierStokesScratchData< dim >::properties_manager, shear_rate, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_divergences, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_hessians, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
Member Data Documentation
cahn_hilliard_parameters
template<int dim> const Parameters::CahnHilliard GLSNavierStokesCahnHilliardAssemblerCore< dim >::cahn_hilliard_parameters
Definition at line 60 of file navier_stokes_cahn_hilliard_assemblers.h.
simulation_control
template<int dim> const std::shared_ptr<SimulationControl> GLSNavierStokesCahnHilliardAssemblerCore< dim >::simulation_control
Definition at line 59 of file navier_stokes_cahn_hilliard_assemblers.h.
SUPG
template<int dim> const bool GLSNavierStokesCahnHilliardAssemblerCore< dim >::SUPG = true
Definition at line 57 of file navier_stokes_cahn_hilliard_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/navier_stokes_cahn_hilliard_assemblers.h
/home/runner/work/lethe/lethe/source/solvers/navier_stokes_cahn_hilliard_assemblers.cc