Lethe Open-Source Library: VelocityVerletIntegrator< dim, PropertiesIndex > Class Template Reference
VelocityVerletIntegrator< dim, PropertiesIndex > Class Template Reference
#include <velocity_verlet_integrator.h>
Public Member Functions
VelocityVerletIntegrator ()
virtual void integrate_half_step_location (Particles::ParticleHandler< dim > &particle_handler, const Tensor< 1, 3 > &body_force, const double time_step, const std::vector< Tensor< 1, 3 > > &torque, const std::vector< Tensor< 1, 3 > > &force, const std::vector< double > &MOI) override
virtual void integrate (Particles::ParticleHandler< dim > &particle_handler, const Tensor< 1, 3 > &body_force, const double time_step, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force, const std::vector< double > &MOI) override
virtual void integrate (Particles::ParticleHandler< dim > &particle_handler, const Tensor< 1, 3 > &body_force, const double time_step, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force, const std::vector< double > &MOI, const parallel::distributed::Triangulation< dim > &triangulation, AdaptiveSparseContacts< dim, PropertiesIndex > &sparse_contacts_object) override
void integrate_with_advected_particles (Particles::ParticleHandler< dim > &particle_handler, const Tensor< 1, 3 > &body_force, const double time_step, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force, const std::vector< double > &MOI, const parallel::distributed::Triangulation< dim > &triangulation, AdaptiveSparseContacts< dim, PropertiesIndex > &sparse_contacts_object)
Public Member Functions inherited from Integrator< dim, PropertiesIndex >
Integrator ()
virtual ~Integrator ()
Detailed Description
template<int dim, typename PropertiesIndex>
class VelocityVerletIntegrator< dim, PropertiesIndex >
Implementation of a classical velocity verlet scheme for the integration of the particle motion. Note that reinitilization of force and torque is also integrated into integration class.
Velocity Verlet is a second-order integration scheme.
Calculation precedure:
Calculation of half-step velocity v(n+1/2) = v(n) + 1/2 * a(n) * dt
Updating particle position x(n+1) = x(n) + v(n+1/2) * dt
Updating acceleration and velocity of particle a(n+1) = F(n+1) / m v(n+1) = v(n+1/2) + 1/2 * a(n+1) * dt
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Definition at line 38 of file velocity_verlet_integrator.h.
Constructor & Destructor Documentation
VelocityVerletIntegrator()
template<int dim, typename PropertiesIndex > VelocityVerletIntegrator< dim, PropertiesIndex >::VelocityVerletIntegrator () inline
Definition at line 41 of file velocity_verlet_integrator.h.
Member Function Documentation
integrate() [1/2]
template<int dim, typename PropertiesIndex > void VelocityVerletIntegrator< dim, PropertiesIndex >::integrate (Particles::ParticleHandler< dim > & particle_handler, const Tensor< 1, 3 > & body_force, const double time_step, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force, const std::vector< double > & MOI) override virtual
Calculate the integration of the motion of all particles by using the Velocity Verlet method.
Parameters
particle_handler The particle handler whose particle motion we wish to integrate
body_force A constant volumetric body force applied to all particles
time_step The value of the time step used for the integration
torque Torque acting on particles
force Force acting on particles
MOI A container of moment of inertia of particles
Implements Integrator< dim, PropertiesIndex >.
Definition at line 59 of file velocity_verlet_integrator.cc.
References point_nd_to_3d().
integrate() [2/2]
template<int dim, typename PropertiesIndex > void VelocityVerletIntegrator< dim, PropertiesIndex >::integrate (Particles::ParticleHandler< dim > & particle_handler, const Tensor< 1, 3 > & body_force, const double time_step, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force, const std::vector< double > & MOI, const parallel::distributed::Triangulation< dim > & triangulation, AdaptiveSparseContacts< dim, PropertiesIndex > & sparse_contacts_object) override virtual
Implements Integrator< dim, PropertiesIndex >.
Definition at line 139 of file velocity_verlet_integrator.cc.
References DEMActionManager::get_action_manager(), AdaptiveSparseContacts< dim, PropertiesIndex >::get_mobility_status(), AdaptiveSparseContacts< dim, PropertiesIndex >::has_advected_particles(), and point_nd_to_3d().
integrate_half_step_location()
template<int dim, typename PropertiesIndex > void VelocityVerletIntegrator< dim, PropertiesIndex >::integrate_half_step_location (Particles::ParticleHandler< dim > & particle_handler, const Tensor< 1, 3 > & body_force, const double time_step, const std::vector< Tensor< 1, 3 > > & torque, const std::vector< Tensor< 1, 3 > > & force, const std::vector< double > & MOI) override virtual
Integrate new particles' location after insertion.
Parameters
particle_handler The particle handler whose particle motion we wish to integrate
body_force A constant volumetric body force applied to all particles
time_step The value of the time step used for the integration
torque Torque acting on particles
force Force acting on particles
MOI A container of moment of inertia of particles
Implements Integrator< dim, PropertiesIndex >.
Definition at line 14 of file velocity_verlet_integrator.cc.
integrate_with_advected_particles()
template<int dim, typename PropertiesIndex > void VelocityVerletIntegrator< dim, PropertiesIndex >::integrate_with_advected_particles (Particles::ParticleHandler< dim > & particle_handler, const Tensor< 1, 3 > & body_force, const double time_step, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force, const std::vector< double > & MOI, const parallel::distributed::Triangulation< dim > & triangulation, AdaptiveSparseContacts< dim, PropertiesIndex > & sparse_contacts_object)
Definition at line 284 of file velocity_verlet_integrator.cc.
References AdaptiveSparseContacts< dim, PropertiesIndex >::get_mobility_status(), AdaptiveSparseContacts< dim, PropertiesIndex >::get_velocities_accelerations(), and point_nd_to_3d().
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/velocity_verlet_integrator.h
/home/runner/work/lethe/lethe/source/dem/velocity_verlet_integrator.cc