Lethe Open-Source Library: VANSOperator< dim, number > Class Template Reference
VANSOperator< dim, number > Class Template Reference
#include <fluid_dynamics_vans_matrix_free_operators.h>
Public Types
using FECellIntegrator = FEEvaluation< dim, -1, 0, dim+1, number >
using FEFaceIntegrator = FEFaceEvaluation< dim, -1, 0, dim+1, number >
using VectorType = LinearAlgebra::distributed::Vector< number >
Public Types inherited from NavierStokesOperatorBase< dim, number >
using FECellIntegrator = FEEvaluation< dim, -1, 0, dim+1, number >
using FEFaceIntegrator = FEFaceEvaluation< dim, -1, 0, dim+1, number >
using VectorType = LinearAlgebra::distributed::Vector< number >
using value_type = number
using size_type = VectorizedArray< number >
using StabilizationType = Parameters::Stabilization::NavierStokesStabilization
Public Member Functions
VANSOperator (const Parameters::CFDDEM &cfd_dem_parameters)
void compute_void_fraction (const DoFHandler< dim > &void_fraction_dof_handler, const LinearAlgebra::distributed::Vector< double > &void_fraction_solution, const LinearAlgebra::distributed::Vector< double > &time_derivative_void_fraction_solution)
void compute_particle_fluid_interaction (const DoFHandler< dim > &fp_force_dof_handler, const LinearAlgebra::distributed::Vector< double > &fp_force_solution, const DoFHandler< dim > &fp_drag_dof_handler, const LinearAlgebra::distributed::Vector< double > &fp_drag_solution, const DoFHandler< dim > &particle_velocity_dof_handler, const LinearAlgebra::distributed::Vector< double > &particle_velocity_solution, const DoFHandler< dim > &momentum_transfer_coefficient_dof_handler, const LinearAlgebra::distributed::Vector< double > &momentum_transfer_coefficient_solution)
Public Member Functions inherited from NavierStokesOperatorBase< dim, number >
NavierStokesOperatorBase ()
NavierStokesOperatorBase (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const AffineConstraints< number > &constraints, const Quadrature< dim > &quadrature, const std::shared_ptr< Function< dim > > forcing_function, const std::shared_ptr< PhysicalPropertiesManager > &physical_properties_manager, const StabilizationType stabilization, const unsigned int mg_level, const std::shared_ptr< SimulationControl > &simulation_control, const BoundaryConditions::NSBoundaryConditions< dim > &boundary_conditions, const bool &enable_hessians_jacobian, const bool &enable_hessians_residual, const bool &enable_mortar)
void reinit (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const AffineConstraints< number > &constraints, const Quadrature< dim > &quadrature, const std::shared_ptr< Function< dim > > forcing_function, const std::shared_ptr< PhysicalPropertiesManager > &physical_properties_manager, const StabilizationType stabilization, const unsigned int mg_level, const std::shared_ptr< SimulationControl > &simulation_control, const BoundaryConditions::NSBoundaryConditions< dim > &boundary_conditions, const bool &enable_hessians_jacobian, const bool &enable_hessians_residual, const bool &enable_mortar)
void compute_element_size ()
void compute_forcing_term ()
void compute_buoyancy_term (const VectorType &temperature_solution, const DoFHandler< dim > &temperature_dof_handler)
types::global_dof_index m () const
number el (unsigned int, unsigned int) const
void clear ()
void initialize_dof_vector (VectorType &vec) const
const std::shared_ptr< const Utilities::MPI::Partitioner > & get_vector_partitioner () const
void vmult (VectorType &dst, const VectorType &src) const
void Tvmult (VectorType &dst, const VectorType &src) const
void vmult_interface_down (VectorType &dst, VectorType const &src) const
void vmult_interface_up (VectorType &dst, VectorType const &src) const
const DynamicSparsityPattern & get_sparsity_pattern () const
const TrilinosWrappers::SparseMatrix & get_system_matrix () const
const MatrixFree< dim, number > & get_system_matrix_free () const
const AlignedVector< VectorizedArray< number > > get_element_size () const
void compute_inverse_diagonal (VectorType &diagonal) const
void evaluate_time_derivative_previous_solutions (const VectorType &time_derivative_previous_solutions)
void evaluate_velocity_ale (const Mapping< dim > &mapping, const double radius, const Point< dim > center_of_rotation, std::shared_ptr< Functions::ParsedFunction< dim > > rotor_angular_velocity)
void update_beta_force (const Tensor< 1, dim > &beta_force)
void evaluate_residual (VectorType &dst, const VectorType &src)
Protected Member Functions
virtual void evaluate_non_linear_term_and_calculate_tau (const VectorType &newton_step) override
void do_cell_integral_local (FECellIntegrator &integrator) const override
void local_evaluate_residual (const MatrixFree< dim, number > &matrix_free, VectorType &dst, const VectorType &src, const std::pair< unsigned int, unsigned int > &range) const override
Protected Member Functions inherited from NavierStokesOperatorBase< dim, number >
void do_cell_integral_range (const MatrixFree< dim, number > &matrix_free, VectorType &dst, const VectorType &src, const std::pair< unsigned int, unsigned int > &range) const
template<bool assemble_residual>
void do_boundary_face_integral_local (FEFaceIntegrator &integrator) const
template<bool assemble_residual>
void do_boundary_face_integral_range (const MatrixFree< dim, number > &matrix_free, VectorType &dst, const VectorType &src, const std::pair< unsigned int, unsigned int > &range) const
void do_internal_face_integral_range (const MatrixFree< dim, number > &matrix_free, VectorType &dst, const VectorType &src, const std::pair< unsigned int, unsigned int > &range) const
TimeSteppingData initialize_time_stepping_data () const
Protected Attributes
Table< 2, VectorizedArray< number > > void_fraction
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > void_fraction_gradient
Table< 2, VectorizedArray< number > > time_derivative_void_fraction
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > particle_fluid_force
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > particle_fluid_drag
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > particle_velocity
Table< 2, VectorizedArray< number > > momentum_transfer_coefficient
Table< 2, VectorizedArray< number > > grad_div_gamma
const Parameters::CFDDEM cfd_dem_parameters
Protected Attributes inherited from NavierStokesOperatorBase< dim, number >
MatrixFree< dim, number > matrix_free
AffineConstraints< number > constraints
DynamicSparsityPattern dsp
TrilinosWrappers::SparseMatrix system_matrix
AlignedVector< VectorizedArray< number > > element_size
unsigned int fe_degree
std::shared_ptr< Function< dim > > forcing_function
Tensor< 1, dim, VectorizedArray< number > > beta_force
StabilizationType stabilization
std::shared_ptr< SimulationControl > simulation_control
std::shared_ptr< PhysicalPropertiesManager > properties_manager
BoundaryConditions::NSBoundaryConditions< dim > boundary_conditions
bool enable_hessians_jacobian
bool enable_hessians_residual
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > forcing_terms
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > buoyancy_term
bool enable_face_terms
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > nonlinear_previous_values
Table< 2, Tensor< 1, dim+1, Tensor< 1, dim, VectorizedArray< number > > > > nonlinear_previous_gradient
Table< 2, Tensor< 1, dim+1, Tensor< 1, dim, VectorizedArray< number > > > > nonlinear_previous_hessian_diagonal
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > time_derivatives_previous_solutions
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > face_nonlinear_previous_values
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > face_target_velocity
Table< 2, VectorizedArray< number > > stabilization_parameter
Table< 2, VectorizedArray< number > > stabilization_parameter_lsic
Table< 2, VectorizedArray< number > > kinematic_viscosity_vector
Table< 2, VectorizedArray< number > > grad_kinematic_viscosity_shear_rate
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > kinematic_viscosity_gradient
Table< 2, Tensor< 1, dim+1, Tensor< 1, dim, VectorizedArray< number > > > > previous_shear_rate
Table< 2, VectorizedArray< number > > previous_shear_rate_magnitude
Table< 1, VectorizedArray< number > > effective_beta_face
bool enable_mortar
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > velocity_for_stabilization
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > velocity_ale
std::vector< unsigned int > constrained_indices
std::vector< std::pair< number, number > > constrained_values
std::vector< unsigned int > edge_constrained_indices
bool has_edge_constrained_indices = false
std::vector< number > edge_constrained_values
std::vector< bool > edge_constrained_cell
Table< 2, bool > bool_dof_mask
ConditionalOStream pcout
Additional Inherited Members
Public Attributes inherited from NavierStokesOperatorBase< dim, number >
std::shared_ptr< MortarManagerCircle< dim > > mortar_manager_mf
std::shared_ptr< CouplingOperator< dim, double > > mortar_coupling_operator_mf
std::shared_ptr< NavierStokesCouplingEvaluation< dim, double > > mortar_coupling_evaluator_mf
TimerOutput timer
Detailed Description
template<int dim, typename number>
class VANSOperator< dim, number >
Implements the matrix-free operator for the VANS equations.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
number Abstract type for number across the class (i.e., double).
Definition at line 20 of file fluid_dynamics_vans_matrix_free_operators.h.
Member Typedef Documentation
FECellIntegrator
template<int dim, typename number > using VANSOperator< dim, number >::FECellIntegrator = FEEvaluation<dim, -1, 0, dim + 1, number>
Definition at line 23 of file fluid_dynamics_vans_matrix_free_operators.h.
FEFaceIntegrator
template<int dim, typename number > using VANSOperator< dim, number >::FEFaceIntegrator = FEFaceEvaluation<dim, -1, 0, dim + 1, number>
Definition at line 24 of file fluid_dynamics_vans_matrix_free_operators.h.
VectorType
template<int dim, typename number > using VANSOperator< dim, number >::VectorType = LinearAlgebra::distributed::Vector<number>
Definition at line 25 of file fluid_dynamics_vans_matrix_free_operators.h.
Constructor & Destructor Documentation
VANSOperator()
template<int dim, typename number > VANSOperator< dim, number >::VANSOperator (const Parameters::CFDDEM & cfd_dem_parameters) inline
Constructor for the VANS operator.
Parameters
[in] cfd_dem_parameters The CFD-DEM parameters used for the simulation. These parameters are notably used to distinguish between model A and model B as well as to establish grad-div stabilization.
Definition at line 35 of file fluid_dynamics_vans_matrix_free_operators.h.
References Parameters::modelA, and Parameters::CFDDEM::vans_model.
Member Function Documentation
compute_particle_fluid_interaction()
template<int dim, typename number > void VANSOperator< dim, number >::compute_particle_fluid_interaction (const DoFHandler< dim > & fp_force_dof_handler, const LinearAlgebra::distributed::Vector< double > & fp_force_solution, const DoFHandler< dim > & fp_drag_dof_handler, const LinearAlgebra::distributed::Vector< double > & fp_drag_solution, const DoFHandler< dim > & particle_velocity_dof_handler, const LinearAlgebra::distributed::Vector< double > & particle_velocity_solution, const DoFHandler< dim > & momentum_transfer_coefficient_dof_handler, const LinearAlgebra::distributed::Vector< double > & momentum_transfer_coefficient_solution)
Compute the terms required to assemble the particle-fluid forces at the gauss points. The function gathers the particle-fluid force (without drag), the particle-fluid drag and the particle velocity. The function assumes that the all of the fields gathered from the projectors are the forces acting on the particles due to the fluid. Consequently, since this aims to gather the forces that apply on the fluid due to the particles, a (-) multiplicator is applied during the gathering stage. With these three elements, the full particle-fluid coupling and its jacobian can be established within the matrix-free operator.
Parameters
[in] fp_force_dof_handler The dof handler associated with the particle-fluid forces.
[in] fp_force_solution The solution of the particle-fluid forces.
[in] fp_drag_dof_handler The dof handler associated with the drag force.
[in] fp_drag_solution The solution of the drag force.
[in] particle_velocity_dof_handler The dof handler associated with the particle velocity.
[in] fp_drag_solution The solution of the particle velocity.
Definition at line 120 of file fluid_dynamics_vans_matrix_free_operators.cc.
References Parameters::fully_explicit.
compute_void_fraction()
template<int dim, typename number > void VANSOperator< dim, number >::compute_void_fraction (const DoFHandler< dim > & void_fraction_dof_handler, const LinearAlgebra::distributed::Vector< double > & void_fraction_solution, const LinearAlgebra::distributed::Vector< double > & time_derivative_void_fraction_solution)
Compute the void fraction at the fluid quadrature point. This essentially calculates the void fraction and the void fraction gradient.
Parameters
[in] void_fraction_dof_handler The dof handler associated with the void fraction
[in] void_fraction_solution The solution of the void fraction
[in] time_derivative_void_fraction_solution The time derivative of the void fraction.
Definition at line 55 of file fluid_dynamics_vans_matrix_free_operators.cc.
References void_fraction.
do_cell_integral_local()
template<int dim, typename number > void VANSOperator< dim, number >::do_cell_integral_local (FECellIntegrator & integrator) const override protected virtual
Perform cell integral on a cell batch without gathering and scattering the values, and according to the Jacobian of the discretized steady/transient VANS equations with stabilization.
Parameters
[in] integrator FEEvaluation object that allows to evaluate functions at quadrature points and perform cell integrations.
Calculates the Jacobian of VANS equations. Here, we note f_pf the forces from the particles to the fluid. The expressions calculated in this cell integral are: (Continuity equation) (q,u) + (q,u) + (VANS equations) + (v, t u) -> Time derivative + (v, (u)u) + (v, (u)u) -> Advection - (v, p) - (v,p) -> Pressure + (v, u) -> Drag force (this is positive because f_pf = - beta(u-v)) + *(v,u) + (v,u) -> Viscous term —> There are currently two terms missing here which would be: + *(v,u^T) + (v,u^T) plus three additional terms in the case of SUPG-PSPG stabilization: + (t u + (u)u + (u)u + p - u +u)q (PSPG Jacobian) + (t u + (u)u + (u)u + p - u +u)uv (SUPG Jacobian P.1) + (t u + (u)u + p - u - f - f_pf)uv (SUPG Jacobian P.2), in the case of additional grad-div stabilization + (v,(u+u)) (grad-div term)
Implements NavierStokesOperatorBase< dim, number >.
Definition at line 306 of file fluid_dynamics_vans_matrix_free_operators.cc.
References time_stepping_is_bdf(), and void_fraction.
evaluate_non_linear_term_and_calculate_tau()
template<int dim, typename number > void VANSOperator< dim, number >::evaluate_non_linear_term_and_calculate_tau (const VectorType & newton_step) override protected virtual
Store relevant values of the vector of the last newton step to use it in the Jacobian and pre-calculate the stabilization parameters tau and gamma.
Parameters
[in] newton_step Vector of the last newton step.
Reimplemented from NavierStokesOperatorBase< dim, number >.
Definition at line 8 of file fluid_dynamics_vans_matrix_free_operators.cc.
References NavierStokesOperatorBase< dim, number >::evaluate_non_linear_term_and_calculate_tau(), and Parameters::Stabilization::pspg_supg.
local_evaluate_residual()
template<int dim, typename number > void VANSOperator< dim, number >::local_evaluate_residual (const MatrixFree< dim, number > & matrix_free, VectorType & dst, const VectorType & src, const std::pair< unsigned int, unsigned int > & range) const override protected virtual
Perform cell integral on a cell batch with gathering and scattering the values, and according to the residual of the discretized steady/transient VANS equations with stabilization.
Parameters
[in] matrix_free Object that contains all data.
[in,out] dst Global vector where the final result is added.
[in] src Input vector with all values in all cells.
[in] range Range of the cell batch.
The expressions calculated in this cell integral are: (q, t) + (q, u) + (q, u) (Continuity equation) +(v,t u) + (v,(u)u) - (v,p) - (v,p) + (v,u) + (v,u) - (v, f_pf) - (v,f) (Weak form of VANS), plus two additional terms in the case of SUPG-PSPG stabilization: + (t u +(u)u + p - u - f_pf - f)q (PSPG term) + (t u +(u)u + p - u - f_pf - f)uv (SUPG term), With additional grad-div stabilization (v,(t+u+u)) (grad-div term)
Implements NavierStokesOperatorBase< dim, number >.
Definition at line 543 of file fluid_dynamics_vans_matrix_free_operators.cc.
References time_stepping_is_bdf(), and void_fraction.
Member Data Documentation
cfd_dem_parameters
template<int dim, typename number > const Parameters::CFDDEM VANSOperator< dim, number >::cfd_dem_parameters protected
Internal copy of the CFD-DEM parameters. This is used for grad-div stabilization, but also to switch between form A and B of the VANS equations.
Definition at line 179 of file fluid_dynamics_vans_matrix_free_operators.h.
grad_div_gamma
template<int dim, typename number > Table<2, VectorizedArray<number> > VANSOperator< dim, number >::grad_div_gamma protected
Table with correct alignment for vectorization to store the values of the grad-div gamma parameter
Definition at line 174 of file fluid_dynamics_vans_matrix_free_operators.h.
momentum_transfer_coefficient
template<int dim, typename number > Table<2, VectorizedArray<number> > VANSOperator< dim, number >::momentum_transfer_coefficient protected
Table with correct alignment for vectorization to store the values of the momentum transfer coefficient.
Definition at line 170 of file fluid_dynamics_vans_matrix_free_operators.h.
particle_fluid_drag
template<int dim, typename number > Table<2, Tensor<1, dim, VectorizedArray<number> > > VANSOperator< dim, number >::particle_fluid_drag protected
Table with correct alignment for vectorization to store the values of the particle-fluid drag. The drag force in this table is volumetric, resulting from the projection used.
Definition at line 162 of file fluid_dynamics_vans_matrix_free_operators.h.
particle_fluid_force
template<int dim, typename number > Table<2, Tensor<1, dim, VectorizedArray<number> > > VANSOperator< dim, number >::particle_fluid_force protected
Table with correct alignment for vectorization to store the values of the particle-fluid forces (without drag). These are the resulting forces applied on the particles due to hydrodynamic interaction, normalized by the volume of the cells.
Definition at line 157 of file fluid_dynamics_vans_matrix_free_operators.h.
particle_velocity
template<int dim, typename number > Table<2, Tensor<1, dim, VectorizedArray<number> > > VANSOperator< dim, number >::particle_velocity protected
Table with correct alignment for vectorization to store the values of the particle velocity.
Definition at line 166 of file fluid_dynamics_vans_matrix_free_operators.h.
time_derivative_void_fraction
template<int dim, typename number > Table<2, VectorizedArray<number> > VANSOperator< dim, number >::time_derivative_void_fraction protected
Table with correct alignment for vectorization to store the values of the time deriative of the void fraction
Definition at line 151 of file fluid_dynamics_vans_matrix_free_operators.h.
void_fraction
template<int dim, typename number > Table<2, VectorizedArray<number> > VANSOperator< dim, number >::void_fraction protected
Table with correct alignment for vectorization to store the values of the void fraction
Definition at line 143 of file fluid_dynamics_vans_matrix_free_operators.h.
void_fraction_gradient
template<int dim, typename number > Table<2, Tensor<1, dim, VectorizedArray<number> > > VANSOperator< dim, number >::void_fraction_gradient protected
Table with correct alignment for vectorization to store the values of the void fraction gradient
Definition at line 147 of file fluid_dynamics_vans_matrix_free_operators.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/fluid_dynamics_vans_matrix_free_operators.h
/home/runner/work/lethe/lethe/source/fem-dem/fluid_dynamics_vans_matrix_free_operators.cc