Lethe Open-Source Library: SurfaceTensionPhaseChange Class Reference
SurfaceTensionPhaseChange Class Reference
#include <surface_tension_model.h>
Public Member Functions
SurfaceTensionPhaseChange (const Parameters::SurfaceTensionParameters &p_surface_tension_parameters)
double value (const std::map< field, double > &fields_value) override
void vector_value (const std::map< field, std::vector< double > > &field_vectors, std::vector< double > &property_vector) override
double jacobian (const std::map< field, double > &field_values, field id) override
void vector_jacobian (const std::map< field, std::vector< double > > &field_vectors, const field id, std::vector< double > &jacobian_vector) override
Public Member Functions inherited from SurfaceTensionLinear
SurfaceTensionLinear (const Parameters::SurfaceTensionParameters &p_surface_tension_parameters)
Public Member Functions inherited from SurfaceTensionModel
bool is_constant_surface_tension_model ()
Public Member Functions inherited from InterfacePropertyModel
InterfacePropertyModel ()
virtual ~InterfacePropertyModel ()
bool depends_on (const field &id)
double numerical_jacobian (const std::map< field, double > &field_values, const field id)
void vector_numerical_jacobian (const std::map< field, std::vector< double > > &field_vectors, const field id, std::vector< double > &jacobian_vector)
Private Attributes
const double T_solidus
const double T_liquidus
Additional Inherited Members
Static Public Member Functions inherited from SurfaceTensionModel
static std::shared_ptr< SurfaceTensionModel > model_cast (const Parameters::MaterialInteractions &material_interaction_parameters)
Protected Attributes inherited from SurfaceTensionLinear
const double surface_tension_coefficient
const double T_0
const double surface_tension_gradient
Protected Attributes inherited from SurfaceTensionModel
bool surface_tension_is_constant = false
Protected Attributes inherited from InterfacePropertyModel
std::map< field, bool > model_depends_on
Detailed Description
Linear surface tension with phase change. The surface tension is given by: alpha_l*(sigma_0 + dsigma/dT * (T-T_0)).
Definition at line 241 of file surface_tension_model.h.
Constructor & Destructor Documentation
SurfaceTensionPhaseChange()
SurfaceTensionPhaseChange::SurfaceTensionPhaseChange (const Parameters::SurfaceTensionParameters & p_surface_tension_parameters) inline
Default constructor.
Parameters
p_surface_tension_parameters The parameters for the surface tension model, including the surface tension coefficient sigma_0 and surface tension gradient dsimga/dT at the reference temperature T_0, and the solidus and liquidus temperatures T_solidus and T_liquidus respectively.
Definition at line 251 of file surface_tension_model.h.
References InterfacePropertyModel::model_depends_on, and temperature.
Member Function Documentation
jacobian()
double SurfaceTensionPhaseChange::jacobian (const std::map< field, double > & field_values, field id) inline override virtual
jacobian Calculates the jacobian (the partial derivative) of the surface tension coefficient with respect to a field.
Parameters
field_values Value of the various fields on which the property may depend.
id Indicator of the field with respect to which the jacobian should be calculated.
Returns
value of the partial derivative of the surface tension coefficient with respect to the field.
Reimplemented from SurfaceTensionLinear.
Definition at line 337 of file surface_tension_model.h.
References calculate_liquid_fraction(), SurfaceTensionLinear::surface_tension_gradient, T_liquidus, T_solidus, and temperature.
value()
double SurfaceTensionPhaseChange::value (const std::map< field, double > & fields_value) inline override virtual
value Calculates the surface tension coefficient.
Parameters
field_vectors Vectors of the fields on which the surface tension depends. In this case, it depends on the temperature.
Returns
value of the physical property calculated with the fields_value.
Reimplemented from SurfaceTensionLinear.
Definition at line 267 of file surface_tension_model.h.
References calculate_liquid_fraction(), SurfaceTensionLinear::surface_tension_coefficient, SurfaceTensionLinear::surface_tension_gradient, SurfaceTensionLinear::T_0, T_liquidus, T_solidus, and temperature.
vector_jacobian()
void SurfaceTensionPhaseChange::vector_jacobian (const std::map< field, std::vector< double > > & field_vectors, const field id, std::vector< double > & jacobian_vector) inline override virtual
vector_jacobian Calculates the derivative of the surface tension coefficient with respect to a field.
Parameters
field_vectors Vector for the values of the fields used to evaluate the property.
id Identifier of the field with respect to which a derivative should be calculated.
jacobian vector of the value of the derivative of the surface tension coefficient with respect to the field id.
Reimplemented from SurfaceTensionLinear.
Definition at line 371 of file surface_tension_model.h.
References calculate_liquid_fraction(), SurfaceTensionLinear::surface_tension_gradient, T_liquidus, T_solidus, and temperature.
vector_value()
void SurfaceTensionPhaseChange::vector_value (const std::map< field, std::vector< double > > & field_vectors, std::vector< double > & property_vector) inline override virtual
vector_value Calculates the vector of surface tension coefficient.
Parameters
field_vectors Vectors of the fields on which the surface tension depends. In this case, it depends on the temperature.
property_vector Vectors of the surface tension coefficient values.
Reimplemented from SurfaceTensionLinear.
Definition at line 300 of file surface_tension_model.h.
References calculate_liquid_fraction(), SurfaceTensionLinear::surface_tension_coefficient, SurfaceTensionLinear::surface_tension_gradient, SurfaceTensionLinear::T_0, T_liquidus, T_solidus, and temperature.
Member Data Documentation
T_liquidus
const double SurfaceTensionPhaseChange::T_liquidus private
Definition at line 401 of file surface_tension_model.h.
T_solidus
const double SurfaceTensionPhaseChange::T_solidus private
Definition at line 400 of file surface_tension_model.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/surface_tension_model.h