Lethe Open-Source Library: CouplingOperator< dim, n_components, Number > Class Template Reference
CouplingOperator< dim, n_components, Number > Class Template Reference
#include <mortar_coupling_manager.h>
Public Types
using FEPointIntegrator = FEPointEvaluation< n_components, dim, dim, Number >
using VectorType = LinearAlgebra::distributed::Vector< Number >
Public Member Functions
CouplingOperator (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const AffineConstraints< Number > &constraints, const Quadrature< dim > &quadrature, const unsigned int n_subdivisions, const double radius, const double rotate_pi, const unsigned int bid_0, const unsigned int bid_1, const double sip_factor=1.0)
const AffineConstraints< Number > & get_affine_constraints () const
void vmult_add (VectorType &dst, const VectorType &src) const
void add_diagonal_entries (VectorType &diagonal) const
void add_sparsity_pattern_entries (TrilinosWrappers::SparsityPattern &dsp) const
void add_system_matrix_entries (TrilinosWrappers::SparseMatrix &system_matrix) const
Private Member Functions
Number compute_penalty_factor (const unsigned int degree, const Number factor) const
Number compute_penalty_parameter (const typename Triangulation< dim >::cell_iterator &cell) const
double get_rad (const typename Triangulation< dim >::cell_iterator &cell, const typename Triangulation< dim >::face_iterator &face) const
Private Attributes
const Mapping< dim > & mapping
const DoFHandler< dim > & dof_handler
const AffineConstraints< Number > & constraints
const Quadrature< dim > & quadrature
std::vector< std::tuple< std::vector< double >, typename Triangulation< dim >::active_cell_iterator, std::vector< Point< dim > >, typename Triangulation< dim >::active_cell_iterator, std::vector< Point< dim > >, std::vector< Tensor< 1, dim, Number > >, Number > > all_intersections
Number penalty_factor
std::shared_ptr< MortarManager< dim > > mortar_manager_q
std::shared_ptr< MortarManager< dim > > mortar_manager_cell
unsigned int bid_0
unsigned int bid_1
Utilities::MPI::NoncontiguousPartitioner partitioner
Utilities::MPI::NoncontiguousPartitioner partitioner_cell
std::vector< types::global_dof_index > dof_indices
std::vector< types::global_dof_index > dof_indices_ghost
std::vector< Number > all_penalty_parameter
std::vector< Number > all_weights
std::vector< Point< dim, Number > > all_points_ref
std::vector< Tensor< 1, dim, Number > > all_normals
AffineConstraints< Number > constraints_extended
Detailed Description
template<int dim, int n_components, typename Number>
class CouplingOperator< dim, n_components, Number >
Definition at line 451 of file mortar_coupling_manager.h.
Member Typedef Documentation
FEPointIntegrator
template<int dim, int n_components, typename Number > using CouplingOperator< dim, n_components, Number >::FEPointIntegrator = FEPointEvaluation<n_components, dim, dim, Number>
Definition at line 454 of file mortar_coupling_manager.h.
VectorType
template<int dim, int n_components, typename Number > using CouplingOperator< dim, n_components, Number >::VectorType = LinearAlgebra::distributed::Vector<Number>
Definition at line 456 of file mortar_coupling_manager.h.
Constructor & Destructor Documentation
CouplingOperator()
template<int dim, int n_components, typename Number > CouplingOperator< dim, n_components, Number >::CouplingOperator (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const AffineConstraints< Number > & constraints, const Quadrature< dim > & quadrature, const unsigned int n_subdivisions, const double radius, const double rotate_pi, const unsigned int bid_0, const unsigned int bid_1, const double sip_factor = 1.0)
Definition at line 534 of file mortar_coupling_manager.h.
References CouplingOperator< dim, n_components, Number >::all_normals, CouplingOperator< dim, n_components, Number >::all_penalty_parameter, CouplingOperator< dim, n_components, Number >::all_points_ref, CouplingOperator< dim, n_components, Number >::all_weights, CouplingOperator< dim, n_components, Number >::bid_0, CouplingOperator< dim, n_components, Number >::bid_1, CouplingOperator< dim, n_components, Number >::compute_penalty_factor(), CouplingOperator< dim, n_components, Number >::compute_penalty_parameter(), CouplingOperator< dim, n_components, Number >::constraints, CouplingOperator< dim, n_components, Number >::constraints_extended, CouplingOperator< dim, n_components, Number >::dof_handler, CouplingOperator< dim, n_components, Number >::dof_indices, CouplingOperator< dim, n_components, Number >::dof_indices_ghost, CouplingOperator< dim, n_components, Number >::get_rad(), CouplingOperator< dim, n_components, Number >::mapping, CouplingOperator< dim, n_components, Number >::mortar_manager_cell, CouplingOperator< dim, n_components, Number >::mortar_manager_q, CouplingOperator< dim, n_components, Number >::partitioner, CouplingOperator< dim, n_components, Number >::partitioner_cell, CouplingOperator< dim, n_components, Number >::penalty_factor, and CouplingOperator< dim, n_components, Number >::quadrature.
Member Function Documentation
add_diagonal_entries()
template<int dim, int n_components, typename Number > void CouplingOperator< dim, n_components, Number >::add_diagonal_entries (VectorType & diagonal) const
Definition at line 930 of file mortar_coupling_manager.h.
References contract(), and outer().
add_sparsity_pattern_entries()
template<int dim, int n_components, typename Number > void CouplingOperator< dim, n_components, Number >::add_sparsity_pattern_entries (TrilinosWrappers::SparsityPattern & dsp) const
Definition at line 1032 of file mortar_coupling_manager.h.
add_system_matrix_entries()
template<int dim, int n_components, typename Number > void CouplingOperator< dim, n_components, Number >::add_system_matrix_entries (TrilinosWrappers::SparseMatrix & system_matrix) const
Definition at line 1055 of file mortar_coupling_manager.h.
References contract(), and outer().
compute_penalty_factor()
template<int dim, int n_components, typename Number > Number CouplingOperator< dim, n_components, Number >::compute_penalty_factor (const unsigned int degree, const Number factor) const private
Definition at line 752 of file mortar_coupling_manager.h.
compute_penalty_parameter()
template<int dim, int n_components, typename Number > Number CouplingOperator< dim, n_components, Number >::compute_penalty_parameter (const typename Triangulation< dim >::cell_iterator & cell) const private
Definition at line 761 of file mortar_coupling_manager.h.
get_affine_constraints()
template<int dim, int n_components, typename Number > const AffineConstraints< Number > & CouplingOperator< dim, n_components, Number >::get_affine_constraints () const
Definition at line 745 of file mortar_coupling_manager.h.
get_rad()
template<int dim, int n_components, typename Number > double CouplingOperator< dim, n_components, Number >::get_rad (const typename Triangulation< dim >::cell_iterator & cell, const typename Triangulation< dim >::face_iterator & face) const private
Definition at line 800 of file mortar_coupling_manager.h.
References point_to_rad().
vmult_add()
template<int dim, int n_components, typename Number > void CouplingOperator< dim, n_components, Number >::vmult_add (VectorType & dst, const VectorType & src) const
Definition at line 814 of file mortar_coupling_manager.h.
References contract(), and outer().
Member Data Documentation
all_intersections
template<int dim, int n_components, typename Number > std::vector<std::tuple<std::vector<double>, typename Triangulation<dim>::active_cell_iterator, std::vector<Point<dim> >, typename Triangulation<dim>::active_cell_iterator, std::vector<Point<dim> >, std::vector<Tensor<1, dim, Number> >, Number> > CouplingOperator< dim, n_components, Number >::all_intersections private
Definition at line 509 of file mortar_coupling_manager.h.
all_normals
template<int dim, int n_components, typename Number > std::vector<Tensor<1, dim, Number> > CouplingOperator< dim, n_components, Number >::all_normals private
Definition at line 528 of file mortar_coupling_manager.h.
all_penalty_parameter
template<int dim, int n_components, typename Number > std::vector<Number> CouplingOperator< dim, n_components, Number >::all_penalty_parameter private
Definition at line 525 of file mortar_coupling_manager.h.
all_points_ref
template<int dim, int n_components, typename Number > std::vector<Point<dim, Number> > CouplingOperator< dim, n_components, Number >::all_points_ref private
Definition at line 527 of file mortar_coupling_manager.h.
all_weights
template<int dim, int n_components, typename Number > std::vector<Number> CouplingOperator< dim, n_components, Number >::all_weights private
Definition at line 526 of file mortar_coupling_manager.h.
bid_0
template<int dim, int n_components, typename Number > unsigned int CouplingOperator< dim, n_components, Number >::bid_0 private
Definition at line 516 of file mortar_coupling_manager.h.
bid_1
template<int dim, int n_components, typename Number > unsigned int CouplingOperator< dim, n_components, Number >::bid_1 private
Definition at line 517 of file mortar_coupling_manager.h.
constraints
template<int dim, int n_components, typename Number > const AffineConstraints<Number>& CouplingOperator< dim, n_components, Number >::constraints private
Definition at line 499 of file mortar_coupling_manager.h.
constraints_extended
template<int dim, int n_components, typename Number > AffineConstraints<Number> CouplingOperator< dim, n_components, Number >::constraints_extended private
Definition at line 530 of file mortar_coupling_manager.h.
dof_handler
template<int dim, int n_components, typename Number > const DoFHandler<dim>& CouplingOperator< dim, n_components, Number >::dof_handler private
Definition at line 498 of file mortar_coupling_manager.h.
dof_indices
template<int dim, int n_components, typename Number > std::vector<types::global_dof_index> CouplingOperator< dim, n_components, Number >::dof_indices private
Definition at line 522 of file mortar_coupling_manager.h.
dof_indices_ghost
template<int dim, int n_components, typename Number > std::vector<types::global_dof_index> CouplingOperator< dim, n_components, Number >::dof_indices_ghost private
Definition at line 523 of file mortar_coupling_manager.h.
mapping
template<int dim, int n_components, typename Number > const Mapping<dim>& CouplingOperator< dim, n_components, Number >::mapping private
Definition at line 497 of file mortar_coupling_manager.h.
mortar_manager_cell
template<int dim, int n_components, typename Number > std::shared_ptr<MortarManager<dim> > CouplingOperator< dim, n_components, Number >::mortar_manager_cell private
Definition at line 514 of file mortar_coupling_manager.h.
mortar_manager_q
template<int dim, int n_components, typename Number > std::shared_ptr<MortarManager<dim> > CouplingOperator< dim, n_components, Number >::mortar_manager_q private
Definition at line 513 of file mortar_coupling_manager.h.
partitioner
template<int dim, int n_components, typename Number > Utilities::MPI::NoncontiguousPartitioner CouplingOperator< dim, n_components, Number >::partitioner private
Definition at line 519 of file mortar_coupling_manager.h.
partitioner_cell
template<int dim, int n_components, typename Number > Utilities::MPI::NoncontiguousPartitioner CouplingOperator< dim, n_components, Number >::partitioner_cell private
Definition at line 520 of file mortar_coupling_manager.h.
penalty_factor
template<int dim, int n_components, typename Number > Number CouplingOperator< dim, n_components, Number >::penalty_factor private
Definition at line 511 of file mortar_coupling_manager.h.
quadrature
template<int dim, int n_components, typename Number > const Quadrature<dim>& CouplingOperator< dim, n_components, Number >::quadrature private
Definition at line 500 of file mortar_coupling_manager.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/mortar_coupling_manager.h