Lethe Open-Source Library: Shape< dim > Class Template Reference
Shape< dim > Class Template Reference abstract
#include <shape.h>
Public Types
enum ShapeType : int {
sphere , hyper_rectangle , ellipsoid , torus ,
cone , cylinder , cylindrical_tube , cylindrical_helix ,
cut_hollow_sphere , death_star , composite_shape , rbf_shape ,
opencascade_shape
}
Public Member Functions
Shape (double radius, const Point< dim > &position, const Tensor< 1, 3 > &orientation)
virtual double value (const Point< dim > &evaluation_point, const unsigned int component=0) const override=0
virtual double value_with_cell_guess (const Point< dim > &evaluation_point, const typename DoFHandler< dim >::active_cell_iterator cell, const unsigned int component=0)
double smooth_max (double a, double b, double smooth_factor=10)
virtual std::tuple< double, Tensor< 1, dim >, Point< dim > > distance_to_shape_with_cell_guess (Shape< dim > &shape, const typename DoFHandler< dim >::active_cell_iterator &cell, std::vector< Point< dim > > &candidate_points, double precision=1e-6, bool exact_distance_outside_of_contact=false)
virtual std::tuple< double, Tensor< 1, dim >, Point< dim > > distance_to_shape (Shape< dim > &shape, std::vector< Point< dim > > &candidate_points, double precision=1e-6, bool exact_distance_outside_of_contact=false)
bool bounding_box_contact (Shape< dim > &shape)
virtual Tensor< 1, dim > gradient_with_cell_guess (const Point< dim > &evaluation_point, const typename DoFHandler< dim >::active_cell_iterator cell, const unsigned int component=0)
virtual std::shared_ptr< Shape< dim > > static_copy () const =0
virtual void closest_surface_point (const Point< dim > &p, Point< dim > &closest_point, const typename DoFHandler< dim >::active_cell_iterator &cell_guess)
virtual void closest_surface_point (const Point< dim > &p, Point< dim > &closest_point) const
virtual double displaced_volume ()
virtual double local_curvature_radius (Point< dim > p)
virtual double local_curvature_radius_with_cell_guess (const Point< dim > p, const typename DoFHandler< dim >::active_cell_iterator cell)
virtual void set_position (const Point< dim > &new_position)
virtual void set_orientation (const Tensor< 1, 3 > &new_orientation)
virtual Point< dim > get_position ()
virtual Tensor< 1, 3 > get_orientation ()
virtual Tensor< 2, 3 > get_rotation_matrix ()
virtual Tensor< 1, dim > get_bounding_box_half_length ()
virtual Point< dim > get_bounding_box_center ()
virtual std::shared_ptr< Manifold< dim - 1, dim > > get_shape_manifold ()
virtual void clear_cache ()
Point< dim > align_and_center (const Point< dim > &evaluation_point) const
Point< dim > reverse_align_and_center (const Point< dim > &evaluation_point) const
std::string point_to_string (const Point< dim > &evaluation_point) const
void set_part_of_a_composite (const bool part_of_a_composite)
virtual void set_layer_thickening (const double layer_thickening)
Tensor< 1, 3 > rotation_matrix_to_xyz_angles (Tensor< 2, 3 > &rotation_matrix_representation) const
Public Attributes
enum Shape::ShapeType type
double effective_radius
std::string additional_info_on_shape
Tensor< 1, dim > bounding_box_half_length
Point< dim > bounding_box_center
Protected Attributes
Point< dim > position
Tensor< 1, 3 > orientation
std::unordered_map< std::string, double > value_cache
std::unordered_map< std::string, Tensor< 1, dim > > gradient_cache
std::unordered_map< std::string, Point< dim > > closest_point_cache
bool part_of_a_composite
Tensor< 2, 3 > rotation_matrix
double layer_thickening
Detailed Description
template<int dim>
class Shape< dim >
A base class used to represent geometrical entities. Its main uses are to return signed distance and its gradient. It inherits AutoDerivativeFunction so that it can evaluate gradients even when they are not implemented analytically.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 53 of file shape.h.
Member Enumeration Documentation
ShapeType
template<int dim> enum Shape::ShapeType : int
enum class that associate an integer index tp each type of shape
Enumerator
sphere
hyper_rectangle
ellipsoid
torus
cone
cylinder
cylindrical_tube
cylindrical_helix
cut_hollow_sphere
death_star
composite_shape
rbf_shape
opencascade_shape
Definition at line 59 of file shape.h.
Constructor & Destructor Documentation
Shape()
template<int dim> Shape< dim >::Shape (double radius, const Point< dim > & position, const Tensor< 1, 3 > & orientation) inline
A general constructor for the Shapes.
Parameters
radius The effective radius to be set for the shape. It's necessary for some calculations since not all shapes are spheres.
position The position to set the shape at
orientation The orientation to set the shape at
Definition at line 83 of file shape.h.
Member Function Documentation
align_and_center()
template<int dim> Point< dim > Shape< dim >::align_and_center (const Point< dim > & evaluation_point) const
Most value functions assume that the particle's position is at the origin and that the shape is aligned with one of the main axes. This function returns a point that is rotated and translated, in accordance with the current shape position and orientation, so that subsequent calculations for the value function are made more easily; it abstracts a step that is required in the value function for most shapes.
Returns the centered and aligned point used on the level set evaluation.
Parameters
evaluation_point The point that will be recentered and realigned
Returns
The aligned and centered point
Definition at line 43 of file shape.cc.
bounding_box_contact()
template<int dim> bool Shape< dim >::bounding_box_contact (Shape< dim > & shape) inline
Check if the bounding box of this shape and another one are overlapping. This function uses the Separating Axis Theorem (SAT) to perform the bounding box check.
Parameters
shape The shape with which the distance is evaluated
Returns
This function returns false if the shapes are not overlapping.
Definition at line 740 of file shape.h.
References Shape< dim >::bounding_box_center, Shape< dim >::bounding_box_half_length, Shape< dim >::layer_thickening, point_nd_to_2d(), point_nd_to_3d(), Shape< dim >::position, Shape< dim >::rotation_matrix, and Shape< dim >::value().
clear_cache()
template<int dim> void Shape< dim >::clear_cache () virtual
Clear the cache of the shape.
Reimplemented in CompositeShape< dim >.
Definition at line 30 of file shape.cc.
closest_surface_point() [1/2]
template<int dim> void Shape< dim >::closest_surface_point (const Point< dim > & p, Point< dim > & closest_point) const virtual
Reimplemented in Superquadric< dim >.
Definition at line 245 of file shape.cc.
closest_surface_point() [2/2]
template<int dim> void Shape< dim >::closest_surface_point (const Point< dim > & p, Point< dim > & closest_point, const typename DoFHandler< dim >::active_cell_iterator & cell_guess) virtual
Sets the closest_point parameter to be the point on the surface of the shape which has the minimal distance from the given point p.
Parameters
p The point at which the evaluation is performed
closest_point The reference to the closest point. This point will be modified by the function.
cell_guess A guess of the cell containing the evaluation point, which is useful to reduce computation time
Reimplemented in Superquadric< dim >.
Definition at line 225 of file shape.cc.
displaced_volume()
template<int dim> double Shape< dim >::displaced_volume () virtual
Return the volume displaced by the solid.
Reimplemented in Sphere< dim >, Plane< dim >, HyperRectangle< dim >, Ellipsoid< dim >, Torus< dim >, Cone< dim >, CutHollowSphere< dim >, DeathStar< dim >, OpenCascadeShape< dim >, RBFShape< dim >, Cylinder< dim >, CylindricalTube< dim >, and CylindricalHelix< dim >.
Definition at line 22 of file shape.cc.
distance_to_shape()
template<int dim> virtual std::tuple< double, Tensor< 1, dim >, Point< dim > > Shape< dim >::distance_to_shape (Shape< dim > & shape, std::vector< Point< dim > > & candidate_points, double precision = 1e-6, bool exact_distance_outside_of_contact = false) inline virtual
Return the distance, the center point, and the normal between the current shape and the shape given in the argument. The center point is the point where both shapes are at the same distance from each other. The normal is defined using the closest surface point on the two shapes. By default, the function does not calculate the distance between the two shapes if their bounding boxes are not in contact. This behavior can be modified using the appropriate parameter.
Parameters
shape The shape with which the distance is evaluated
cell The cell that is likely to contain the evaluation point
candidate_points This is the initial guess points used in the calculation.
precision This is the precision of the distance between the two shapes.
exact_distance_outside_of_contact This is a boolean to force the exact distance evaluation if the shapes are not in contact.
Reimplemented in Sphere< dim >.
Definition at line 448 of file shape.h.
References Shape< dim >::bounding_box_center, Shape< dim >::bounding_box_contact(), Shape< dim >::bounding_box_half_length, Shape< dim >::closest_surface_point(), Shape< dim >::effective_radius, point_nd_to_3d(), Shape< dim >::position, Shape< dim >::rotation_matrix, Shape< dim >::smooth_max(), tensor_nd_to_2d(), and Shape< dim >::value().
distance_to_shape_with_cell_guess()
template<int dim> virtual std::tuple< double, Tensor< 1, dim >, Point< dim > > Shape< dim >::distance_to_shape_with_cell_guess (Shape< dim > & shape, const typename DoFHandler< dim >::active_cell_iterator & cell, std::vector< Point< dim > > & candidate_points, double precision = 1e-6, bool exact_distance_outside_of_contact = false) inline virtual
Return the distance, the center point, and the unit normal vector between the current shape and the shape given in the argument. The center point is the point where both shapes are at the same distance from each other. The unit normal vector is defined using the closest surface point of the two shapes. By default, the function does not calculate the distance between the two shapes if their bounding boxes are not in contact. This behavior can be modified by setting exact_distance_outside_of_contact to true.
Parameters
shape The shape with which the distance is evaluated
cell The cell that is likely to contain the evaluation point
candidate_points This is the initial guess points used in the calculation.
precision This is the precision of the distance between the two shapes.
exact_distance_outside_of_contact This is a boolean to force the exact distance evaluation if the shapes are not in contact.
Reimplemented in Sphere< dim >.
Definition at line 143 of file shape.h.
References Shape< dim >::bounding_box_center, Shape< dim >::bounding_box_contact(), Shape< dim >::bounding_box_half_length, Shape< dim >::closest_surface_point(), Shape< dim >::effective_radius, Shape< dim >::gradient_with_cell_guess(), point_nd_to_3d(), Shape< dim >::position, Shape< dim >::rotation_matrix, Shape< dim >::smooth_max(), tensor_nd_to_2d(), and Shape< dim >::value_with_cell_guess().
get_bounding_box_center()
template<int dim> virtual Point< dim > Shape< dim >::get_bounding_box_center () inline virtual
Returns the bounding box position.
Definition at line 1227 of file shape.h.
References Shape< dim >::bounding_box_center.
get_bounding_box_half_length()
template<int dim> virtual Tensor< 1, dim > Shape< dim >::get_bounding_box_half_length () inline virtual
Returns the bounding box half length.
Definition at line 1216 of file shape.h.
References Shape< dim >::bounding_box_half_length.
get_orientation()
template<int dim> virtual Tensor< 1, 3 > Shape< dim >::get_orientation () inline virtual
Returns the orientation of the shape.
Definition at line 1194 of file shape.h.
References Shape< dim >::orientation.
get_position()
template<int dim> virtual Point< dim > Shape< dim >::get_position () inline virtual
Returns the position of the shape.
Definition at line 1183 of file shape.h.
References Shape< dim >::position.
get_rotation_matrix()
template<int dim> virtual Tensor< 2, 3 > Shape< dim >::get_rotation_matrix () inline virtual
Returns the orientation of the shape.
Definition at line 1205 of file shape.h.
References Shape< dim >::rotation_matrix.
get_shape_manifold()
template<int dim> std::shared_ptr< Manifold< dim - 1, dim > > Shape< dim >::get_shape_manifold () virtual
Returns the default manifold of the shape. If not redefined, it is a flat manifold.
Reimplemented in Sphere< dim >.
Definition at line 201 of file shape.cc.
gradient_with_cell_guess()
template<int dim> Tensor< 1, dim > Shape< dim >::gradient_with_cell_guess (const Point< dim > & evaluation_point, const typename DoFHandler< dim >::active_cell_iterator cell, const unsigned int component = 0) virtual
Return the analytical gradient of the distance.
Parameters
evaluation_point The point at which the function will be evaluated
cell The cell that is likely to contain the evaluation point
component This parameter is not used, but it is necessary because Shapes inherit from the Function class of deal.II.
Reimplemented in Superquadric< dim >, CompositeShape< dim >, OpenCascadeShape< dim >, and RBFShape< dim >.
Definition at line 273 of file shape.cc.
local_curvature_radius()
template<int dim> virtual double Shape< dim >::local_curvature_radius (Point< dim > p) inline virtual
Return the curvature of the level set at a given point.
Reimplemented in Sphere< dim >.
Definition at line 1072 of file shape.h.
References Shape< dim >::effective_radius.
local_curvature_radius_with_cell_guess()
template<int dim> virtual double Shape< dim >::local_curvature_radius_with_cell_guess (const Point< dim > p, const typename DoFHandler< dim >::active_cell_iterator cell) inline virtual
Return the curvature of the level at a given point using the cell guess functions.
Parameters
cell The cell that is likely to contain the evaluation point
p The point where the curvature is evaluated.
Reimplemented in Sphere< dim >.
Definition at line 1100 of file shape.h.
References Shape< dim >::effective_radius, and Shape< dim >::gradient_with_cell_guess().
point_to_string()
template<int dim> std::string Shape< dim >::point_to_string (const Point< dim > & evaluation_point) const
This function returns a point in a string of text. This is used in the cache of the shape.
Parameters
evaluation_point is the point that is transformed to its text form.
Definition at line 208 of file shape.cc.
reverse_align_and_center()
template<int dim> Point< dim > Shape< dim >::reverse_align_and_center (const Point< dim > & evaluation_point) const
This function applies the inverse operation of align_and_center.
Returns the centered and aligned point used on the level set evaluation in the global reference frame.
Parameters
evaluation_point The point that will be centered and aligned in the global reference frame.
Returns
The aligned and centered point
Definition at line 122 of file shape.cc.
rotation_matrix_to_xyz_angles()
template<int dim> Tensor< 1, 3 > Shape< dim >::rotation_matrix_to_xyz_angles (Tensor< 2, 3 > & rotation_matrix_representation) const inline
Function that return the XYZ rotation angles from a rotation matrix.
Parameters
rotation_matrix_representation The rotation matrix.
Definition at line 1323 of file shape.h.
set_layer_thickening()
template<int dim> virtual void Shape< dim >::set_layer_thickening (const double layer_thickening) inline virtual
Sets the layer thickening value (positive or negative) of the particle's shape.
Parameters
layer_thickening Thickness to be artificially added to the particle. A negative value will decrease the particle's thickness by subtracting a layer of specified width.
Reimplemented in CompositeShape< dim >.
Definition at line 1311 of file shape.h.
References Shape< dim >::layer_thickening.
set_orientation()
template<int dim> virtual void Shape< dim >::set_orientation (const Tensor< 1, 3 > & new_orientation) inline virtual
Sets a new orientation for the shape.
Parameters
The new orientation the shape will be set at
Definition at line 1148 of file shape.h.
References Shape< dim >::clear_cache(), Shape< dim >::orientation, and Shape< dim >::rotation_matrix.
set_part_of_a_composite()
template<int dim> void Shape< dim >::set_part_of_a_composite (const bool part_of_a_composite) inline
Defines if this shape is part of a composite. If true, cache management is deactivated and delegated to the upper level shape, to avoid cache duplication.
Parameters
part_of_a_composite is true if this shape is a constituent of a composite shape
Definition at line 1296 of file shape.h.
References Shape< dim >::part_of_a_composite.
set_position()
template<int dim> virtual void Shape< dim >::set_position (const Point< dim > & new_position) inline virtual
Sets a new position for the shape.
Parameters
The new position the shape will be placed at
Reimplemented in Sphere< dim >, and OpenCascadeShape< dim >.
Definition at line 1135 of file shape.h.
References Shape< dim >::clear_cache(), and Shape< dim >::position.
smooth_max()
template<int dim> double Shape< dim >::smooth_max (double a, double b, double smooth_factor = 10) inline
Return the smoothed maximum of two variables used for shape contact calculation.
Parameters
a first variable
b second variable
Definition at line 128 of file shape.h.
static_copy()
template<int dim> virtual std::shared_ptr< Shape< dim > > Shape< dim >::static_copy () const pure virtual
Return a pointer to a copy of the Shape.
Implemented in Sphere< dim >, Plane< dim >, Superquadric< dim >, HyperRectangle< dim >, Ellipsoid< dim >, Torus< dim >, Cone< dim >, CutHollowSphere< dim >, DeathStar< dim >, CompositeShape< dim >, OpenCascadeShape< dim >, RBFShape< dim >, Cylinder< dim >, CylindricalTube< dim >, and CylindricalHelix< dim >.
value()
template<int dim> virtual double Shape< dim >::value (const Point< dim > & evaluation_point, const unsigned int component = 0) const override pure virtual
Return the evaluation of the signed distance function of this solid at the given point evaluation point Most level set functions implemented come from Inigo Quilez: iquilezles.org/articles/distfunctions.
Parameters
evaluation_point The point at which the function will be evaluated
component This parameter is not used, but it is necessary because Shapes inherit from the Function class of deal.II.
Implemented in Sphere< dim >, Plane< dim >, Superquadric< dim >, HyperRectangle< dim >, Ellipsoid< dim >, Torus< dim >, Cone< dim >, CutHollowSphere< dim >, DeathStar< dim >, CompositeShape< dim >, OpenCascadeShape< dim >, RBFShape< dim >, Cylinder< dim >, CylindricalTube< dim >, and CylindricalHelix< dim >.
value_with_cell_guess()
template<int dim> double Shape< dim >::value_with_cell_guess (const Point< dim > & evaluation_point, const typename DoFHandler< dim >::active_cell_iterator cell, const unsigned int component = 0) virtual
Return the evaluation of the signed distance function of this solid at the given point evaluation point with a guess for the cell containing the evaluation point.
Parameters
evaluation_point The point at which the function will be evaluated
cell The cell that is likely to contain the evaluation point
component This parameter is not used, but it is necessary because Shapes inherit from the Function class of deal.II.
Reimplemented in OpenCascadeShape< dim >, Superquadric< dim >, CompositeShape< dim >, and RBFShape< dim >.
Definition at line 263 of file shape.cc.
Member Data Documentation
additional_info_on_shape
template<int dim> std::string Shape< dim >::additional_info_on_shape
Definition at line 1341 of file shape.h.
bounding_box_center
template<int dim> Point<dim> Shape< dim >::bounding_box_center
Definition at line 1346 of file shape.h.
bounding_box_half_length
template<int dim> Tensor<1, dim> Shape< dim >::bounding_box_half_length
Definition at line 1344 of file shape.h.
closest_point_cache
template<int dim> std::unordered_map<std::string, Point<dim> > Shape< dim >::closest_point_cache protected
Definition at line 1360 of file shape.h.
effective_radius
template<int dim> double Shape< dim >::effective_radius
Definition at line 1336 of file shape.h.
gradient_cache
template<int dim> std::unordered_map<std::string, Tensor<1, dim> > Shape< dim >::gradient_cache protected
Definition at line 1359 of file shape.h.
layer_thickening
template<int dim> double Shape< dim >::layer_thickening protected
Definition at line 1367 of file shape.h.
orientation
template<int dim> Tensor<1, 3> Shape< dim >::orientation protected
Definition at line 1354 of file shape.h.
part_of_a_composite
template<int dim> bool Shape< dim >::part_of_a_composite protected
Definition at line 1361 of file shape.h.
position
template<int dim> Point<dim> Shape< dim >::position protected
Definition at line 1351 of file shape.h.
rotation_matrix
template<int dim> Tensor<2, 3> Shape< dim >::rotation_matrix protected
Definition at line 1365 of file shape.h.
type
template<int dim> enum Shape::ShapeType Shape< dim >::type
value_cache
template<int dim> std::unordered_map<std::string, double> Shape< dim >::value_cache protected
Definition at line 1358 of file shape.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/shape.h
/home/runner/work/lethe/lethe/source/core/shape.cc