Lethe Open-Source Library: VOFAlgebraicInterfaceReinitialization< dim > Class Template Reference
VOFAlgebraicInterfaceReinitialization< dim > Class Template Reference
#include <vof_algebraic_interface_reinitialization.h>
Public Member Functions
VOFAlgebraicInterfaceReinitialization (const SimulationParameters< dim > &p_simulation_parameters, const ConditionalOStream &p_pcout, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > &p_triangulation, const std::shared_ptr< SimulationControl > &p_simulation_control, MultiphysicsInterface< dim > *p_multiphysics_interface, VOFSubequationsInterface< dim > *p_subequations_interface)
~VOFAlgebraicInterfaceReinitialization ()=default
void setup_dofs () override
void solve () override
GlobalVectorType & get_evaluation_point () override
GlobalVectorType & get_local_evaluation_point () override
GlobalVectorType & get_newton_update () override
GlobalVectorType & get_present_solution () override
GlobalVectorType & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
void output_newton_update_norms (const unsigned int display_precision) override
Public Member Functions inherited from PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >
PhysicsNonlinearSubequationsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters, const ConditionalOStream &pcout)
void setup_preconditioner () override
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void write_output_results (const unsigned int step)
double compute_diffusivity (const double min_cell_size) const
double compute_time_step ()
void define_zero_constraints ()
void define_non_zero_constraints ()
void set_initial_conditions ()
void assemble_system_matrix () override
void assemble_system_rhs () override
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
bool continue_iterating (const double time_step_inv, const unsigned int step_number)
Private Attributes
const VOFSubequationsID subequation_id
VOFSubequationsInterface< dim > * subequations_interface
MultiphysicsInterface< dim > * multiphysics_interface
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< SimulationControl > simulation_control
PVDHandler pvdhandler
double current_time_step
std::vector< double > time_step_vector = {0.0}
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FiniteElement< dim > > fe
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType previous_local_evaluation_point
GlobalVectorType newton_update
GlobalVectorType present_solution
GlobalVectorType previous_solution
GlobalVectorType system_rhs
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
TrilinosWrappers::SparseMatrix system_matrix
const Parameters::Verbosity subequation_verbosity
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Protected Attributes inherited from PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >
const ConditionalOStream pcout
Detailed Description
template<int dim>
class VOFAlgebraicInterfaceReinitialization< dim >
VOF algebraic reinitialization solver.
Template Parameters
dim Number of dimensions of the problem.
Definition at line 34 of file vof_algebraic_interface_reinitialization.h.
Constructor & Destructor Documentation
VOFAlgebraicInterfaceReinitialization()
template<int dim> VOFAlgebraicInterfaceReinitialization< dim >::VOFAlgebraicInterfaceReinitialization (const SimulationParameters< dim > & p_simulation_parameters, const ConditionalOStream & p_pcout, std::shared_ptr< parallel::DistributedTriangulationBase< dim > > & p_triangulation, const std::shared_ptr< SimulationControl > & p_simulation_control, MultiphysicsInterface< dim > * p_multiphysics_interface, VOFSubequationsInterface< dim > * p_subequations_interface) inline
Constructor of the VOF algebraic interface reinitialization.
Parameters
[in] p_simulation_parameters Simulation parameters.
[in] p_pcout Parallel cout used to print the information.
[in] p_triangulation Distributed mesh information.
[in] p_simulation_control SimulationControl object.
[in] p_multiphysics_interface Multiphysics interface object used to get information from physics.
[in,out] p_subequations_interface Subequations interface object used to get information from other subequations and store information from the current one.
Definition at line 56 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::cell_quadrature, VOFAlgebraicInterfaceReinitialization< dim >::fe, VOFAlgebraicInterfaceReinitialization< dim >::mapping, and VOFAlgebraicInterfaceReinitialization< dim >::simulation_parameters.
~VOFAlgebraicInterfaceReinitialization()
template<int dim> VOFAlgebraicInterfaceReinitialization< dim >::~VOFAlgebraicInterfaceReinitialization () default
Default destructor.
Member Function Documentation
assemble_system_matrix()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::assemble_system_matrix () override private virtual
Assemble the matrix.
Implements PhysicsSolver< VectorType >.
Definition at line 199 of file vof_algebraic_interface_reinitialization.cc.
References algebraic_interface_reinitialization, Parameters::SimulationControl::bdf1, calculate_bdf_coefficients(), curvature_projection, identify_minimum_cell_size(), and phase_gradient_projection.
assemble_system_rhs()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::assemble_system_rhs () override private virtual
Assemble the right-hand side (rhs).
Implements PhysicsSolver< VectorType >.
Definition at line 393 of file vof_algebraic_interface_reinitialization.cc.
References algebraic_interface_reinitialization, Parameters::SimulationControl::bdf1, calculate_bdf_coefficients(), curvature_projection, identify_minimum_cell_size(), and phase_gradient_projection.
compute_diffusivity()
template<int dim> double VOFAlgebraicInterfaceReinitialization< dim >::compute_diffusivity (const double min_cell_size) const inline private
Computes mesh-dependant diffusivity coefficient value.
Parameters
[in] min_cell_size Smallest cell's measure.
Returns
Constant diffusivity coefficient value for a given mesh.
Definition at line 232 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::simulation_parameters.
compute_time_step()
template<int dim> double VOFAlgebraicInterfaceReinitialization< dim >::compute_time_step () inline private
Computes algebraic reinitialization time-step value with user-imposed CFL and minimum cell size.
Returns
Algebraic reinitialization time-step.
Definition at line 250 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::cell_quadrature, VOFAlgebraicInterfaceReinitialization< dim >::dof_handler, identify_minimum_cell_size(), VOFAlgebraicInterfaceReinitialization< dim >::mapping, VOFAlgebraicInterfaceReinitialization< dim >::simulation_parameters, and VOFAlgebraicInterfaceReinitialization< dim >::triangulation.
continue_iterating()
template<int dim> bool VOFAlgebraicInterfaceReinitialization< dim >::continue_iterating (const double time_step_inv, const unsigned int step_number) inline private
Indicate if the algebraic reinitialization should continue by checking if at least one of the two stop criteria (steady-state criterion or maximum number of reinitialization steps) is met.
Parameters
[in] time_step_inv Inverse of the current reinitialization time-step.
[in] step_number Algebraic interface reinitialization step number.
Returns
Boolean indicating if the algebraic reinitialization should continue
Definition at line 323 of file vof_algebraic_interface_reinitialization.h.
References Parameters::extra_verbose, VOFAlgebraicInterfaceReinitialization< dim >::local_evaluation_point, PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >::pcout, VOFAlgebraicInterfaceReinitialization< dim >::previous_local_evaluation_point, VOFAlgebraicInterfaceReinitialization< dim >::simulation_parameters, and VOFAlgebraicInterfaceReinitialization< dim >::subequation_verbosity.
define_non_zero_constraints()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::define_non_zero_constraints () private
Define the non zero constraints used to solve the problem.
Definition at line 125 of file vof_algebraic_interface_reinitialization.cc.
References BoundaryConditions::periodic, and BoundaryConditions::vof_dirichlet.
define_zero_constraints()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::define_zero_constraints () private
Define the zero constraints used to solve the problem.
Definition at line 84 of file vof_algebraic_interface_reinitialization.cc.
References BoundaryConditions::periodic, and BoundaryConditions::vof_dirichlet.
get_evaluation_point()
template<int dim> GlobalVectorType & VOFAlgebraicInterfaceReinitialization< dim >::get_evaluation_point () inline override virtual
Getter method to access the private attribute evaluation_point for the subequation currently solved.
Returns
The vector in which the evaluation is performed.
Implements PhysicsSolver< VectorType >.
Definition at line 126 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> GlobalVectorType & VOFAlgebraicInterfaceReinitialization< dim >::get_local_evaluation_point () inline override virtual
Getter method to access the private attribute local_evaluation_point for the subequation currently solved.
Returns
The local evaluation point. Ghosts cells are not considered in this evaluation.
Implements PhysicsSolver< VectorType >.
Definition at line 139 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::local_evaluation_point.
get_newton_update()
template<int dim> GlobalVectorType & VOFAlgebraicInterfaceReinitialization< dim >::get_newton_update () inline override virtual
Getter method to access the private attribute newton_update for the subequation currently solved.
Returns
The direction used to perform the newton iteration.
Implements PhysicsSolver< VectorType >.
Definition at line 151 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints< double > & VOFAlgebraicInterfaceReinitialization< dim >::get_nonzero_constraints () inline override virtual
Getter method to access the private attribute nonzero_constraints for the subequation currently solved.
Returns
Container of nonzero constraints that arise from several sources such as boundary conditions and hanging nodes in the mesh. See the deal.II documentation on constraints on degrees of freedom for more information.
Implements PhysicsSolver< VectorType >.
Definition at line 189 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::nonzero_constraints.
get_present_solution()
template<int dim> GlobalVectorType & VOFAlgebraicInterfaceReinitialization< dim >::get_present_solution () inline override virtual
Getter method to access the private attribute present_solution for the subequation currently solved.
Returns
Vector containing all the values of the solution.
Implements PhysicsSolver< VectorType >.
Definition at line 163 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::present_solution.
get_system_rhs()
template<int dim> GlobalVectorType & VOFAlgebraicInterfaceReinitialization< dim >::get_system_rhs () inline override virtual
Getter method to access the private attribute system_rhs for the subequation currently solved.
Returns
Right-hand side vector.
Implements PhysicsSolver< VectorType >.
Definition at line 175 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::system_rhs.
output_newton_update_norms()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::output_newton_update_norms (const unsigned int display_precision) inline override virtual
Output the \(L_2\) and \(L_\infty\) norms of the correction vector.
Parameters
[in] display_precision Number of outputted digits.
Implements PhysicsSolver< VectorType >.
Definition at line 201 of file vof_algebraic_interface_reinitialization.h.
References VOFAlgebraicInterfaceReinitialization< dim >::newton_update, and PhysicsNonlinearSubequationsSolver< dim, GlobalVectorType >::pcout.
set_initial_conditions()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::set_initial_conditions () private
Sets-up the initial conditions associated with the subequation.
Definition at line 167 of file vof_algebraic_interface_reinitialization.cc.
References VOF.
setup_dofs()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::setup_dofs () override virtual
Set up the DofHandler and the degree of freedom associated with the subequation.
Implements PhysicsSubequationsSolverBase.
Definition at line 14 of file vof_algebraic_interface_reinitialization.cc.
References Parameters::quiet.
solve()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::solve () override virtual
Solve interface algebraic reinitialization process until one of the stop criteria is met.
Implements PhysicsSubequationsSolverBase.
Definition at line 688 of file vof_algebraic_interface_reinitialization.cc.
References algebraic_interface_reinitialization, announce_string(), and Parameters::quiet.
solve_linear_system()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override private virtual
Solve the linear system.
Parameters
[in] initial_step Provides the linear solver with indication if this solution is the first one for the system of equation or not.
[in] renewed_matrix Indicates to the linear solve if the system matrix has been recalculated or not.
Implements PhysicsSolver< VectorType >.
Definition at line 595 of file vof_algebraic_interface_reinitialization.cc.
References algebraic_interface_reinitialization, and Parameters::quiet.
write_output_results()
template<int dim> void VOFAlgebraicInterfaceReinitialization< dim >::write_output_results (const unsigned int step) private
Write parallel VTU files of quantities of interest for the algebraic interface reinitialization process.
Parameters
[in] step Integer indicating the reinitialization step number.
Note
Only the reinitialization steps of the last global time-step (simulation time-step) ran are outputted.
Definition at line 768 of file vof_algebraic_interface_reinitialization.cc.
References curvature_projection, phase_gradient_projection, and VOF.
Member Data Documentation
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > VOFAlgebraicInterfaceReinitialization< dim >::cell_quadrature private
Definition at line 392 of file vof_algebraic_interface_reinitialization.h.
current_time_step
template<int dim> double VOFAlgebraicInterfaceReinitialization< dim >::current_time_step private
Definition at line 382 of file vof_algebraic_interface_reinitialization.h.
dof_handler
template<int dim> DoFHandler<dim> VOFAlgebraicInterfaceReinitialization< dim >::dof_handler private
Definition at line 387 of file vof_algebraic_interface_reinitialization.h.
evaluation_point
template<int dim> GlobalVectorType VOFAlgebraicInterfaceReinitialization< dim >::evaluation_point private
Definition at line 397 of file vof_algebraic_interface_reinitialization.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > VOFAlgebraicInterfaceReinitialization< dim >::fe private
Definition at line 388 of file vof_algebraic_interface_reinitialization.h.
local_evaluation_point
template<int dim> GlobalVectorType VOFAlgebraicInterfaceReinitialization< dim >::local_evaluation_point private
Definition at line 398 of file vof_algebraic_interface_reinitialization.h.
locally_owned_dofs
template<int dim> IndexSet VOFAlgebraicInterfaceReinitialization< dim >::locally_owned_dofs private
Definition at line 395 of file vof_algebraic_interface_reinitialization.h.
locally_relevant_dofs
template<int dim> IndexSet VOFAlgebraicInterfaceReinitialization< dim >::locally_relevant_dofs private
Definition at line 396 of file vof_algebraic_interface_reinitialization.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > VOFAlgebraicInterfaceReinitialization< dim >::mapping private
Definition at line 391 of file vof_algebraic_interface_reinitialization.h.
multiphysics_interface
template<int dim> MultiphysicsInterface<dim>* VOFAlgebraicInterfaceReinitialization< dim >::multiphysics_interface private
Definition at line 370 of file vof_algebraic_interface_reinitialization.h.
newton_update
template<int dim> GlobalVectorType VOFAlgebraicInterfaceReinitialization< dim >::newton_update private
Definition at line 400 of file vof_algebraic_interface_reinitialization.h.
nonzero_constraints
template<int dim> AffineConstraints<double> VOFAlgebraicInterfaceReinitialization< dim >::nonzero_constraints private
Definition at line 405 of file vof_algebraic_interface_reinitialization.h.
present_solution
template<int dim> GlobalVectorType VOFAlgebraicInterfaceReinitialization< dim >::present_solution private
Definition at line 401 of file vof_algebraic_interface_reinitialization.h.
previous_local_evaluation_point
template<int dim> GlobalVectorType VOFAlgebraicInterfaceReinitialization< dim >::previous_local_evaluation_point private
Definition at line 399 of file vof_algebraic_interface_reinitialization.h.
previous_solution
template<int dim> GlobalVectorType VOFAlgebraicInterfaceReinitialization< dim >::previous_solution private
Definition at line 402 of file vof_algebraic_interface_reinitialization.h.
pvdhandler
template<int dim> PVDHandler VOFAlgebraicInterfaceReinitialization< dim >::pvdhandler private
Definition at line 379 of file vof_algebraic_interface_reinitialization.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> VOFAlgebraicInterfaceReinitialization< dim >::simulation_control private
Definition at line 376 of file vof_algebraic_interface_reinitialization.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& VOFAlgebraicInterfaceReinitialization< dim >::simulation_parameters private
Definition at line 373 of file vof_algebraic_interface_reinitialization.h.
subequation_id
template<int dim> const VOFSubequationsID VOFAlgebraicInterfaceReinitialization< dim >::subequation_id private
Definition at line 367 of file vof_algebraic_interface_reinitialization.h.
subequation_verbosity
template<int dim> const Parameters::Verbosity VOFAlgebraicInterfaceReinitialization< dim >::subequation_verbosity private
Definition at line 409 of file vof_algebraic_interface_reinitialization.h.
subequations_interface
template<int dim> VOFSubequationsInterface<dim>* VOFAlgebraicInterfaceReinitialization< dim >::subequations_interface private
Definition at line 368 of file vof_algebraic_interface_reinitialization.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix VOFAlgebraicInterfaceReinitialization< dim >::system_matrix private
Definition at line 406 of file vof_algebraic_interface_reinitialization.h.
system_rhs
template<int dim> GlobalVectorType VOFAlgebraicInterfaceReinitialization< dim >::system_rhs private
Definition at line 403 of file vof_algebraic_interface_reinitialization.h.
time_step_vector
template<int dim> std::vector<double> VOFAlgebraicInterfaceReinitialization< dim >::time_step_vector = {0.0} private
Definition at line 383 of file vof_algebraic_interface_reinitialization.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > VOFAlgebraicInterfaceReinitialization< dim >::triangulation private
Definition at line 386 of file vof_algebraic_interface_reinitialization.h.
zero_constraints
template<int dim> AffineConstraints<double> VOFAlgebraicInterfaceReinitialization< dim >::zero_constraints private
Definition at line 404 of file vof_algebraic_interface_reinitialization.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/vof_algebraic_interface_reinitialization.h
/home/runner/work/lethe/lethe/source/solvers/vof_algebraic_interface_reinitialization.cc