Lethe Open-Source Library: GLSIsothermalCompressibleNavierStokesCLSAssemblerCore< dim > Class Template Reference
GLSIsothermalCompressibleNavierStokesCLSAssemblerCore< dim > Class Template Reference
#include <isothermal_compressible_navier_stokes_cls_assembler.h>
Public Member Functions
GLSIsothermalCompressibleNavierStokesCLSAssemblerCore (const std::shared_ptr< SimulationControl > &simulation_control, const SimulationParameters< dim > &nsparam)
virtual void assemble_matrix (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual void assemble_rhs (const NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
Public Member Functions inherited from PhysicsAssemblerBase< ScratchDataType, CopyDataType >
virtual void assemble_matrix (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
virtual void assemble_rhs (const ScratchDataType &scratch_data, CopyDataType &copy_data)=0
virtual ~PhysicsAssemblerBase ()=default
Public Attributes
const std::shared_ptr< SimulationControl > simulation_control
const Parameters::CLS cls_parameters
Detailed Description
template<int dim>
class GLSIsothermalCompressibleNavierStokesCLSAssemblerCore< dim >
Class that assembles the core of the Navier-Stokes equation with free surface using CLS modeling. According to the following weak form: \(\nabla \cdot (\rho \mathbf{u}) + \rho \mathbf{u} \cdot \nabla \mathbf{u} - \nabla p - \mu \nabla\cdot (\nabla \mathbf{u} + (\nabla \mathbf{u})^T) = 0 \) with a full GLS stabilization.
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 28 of file isothermal_compressible_navier_stokes_cls_assembler.h.
Constructor & Destructor Documentation
GLSIsothermalCompressibleNavierStokesCLSAssemblerCore()
template<int dim> GLSIsothermalCompressibleNavierStokesCLSAssemblerCore< dim >::GLSIsothermalCompressibleNavierStokesCLSAssemblerCore (const std::shared_ptr< SimulationControl > & simulation_control, const SimulationParameters< dim > & nsparam) inline
Definition at line 32 of file isothermal_compressible_navier_stokes_cls_assembler.h.
Member Function Documentation
assemble_matrix()
template<int dim> void GLSIsothermalCompressibleNavierStokesCLSAssemblerCore< dim >::assemble_matrix (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_matrix Assembles the matrix
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 12 of file isothermal_compressible_navier_stokes_cls_assembler.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::compressibility_multiplier, NavierStokesScratchData< dim >::density, NavierStokesScratchData< dim >::density_0, NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::dynamic_viscosity, NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, NavierStokesScratchData< dim >::laplacian_phi_u, StabilizedMethodsTensorCopyData< dim >::local_matrix, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_scaling_factor, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_jacobian, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_hessians, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
assemble_rhs()
template<int dim> void GLSIsothermalCompressibleNavierStokesCLSAssemblerCore< dim >::assemble_rhs (const NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_rhs Assembles the rhs
Parameters
scratch_data (see base class)
copy_data (see base class)
Definition at line 188 of file isothermal_compressible_navier_stokes_cls_assembler.cc.
References calculate_navier_stokes_gls_tau_steady(), calculate_navier_stokes_gls_tau_transient(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::compressibility_multiplier, NavierStokesScratchData< dim >::density, NavierStokesScratchData< dim >::density_0, NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::dynamic_viscosity, NavierStokesScratchData< dim >::dynamic_viscosity_for_stabilization, NavierStokesScratchData< dim >::force, NavierStokesScratchData< dim >::grad_phi_p, NavierStokesScratchData< dim >::grad_phi_u, NavierStokesScratchData< dim >::JxW, StabilizedMethodsTensorCopyData< dim >::local_rhs, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, pressure, NavierStokesScratchData< dim >::pressure_gradients, NavierStokesScratchData< dim >::pressure_values, shear_rate, Parameters::SimulationControl::steady, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_divergences, NavierStokesScratchData< dim >::velocity_gradients, NavierStokesScratchData< dim >::velocity_hessians, NavierStokesScratchData< dim >::velocity_laplacians, and NavierStokesScratchData< dim >::velocity_values.
Member Data Documentation
cls_parameters
template<int dim> const Parameters::CLS GLSIsothermalCompressibleNavierStokesCLSAssemblerCore< dim >::cls_parameters
Definition at line 58 of file isothermal_compressible_navier_stokes_cls_assembler.h.
simulation_control
template<int dim> const std::shared_ptr<SimulationControl> GLSIsothermalCompressibleNavierStokesCLSAssemblerCore< dim >::simulation_control
Definition at line 57 of file isothermal_compressible_navier_stokes_cls_assembler.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/isothermal_compressible_navier_stokes_cls_assembler.h
/home/runner/work/lethe/lethe/source/solvers/isothermal_compressible_navier_stokes_cls_assembler.cc