Lethe Open-Source Library: KinsolNewtonNonLinearSolverStrategy< VectorType > Class Template Reference
KinsolNewtonNonLinearSolverStrategy< VectorType > Class Template Reference
#include <kinsol_newton_non_linear_solver_strategy.h>
Public Member Functions
KinsolNewtonNonLinearSolverStrategy (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &param)
void solve () override
Public Member Functions inherited from PhysicsSolverStrategy< VectorType >
PhysicsSolverStrategy (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &params)
PhysicsSolverStrategy (PhysicsSolver< VectorType > *physics_solver)
virtual ~PhysicsSolverStrategy ()
unsigned int get_current_newton_iteration () const
Additional Inherited Members
Protected Attributes inherited from PhysicsSolverStrategy< VectorType >
PhysicsSolver< VectorType > * physics_solver
Parameters::NonLinearSolver params
unsigned int outer_iteration
Detailed Description
template<typename VectorType>
class KinsolNewtonNonLinearSolverStrategy< VectorType >
Non-linear Newton solver for non-linear systems of equations implemented in the SUNDIALS suite, specifically the KINSOL package. This solver has internal algorithms to determine the time step and decide whether to reassemble the Jacobian matrix or not.
Definition at line 19 of file kinsol_newton_non_linear_solver_strategy.h.
Constructor & Destructor Documentation
KinsolNewtonNonLinearSolverStrategy()
template<typename VectorType > KinsolNewtonNonLinearSolverStrategy< VectorType >::KinsolNewtonNonLinearSolverStrategy (PhysicsSolver< VectorType > * physics_solver, const Parameters::NonLinearSolver & param)
Constructor.
Parameters
[in] physics_solver A pointer to the physics solver to which the non-linear solver is attached.
[in] param Non-linear solver parameters as specified in the simulation parameter file.
Definition at line 45 of file kinsol_newton_non_linear_solver_strategy.h.
Member Function Documentation
solve()
template<typename VectorType > void KinsolNewtonNonLinearSolverStrategy< VectorType >::solve () override virtual
Solve the non-linear system of equations.
Implements PhysicsSolverStrategy< VectorType >.
Definition at line 53 of file kinsol_newton_non_linear_solver_strategy.h.
References PhysicsSolver< VectorType >::apply_constraints(), PhysicsSolver< VectorType >::assemble_system_matrix(), PhysicsSolver< VectorType >::assemble_system_rhs(), PhysicsSolver< VectorType >::get_evaluation_point(), PhysicsSolver< VectorType >::get_local_evaluation_point(), PhysicsSolver< VectorType >::get_newton_update(), PhysicsSolver< VectorType >::get_present_solution(), PhysicsSolver< VectorType >::get_system_rhs(), Parameters::NonLinearSolver::line_search, Parameters::NonLinearSolver::normal_newton, PhysicsSolver< VectorType >::pcout, Parameters::NonLinearSolver::picard, PhysicsSolver< VectorType >::setup_preconditioner(), and PhysicsSolver< VectorType >::solve_linear_system().
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/kinsol_newton_non_linear_solver_strategy.h