Lethe Open-Source Library: ParticlesForceChains< dim, PropertiesIndex, force_model, rolling_friction_model > Class Template Reference
ParticlesForceChains< dim, PropertiesIndex, force_model, rolling_friction_model > Class Template Reference
#include <force_chains_visualization.h>
Public Member Functions
ParticlesForceChains (const DEMSolverParameters< dim > &dem_parameters)
virtual ~ParticlesForceChains ()
void write_force_chains (const DEMSolverParameters< dim > &dem_parameters, PVDHandler &pvd_handler, const MPI_Comm mpi_communicator, const std::string folder, const unsigned int iter, const double time, typename dem_data_structures< dim >::adjacent_particle_pairs &local_adjacent_particles, typename dem_data_structures< dim >::adjacent_particle_pairs &ghost_adjacent_particles) override
Public Member Functions inherited from ParticleParticleContactForce< dim, PropertiesIndex, force_model, rolling_friction_model >
ParticleParticleContactForce (const DEMSolverParameters< dim > &dem_parameters)
virtual ~ParticleParticleContactForce ()
virtual void calculate_particle_particle_contact (typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &local_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &ghost_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &local_local_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &local_ghost_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &ghost_local_periodic_adjacent_particles, const double dt, ParticleInteractionOutcomes< PropertiesIndex > &contact_outcome) override
Public Member Functions inherited from ParticleParticleContactForceBase< dim, PropertiesIndex >
void set_periodic_offset (const Tensor< 1, dim > &periodic_offset)
Private Member Functions
void calculate_force_chains (typename dem_data_structures< dim >::adjacent_particle_pairs &local_adjacent_particles, typename dem_data_structures< dim >::adjacent_particle_pairs &ghost_adjacent_particles, std::vector< Point< 3 > > &vertices, std::vector< double > &normal_forces_vector) override
template<ContactType contact_type>
void execute_contact_calculation (typename DEM::dem_data_structures< dim >::particle_contact_info &adjacent_particles_list, std::vector< Point< 3 > > &vertices, std::vector< double > &normal_forces_vector)
void update_contact_information (Tensor< 1, 3 > &tangential_relative_velocity, double &normal_relative_velocity_value, Tensor< 1, 3 > &normal_unit_vector, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, const Point< 3 > &particle_one_location, const Point< 3 > &particle_two_location)
void multi_general_cell (Triangulation< 1, 3 > &tria, const std::vector< Point< 3 > > &vertices)
Additional Inherited Members
Protected Member Functions inherited from ParticleParticleContactForce< dim, PropertiesIndex, force_model, rolling_friction_model >
void update_contact_information (particle_particle_contact_info< dim > &contact_info, Tensor< 1, 3 > &tangential_relative_velocity, double &normal_relative_velocity_value, Tensor< 1, 3 > &normal_unit_vector, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, const Point< 3 > &particle_one_location, const Point< 3 > &particle_two_location, const double dt)
Point< 3 > get_location (const Particles::ParticleIterator< dim > &particle) &
Point< 3 > get_periodic_location (const Particles::ParticleIterator< dim > &particle) &
void calculate_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
double get_force_calculation_threshold_distance ()
Protected Attributes inherited from ParticleParticleContactForceBase< dim, PropertiesIndex >
Tensor< 1, dim > periodic_offset
Detailed Description
template<int dim, typename PropertiesIndex, Parameters::Lagrangian::ParticleParticleContactForceModel force_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model>
class ParticlesForceChains< dim, PropertiesIndex, force_model, rolling_friction_model >
Class that carries out the calculation of particle-particle contact force and the visualization of force chains by writing vtu files, pvtu files and a pvd file. Instead of using a inheritance hierarchy to distinguish between the contact model, the class is templated with the type of force model and rolling friction model. Consequently, the code for each combination of force model is generated at compile time.
Template Parameters
dim The dimension of the problem
force_model The particle-particle contact force model
rolling_friction_model The rolling resistance model
Definition at line 110 of file force_chains_visualization.h.
Constructor & Destructor Documentation
ParticlesForceChains()
template<int dim, typename PropertiesIndex , ParticleParticleContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> ParticlesForceChains< dim, PropertiesIndex, contact_model, rolling_friction_model >::ParticlesForceChains (const DEMSolverParameters< dim > & dem_parameters)
Definition at line 27 of file force_chains_visualization.cc.
~ParticlesForceChains()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel force_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> virtual ParticlesForceChains< dim, PropertiesIndex, force_model, rolling_friction_model >::~ParticlesForceChains () inline virtual
Definition at line 120 of file force_chains_visualization.h.
Member Function Documentation
calculate_force_chains()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel force_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticlesForceChains< dim, PropertiesIndex, force_model, rolling_friction_model >::calculate_force_chains (typename dem_data_structures< dim >::adjacent_particle_pairs & local_adjacent_particles, typename dem_data_structures< dim >::adjacent_particle_pairs & ghost_adjacent_particles, std::vector< Point< 3 > > & vertices, std::vector< double > & normal_forces_vector) override private virtual
Calculate normal forces between all touching particles with ParticleParticleContactForce class' methods. Stock normal forces and particles position in vectors.
Parameters
[in] local_adjacent_particles Container of the contact pair candidates information for calculation of the local particle-particle contact forces.
[in] ghost_adjacent_particles Container of the contact pair candidates information for calculation of the local-ghost particle-particle contact forces.
[out] vertices the vector of positions of touching particles.
[out] normal_forces_vector the vector of normal forces between each touching particles.
Implements ParticlesForceChainsBase< dim, PropertiesIndex >.
Definition at line 67 of file force_chains_visualization.cc.
execute_contact_calculation()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel force_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> template<ContactType contact_type> void ParticlesForceChains< dim, PropertiesIndex, force_model, rolling_friction_model >::execute_contact_calculation (typename DEM::dem_data_structures< dim >::particle_contact_info & adjacent_particles_list, std::vector< Point< 3 > > & vertices, std::vector< double > & normal_forces_vector) inline private
Execute the contact calculation step for the particle-particle contact only for local-local and local-ghost contacts with no periodicity. This is a simplified version of the contact calculation of the particle-particle contact forces class, without the other contact types and the update of the particles forces, torques and tangential displacement.
Template Parameters
force_model The particle-particle contact force model.
Parameters
[in] adjacent_particles_list Container of the adjacent particles of a particles.
[out] vertices the vector of positions of touching particles.
[out] normal_forces_vector the vector of normal forces between each touching particles.
Definition at line 196 of file force_chains_visualization.h.
References ParticleParticleContactForce< dim, PropertiesIndex, force_model, rolling_friction_model >::calculate_contact(), ParticleParticleContactForce< dim, PropertiesIndex, force_model, rolling_friction_model >::get_force_calculation_threshold_distance(), ParticleParticleContactForce< dim, PropertiesIndex, force_model, rolling_friction_model >::get_location(), ghost_particle_particle, and ParticlesForceChains< dim, PropertiesIndex, force_model, rolling_friction_model >::update_contact_information().
multi_general_cell()
template<int dim, typename PropertiesIndex , ParticleParticleContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> void ParticlesForceChains< dim, PropertiesIndex, contact_model, rolling_friction_model >::multi_general_cell (Triangulation< 1, 3 > & tria, const std::vector< Point< 3 > > & vertices) private
Create a triangulation with a unique cell (represented by a line) for each normal force between two particles.
Parameters
[out] tria Empty triangulation used to create a triangulation with all the vertices needed.
[in] vertices Vector of points used to create a triangulation
Definition at line 43 of file force_chains_visualization.cc.
update_contact_information()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel force_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticlesForceChains< dim, PropertiesIndex, force_model, rolling_friction_model >::update_contact_information (Tensor< 1, 3 > & tangential_relative_velocity, double & normal_relative_velocity_value, Tensor< 1, 3 > & normal_unit_vector, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, const Point< 3 > & particle_one_location, const Point< 3 > & particle_two_location) inline private
Update the contact pair information for all contact force calculations.
Parameters
[out] tangential_relative_velocity Tangential relative velocity.
[out] normal_relative_velocity_value Normal relative velocity.
[out] normal_unit_vector Normal vector of the contact.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[in] particle_one_location Location of particle one in contact.
[in] particle_two_location Location of particle two in contact.
Definition at line 298 of file force_chains_visualization.h.
write_force_chains()
template<int dim, typename PropertiesIndex , ParticleParticleContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> void ParticlesForceChains< dim, PropertiesIndex, contact_model, rolling_friction_model >::write_force_chains (const DEMSolverParameters< dim > & dem_parameters, PVDHandler & pvd_handler, const MPI_Comm mpi_communicator, const std::string folder, const unsigned int iter, const double time, typename dem_data_structures< dim >::adjacent_particle_pairs & local_adjacent_particles, typename dem_data_structures< dim >::adjacent_particle_pairs & ghost_adjacent_particles) override virtual
Output the force chains in VTU and PVTU files for each iteration and a PVD file.
Parameters
[in] dem_parameters DEM parameters declared in the .prm file.
[in] pvd_handler a PVDHandler to store the information about the file name and time associated with it.
[in] mpi_communicator The mpi communicator.
[in] folder a string that contains the path where the results are to be saved.
[in] iter the iteration number associated with the file.
[in] time the time associated with the file.
[in] local_adjacent_particles Container of the contact pair candidates information for calculation of the local particle-particle contact forces.
[in] ghost_adjacent_particles Container of the contact pair candidates information for calculation of the local-ghost particle-particle contact forces.
Implements ParticlesForceChainsBase< dim, PropertiesIndex >.
Definition at line 102 of file force_chains_visualization.cc.
References PVDHandler::append(), Parameters::SimulationControl::output_name, DEMSolverParameters< dim >::simulation_control, and PVDHandler::times_and_names.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/force_chains_visualization.h
/home/runner/work/lethe/lethe/source/dem/force_chains_visualization.cc