Lethe Open-Source Library: VANSAssemblerBDF< dim > Class Template Reference
VANSAssemblerBDF< dim > Class Template Reference
#include <vans_assemblers.h>
Public Member Functions
VANSAssemblerBDF (std::shared_ptr< SimulationControl > simulation_control, Parameters::CFDDEM cfd_dem)
virtual void assemble_matrix (NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual void assemble_rhs (NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
Public Attributes
std::shared_ptr< SimulationControl > simulation_control
Parameters::CFDDEM cfd_dem
Detailed Description
template<int dim>
class VANSAssemblerBDF< dim >
Class that assembles the transient time arising from BDF time integration for the Navier-Stokes equation with free surface using VOF modeling.. For example, if a BDF1 scheme is chosen, the following is assembled \(\frac{(\rho \mathbf{u})^{t+\Delta t}-(\rho \mathbf{u})^{t}}{\Delta t}\).
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 140 of file vans_assemblers.h.
Constructor & Destructor Documentation
VANSAssemblerBDF()
template<int dim> VANSAssemblerBDF< dim >::VANSAssemblerBDF (std::shared_ptr< SimulationControl > simulation_control, Parameters::CFDDEM cfd_dem) inline
Definition at line 143 of file vans_assemblers.h.
Member Function Documentation
assemble_matrix()
template<int dim> void VANSAssemblerBDF< dim >::assemble_matrix (NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_matrix Assembles the matrix
Parameters
scratch_data (see base class)
copy_data (see base class)
Implements NavierStokesAssemblerBase< dim >.
Definition at line 745 of file vans_assemblers.cc.
References NavierStokesScratchData< dim >::JxW, StabilizedMethodsTensorCopyData< dim >::local_matrix, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, number_of_previous_solutions(), NavierStokesScratchData< dim >::phi_u, NavierStokesScratchData< dim >::previous_velocity_values, StabilizedMethodsTensorCopyData< dim >::strong_jacobian, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_values, and NavierStokesScratchData< dim >::void_fraction_values.
assemble_rhs()
template<int dim> void VANSAssemblerBDF< dim >::assemble_rhs (NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override virtual
assemble_rhs Assembles the rhs
Parameters
scratch_data (see base class)
copy_data (see base class)
Implements NavierStokesAssemblerBase< dim >.
Definition at line 805 of file vans_assemblers.cc.
References calculate_gamma(), NavierStokesScratchData< dim >::cell_size, NavierStokesScratchData< dim >::div_phi_u, NavierStokesScratchData< dim >::JxW, NavierStokesScratchData< dim >::kinematic_viscosity, StabilizedMethodsTensorCopyData< dim >::local_rhs, NavierStokesScratchData< dim >::n_dofs, NavierStokesScratchData< dim >::n_q_points, number_of_previous_solutions(), NavierStokesScratchData< dim >::phi_p, NavierStokesScratchData< dim >::phi_u, NavierStokesScratchData< dim >::previous_velocity_values, NavierStokesScratchData< dim >::previous_void_fraction_values, StabilizedMethodsTensorCopyData< dim >::strong_residual, velocity, NavierStokesScratchData< dim >::velocity_values, and NavierStokesScratchData< dim >::void_fraction_values.
Member Data Documentation
cfd_dem
template<int dim> Parameters::CFDDEM VANSAssemblerBDF< dim >::cfd_dem
Definition at line 169 of file vans_assemblers.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> VANSAssemblerBDF< dim >::simulation_control
Definition at line 167 of file vans_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/vans_assemblers.h
/home/runner/work/lethe/lethe/source/fem-dem/vans_assemblers.cc