Lethe Open-Source Library: NavierStokesOperatorBase< dim, number > Class Template Reference
NavierStokesOperatorBase< dim, number > Class Template Reference abstract
#include <fluid_dynamics_matrix_free_operators.h>
Public Types
using FECellIntegrator = FEEvaluation< dim, -1, 0, dim+1, number >
using FEFaceIntegrator = FEFaceEvaluation< dim, -1, 0, dim+1, number >
using VectorType = LinearAlgebra::distributed::Vector< number >
using value_type = number
using size_type = VectorizedArray< number >
using StabilizationType = Parameters::Stabilization::NavierStokesStabilization
Public Member Functions
NavierStokesOperatorBase ()
NavierStokesOperatorBase (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const AffineConstraints< number > &constraints, const Quadrature< dim > &quadrature, const std::shared_ptr< Function< dim > > forcing_function, const std::shared_ptr< PhysicalPropertiesManager > &physical_properties_manager, const StabilizationType stabilization, const unsigned int mg_level, const std::shared_ptr< SimulationControl > &simulation_control, const BoundaryConditions::NSBoundaryConditions< dim > &boundary_conditions, const bool &enable_hessians_jacobian, const bool &enable_hessians_residual)
void reinit (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const AffineConstraints< number > &constraints, const Quadrature< dim > &quadrature, const std::shared_ptr< Function< dim > > forcing_function, const std::shared_ptr< PhysicalPropertiesManager > &physical_properties_manager, const StabilizationType stabilization, const unsigned int mg_level, const std::shared_ptr< SimulationControl > &simulation_control, const BoundaryConditions::NSBoundaryConditions< dim > &boundary_conditions, const bool &enable_hessians_jacobian, const bool &enable_hessians_residual)
void compute_element_size ()
void compute_forcing_term ()
void compute_buoyancy_term (const VectorType &temperature_solution, const DoFHandler< dim > &temperature_dof_handler)
types::global_dof_index m () const
number el (unsigned int, unsigned int) const
void clear ()
void initialize_dof_vector (VectorType &vec) const
const std::shared_ptr< const Utilities::MPI::Partitioner > & get_vector_partitioner () const
void vmult (VectorType &dst, const VectorType &src) const
void Tvmult (VectorType &dst, const VectorType &src) const
void vmult_interface_down (VectorType &dst, VectorType const &src) const
void vmult_interface_up (VectorType &dst, VectorType const &src) const
const DynamicSparsityPattern & get_sparsity_pattern () const
const TrilinosWrappers::SparseMatrix & get_system_matrix () const
const MatrixFree< dim, number > & get_system_matrix_free () const
const AlignedVector< VectorizedArray< number > > get_element_size () const
void compute_inverse_diagonal (VectorType &diagonal) const
virtual void evaluate_non_linear_term_and_calculate_tau (const VectorType &newton_step)
void evaluate_time_derivative_previous_solutions (const VectorType &time_derivative_previous_solutions)
void update_beta_force (const Tensor< 1, dim > &beta_force)
void evaluate_residual (VectorType &dst, const VectorType &src)
Public Attributes
TimerOutput timer
Protected Member Functions
virtual void do_cell_integral_local (FECellIntegrator &integrator) const =0
void do_cell_integral_range (const MatrixFree< dim, number > &matrix_free, VectorType &dst, const VectorType &src, const std::pair< unsigned int, unsigned int > &range) const
template<bool assemble_residual>
void do_boundary_face_integral_local (FEFaceIntegrator &integrator) const
template<bool assemble_residual>
void do_boundary_face_integral_range (const MatrixFree< dim, number > &matrix_free, VectorType &dst, const VectorType &src, const std::pair< unsigned int, unsigned int > &range) const
void do_internal_face_integral_range (const MatrixFree< dim, number > &matrix_free, VectorType &dst, const VectorType &src, const std::pair< unsigned int, unsigned int > &range) const
virtual void local_evaluate_residual (const MatrixFree< dim, number > &matrix_free, VectorType &dst, const VectorType &src, const std::pair< unsigned int, unsigned int > &range) const =0
Protected Attributes
MatrixFree< dim, number > matrix_free
AffineConstraints< number > constraints
DynamicSparsityPattern dsp
TrilinosWrappers::SparseMatrix system_matrix
AlignedVector< VectorizedArray< number > > element_size
unsigned int fe_degree
std::shared_ptr< Function< dim > > forcing_function
Tensor< 1, dim, VectorizedArray< number > > beta_force
StabilizationType stabilization
std::shared_ptr< SimulationControl > simulation_control
std::shared_ptr< PhysicalPropertiesManager > properties_manager
BoundaryConditions::NSBoundaryConditions< dim > boundary_conditions
bool enable_hessians_jacobian
bool enable_hessians_residual
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > forcing_terms
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > buoyancy_term
bool enable_face_terms
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > nonlinear_previous_values
Table< 2, Tensor< 1, dim+1, Tensor< 1, dim, VectorizedArray< number > > > > nonlinear_previous_gradient
Table< 2, Tensor< 1, dim+1, Tensor< 1, dim, VectorizedArray< number > > > > nonlinear_previous_hessian_diagonal
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > time_derivatives_previous_solutions
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > face_nonlinear_previous_values
Table< 2, Tensor< 1, dim, VectorizedArray< number > > > face_target_velocity
Table< 2, VectorizedArray< number > > stabilization_parameter
Table< 2, VectorizedArray< number > > stabilization_parameter_lsic
Table< 2, VectorizedArray< number > > kinematic_viscosity_vector
Table< 2, VectorizedArray< number > > grad_kinematic_viscosity_shear_rate
Table< 2, Tensor< 1, dim+1, VectorizedArray< number > > > kinematic_viscosity_gradient
Table< 2, Tensor< 1, dim+1, Tensor< 1, dim, VectorizedArray< number > > > > previous_shear_rate
Table< 2, VectorizedArray< number > > previous_shear_rate_magnitude
Table< 1, VectorizedArray< number > > effective_beta_face
std::vector< unsigned int > constrained_indices
std::vector< std::pair< number, number > > constrained_values
std::vector< unsigned int > edge_constrained_indices
bool has_edge_constrained_indices = false
std::vector< number > edge_constrained_values
std::vector< bool > edge_constrained_cell
Table< 2, bool > bool_dof_mask
ConditionalOStream pcout
Static Private Member Functions
static IndexSet get_refinement_edges (const MatrixFree< dim, number > &matrix_free)
Detailed Description
template<int dim, typename number>
class NavierStokesOperatorBase< dim, number >
A class that serves as base for all the matrix-free Navier-Stokes operators.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
number Abstract type for number across the class (i.e., double).
Definition at line 117 of file fluid_dynamics_matrix_free_operators.h.
Member Typedef Documentation
FECellIntegrator
template<int dim, typename number > using NavierStokesOperatorBase< dim, number >::FECellIntegrator = FEEvaluation<dim, -1, 0, dim + 1, number>
Definition at line 120 of file fluid_dynamics_matrix_free_operators.h.
FEFaceIntegrator
template<int dim, typename number > using NavierStokesOperatorBase< dim, number >::FEFaceIntegrator = FEFaceEvaluation<dim, -1, 0, dim + 1, number>
Definition at line 121 of file fluid_dynamics_matrix_free_operators.h.
size_type
template<int dim, typename number > using NavierStokesOperatorBase< dim, number >::size_type = VectorizedArray<number>
Definition at line 124 of file fluid_dynamics_matrix_free_operators.h.
StabilizationType
template<int dim, typename number > using NavierStokesOperatorBase< dim, number >::StabilizationType = Parameters::Stabilization::NavierStokesStabilization
Definition at line 125 of file fluid_dynamics_matrix_free_operators.h.
value_type
template<int dim, typename number > using NavierStokesOperatorBase< dim, number >::value_type = number
Definition at line 123 of file fluid_dynamics_matrix_free_operators.h.
VectorType
template<int dim, typename number > using NavierStokesOperatorBase< dim, number >::VectorType = LinearAlgebra::distributed::Vector<number>
Definition at line 122 of file fluid_dynamics_matrix_free_operators.h.
Constructor & Destructor Documentation
NavierStokesOperatorBase() [1/2]
template<int dim, typename number > NavierStokesOperatorBase< dim, number >::NavierStokesOperatorBase ()
Default constructor.
Definition at line 70 of file fluid_dynamics_matrix_free_operators.cc.
NavierStokesOperatorBase() [2/2]
template<int dim, typename number > NavierStokesOperatorBase< dim, number >::NavierStokesOperatorBase (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const AffineConstraints< number > & constraints, const Quadrature< dim > & quadrature, const std::shared_ptr< Function< dim > > forcing_function, const std::shared_ptr< PhysicalPropertiesManager > & physical_properties_manager, const StabilizationType stabilization, const unsigned int mg_level, const std::shared_ptr< SimulationControl > & simulation_control, const BoundaryConditions::NSBoundaryConditions< dim > & boundary_conditions, const bool & enable_hessians_jacobian, const bool & enable_hessians_residual)
Constructor that points to the reinit function.
Parameters
[in] mapping Describes the transformations from unit to real cell.
[in] dof_handler Describes the layout of DoFs and the type of FE.
[in] constraints Object with constraints according to DoFs.
[in] quadrature Required for local operations on cells.
[in] forcing_function Function specified in parameter file as source term.
[in] properties_manager The physical properties manager (see physical_properties_manager.h)
[in] stabilization Stabilization type specified in parameter file.
[in] mg_level Level of the operator in case of MG methods.
[in] simulation_control Required to get the time stepping method.
[in] physical_properties_manager Required to have the updated values of physical properties in case of ramp or viscous initial conditions.
[in] boundary_conditions Contains information regarding all boundary conditions. Required to weakly impose boundary conditions.
[in] enable_hessians_jacobian Flag to turn hessian terms from jacobian on or off.
[in] enable_hessians_residual Flag to turn hessian terms from residual on or off.
Definition at line 76 of file fluid_dynamics_matrix_free_operators.cc.
References NavierStokesOperatorBase< dim, number >::boundary_conditions, NavierStokesOperatorBase< dim, number >::constraints, NavierStokesOperatorBase< dim, number >::enable_hessians_jacobian, NavierStokesOperatorBase< dim, number >::enable_hessians_residual, NavierStokesOperatorBase< dim, number >::forcing_function, NavierStokesOperatorBase< dim, number >::reinit(), NavierStokesOperatorBase< dim, number >::simulation_control, and NavierStokesOperatorBase< dim, number >::stabilization.
Member Function Documentation
clear()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::clear ()
Clear the matrix-free object.
Definition at line 397 of file fluid_dynamics_matrix_free_operators.cc.
compute_buoyancy_term()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::compute_buoyancy_term (const VectorType & temperature_solution, const DoFHandler< dim > & temperature_dof_handler)
Precompute buoyancy term for heat-transfer coupling.
Parameters
[in] temperature_solution Present solution of the temperature as given by the multiphysics interface.
[in] temperature_dof_handler DoF Handler used for the heat transfer.
Definition at line 319 of file fluid_dynamics_matrix_free_operators.cc.
compute_element_size()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::compute_element_size ()
Compute the element size h of the cells required to calculate stabilization parameters.
Definition at line 269 of file fluid_dynamics_matrix_free_operators.cc.
compute_forcing_term()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::compute_forcing_term ()
Precompute forcing term.
Definition at line 291 of file fluid_dynamics_matrix_free_operators.cc.
compute_inverse_diagonal()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::compute_inverse_diagonal (VectorType & diagonal) const
Compute the diagonal of the operator using an optimized MatrixFree function. Needed for preconditioners.
Parameters
[in,out] diagonal The vector where the computed diagonal is stored.
Definition at line 1131 of file fluid_dynamics_matrix_free_operators.cc.
do_boundary_face_integral_local()
template<int dim, typename number > template<bool assemble_residual> void NavierStokesOperatorBase< dim, number >::do_boundary_face_integral_local (FEFaceIntegrator & integrator) const protected
Carry out the integration of boundary face integrals.
Template Parameters
assemble_residual Flag to assemble the residual or the Jacobian.
Parameters
[in] integrator FEFaceEvaluation object that allows to evaluate functions at quadrature points and perform face integrations.
Definition at line 1241 of file fluid_dynamics_matrix_free_operators.cc.
References BoundaryConditions::function_weak, BoundaryConditions::outlet, and velocity.
do_boundary_face_integral_range()
template<int dim, typename number > template<bool assemble_residual> void NavierStokesOperatorBase< dim, number >::do_boundary_face_integral_range (const MatrixFree< dim, number > & matrix_free, VectorType & dst, const VectorType & src, const std::pair< unsigned int, unsigned int > & range) const protected
Loop over all boundary face batches within certain range and perform a face integral with access to global vectors, i.e., gathering and scattering values. This is used to weakly impose Dirichlet boundary conditions or outlet boundary conditions.
Template Parameters
assemble_residual Flag to assemble the residual or the Jacobian.
Parameters
[in] matrix_free Object that contains all data.
[in,out] dst Global vector where the final result is added.
[in] src Input vector with all values in all cells.
[in] range Range of the face batch.
Definition at line 1204 of file fluid_dynamics_matrix_free_operators.cc.
do_cell_integral_local()
template<int dim, typename number > virtual void NavierStokesOperatorBase< dim, number >::do_cell_integral_local (FECellIntegrator & integrator) const protected pure virtual
Interface to function that performs a cell integral in a cell batch without gathering and scattering the values. Should be overriden by derived classes.
Parameters
[in] integrator FEEvaluation object that allows to evaluate functions at quadrature points and perform cell integrations.
Implemented in VANSOperator< dim, number >, NavierStokesStabilizedOperator< dim, number >, and NavierStokesNonNewtonianStabilizedOperator< dim, number >.
do_cell_integral_range()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::do_cell_integral_range (const MatrixFree< dim, number > & matrix_free, VectorType & dst, const VectorType & src, const std::pair< unsigned int, unsigned int > & range) const protected
Loop over all cell batches within certain range and perform a cell integral with access to global vectors, i.e., gathering and scattering values.
Parameters
[in] matrix_free Object that contains all data.
[in,out] dst Global vector where the final result is added.
[in] src Input vector with all values in all cells.
[in] range Range of the cell batch.
Definition at line 1165 of file fluid_dynamics_matrix_free_operators.cc.
do_internal_face_integral_range()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::do_internal_face_integral_range (const MatrixFree< dim, number > & matrix_free, VectorType & dst, const VectorType & src, const std::pair< unsigned int, unsigned int > & range) const protected
Loop over all internal face batches within certain range and perform a face integral with access to global vectors, i.e., gathering and scattering values. This is only required for compilation and not needed for our CG implementation.
Parameters
[in] matrix_free Object that contains all data.
[in,out] dst Global vector where the final result is added.
[in] src Input vector with all values in all cells.
[in] range Range of the face batch.
Definition at line 1187 of file fluid_dynamics_matrix_free_operators.cc.
el()
template<int dim, typename number > number NavierStokesOperatorBase< dim, number >::el (unsigned int , unsigned int) const
Access a particular element in the matrix. Only required for compilation and it is not used.
Parameters
int
int
Returns
number
Definition at line 389 of file fluid_dynamics_matrix_free_operators.cc.
evaluate_non_linear_term_and_calculate_tau()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::evaluate_non_linear_term_and_calculate_tau (const VectorType & newton_step) virtual
Store relevant values of the vector of the last newton step to use it in the Jacobian and pre-calculate the stabilization parameter tau.
Parameters
[in] newton_step Vector of the last newton step.
Reimplemented in VANSOperator< dim, number >.
Definition at line 776 of file fluid_dynamics_matrix_free_operators.cc.
References BoundaryConditions::function_weak, is_bdf(), BoundaryConditions::outlet, and shear_rate.
evaluate_residual()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::evaluate_residual (VectorType & dst, const VectorType & src)
Evaluate right hand side using the matrix-free operator.
Parameters
[in,out] dst Destination vector holding the result.
[in] src Input vector for which the residual is evaluated.
Definition at line 1103 of file fluid_dynamics_matrix_free_operators.cc.
References NavierStokesOperatorBase< dim, number >::do_internal_face_integral_range(), and NavierStokesOperatorBase< dim, number >::local_evaluate_residual().
evaluate_time_derivative_previous_solutions()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::evaluate_time_derivative_previous_solutions (const VectorType & time_derivative_previous_solutions)
Store the values of the vector containing the time derivatives of previous solutions to use them in the Jacobian and residual cell integrals.
Parameters
[in] time_derivative_previous_solutions Vector with the time derivative of previous solutions.
Definition at line 1064 of file fluid_dynamics_matrix_free_operators.cc.
get_element_size()
template<int dim, typename number > const AlignedVector< VectorizedArray< number > > NavierStokesOperatorBase< dim, number >::get_element_size () const
Get the element size object.
Returns
Aligned vector with the size of all elements.
Definition at line 769 of file fluid_dynamics_matrix_free_operators.cc.
get_refinement_edges()
template<int dim, typename number > IndexSet NavierStokesOperatorBase< dim, number >::get_refinement_edges (const MatrixFree< dim, number > & matrix_free) static private
Get the refinement edges. Only needed if the local smoothing multigrid approach is used.
Parameters
[in] matrix_free Object that contains all data.
Returns
Set containing the indices of the refinement edges.
Definition at line 1365 of file fluid_dynamics_matrix_free_operators.cc.
get_sparsity_pattern()
template<int dim, typename number > const DynamicSparsityPattern & NavierStokesOperatorBase< dim, number >::get_sparsity_pattern () const
Return sparsity pattern used to set up the sparse matrix by get_system_matrix().
Returns
Sparsity pattern.
Definition at line 568 of file fluid_dynamics_matrix_free_operators.cc.
get_system_matrix()
template<int dim, typename number > const TrilinosWrappers::SparseMatrix & NavierStokesOperatorBase< dim, number >::get_system_matrix () const
Calculate matrix if needed, e.g., by coarse-grid solver when a multigrid algorithm is used.
Returns
Trilinos sparse matrix.
Definition at line 577 of file fluid_dynamics_matrix_free_operators.cc.
get_system_matrix_free()
template<int dim, typename number > const MatrixFree< dim, number > & NavierStokesOperatorBase< dim, number >::get_system_matrix_free () const
Get the system matrix free object.
Returns
Matrix free object.
Definition at line 762 of file fluid_dynamics_matrix_free_operators.cc.
get_vector_partitioner()
template<int dim, typename number > const std::shared_ptr< const Utilities::MPI::Partitioner > & NavierStokesOperatorBase< dim, number >::get_vector_partitioner () const
Get the vector partitioner object required for local smoothing multigrid preconditioner.
Returns
Pointer to vector partitioner.
Definition at line 412 of file fluid_dynamics_matrix_free_operators.cc.
initialize_dof_vector()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::initialize_dof_vector (VectorType & vec) const
Initialize a given vector by delegating it to the MatrixFree function in charge of this task.
Parameters
[in,out] vec Vector to be initialized.
Definition at line 404 of file fluid_dynamics_matrix_free_operators.cc.
local_evaluate_residual()
template<int dim, typename number > virtual void NavierStokesOperatorBase< dim, number >::local_evaluate_residual (const MatrixFree< dim, number > & matrix_free, VectorType & dst, const VectorType & src, const std::pair< unsigned int, unsigned int > & range) const protected pure virtual
Interface to function in charge of computing the residual using a cell integral in a cell batch with gathering and scattering values. Should be overriden by derived classes.
Parameters
[in] matrix_free Object that contains all data.
[in,out] dst Global vector where the final result is added.
[in] src Input vector with all values in all cells.
[in] range Range of the cell batch.
Implemented in VANSOperator< dim, number >, NavierStokesStabilizedOperator< dim, number >, and NavierStokesNonNewtonianStabilizedOperator< dim, number >.
m()
template<int dim, typename number > types::global_dof_index NavierStokesOperatorBase< dim, number >::m () const
Get the total number of DoFs.
Returns
Total number of degrees of freedom.
Definition at line 378 of file fluid_dynamics_matrix_free_operators.cc.
reinit()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::reinit (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const AffineConstraints< number > & constraints, const Quadrature< dim > & quadrature, const std::shared_ptr< Function< dim > > forcing_function, const std::shared_ptr< PhysicalPropertiesManager > & physical_properties_manager, const StabilizationType stabilization, const unsigned int mg_level, const std::shared_ptr< SimulationControl > & simulation_control, const BoundaryConditions::NSBoundaryConditions< dim > & boundary_conditions, const bool & enable_hessians_jacobian, const bool & enable_hessians_residual)
Initialize the main matrix free object that contains all data and is needed to perform loops over cells, and initialize relevant member variables such as parameters and element size. Calculate edge constraints in case the local smoothing multigrid is used.
Parameters
[in] mapping Describes the transformations from unit to real cell.
[in] dof_handler Describes the layout of DoFs and the type of FE.
[in] constraints Object with constraints according to DoFs.
[in] quadrature Required for local operations on cells.
[in] forcing_function Function specified in parameter file as source term.
[in] properties_manager The physical properties manager (see physical_properties_manager.h)
[in] stabilization Stabilization type specified in parameter file.
[in] mg_level Level of the operator in case of MG methods.
[in] simulation_control Required to get the time stepping method.
[in] boundary_conditions Contains information regarding all boundary conditions. Required to weakly impose boundary conditions.
[in] enable_hessians_jacobian Flag to turn hessian terms from jacobian on or off.
[in] enable_hessians_residual Flag to turn hessian terms from residual on or off.
Definition at line 108 of file fluid_dynamics_matrix_free_operators.cc.
References create_bool_dof_mask(), BoundaryConditions::function_weak, Parameters::Stabilization::gls, BoundaryConditions::outlet, Parameters::Stabilization::pspg_supg, and BoundaryConditions::BoundaryConditions::type.
Tvmult()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::Tvmult (VectorType & dst, const VectorType & src) const
Perform the transposed operator evaluation.
Parameters
[in,out] dst Destination vector holding the result.
[in] src Input source vector.
Definition at line 473 of file fluid_dynamics_matrix_free_operators.cc.
update_beta_force()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::update_beta_force (const Tensor< 1, dim > & beta_force)
Store the values of the source term calculated if dynamic control is enabled in the appropriate structure.
Parameters
[in] beta_force Source term calculated by the dynamic flow control.
Definition at line 1091 of file fluid_dynamics_matrix_free_operators.cc.
vmult()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::vmult (VectorType & dst, const VectorType & src) const
Perform an operator evaluation dst = A*src by looping with the help of the MatrixFree object over all cells and evaluating the effect of cell integrals.
Parameters
[in,out] dst Destination vector holding the result.
[in] src Input source vector.
Definition at line 419 of file fluid_dynamics_matrix_free_operators.cc.
References NavierStokesOperatorBase< dim, number >::do_cell_integral_range(), and NavierStokesOperatorBase< dim, number >::do_internal_face_integral_range().
vmult_interface_down()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::vmult_interface_down (VectorType & dst, VectorType const & src) const
Vmult operator for an interface. Required only if local smoothing multigrid is used and for meshes with hanging nodes.
Parameters
[in,out] dst Destination vector holding the result.
[in] src Input source vector.
Definition at line 481 of file fluid_dynamics_matrix_free_operators.cc.
References NavierStokesOperatorBase< dim, number >::do_cell_integral_range(), and NavierStokesOperatorBase< dim, number >::do_internal_face_integral_range().
vmult_interface_up()
template<int dim, typename number > void NavierStokesOperatorBase< dim, number >::vmult_interface_up (VectorType & dst, VectorType const & src) const
Vmult operator for an interface. Required only if local smoothing multigrid is used and for meshes with hanging nodes.
Parameters
[in,out] dst Destination vector holding the result.
[in] src Input source vector.
Definition at line 513 of file fluid_dynamics_matrix_free_operators.cc.
References NavierStokesOperatorBase< dim, number >::do_cell_integral_range(), and NavierStokesOperatorBase< dim, number >::do_internal_face_integral_range().
Member Data Documentation
beta_force
template<int dim, typename number > Tensor<1, dim, VectorizedArray<number> > NavierStokesOperatorBase< dim, number >::beta_force protected
Additional source term in the case of dynamic flow control.
Definition at line 560 of file fluid_dynamics_matrix_free_operators.h.
bool_dof_mask
template<int dim, typename number > Table<2, bool> NavierStokesOperatorBase< dim, number >::bool_dof_mask protected
DoF mask object needed for the sparsity pattern and computation of the system matrix of the coarse level in case FE_Q_iso_Q1 elements are used.
Definition at line 774 of file fluid_dynamics_matrix_free_operators.h.
boundary_conditions
template<int dim, typename number > BoundaryConditions::NSBoundaryConditions<dim> NavierStokesOperatorBase< dim, number >::boundary_conditions protected
Boundary conditions object to impose the correct boundary conditions. This object is only used to impose boundary conditions that appear in the weak form as face terms (Weak Dirichlet boundary conditions and, eventually, outlets). However, the entire boundary_conditions object is stored instead of trying to isolate which parameters are used since many of them are used in the initialization of the boundary conditions.
Definition at line 589 of file fluid_dynamics_matrix_free_operators.h.
buoyancy_term
template<int dim, typename number > Table<2, Tensor<1, dim, VectorizedArray<number> > > NavierStokesOperatorBase< dim, number >::buoyancy_term protected
Table with precomputed buoyancy term values.
Definition at line 614 of file fluid_dynamics_matrix_free_operators.h.
constrained_indices
template<int dim, typename number > std::vector<unsigned int> NavierStokesOperatorBase< dim, number >::constrained_indices protected
Vector with the constrained indices used for the local smoothing approach.
Definition at line 734 of file fluid_dynamics_matrix_free_operators.h.
constrained_values
template<int dim, typename number > std::vector<std::pair<number, number> > NavierStokesOperatorBase< dim, number >::constrained_values mutable protected
Vector with the constrained values used for the local smoothing approach.
Definition at line 740 of file fluid_dynamics_matrix_free_operators.h.
constraints
template<int dim, typename number > AffineConstraints<number> NavierStokesOperatorBase< dim, number >::constraints protected
Object that stores constraints for the matrix free implementation.
Definition at line 523 of file fluid_dynamics_matrix_free_operators.h.
dsp
template<int dim, typename number > DynamicSparsityPattern NavierStokesOperatorBase< dim, number >::dsp mutable protected
Sparsity pattern used when the matrix of certain level is computed and stored.
Definition at line 529 of file fluid_dynamics_matrix_free_operators.h.
edge_constrained_cell
template<int dim, typename number > std::vector<bool> NavierStokesOperatorBase< dim, number >::edge_constrained_cell protected
Vector used to mark edge constrained cells in order to verify constrained indices for the local smoothing approach.
Definition at line 767 of file fluid_dynamics_matrix_free_operators.h.
edge_constrained_indices
template<int dim, typename number > std::vector<unsigned int> NavierStokesOperatorBase< dim, number >::edge_constrained_indices protected
Vector with the constrained edge indices for the local smoothing approach.
Definition at line 746 of file fluid_dynamics_matrix_free_operators.h.
edge_constrained_values
template<int dim, typename number > std::vector<number> NavierStokesOperatorBase< dim, number >::edge_constrained_values mutable protected
Vector with edge constrained values used for the local smoothing approach.
Definition at line 759 of file fluid_dynamics_matrix_free_operators.h.
effective_beta_face
template<int dim, typename number > Table<1, VectorizedArray<number> > NavierStokesOperatorBase< dim, number >::effective_beta_face protected
Table with correct alignment for vectorization to store the values of the face penalization term effective_beta_face.
Definition at line 728 of file fluid_dynamics_matrix_free_operators.h.
element_size
template<int dim, typename number > AlignedVector<VectorizedArray<number> > NavierStokesOperatorBase< dim, number >::element_size protected
Aligned vector to store the element size of all the elements.
Definition at line 542 of file fluid_dynamics_matrix_free_operators.h.
enable_face_terms
template<int dim, typename number > bool NavierStokesOperatorBase< dim, number >::enable_face_terms protected
Flag to turn the calculation of face terms on or off. This is used for weakly imposed Dirichlet boundary conditions or outlets.
Definition at line 621 of file fluid_dynamics_matrix_free_operators.h.
enable_hessians_jacobian
template<int dim, typename number > bool NavierStokesOperatorBase< dim, number >::enable_hessians_jacobian protected
Flag to turn hessian terms from jacobian on or off.
Definition at line 595 of file fluid_dynamics_matrix_free_operators.h.
enable_hessians_residual
template<int dim, typename number > bool NavierStokesOperatorBase< dim, number >::enable_hessians_residual protected
Flag to turn hessian terms from residual on or off.
Definition at line 601 of file fluid_dynamics_matrix_free_operators.h.
face_nonlinear_previous_values
template<int dim, typename number > Table<2, Tensor<1, dim + 1, VectorizedArray<number> > > NavierStokesOperatorBase< dim, number >::face_nonlinear_previous_values protected
Table with correct alignment for vectorization to store the values of the velocity at faces.
Definition at line 661 of file fluid_dynamics_matrix_free_operators.h.
face_target_velocity
template<int dim, typename number > Table<2, Tensor<1, dim, VectorizedArray<number> > > NavierStokesOperatorBase< dim, number >::face_target_velocity protected
Table with correct alignment for vectorization to store the values of the target velocity of a weakly imposed Dirichlet boundary condition.
Definition at line 668 of file fluid_dynamics_matrix_free_operators.h.
fe_degree
template<int dim, typename number > unsigned int NavierStokesOperatorBase< dim, number >::fe_degree protected
Finite element degree for the operator.
Definition at line 548 of file fluid_dynamics_matrix_free_operators.h.
forcing_function
template<int dim, typename number > std::shared_ptr<Function<dim> > NavierStokesOperatorBase< dim, number >::forcing_function protected
Force function or source function for the Navier-Stokes equations.
Definition at line 554 of file fluid_dynamics_matrix_free_operators.h.
forcing_terms
template<int dim, typename number > Table<2, Tensor<1, dim, VectorizedArray<number> > > NavierStokesOperatorBase< dim, number >::forcing_terms protected
Table with precomputed forcing term values.
Definition at line 607 of file fluid_dynamics_matrix_free_operators.h.
grad_kinematic_viscosity_shear_rate
template<int dim, typename number > Table<2, VectorizedArray<number> > NavierStokesOperatorBase< dim, number >::grad_kinematic_viscosity_shear_rate protected
Table with correct alignment for vectorization to store the values of the gradient of the kinematic viscosity w.r.t shear rate.
Definition at line 698 of file fluid_dynamics_matrix_free_operators.h.
has_edge_constrained_indices
template<int dim, typename number > bool NavierStokesOperatorBase< dim, number >::has_edge_constrained_indices = false protected
Variable to identify whether there are edge constrained indices for the local smoothing approach.
Definition at line 753 of file fluid_dynamics_matrix_free_operators.h.
kinematic_viscosity_gradient
template<int dim, typename number > Table<2, Tensor<1, dim + 1, VectorizedArray<number> > > NavierStokesOperatorBase< dim, number >::kinematic_viscosity_gradient protected
Table with correct alignment for vectorization to store the values of the kinematic viscosity gradient.
Definition at line 706 of file fluid_dynamics_matrix_free_operators.h.
kinematic_viscosity_vector
template<int dim, typename number > Table<2, VectorizedArray<number> > NavierStokesOperatorBase< dim, number >::kinematic_viscosity_vector protected
Table with correct alignment for vectorization to store the values of the kinematic viscosity.
Definition at line 691 of file fluid_dynamics_matrix_free_operators.h.
matrix_free
template<int dim, typename number > MatrixFree<dim, number> NavierStokesOperatorBase< dim, number >::matrix_free protected
Object storing all the relevant data needed for the matrix free implementation.
Definition at line 517 of file fluid_dynamics_matrix_free_operators.h.
nonlinear_previous_gradient
template<int dim, typename number > Table<2, Tensor<1, dim + 1, Tensor<1, dim, VectorizedArray<number> > > > NavierStokesOperatorBase< dim, number >::nonlinear_previous_gradient protected
Table with correct alignment for vectorization to store the gradients of the previous newton step.
Definition at line 637 of file fluid_dynamics_matrix_free_operators.h.
nonlinear_previous_hessian_diagonal
template<int dim, typename number > Table<2, Tensor<1, dim + 1, Tensor<1, dim, VectorizedArray<number> > > > NavierStokesOperatorBase< dim, number >::nonlinear_previous_hessian_diagonal protected
Table with correct alignment for vectorization to store the hessian diagonal of the previous newton step.
Definition at line 645 of file fluid_dynamics_matrix_free_operators.h.
nonlinear_previous_values
template<int dim, typename number > Table<2, Tensor<1, dim + 1, VectorizedArray<number> > > NavierStokesOperatorBase< dim, number >::nonlinear_previous_values protected
Table with correct alignment for vectorization to store the values of the previous newton step.
Definition at line 629 of file fluid_dynamics_matrix_free_operators.h.
pcout
template<int dim, typename number > ConditionalOStream NavierStokesOperatorBase< dim, number >::pcout protected
Conditional OStream for parallel output.
Definition at line 780 of file fluid_dynamics_matrix_free_operators.h.
previous_shear_rate
template<int dim, typename number > Table<2, Tensor<1, dim + 1, Tensor<1, dim, VectorizedArray<number> > > > NavierStokesOperatorBase< dim, number >::previous_shear_rate protected
Table with correct alignment for vectorization to store the values of the shear_rate.
Definition at line 714 of file fluid_dynamics_matrix_free_operators.h.
previous_shear_rate_magnitude
template<int dim, typename number > Table<2, VectorizedArray<number> > NavierStokesOperatorBase< dim, number >::previous_shear_rate_magnitude protected
Table with correct alignment for vectorization to store the values of the shear_rate_magnitude.
Definition at line 721 of file fluid_dynamics_matrix_free_operators.h.
properties_manager
template<int dim, typename number > std::shared_ptr<PhysicalPropertiesManager> NavierStokesOperatorBase< dim, number >::properties_manager protected
Object pointing to the physical properties manager of the matrix free class.
Definition at line 578 of file fluid_dynamics_matrix_free_operators.h.
simulation_control
template<int dim, typename number > std::shared_ptr<SimulationControl> NavierStokesOperatorBase< dim, number >::simulation_control protected
Object storing the information regarding the time stepping method.
Definition at line 572 of file fluid_dynamics_matrix_free_operators.h.
stabilization
template<int dim, typename number > StabilizationType NavierStokesOperatorBase< dim, number >::stabilization protected
Stabilization type needed to add or remove terms from operator.
Definition at line 566 of file fluid_dynamics_matrix_free_operators.h.
stabilization_parameter
template<int dim, typename number > Table<2, VectorizedArray<number> > NavierStokesOperatorBase< dim, number >::stabilization_parameter protected
Table with correct alignment for vectorization to store the values of the stabilization parameter tau.
Definition at line 676 of file fluid_dynamics_matrix_free_operators.h.
stabilization_parameter_lsic
template<int dim, typename number > Table<2, VectorizedArray<number> > NavierStokesOperatorBase< dim, number >::stabilization_parameter_lsic protected
Table with correct alignment for vectorization to store the values of the stabilization parameter tau lsic.
Definition at line 683 of file fluid_dynamics_matrix_free_operators.h.
system_matrix
template<int dim, typename number > TrilinosWrappers::SparseMatrix NavierStokesOperatorBase< dim, number >::system_matrix mutable protected
Sparse trilinos matrix used when the matrix of certain level is computed and stored.
Definition at line 536 of file fluid_dynamics_matrix_free_operators.h.
time_derivatives_previous_solutions
template<int dim, typename number > Table<2, Tensor<1, dim + 1, VectorizedArray<number> > > NavierStokesOperatorBase< dim, number >::time_derivatives_previous_solutions protected
Table with correct alignment for vectorization to store the time derivatives of previous solutions.
Definition at line 653 of file fluid_dynamics_matrix_free_operators.h.
timer
template<int dim, typename number > TimerOutput NavierStokesOperatorBase< dim, number >::timer mutable
Timer for internal operator calls.
Definition at line 787 of file fluid_dynamics_matrix_free_operators.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/fluid_dynamics_matrix_free_operators.h
/home/runner/work/lethe/lethe/source/solvers/fluid_dynamics_matrix_free_operators.cc