Lethe Open-Source Library: SimulationControlSteady Class Reference
SimulationControlSteady Class Reference
#include <simulation_control.h>
Public Member Functions
SimulationControlSteady (const Parameters::SimulationControl &param)
virtual void print_progression (const ConditionalOStream &pcout) override
virtual bool integrate () override
virtual bool is_at_end () override
Public Member Functions inherited from SimulationControl
SimulationControl (const Parameters::SimulationControl &param)
virtual ~SimulationControl ()=default
void add_time_step (double p_timestep)
bool is_at_start ()
bool is_steady ()
bool is_bdf ()
bool is_sdirk ()
virtual double calculate_time_step ()
bool output_enabled () const
virtual bool is_output_iteration ()
bool get_output_boundaries ()
virtual bool is_verbose_iteration ()
virtual bool is_first_assembly ()
void update_assembly_method ()
void set_CFL (const double p_CFL)
void set_current_time_step (const double new_time_step)
void set_suggested_time_step (const double new_time_step)
void provide_residual (const double new_residual)
double get_time_step () const
unsigned int get_iteration_number () const
std::string get_output_name () const
std::string get_output_path () const
unsigned int get_group_files () const
unsigned int get_log_precision () const
double get_current_time () const
double get_previous_time () const
std::vector< double > get_time_steps_vector () const
double get_CFL () const
unsigned int get_step_number () const
unsigned int get_number_subdivision () const
unsigned int get_log_frequency () const
Parameters::SimulationControl::TimeSteppingMethod get_assembly_method () const
void set_assembly_method (Parameters::SimulationControl::TimeSteppingMethod method)
unsigned int get_number_of_previous_solution_in_assembly () const
std::vector< double > get_simulation_times () const
Vector< double > const & get_bdf_coefficients ()
virtual void save (const std::string &prefix)
virtual void read (const std::string &prefix)
std::vector< double > get_checkpointed_simulation_control_info (const std::string &prefix)
Additional Inherited Members
Static Public Member Functions inherited from SimulationControl
static unsigned int get_number_of_stages (const Parameters::SimulationControl::TimeSteppingMethod &method)
Protected Member Functions inherited from SimulationControl
void update_bdf_coefficients ()
Protected Attributes inherited from SimulationControl
Parameters::SimulationControl::TimeSteppingMethod method
Parameters::SimulationControl::TimeSteppingMethod assembly_method
double current_time
double previous_time
double time_step
double initial_time_step
double end_time
bool time_step_independent_of_end_time
std::vector< double > time_step_vector
unsigned int iteration_number
unsigned int number_mesh_adapt
double CFL
double max_CFL
double residual
double stop_tolerance
unsigned int output_iteration_frequency
unsigned int log_frequency
unsigned int log_precision
unsigned int subdivision
unsigned int group_files
std::string output_name
std::string output_path
bool output_boundaries
bool first_assembly
Parameters::SimulationControl::BDFStartupMethods bdf_start_method
double startup_timestep_scaling
Vector< double > bdf_coefs
Static Protected Attributes inherited from SimulationControl
static const unsigned int n_previous_time_steps = 4
Detailed Description
Definition at line 637 of file simulation_control.h.
Constructor & Destructor Documentation
SimulationControlSteady()
SimulationControlSteady::SimulationControlSteady (const Parameters::SimulationControl & param)
Definition at line 513 of file simulation_control.cc.
Member Function Documentation
integrate()
bool SimulationControlSteady::integrate () override virtual
Proceeds with the simulation until the end condition is reached.
Implements SimulationControl.
Definition at line 519 of file simulation_control.cc.
References SimulationControl::current_time, is_at_end(), SimulationControl::iteration_number, and SimulationControl::previous_time.
is_at_end()
bool SimulationControlSteady::is_at_end () override virtual
Ends the simulation when the number of mesh adaptation is reached.
Implements SimulationControl.
Definition at line 553 of file simulation_control.cc.
References SimulationControl::iteration_number, and SimulationControl::number_mesh_adapt.
print_progression()
void SimulationControlSteady::print_progression (const ConditionalOStream & pcout) override virtual
print_progress Function that prints the current progress status of the simulation
Parameters
[in] pcout the ConditionalOSStream that is use to write
Implements SimulationControl.
Definition at line 536 of file simulation_control.cc.
References announce_string(), SimulationControl::is_verbose_iteration(), SimulationControl::iteration_number, and SimulationControl::number_mesh_adapt.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/simulation_control.h
/home/runner/work/lethe/lethe/source/core/simulation_control.cc