Lethe Open-Source Library: SerialSolid< dim, spacedim > Class Template Reference
SerialSolid< dim, spacedim > Class Template Reference
#include <serial_solid.h>
Public Member Functions
SerialSolid (std::shared_ptr< Parameters::RigidSolidObject< spacedim > > &param, unsigned int id)
std::vector< std::pair< typename Triangulation< spacedim >::active_cell_iterator, typename Triangulation< dim, spacedim >::active_cell_iterator > > map_solid_in_background_triangulation (const parallel::TriangulationBase< spacedim > &background_tr)
void initial_setup ()
void setup_triangulation (const bool restart)
void setup_dof_handler ()
std::shared_ptr< Triangulation< dim, spacedim > > get_triangulation ()
DoFHandler< dim, spacedim > & get_dof_handler ()
Vector< double > & get_displacement_vector ()
double get_max_displacement_since_mapped () const
Tensor< 1, 3 > get_translational_velocity () const
Tensor< 1, 3 > get_angular_velocity () const
Point< 3 > get_center_of_rotation () const
double get_temperature () const
Parameters::ThermalBoundaryType get_thermal_boundary_type () const
unsigned int get_solid_id () const
void update_solid_temperature (const double initial_time)
void move_solid_triangulation (double time_step, double initial_time)
void write_output_results (const std::shared_ptr< SimulationControl > &simulation_control)
void read_checkpoint (const std::string &prefix_name)
void write_checkpoint (const std::string &prefix_name)
Private Member Functions
void displace_solid_triangulation ()
void reset_displacement_monitoring ()
void move_solid_triangulation_with_displacement ()
void rotate_grid (const double angle, const Tensor< 1, 3 > &axis)
void translate_grid (const Tensor< 1, 3 > &translate)
void rotate_grid (const double angle, const Tensor< 1, 3 > &axis)
void rotate_grid (const double angle, const Tensor< 1, 3 > &axis)
void rotate_grid (const double angle, const Tensor< 1, 3 > &axis)
void rotate_grid (const double angle, const Tensor< 1, 3 > &axis)
void translate_grid (const Tensor< 1, 3 > &translation)
void translate_grid (const Tensor< 1, 3 > &translation)
void translate_grid (const Tensor< 1, 3 > &translation)
void translate_grid (const Tensor< 1, 3 > &translation)
Private Attributes
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< Parameters::RigidSolidObject< spacedim > > & param
unsigned int id
std::shared_ptr< Triangulation< dim, spacedim > > solid_tria
std::shared_ptr< FiniteElement< dim, spacedim > > fe
std::shared_ptr< Mapping< dim, spacedim > > solid_mapping
DoFHandler< dim, spacedim > displacement_dh
std::shared_ptr< FESystem< dim, spacedim > > displacement_fe
Vector< double > displacement
Vector< double > displacement_since_mapped
PVDHandler pvdhandler
const bool output_bool
std::shared_ptr< Function< spacedim > > translational_velocity
std::shared_ptr< Function< spacedim > > angular_velocity
Point< spacedim > center_of_rotation
Tensor< 1, spacedim > current_translational_velocity
Tensor< 1, 3 > current_angular_velocity
std::shared_ptr< Function< spacedim > > solid_temperature
Parameters::ThermalBoundaryType thermal_boundary_type
double current_solid_temperature
Detailed Description
template<int dim, int spacedim = dim>
class SerialSolid< dim, spacedim >
A class that generates an object to manage a serial triangulation that represents a solid object. This class can represent solid objects for which the dimension do not match the spatial dimension. For example, a 2D surface defined in 3D or a line defined in 2D.
Template Parameters
dim An integer that denotes the dimensionality of the geometry
spacedim An integer that denotes the dimension of the space occupied by the embedded solid
Definition at line 35 of file serial_solid.h.
Constructor & Destructor Documentation
SerialSolid()
template<int dim, int spacedim> SerialSolid< dim, spacedim >::SerialSolid (std::shared_ptr< Parameters::RigidSolidObject< spacedim > > & param, unsigned int id)
Definition at line 23 of file serial_solid.cc.
References SerialSolid< dim, spacedim >::displacement_dh, SerialSolid< dim, spacedim >::displacement_fe, SerialSolid< dim, spacedim >::fe, SerialSolid< dim, spacedim >::initial_setup(), SerialSolid< dim, spacedim >::param, SerialSolid< dim, spacedim >::solid_mapping, and SerialSolid< dim, spacedim >::solid_tria.
Member Function Documentation
displace_solid_triangulation()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::displace_solid_triangulation () private
Moves the dofs of the solid_triangulation by using the displacement vector. This is only used to move the solid triangulation at the correct location when the simulation is restarted.
Definition at line 405 of file serial_solid.cc.
get_angular_velocity()
template<int dim, int spacedim = dim> Tensor< 1, 3 > SerialSolid< dim, spacedim >::get_angular_velocity () const inline
Returns the angular velocity of the center of mass of the solid object.
Returns
The angular velocity of the solid object
Definition at line 125 of file serial_solid.h.
References SerialSolid< dim, spacedim >::current_angular_velocity.
get_center_of_rotation()
template<int dim, int spacedim = dim> Point< 3 > SerialSolid< dim, spacedim >::get_center_of_rotation () const inline
Returns the center of rotation of the center of mass of the solid object.
Returns
The center of rotation of the solid object
Definition at line 136 of file serial_solid.h.
References SerialSolid< dim, spacedim >::center_of_rotation, and point_nd_to_3d().
get_displacement_vector()
template<int dim, int spacedim> Vector< double > & SerialSolid< dim, spacedim >::get_displacement_vector ()
Returns the displacement vector of all the vertices of the solid object.
Returns
the reference to the displacement vector
Definition at line 237 of file serial_solid.cc.
get_dof_handler()
template<int dim, int spacedim> DoFHandler< dim, spacedim > & SerialSolid< dim, spacedim >::get_dof_handler ()
Returns the dof_handler associated with the displacement of the solid object.
Returns
the reference to the displacement dof handler
Definition at line 229 of file serial_solid.cc.
get_max_displacement_since_mapped()
template<int dim, int spacedim> double SerialSolid< dim, spacedim >::get_max_displacement_since_mapped () const
Calculates the max displacement of the solid object. The max displacement is defined as the L^\infty norm of the displacement components. This is a measure of the maximal displacement in any direction.
Returns
The reference to the vector of the displacement since the mapping
Definition at line 244 of file serial_solid.cc.
get_solid_id()
template<int dim, int spacedim = dim> unsigned int SerialSolid< dim, spacedim >::get_solid_id () const inline
Returns the solid id of the solid object. This ID is an unsigned integer which is given to the solid object at compile time and is mostly used when writing files.
Returns
id of the solid
Definition at line 175 of file serial_solid.h.
References SerialSolid< dim, spacedim >::id.
get_temperature()
template<int dim, int spacedim = dim> double SerialSolid< dim, spacedim >::get_temperature () const inline
Returns the temperature of the solid object.
Returns
The temperature of the solid object
Definition at line 151 of file serial_solid.h.
References SerialSolid< dim, spacedim >::current_solid_temperature.
get_thermal_boundary_type()
template<int dim, int spacedim = dim> Parameters::ThermalBoundaryType SerialSolid< dim, spacedim >::get_thermal_boundary_type () const inline
Returns the thermal boundary type of the solid object.
Returns
The thermal boundary type of the solid object
Definition at line 162 of file serial_solid.h.
References SerialSolid< dim, spacedim >::thermal_boundary_type.
get_translational_velocity()
template<int dim, int spacedim = dim> Tensor< 1, 3 > SerialSolid< dim, spacedim >::get_translational_velocity () const inline
Returns translational velocity of the center of mass of the solid object.
Returns
The translational velocity of the solid object
Definition at line 110 of file serial_solid.h.
References SerialSolid< dim, spacedim >::current_translational_velocity, and tensor_nd_to_3d().
get_triangulation()
template<int dim, int spacedim> std::shared_ptr< Triangulation< dim, spacedim > > SerialSolid< dim, spacedim >::get_triangulation ()
Returns the shared pointer to the solid object triangulation.
Returns
shared_ptr of the solid triangulation
Definition at line 251 of file serial_solid.cc.
initial_setup()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::initial_setup ()
Manages solid triangulation setup.
Definition at line 144 of file serial_solid.cc.
map_solid_in_background_triangulation()
template<int dim, int spacedim> std::vector< std::pair< typename Triangulation< spacedim >::active_cell_iterator, typename Triangulation< dim, spacedim >::active_cell_iterator > > SerialSolid< dim, spacedim >::map_solid_in_background_triangulation (const parallel::TriangulationBase< spacedim > & background_tr)
Maps the solid object in the background triangulation.
Definition at line 76 of file serial_solid.cc.
References LetheGridTools::find_point_triangle_distance().
move_solid_triangulation()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::move_solid_triangulation (double time_step, double initial_time)
Moves the vertices of the solid triangulation. This function uses explicitEuler scheme time integrator to displace the vertices of the solid triangulation and stores the displacement in an array in order to allow correct checkpointing of the triangulation.
Parameters
time_step The time_step value for this iteration
initial_time The initial time (time t) of the timestep. This is used to set the time of the velocity function.
Definition at line 326 of file serial_solid.cc.
move_solid_triangulation_with_displacement()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::move_solid_triangulation_with_displacement () private
Moves the vertices of the solid triangulation using the displacement vector. This is mostly used when restarting simulations which contain a serial solid in order to replace it at the position it was when the simulation finished.
Definition at line 439 of file serial_solid.cc.
read_checkpoint()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::read_checkpoint (const std::string & prefix_name)
read solid base triangulation checkpoint and replaces the triangulation at the location where it was when it was checkpointed
Parameters
prefix_name The prefix of the checkpoint of the simulation
Definition at line 570 of file serial_solid.cc.
reset_displacement_monitoring()
template<int dim, int spacedim = dim> void SerialSolid< dim, spacedim >::reset_displacement_monitoring () inline private
Reset displacements since intersection for contact detection.
Definition at line 244 of file serial_solid.h.
References SerialSolid< dim, spacedim >::displacement_since_mapped.
rotate_grid() [1/5]
template<int dim, int spacedim = dim> void SerialSolid< dim, spacedim >::rotate_grid (const double angle, const Tensor< 1, 3 > & axis) private
Rotates the grid by a given angle around an axis.
Parameters
angle The angle (in rad) with which the solid is rotated
axis The axis over which the solid is rotated.
rotate_grid() [2/5]
void SerialSolid< 1, 2 >::rotate_grid (const double angle, const Tensor< 1, 3 > & axis) private
Definition at line 258 of file serial_solid.cc.
rotate_grid() [3/5]
void SerialSolid< 2, 2 >::rotate_grid (const double angle, const Tensor< 1, 3 > & axis) private
Definition at line 266 of file serial_solid.cc.
rotate_grid() [4/5]
void SerialSolid< 2, 3 >::rotate_grid (const double angle, const Tensor< 1, 3 > & axis) private
Definition at line 274 of file serial_solid.cc.
rotate_grid() [5/5]
void SerialSolid< 3, 3 >::rotate_grid (const double angle, const Tensor< 1, 3 > & axis) private
Definition at line 280 of file serial_solid.cc.
setup_dof_handler()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::setup_dof_handler ()
Set-ups the displacement vector to store the motion of the triangulation.
Definition at line 600 of file serial_solid.cc.
setup_triangulation()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::setup_triangulation (const bool restart)
Generates a solid triangulation from a dealii or gmsh mesh.
Parameters
restart Boolean variable that indicates if the simulation is being restarted
Definition at line 156 of file serial_solid.cc.
References Parameters::Mesh::dealii, and Parameters::Mesh::gmsh.
translate_grid() [1/5]
template<int dim, int spacedim = dim> void SerialSolid< dim, spacedim >::translate_grid (const Tensor< 1, 3 > & translate) private
Translate the grid. In spacedim=2, the third component is ignore.
Parameters
translate The vector with which the solid is translated.
translate_grid() [2/5]
void SerialSolid< 1, 2 >::translate_grid (const Tensor< 1, 3 > & translation) private
Definition at line 287 of file serial_solid.cc.
translate_grid() [3/5]
void SerialSolid< 2, 2 >::translate_grid (const Tensor< 1, 3 > & translation) private
Definition at line 294 of file serial_solid.cc.
translate_grid() [4/5]
void SerialSolid< 2, 3 >::translate_grid (const Tensor< 1, 3 > & translation) private
Definition at line 301 of file serial_solid.cc.
translate_grid() [5/5]
void SerialSolid< 3, 3 >::translate_grid (const Tensor< 1, 3 > & translation) private
Definition at line 308 of file serial_solid.cc.
update_solid_temperature()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::update_solid_temperature (const double initial_time)
Update the temperature of the solid object, which is a function of time.
Parameters
initial_time The initial time (time t) of the timestep. This is used to set the time of the temperature function.
Definition at line 315 of file serial_solid.cc.
References Parameters::adiabatic.
write_checkpoint()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::write_checkpoint (const std::string & prefix_name)
write solid base triangulation checkpoint
Parameters
prefix_name The prefix of the checkpoint of the simulation
Definition at line 544 of file serial_solid.cc.
write_output_results()
template<int dim, int spacedim> void SerialSolid< dim, spacedim >::write_output_results (const std::shared_ptr< SimulationControl > & simulation_control)
Write the output file of the solid object triangulation.
Parameters
simulation_control The simulation control object
Definition at line 474 of file serial_solid.cc.
Member Data Documentation
angular_velocity
template<int dim, int spacedim = dim> std::shared_ptr<Function<spacedim> > SerialSolid< dim, spacedim >::angular_velocity private
Definition at line 305 of file serial_solid.h.
center_of_rotation
template<int dim, int spacedim = dim> Point<spacedim> SerialSolid< dim, spacedim >::center_of_rotation private
Definition at line 306 of file serial_solid.h.
current_angular_velocity
template<int dim, int spacedim = dim> Tensor<1, 3> SerialSolid< dim, spacedim >::current_angular_velocity private
Definition at line 308 of file serial_solid.h.
current_solid_temperature
template<int dim, int spacedim = dim> double SerialSolid< dim, spacedim >::current_solid_temperature private
Definition at line 311 of file serial_solid.h.
current_translational_velocity
template<int dim, int spacedim = dim> Tensor<1, spacedim> SerialSolid< dim, spacedim >::current_translational_velocity private
Definition at line 307 of file serial_solid.h.
displacement
template<int dim, int spacedim = dim> Vector<double> SerialSolid< dim, spacedim >::displacement private
Definition at line 296 of file serial_solid.h.
displacement_dh
template<int dim, int spacedim = dim> DoFHandler<dim, spacedim> SerialSolid< dim, spacedim >::displacement_dh private
Definition at line 294 of file serial_solid.h.
displacement_fe
template<int dim, int spacedim = dim> std::shared_ptr<FESystem<dim, spacedim> > SerialSolid< dim, spacedim >::displacement_fe private
Definition at line 295 of file serial_solid.h.
displacement_since_mapped
template<int dim, int spacedim = dim> Vector<double> SerialSolid< dim, spacedim >::displacement_since_mapped private
Definition at line 297 of file serial_solid.h.
fe
template<int dim, int spacedim = dim> std::shared_ptr<FiniteElement<dim, spacedim> > SerialSolid< dim, spacedim >::fe private
Definition at line 292 of file serial_solid.h.
id
template<int dim, int spacedim = dim> unsigned int SerialSolid< dim, spacedim >::id private
Definition at line 288 of file serial_solid.h.
mpi_communicator
template<int dim, int spacedim = dim> MPI_Comm SerialSolid< dim, spacedim >::mpi_communicator private
Definition at line 280 of file serial_solid.h.
n_mpi_processes
template<int dim, int spacedim = dim> const unsigned int SerialSolid< dim, spacedim >::n_mpi_processes private
Definition at line 281 of file serial_solid.h.
output_bool
template<int dim, int spacedim = dim> const bool SerialSolid< dim, spacedim >::output_bool private
Definition at line 301 of file serial_solid.h.
param
template<int dim, int spacedim = dim> std::shared_ptr<Parameters::RigidSolidObject<spacedim> >& SerialSolid< dim, spacedim >::param private
Definition at line 285 of file serial_solid.h.
pvdhandler
template<int dim, int spacedim = dim> PVDHandler SerialSolid< dim, spacedim >::pvdhandler private
Definition at line 300 of file serial_solid.h.
solid_mapping
template<int dim, int spacedim = dim> std::shared_ptr<Mapping<dim, spacedim> > SerialSolid< dim, spacedim >::solid_mapping private
Definition at line 293 of file serial_solid.h.
solid_temperature
template<int dim, int spacedim = dim> std::shared_ptr<Function<spacedim> > SerialSolid< dim, spacedim >::solid_temperature private
Definition at line 309 of file serial_solid.h.
solid_tria
template<int dim, int spacedim = dim> std::shared_ptr<Triangulation<dim, spacedim> > SerialSolid< dim, spacedim >::solid_tria private
Definition at line 291 of file serial_solid.h.
thermal_boundary_type
template<int dim, int spacedim = dim> Parameters::ThermalBoundaryType SerialSolid< dim, spacedim >::thermal_boundary_type private
Definition at line 310 of file serial_solid.h.
this_mpi_process
template<int dim, int spacedim = dim> const unsigned int SerialSolid< dim, spacedim >::this_mpi_process private
Definition at line 282 of file serial_solid.h.
translational_velocity
template<int dim, int spacedim = dim> std::shared_ptr<Function<spacedim> > SerialSolid< dim, spacedim >::translational_velocity private
Definition at line 304 of file serial_solid.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/serial_solid.h
/home/runner/work/lethe/lethe/source/core/serial_solid.cc