Lethe Open-Source Library: InexactNewtonNonLinearSolver< VectorType > Class Template Reference
InexactNewtonNonLinearSolver< VectorType > Class Template Reference
#include <inexact_newton_non_linear_solver.h>
Public Member Functions
InexactNewtonNonLinearSolver (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &param)
void solve (const bool is_initial_step) override
Public Member Functions inherited from NonLinearSolver< VectorType >
NonLinearSolver (PhysicsSolver< VectorType > *physics_solver, const Parameters::NonLinearSolver &params)
virtual ~NonLinearSolver ()
unsigned int get_current_newton_iteration () const
Private Attributes
bool matrix_requires_assembly
Additional Inherited Members
Protected Attributes inherited from NonLinearSolver< VectorType >
PhysicsSolver< VectorType > * physics_solver
Parameters::NonLinearSolver params
unsigned int outer_iteration
Detailed Description
template<typename VectorType>
class InexactNewtonNonLinearSolver< VectorType >
Non-linear solver for non-linear systems of equations which uses an inexact Newton method with \(\alpha\) relaxation to ensure that the residual is monotonically decreasing. It allows to reuse the matrix and avoid its reassembly for every Newton step.
Definition at line 19 of file inexact_newton_non_linear_solver.h.
Constructor & Destructor Documentation
InexactNewtonNonLinearSolver()
template<typename VectorType > InexactNewtonNonLinearSolver< VectorType >::InexactNewtonNonLinearSolver (PhysicsSolver< VectorType > * physics_solver, const Parameters::NonLinearSolver & param)
Constructor.
Parameters
[in] physics_solver A pointer to the physics solver to which the non-linear solver is attached.
[in] param Non-linear solver parameters as specified in the simulation parameter file.
Definition at line 51 of file inexact_newton_non_linear_solver.h.
Member Function Documentation
solve()
template<typename VectorType > void InexactNewtonNonLinearSolver< VectorType >::solve (const bool is_initial_step) override virtual
Solve the non-linear system of equations.
Parameters
[in] is_initial_step Boolean variable that controls which constraints are going to be applied to the equations depending on the time step.
Implements NonLinearSolver< VectorType >.
Definition at line 60 of file inexact_newton_non_linear_solver.h.
References PhysicsSolver< VectorType >::apply_constraints(), PhysicsSolver< VectorType >::assemble_system_matrix(), PhysicsSolver< VectorType >::assemble_system_rhs(), PhysicsSolver< VectorType >::get_current_residual(), PhysicsSolver< VectorType >::get_evaluation_point(), PhysicsSolver< VectorType >::get_local_evaluation_point(), PhysicsSolver< VectorType >::get_newton_update(), PhysicsSolver< VectorType >::get_present_solution(), PhysicsSolver< VectorType >::get_system_rhs(), PhysicsSolver< VectorType >::output_newton_update_norms(), PhysicsSolver< VectorType >::pcout, Parameters::quiet, PhysicsSolver< VectorType >::setup_preconditioner(), and PhysicsSolver< VectorType >::solve_linear_system().
Member Data Documentation
matrix_requires_assembly
template<typename VectorType > bool InexactNewtonNonLinearSolver< VectorType >::matrix_requires_assembly private
Definition at line 47 of file inexact_newton_non_linear_solver.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/inexact_newton_non_linear_solver.h