Lethe Open-Source Library: CouplingOperatorBase< dim, Number, DataType_ > Class Template Reference
CouplingOperatorBase< dim, Number, DataType_ > Class Template Reference abstract
#include <mortar_coupling_manager.h>
Public Types
using DataType = DataType_
using VectorType = LinearAlgebra::distributed::Vector< Number >
Public Member Functions
CouplingOperatorBase (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const AffineConstraints< Number > &constraints, const Quadrature< dim > quadrature, const unsigned int n_subdivisions, const unsigned int n_components, const unsigned int N, const double radius, const double rotate_pi, const unsigned int bid_0, const unsigned int bid_1, const double sip_factor, const std::vector< unsigned int > relevant_dof_indices, const double penalty_factor_grad)
const AffineConstraints< Number > & get_affine_constraints () const
void vmult_add (VectorType &dst, const VectorType &src) const
void add_diagonal_entries (VectorType &diagonal) const
void add_sparsity_pattern_entries (TrilinosWrappers::SparsityPattern &dsp) const
void add_system_matrix_entries (TrilinosWrappers::SparseMatrix &system_matrix) const
Protected Member Functions
virtual void local_reinit (const typename Triangulation< dim >::cell_iterator &cell, const ArrayView< const Point< dim, Number > > &points) const =0
virtual void local_evaluate (const Vector< Number > &buffer, const unsigned int ptr_q, const unsigned int q_stride, DataType *all_value_m) const =0
virtual void local_integrate (Vector< Number > &buffer, const unsigned int ptr_q, const unsigned int q_stride, DataType *all_value_m, DataType *all_value_p) const =0
Protected Attributes
Number penalty_factor
Number penalty_factor_grad
std::shared_ptr< MortarManager< dim > > mortar_manager_q
std::shared_ptr< MortarManager< dim > > mortar_manager_cell
const unsigned int n_components
const unsigned int N
const unsigned int bid_0
const unsigned int bid_1
const std::vector< unsigned int > relevant_dof_indices
const unsigned int n_dofs_per_cell
Utilities::MPI::NoncontiguousPartitioner partitioner
Utilities::MPI::NoncontiguousPartitioner partitioner_cell
std::vector< types::global_dof_index > dof_indices
std::vector< types::global_dof_index > dof_indices_ghost
std::vector< Number > all_penalty_parameter
std::vector< Number > all_weights
std::vector< Point< dim, Number > > all_points_ref
std::vector< Tensor< 1, dim, Number > > all_normals
AffineConstraints< Number > constraints_extended
Private Member Functions
Number compute_penalty_factor (const unsigned int degree, const Number factor) const
Number compute_penalty_parameter (const typename Triangulation< dim >::cell_iterator &cell) const
double get_rad (const typename Triangulation< dim >::cell_iterator &cell, const typename Triangulation< dim >::face_iterator &face) const
std::vector< types::global_dof_index > get_dof_indices (const typename DoFHandler< dim >::active_cell_iterator &cell) const
Private Attributes
const Mapping< dim > & mapping
const DoFHandler< dim > & dof_handler
const AffineConstraints< Number > & constraints
const Quadrature< dim > quadrature
std::vector< std::tuple< std::vector< double >, typename Triangulation< dim >::active_cell_iterator, std::vector< Point< dim > >, typename Triangulation< dim >::active_cell_iterator, std::vector< Point< dim > >, std::vector< Tensor< 1, dim, Number > >, Number > > all_intersections
Detailed Description
template<int dim, typename Number, typename DataType_>
class CouplingOperatorBase< dim, Number, DataType_ >
Definition at line 491 of file mortar_coupling_manager.h.
Member Typedef Documentation
DataType
template<int dim, typename Number , typename DataType_ > using CouplingOperatorBase< dim, Number, DataType_ >::DataType = DataType_
Definition at line 494 of file mortar_coupling_manager.h.
VectorType
template<int dim, typename Number , typename DataType_ > using CouplingOperatorBase< dim, Number, DataType_ >::VectorType = LinearAlgebra::distributed::Vector<Number>
Definition at line 495 of file mortar_coupling_manager.h.
Constructor & Destructor Documentation
CouplingOperatorBase()
template<int dim, typename Number , typename DataType_ > CouplingOperatorBase< dim, Number, DataType_ >::CouplingOperatorBase (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const AffineConstraints< Number > & constraints, const Quadrature< dim > quadrature, const unsigned int n_subdivisions, const unsigned int n_components, const unsigned int N, const double radius, const double rotate_pi, const unsigned int bid_0, const unsigned int bid_1, const double sip_factor, const std::vector< unsigned int > relevant_dof_indices, const double penalty_factor_grad)
Definition at line 974 of file mortar_coupling_manager.h.
References CouplingOperatorBase< dim, Number, DataType_ >::all_normals, CouplingOperatorBase< dim, Number, DataType_ >::all_penalty_parameter, CouplingOperatorBase< dim, Number, DataType_ >::all_points_ref, CouplingOperatorBase< dim, Number, DataType_ >::all_weights, CouplingOperatorBase< dim, Number, DataType_ >::bid_0, CouplingOperatorBase< dim, Number, DataType_ >::bid_1, CouplingOperatorBase< dim, Number, DataType_ >::compute_penalty_factor(), CouplingOperatorBase< dim, Number, DataType_ >::compute_penalty_parameter(), CouplingOperatorBase< dim, Number, DataType_ >::constraints, CouplingOperatorBase< dim, Number, DataType_ >::constraints_extended, CouplingOperatorBase< dim, Number, DataType_ >::dof_handler, CouplingOperatorBase< dim, Number, DataType_ >::dof_indices, CouplingOperatorBase< dim, Number, DataType_ >::dof_indices_ghost, CouplingOperatorBase< dim, Number, DataType_ >::get_dof_indices(), CouplingOperatorBase< dim, Number, DataType_ >::get_rad(), CouplingOperatorBase< dim, Number, DataType_ >::mapping, CouplingOperatorBase< dim, Number, DataType_ >::mortar_manager_cell, CouplingOperatorBase< dim, Number, DataType_ >::mortar_manager_q, CouplingOperatorBase< dim, Number, DataType_ >::n_dofs_per_cell, CouplingOperatorBase< dim, Number, DataType_ >::partitioner, CouplingOperatorBase< dim, Number, DataType_ >::partitioner_cell, CouplingOperatorBase< dim, Number, DataType_ >::penalty_factor, CouplingOperatorBase< dim, Number, DataType_ >::penalty_factor_grad, and CouplingOperatorBase< dim, Number, DataType_ >::quadrature.
Member Function Documentation
add_diagonal_entries()
template<int dim, typename Number , typename DataType_ > void CouplingOperatorBase< dim, Number, DataType_ >::add_diagonal_entries (VectorType & diagonal) const
Definition at line 1383 of file mortar_coupling_manager.h.
add_sparsity_pattern_entries()
template<int dim, typename Number , typename DataType_ > void CouplingOperatorBase< dim, Number, DataType_ >::add_sparsity_pattern_entries (TrilinosWrappers::SparsityPattern & dsp) const
Definition at line 1435 of file mortar_coupling_manager.h.
add_system_matrix_entries()
template<int dim, typename Number , typename DataType_ > void CouplingOperatorBase< dim, Number, DataType_ >::add_system_matrix_entries (TrilinosWrappers::SparseMatrix & system_matrix) const
Definition at line 1456 of file mortar_coupling_manager.h.
compute_penalty_factor()
template<int dim, typename Number , typename DataType_ > Number CouplingOperatorBase< dim, Number, DataType_ >::compute_penalty_factor (const unsigned int degree, const Number factor) const private
Definition at line 1228 of file mortar_coupling_manager.h.
compute_penalty_parameter()
template<int dim, typename Number , typename DataType_ > Number CouplingOperatorBase< dim, Number, DataType_ >::compute_penalty_parameter (const typename Triangulation< dim >::cell_iterator & cell) const private
Definition at line 1237 of file mortar_coupling_manager.h.
get_affine_constraints()
template<int dim, typename Number , typename DataType_ > const AffineConstraints< Number > & CouplingOperatorBase< dim, Number, DataType_ >::get_affine_constraints () const
Definition at line 1221 of file mortar_coupling_manager.h.
get_dof_indices()
template<int dim, typename Number , typename DataType_ > std::vector< types::global_dof_index > CouplingOperatorBase< dim, Number, DataType_ >::get_dof_indices (const typename DoFHandler< dim >::active_cell_iterator & cell) const private
Definition at line 1290 of file mortar_coupling_manager.h.
get_rad()
template<int dim, typename Number , typename DataType_ > double CouplingOperatorBase< dim, Number, DataType_ >::get_rad (const typename Triangulation< dim >::cell_iterator & cell, const typename Triangulation< dim >::face_iterator & face) const private
Definition at line 1276 of file mortar_coupling_manager.h.
References point_to_rad().
local_evaluate()
template<int dim, typename Number , typename DataType_ > virtual void CouplingOperatorBase< dim, Number, DataType_ >::local_evaluate (const Vector< Number > & buffer, const unsigned int ptr_q, const unsigned int q_stride, DataType * all_value_m) const protected pure virtual
local_integrate()
template<int dim, typename Number , typename DataType_ > virtual void CouplingOperatorBase< dim, Number, DataType_ >::local_integrate (Vector< Number > & buffer, const unsigned int ptr_q, const unsigned int q_stride, DataType * all_value_m, DataType * all_value_p) const protected pure virtual
local_reinit()
template<int dim, typename Number , typename DataType_ > virtual void CouplingOperatorBase< dim, Number, DataType_ >::local_reinit (const typename Triangulation< dim >::cell_iterator & cell, const ArrayView< const Point< dim, Number > > & points) const protected pure virtual
Implemented in CouplingOperator< dim, n_components, Number >, and CouplingOperatorStokes< dim, Number >.
vmult_add()
template<int dim, typename Number , typename DataType_ > void CouplingOperatorBase< dim, Number, DataType_ >::vmult_add (VectorType & dst, const VectorType & src) const
Definition at line 1307 of file mortar_coupling_manager.h.
Member Data Documentation
all_intersections
template<int dim, typename Number , typename DataType_ > std::vector<std::tuple<std::vector<double>, typename Triangulation<dim>::active_cell_iterator, std::vector<Point<dim> >, typename Triangulation<dim>::active_cell_iterator, std::vector<Point<dim> >, std::vector<Tensor<1, dim, Number> >, Number> > CouplingOperatorBase< dim, Number, DataType_ >::all_intersections private
Definition at line 557 of file mortar_coupling_manager.h.
all_normals
template<int dim, typename Number , typename DataType_ > std::vector<Tensor<1, dim, Number> > CouplingOperatorBase< dim, Number, DataType_ >::all_normals protected
Definition at line 584 of file mortar_coupling_manager.h.
all_penalty_parameter
template<int dim, typename Number , typename DataType_ > std::vector<Number> CouplingOperatorBase< dim, Number, DataType_ >::all_penalty_parameter protected
Definition at line 581 of file mortar_coupling_manager.h.
all_points_ref
template<int dim, typename Number , typename DataType_ > std::vector<Point<dim, Number> > CouplingOperatorBase< dim, Number, DataType_ >::all_points_ref protected
Definition at line 583 of file mortar_coupling_manager.h.
all_weights
template<int dim, typename Number , typename DataType_ > std::vector<Number> CouplingOperatorBase< dim, Number, DataType_ >::all_weights protected
Definition at line 582 of file mortar_coupling_manager.h.
bid_0
template<int dim, typename Number , typename DataType_ > const unsigned int CouplingOperatorBase< dim, Number, DataType_ >::bid_0 protected
Definition at line 569 of file mortar_coupling_manager.h.
bid_1
template<int dim, typename Number , typename DataType_ > const unsigned int CouplingOperatorBase< dim, Number, DataType_ >::bid_1 protected
Definition at line 570 of file mortar_coupling_manager.h.
constraints
template<int dim, typename Number , typename DataType_ > const AffineConstraints<Number>& CouplingOperatorBase< dim, Number, DataType_ >::constraints private
Definition at line 547 of file mortar_coupling_manager.h.
constraints_extended
template<int dim, typename Number , typename DataType_ > AffineConstraints<Number> CouplingOperatorBase< dim, Number, DataType_ >::constraints_extended protected
Definition at line 586 of file mortar_coupling_manager.h.
dof_handler
template<int dim, typename Number , typename DataType_ > const DoFHandler<dim>& CouplingOperatorBase< dim, Number, DataType_ >::dof_handler private
Definition at line 546 of file mortar_coupling_manager.h.
dof_indices
template<int dim, typename Number , typename DataType_ > std::vector<types::global_dof_index> CouplingOperatorBase< dim, Number, DataType_ >::dof_indices protected
Definition at line 578 of file mortar_coupling_manager.h.
dof_indices_ghost
template<int dim, typename Number , typename DataType_ > std::vector<types::global_dof_index> CouplingOperatorBase< dim, Number, DataType_ >::dof_indices_ghost protected
Definition at line 579 of file mortar_coupling_manager.h.
mapping
template<int dim, typename Number , typename DataType_ > const Mapping<dim>& CouplingOperatorBase< dim, Number, DataType_ >::mapping private
Definition at line 545 of file mortar_coupling_manager.h.
mortar_manager_cell
template<int dim, typename Number , typename DataType_ > std::shared_ptr<MortarManager<dim> > CouplingOperatorBase< dim, Number, DataType_ >::mortar_manager_cell protected
Definition at line 564 of file mortar_coupling_manager.h.
mortar_manager_q
template<int dim, typename Number , typename DataType_ > std::shared_ptr<MortarManager<dim> > CouplingOperatorBase< dim, Number, DataType_ >::mortar_manager_q protected
Definition at line 563 of file mortar_coupling_manager.h.
N
template<int dim, typename Number , typename DataType_ > const unsigned int CouplingOperatorBase< dim, Number, DataType_ >::N protected
Definition at line 567 of file mortar_coupling_manager.h.
n_components
template<int dim, typename Number , typename DataType_ > const unsigned int CouplingOperatorBase< dim, Number, DataType_ >::n_components protected
Definition at line 566 of file mortar_coupling_manager.h.
n_dofs_per_cell
template<int dim, typename Number , typename DataType_ > const unsigned int CouplingOperatorBase< dim, Number, DataType_ >::n_dofs_per_cell protected
Definition at line 573 of file mortar_coupling_manager.h.
partitioner
template<int dim, typename Number , typename DataType_ > Utilities::MPI::NoncontiguousPartitioner CouplingOperatorBase< dim, Number, DataType_ >::partitioner protected
Definition at line 575 of file mortar_coupling_manager.h.
partitioner_cell
template<int dim, typename Number , typename DataType_ > Utilities::MPI::NoncontiguousPartitioner CouplingOperatorBase< dim, Number, DataType_ >::partitioner_cell protected
Definition at line 576 of file mortar_coupling_manager.h.
penalty_factor
template<int dim, typename Number , typename DataType_ > Number CouplingOperatorBase< dim, Number, DataType_ >::penalty_factor protected
Definition at line 560 of file mortar_coupling_manager.h.
penalty_factor_grad
template<int dim, typename Number , typename DataType_ > Number CouplingOperatorBase< dim, Number, DataType_ >::penalty_factor_grad protected
Definition at line 561 of file mortar_coupling_manager.h.
quadrature
template<int dim, typename Number , typename DataType_ > const Quadrature<dim> CouplingOperatorBase< dim, Number, DataType_ >::quadrature private
Definition at line 548 of file mortar_coupling_manager.h.
relevant_dof_indices
template<int dim, typename Number , typename DataType_ > const std::vector<unsigned int> CouplingOperatorBase< dim, Number, DataType_ >::relevant_dof_indices protected
Definition at line 572 of file mortar_coupling_manager.h.
The documentation for this class was generated from the following file:
/home/runner/work/lethe/lethe/include/core/mortar_coupling_manager.h