Lethe Open-Source Library: GridImpingingJetMixer< dim, spacedim > Class Template Reference
GridImpingingJetMixer< dim, spacedim > Class Template Reference
#include <grid_impinging_jet_mixer.h>
Public Member Functions
GridImpingingJetMixer (const std::string &grid_arguments)
void make_grid (Triangulation< dim, spacedim > &triangulation)
void make_grid (Triangulation< 3, 3 > &triangulation)
Private Attributes
std::string grid_arguments
MixerGeometry geometry
Detailed Description
template<int dim, int spacedim>
class GridImpingingJetMixer< dim, spacedim >
Generates a 3D mesh for an impinging-jet mixer geometry.
The geometry (axis of the mixing chamber = z, vertical) consists of:
A large vertical mixing chamber (cylinder of radius R_chamber) whose top is closed by a hemispherical dome;
A conical reduction (R_chamber -> r_outlet) followed by a straight outlet pipe (radius r_outlet) below the chamber;
Two opposing, smaller horizontal inlet pipes (radius r_inlet) entering the side wall of the chamber from +x and -x, whose jets impinge on the chamber axis. The mesh is datumed so that the common axis of the two inlet pipes lies on the z = 0 plane (the impingement plane).
How the inlets are connected to the chamber
A round pipe entering the curved wall of a larger cylinder is a saddle intersection that cannot be produced conformingly by merging library primitives (a naive merge leaves the pipes floating against the wall). The inlet pipes are therefore grown out of the chamber wall itself:
The vessel (chamber + dome + reduction + outlet) is built as one conforming triangulation and refined so the wall is finely resolved;
at each inlet location, the small patch of chamber-wall faces that falls inside the inlet footprint is selected;
that patch is extruded outward in +/- x to build the inlet pipe. Because the new pipe cells reuse the wall-patch vertices, the patch faces become interior faces shared between chamber and pipe – the inlet opens into the chamber and the mesh stays watertight and conforming.
Boundary IDs are assigned as follows:
0: inlet 1 (+x),
1: inlet 2 (-x),
2: outlet,
3: walls (everything else).
Manifold IDs are assigned as follows:
0: cylindrical about the z-axis (chamber, reduction, outlet laterals),
1: spherical (hemispherical dome),
2: cylindrical about the x-axis (both inlet pipes).
Template Parameters
dim The dimension of the mesh, must be 3.
spacedim The dimension of the space, must be 3.
Definition at line 105 of file grid_impinging_jet_mixer.h.
Constructor & Destructor Documentation
GridImpingingJetMixer()
template<int dim, int spacedim> GridImpingingJetMixer< dim, spacedim >::GridImpingingJetMixer (const std::string & grid_arguments)
Constructor that parses the geometry dimensions from a colon-separated string.
The eight geometric dimensions (all in metres) are, in order: R_chamber : r_inlet : r_outlet : H_chamber : L_cone : L_outlet : L_inlet : z_inlet An empty string keeps the default dimensions. The mesh discretisation is not exposed and stays hardcoded.
Parameters
[in] grid_arguments A colon-separated string with the geometry dimensions, or an empty string to use the defaults.
Definition at line 179 of file grid_impinging_jet_mixer.cc.
References MixerGeometry::H_chamber, MixerGeometry::L_cone, MixerGeometry::L_inlet, MixerGeometry::L_outlet, MixerGeometry::R_chamber, MixerGeometry::r_inlet, MixerGeometry::r_outlet, and MixerGeometry::z_inlet.
Member Function Documentation
make_grid() [1/2]
void GridImpingingJetMixer< 3, 3 >::make_grid (Triangulation< 3, 3 > & triangulation)
Definition at line 246 of file grid_impinging_jet_mixer.cc.
References MixerGeometry::L_inlet, MixerGeometry::R_chamber, MixerGeometry::r_inlet, MixerGeometry::z_chamber_top(), MixerGeometry::z_dome_center(), MixerGeometry::z_inlet, and MixerGeometry::z_outlet_bottom().
make_grid() [2/2]
template<int dim, int spacedim> void GridImpingingJetMixer< dim, spacedim >::make_grid (Triangulation< dim, spacedim > & triangulation)
Generate the impinging-jet mixer mesh.
Parameters
[out] triangulation The triangulation to fill with the mesh.
Definition at line 616 of file grid_impinging_jet_mixer.cc.
Member Data Documentation
geometry
template<int dim, int spacedim> MixerGeometry GridImpingingJetMixer< dim, spacedim >::geometry private
All geometry dimensions (SI units, metres), with their defaults. Populated from the grid-argument string by the constructor when one is provided.
Definition at line 137 of file grid_impinging_jet_mixer.h.
grid_arguments
template<int dim, int spacedim> std::string GridImpingingJetMixer< dim, spacedim >::grid_arguments private
Arguments used to generate the grid.
Definition at line 133 of file grid_impinging_jet_mixer.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/grid_impinging_jet_mixer.h
/home/runner/work/lethe/lethe/source/core/grid_impinging_jet_mixer.cc