Lethe Open-Source Library: NavierStokesBase< dim, VectorType, DofsType > Class Template Reference
NavierStokesBase< dim, VectorType, DofsType > Class Template Reference abstract
#include <navier_stokes_base.h>
Classes
struct SDIRKVectors
Protected Member Functions
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual VectorType & get_evaluation_point () override
virtual VectorType & get_local_evaluation_point () override
virtual VectorType & get_newton_update () override
virtual VectorType & get_present_solution () override
virtual VectorType & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void setup_dofs ()
virtual void set_initial_condition (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void postprocess_fd (bool first_iteration)
virtual void setup_dofs_fd ()=0
virtual void update_mortar_configuration ()
virtual void update_multiphysics_time_average_solution ()=0
virtual void update_solutions_for_multiphysics ()
virtual void update_solutions_for_fluid_dynamics ()
virtual void set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false)=0
void postprocessing_forces (const VectorType &evaluation_point)
void postprocessing_torques (const VectorType &evaluation_point)
virtual void dynamic_flow_control ()
virtual void multi_stage_preresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method)
virtual void multi_stage_postresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method, double time_step)
virtual void update_multi_stage_solution (double time_step)
virtual void iterate ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
void transfer_solution (SolutionTransfer< dim, VectorType > &solution_transfer, std::vector< SolutionTransfer< dim, VectorType > > &previous_solutions_transfer)
virtual void read_checkpoint ()
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void reinit_mortar_operators ()
std::shared_ptr< Mapping< dim > > get_mapping ()
void rotate_rotor_mapping (const bool is_first)
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
virtual std::vector< OutputStructTableHandler > gather_tables ()
void serialize_tables_vector (const std::vector< OutputStructTableHandler > &table_output_structs)
void deserialize_tables_vector (std::vector< OutputStructTableHandler > &table_output_structs)
virtual void write_checkpoint ()
virtual std::vector< OutputStruct< dim, VectorType > > gather_output_hook ()
void gather_output_results (const VectorType &solution, std::vector< OutputStruct< dim, VectorType > > &solution_output_structs)
void write_output_results (const VectorType &solution)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
VectorType init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes
DofsType locally_owned_dofs
DofsType locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
VectorType evaluation_point
VectorType local_evaluation_point
VectorType newton_update
VectorType present_solution
VectorType system_rhs
std::vector< VectorType > previous_solutions
SDIRKVectors sdirk_vectors
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::shared_ptr< MortarManagerCircle< dim > > mortar_manager
std::shared_ptr< CouplingOperator< dim, double > > mortar_coupling_operator
std::shared_ptr< NavierStokesCouplingEvaluation< dim, double > > mortar_coupling_evaluator
std::shared_ptr< MappingQCache< dim > > mapping_cache
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, VectorType, DofsType > > average_velocities
VectorType average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Additional Inherited Members
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
virtual void assemble_system_matrix ()=0
virtual void assemble_system_rhs ()=0
virtual void setup_preconditioner ()=0
virtual void solve_linear_system (const bool initial_step, const bool renewed_matrix=true)=0
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim, typename VectorType, typename DofsType>
class NavierStokesBase< dim, VectorType, DofsType >
A base class for all the Navier-Stokes equation This class regroups common facilities that are shared by all the Navier-Stokes implementations to reduce code multiplicity
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
VectorType The Vector type used for the solvers
DofsType the type of dof storage indices
Author
Bruno Blais, 2019
Definition at line 119 of file navier_stokes_base.h.
Constructor & Destructor Documentation
NavierStokesBase()
template<int dim, typename VectorType , typename DofsType > NavierStokesBase< dim, VectorType, DofsType >::NavierStokesBase (SimulationParameters< dim > & nsparam) protected
Definition at line 47 of file navier_stokes_base.cc.
References NavierStokesBase< dim, VectorType, DofsType >::cell_quadrature, NavierStokesBase< dim, VectorType, DofsType >::dof_handler, Parameters::FEM::enable_bubble_function_pressure, Parameters::FEM::enable_bubble_function_velocity, NavierStokesBase< dim, VectorType, DofsType >::face_quadrature, NavierStokesBase< dim, VectorType, DofsType >::fe, SimulationParameters< dim >::fem_parameters, fluid_dynamics, SimulationParameters< dim >::linear_solver, NavierStokesBase< dim, VectorType, DofsType >::mapping, NavierStokesBase< dim, VectorType, DofsType >::mpi_communicator, NavierStokesBase< dim, VectorType, DofsType >::number_quadrature_points, Parameters::FEM::pressure_order, NavierStokesBase< dim, VectorType, DofsType >::simulation_parameters, NavierStokesBase< dim, VectorType, DofsType >::triangulation, NavierStokesBase< dim, VectorType, DofsType >::velocity_fem_degree, and Parameters::FEM::velocity_order.
~NavierStokesBase()
template<int dim, typename VectorType , typename DofsType > virtual NavierStokesBase< dim, VectorType, DofsType >::~NavierStokesBase () inline protected virtual
Definition at line 124 of file navier_stokes_base.h.
Member Function Documentation
box_refine_mesh()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::box_refine_mesh (const bool restart) protected
Allow the initial refinement of all cells of the principal mesh that are partially contained in one of the cells of the box refinement mesh given in the parameter.
Parameters
restart Indicator if the simulation is being restarted or not.
Definition at line 878 of file navier_stokes_base.cc.
cell_in_constraining_domain()
template<int dim, typename VectorType , typename DofsType > bool NavierStokesBase< dim, VectorType, DofsType >::cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator & cell, const Point< dim > & plane_point, const Tensor< 1, dim > & plane_normal_vector) inline protected
Checks and identifies if the cell is located in the constraining domain defined by a plane with its outward-pointing normal vector. The check is done through a scalar product between a vector formed by a vertex of the cell to @plane_point and @plane_normal_vector. If one of the vertices of the cell results in a negative scalar product result, the cell is excluded from the constrained domain.
Parameters
[in] cell Pointer to an active cell of the fluid dynamics DoFHandler.
[in] plane_point Coordinates of a point on the restriction plane for the stasis constraint application domain.
[in] plane_normal_vector Outward-pointing normal vector to define the restriction plane for the stasis constraint application domain.
Returns
Boolean indicating if the cell is in the domain of interest (true) or not (false).
Definition at line 557 of file navier_stokes_base.h.
check_cell_is_connected_to_fluid()
template<int dim, typename VectorType , typename DofsType > bool NavierStokesBase< dim, VectorType, DofsType >::check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > & dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > & local_dof_indices) inline protected
Check if the cell is connected to a fluid cell.
Parameters
[in] dofs_are_connected_to_fluid Container of global DOF indices connected to at least one fluid cell.
[in] local_dof_indices Vector of a cell's local DOF indices.
Returns
Boolean indicating if the cell is connected to a fluid (true) or not (false).
Definition at line 751 of file navier_stokes_base.h.
check_existance_of_bc()
template<int dim, typename VectorType , typename DofsType > bool NavierStokesBase< dim, VectorType, DofsType >::check_existance_of_bc (BoundaryConditions::BoundaryType bc) protected
Check if a specifique boundary condition exist.
Parameters
bc,the boundary type that we want to check if it exists
Definition at line 250 of file navier_stokes_base.cc.
constrain_pressure()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::constrain_pressure (const bool & non_zero_constraints, const std::vector< types::global_dof_index > & local_dof_indices, AffineConstraints< double > & zero_constraints) inline protected
Constrain pressure DOFs if cells are not connected to fluid and DOFs are locally owned.
Parameters
[in] non_zero_constraints If this parameter is true, it indicates that non-zero constraints are applied in the solid domain. If this is set to false, homogeneous constraints are applied in the solid domain.
[in] local_dof_indices Vector of a cell's local DOF indices.
[out] zero_constraints Homogeneous constraints holding object.
Definition at line 779 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::fe, NavierStokesBase< dim, VectorType, DofsType >::locally_owned_dofs, NavierStokesBase< dim, VectorType, DofsType >::nonzero_constraints, and NavierStokesBase< dim, VectorType, DofsType >::zero_constraints.
constrain_solid_cell_velocity_dofs()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::constrain_solid_cell_velocity_dofs (const bool & non_zero_constraints, const std::vector< types::global_dof_index > & local_dof_indices, AffineConstraints< double > & zero_constraints) inline protected
Constrain velocity DOFs of a solid cell.
Parameters
[in] non_zero_constraints If this parameter is true, it indicates that non-zero constraints are applied in the solid domain. If this is set to false, homogeneous constraints are applied in the solid domain.
[in] local_dof_indices Vector of a cell's local DOF indices.
[out] zero_constraints Homogeneous constraints holding object.
Definition at line 666 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::fe, NavierStokesBase< dim, VectorType, DofsType >::nonzero_constraints, and NavierStokesBase< dim, VectorType, DofsType >::zero_constraints.
constrain_stasis_with_temperature()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::constrain_stasis_with_temperature (const DoFHandler< dim > * dof_handler_ht) protected
Constrain a fluid's subdomains according to the temperature field to null velocity and pressure fields to model solid subdomains.
Note
Its equivalent for Volume of Fluid (VOF) simulations is NavierStokesBase<dim, VectorType, DofsType>::constrain_solid_domain_vof.
Parameters
[in] dof_handler_ht DoFHandler of the Heat Transfer (HT) auxiliary physic.
Definition at line 2487 of file navier_stokes_base.cc.
References heat_transfer.
constrain_stasis_with_temperature_vof()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::constrain_stasis_with_temperature_vof (const DoFHandler< dim > * dof_handler_vof, const DoFHandler< dim > * dof_handler_ht) protected
Constrain fluids' subdomains according to the temperature field to null velocity and pressure fields to model solid subdomains in Volume of Fluid (VOF) simulations.
Parameters
[in] dof_handler_vof DoFHandler of the VOF auxiliary physic.
[in] dof_handler_ht DoFHandler of the Heat Transfer (HT) auxiliary physic.
Definition at line 2540 of file navier_stokes_base.cc.
References heat_transfer, and VOF.
define_non_zero_constraints()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::define_non_zero_constraints () protected
Define the non-zero constraints used to solve the problem.
Definition at line 1916 of file navier_stokes_base.cc.
References BoundaryConditions::function, BoundaryConditions::noslip, BoundaryConditions::periodic, pressure, and BoundaryConditions::slip.
define_zero_constraints()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::define_zero_constraints () protected
Define the zero constraints used to solve the problem.
Definition at line 2028 of file navier_stokes_base.cc.
References BoundaryConditions::function, BoundaryConditions::function_weak, BoundaryConditions::none, BoundaryConditions::noslip, BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::periodic, BoundaryConditions::pressure, pressure, and BoundaryConditions::slip.
deserialize_tables_vector()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::deserialize_tables_vector (std::vector< OutputStructTableHandler > & table_output_structs) protected
Deserializes all the TableHandler objects in table_output_structs.
Parameters
[in] table_output_structs Vector of structures containing references to TableHandler objects that needs to be serialized/deserialized for a given solver, and their corresponding file names.
Definition at line 3167 of file navier_stokes_base.cc.
References deserialize_table().
dynamic_flow_control()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::dynamic_flow_control () protected virtual
If set to enable, dynamic_flow_control allows to control the flow by executing space-average velocity and beta coefficient force calculation at each time step.
Reimplemented in CFDDEMSolver< dim >.
Definition at line 212 of file navier_stokes_base.cc.
References announce_string(), calculate_average_velocity(), Parameters::SimulationControl::steady, and Parameters::verbose.
enable_dynamic_zero_constraints_fd()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::enable_dynamic_zero_constraints_fd () protected virtual
Enable the use of dynamic zero constraints by initializing required FEValues objects.
Note
At the moment, the only solution-dependent dynamic constraint depends on the temperature field obtained from the Heat Transfer (HT) auxiliary physic.
Definition at line 806 of file navier_stokes_base.cc.
References heat_transfer.
establish_solid_domain()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::establish_solid_domain (const bool non_zero_constraints) protected
Turn regions of the mesh where the material_id>0 into a solid block by injecting velocity and pressure DOFs into the zero constraints.
It is achieved by imposing \(\mathbf{u}=0\) within the cells which have a material_id>0. In addition, solid cells which are not connected to the fluid by any means also get a pressure Dirichlet boundary condition which fixes the pressure to 0. It ensures that the linear system is well-posed. Right now, this routine only supports the usage of 1 solid domain, but eventually it could be extended to more than one. By default, the fluid domain is assumed to have a material_id=0 and the rest of the domains have a material_id>0.
Parameters
[in] non_zero_constraints If this parameter is true, it indicates that non-zero constraints are being constrained for the solid domain. If this is set to false, homogeneous constraints are constrained in the solid domain.
Definition at line 2410 of file navier_stokes_base.cc.
finish_simulation()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::finish_simulation () inline protected
Finish the simulation by calling all the post-processing elements that are required.
Generic interface routine to allow the CFD solver to cooperate with the multiphysics modules
Definition at line 183 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::finish_simulation_fd(), and NavierStokesBase< dim, VectorType, DofsType >::multiphysics.
finish_simulation_fd()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::finish_simulation_fd () protected
Finishes the simulation for fluid dynamics by calling the post-processing elements that are required.
Definition at line 484 of file navier_stokes_base.cc.
References Parameters::SimulationControl::steady.
finish_time_step()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::finish_time_step () protected virtual
Finishes the time step of the fluid dynamics. Post-processing and time stepping.
Key physics component for fluid dynamics
Definition at line 544 of file navier_stokes_base.cc.
References announce_string(), calculate_CFL(), Parameters::Timer::iteration, Parameters::SimulationControl::steady, and write_checkpoint().
flag_dofs_connected_to_fluid()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > & local_dof_indices, std::unordered_set< types::global_dof_index > & dofs_are_connected_to_fluid) inline protected
Flag DOFs connected to fluid cells.
Parameters
[in] local_dof_indices Vector of a cell's local DOF indices.
[out] dofs_are_connected_to_fluid Container of global DOF indices connected to at least one fluid cell.
Definition at line 724 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::fe.
flag_dofs_in_solid()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::flag_dofs_in_solid (const std::vector< types::global_dof_index > & local_dof_indices, std::unordered_set< types::global_dof_index > & dofs_are_in_solid) inline protected
Flag DOFs in solid cells.
Parameters
[in] local_dof_indices Vector of a cell's local DOF indices.
[out] dofs_are_in_solid Container of global DOF indices located in solid cells.
Definition at line 700 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::fe.
gather_output_hook()
template<int dim, typename VectorType , typename DofsType > std::vector< OutputStruct< dim, VectorType > > NavierStokesBase< dim, VectorType, DofsType >::gather_output_hook () protected virtual
Gather and return vector of output structs that are particular to some applications.
Returns
Vector of OutputStructs that will be used to write the output results as VTU files.
Reimplemented in FluidDynamicsSharp< dim >, FluidDynamicsVANS< dim >, and FluidDynamicsVANSMatrixFree< dim >.
Definition at line 2651 of file navier_stokes_base.cc.
gather_output_results()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::gather_output_results (const VectorType & solution, std::vector< OutputStruct< dim, VectorType > > & solution_output_structs) protected
Gather solution information to generate output results.
Parameters
[in] solution Vector of present solution
[in,out] solution_output_structs Vector of OutputStructs that will be used to write the output results as VTU files
Definition at line 2658 of file navier_stokes_base.cc.
References Parameters::average_velocity_profile, OutputStructPostprocessor< dim, VectorType >::dof_handler, and Parameters::VelocitySource::srf.
gather_tables()
template<int dim, typename VectorType , typename DofsType > std::vector< OutputStructTableHandler > NavierStokesBase< dim, VectorType, DofsType >::gather_tables () protected virtual
Returns a vector of references to TableHandler objects that needs to be serialized/ deserialized for a given solver.
Returns
Structure containing a vector of references to TableHandler objects that needs to be serialized/deserialized for a given solver, and their corresponding file names.
Reimplemented in CFDDEMSolver< dim >, and FluidDynamicsNitsche< dim, spacedim >.
Definition at line 3084 of file navier_stokes_base.cc.
References Parameters::PostProcessing::apparent_viscosity_output_name, Parameters::PostProcessing::calculate_apparent_viscosity, Parameters::PostProcessing::calculate_enstrophy, Parameters::PostProcessing::calculate_flow_rate, Parameters::PostProcessing::calculate_kinetic_energy, Parameters::PostProcessing::calculate_pressure_drop, Parameters::PostProcessing::calculate_pressure_power, Parameters::PostProcessing::calculate_viscous_dissipation, Parameters::PostProcessing::enstrophy_output_name, Parameters::PostProcessing::flow_rate_output_name, Parameters::PostProcessing::kinetic_energy_output_name, Parameters::PostProcessing::pressure_drop_output_name, Parameters::PostProcessing::pressure_power_output_name, and Parameters::PostProcessing::viscous_dissipation_output_name.
get_cell_filtered_phase_fraction_values()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator & cell, const DoFHandler< dim > * dof_handler_vof, const GlobalVectorType & filtered_phase_fraction_solution, std::vector< double > & local_filtered_phase_fraction_values) inline protected
Get cell's local filtered phase fraction values at quadrature points.
Parameters
[in] cell Pointer to an active cell of the fluid dynamics DoFHandler.
[in] dof_handler_vof DoFHandler of the Volume of Fluid (VOF) auxiliary physic.
[in] filtered_phase_fraction_solution Filtered phase fraction solution vector from the VOF auxiliary physic.
[out] local_filtered_phase_fraction_values Cell's local filtered phase fraction values at quadrature points.
Definition at line 621 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::fe_values_vof, and NavierStokesBase< dim, VectorType, DofsType >::triangulation.
get_cell_temperature_values()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator & cell, const DoFHandler< dim > * dof_handler_ht, const GlobalVectorType & temperature_solution, std::vector< double > & local_temperature_values) inline protected
Get cell's local temperature values at quadrature points.
Parameters
[in] cell Pointer to an active cell of the fluid dynamics DoFHandler.
[in] dof_handler_ht DoFHandler of the Heat Transfer (HT) auxiliary physic.
[in] temperature_solution Temperature solution vector from the HT auxiliary physic.
[out] local_temperature_values Cell's local temperature values at quadrature points.
Definition at line 591 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::fe_values_temperature, and NavierStokesBase< dim, VectorType, DofsType >::triangulation.
get_evaluation_point()
template<int dim, typename VectorType , typename DofsType > virtual VectorType & NavierStokesBase< dim, VectorType, DofsType >::get_evaluation_point () inline override protected virtual
Getter methods to get the private attributes for the physic currently solved.
Parameters
current_physics_id Indicates the number associated with the physic currently solved. If the solver is only solving for a fluid dynamics problem, then the value will always be PhysicsID::fluid_dynamics.
Implements PhysicsSolver< VectorType >.
Definition at line 136 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::evaluation_point.
get_local_evaluation_point()
template<int dim, typename VectorType , typename DofsType > virtual VectorType & NavierStokesBase< dim, VectorType, DofsType >::get_local_evaluation_point () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 141 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::local_evaluation_point.
get_mapping()
template<int dim, typename VectorType , typename DofsType > std::shared_ptr< Mapping< dim > > NavierStokesBase< dim, VectorType, DofsType >::get_mapping () inline protected
Returns the mapping shared pointer. A MappingQCache is necessary for prescribed rotation in rotor-stator configurations.
Definition at line 481 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::mapping, NavierStokesBase< dim, VectorType, DofsType >::mapping_cache, and NavierStokesBase< dim, VectorType, DofsType >::simulation_parameters.
get_newton_update()
template<int dim, typename VectorType , typename DofsType > virtual VectorType & NavierStokesBase< dim, VectorType, DofsType >::get_newton_update () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 146 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::newton_update.
get_nonzero_constraints()
template<int dim, typename VectorType , typename DofsType > virtual AffineConstraints< double > & NavierStokesBase< dim, VectorType, DofsType >::get_nonzero_constraints () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 161 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::nonzero_constraints.
get_present_solution()
template<int dim, typename VectorType , typename DofsType > virtual VectorType & NavierStokesBase< dim, VectorType, DofsType >::get_present_solution () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 151 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::present_solution.
get_system_rhs()
template<int dim, typename VectorType , typename DofsType > virtual VectorType & NavierStokesBase< dim, VectorType, DofsType >::get_system_rhs () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 156 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::system_rhs.
identify_cell_and_constrain_velocity()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > & local_dof_indices, const std::vector< double > & local_temperature_values, StasisConstraintWithTemperature & stasis_constraint_struct) protected
Identify if temperature DOFs of the cell are within the constraining range. If they are, velocity DOFs of the cell are constrained.
Parameters
[in] local_dof_indices Vector of a cell's local DOF indices.
[in] local_temperature_values Cell's local temperature values at quadrature points.
[in,out] stasis_constraint_struct Struct containing flagged DOF containers, temperature range information and fluid id.
Definition at line 2631 of file navier_stokes_base.cc.
References StasisConstraintWithTemperature::max_solid_temperature, StasisConstraintWithTemperature::min_solid_temperature, and temperature.
init_temporary_vector()
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::init_temporary_vector () inline protected
This function initializes correctly a temporary vector depending on the vector type.
Definition at line 3368 of file navier_stokes_base.cc.
iterate()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::iterate () protected virtual
Do a regular CFD iteration.
Reimplemented in FluidDynamicsVANS< dim >.
Definition at line 691 of file navier_stokes_base.cc.
References announce_string(), fluid_dynamics, SimulationControl::get_number_of_stages(), Parameters::quiet, and PhysicsSolver< VectorType >::solve_non_linear_system().
multi_stage_postresolution()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::multi_stage_postresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method, double time_step) protected virtual
Calculate \(k_i \) from \(u*_i : k_i = \frac{u*_i - u_n}{time_step*a_ii} - \sum{j=1}^{i-1} a_ij * k_j \) Update \(\sum_{i=1}^{N_{stages}} b_i * k_i \).
Parameters
stage An unsigned integer which gives the index of the current stage
method SDIRK method for now (BDF methods are single stage)
time_step The current time step to build the solution at the next time step
Definition at line 626 of file navier_stokes_base.cc.
References SDIRKStageData::a_ij, and sdirk_table().
multi_stage_preresolution()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::multi_stage_preresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method) protected virtual
Update the sum_over_previous_stages variable to use it in the solver.
Parameters
stage An unsigned integer which gives the index of the current stage
method SDIRK method for now (BDF methods are single stage)
Definition at line 582 of file navier_stokes_base.cc.
References SDIRKStageData::a_ij, and sdirk_table().
output_newton_update_norms()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::output_newton_update_norms (const unsigned int display_precision) override protected virtual
Output the L2 and Linfty norms of the correction vector.
Parameters
[in] display_precision Number of outputted digits.
Implements PhysicsSolver< VectorType >.
Definition at line 3283 of file navier_stokes_base.cc.
References pressure.
percolate_time_vectors_fd()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::percolate_time_vectors_fd () protected virtual
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
Definition at line 532 of file navier_stokes_base.cc.
postprocess()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::postprocess (bool first_iteration) inline protected virtual
Post-process simulation after an iteration.
Parameters
first_iteration Indicator if the simulation is at it's first simulation or not.
Definition at line 195 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::multiphysics, NavierStokesBase< dim, VectorType, DofsType >::postprocess_fd(), NavierStokesBase< dim, VectorType, DofsType >::present_solution, NavierStokesBase< dim, VectorType, DofsType >::simulation_control, and NavierStokesBase< dim, VectorType, DofsType >::write_output_results().
postprocess_fd()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::postprocess_fd (bool first_iteration) protected virtual
Post-process fluid dynamics after an iteration.
Reimplemented in CFDDEMSolver< dim >, and FluidDynamicsSharp< dim >.
Definition at line 1415 of file navier_stokes_base.cc.
References announce_string(), calculate_apparent_viscosity(), calculate_enstrophy(), calculate_flow_rate(), calculate_kinetic_energy(), calculate_L2_error(), calculate_pressure_drop(), calculate_pressure_power(), calculate_viscous_dissipation(), Parameters::SimulationControl::steady, and Parameters::verbose.
postprocessing_forces()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::postprocessing_forces (const VectorType & evaluation_point) protected
Post-processing function Outputs the forces acting on each boundary condition.
End of key physics components for fluid dynamics
Definition at line 269 of file navier_stokes_base.cc.
postprocessing_torques()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::postprocessing_torques (const VectorType & evaluation_point) protected
Post-processing function Outputs the torque acting on each boundary condition.
Definition at line 405 of file navier_stokes_base.cc.
read_checkpoint()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::read_checkpoint () protected virtual
Restart a previous simulation from a checkpoint file.
Reimplemented in CFDDEMSolver< dim >, FluidDynamicsSharp< dim >, and FluidDynamicsNitsche< dim, spacedim >.
Definition at line 2269 of file navier_stokes_base.cc.
refine_mesh()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::refine_mesh () protected virtual
Allow the refinement of the mesh according to one of the 2 methods proposed.
Reimplemented in FluidDynamicsNitsche< dim, spacedim >.
Definition at line 855 of file navier_stokes_base.cc.
refine_mesh_kelly()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::refine_mesh_kelly () protected
Allow the refinement of the mesh based on the Kelly error estimator. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
Definition at line 1091 of file navier_stokes_base.cc.
References Parameters::average_velocity_profile, Parameters::MeshAdaptation::fraction, Parameters::MeshAdaptation::number, pressure, and velocity.
refine_mesh_uniform()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::refine_mesh_uniform () protected
Allow the uniform refinement of all the mesh.
Definition at line 1317 of file navier_stokes_base.cc.
reinit_mortar_operators()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::reinit_mortar_operators () protected
Initialize mortar coupling manager, operator, and evaluator.
Definition at line 2136 of file navier_stokes_base.cc.
rescale_pressure_dofs_in_newton_update()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::rescale_pressure_dofs_in_newton_update () protected
This function is used to rescale pressure DOFs in the newton correction.
Definition at line 3235 of file navier_stokes_base.cc.
rotate_rotor_mapping()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::rotate_rotor_mapping (const bool is_first) protected
Rotate rotor mapping in mortar method.
Parameters
[in] is_first Whether this is the first mapping rotation. This boolean is used only for printing output purposes; since the mapping needs to be rotated before setting up dofs, but also after the constraints are first defined, this function is called twice before the iterate() loop. The parameter is_first just prevents the mortar verbosity from being printed twice
Definition at line 2172 of file navier_stokes_base.cc.
References compute_n_subdivisions_and_radius(), LetheGridTools::rotate_mapping(), and Parameters::verbose.
serialize_tables_vector()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::serialize_tables_vector (const std::vector< OutputStructTableHandler > & table_output_structs) protected
Serializes all the TableHandler objects in table_output_structs.
Parameters
[in] table_output_structs Vector of structures containing references to TableHandler objects that needs to be serialized/deserialized for a given solver, and their corresponding file names.
Definition at line 3154 of file navier_stokes_base.cc.
References serialize_table().
set_initial_condition()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::set_initial_condition (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart = false) inline protected virtual
Set the initial condition.
Parameters
initial_condition_type Type of method use to impose initial condition.
restart Indicator if the simulation is being restarted or not.
Definition at line 225 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::multiphysics, NavierStokesBase< dim, VectorType, DofsType >::postprocess_fd(), NavierStokesBase< dim, VectorType, DofsType >::present_solution, NavierStokesBase< dim, VectorType, DofsType >::refine_mesh(), NavierStokesBase< dim, VectorType, DofsType >::set_initial_condition_fd(), NavierStokesBase< dim, VectorType, DofsType >::simulation_control, NavierStokesBase< dim, VectorType, DofsType >::simulation_parameters, and NavierStokesBase< dim, VectorType, DofsType >::write_output_results().
set_initial_condition_fd()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart = false) protected pure virtual
Implemented in FluidDynamicsBlock< dim >, FluidDynamicsMatrixBased< dim >, and FluidDynamicsMatrixFree< dim >.
set_nodal_values()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::set_nodal_values () protected
Set the nodal values of velocity and pressure.
Definition at line 1870 of file navier_stokes_base.cc.
References Parameters::SimulationControl::initial_solution, and pressure.
set_solution_from_checkpoint()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::set_solution_from_checkpoint (std::string checkpoint_file_prefix) protected virtual
Read the solution from a checkpoint file and set it as the current solution.
Definition at line 2305 of file navier_stokes_base.cc.
References Parameters::average_velocity_profile.
setup_dofs()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::setup_dofs () inline protected virtual
Initialize the degree of freedom and the memory associated with them for fluid dynamics and enabled auxiliary physics.
Reimplemented in FluidDynamicsVANS< dim >, and FluidDynamicsVANSMatrixFree< dim >.
Definition at line 208 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::multiphysics, NavierStokesBase< dim, VectorType, DofsType >::setup_dofs_fd(), and NavierStokesBase< dim, VectorType, DofsType >::verify_consistency_of_boundary_conditions().
setup_dofs_fd()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::setup_dofs_fd () protected pure virtual
Initialize the dofs for fluid dynamics.
Implemented in FluidDynamicsBlock< dim >, FluidDynamicsMatrixBased< dim >, and FluidDynamicsMatrixFree< dim >.
transfer_solution()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::transfer_solution (SolutionTransfer< dim, VectorType > & solution_transfer, std::vector< SolutionTransfer< dim, VectorType > > & previous_solutions_transfer) protected
Transfer solution after mesh refinement.
Definition at line 1375 of file navier_stokes_base.cc.
References Parameters::average_velocity_profile.
update_boundary_conditions()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::update_boundary_conditions () protected
Update non-zero constraints if the boundary is time dependent. Note: not implemented for the block fluid dynamics application.
Definition at line 2224 of file navier_stokes_base.cc.
References BoundaryConditions::function, BoundaryConditions::function_weak, BoundaryConditions::partial_slip, and BoundaryConditions::pressure.
update_mortar_configuration()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::update_mortar_configuration () inline protected virtual
Update mortar configuration.
When the rotor domain is rotated, the mortar cells need to be reinitialized according to the new rotor-stator interface configuration.
Reimplemented in FluidDynamicsMatrixBased< dim >, and FluidDynamicsMatrixFree< dim >.
Definition at line 299 of file navier_stokes_base.h.
update_multi_stage_solution()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::update_multi_stage_solution (double time_step) protected virtual
\(u_{n+1} = u_n + time_step * \sum_{i=1}^{N_{stages}} b_i * k_i \)
Parameters
time_step The current time step to build the solution at the next time step
Definition at line 669 of file navier_stokes_base.cc.
update_multiphysics_time_average_solution()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::update_multiphysics_time_average_solution () protected pure virtual
Update the time average velocity field solution.
Implemented in FluidDynamicsBlock< dim >, FluidDynamicsMatrixBased< dim >, and FluidDynamicsMatrixFree< dim >.
update_solutions_for_fluid_dynamics()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::update_solutions_for_fluid_dynamics () inline protected virtual
Required only for the matrix-free solver to update multiphysics solutions within iterate function.
Reimplemented in FluidDynamicsMatrixFree< dim >.
Definition at line 319 of file navier_stokes_base.h.
update_solutions_for_multiphysics()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::update_solutions_for_multiphysics () inline protected virtual
Required only for the matrix-free solver to update solutions within iterate function.
Reimplemented in FluidDynamicsMatrixFree< dim >.
Definition at line 312 of file navier_stokes_base.h.
verify_consistency_of_boundary_conditions()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::verify_consistency_of_boundary_conditions () inline protected
Verify consistency of the input parameters for boundary conditions to ensure that for every boundary condition within the triangulation, a boundary condition has been specified in the input file.
Definition at line 957 of file navier_stokes_base.h.
References NavierStokesBase< dim, VectorType, DofsType >::simulation_parameters, and NavierStokesBase< dim, VectorType, DofsType >::triangulation.
write_checkpoint()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::write_checkpoint () protected virtual
Write the checkpoint.
Reimplemented in CFDDEMSolver< dim >, FluidDynamicsSharp< dim >, and FluidDynamicsNitsche< dim, spacedim >.
Definition at line 3180 of file navier_stokes_base.cc.
References Parameters::average_velocity_profile.
write_output_forces()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::write_output_forces () protected
Writes the forces per boundary condition to a text file output.
Definition at line 3042 of file navier_stokes_base.cc.
write_output_results()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::write_output_results (const VectorType & solution) protected
Generate post-processing parallel VTU files from vector of solution_output_struct.
Parameters
[in] solution Vector of present solution
Definition at line 2884 of file navier_stokes_base.cc.
write_output_torques()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::write_output_torques () protected
Writes the torques per boundary condition to a text file output.
Definition at line 3063 of file navier_stokes_base.cc.
Member Data Documentation
apparent_viscosity_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::apparent_viscosity_table protected
Definition at line 1069 of file navier_stokes_base.h.
assemblers
template<int dim, typename VectorType , typename DofsType > std::vector<std::shared_ptr<NavierStokesAssemblerBase<dim> > > NavierStokesBase< dim, VectorType, DofsType >::assemblers protected
Definition at line 1056 of file navier_stokes_base.h.
average_solution
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::average_solution protected
Definition at line 1074 of file navier_stokes_base.h.
average_velocities
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<AverageVelocities<dim, VectorType, DofsType> > NavierStokesBase< dim, VectorType, DofsType >::average_velocities protected
Definition at line 1073 of file navier_stokes_base.h.
cell_quadrature
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<Quadrature<dim> > NavierStokesBase< dim, VectorType, DofsType >::cell_quadrature protected
Definition at line 1043 of file navier_stokes_base.h.
computing_timer
template<int dim, typename VectorType , typename DofsType > TimerOutput NavierStokesBase< dim, VectorType, DofsType >::computing_timer protected
Definition at line 984 of file navier_stokes_base.h.
dof_handler
template<int dim, typename VectorType , typename DofsType > DoFHandler<dim> NavierStokesBase< dim, VectorType, DofsType >::dof_handler protected
Definition at line 981 of file navier_stokes_base.h.
dynamic_zero_constraints
template<int dim, typename VectorType , typename DofsType > AffineConstraints<double> NavierStokesBase< dim, VectorType, DofsType >::dynamic_zero_constraints protected
Dynamic homogeneous constraints used for temperature-dependent solid domain constraints
Definition at line 1098 of file navier_stokes_base.h.
enstrophy_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::enstrophy_table protected
Definition at line 1065 of file navier_stokes_base.h.
error_table
template<int dim, typename VectorType , typename DofsType > ConvergenceTable NavierStokesBase< dim, VectorType, DofsType >::error_table protected
Definition at line 1080 of file navier_stokes_base.h.
evaluation_point
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::evaluation_point protected
Definition at line 1001 of file navier_stokes_base.h.
exact_solution
template<int dim, typename VectorType , typename DofsType > Function<dim>* NavierStokesBase< dim, VectorType, DofsType >::exact_solution protected
Definition at line 990 of file navier_stokes_base.h.
face_quadrature
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<Quadrature<dim - 1> > NavierStokesBase< dim, VectorType, DofsType >::face_quadrature protected
Definition at line 1044 of file navier_stokes_base.h.
fe
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<FESystem<dim> > NavierStokesBase< dim, VectorType, DofsType >::fe protected
Definition at line 982 of file navier_stokes_base.h.
fe_values_temperature
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<FEValues<dim> > NavierStokesBase< dim, VectorType, DofsType >::fe_values_temperature protected
FEValues object used for temperature-dependent solid domain constraints.
Definition at line 1089 of file navier_stokes_base.h.
fe_values_vof
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<FEValues<dim> > NavierStokesBase< dim, VectorType, DofsType >::fe_values_vof protected
FEValues object used for temperature-dependent solid domain constraints in VOF simulations
Definition at line 1092 of file navier_stokes_base.h.
flow_control
template<int dim, typename VectorType , typename DofsType > FlowControl<dim> NavierStokesBase< dim, VectorType, DofsType >::flow_control protected
Definition at line 994 of file navier_stokes_base.h.
flow_rate_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::flow_rate_table protected
Definition at line 1071 of file navier_stokes_base.h.
forces_on_boundaries
template<int dim, typename VectorType , typename DofsType > std::vector<std::map<types::boundary_id, Tensor<1, dim> > > NavierStokesBase< dim, VectorType, DofsType >::forces_on_boundaries protected
Definition at line 1084 of file navier_stokes_base.h.
forces_tables
template<int dim, typename VectorType , typename DofsType > std::map<types::boundary_id, TableHandler> NavierStokesBase< dim, VectorType, DofsType >::forces_tables protected
Definition at line 1085 of file navier_stokes_base.h.
forcing_function
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<Function<dim> > NavierStokesBase< dim, VectorType, DofsType >::forcing_function protected
Definition at line 991 of file navier_stokes_base.h.
kinetic_energy_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::kinetic_energy_table protected
Definition at line 1068 of file navier_stokes_base.h.
local_evaluation_point
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::local_evaluation_point protected
Definition at line 1002 of file navier_stokes_base.h.
locally_owned_dofs
template<int dim, typename VectorType , typename DofsType > DofsType NavierStokesBase< dim, VectorType, DofsType >::locally_owned_dofs protected
Definition at line 973 of file navier_stokes_base.h.
locally_relevant_dofs
template<int dim, typename VectorType , typename DofsType > DofsType NavierStokesBase< dim, VectorType, DofsType >::locally_relevant_dofs protected
Definition at line 974 of file navier_stokes_base.h.
mapping
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<Mapping<dim> > NavierStokesBase< dim, VectorType, DofsType >::mapping protected
Definition at line 1042 of file navier_stokes_base.h.
mapping_cache
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<MappingQCache<dim> > NavierStokesBase< dim, VectorType, DofsType >::mapping_cache protected
Definition at line 1053 of file navier_stokes_base.h.
mesh_controller
template<int dim, typename VectorType , typename DofsType > MeshController NavierStokesBase< dim, VectorType, DofsType >::mesh_controller protected
Definition at line 1077 of file navier_stokes_base.h.
mortar_coupling_evaluator
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<NavierStokesCouplingEvaluation<dim, double> > NavierStokesBase< dim, VectorType, DofsType >::mortar_coupling_evaluator protected
Definition at line 1050 of file navier_stokes_base.h.
mortar_coupling_operator
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<CouplingOperator<dim, double> > NavierStokesBase< dim, VectorType, DofsType >::mortar_coupling_operator protected
Definition at line 1048 of file navier_stokes_base.h.
mortar_manager
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<MortarManagerCircle<dim> > NavierStokesBase< dim, VectorType, DofsType >::mortar_manager protected
Definition at line 1047 of file navier_stokes_base.h.
mpi_communicator
template<int dim, typename VectorType , typename DofsType > MPI_Comm NavierStokesBase< dim, VectorType, DofsType >::mpi_communicator protected
Definition at line 976 of file navier_stokes_base.h.
multiphysics
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<MultiphysicsInterface<dim> > NavierStokesBase< dim, VectorType, DofsType >::multiphysics protected
Definition at line 1059 of file navier_stokes_base.h.
n_mpi_processes
template<int dim, typename VectorType , typename DofsType > const unsigned int NavierStokesBase< dim, VectorType, DofsType >::n_mpi_processes protected
Definition at line 977 of file navier_stokes_base.h.
newton_update
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::newton_update protected
Definition at line 1003 of file navier_stokes_base.h.
nonzero_constraints
template<int dim, typename VectorType , typename DofsType > AffineConstraints<double> NavierStokesBase< dim, VectorType, DofsType >::nonzero_constraints protected
Definition at line 998 of file navier_stokes_base.h.
number_quadrature_points
template<int dim, typename VectorType , typename DofsType > unsigned int NavierStokesBase< dim, VectorType, DofsType >::number_quadrature_points protected
Definition at line 1039 of file navier_stokes_base.h.
present_solution
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::present_solution protected
Definition at line 1004 of file navier_stokes_base.h.
pressure_drop_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::pressure_drop_table protected
Definition at line 1070 of file navier_stokes_base.h.
pressure_fem_degree
template<int dim, typename VectorType , typename DofsType > const unsigned int NavierStokesBase< dim, VectorType, DofsType >::pressure_fem_degree protected
Definition at line 1038 of file navier_stokes_base.h.
pressure_power_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::pressure_power_table protected
Definition at line 1066 of file navier_stokes_base.h.
previous_solutions
template<int dim, typename VectorType , typename DofsType > std::vector<VectorType> NavierStokesBase< dim, VectorType, DofsType >::previous_solutions protected
Definition at line 1008 of file navier_stokes_base.h.
pvdhandler
template<int dim, typename VectorType , typename DofsType > PVDHandler NavierStokesBase< dim, VectorType, DofsType >::pvdhandler protected
Definition at line 987 of file navier_stokes_base.h.
sdirk_vectors
template<int dim, typename VectorType , typename DofsType > SDIRKVectors NavierStokesBase< dim, VectorType, DofsType >::sdirk_vectors protected
Instance of SDIRK-related vectors.
Definition at line 1034 of file navier_stokes_base.h.
simulation_control
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<SimulationControl> NavierStokesBase< dim, VectorType, DofsType >::simulation_control protected
Definition at line 1062 of file navier_stokes_base.h.
simulation_parameters
template<int dim, typename VectorType , typename DofsType > SimulationParameters<dim> NavierStokesBase< dim, VectorType, DofsType >::simulation_parameters protected
Definition at line 986 of file navier_stokes_base.h.
stasis_constraint_structs
template<int dim, typename VectorType , typename DofsType > std::vector<StasisConstraintWithTemperature> NavierStokesBase< dim, VectorType, DofsType >::stasis_constraint_structs protected
Vector containing solid domain constraint structs for temperature-dependent solid domain constraints in VOF simulations
Definition at line 1095 of file navier_stokes_base.h.
system_rhs
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::system_rhs protected
Definition at line 1005 of file navier_stokes_base.h.
this_mpi_process
template<int dim, typename VectorType , typename DofsType > const unsigned int NavierStokesBase< dim, VectorType, DofsType >::this_mpi_process protected
Definition at line 978 of file navier_stokes_base.h.
torques_tables
template<int dim, typename VectorType , typename DofsType > std::map<types::boundary_id, TableHandler> NavierStokesBase< dim, VectorType, DofsType >::torques_tables protected
Definition at line 1086 of file navier_stokes_base.h.
triangulation
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<parallel::DistributedTriangulationBase<dim> > NavierStokesBase< dim, VectorType, DofsType >::triangulation protected
Definition at line 980 of file navier_stokes_base.h.
velocity_fem_degree
template<int dim, typename VectorType , typename DofsType > const unsigned int NavierStokesBase< dim, VectorType, DofsType >::velocity_fem_degree protected
Definition at line 1037 of file navier_stokes_base.h.
viscous_dissipation_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::viscous_dissipation_table protected
Definition at line 1067 of file navier_stokes_base.h.
zero_constraints
template<int dim, typename VectorType , typename DofsType > AffineConstraints<double> NavierStokesBase< dim, VectorType, DofsType >::zero_constraints protected
Definition at line 997 of file navier_stokes_base.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/navier_stokes_base.h
/home/runner/work/lethe/lethe/source/solvers/navier_stokes_base.cc