Lethe Open-Source Library: CFDDEMMatrixFree< dim > Class Template Reference
CFDDEMMatrixFree< dim > Class Template Reference
#include <cfd_dem_coupling_matrix_free.h>
Public Member Functions
CFDDEMMatrixFree (CFDDEMSimulationParameters< dim > &param)
void solve () override
Public Member Functions inherited from FluidDynamicsVANSMatrixFree< dim >
FluidDynamicsVANSMatrixFree (CFDDEMSimulationParameters< dim > &param)
void solve () override
Public Member Functions inherited from FluidDynamicsMatrixFree< dim >
FluidDynamicsMatrixFree (SimulationParameters< dim > &nsparam)
~FluidDynamicsMatrixFree ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
PhysicsSolver ()
virtual ~PhysicsSolver ()
void solve_governing_system ()
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void dem_setup_parameters ()
void setup_distribution_type ()
std::shared_ptr< Insertion< dim, DEM::CFDDEMProperties::PropertiesIndex > > set_insertion_type ()
std::shared_ptr< Integrator< dim, DEM::CFDDEMProperties::PropertiesIndex > > set_integrator_type ()
void initialize_dem_parameters ()
void read_dem () override
void set_initial_condition (const Parameters::FluidDynamicsInitialConditionType initial_condition_type, const bool restart=false) override
std::vector< OutputStructTableHandler > gather_tables () override
void write_checkpoint () override
void read_checkpoint () override
void check_contact_detection_method (unsigned int counter)
void load_balance ()
void insert_particles ()
void add_fluid_particle_interaction ()
void particle_wall_contact_force ()
void write_dem_output_results ()
void report_particle_statistics ()
void postprocess_fd (bool first_iteration) override
void postprocess_cfd_dem ()
void dynamic_flow_control () override
void sort_particles_into_subdomains_and_cells ()
void dem_iterator (unsigned int counter)
void update_dem_time_step ()
void dem_contact_build (unsigned int counter)
Private Attributes
unsigned int coupling_frequency
Tensor< 1, 3 > g
ParticleInteractionOutcomes< DEM::CFDDEMProperties::PropertiesIndex > contact_outcome
std::vector< double > displacement
std::vector< double > MOI
double neighborhood_threshold_squared
std::vector< std::shared_ptr< Distribution > > size_distribution_object_container
double maximum_particle_diameter
double smallest_contact_search_criterion
OngoingCollisionLog< dim > ongoing_collision_log
CompletedCollisionLog< dim > collision_event_log
DEMContactManager< dim, DEM::CFDDEMProperties::PropertiesIndex > contact_manager
LagrangianLoadBalancing< dim, DEM::CFDDEMProperties::PropertiesIndex > load_balancing
ParticlePointLineForce< dim, DEM::CFDDEMProperties::PropertiesIndex > particle_point_line_contact_force_object
std::shared_ptr< Integrator< dim, DEM::CFDDEMProperties::PropertiesIndex > > integrator_object
std::shared_ptr< Insertion< dim, DEM::CFDDEMProperties::PropertiesIndex > > insertion_object
std::shared_ptr< ParticleParticleContactForceBase< dim, DEM::CFDDEMProperties::PropertiesIndex > > particle_particle_contact_force_object
std::shared_ptr< ParticleWallContactForceBase< dim, DEM::CFDDEMProperties::PropertiesIndex > > particle_wall_contact_force_object
Visualization< dim, DEM::CFDDEMProperties::PropertiesIndex > visualization_object
BoundaryCellsInformation< dim > boundary_cell_object
dem_data_structures< dim >::solid_surfaces_mesh_information solid_surfaces_mesh_info
dem_data_structures< dim >::boundary_points_and_normal_vectors updated_boundary_points_and_normal_vectors
dem_data_structures< dim >::vector_on_boundary forces_boundary_information
dem_data_structures< dim >::vector_on_boundary torques_boundary_information
DEM::dem_data_structures< dim >::periodic_boundaries_cells_info periodic_boundaries_cells_information
PeriodicBoundariesManipulator< dim > periodic_boundaries_object
AdaptiveSparseContacts< dim, DEM::CFDDEMProperties::PropertiesIndex > sparse_contacts_object
unsigned int contact_search_counter
unsigned int contact_search_total_number
statistics contact_list
DEM::ParticleProperties< dim, DEM::CFDDEMProperties::PropertiesIndex > properties_class
PVDHandler grid_pvdhandler
PVDHandler particles_pvdhandler
DEMSolverParameters< dim > dem_parameters
double dem_time_step
double rayleigh_time_step
TableHandler table_phase_volumes
DEMActionManager * dem_action_manager
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Protected Member Functions inherited from FluidDynamicsVANSMatrixFree< dim >
void setup_dofs () override
void assemble_system_rhs () override
virtual void finish_time_step_fd ()
std::vector< OutputStruct< dim, LinearAlgebra::distributed::Vector< double > > > gather_output_hook () override
void create_GMG () override
void initialize_GMG () override
void evaluate_time_derivative_void_fraction ()
Protected Member Functions inherited from FluidDynamicsMatrixFree< dim >
virtual void setup_dofs_fd () override
void multi_stage_preresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method) override
virtual void multi_stage_postresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method, double time_step) override
virtual void update_multi_stage_solution (double time_step) override
virtual void set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false) override
virtual void assemble_system_matrix () override
virtual void update_mortar_configuration () override
void reinit_mortar_operators_mf ()
virtual void update_multiphysics_time_average_solution () override
virtual void update_solutions_for_multiphysics () override
virtual void update_solutions_for_fluid_dynamics () override
void calculate_time_derivative_previous_solutions ()
void setup_preconditioner () override
void solve_linear_system () override
void print_mg_setup_times ()
Protected Member Functions inherited from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual LinearAlgebra::distributed::Vector< double > & get_evaluation_point () override
virtual LinearAlgebra::distributed::Vector< double > & get_local_evaluation_point () override
virtual LinearAlgebra::distributed::Vector< double > & get_newton_update () override
virtual LinearAlgebra::distributed::Vector< double > & get_present_solution () override
virtual LinearAlgebra::distributed::Vector< double > & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
double get_residual_rescale_metric () const override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
void postprocessing_forces (const LinearAlgebra::distributed::Vector< double > &evaluation_point)
void postprocessing_torques (const LinearAlgebra::distributed::Vector< double > &evaluation_point)
virtual void iterate ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
void transfer_solution (SolutionTransfer< dim, LinearAlgebra::distributed::Vector< double > > &solution_transfer, std::vector< SolutionTransfer< dim, LinearAlgebra::distributed::Vector< double > > > &previous_solutions_transfer)
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void reinit_mortar_operators ()
std::shared_ptr< Mapping< dim > > get_mapping ()
void rotate_rotor_mapping (const bool is_first)
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
void gather_output_results (const LinearAlgebra::distributed::Vector< double > &solution, std::vector< OutputStruct< dim, LinearAlgebra::distributed::Vector< double > > > &solution_output_structs)
void write_output_results (const LinearAlgebra::distributed::Vector< double > &solution)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
LinearAlgebra::distributed::Vector< double > init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes inherited from FluidDynamicsVANSMatrixFree< dim >
CFDDEMSimulationParameters< dim > cfd_dem_simulation_parameters
MappingQGeneric< dim > particle_mapping
Particles::ParticleHandler< dim, dim > particle_handler
ParticleProjector< dim > particle_projector
bool has_periodic_boundaries
Tensor< 1, dim > periodic_offset
unsigned int periodic_direction
VectorType time_derivative_void_fraction
Protected Attributes inherited from FluidDynamicsMatrixFree< dim >
std::shared_ptr< NavierStokesOperatorBase< dim, double > > system_operator
std::shared_ptr< MFNavierStokesPreconditionGMGBase< dim > > gmg_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
VectorType time_derivative_previous_solutions
DoFHandler< dim > dof_handler_fe_q_iso_q1
TrilinosWrappers::MPI::Vector multiphysics_average_velocities
std::shared_ptr< TrilinosWrappers::MPI::Vector > multiphysics_present_solution
std::shared_ptr< std::vector< TrilinosWrappers::MPI::Vector > > multiphysics_previous_solutions
VectorType temperature_present_solution
std::shared_ptr< PhysicalPropertiesManager > physical_properties_manager
Protected Attributes inherited from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< DoFHandler< dim > > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
PVDHandler pvdhandler_boundary
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
bool use_manifold_for_normal
LinearAlgebra::distributed::Vector< double > evaluation_point
LinearAlgebra::distributed::Vector< double > local_evaluation_point
LinearAlgebra::distributed::Vector< double > newton_update
std::shared_ptr< LinearAlgebra::distributed::Vector< double > > present_solution
LinearAlgebra::distributed::Vector< double > system_rhs
std::shared_ptr< std::vector< LinearAlgebra::distributed::Vector< double > > > previous_solutions
SDIRKVectors sdirk_vectors
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::shared_ptr< MortarManagerCircle< dim > > mortar_manager
std::shared_ptr< CouplingOperator< dim, double > > mortar_coupling_operator
std::shared_ptr< NavierStokesCouplingEvaluation< dim, double > > mortar_coupling_evaluator
std::shared_ptr< MappingQCache< dim > > mapping_cache
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, LinearAlgebra::distributed::Vector< double >, IndexSet > > average_velocities
LinearAlgebra::distributed::Vector< double > average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Detailed Description
template<int dim>
class CFDDEMMatrixFree< dim >
Solver class for coupled Computational Fluid Dynamics and Discrete Element Method (CFD-DEM) simulations using a matrix-free formulation.
This class implements a two-way coupled CFD-DEM solver that combines the Volume-averaged Navier-Stokes (VANS) equations for fluid flow with the soft-sphere Discrete Element Method for particle dynamics. The solver enables simulation of fluid-particle interactions in systems containing dense particle suspensions.
The CFD component uses Galerkin Least Squares (GLS) stabilization for the VANS equations, while the DEM component handles particle-particle and particle-wall collisions using the soft-sphere contact model. A matrix-free formulation is used to solve the VANS equation.
Template Parameters
dim Spatial dimension of the simulation (2 or 3). While 2D simulation are theoretically supported, they have not been tested.
Definition at line 41 of file cfd_dem_coupling_matrix_free.h.
Constructor & Destructor Documentation
CFDDEMMatrixFree()
template<int dim> CFDDEMMatrixFree< dim >::CFDDEMMatrixFree (CFDDEMSimulationParameters< dim > & param)
Constructor for the CFD-DEM matrix-free solver.
Parameters
[in] param Simulation parameters containing all CFD-DEM configuration options
Definition at line 29 of file cfd_dem_coupling_matrix_free.cc.
Member Function Documentation
add_fluid_particle_interaction()
template<int dim> void CFDDEMMatrixFree< dim >::add_fluid_particle_interaction () private
Calculate and add fluid-particle interaction forces and torques.
Computes the hydrodynamic forces acting on particles due to fluid motion and adds them to the particle force container for use in DEM integration.
Reference to torque vector from contact outcomes
Reference to force vector from contact outcomes
Definition at line 786 of file cfd_dem_coupling_matrix_free.cc.
References DEM::CFDDEMProperties::fem_drag_x, DEM::CFDDEMProperties::fem_drag_y, DEM::CFDDEMProperties::fem_drag_z, DEM::CFDDEMProperties::fem_force_one_way_coupling_x, DEM::CFDDEMProperties::fem_force_one_way_coupling_y, DEM::CFDDEMProperties::fem_force_one_way_coupling_z, DEM::CFDDEMProperties::fem_force_two_way_coupling_x, DEM::CFDDEMProperties::fem_force_two_way_coupling_y, DEM::CFDDEMProperties::fem_force_two_way_coupling_z, DEM::CFDDEMProperties::fem_torque_x, DEM::CFDDEMProperties::fem_torque_y, and DEM::CFDDEMProperties::fem_torque_z.
check_contact_detection_method()
template<int dim> void CFDDEMMatrixFree< dim >::check_contact_detection_method (unsigned int counter) private
Check if contact detection is required and execute it if necessary.
Determines whether a contact detection step should be performed based on the contact detection frequency and executes the appropriate contact detection algorithm.
Parameters
[in] counter Current DEM iteration number
Definition at line 731 of file cfd_dem_coupling_matrix_free.cc.
References Parameters::Lagrangian::ModelParameters< dim >::contact_detection_frequency, Parameters::Lagrangian::ModelParameters< dim >::contact_detection_method, and find_particle_contact_detection_step().
dem_contact_build()
template<int dim> void CFDDEMMatrixFree< dim >::dem_contact_build (unsigned int counter) private
Perform contact detection and build contact lists.
Checks if a contact search should be performed based on the contact detection frequency and executes the appropriate contact detection algorithm to identify particle-particle and particle-wall contacts.
Parameters
[in] counter Current DEM iteration number
Definition at line 1283 of file cfd_dem_coupling_matrix_free.cc.
dem_iterator()
template<int dim> void CFDDEMMatrixFree< dim >::dem_iterator (unsigned int counter) private
Execute a DEM time step.
Performs a full DEM time step including particle-particle and particle-wall contact force calculations, time integration of particle motion, and updates to particle positions and velocities.
Parameters
[in] counter Current DEM iteration number
Definition at line 1202 of file cfd_dem_coupling_matrix_free.cc.
dem_setup_parameters()
template<int dim> void CFDDEMMatrixFree< dim >::dem_setup_parameters () private
Set up the various parameters related to the DEM simulation.
Initializes DEM-specific parameters including contact detection methods, integration schemes, and material properties based on the simulation parameters provided during construction.
Definition at line 95 of file cfd_dem_coupling_matrix_free.cc.
References DEMActionManager::get_action_manager(), Parameters::Lagrangian::BCDEM::periodic, and set_particle_particle_contact_force_model().
dynamic_flow_control()
template<int dim> void CFDDEMMatrixFree< dim >::dynamic_flow_control () override private virtual
Calculate dynamic flow control accounting for void fraction.
Performs dynamic flow control calculations that incorporate the local void fraction (porosity) field in the average velocity computation, enabling proper flow control in particle-laden flows.
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 1097 of file cfd_dem_coupling_matrix_free.cc.
References announce_string(), calculate_average_velocity(), Parameters::SimulationControl::steady, and Parameters::verbose.
gather_tables()
template<int dim> std::vector< OutputStructTableHandler > CFDDEMMatrixFree< dim >::gather_tables () override private virtual
Gather TableHandler objects for serialization during checkpointing.
Collects all TableHandler objects that need to be serialized and deserialized during checkpoint operations, including their associated file names for proper storage and retrieval.
Returns
Vector of OutputStructTableHandler containing references to TableHandler objects and their corresponding file names
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 448 of file cfd_dem_coupling_matrix_free.cc.
References Parameters::PostProcessing::calculate_phase_volumes, and Parameters::PostProcessing::phase_volumes_output_name.
initialize_dem_parameters()
template<int dim> void CFDDEMMatrixFree< dim >::initialize_dem_parameters () private
Initialize fundamental DEM simulation parameters.
Sets up basic DEM parameters including time stepping, contact detection frequency, and other core simulation settings.
Definition at line 286 of file cfd_dem_coupling_matrix_free.cc.
References set_particle_wall_contact_force_model().
insert_particles()
template<int dim> void CFDDEMMatrixFree< dim >::insert_particles () private
Check if particles need to be inserted and perform insertion.
Determines if new particles should be inserted into the simulation domain based on the insertion parameters and executes particle insertion using the configured insertion method.
Definition at line 831 of file cfd_dem_coupling_matrix_free.cc.
load_balance()
template<int dim> void CFDDEMMatrixFree< dim >::load_balance () private
Check if load balancing is required and perform it if necessary.
Evaluates the current load distribution across MPI processes and performs load balancing to maintain computational efficiency when particle distribution becomes uneven.
Definition at line 771 of file cfd_dem_coupling_matrix_free.cc.
particle_wall_contact_force()
template<int dim> void CFDDEMMatrixFree< dim >::particle_wall_contact_force () private
Calculate contact forces between particles and walls.
Computes collision forces and torques resulting from particle-wall interactions using the soft-sphere contact model.
Definition at line 858 of file cfd_dem_coupling_matrix_free.cc.
postprocess_cfd_dem()
template<int dim> void CFDDEMMatrixFree< dim >::postprocess_cfd_dem () private
Perform CFD-DEM coupled post-processing after each iteration.
Executes post-processing operations specific to the coupled CFD-DEM simulation including coupled field analysis and specialized output generation.
Definition at line 1036 of file cfd_dem_coupling_matrix_free.cc.
References calculate_fluid_and_particle_volumes(), and Parameters::verbose.
postprocess_fd()
template<int dim> void CFDDEMMatrixFree< dim >::postprocess_fd (bool first_iteration) override private virtual
Perform fluid dynamics post-processing after each iteration.
Executes post-processing operations specific to the fluid dynamics component including output writing and monitoring.
Parameters
[in] first_iteration Flag indicating if this is the first iteration
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 1017 of file cfd_dem_coupling_matrix_free.cc.
References NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::postprocess_fd().
read_checkpoint()
template<int dim> void CFDDEMMatrixFree< dim >::read_checkpoint () override private virtual
Read CFD-DEM simulation checkpoint files.
Loads the complete simulation state from previously written checkpoint files to restart a CFD-DEM simulation from a specific time step.
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 564 of file cfd_dem_coupling_matrix_free.cc.
References deserialize_tables_vector(), and NavierStokesBase< dim, VectorType, DofsType >::gather_tables().
read_dem()
template<int dim> void CFDDEMMatrixFree< dim >::read_dem () override private virtual
Read DEM restart files from a previous simulation.
Loads particle data, contact information, and other DEM state variables from checkpoint files to continue a previously interrupted simulation.
Reimplemented from FluidDynamicsVANSMatrixFree< dim >.
Definition at line 356 of file cfd_dem_coupling_matrix_free.cc.
References convert_particle_handler(), and DEM::DEMProperties::n_properties.
report_particle_statistics()
template<int dim> void CFDDEMMatrixFree< dim >::report_particle_statistics () private
Calculate and report particle statistics to the terminal.
Computes and displays comprehensive statistics about particle behavior including minimum, maximum, and average values for linear velocity, angular velocity, kinetic energies, and contact search performance metrics.
Definition at line 921 of file cfd_dem_coupling_matrix_free.cc.
References add_statistics_to_table_handler(), announce_string(), DEM::calculate_granular_statistics(), DEM::omega, DEM::rotational_kinetic_energy, DEM::translational_kinetic_energy, and DEM::velocity.
set_initial_condition()
template<int dim> void CFDDEMMatrixFree< dim >::set_initial_condition (const Parameters::FluidDynamicsInitialConditionType initial_condition_type, const bool restart = false) inline override private virtual
Set the initial condition. The version in this class does not output the solution, since the void fraction is not initialized yet.
Parameters
[in] initial_condition_type Type of method use to impose initial condition.
[in] restart Indicator if the simulation is being restarted or not.
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 134 of file cfd_dem_coupling_matrix_free.h.
References NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::multiphysics, PhysicsSolver< VectorType >::pcout, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::refine_mesh(), FluidDynamicsMatrixFree< dim >::set_initial_condition_fd(), and NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::simulation_parameters.
set_insertion_type()
template<int dim> std::shared_ptr< Insertion< dim, DEM::CFDDEMProperties::PropertiesIndex > > CFDDEMMatrixFree< dim >::set_insertion_type () private
Set up the particle insertion method for the simulation.
Creates and configures the appropriate insertion object based on the simulation parameters (e.g., volume insertion, plane insertion, etc.).
Returns
Shared pointer to the configured insertion object
Definition at line 211 of file cfd_dem_coupling_matrix_free.cc.
set_integrator_type()
template<int dim> std::shared_ptr< Integrator< dim, DEM::CFDDEMProperties::PropertiesIndex > > CFDDEMMatrixFree< dim >::set_integrator_type () private
Set up the time integration method for particle motion.
Creates and configures the appropriate integration scheme for solving particle equations of motion (e.g., velocity Verlet, explicit Euler).
Returns
Shared pointer to the configured integration object
Definition at line 263 of file cfd_dem_coupling_matrix_free.cc.
setup_distribution_type()
template<int dim> void CFDDEMMatrixFree< dim >::setup_distribution_type () private
Initialize the particle size distribution and related parameters.
Sets up the particle size distribution type for the simulation and calculates the maximum particle diameter and neighborhood threshold squared values required for contact detection algorithms.
Definition at line 35 of file cfd_dem_coupling_matrix_free.cc.
References Parameters::Lagrangian::LagrangianPhysicalProperties::diameter_max_cutoff, Parameters::Lagrangian::LagrangianPhysicalProperties::diameter_min_cutoff, Parameters::Lagrangian::LagrangianPhysicalProperties::distribution_type, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_average_diameter, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_custom_diameter, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_custom_probability, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_size_std, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number, and Parameters::Lagrangian::LagrangianPhysicalProperties::seed_for_distributions.
solve()
template<int dim> void CFDDEMMatrixFree< dim >::solve () override virtual
Engine of the CFD-DEM solver. Calls all the necessary functions to set parameters, solve the simulation, and finish the simulation.
Reimplemented from FluidDynamicsMatrixFree< dim >.
Definition at line 1360 of file cfd_dem_coupling_matrix_free.cc.
References announce_string(), Parameters::Timer::end, read_mesh_and_manifolds(), and time_stepping_is_bdf().
sort_particles_into_subdomains_and_cells()
template<int dim> void CFDDEMMatrixFree< dim >::sort_particles_into_subdomains_and_cells () inline private
Sort particles into subdomains and cells for efficient processing.
Redistributes particles among computational subdomains and associates them with their containing cells, then reinitialize containers that depend on local particle identifiers.
Definition at line 1163 of file cfd_dem_coupling_matrix_free.cc.
References DEM::CFDDEMProperties::dp, and DEM::CFDDEMProperties::mass.
update_dem_time_step()
template<int dim> void CFDDEMMatrixFree< dim >::update_dem_time_step () inline private
Calculate the new DEM time-step.
Calculate the new DEM time-step in a CFD-DEM simulation with adaptive time-stepping
Definition at line 326 of file cfd_dem_coupling_matrix_free.h.
References CFDDEMMatrixFree< dim >::coupling_frequency, CFDDEMMatrixFree< dim >::dem_time_step, PhysicsSolver< VectorType >::pcout, CFDDEMMatrixFree< dim >::rayleigh_time_step, and NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::simulation_control.
write_checkpoint()
template<int dim> void CFDDEMMatrixFree< dim >::write_checkpoint () override private virtual
Write CFD-DEM simulation checkpoint files.
Saves the complete state of the CFD-DEM simulation including fluid variables, particle data, and auxiliary information to enable simulation restart from the current time step.
Reimplemented from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 466 of file cfd_dem_coupling_matrix_free.cc.
References NavierStokesBase< dim, VectorType, DofsType >::gather_tables(), and serialize_tables_vector().
write_dem_output_results()
template<int dim> void CFDDEMMatrixFree< dim >::write_dem_output_results () private
Write DEM simulation results to output files.
Generates visualization output files containing particle positions, velocities, forces, and other relevant DEM variables in parallel VTU format for post-processing.
Definition at line 893 of file cfd_dem_coupling_matrix_free.cc.
References Visualization< dim, PropertiesIndex >::build_patches().
Member Data Documentation
boundary_cell_object
template<int dim> BoundaryCellsInformation<dim> CFDDEMMatrixFree< dim >::boundary_cell_object private
Information about boundary cells for contact detection.
Definition at line 429 of file cfd_dem_coupling_matrix_free.h.
collision_event_log
template<int dim> CompletedCollisionLog<dim> CFDDEMMatrixFree< dim >::collision_event_log private
Object to store completed collision events.
Stores complete collision event data including start and end information for post-processing and analysis purposes.
Definition at line 390 of file cfd_dem_coupling_matrix_free.h.
contact_list
template<int dim> statistics CFDDEMMatrixFree< dim >::contact_list private
Statistics container for timing and contact list information.
Definition at line 465 of file cfd_dem_coupling_matrix_free.h.
contact_manager
template<int dim> DEMContactManager<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMMatrixFree< dim >::contact_manager private
Manager for particle-particle and particle-wall contact detection and handling
Definition at line 395 of file cfd_dem_coupling_matrix_free.h.
contact_outcome
template<int dim> ParticleInteractionOutcomes<DEM::CFDDEMProperties::PropertiesIndex> CFDDEMMatrixFree< dim >::contact_outcome private
Container for particle interaction outcomes (forces and torques)
Definition at line 356 of file cfd_dem_coupling_matrix_free.h.
contact_search_counter
template<int dim> unsigned int CFDDEMMatrixFree< dim >::contact_search_counter private
Counter for contact searches performed in the current CFD iteration.
Definition at line 459 of file cfd_dem_coupling_matrix_free.h.
contact_search_total_number
template<int dim> unsigned int CFDDEMMatrixFree< dim >::contact_search_total_number private
Total number of contact searches since simulation start.
Definition at line 462 of file cfd_dem_coupling_matrix_free.h.
coupling_frequency
template<int dim> unsigned int CFDDEMMatrixFree< dim >::coupling_frequency private
Frequency of coupling between CFD and DEM solvers (in DEM time steps)
Definition at line 348 of file cfd_dem_coupling_matrix_free.h.
dem_action_manager
template<int dim> DEMActionManager* CFDDEMMatrixFree< dim >::dem_action_manager private
Pointer to DEM action manager for handling DEM-specific operations.
Definition at line 491 of file cfd_dem_coupling_matrix_free.h.
dem_parameters
template<int dim> DEMSolverParameters<dim> CFDDEMMatrixFree< dim >::dem_parameters private
DEM simulation parameters container.
Definition at line 478 of file cfd_dem_coupling_matrix_free.h.
dem_time_step
template<int dim> double CFDDEMMatrixFree< dim >::dem_time_step private
Time step size for DEM integration.
Definition at line 481 of file cfd_dem_coupling_matrix_free.h.
displacement
template<int dim> std::vector<double> CFDDEMMatrixFree< dim >::displacement private
Displacement vector for particle motion calculations.
Definition at line 359 of file cfd_dem_coupling_matrix_free.h.
forces_boundary_information
template<int dim> dem_data_structures<dim>::vector_on_boundary CFDDEMMatrixFree< dim >::forces_boundary_information private
Force information stored on boundary elements.
Definition at line 441 of file cfd_dem_coupling_matrix_free.h.
g
template<int dim> Tensor<1, 3> CFDDEMMatrixFree< dim >::g private
Gravitational acceleration vector.
Definition at line 352 of file cfd_dem_coupling_matrix_free.h.
grid_pvdhandler
template<int dim> PVDHandler CFDDEMMatrixFree< dim >::grid_pvdhandler private
PVD handler for grid visualization output.
Definition at line 472 of file cfd_dem_coupling_matrix_free.h.
insertion_object
template<int dim> std::shared_ptr<Insertion<dim, DEM::CFDDEMProperties::PropertiesIndex> > CFDDEMMatrixFree< dim >::insertion_object private
Particle insertion method handler.
Definition at line 411 of file cfd_dem_coupling_matrix_free.h.
integrator_object
template<int dim> std::shared_ptr<Integrator<dim, DEM::CFDDEMProperties::PropertiesIndex> > CFDDEMMatrixFree< dim >::integrator_object private
Time integration scheme for particle motion equations.
Definition at line 407 of file cfd_dem_coupling_matrix_free.h.
load_balancing
template<int dim> LagrangianLoadBalancing<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMMatrixFree< dim >::load_balancing private
Load balancing handler for distributing particles across MPI processes.
Definition at line 399 of file cfd_dem_coupling_matrix_free.h.
maximum_particle_diameter
template<int dim> double CFDDEMMatrixFree< dim >::maximum_particle_diameter private
Maximum diameter among all particles in the simulation.
Definition at line 371 of file cfd_dem_coupling_matrix_free.h.
MOI
template<int dim> std::vector<double> CFDDEMMatrixFree< dim >::MOI private
Moment of inertia values for all particles.
Definition at line 362 of file cfd_dem_coupling_matrix_free.h.
neighborhood_threshold_squared
template<int dim> double CFDDEMMatrixFree< dim >::neighborhood_threshold_squared private
Squared threshold distance for neighborhood particle detection.
Definition at line 365 of file cfd_dem_coupling_matrix_free.h.
ongoing_collision_log
template<int dim> OngoingCollisionLog<dim> CFDDEMMatrixFree< dim >::ongoing_collision_log private
Object to store ongoing collision information.
Stores particle ID, boundary ID, velocity tensor, angular velocity tensor, and collision time for collisions currently in progress.
Definition at line 382 of file cfd_dem_coupling_matrix_free.h.
particle_particle_contact_force_object
template<int dim> std::shared_ptr< ParticleParticleContactForceBase<dim, DEM::CFDDEMProperties::PropertiesIndex> > CFDDEMMatrixFree< dim >::particle_particle_contact_force_object private
Contact force model for particle-particle interactions.
Definition at line 417 of file cfd_dem_coupling_matrix_free.h.
particle_point_line_contact_force_object
template<int dim> ParticlePointLineForce<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMMatrixFree< dim >::particle_point_line_contact_force_object private
Handler for point and line contact forces between particles.
Definition at line 403 of file cfd_dem_coupling_matrix_free.h.
particle_wall_contact_force_object
template<int dim> std::shared_ptr< ParticleWallContactForceBase<dim, DEM::CFDDEMProperties::PropertiesIndex> > CFDDEMMatrixFree< dim >::particle_wall_contact_force_object private
Contact force model for particle-wall interactions.
Definition at line 422 of file cfd_dem_coupling_matrix_free.h.
particles_pvdhandler
template<int dim> PVDHandler CFDDEMMatrixFree< dim >::particles_pvdhandler private
PVD handler for particle visualization output.
Definition at line 475 of file cfd_dem_coupling_matrix_free.h.
periodic_boundaries_cells_information
template<int dim> DEM::dem_data_structures<dim>::periodic_boundaries_cells_info CFDDEMMatrixFree< dim >::periodic_boundaries_cells_information private
Information about cells involved in periodic boundary conditions.
Definition at line 449 of file cfd_dem_coupling_matrix_free.h.
periodic_boundaries_object
template<int dim> PeriodicBoundariesManipulator<dim> CFDDEMMatrixFree< dim >::periodic_boundaries_object private
Handler for periodic boundary condition manipulations.
Definition at line 452 of file cfd_dem_coupling_matrix_free.h.
properties_class
template<int dim> DEM::ParticleProperties<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMMatrixFree< dim >::properties_class private
Particle properties handler for DEM simulation.
Definition at line 469 of file cfd_dem_coupling_matrix_free.h.
rayleigh_time_step
template<int dim> double CFDDEMMatrixFree< dim >::rayleigh_time_step private
Rayleigh time step.
Definition at line 484 of file cfd_dem_coupling_matrix_free.h.
size_distribution_object_container
template<int dim> std::vector<std::shared_ptr<Distribution> > CFDDEMMatrixFree< dim >::size_distribution_object_container private
Container for particle size distribution objects.
Definition at line 368 of file cfd_dem_coupling_matrix_free.h.
smallest_contact_search_criterion
template<int dim> double CFDDEMMatrixFree< dim >::smallest_contact_search_criterion private
Smallest criterion used for contact search algorithms.
Definition at line 374 of file cfd_dem_coupling_matrix_free.h.
solid_surfaces_mesh_info
template<int dim> dem_data_structures<dim>::solid_surfaces_mesh_information CFDDEMMatrixFree< dim >::solid_surfaces_mesh_info private
Mesh information for solid surfaces in contact with particles.
Definition at line 433 of file cfd_dem_coupling_matrix_free.h.
sparse_contacts_object
template<int dim> AdaptiveSparseContacts<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMMatrixFree< dim >::sparse_contacts_object private
Object for handling adaptive sparse contact detection algorithms.
Definition at line 456 of file cfd_dem_coupling_matrix_free.h.
table_phase_volumes
template<int dim> TableHandler CFDDEMMatrixFree< dim >::table_phase_volumes private
TableHandler for post-processing phase volume calculations Stores total fluid volume and total particle volume data
Definition at line 488 of file cfd_dem_coupling_matrix_free.h.
torques_boundary_information
template<int dim> dem_data_structures<dim>::vector_on_boundary CFDDEMMatrixFree< dim >::torques_boundary_information private
Torque information stored on boundary elements.
Definition at line 445 of file cfd_dem_coupling_matrix_free.h.
updated_boundary_points_and_normal_vectors
template<int dim> dem_data_structures<dim>::boundary_points_and_normal_vectors CFDDEMMatrixFree< dim >::updated_boundary_points_and_normal_vectors private
Updated boundary points and their corresponding normal vectors.
Definition at line 437 of file cfd_dem_coupling_matrix_free.h.
visualization_object
template<int dim> Visualization<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMMatrixFree< dim >::visualization_object private
Visualization handler for DEM output generation.
Definition at line 426 of file cfd_dem_coupling_matrix_free.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/cfd_dem_coupling_matrix_free.h
/home/runner/work/lethe/lethe/source/fem-dem/cfd_dem_coupling_matrix_free.cc