Lethe Open-Source Library: FluidDynamicsSharp< dim > Class Template Reference
FluidDynamicsSharp< dim > Class Template Reference
#include <fluid_dynamics_sharp.h>
Classes
struct Visualization_IB
Public Member Functions
FluidDynamicsSharp (CFDDEMSimulationParameters< dim > &nsparam)
~FluidDynamicsSharp ()
void solve () override
void assemble_system_matrix () override
void assemble_system_rhs () override
Public Member Functions inherited from FluidDynamicsMatrixBased< dim >
FluidDynamicsMatrixBased (SimulationParameters< dim > &nsparam)
~FluidDynamicsMatrixBased ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
virtual void apply_constraints ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
void setup_assemblers () override
void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data) override
void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual void assemble_matrix_and_rhs ()
virtual void assemble_rhs ()
void vertices_cell_mapping ()
void define_particles ()
void force_on_ib ()
void sharp_edge ()
void write_force_ib ()
void integrate_particles ()
void finish_time_step_particles ()
std::pair< double, double > calculate_L2_error_particles ()
virtual void postprocess_fd (bool firstIter) override
virtual std::vector< OutputStruct< dim, GlobalVectorType > > gather_output_hook () override
void refine_ib (const bool initial_refinement)
void check_whether_all_particles_are_sphere ()
void generate_cut_cells_map ()
void optimized_generate_cut_cells_map ()
std::pair< bool, bool > generate_cut_cell_candidates (const typename DoFHandler< dim >::cell_iterator &cell, const unsigned int p_id)
std::tuple< bool, unsigned int, std::vector< types::global_dof_index > > cell_cut (const typename DoFHandler< dim >::active_cell_iterator &cell, std::vector< types::global_dof_index > &local_dof_indices, std::map< types::global_dof_index, Point< dim > > &support_points)
bool cell_cut_by_p_absolute_distance (const typename DoFHandler< dim >::active_cell_iterator &cell, std::map< types::global_dof_index, Point< dim > > &support_points, unsigned int p)
std::tuple< bool, unsigned int, std::vector< types::global_dof_index > > cell_inside (const typename DoFHandler< dim >::active_cell_iterator &cell, std::vector< types::global_dof_index > &local_dof_indices, std::map< types::global_dof_index, Point< dim > > &support_points)
virtual void write_checkpoint () override
virtual void read_checkpoint () override
void load_particles_from_file ()
void refinement_control (const bool initial_refinement)
bool point_inside_cell (const typename DoFHandler< dim >::active_cell_iterator &cell, Point< dim > point)
double get_current_residual () override
void update_precalculations_for_ib ()
Private Attributes
CFDDEMSimulationParameters< dim > cfd_dem_parameters
bool all_spheres
bool some_particles_are_coupled
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_cell
std::map< typename DoFHandler< dim >::active_cell_iterator, std::tuple< bool, unsigned int, std::vector< unsigned int > > > cut_cells_map
std::map< typename DoFHandler< dim >::active_cell_iterator, std::tuple< bool, unsigned int, double > > overconstrained_fluid_cell_map
GlobalVectorType local_dof_overconstrained
GlobalVectorType dof_overconstrained
std::map< unsigned int, bool > dof_with_more_then_one_particle
std::map< typename DoFHandler< dim >::active_cell_iterator, std::tuple< bool, unsigned int > > cells_inside_map
std::map< unsigned int, std::pair< bool, typename DoFHandler< dim >::active_cell_iterator > > ib_done
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers_inside_ib
PVDHandler ib_particles_pvdhandler
std::vector< IBParticle< dim > > particles
double particle_residual
std::vector< TableHandler > table_p
TableHandler table_all_p
IBParticlesDEM< dim > ib_dem
std::shared_ptr< Shape< dim > > combined_shapes
std::shared_ptr< LevelsetPostprocessor< dim > > levelset_postprocessor
std::shared_ptr< LevelsetGradientPostprocessor< dim > > levelset_gradient_postprocessor
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Protected Member Functions inherited from FluidDynamicsMatrixBased< dim >
virtual void setup_dofs_fd () override
virtual void set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false) override
virtual void update_multiphysics_time_average_solution () override
void setup_preconditioner () override
void define_dynamic_zero_constraints ()
virtual void update_mortar_configuration () override
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Protected Member Functions inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual GlobalVectorType & get_evaluation_point () override
virtual GlobalVectorType & get_local_evaluation_point () override
virtual GlobalVectorType & get_newton_update () override
virtual GlobalVectorType & get_present_solution () override
virtual GlobalVectorType & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void setup_dofs ()
virtual void set_initial_condition (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void update_solutions_for_multiphysics ()
virtual void update_solutions_for_fluid_dynamics ()
void postprocessing_forces (const GlobalVectorType &evaluation_point)
void postprocessing_torques (const GlobalVectorType &evaluation_point)
virtual void dynamic_flow_control ()
virtual void multi_stage_preresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method)
virtual void multi_stage_postresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method, double time_step)
virtual void update_multi_stage_solution (double time_step)
virtual void iterate ()
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
void transfer_solution (SolutionTransfer< dim, GlobalVectorType > &solution_transfer, std::vector< SolutionTransfer< dim, GlobalVectorType > > &previous_solutions_transfer)
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void reinit_mortar_operators ()
std::shared_ptr< Mapping< dim > > get_mapping ()
void rotate_rotor_mapping (const bool is_first)
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
virtual std::vector< OutputStructTableHandler > gather_tables ()
void serialize_tables_vector (const std::vector< OutputStructTableHandler > &table_output_structs)
void deserialize_tables_vector (std::vector< OutputStructTableHandler > &table_output_structs)
void gather_output_results (const GlobalVectorType &solution, std::vector< OutputStruct< dim, GlobalVectorType > > &solution_output_structs)
void write_output_results (const GlobalVectorType &solution)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
GlobalVectorType init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes inherited from FluidDynamicsMatrixBased< dim >
TrilinosWrappers::SparseMatrix system_matrix
Protected Attributes inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
GlobalVectorType present_solution
GlobalVectorType system_rhs
std::vector< GlobalVectorType > previous_solutions
SDIRKVectors sdirk_vectors
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::shared_ptr< MortarManagerCircle< dim > > mortar_manager
std::shared_ptr< CouplingOperator< dim, double > > mortar_coupling_operator
std::shared_ptr< NavierStokesCouplingEvaluation< dim, double > > mortar_coupling_evaluator
std::shared_ptr< MappingQCache< dim > > mapping_cache
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, GlobalVectorType, IndexSet > > average_velocities
GlobalVectorType average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Detailed Description
template<int dim>
class FluidDynamicsSharp< dim >
A solver class for the Navier-Stokes equation using GLS stabilization and Sharp-Edge immersed boundaries
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 30 of file fluid_dynamics_sharp.h.
Constructor & Destructor Documentation
FluidDynamicsSharp()
template<int dim> FluidDynamicsSharp< dim >::FluidDynamicsSharp (CFDDEMSimulationParameters< dim > & nsparam)
Definition at line 28 of file fluid_dynamics_sharp.cc.
~FluidDynamicsSharp()
template<int dim> FluidDynamicsSharp< dim >::~FluidDynamicsSharp () default
Member Function Documentation
assemble_local_system_matrix()
template<int dim> void FluidDynamicsSharp< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override private virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell This function is modified compared to the GLS function to take into account the cells that are cut or inside a particle
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 3958 of file fluid_dynamics_sharp.cc.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::assemblers, FluidDynamicsSharp< dim >::assemblers_inside_ib, NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_cut, StabilizedMethodsTensorCopyData< dim >::cell_is_local, FluidDynamicsSharp< dim >::cells_inside_map, FluidDynamicsSharp< dim >::cut_cells_map, NavierStokesBase< dim, GlobalVectorType, IndexSet >::evaluation_point, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesBase< dim, GlobalVectorType, IndexSet >::multiphysics, FluidDynamicsSharp< dim >::overconstrained_fluid_cell_map, NavierStokesBase< dim, GlobalVectorType, IndexSet >::previous_solutions, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::sdirk_vectors, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, NavierStokesBase< dim, GlobalVectorType, IndexSet >::triangulation, and VOF.
assemble_local_system_rhs()
template<int dim> void FluidDynamicsSharp< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override private virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 4049 of file fluid_dynamics_sharp.cc.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::assemblers, FluidDynamicsSharp< dim >::assemblers_inside_ib, NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_cut, StabilizedMethodsTensorCopyData< dim >::cell_is_local, FluidDynamicsSharp< dim >::cells_inside_map, FluidDynamicsSharp< dim >::cut_cells_map, NavierStokesBase< dim, GlobalVectorType, IndexSet >::evaluation_point, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesBase< dim, GlobalVectorType, IndexSet >::multiphysics, FluidDynamicsSharp< dim >::overconstrained_fluid_cell_map, NavierStokesBase< dim, GlobalVectorType, IndexSet >::previous_solutions, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::sdirk_vectors, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, NavierStokesBase< dim, GlobalVectorType, IndexSet >::triangulation, and VOF.
assemble_matrix_and_rhs()
template<int dim> virtual void FluidDynamicsSharp< dim >::assemble_matrix_and_rhs () inline private virtual
Call for the assembly of the matrix and the right hand side.
Deprecated:
This function is to be deprecated when the non-linear solvers have been refactored to call for rhs and matrix assembly seperately.
Definition at line 148 of file fluid_dynamics_sharp.h.
References FluidDynamicsSharp< dim >::all_spheres, FluidDynamicsMatrixBased< dim >::assemble_system_matrix(), FluidDynamicsSharp< dim >::force_on_ib(), FluidDynamicsSharp< dim >::generate_cut_cells_map(), PhysicsSolver< VectorType >::get_current_newton_iteration(), FluidDynamicsSharp< dim >::integrate_particles(), FluidDynamicsSharp< dim >::optimized_generate_cut_cells_map(), FluidDynamicsSharp< dim >::sharp_edge(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, FluidDynamicsSharp< dim >::some_particles_are_coupled, and FluidDynamicsSharp< dim >::update_precalculations_for_ib().
assemble_rhs()
template<int dim> virtual void FluidDynamicsSharp< dim >::assemble_rhs () inline private virtual
Call for the assembly of the right hand side.
Deprecated:
This function is to be deprecated when the non-linear solvers have been refactored to call for rhs and matrix assembly seperately.
Modified version of assemble_matrix_and_rhs to include the presence of extra steps. For more detail see the same function in the fluid_dynamics_matrix_based.h solver.
Definition at line 187 of file fluid_dynamics_sharp.h.
References FluidDynamicsMatrixBased< dim >::assemble_system_rhs().
assemble_system_matrix()
template<int dim> void FluidDynamicsSharp< dim >::assemble_system_matrix () inline override virtual
Call for the assembly of the matrix.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 44 of file fluid_dynamics_sharp.h.
References FluidDynamicsSharp< dim >::assemble_matrix_and_rhs().
assemble_system_rhs()
template<int dim> void FluidDynamicsSharp< dim >::assemble_system_rhs () inline override virtual
Call for the assembly of the right-hand side.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 53 of file fluid_dynamics_sharp.h.
References FluidDynamicsSharp< dim >::assemble_rhs(), and FluidDynamicsSharp< dim >::sharp_edge().
calculate_L2_error_particles()
template<int dim> std::pair< double, double > FluidDynamicsSharp< dim >::calculate_L2_error_particles () private
Evaluate the L2 error on the computational domain if an analytical solution is given. This function is slightly different from its standard GLS counterpart as the cells that are cut by an immersed boundary should not be taken into account in the error evaluation. See "computation domain" definition in: L. Barbeau, S. tienne, C. Bguin & B. Blais, Development of a high-order continuous Galerkin sharp-interface immersed boundary method and its application to incompressible flow problems, Computers & Fluids, 2020, in press, ref. CAF-D-20-0077.
Definition at line 1821 of file fluid_dynamics_sharp.cc.
References BoundaryConditions::function_weak, pressure, and NavierStokesFunctionDefined< dim >::value().
cell_cut()
template<int dim> std::tuple< bool, unsigned int, std::vector< types::global_dof_index > > FluidDynamicsSharp< dim >::cell_cut (const typename DoFHandler< dim >::active_cell_iterator & cell, std::vector< types::global_dof_index > & local_dof_indices, std::map< types::global_dof_index, Point< dim > > & support_points) private
Return a bool to define if a cell is cut by an IB particle and the local DOFs of the cell for later us. If the cell is cut, the function will return the id of the particle that cut it, else it returns 0.
Parameters
cell,the cell that we verify whether it is cut or not.
local_dof_indices,a container for the local dof indices used during the function call.
support_points,a mapping of support points for the DOFs.
cell_cut_by_p_absolute_distance()
template<int dim> bool FluidDynamicsSharp< dim >::cell_cut_by_p_absolute_distance (const typename DoFHandler< dim >::active_cell_iterator & cell, std::map< types::global_dof_index, Point< dim > > & support_points, unsigned int p) private
Return a bool to define if a cell is cut by an IB. This function is built to handle special cases where the level set is always positive.
Parameters
cell,the cell that we verify whether it is cut or not.
support_points,a mapping of support points for the DOFs.
p,the particle index of the particle used in the check
Definition at line 440 of file fluid_dynamics_sharp.cc.
cell_inside()
template<int dim> std::tuple< bool, unsigned int, std::vector< types::global_dof_index > > FluidDynamicsSharp< dim >::cell_inside (const typename DoFHandler< dim >::active_cell_iterator & cell, std::vector< types::global_dof_index > & local_dof_indices, std::map< types::global_dof_index, Point< dim > > & support_points) private
Return a bool to define if a cell is contains inside an IB particle and the local DOFs of the cell for later us. If the cell is cut, the function will return the id of the particle, else it returns 0.
Parameters
cell,the cell that we verify whether it is cut or not.
local_dof_indices,a container for the local dof indices used during the function call.
support_points,a mapping of support points for the DOFs.
check_whether_all_particles_are_sphere()
template<int dim> void FluidDynamicsSharp< dim >::check_whether_all_particles_are_sphere () private
This function checks if all particles are spheres. If one of them is not, the code will use the regular generate_cut_cells function. If all particles are spheres, it uses the optimized_generate_cut_cells.
Definition at line 52 of file fluid_dynamics_sharp.cc.
copy_local_matrix_to_global_matrix()
template<int dim> void FluidDynamicsSharp< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > & copy_data) override private virtual
Copy local cell information to global matrix This function is modified compared to the GLS function to take into account the cells that are cut or inside a particle.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 4035 of file fluid_dynamics_sharp.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_cut, StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, StabilizedMethodsTensorCopyData< dim >::local_matrix, and NavierStokesBase< dim, GlobalVectorType, IndexSet >::zero_constraints.
copy_local_rhs_to_global_rhs()
template<int dim> void FluidDynamicsSharp< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > & copy_data) override private virtual
Copy local cell rhs information to global rhs This function is modified compared to the GLS function to take into account the cells that are cut or inside a particle.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 4128 of file fluid_dynamics_sharp.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_cut, StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, StabilizedMethodsTensorCopyData< dim >::local_rhs, and NavierStokesBase< dim, GlobalVectorType, IndexSet >::zero_constraints.
define_particles()
template<int dim> void FluidDynamicsSharp< dim >::define_particles () private
Defines the particle structure and value based on the parameter file. This structure gives access to the position, velocity, force and other proprieties of each IB particle. All the variables defined for each of the particle are described in the class: IBparticle. see: \ib_particle.h.
Definition at line 755 of file fluid_dynamics_sharp.cc.
finish_time_step_particles()
template<int dim> void FluidDynamicsSharp< dim >::finish_time_step_particles () private
Store the solution of the particles dynamics parameters for integration. Defines the table to store the history of each of the particles.
Definition at line 2748 of file fluid_dynamics_sharp.cc.
References FluidDynamicsSharp< dim >::Visualization_IB::build_patches(), FluidDynamicsSharp< dim >::ib_particles_pvdhandler, NavierStokesBase< dim, GlobalVectorType, IndexSet >::mpi_communicator, DEM::omega, FluidDynamicsSharp< dim >::particles, PhysicsSolver< VectorType >::pcout, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_control, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, FluidDynamicsSharp< dim >::some_particles_are_coupled, Parameters::SimulationControl::steady, FluidDynamicsSharp< dim >::table_all_p, FluidDynamicsSharp< dim >::table_p, tensor_nd_to_2d(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::this_mpi_process, DEM::velocity, and Parameters::verbose.
force_on_ib()
template<int dim> void FluidDynamicsSharp< dim >::force_on_ib () private
Evaluate the forces applied on each of the IB particle.
Definition at line 985 of file fluid_dynamics_sharp.cc.
References calculate_shear_rate_magnitude(), IBStencil< dim >::coefficients(), IBStencil< dim >::point_for_cell_detection(), pressure, shear_rate, IBStencil< dim >::support_points_for_interpolation(), temperature, and tensor_nd_to_3d().
gather_output_hook()
template<int dim> std::vector< OutputStruct< dim, GlobalVectorType > > FluidDynamicsSharp< dim >::gather_output_hook () override private virtual
Adds levelset to output files.
Returns
Vector of OutputStructs that will be used to write the output results as VTU files.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 1679 of file fluid_dynamics_sharp.cc.
generate_cut_cell_candidates()
template<int dim> std::pair< bool, bool > FluidDynamicsSharp< dim >::generate_cut_cell_candidates (const typename DoFHandler< dim >::cell_iterator & cell, const unsigned int p_id) private
This function abstracts the generation of cell candidates that possibly are cut.
Definition at line 635 of file fluid_dynamics_sharp.cc.
generate_cut_cells_map()
template<int dim> void FluidDynamicsSharp< dim >::generate_cut_cells_map () private
This function creates a map (cut_cells_map) that indicates if a cell is cut, and the particle id of the particle that cut it.
Definition at line 76 of file fluid_dynamics_sharp.cc.
get_current_residual()
template<int dim> double FluidDynamicsSharp< dim >::get_current_residual () inline override private virtual
A override of the get_current_residual to take into account the particles coupling residual.
Reimplemented from PhysicsSolver< VectorType >.
Definition at line 467 of file fluid_dynamics_sharp.h.
References fluid_dynamics, FluidDynamicsSharp< dim >::particle_residual, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, and NavierStokesBase< dim, GlobalVectorType, IndexSet >::system_rhs.
integrate_particles()
template<int dim> void FluidDynamicsSharp< dim >::integrate_particles () private
Integrate the particle velocity and position based on the forces and torques and applies the next value to the particle.
Definition at line 2086 of file fluid_dynamics_sharp.cc.
References LetheGridTools::find_cell_around_point_with_tree(), fluid_dynamics, number_of_previous_solutions(), DEM::omega, Parameters::quiet, IBParticle< dim >::set_position(), shear_rate, temperature, and IBParticle< dim >::velocity_iter.
load_particles_from_file()
template<int dim> void FluidDynamicsSharp< dim >::load_particles_from_file () private
Definition at line 4518 of file fluid_dynamics_sharp.cc.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::computing_timer, fill_string_vectors_from_file(), FluidDynamicsSharp< dim >::particles, PhysicsSolver< VectorType >::pcout, and NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters.
optimized_generate_cut_cells_map()
template<int dim> void FluidDynamicsSharp< dim >::optimized_generate_cut_cells_map () private
This function is only applied if all particles are spheres. It creates two maps (cut_cells_map and cells_inside_map) to access the cells cut by particles and inside the particles, respectively. The map keys are the particle's IDs. The algorithm was optimized to reduce the cost of this step.
Definition at line 497 of file fluid_dynamics_sharp.cc.
point_inside_cell()
template<int dim> bool FluidDynamicsSharp< dim >::point_inside_cell (const typename DoFHandler< dim >::active_cell_iterator & cell, Point< dim > point) private
Return a bool that describes if a cell contains a specific point.
Parameters
cell,The initial cell for which we want to check if the point is inside.
point,The point that we wish to check
postprocess_fd()
template<int dim> void FluidDynamicsSharp< dim >::postprocess_fd (bool firstIter) override private virtual
Same function as its standard GLS counterpart but it used the error evaluation that takes into account the particles position.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 1756 of file fluid_dynamics_sharp.cc.
References NavierStokesBase< dim, VectorType, DofsType >::postprocess_fd(), Parameters::SimulationControl::steady, and Parameters::verbose.
read_checkpoint()
template<int dim> void FluidDynamicsSharp< dim >::read_checkpoint () override private virtual
Restart a previous simulation from a checkpoint file.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 4285 of file fluid_dynamics_sharp.cc.
References FluidDynamicsSharp< dim >::cfd_dem_parameters, FluidDynamicsSharp< dim >::check_whether_all_particles_are_sphere(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::computing_timer, NavierStokesBase< dim, GlobalVectorType, IndexSet >::dof_handler, fill_table_from_file(), fill_vectors_from_file(), FluidDynamicsSharp< dim >::ib_dem, FluidDynamicsSharp< dim >::ib_particles_pvdhandler, FluidDynamicsSharp< dim >::particles, PVDHandler::read(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::read_checkpoint(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, FluidDynamicsSharp< dim >::table_p, and FluidDynamicsSharp< dim >::update_precalculations_for_ib().
refine_ib()
template<int dim> void FluidDynamicsSharp< dim >::refine_ib (const bool initial_refinement) private
Allow a refinement around each of the particles. The zone where the cells will be refined is defined by a ring in 2D and a shell in 3D. The outside and inside radius of the ring\shell is defined in relation to the diameter of the particle by the immersed boundaries parameter: "refine mesh inside radius factor" and "refine mesh outside radius factor". These factors multiply the radius of the particle to define the outside and inside radius of the ring\shell.
Parameters
initial_refinement,A bool that indicate if this is the initial refinement.
Definition at line 813 of file fluid_dynamics_sharp.cc.
refinement_control()
template<int dim> void FluidDynamicsSharp< dim >::refinement_control (const bool initial_refinement) private
Regroup and organize the refinement process around the IB particle.
Parameters
initial_refinement,A bool that indicate if this is the initial refinement.
Definition at line 356 of file fluid_dynamics_sharp.cc.
References NavierStokesBase< dim, VectorType, DofsType >::refine_mesh().
setup_assemblers()
template<int dim> void FluidDynamicsSharp< dim >::setup_assemblers () override private virtual
sets up the vector of assembler functions This function is modified compared to the GLS function to take into account the cells that are cut or inside a particle. Refer to 2 different assembler depending on what type of equations is assembled inside the particles.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 3837 of file fluid_dynamics_sharp.cc.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::assemblers, FluidDynamicsSharp< dim >::assemblers_inside_ib, NavierStokesBase< dim, GlobalVectorType, IndexSet >::check_existance_of_bc(), BoundaryConditions::function_weak, is_bdf(), BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::pressure, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_control, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, and Parameters::VelocitySource::srf.
sharp_edge()
template<int dim> void FluidDynamicsSharp< dim >::sharp_edge () private
Modify the system matrix to impose IB condition using the sharp_edge approach. The detail of this approach are presented in : L. Barbeau, S. tienne, C. Bguin & B. Blais, Development of a high-order continuous Galerkin sharp-interface immersed boundary method and its application to incompressible flow problems, Computers & Fluids, 2020, in press, ref. CAF-D-20-00773.
Definition at line 3091 of file fluid_dynamics_sharp.cc.
References FluidDynamicsSharp< dim >::cell_cut(), IBStencil< dim >::coefficients(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::computing_timer, FluidDynamicsSharp< dim >::cut_cells_map, NavierStokesBase< dim, GlobalVectorType, IndexSet >::dof_handler, NavierStokesBase< dim, GlobalVectorType, IndexSet >::evaluation_point, NavierStokesBase< dim, GlobalVectorType, IndexSet >::fe, LetheGridTools::find_cell_around_point_with_tree(), FluidDynamicsSharp< dim >::ib_done, IBStencil< dim >::ib_velocity(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::locally_owned_dofs, NavierStokesBase< dim, GlobalVectorType, IndexSet >::mapping, NavierStokesBase< dim, GlobalVectorType, IndexSet >::nonzero_constraints, IBStencil< dim >::number_of_interpolation_support_points(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::number_quadrature_points, FluidDynamicsSharp< dim >::overconstrained_fluid_cell_map, FluidDynamicsSharp< dim >::particles, IBStencil< dim >::point_for_cell_detection(), pressure, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_control, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, Parameters::SimulationControl::steady, IBStencil< dim >::support_points_for_interpolation(), FluidDynamicsMatrixBased< dim >::system_matrix, NavierStokesBase< dim, GlobalVectorType, IndexSet >::system_rhs, NavierStokesBase< dim, GlobalVectorType, IndexSet >::triangulation, FluidDynamicsSharp< dim >::vertices_to_cell, and NavierStokesBase< dim, GlobalVectorType, IndexSet >::zero_constraints.
solve()
template<int dim> void FluidDynamicsSharp< dim >::solve () override virtual
solve Solves the Navier-Stokes problem
This functions solves the problem defined by the Navier-Stokes parameter by iterating through time or through the mesh refinements.
Reimplemented from FluidDynamicsMatrixBased< dim >.
Definition at line 4816 of file fluid_dynamics_sharp.cc.
References FluidDynamicsSharp< dim >::all_spheres, FluidDynamicsSharp< dim >::define_particles(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::dof_handler, NavierStokesBase< dim, GlobalVectorType, IndexSet >::dynamic_flow_control(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::face_quadrature, NavierStokesBase< dim, GlobalVectorType, IndexSet >::finish_simulation(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::finish_time_step(), FluidDynamicsSharp< dim >::finish_time_step_particles(), FluidDynamicsSharp< dim >::force_on_ib(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::forcing_function, FluidDynamicsSharp< dim >::generate_cut_cells_map(), FluidDynamicsSharp< dim >::ib_dem, FluidDynamicsSharp< dim >::ib_done, FluidDynamicsSharp< dim >::integrate_particles(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::iterate(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::mapping, NavierStokesBase< dim, GlobalVectorType, IndexSet >::multiphysics, FluidDynamicsSharp< dim >::optimized_generate_cut_cells_map(), FluidDynamicsSharp< dim >::particles, PhysicsSolver< VectorType >::pcout, NavierStokesBase< dim, GlobalVectorType, IndexSet >::postprocess(), read_mesh_and_manifolds(), FluidDynamicsSharp< dim >::refinement_control(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::set_initial_condition(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::setup_dofs(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_control, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, FluidDynamicsSharp< dim >::some_particles_are_coupled, NavierStokesBase< dim, GlobalVectorType, IndexSet >::triangulation, NavierStokesBase< dim, GlobalVectorType, IndexSet >::update_boundary_conditions(), FluidDynamicsMatrixBased< dim >::update_multiphysics_time_average_solution(), FluidDynamicsSharp< dim >::update_precalculations_for_ib(), FluidDynamicsSharp< dim >::vertices_cell_mapping(), and FluidDynamicsSharp< dim >::write_force_ib().
update_precalculations_for_ib()
template<int dim> void FluidDynamicsSharp< dim >::update_precalculations_for_ib () private
This function updates the precalculations for every immersed particle.
Definition at line 4803 of file fluid_dynamics_sharp.cc.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::computing_timer, NavierStokesBase< dim, GlobalVectorType, IndexSet >::dof_handler, and FluidDynamicsSharp< dim >::particles.
vertices_cell_mapping()
template<int dim> void FluidDynamicsSharp< dim >::vertices_cell_mapping () private
Map the vertex index to the cell that includes that vertex. This map is used to find all the cell close to a specific vertex.
Definition at line 42 of file fluid_dynamics_sharp.cc.
References LetheGridTools::vertices_cell_mapping().
write_checkpoint()
template<int dim> void FluidDynamicsSharp< dim >::write_checkpoint () override private virtual
Write a gls_sharp simulation checkpointing to allow for gls_sharp simulation restart This function stores all the previous' particles states in one file. Each row corresponds to one particle state. The file is structured as follows:
P0 state at time t
P0 state at time t-dt
P0 state at time t-2dt
P1 state at time t
P1 state at time t-dt
P1 state at time t-2dt
etc
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 4143 of file fluid_dynamics_sharp.cc.
References FluidDynamicsSharp< dim >::ib_particles_pvdhandler, NavierStokesBase< dim, GlobalVectorType, IndexSet >::mpi_communicator, FluidDynamicsSharp< dim >::particles, NavierStokesBase< dim, GlobalVectorType, IndexSet >::pvdhandler, PVDHandler::save(), NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_control, NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters, and NavierStokesBase< dim, GlobalVectorType, IndexSet >::write_checkpoint().
write_force_ib()
template<int dim> void FluidDynamicsSharp< dim >::write_force_ib () private
Write in a specifique file for each of the paticles its forces, velocity, position at each time step.
Definition at line 1650 of file fluid_dynamics_sharp.cc.
Member Data Documentation
all_spheres
template<int dim> bool FluidDynamicsSharp< dim >::all_spheres private
Definition at line 563 of file fluid_dynamics_sharp.h.
assemblers_inside_ib
template<int dim> std::vector<std::shared_ptr<NavierStokesAssemblerBase<dim> > > FluidDynamicsSharp< dim >::assemblers_inside_ib private
Definition at line 615 of file fluid_dynamics_sharp.h.
cells_inside_map
template<int dim> std::map<typename DoFHandler<dim>::active_cell_iterator, std::tuple<bool, unsigned int> > FluidDynamicsSharp< dim >::cells_inside_map private
Definition at line 604 of file fluid_dynamics_sharp.h.
cfd_dem_parameters
template<int dim> CFDDEMSimulationParameters<dim> FluidDynamicsSharp< dim >::cfd_dem_parameters private
Members
Definition at line 561 of file fluid_dynamics_sharp.h.
combined_shapes
template<int dim> std::shared_ptr<Shape<dim> > FluidDynamicsSharp< dim >::combined_shapes private
Definition at line 630 of file fluid_dynamics_sharp.h.
cut_cells_map
template<int dim> std::map<typename DoFHandler<dim>::active_cell_iterator, std::tuple<bool, unsigned int, std::vector<unsigned int> > > FluidDynamicsSharp< dim >::cut_cells_map private
Definition at line 580 of file fluid_dynamics_sharp.h.
dof_overconstrained
template<int dim> GlobalVectorType FluidDynamicsSharp< dim >::dof_overconstrained private
Definition at line 598 of file fluid_dynamics_sharp.h.
dof_with_more_then_one_particle
template<int dim> std::map<unsigned int, bool> FluidDynamicsSharp< dim >::dof_with_more_then_one_particle private
Definition at line 599 of file fluid_dynamics_sharp.h.
ib_dem
template<int dim> IBParticlesDEM<dim> FluidDynamicsSharp< dim >::ib_dem private
Definition at line 627 of file fluid_dynamics_sharp.h.
ib_done
template<int dim> std::map<unsigned int, std::pair<bool, typename DoFHandler<dim>::active_cell_iterator> > FluidDynamicsSharp< dim >::ib_done private
Definition at line 611 of file fluid_dynamics_sharp.h.
ib_particles_pvdhandler
template<int dim> PVDHandler FluidDynamicsSharp< dim >::ib_particles_pvdhandler private
Definition at line 617 of file fluid_dynamics_sharp.h.
levelset_gradient_postprocessor
template<int dim> std::shared_ptr<LevelsetGradientPostprocessor<dim> > FluidDynamicsSharp< dim >::levelset_gradient_postprocessor private
Definition at line 636 of file fluid_dynamics_sharp.h.
levelset_postprocessor
template<int dim> std::shared_ptr<LevelsetPostprocessor<dim> > FluidDynamicsSharp< dim >::levelset_postprocessor private
Definition at line 634 of file fluid_dynamics_sharp.h.
local_dof_overconstrained
template<int dim> GlobalVectorType FluidDynamicsSharp< dim >::local_dof_overconstrained private
Definition at line 597 of file fluid_dynamics_sharp.h.
overconstrained_fluid_cell_map
template<int dim> std::map<typename DoFHandler<dim>::active_cell_iterator, std::tuple<bool, unsigned int, double> > FluidDynamicsSharp< dim >::overconstrained_fluid_cell_map private
Definition at line 591 of file fluid_dynamics_sharp.h.
particle_residual
template<int dim> double FluidDynamicsSharp< dim >::particle_residual private
Definition at line 620 of file fluid_dynamics_sharp.h.
particles
template<int dim> std::vector<IBParticle<dim> > FluidDynamicsSharp< dim >::particles private
Definition at line 619 of file fluid_dynamics_sharp.h.
some_particles_are_coupled
template<int dim> bool FluidDynamicsSharp< dim >::some_particles_are_coupled private
Definition at line 566 of file fluid_dynamics_sharp.h.
table_all_p
template<int dim> TableHandler FluidDynamicsSharp< dim >::table_all_p private
Definition at line 623 of file fluid_dynamics_sharp.h.
table_p
template<int dim> std::vector<TableHandler> FluidDynamicsSharp< dim >::table_p private
Definition at line 622 of file fluid_dynamics_sharp.h.
vertices_to_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > FluidDynamicsSharp< dim >::vertices_to_cell private
Definition at line 570 of file fluid_dynamics_sharp.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/fluid_dynamics_sharp.h
/home/runner/work/lethe/lethe/source/fem-dem/fluid_dynamics_sharp.cc