Lethe Open-Source Library: VANSAssemblerViscousTorque< dim > Class Template Reference
VANSAssemblerViscousTorque< dim > Class Template Reference
#include <vans_assemblers.h>
Public Member Functions
VANSAssemblerViscousTorque (Parameters::Lagrangian::LagrangianPhysicalProperties lagrangian_physical_properties)
virtual void calculate_particle_fluid_interactions (NavierStokesScratchData< dim > &scratch_data) override
Public Attributes
Parameters::Lagrangian::LagrangianPhysicalProperties lagrangian_physical_properties
Detailed Description
template<int dim>
class VANSAssemblerViscousTorque< dim >
Class that assembles the Viscous dissipative torque due to particle's rotation as defined by Derksen (2004). M_viscous_rotation = pi * pow(dp, 3) * mu * (- omega_p)
The complete model described by Derksen is composed of VANSAssemblerViscousTorque + VANSAssemblerVorticalTorque
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 508 of file vans_assemblers.h.
Constructor & Destructor Documentation
VANSAssemblerViscousTorque()
template<int dim> VANSAssemblerViscousTorque< dim >::VANSAssemblerViscousTorque (Parameters::Lagrangian::LagrangianPhysicalProperties lagrangian_physical_properties) inline
Definition at line 511 of file vans_assemblers.h.
Member Function Documentation
calculate_particle_fluid_interactions()
template<int dim> void VANSAssemblerViscousTorque< dim >::calculate_particle_fluid_interactions (NavierStokesScratchData< dim > & scratch_data) override virtual
calculate_particle_fluid_interactions calculates the viscous torque dissipation
Parameters
scratch_data (see base class)
copy_data (see base class)
Implements ParticleFluidAssemblerBase< dim >.
Definition at line 1703 of file vans_assemblers.cc.
References PhysicalPropertiesManager::density_is_constant(), DEM::CFDDEMProperties::dp, DEM::CFDDEMProperties::fem_torque_x, PhysicalPropertiesManager::get_density_scale(), PhysicalPropertiesManager::get_kinematic_viscosity_scale(), PhysicalPropertiesManager::is_non_newtonian(), DEM::CFDDEMProperties::omega_x, NavierStokesScratchData< dim >::pic, and NavierStokesScratchData< dim >::properties_manager.
Member Data Documentation
lagrangian_physical_properties
template<int dim> Parameters::Lagrangian::LagrangianPhysicalProperties VANSAssemblerViscousTorque< dim >::lagrangian_physical_properties
Definition at line 528 of file vans_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/vans_assemblers.h
/home/runner/work/lethe/lethe/source/fem-dem/vans_assemblers.cc