Lethe Open-Source Library: ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model > Class Template Reference
ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model > Class Template Reference
#include <particle_wall_contact_force.h>
Public Member Functions
ParticleWallContactForce (const DEMSolverParameters< dim > &dem_parameters)
virtual ~ParticleWallContactForce ()
virtual void calculate_particle_wall_contact (typename DEM::dem_data_structures< dim >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double dt, ParticleInteractionOutcomes< PropertiesIndex > &contact_outcome) override
virtual void calculate_particle_solid_object_contact (typename DEM::dem_data_structures< dim >::particle_floating_mesh_in_contact &particle_floating_mesh_in_contact, const double dt, const std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > &solids, ParticleInteractionOutcomes< PropertiesIndex > &contact_outcome) override
Protected Member Functions
void update_contact_information (particle_wall_contact_info< dim > &contact_info, Tensor< 1, 3 > &tangential_relative_velocity, double &normal_relative_velocity_value, const Point< 3 > &particle_location, const ArrayView< const double > &particle_properties, const double dt)
void update_particle_solid_object_contact_information (particle_wall_contact_info< dim > &contact_info, Tensor< 1, 3 > &tangential_relative_velocity, double &normal_relative_velocity_value, const ArrayView< const double > &particle_properties, const double dt, const Tensor< 1, 3 > &cut_cell_translational_velocity, const Tensor< 1, 3 > &cut_cell_rotational_velocity, const double center_of_rotation_particle_distance)
Tensor< 1, 3 > find_projection (const Tensor< 1, 3 > &vector_a, const Tensor< 1, 3 > &vector_b)
Point< 3 > get_location (const Particles::ParticleIterator< dim > &particle) &
void calculate_contact (particle_wall_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > &particle_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
double get_force_calculation_threshold_distance ()
Private Member Functions
void apply_force_and_torque (const Tensor< 1, 3 > &normal_force, const Tensor< 1, 3 > &tangential_force, const Tensor< 1, 3 > &tangential_torque, const Tensor< 1, 3 > &rolling_resistance_torque, Tensor< 1, 3 > &particle_torque, Tensor< 1, 3 > &particle_force)
Tensor< 1, 3 > calculate_rolling_resistance_torque (const double particle_radius, const ArrayView< const double > &particle_properties, const double rolling_friction_coeff, const double rolling_viscous_damping_coeff, const double dt, const double normal_spring_constant, const double normal_force_norm, const Tensor< 1, 3 > &normal_unit_vector, Tensor< 1, 3 > &cumulative_rolling_resistance_spring_torque)
void calculate_linear_contact (particle_wall_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > &particle_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_nonlinear_contact (particle_wall_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > &particle_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_JKR_contact (particle_wall_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > &particle_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_DMT_contact (particle_wall_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > &particle_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void set_effective_properties (const DEMSolverParameters< dim > &dem_parameters)
void set_multiphysic_properties (const DEMSolverParameters< dim > &dem_parameters)
Private Attributes
unsigned int n_particle_types
std::vector< double > effective_youngs_modulus
std::vector< double > effective_real_youngs_modulus
std::vector< double > effective_shear_modulus
std::vector< double > effective_coefficient_of_restitution
std::vector< double > effective_coefficient_of_friction
std::vector< double > effective_coefficient_of_rolling_friction
std::vector< double > effective_coefficient_of_rolling_viscous_damping
std::vector< double > effective_surface_energy
std::vector< double > effective_hamaker_constant
std::vector< double > model_parameter_beta
std::vector< double > equivalent_surface_roughness
std::vector< double > equivalent_surface_slope
std::vector< double > effective_microhardness
std::vector< double > particle_thermal_conductivity
std::vector< double > gas_parameter_m
double gas_thermal_conductivity
double wall_thermal_conductivity
const double dmt_cut_off_threshold
const double f_coefficient_epsd
std::unordered_map< unsigned int, double > boundary_rotational_speed_map
std::unordered_map< unsigned int, Tensor< 1, 3 > > boundary_translational_velocity_map
std::unordered_map< unsigned int, Tensor< 1, 3 > > boundary_rotational_vector
std::unordered_map< unsigned int, Point< 3 > > point_on_rotation_vector
const unsigned int vertices_per_triangle = 3
Point< 3 > center_mass_container
Detailed Description
template<int dim, typename PropertiesIndex, Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model>
class ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >
Execute calculation of particle-wall contacts.
Template Parameters
dim The dimension of the problem.
contact_model The particle-wall contact force model.
rolling_friction_model The rolling resistance model.
Definition at line 89 of file particle_wall_contact_force.h.
Constructor & Destructor Documentation
ParticleWallContactForce()
template<int dim, typename PropertiesIndex , ParticleWallContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::ParticleWallContactForce (const DEMSolverParameters< dim > & dem_parameters)
Definition at line 16 of file particle_wall_contact_force.cc.
References ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::set_effective_properties(), and ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::set_multiphysic_properties().
~ParticleWallContactForce()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> virtual ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::~ParticleWallContactForce () inline virtual
Definition at line 95 of file particle_wall_contact_force.h.
Member Function Documentation
apply_force_and_torque()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::apply_force_and_torque (const Tensor< 1, 3 > & normal_force, const Tensor< 1, 3 > & tangential_force, const Tensor< 1, 3 > & tangential_torque, const Tensor< 1, 3 > & rolling_resistance_torque, Tensor< 1, 3 > & particle_torque, Tensor< 1, 3 > & particle_force) inline private
Apply the calculated force and torque on the particle in contact.
Parameters
[in] normal_force Contact normal force.
[in] tangential_force Contact tangential force.
[in] tangential_torque Contact torque induced by the tangential force.
[in] rolling_resistance_torque Contact rolling resistance torque.
[in,out] particle_torque Torque acting on particle.
[in,out] particle_force Force acting on particle.
Definition at line 448 of file particle_wall_contact_force.h.
calculate_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_contact (particle_wall_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > & particle_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline protected
Calculate the particle-wall contact force and torque according to the contact model.
Parameters
[in,out] contact_info A container with the required information for calculation of the contact force for a particle-wall pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative velocity value.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_properties Properties of particle.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] tangential_torque Contact tangential torque.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 330 of file particle_wall_contact_force.h.
References ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_DMT_contact(), ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_JKR_contact(), ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_linear_contact(), and ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_nonlinear_contact().
calculate_DMT_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_DMT_contact (particle_wall_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > & particle_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-wall cohesive force and contact torque based on the updated values in contact_info. It uses the DMT cohesive force model.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle-wall.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative velocity value.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_properties Properties of particle.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] tangential_torque Contact tangential torque.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 960 of file particle_wall_contact_force.h.
References ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_nonlinear_contact(), ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_hamaker_constant, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy, particle_wall_contact_info< dim >::normal_vector, particle_wall_contact_info< dim >::rolling_resistance_spring_torque, and particle_wall_contact_info< dim >::tangential_displacement.
calculate_JKR_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_JKR_contact (particle_wall_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > & particle_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-wall JKR contact force and torque based on the updated values in contact_info.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle-wall pair.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative velocity value.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_properties Properties of particle.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] tangential_torque Contact tangential torque.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 796 of file particle_wall_contact_force.h.
References ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_viscous_damping, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, particle_wall_contact_info< dim >::normal_vector, particle_wall_contact_info< dim >::rolling_resistance_spring_torque, and particle_wall_contact_info< dim >::tangential_displacement.
calculate_linear_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_linear_contact (particle_wall_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > & particle_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-wall linear contact force and torque based on the updated values in contact_info.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle-wall pair.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative velocity value.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_properties Properties of particle.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] tangential_torque Contact tangential torque.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 555 of file particle_wall_contact_force.h.
References ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_viscous_damping, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, particle_wall_contact_info< dim >::normal_vector, particle_wall_contact_info< dim >::rolling_resistance_spring_torque, and particle_wall_contact_info< dim >::tangential_displacement.
calculate_nonlinear_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_nonlinear_contact (particle_wall_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const double normal_overlap, const double dt, const ArrayView< const double > & particle_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-wall non-linear contact force and torque based on the updated values in contact_info.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle-wall pair.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative velocity value.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_properties Properties of particle.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] tangential_torque Contact tangential torque..
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 668 of file particle_wall_contact_force.h.
References ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_viscous_damping, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, particle_wall_contact_info< dim >::normal_vector, particle_wall_contact_info< dim >::rolling_resistance_spring_torque, and particle_wall_contact_info< dim >::tangential_displacement.
calculate_particle_solid_object_contact()
template<int dim, typename PropertiesIndex , ParticleWallContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_particle_solid_object_contact (typename DEM::dem_data_structures< dim >::particle_floating_mesh_in_contact & particle_floating_mesh_in_contact, const double dt, const std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > & solids, ParticleInteractionOutcomes< PropertiesIndex > & contact_outcome) override virtual
Calculate the contact outcomes for particle-solid objects contacts using the contact pair information and physical properties.
Parameters
[in] particle_floating_mesh_in_contact A container that stores the information of particle-floating mesh contact.
[in] dt DEM time step.
[in] solids Floating solids.
[out] contact_outcome Interaction outcomes.
Implements ParticleWallContactForceBase< dim, PropertiesIndex >.
Definition at line 143 of file particle_wall_contact_force.cc.
References Parameters::adiabatic, apply_heat_transfer_on_single_local_particle(), calculate_contact_thermal_conductance(), ParticleInteractionOutcomes< PropertiesIndex >::force, get_location(), ParticleInteractionOutcomes< PropertiesIndex >::heat_transfer_rate, particle_floating_mesh, and ParticleInteractionOutcomes< PropertiesIndex >::torque.
calculate_particle_wall_contact()
template<int dim, typename PropertiesIndex , ParticleWallContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_particle_wall_contact (typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double dt, ParticleInteractionOutcomes< PropertiesIndex > & contact_outcome) override virtual
Calculate the contact outcomes for particle-wall contacts using the contact pair information and physical properties.
Parameters
[in] particle_wall_pairs_in_contact Required information for the calculation of the particle-wall contact.
[in] dt DEM time step.
[out] contact_outcome Interaction outcomes.
Implements ParticleWallContactForceBase< dim, PropertiesIndex >.
Definition at line 37 of file particle_wall_contact_force.cc.
References find_projection(), ParticleInteractionOutcomes< PropertiesIndex >::force, get_location(), and ParticleInteractionOutcomes< PropertiesIndex >::torque.
calculate_rolling_resistance_torque()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Tensor< 1, 3 > ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque (const double particle_radius, const ArrayView< const double > & particle_properties, const double rolling_friction_coeff, const double rolling_viscous_damping_coeff, const double dt, const double normal_spring_constant, const double normal_force_norm, const Tensor< 1, 3 > & normal_unit_vector, Tensor< 1, 3 > & cumulative_rolling_resistance_spring_torque) inline private
Calculate the rolling resistance torque acting on the particle according to the rolling resistance model.
Parameters
[in] particle_radius Radius of the particle.
[in] particle_properties Properties of particle.
[in] rolling_friction_coeff Effective rolling friction coefficient.
[in] rolling_viscous_damping_coeff Effective rolling viscous damping coefficient
[in] dt DEM time step.
[in] normal_spring_constant Normal contact stiffness constant.
[in] normal_force_norm Norm of the normal force.
[in] normal_unit_vector Normal unit vector.
[in,out] cumulative_rolling_resistance_spring_torque Cumulative spring rolling resistance torque.
Returns
Rolling resistance torque.
Definition at line 486 of file particle_wall_contact_force.h.
References ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::f_coefficient_epsd, and no_rolling_torque().
find_projection()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Tensor< 1, 3 > ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::find_projection (const Tensor< 1, 3 > & vector_a, const Tensor< 1, 3 > & vector_b) inline protected
This function is used to find the projection of vector_a on vector_b.
Parameters
[in] vector_a A vector which is going to be projected on vector_b
[in] vector_b The projection vector of vector_a
Returns
The projection of vector_a on vector_b
Definition at line 288 of file particle_wall_contact_force.h.
get_force_calculation_threshold_distance()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> double ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::get_force_calculation_threshold_distance () inline protected
Calculate the minimum overlap at which particle-wall forces are computed. This function is useful for non-contact cohesive force models such as the DMT.
Returns
minimum overlap for the force calculation.
Definition at line 408 of file particle_wall_contact_force.h.
References Parameters::Lagrangian::DMT, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::dmt_cut_off_threshold, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_hamaker_constant, and ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy.
get_location()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Point< 3 > ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::get_location (const Particles::ParticleIterator< dim > & particle) & inline protected
Get the 3d location of the particle.
Parameters
[in] particle The particle to get the location from.
Returns
3d location of particle.
Definition at line 303 of file particle_wall_contact_force.h.
References point_nd_to_3d().
set_effective_properties()
template<int dim, typename PropertiesIndex , ParticleWallContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::set_effective_properties (const DEMSolverParameters< dim > & dem_parameters) private
Set every containers needed to carry the particle-wall force calculation.
Parameters
[in] dem_parameters DEM parameters declared in the .prm file.
Definition at line 367 of file particle_wall_contact_force.cc.
References DEMSolverParameters< dim >::boundary_conditions, Parameters::Lagrangian::BCDEM::boundary_rotational_speed, Parameters::Lagrangian::BCDEM::boundary_rotational_vector, Parameters::Lagrangian::BCDEM::boundary_translational_velocity, DEMSolverParameters< dim >::forces_torques, harmonic_mean(), DEMSolverParameters< dim >::lagrangian_physical_properties, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number, and Parameters::Lagrangian::BCDEM::point_on_rotation_axis.
set_multiphysic_properties()
template<int dim, typename PropertiesIndex , ParticleWallContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::set_multiphysic_properties (const DEMSolverParameters< dim > & dem_parameters) private
Set every containers needed to carry the heat transfer rate calculation.
Parameters
[in] dem_parameters DEM parameters declared in the .prm file.
Definition at line 484 of file particle_wall_contact_force.cc.
References harmonic_mean(), DEMSolverParameters< dim >::lagrangian_physical_properties, and Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number.
update_contact_information()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::update_contact_information (particle_wall_contact_info< dim > & contact_info, Tensor< 1, 3 > & tangential_relative_velocity, double & normal_relative_velocity_value, const Point< 3 > & particle_location, const ArrayView< const double > & particle_properties, const double dt) inline protected
Update the contact pair information for contact calculations.
Parameters
[in,out] contact_info Contact information of a particle-wall pair.
[out] tangential_relative_velocity Tangential relative velocity.
[out] normal_relative_velocity_value Normal relative contact velocity value.
[in] particle_location Location of particle in 3d.
[in] particle_properties Properties of particle.
[in] dt DEM time step.
Definition at line 145 of file particle_wall_contact_force.h.
References particle_wall_contact_info< dim >::boundary_id, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::boundary_rotational_speed_map, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::boundary_rotational_vector, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::boundary_translational_velocity_map, particle_wall_contact_info< dim >::normal_vector, ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::point_on_rotation_vector, and particle_wall_contact_info< dim >::tangential_displacement.
update_particle_solid_object_contact_information()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::update_particle_solid_object_contact_information (particle_wall_contact_info< dim > & contact_info, Tensor< 1, 3 > & tangential_relative_velocity, double & normal_relative_velocity_value, const ArrayView< const double > & particle_properties, const double dt, const Tensor< 1, 3 > & cut_cell_translational_velocity, const Tensor< 1, 3 > & cut_cell_rotational_velocity, const double center_of_rotation_particle_distance) inline protected
Update the contact pair information for particle-solid object contacts.
Parameters
[in,out] contact_info Contact information of a particle-wall pair.
[out] tangential_relative_velocity Tangential relative velocity.
[out] normal_relative_velocity_value Normal relative contact velocity value.
[in] particle_properties Properties of particle.
[in] dt DEM time step.
[in] cut_cell_translational_velocity Translational velocity of the cut cell.
[in] cut_cell_rotational_velocity Rotational veclocity of the cut cell.
[in] center_of_rotation_particle_distance Distance between the particle and the center of rotation of the floating mesh.
Definition at line 230 of file particle_wall_contact_force.h.
References particle_wall_contact_info< dim >::normal_vector, and particle_wall_contact_info< dim >::tangential_displacement.
Member Data Documentation
boundary_rotational_speed_map
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::unordered_map<unsigned int, double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::boundary_rotational_speed_map private
Definition at line 1071 of file particle_wall_contact_force.h.
boundary_rotational_vector
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::unordered_map<unsigned int, Tensor<1, 3> > ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::boundary_rotational_vector private
Definition at line 1074 of file particle_wall_contact_force.h.
boundary_translational_velocity_map
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::unordered_map<unsigned int, Tensor<1, 3> > ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::boundary_translational_velocity_map private
Definition at line 1073 of file particle_wall_contact_force.h.
center_mass_container
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Point<3> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::center_mass_container private
Definition at line 1077 of file particle_wall_contact_force.h.
dmt_cut_off_threshold
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> const double ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::dmt_cut_off_threshold private
Definition at line 1068 of file particle_wall_contact_force.h.
effective_coefficient_of_friction
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction private
Definition at line 1055 of file particle_wall_contact_force.h.
effective_coefficient_of_restitution
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_restitution private
Definition at line 1054 of file particle_wall_contact_force.h.
effective_coefficient_of_rolling_friction
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction private
Definition at line 1056 of file particle_wall_contact_force.h.
effective_coefficient_of_rolling_viscous_damping
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_viscous_damping private
Definition at line 1057 of file particle_wall_contact_force.h.
effective_hamaker_constant
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_hamaker_constant private
Definition at line 1059 of file particle_wall_contact_force.h.
effective_microhardness
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_microhardness private
Definition at line 1063 of file particle_wall_contact_force.h.
effective_real_youngs_modulus
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_real_youngs_modulus private
Definition at line 1052 of file particle_wall_contact_force.h.
effective_shear_modulus
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus private
Definition at line 1053 of file particle_wall_contact_force.h.
effective_surface_energy
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy private
Definition at line 1058 of file particle_wall_contact_force.h.
effective_youngs_modulus
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus private
Definition at line 1051 of file particle_wall_contact_force.h.
equivalent_surface_roughness
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::equivalent_surface_roughness private
Definition at line 1061 of file particle_wall_contact_force.h.
equivalent_surface_slope
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::equivalent_surface_slope private
Definition at line 1062 of file particle_wall_contact_force.h.
f_coefficient_epsd
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> const double ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::f_coefficient_epsd private
Definition at line 1069 of file particle_wall_contact_force.h.
gas_parameter_m
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::gas_parameter_m private
Definition at line 1065 of file particle_wall_contact_force.h.
gas_thermal_conductivity
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> double ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::gas_thermal_conductivity private
Definition at line 1066 of file particle_wall_contact_force.h.
model_parameter_beta
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta private
Definition at line 1060 of file particle_wall_contact_force.h.
n_particle_types
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> unsigned int ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::n_particle_types private
Definition at line 1050 of file particle_wall_contact_force.h.
particle_thermal_conductivity
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::particle_thermal_conductivity private
Definition at line 1064 of file particle_wall_contact_force.h.
point_on_rotation_vector
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::unordered_map<unsigned int, Point<3> > ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::point_on_rotation_vector private
Definition at line 1075 of file particle_wall_contact_force.h.
vertices_per_triangle
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> const unsigned int ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vertices_per_triangle = 3 private
Definition at line 1076 of file particle_wall_contact_force.h.
wall_thermal_conductivity
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleWallContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> double ParticleWallContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::wall_thermal_conductivity private
Definition at line 1067 of file particle_wall_contact_force.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/particle_wall_contact_force.h
/home/runner/work/lethe/lethe/source/dem/particle_wall_contact_force.cc