Lethe Open-Source Library: PhysicalPropertiesManager Class Reference
PhysicalPropertiesManager Class Reference
#include <physical_properties_manager.h>
Public Member Functions
PhysicalPropertiesManager ()
PhysicalPropertiesManager (Parameters::PhysicalProperties physical_properties)
void initialize (Parameters::PhysicalProperties physical_properties)
void provide_simulation_control (std::shared_ptr< SimulationControl > &simulation_control)
unsigned int get_number_of_fluids () const
unsigned int get_number_of_solids () const
unsigned int get_number_of_material_interactions () const
std::shared_ptr< DensityModel > get_density (const unsigned int fluid_id=0, const unsigned int material_id=0) const
std::shared_ptr< SpecificHeatModel > get_specific_heat (const unsigned int fluid_id=0, const unsigned int material_id=0) const
std::shared_ptr< ThermalConductivityModel > get_thermal_conductivity (const unsigned int fluid_id=0, const unsigned int material_id=0) const
std::shared_ptr< RheologicalModel > get_rheology (const unsigned int fluid_id=0, const unsigned int material_id=0) const
std::shared_ptr< ThermalExpansionModel > get_thermal_expansion (const unsigned int fluid_id=0, const unsigned int material_id=0) const
std::shared_ptr< TracerDiffusivityModel > get_tracer_diffusivity (const unsigned int fluid_id=0, const unsigned int material_id=0) const
std::shared_ptr< TracerReactionPrefactorModel > get_tracer_reaction_prefactor (const unsigned int fluid_id=0, const unsigned int material_id=0) const
std::shared_ptr< SurfaceTensionModel > get_surface_tension (const unsigned int material_interaction_id=0) const
std::shared_ptr< MobilityCahnHilliardModel > get_mobility_cahn_hilliard (const unsigned int material_interaction_id=0) const
std::vector< std::shared_ptr< DensityModel > > get_density_vector () const
std::vector< std::shared_ptr< SpecificHeatModel > > get_specific_heat_vector () const
std::vector< std::shared_ptr< ThermalConductivityModel > > get_thermal_conductivity_vector () const
std::vector< std::shared_ptr< RheologicalModel > > get_rheology_vector () const
std::vector< std::shared_ptr< ThermalExpansionModel > > get_thermal_expansion_vector () const
std::vector< Parameters::PhaseChange > get_phase_change_parameters_vector () const
std::vector< std::shared_ptr< TracerDiffusivityModel > > get_tracer_diffusivity_vector () const
std::vector< std::shared_ptr< SurfaceTensionModel > > get_surface_tension_vector () const
std::vector< std::shared_ptr< MobilityCahnHilliardModel > > get_mobility_cahn_hilliard_vector () const
double get_kinematic_viscosity_scale () const
double get_density_scale () const
void set_rheology (std::shared_ptr< RheologicalModel > p_rheology, const unsigned int fluid_id=0)
bool is_non_newtonian () const
bool field_is_required (const field id) const
bool density_is_constant () const
Parameters::PhysicalProperties get_physical_properties_parameters () const
bool has_phase_change () const
bool surface_tension_is_constant () const
unsigned int get_material_interaction_id (const material_interactions_type material_interaction_type, const unsigned int material_0_id, const unsigned int material_1_id) const
double get_reference_temperature () const
Public Attributes
bool is_initialized
Private Member Functions
void establish_fields_required_by_model (PhysicalPropertyModel &model)
void establish_fields_required_by_model (InterfacePropertyModel &model)
unsigned int calculate_global_id (const unsigned int fluid_id, const unsigned int material_id) const
Private Attributes
std::vector< std::shared_ptr< DensityModel > > density
std::vector< std::shared_ptr< SpecificHeatModel > > specific_heat
std::vector< std::shared_ptr< ThermalConductivityModel > > thermal_conductivity
std::vector< std::shared_ptr< RheologicalModel > > rheology
std::vector< std::shared_ptr< ThermalExpansionModel > > thermal_expansion
std::vector< std::shared_ptr< TracerDiffusivityModel > > tracer_diffusivity
std::vector< std::shared_ptr< TracerReactionPrefactorModel > > tracer_reaction_prefactor
std::vector< double > tracer_reaction_order
std::vector< std::shared_ptr< SurfaceTensionModel > > surface_tension
std::vector< std::shared_ptr< MobilityCahnHilliardModel > > mobility_cahn_hilliard
std::vector< Parameters::PhaseChange > phase_change_parameters
std::map< field, bool > required_fields
bool non_newtonian_flow
bool constant_density
bool constant_surface_tension
bool phase_change
double reference_temperature
Parameters::PhysicalProperties physical_properties_parameters
unsigned int number_of_fluids
unsigned int number_of_solids
unsigned int number_of_material_interactions
std::map< std::pair< unsigned int, unsigned int >, unsigned int > fluid_fluid_interactions_with_material_interaction_ids
std::map< std::pair< unsigned int, unsigned int >, unsigned int > fluid_solid_interactions_with_material_interaction_ids
Detailed Description
Class that manages the physical properties model which are required to calculate the various physical properties This centralizes the place where the models are created. The class can be constructed empty and initialized from parameters or it can be constructed directly with a Parameters section. The architecture of the PhysicalPropertiesManager is made to ensure that it can store as many physical properties models as required. It first stores the physical properties of the fluids, which are always assumed to lie in material_id=0, and then stores the physical properties of the solid, which may be in cells for which material_id>0.
Definition at line 57 of file physical_properties_manager.h.
Constructor & Destructor Documentation
PhysicalPropertiesManager() [1/2]
PhysicalPropertiesManager::PhysicalPropertiesManager () inline
Default constructor that initialized none of the physical properties.
Definition at line 63 of file physical_properties_manager.h.
PhysicalPropertiesManager() [2/2]
PhysicalPropertiesManager::PhysicalPropertiesManager (Parameters::PhysicalProperties physical_properties)
PhysicalPropertiesManager Constructor that initializes the class.
Parameters
physical_properties Parameters for the physical properties
Member Function Documentation
calculate_global_id()
unsigned int PhysicalPropertiesManager::calculate_global_id (const unsigned int fluid_id, const unsigned int material_id) const inline private
Calculates the global id of the physical property. By default. Lethe stores all the properties of the fluids, then the properties of the solid. Fluids need to have a material id of 0, then solids are consequential.
Parameters
fluid_id the id of the fluid (0 for single phase simulations, 0 or 1 for VOF simulations)
material_id the material id of the cell. Cells with material_id=0 are fluid cells (0 or 1) and cells with material_id>0 are solid cells
Definition at line 351 of file physical_properties_manager.h.
References number_of_fluids.
density_is_constant()
bool PhysicalPropertiesManager::density_is_constant () const inline
Definition at line 278 of file physical_properties_manager.h.
References constant_density.
establish_fields_required_by_model() [1/2]
void PhysicalPropertiesManager::establish_fields_required_by_model (InterfacePropertyModel & model) private
Definition at line 19 of file physical_properties_manager.cc.
References InterfacePropertyModel::depends_on(), and required_fields.
establish_fields_required_by_model() [2/2]
void PhysicalPropertiesManager::establish_fields_required_by_model (PhysicalPropertyModel & model) private
Definition at line 7 of file physical_properties_manager.cc.
References PhysicalPropertyModel::depends_on(), and required_fields.
field_is_required()
bool PhysicalPropertiesManager::field_is_required (const field id) const inline
Definition at line 272 of file physical_properties_manager.h.
References required_fields.
get_density()
std::shared_ptr< DensityModel > PhysicalPropertiesManager::get_density (const unsigned int fluid_id = 0, const unsigned int material_id = 0) const inline
Definition at line 117 of file physical_properties_manager.h.
References calculate_global_id(), and density.
get_density_scale()
double PhysicalPropertiesManager::get_density_scale () const inline
Definition at line 253 of file physical_properties_manager.h.
References density.
get_density_vector()
std::vector< std::shared_ptr< DensityModel > > PhysicalPropertiesManager::get_density_vector () const inline
Definition at line 188 of file physical_properties_manager.h.
References density.
get_kinematic_viscosity_scale()
double PhysicalPropertiesManager::get_kinematic_viscosity_scale () const inline
Definition at line 247 of file physical_properties_manager.h.
References rheology.
get_material_interaction_id()
unsigned int PhysicalPropertiesManager::get_material_interaction_id (const material_interactions_type material_interaction_type, const unsigned int material_0_id, const unsigned int material_1_id) const inline
Definition at line 302 of file physical_properties_manager.h.
References fluid_fluid, fluid_fluid_interactions_with_material_interaction_ids, fluid_solid, and fluid_solid_interactions_with_material_interaction_ids.
get_mobility_cahn_hilliard()
std::shared_ptr< MobilityCahnHilliardModel > PhysicalPropertiesManager::get_mobility_cahn_hilliard (const unsigned int material_interaction_id = 0) const inline
Returns the mobility model for a given material_interaction_id (integer)
Parameters
material_interaction_id
Returns
A shared pointer to a MobilityCahnHilliardModel which inherits from the InterfacePropertyModel class.
Definition at line 180 of file physical_properties_manager.h.
References mobility_cahn_hilliard.
get_mobility_cahn_hilliard_vector()
std::vector< std::shared_ptr< MobilityCahnHilliardModel > > PhysicalPropertiesManager::get_mobility_cahn_hilliard_vector () const inline
Returns the vector of all mobility models defined in the problem.
Returns
A vector of shared pointer, each one them pointing to a MobilityCahnHilliardModel.
Definition at line 241 of file physical_properties_manager.h.
References mobility_cahn_hilliard.
get_number_of_fluids()
unsigned int PhysicalPropertiesManager::get_number_of_fluids () const inline
Definition at line 98 of file physical_properties_manager.h.
References number_of_fluids.
get_number_of_material_interactions()
unsigned int PhysicalPropertiesManager::get_number_of_material_interactions () const inline
Definition at line 110 of file physical_properties_manager.h.
References number_of_material_interactions.
get_number_of_solids()
unsigned int PhysicalPropertiesManager::get_number_of_solids () const inline
Definition at line 104 of file physical_properties_manager.h.
References number_of_solids.
get_phase_change_parameters_vector()
std::vector< Parameters::PhaseChange > PhysicalPropertiesManager::get_phase_change_parameters_vector () const inline
Definition at line 218 of file physical_properties_manager.h.
References phase_change_parameters.
get_physical_properties_parameters()
Parameters::PhysicalProperties PhysicalPropertiesManager::get_physical_properties_parameters () const inline
Definition at line 284 of file physical_properties_manager.h.
References physical_properties_parameters.
get_reference_temperature()
double PhysicalPropertiesManager::get_reference_temperature () const inline
Definition at line 330 of file physical_properties_manager.h.
References reference_temperature.
get_rheology()
std::shared_ptr< RheologicalModel > PhysicalPropertiesManager::get_rheology (const unsigned int fluid_id = 0, const unsigned int material_id = 0) const inline
Definition at line 138 of file physical_properties_manager.h.
References calculate_global_id(), and rheology.
get_rheology_vector()
std::vector< std::shared_ptr< RheologicalModel > > PhysicalPropertiesManager::get_rheology_vector () const inline
Definition at line 206 of file physical_properties_manager.h.
References rheology.
get_specific_heat()
std::shared_ptr< SpecificHeatModel > PhysicalPropertiesManager::get_specific_heat (const unsigned int fluid_id = 0, const unsigned int material_id = 0) const inline
Definition at line 124 of file physical_properties_manager.h.
References calculate_global_id(), and specific_heat.
get_specific_heat_vector()
std::vector< std::shared_ptr< SpecificHeatModel > > PhysicalPropertiesManager::get_specific_heat_vector () const inline
Definition at line 194 of file physical_properties_manager.h.
References specific_heat.
get_surface_tension()
std::shared_ptr< SurfaceTensionModel > PhysicalPropertiesManager::get_surface_tension (const unsigned int material_interaction_id = 0) const inline
Definition at line 167 of file physical_properties_manager.h.
References surface_tension.
get_surface_tension_vector()
std::vector< std::shared_ptr< SurfaceTensionModel > > PhysicalPropertiesManager::get_surface_tension_vector () const inline
Definition at line 230 of file physical_properties_manager.h.
References surface_tension.
get_thermal_conductivity()
std::shared_ptr< ThermalConductivityModel > PhysicalPropertiesManager::get_thermal_conductivity (const unsigned int fluid_id = 0, const unsigned int material_id = 0) const inline
Definition at line 131 of file physical_properties_manager.h.
References calculate_global_id(), and thermal_conductivity.
get_thermal_conductivity_vector()
std::vector< std::shared_ptr< ThermalConductivityModel > > PhysicalPropertiesManager::get_thermal_conductivity_vector () const inline
Definition at line 200 of file physical_properties_manager.h.
References thermal_conductivity.
get_thermal_expansion()
std::shared_ptr< ThermalExpansionModel > PhysicalPropertiesManager::get_thermal_expansion (const unsigned int fluid_id = 0, const unsigned int material_id = 0) const inline
Definition at line 145 of file physical_properties_manager.h.
References calculate_global_id(), and thermal_expansion.
get_thermal_expansion_vector()
std::vector< std::shared_ptr< ThermalExpansionModel > > PhysicalPropertiesManager::get_thermal_expansion_vector () const inline
Definition at line 212 of file physical_properties_manager.h.
References thermal_expansion.
get_tracer_diffusivity()
std::shared_ptr< TracerDiffusivityModel > PhysicalPropertiesManager::get_tracer_diffusivity (const unsigned int fluid_id = 0, const unsigned int material_id = 0) const inline
Definition at line 152 of file physical_properties_manager.h.
References calculate_global_id(), and tracer_diffusivity.
get_tracer_diffusivity_vector()
std::vector< std::shared_ptr< TracerDiffusivityModel > > PhysicalPropertiesManager::get_tracer_diffusivity_vector () const inline
Definition at line 224 of file physical_properties_manager.h.
References tracer_diffusivity.
get_tracer_reaction_prefactor()
std::shared_ptr< TracerReactionPrefactorModel > PhysicalPropertiesManager::get_tracer_reaction_prefactor (const unsigned int fluid_id = 0, const unsigned int material_id = 0) const inline
Definition at line 159 of file physical_properties_manager.h.
References calculate_global_id(), and tracer_reaction_prefactor.
has_phase_change()
bool PhysicalPropertiesManager::has_phase_change () const inline
Definition at line 290 of file physical_properties_manager.h.
References phase_change.
initialize()
void PhysicalPropertiesManager::initialize (Parameters::PhysicalProperties physical_properties)
initialize Initializes the physical properties using the parameters
Parameters
physical_properties Parameters for the physical properties
Definition at line 31 of file physical_properties_manager.cc.
References constant_density, constant_surface_tension, density, establish_fields_required_by_model(), Parameters::PhysicalProperties::fluid_fluid_interactions_with_material_interaction_ids, fluid_fluid_interactions_with_material_interaction_ids, Parameters::PhysicalProperties::fluid_solid_interactions_with_material_interaction_ids, fluid_solid_interactions_with_material_interaction_ids, Parameters::PhysicalProperties::fluids, is_initialized, levelset, Parameters::PhysicalProperties::material_interactions, mobility_cahn_hilliard, DensityModel::model_cast(), RheologicalModel::model_cast(), SpecificHeatModel::model_cast(), ThermalConductivityModel::model_cast(), ThermalExpansionModel::model_cast(), TracerDiffusivityModel::model_cast(), TracerReactionPrefactorModel::model_cast(), MobilityCahnHilliardModel::model_cast(), SurfaceTensionModel::model_cast(), non_newtonian_flow, Parameters::PhysicalProperties::number_of_fluids, number_of_fluids, Parameters::PhysicalProperties::number_of_material_interactions, number_of_material_interactions, Parameters::PhysicalProperties::number_of_solids, number_of_solids, Parameters::Material::phase_change, phase_change, phase_change_parameters, phase_order_cahn_hilliard, physical_properties_parameters, pressure, Parameters::PhysicalProperties::reference_temperature, reference_temperature, required_fields, rheology, shear_rate, Parameters::PhysicalProperties::solids, specific_heat, surface_tension, temperature, temperature_p1, temperature_p2, thermal_conductivity, thermal_expansion, tracer_concentration, tracer_diffusivity, tracer_reaction_order, and tracer_reaction_prefactor.
is_non_newtonian()
bool PhysicalPropertiesManager::is_non_newtonian () const inline
Definition at line 266 of file physical_properties_manager.h.
References non_newtonian_flow.
provide_simulation_control()
void PhysicalPropertiesManager::provide_simulation_control (std::shared_ptr< SimulationControl > & simulation_control) inline
Definition at line 84 of file physical_properties_manager.h.
References number_of_fluids, number_of_solids, provide_simulation_control(), and specific_heat.
set_rheology()
void PhysicalPropertiesManager::set_rheology (std::shared_ptr< RheologicalModel > p_rheology, const unsigned int fluid_id = 0) inline
Definition at line 259 of file physical_properties_manager.h.
References rheology.
surface_tension_is_constant()
bool PhysicalPropertiesManager::surface_tension_is_constant () const inline
Definition at line 296 of file physical_properties_manager.h.
References constant_surface_tension.
Member Data Documentation
constant_density
bool PhysicalPropertiesManager::constant_density private
Definition at line 383 of file physical_properties_manager.h.
constant_surface_tension
bool PhysicalPropertiesManager::constant_surface_tension private
Definition at line 384 of file physical_properties_manager.h.
density
std::vector<std::shared_ptr<DensityModel> > PhysicalPropertiesManager::density private
Definition at line 366 of file physical_properties_manager.h.
fluid_fluid_interactions_with_material_interaction_ids
std::map<std::pair<unsigned int, unsigned int>, unsigned int> PhysicalPropertiesManager::fluid_fluid_interactions_with_material_interaction_ids private
Definition at line 402 of file physical_properties_manager.h.
fluid_solid_interactions_with_material_interaction_ids
std::map<std::pair<unsigned int, unsigned int>, unsigned int> PhysicalPropertiesManager::fluid_solid_interactions_with_material_interaction_ids private
Definition at line 404 of file physical_properties_manager.h.
is_initialized
bool PhysicalPropertiesManager::is_initialized
Definition at line 363 of file physical_properties_manager.h.
mobility_cahn_hilliard
std::vector<std::shared_ptr<MobilityCahnHilliardModel> > PhysicalPropertiesManager::mobility_cahn_hilliard private
Definition at line 377 of file physical_properties_manager.h.
non_newtonian_flow
bool PhysicalPropertiesManager::non_newtonian_flow private
Definition at line 382 of file physical_properties_manager.h.
number_of_fluids
unsigned int PhysicalPropertiesManager::number_of_fluids private
Definition at line 396 of file physical_properties_manager.h.
number_of_material_interactions
unsigned int PhysicalPropertiesManager::number_of_material_interactions private
Definition at line 398 of file physical_properties_manager.h.
number_of_solids
unsigned int PhysicalPropertiesManager::number_of_solids private
Definition at line 397 of file physical_properties_manager.h.
phase_change
bool PhysicalPropertiesManager::phase_change private
Definition at line 385 of file physical_properties_manager.h.
phase_change_parameters
std::vector<Parameters::PhaseChange> PhysicalPropertiesManager::phase_change_parameters private
Definition at line 378 of file physical_properties_manager.h.
physical_properties_parameters
Parameters::PhysicalProperties PhysicalPropertiesManager::physical_properties_parameters private
Definition at line 394 of file physical_properties_manager.h.
reference_temperature
double PhysicalPropertiesManager::reference_temperature private
Definition at line 391 of file physical_properties_manager.h.
required_fields
std::map<field, bool> PhysicalPropertiesManager::required_fields private
Definition at line 380 of file physical_properties_manager.h.
rheology
std::vector<std::shared_ptr<RheologicalModel> > PhysicalPropertiesManager::rheology private
Definition at line 369 of file physical_properties_manager.h.
specific_heat
std::vector<std::shared_ptr<SpecificHeatModel> > PhysicalPropertiesManager::specific_heat private
Definition at line 367 of file physical_properties_manager.h.
surface_tension
std::vector<std::shared_ptr<SurfaceTensionModel> > PhysicalPropertiesManager::surface_tension private
Definition at line 375 of file physical_properties_manager.h.
thermal_conductivity
std::vector<std::shared_ptr<ThermalConductivityModel> > PhysicalPropertiesManager::thermal_conductivity private
Definition at line 368 of file physical_properties_manager.h.
thermal_expansion
std::vector<std::shared_ptr<ThermalExpansionModel> > PhysicalPropertiesManager::thermal_expansion private
Definition at line 370 of file physical_properties_manager.h.
tracer_diffusivity
std::vector<std::shared_ptr<TracerDiffusivityModel> > PhysicalPropertiesManager::tracer_diffusivity private
Definition at line 371 of file physical_properties_manager.h.
tracer_reaction_order
std::vector<double> PhysicalPropertiesManager::tracer_reaction_order private
Definition at line 374 of file physical_properties_manager.h.
tracer_reaction_prefactor
std::vector<std::shared_ptr<TracerReactionPrefactorModel> > PhysicalPropertiesManager::tracer_reaction_prefactor private
Definition at line 373 of file physical_properties_manager.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/physical_properties_manager.h
/home/runner/work/lethe/lethe/source/solvers/physical_properties_manager.cc