Lethe Open-Source Library: NavierStokesCouplingEvaluationSIPG< dim, Number > Class Template Reference
NavierStokesCouplingEvaluationSIPG< dim, Number > Class Template Reference
#include <mortar_coupling_manager.h>
Public Types
using FEPointIntegratorU = FEPointEvaluation< dim, dim, dim, Number >
using FEPointIntegratorP = FEPointEvaluation< 1, dim, dim, Number >
using u_value_type = typename FEPointIntegratorU::value_type
Public Member Functions
NavierStokesCouplingEvaluationSIPG (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const double kinematic_viscosity)
virtual ~NavierStokesCouplingEvaluationSIPG ()=default
unsigned int data_size () const override
const std::vector< unsigned int > & get_relevant_dof_indices () const override
void local_reinit (const typename Triangulation< dim >::cell_iterator &cell, const ArrayView< const Point< dim, Number > > &points) const override
void local_evaluate (const CouplingEvaluationData< dim, Number > &data, const Vector< Number > &buffer, const unsigned int ptr_q, const unsigned int q_stride, Number *all_values_local) const override
void local_integrate (const CouplingEvaluationData< dim, Number > &data, Vector< Number > &buffer, const unsigned int ptr_q, const unsigned int q_stride, Number *all_values_m, Number *all_values_p) const override
Public Member Functions inherited from CouplingEvaluationBase< dim, Number >
virtual ~CouplingEvaluationBase ()=default
Public Attributes
const FESystem< dim > fe_sub_u
const FESystem< dim > fe_sub_p
FEPointIntegratorU phi_u_m
FEPointIntegratorP phi_p_m
std::vector< unsigned int > relevant_dof_indices
const double kinematic_viscosity
Detailed Description
template<int dim, typename Number>
class NavierStokesCouplingEvaluationSIPG< dim, Number >
Definition at line 1149 of file mortar_coupling_manager.h.
Member Typedef Documentation
FEPointIntegratorP
template<int dim, typename Number > using NavierStokesCouplingEvaluationSIPG< dim, Number >::FEPointIntegratorP = FEPointEvaluation<1, dim, dim, Number>
Definition at line 1154 of file mortar_coupling_manager.h.
FEPointIntegratorU
template<int dim, typename Number > using NavierStokesCouplingEvaluationSIPG< dim, Number >::FEPointIntegratorU = FEPointEvaluation<dim, dim, dim, Number>
Definition at line 1153 of file mortar_coupling_manager.h.
u_value_type
template<int dim, typename Number > using NavierStokesCouplingEvaluationSIPG< dim, Number >::u_value_type = typename FEPointIntegratorU::value_type
Definition at line 1156 of file mortar_coupling_manager.h.
Constructor & Destructor Documentation
NavierStokesCouplingEvaluationSIPG()
template<int dim, typename Number > NavierStokesCouplingEvaluationSIPG< dim, Number >::NavierStokesCouplingEvaluationSIPG (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const double kinematic_viscosity)
Class constructor.
Parameters
[in] mapping Mapping associated to the domain
[in] dof_handler DoFHandler associated to the triangulation
[in] kinematic_vicosity Kinematic viscosity
Definition at line 1904 of file mortar_coupling_manager.cc.
References NavierStokesCouplingEvaluationSIPG< dim, Number >::relevant_dof_indices.
~NavierStokesCouplingEvaluationSIPG()
template<int dim, typename Number > virtual NavierStokesCouplingEvaluationSIPG< dim, Number >::~NavierStokesCouplingEvaluationSIPG () virtual default
Default destructor.
Member Function Documentation
data_size()
template<int dim, typename Number > unsigned int NavierStokesCouplingEvaluationSIPG< dim, Number >::data_size () const override virtual
Number of data points of type Number associated to a quadrature point.
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1932 of file mortar_coupling_manager.cc.
get_relevant_dof_indices()
template<int dim, typename Number > const std::vector< unsigned int > & NavierStokesCouplingEvaluationSIPG< dim, Number >::get_relevant_dof_indices () const override virtual
Return relevant dof indices.
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1939 of file mortar_coupling_manager.cc.
local_evaluate()
template<int dim, typename Number > void NavierStokesCouplingEvaluationSIPG< dim, Number >::local_evaluate (const CouplingEvaluationData< dim, Number > & data, const Vector< Number > & buffer, const unsigned int ptr_q, const unsigned int q_stride, Number * all_value_m) const override virtual
Evaluate values and gradients at the coupling entries.
Parameters
[in] data Coupling evaluation data containing values of normals, weights, and penalty parameters at each integration point
[in,out] buffer Temporary vector where data is stored before being passes to the system matrix
[in] ptr_q Pointer for the quadrature point index related to the rotor-stator interface
[in] q_stride Pointer for the cell index in which the quadrature point lies in
[in] all_value_m Number of values stored in the mortar side of the interface
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1957 of file mortar_coupling_manager.cc.
References CouplingEvaluationData< dim, Number >::all_normals, contract(), and BufferRW< T >::write().
local_integrate()
template<int dim, typename Number > void NavierStokesCouplingEvaluationSIPG< dim, Number >::local_integrate (const CouplingEvaluationData< dim, Number > & data, Vector< Number > & buffer, const unsigned int ptr_q, const unsigned int q_stride, Number * all_value_m, Number * all_value_p) const override virtual
Perform integral of mortar elements at the rotor-stator interface.
Parameters
[in] data Coupling evaluation data containing values of normals, weights, and penalty parameters at each integration point
[in] buffer Temporary vector where data is stored before being passes to the system matrix
[in] ptr_q Pointer for the quadrature point index related to the rotor-stator interface
[in] q_stride Pointer for the cell index in which the quadrature point lies in
[in] all_value_m Number of values stored in the mortar side of the interface
[in] all_value_p Number of values stored in the non-mortar side of the interface
Notation referring to quantities on both mortar sides: {{.}} = avg(.), and [.] = jump(.) *
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 2003 of file mortar_coupling_manager.cc.
References CouplingEvaluationData< dim, Number >::all_normals, CouplingEvaluationData< dim, Number >::all_penalty_parameter, CouplingEvaluationData< dim, Number >::all_weights, contract(), outer(), and CouplingEvaluationData< dim, Number >::penalty_factor.
local_reinit()
template<int dim, typename Number > void NavierStokesCouplingEvaluationSIPG< dim, Number >::local_reinit (const typename Triangulation< dim >::cell_iterator & cell, const ArrayView< const Point< dim, Number > > & points) const override virtual
Set up mapping information.
Parameters
[in] cell Cell iterator
[in] points List of points where FEPointIntegrator should be evaluated
Implements CouplingEvaluationBase< dim, Number >.
Definition at line 1947 of file mortar_coupling_manager.cc.
Member Data Documentation
fe_sub_p
template<int dim, typename Number > const FESystem<dim> NavierStokesCouplingEvaluationSIPG< dim, Number >::fe_sub_p
Definition at line 1202 of file mortar_coupling_manager.h.
fe_sub_u
template<int dim, typename Number > const FESystem<dim> NavierStokesCouplingEvaluationSIPG< dim, Number >::fe_sub_u
Finite element that matches the components n_components components starting at component with index first_selected_component.
Definition at line 1201 of file mortar_coupling_manager.h.
kinematic_viscosity
template<int dim, typename Number > const double NavierStokesCouplingEvaluationSIPG< dim, Number >::kinematic_viscosity
Kinematic viscosity.
Definition at line 1212 of file mortar_coupling_manager.h.
phi_p_m
template<int dim, typename Number > FEPointIntegratorP NavierStokesCouplingEvaluationSIPG< dim, Number >::phi_p_m mutable
Definition at line 1206 of file mortar_coupling_manager.h.
phi_u_m
template<int dim, typename Number > FEPointIntegratorU NavierStokesCouplingEvaluationSIPG< dim, Number >::phi_u_m mutable
Interface to the evaluation of mortar coupling interpolated solution.
Definition at line 1205 of file mortar_coupling_manager.h.
relevant_dof_indices
template<int dim, typename Number > std::vector<unsigned int> NavierStokesCouplingEvaluationSIPG< dim, Number >::relevant_dof_indices
Relevant dof indices.
Definition at line 1209 of file mortar_coupling_manager.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/mortar_coupling_manager.h
/home/runner/work/lethe/lethe/source/core/mortar_coupling_manager.cc