Lethe Open-Source Library: CFDDEMSolver< dim > Class Template Reference
CFDDEMSolver< dim > Class Template Reference
#include <cfd_dem_coupling.h>
Public Member Functions
CFDDEMSolver (CFDDEMSimulationParameters< dim > &nsparam)
~CFDDEMSolver () override
virtual void solve () override
Public Member Functions inherited from FluidDynamicsVANS< dim >
FluidDynamicsVANS (CFDDEMSimulationParameters< dim > &nsparam)
~FluidDynamicsVANS ()
Public Member Functions inherited from FluidDynamicsMatrixBased< dim >
FluidDynamicsMatrixBased (SimulationParameters< dim > &nsparam)
~FluidDynamicsMatrixBased ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
PhysicsSolver ()
virtual ~PhysicsSolver ()
void solve_governing_system ()
virtual void apply_constraints ()
virtual double get_current_residual ()
unsigned int get_current_newton_iteration () const
Private Member Functions
void dem_setup_parameters ()
void setup_distribution_type ()
std::shared_ptr< Insertion< dim, DEM::CFDDEMProperties::PropertiesIndex > > set_insertion_type ()
std::shared_ptr< Integrator< dim, DEM::CFDDEMProperties::PropertiesIndex > > set_integrator_type ()
void initialize_dem_parameters ()
void read_dem () override
void set_initial_condition (const Parameters::FluidDynamicsInitialConditionType initial_condition_type, const bool restart=false) override
std::vector< OutputStructTableHandler > gather_tables () override
void write_checkpoint () override
void read_checkpoint () override
void check_contact_detection_method (unsigned int counter)
void load_balance ()
void insert_particles ()
void add_fluid_particle_interaction_force ()
void add_fluid_particle_interaction_torque ()
void particle_wall_contact_force ()
void write_dem_output_results ()
void report_particle_statistics ()
void print_particles_summary ()
void postprocess_fd (bool first_iteration) override
void postprocess_cfd_dem ()
void dynamic_flow_control () override
void sort_particles_into_subdomains_and_cells ()
void dem_iterator (unsigned int counter)
void update_dem_time_step ()
void dem_contact_build (unsigned int counter)
Private Attributes
unsigned int coupling_frequency
Tensor< 1, 3 > g
ParticleInteractionOutcomes< DEM::CFDDEMProperties::PropertiesIndex > contact_outcome
std::vector< Tensor< 1, 3 > > & torque = contact_outcome.torque
std::vector< Tensor< 1, 3 > > & force = contact_outcome.force
std::vector< double > displacement
std::vector< double > MOI
double neighborhood_threshold_squared
std::vector< std::shared_ptr< Distribution > > size_distribution_object_container
double maximum_particle_diameter
double smallest_contact_search_criterion
OngoingCollisionLog< dim > ongoing_collision_log
CompletedCollisionLog< dim > collision_event_log
DEMContactManager< dim, DEM::CFDDEMProperties::PropertiesIndex > contact_manager
LagrangianLoadBalancing< dim, DEM::CFDDEMProperties::PropertiesIndex > load_balancing
ParticlePointLineForce< dim, DEM::CFDDEMProperties::PropertiesIndex > particle_point_line_contact_force_object
std::shared_ptr< Integrator< dim, DEM::CFDDEMProperties::PropertiesIndex > > integrator_object
std::shared_ptr< Insertion< dim, DEM::CFDDEMProperties::PropertiesIndex > > insertion_object
std::shared_ptr< ParticleParticleContactForceBase< dim, DEM::CFDDEMProperties::PropertiesIndex > > particle_particle_contact_force_object
std::shared_ptr< ParticleWallContactForceBase< dim, DEM::CFDDEMProperties::PropertiesIndex > > particle_wall_contact_force_object
Visualization< dim, DEM::CFDDEMProperties::PropertiesIndex > visualization_object
BoundaryCellsInformation< dim > boundary_cell_object
dem_data_structures< dim >::solid_surfaces_mesh_information solid_surfaces_mesh_info
dem_data_structures< dim >::boundary_points_and_normal_vectors updated_boundary_points_and_normal_vectors
dem_data_structures< dim >::vector_on_boundary forces_boundary_information
dem_data_structures< dim >::vector_on_boundary torques_boundary_information
DEM::dem_data_structures< dim >::periodic_boundaries_cells_info periodic_boundaries_cells_information
PeriodicBoundariesManipulator< dim > periodic_boundaries_object
AdaptiveSparseContacts< dim, DEM::CFDDEMProperties::PropertiesIndex > sparse_contacts_object
unsigned int contact_search_counter
unsigned int contact_search_total_number
statistics contact_list
DEM::ParticleProperties< dim, DEM::CFDDEMProperties::PropertiesIndex > properties_class
PVDHandler grid_pvdhandler
PVDHandler particles_pvdhandler
DEMSolverParameters< dim > dem_parameters
double dem_time_step
double rayleigh_time_step
const unsigned int this_mpi_process
const unsigned int n_mpi_processes
TableHandler table_phase_volumes
DEMActionManager * dem_action_manager
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Protected Member Functions inherited from FluidDynamicsVANS< dim >
virtual void setup_dofs () override
virtual void iterate () override
void calculate_void_fraction (const double time)
void vertices_cell_mapping ()
virtual void monitor_mass_conservation ()
virtual void finish_time_step_fd ()
void assemble_system_matrix () override
void assemble_system_rhs () override
void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
void setup_assemblers () override
void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data) override
void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data) override
virtual std::vector< OutputStruct< dim, GlobalVectorType > > gather_output_hook () override
Protected Member Functions inherited from FluidDynamicsMatrixBased< dim >
virtual void setup_dofs_fd () override
void multi_stage_preresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method) override
virtual void multi_stage_postresolution (unsigned int stage, Parameters::SimulationControl::TimeSteppingMethod method, double time_step) override
virtual void update_multi_stage_solution (double time_step) override
virtual void set_initial_condition_fd (Parameters::FluidDynamicsInitialConditionType initial_condition_type, bool restart=false) override
virtual void update_multiphysics_time_average_solution () override
void setup_preconditioner () override
void define_dynamic_zero_constraints ()
void define_pressure_constraints ()
virtual void update_mortar_configuration () override
void solve_linear_system () override
Protected Member Functions inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual GlobalVectorType & get_evaluation_point () override
virtual GlobalVectorType & get_local_evaluation_point () override
virtual GlobalVectorType & get_newton_update () override
virtual GlobalVectorType & get_present_solution () override
virtual GlobalVectorType & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
virtual void output_newton_update_norms (const unsigned int display_precision) override
double get_residual_rescale_metric () const override
void finish_simulation ()
virtual void postprocess (bool first_iteration)
virtual void finish_time_step ()
virtual void percolate_time_vectors_fd ()
void finish_simulation_fd ()
virtual void update_solutions_for_multiphysics ()
virtual void update_solutions_for_fluid_dynamics ()
void postprocessing_forces (const GlobalVectorType &evaluation_point)
void postprocessing_torques (const GlobalVectorType &evaluation_point)
virtual void enable_dynamic_zero_constraints_fd ()
void box_refine_mesh (const bool restart)
virtual void refine_mesh ()
void refine_mesh_kelly ()
void refine_mesh_uniform ()
void transfer_solution (SolutionTransfer< dim, GlobalVectorType > &solution_transfer, std::vector< SolutionTransfer< dim, GlobalVectorType > > &previous_solutions_transfer)
virtual void set_solution_from_checkpoint (std::string checkpoint_file_prefix)
void set_nodal_values ()
void define_non_zero_constraints ()
void define_zero_constraints ()
void reinit_mortar_operators ()
std::shared_ptr< Mapping< dim > > get_mapping ()
void rotate_rotor_mapping (const bool is_first)
void update_boundary_conditions ()
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
void establish_solid_domain (const bool non_zero_constraints)
bool cell_in_constraining_domain (const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &plane_point, const Tensor< 1, dim > &plane_normal_vector)
void get_cell_temperature_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_ht, const GlobalVectorType &temperature_solution, std::vector< double > &local_temperature_values)
void get_cell_filtered_phase_fraction_values (const typename DoFHandler< dim >::active_cell_iterator &cell, const DoFHandler< dim > *dof_handler_vof, const GlobalVectorType &filtered_phase_fraction_solution, std::vector< double > &local_filtered_phase_fraction_values)
void identify_cell_and_constrain_velocity (const std::vector< types::global_dof_index > &local_dof_indices, const std::vector< double > &local_temperature_values, StasisConstraintWithTemperature &stasis_constraint_struct)
void constrain_solid_cell_velocity_dofs (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void flag_dofs_in_solid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_in_solid)
void flag_dofs_connected_to_fluid (const std::vector< types::global_dof_index > &local_dof_indices, std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid)
bool check_cell_is_connected_to_fluid (const std::unordered_set< types::global_dof_index > &dofs_are_connected_to_fluid, const std::vector< types::global_dof_index > &local_dof_indices)
void constrain_pressure (const bool &non_zero_constraints, const std::vector< types::global_dof_index > &local_dof_indices, AffineConstraints< double > &zero_constraints)
void constrain_stasis_with_temperature (const DoFHandler< dim > *dof_handler_ht)
void constrain_stasis_with_temperature_vof (const DoFHandler< dim > *dof_handler_vof, const DoFHandler< dim > *dof_handler_ht)
void gather_output_results (const GlobalVectorType &solution, std::vector< OutputStruct< dim, GlobalVectorType > > &solution_output_structs)
void write_output_results (const GlobalVectorType &solution)
void write_output_forces ()
void write_output_torques ()
void rescale_pressure_dofs_in_newton_update ()
GlobalVectorType init_temporary_vector ()
void verify_consistency_of_boundary_conditions ()
Protected Attributes inherited from FluidDynamicsVANS< dim >
CFDDEMSimulationParameters< dim > cfd_dem_simulation_parameters
MappingQGeneric< dim > particle_mapping
std::vector< std::shared_ptr< ParticleFluidAssemblerBase< dim > > > particle_fluid_assemblers
const bool PSPG = true
const bool SUPG = true
const double GLS_u_scale = 1
double pressure_drop
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_cell
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_periodic_cell
Particles::ParticleHandler< dim, dim > particle_handler
ParticleProjector< dim > particle_projector
bool has_periodic_boundaries
Tensor< 1, dim > periodic_offset
unsigned int periodic_direction
Protected Attributes inherited from FluidDynamicsMatrixBased< dim >
TrilinosWrappers::SparseMatrix system_matrix
Protected Attributes inherited from NavierStokesBase< dim, GlobalVectorType, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< DoFHandler< dim > > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
PVDHandler pvdhandler_boundary
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
bool use_manifold_for_normal
GlobalVectorType evaluation_point
GlobalVectorType local_evaluation_point
GlobalVectorType newton_update
std::shared_ptr< GlobalVectorType > present_solution
GlobalVectorType system_rhs
std::shared_ptr< std::vector< GlobalVectorType > > previous_solutions
SDIRKVectors sdirk_vectors
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::shared_ptr< MortarManagerCircle< dim > > mortar_manager
std::shared_ptr< CouplingOperator< dim, double > > mortar_coupling_operator
std::shared_ptr< NavierStokesCouplingEvaluation< dim, double > > mortar_coupling_evaluator
std::shared_ptr< MappingQCache< dim > > mapping_cache
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler pressure_power_table
TableHandler viscous_dissipation_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, GlobalVectorType, IndexSet > > average_velocities
GlobalVectorType average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > forces_on_boundaries
std::map< types::boundary_id, TableHandler > forces_tables
std::map< types::boundary_id, TableHandler > torques_tables
std::shared_ptr< FEValues< dim > > fe_values_temperature
std::shared_ptr< FEValues< dim > > fe_values_vof
std::vector< StasisConstraintWithTemperature > stasis_constraint_structs
AffineConstraints< double > dynamic_zero_constraints
Detailed Description
template<int dim>
class CFDDEMSolver< dim >
Solver class for coupled Computational Fluid Dynamics and Discrete Element Method (CFD-DEM) simulations.
This class implements a two-way coupled CFD-DEM solver that combines the Volume-averaged Navier-Stokes (VANS) equations for fluid flow with the soft-sphere Discrete Element Method for particle dynamics. The solver enables simulation of fluid-particle interactions in systems containing dense particle suspensions.
The CFD component uses Galerkin Least Squares (GLS) stabilization for the VANS equations, while the DEM component handles particle-particle and particle-wall collisions using the soft-sphere contact model.
Template Parameters
dim Spatial dimension of the simulation (2 or 3)
Definition at line 44 of file cfd_dem_coupling.h.
Constructor & Destructor Documentation
CFDDEMSolver()
template<int dim> CFDDEMSolver< dim >::CFDDEMSolver (CFDDEMSimulationParameters< dim > & nsparam)
Constructor for the CFD-DEM solver.
Parameters
[in] nsparam Simulation parameters containing all CFD-DEM configuration options
Definition at line 26 of file cfd_dem_coupling.cc.
~CFDDEMSolver()
template<int dim> CFDDEMSolver< dim >::~CFDDEMSolver () override default
Destructor for the CFD-DEM solver.
Member Function Documentation
add_fluid_particle_interaction_force()
template<int dim> void CFDDEMSolver< dim >::add_fluid_particle_interaction_force () private
Calculate and add fluid-particle interaction forces.
Computes the hydrodynamic forces acting on particles due to fluid motion and adds them to the particle force container for use in DEM integration.
Definition at line 948 of file cfd_dem_coupling.cc.
References DEM::CFDDEMProperties::fem_drag_x, DEM::CFDDEMProperties::fem_drag_y, DEM::CFDDEMProperties::fem_drag_z, DEM::CFDDEMProperties::fem_force_one_way_coupling_x, DEM::CFDDEMProperties::fem_force_one_way_coupling_y, DEM::CFDDEMProperties::fem_force_one_way_coupling_z, DEM::CFDDEMProperties::fem_force_two_way_coupling_x, DEM::CFDDEMProperties::fem_force_two_way_coupling_y, and DEM::CFDDEMProperties::fem_force_two_way_coupling_z.
add_fluid_particle_interaction_torque()
template<int dim> void CFDDEMSolver< dim >::add_fluid_particle_interaction_torque () private
Calculate and add fluid-particle interaction torques.
Computes the hydrodynamic torques acting on particles due to fluid motion and adds them to the particle torque container for use in DEM integration.
Definition at line 981 of file cfd_dem_coupling.cc.
References DEM::CFDDEMProperties::fem_torque_x, DEM::CFDDEMProperties::fem_torque_y, and DEM::CFDDEMProperties::fem_torque_z.
check_contact_detection_method()
template<int dim> void CFDDEMSolver< dim >::check_contact_detection_method (unsigned int counter) private
Check if contact detection is required and execute it if necessary.
Determines whether a contact detection step should be performed based on the contact detection frequency and executes the appropriate contact detection algorithm.
Parameters
[in] counter Current DEM iteration number
Definition at line 732 of file cfd_dem_coupling.cc.
References Parameters::Lagrangian::ModelParameters< dim >::contact_detection_frequency, Parameters::Lagrangian::ModelParameters< dim >::contact_detection_method, and find_particle_contact_detection_step().
dem_contact_build()
template<int dim> void CFDDEMSolver< dim >::dem_contact_build (unsigned int counter) private
Perform contact detection and build contact lists.
Checks if a contact search should be performed based on the contact detection frequency and executes the appropriate contact detection algorithm to identify particle-particle and particle-wall contacts.
Parameters
[in] counter Current DEM iteration number
Definition at line 1522 of file cfd_dem_coupling.cc.
dem_iterator()
template<int dim> void CFDDEMSolver< dim >::dem_iterator (unsigned int counter) private
Execute a complete DEM iteration step.
Performs a full DEM time step including particle-particle and particle-wall contact force calculations, time integration of particle motion, and updates to particle positions and velocities.
Parameters
[in] counter Current DEM iteration number
Definition at line 1440 of file cfd_dem_coupling.cc.
dem_setup_parameters()
template<int dim> void CFDDEMSolver< dim >::dem_setup_parameters () private
Set up the various parameters related to the DEM simulation.
Initializes DEM-specific parameters including contact detection methods, integration schemes, and material properties based on the simulation parameters provided during construction.
Definition at line 37 of file cfd_dem_coupling.cc.
References DEMActionManager::get_action_manager(), Parameters::Lagrangian::BCDEM::periodic, and set_particle_particle_contact_force_model().
dynamic_flow_control()
template<int dim> void CFDDEMSolver< dim >::dynamic_flow_control () override private virtual
Calculate dynamic flow control accounting for void fraction.
Performs dynamic flow control calculations that incorporate the local void fraction (porosity) field in the average velocity computation, enabling proper flow control in particle-laden flows.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 1336 of file cfd_dem_coupling.cc.
References announce_string(), calculate_average_velocity(), Parameters::SimulationControl::steady, and Parameters::verbose.
gather_tables()
template<int dim> std::vector< OutputStructTableHandler > CFDDEMSolver< dim >::gather_tables () override private virtual
Gather TableHandler objects for serialization during checkpointing.
Collects all TableHandler objects that need to be serialized and deserialized during checkpoint operations, including their associated file names for proper storage and retrieval.
Returns
Vector of OutputStructTableHandler containing references to TableHandler objects and their corresponding file names
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 448 of file cfd_dem_coupling.cc.
References Parameters::PostProcessing::calculate_phase_volumes, and Parameters::PostProcessing::phase_volumes_output_name.
initialize_dem_parameters()
template<int dim> void CFDDEMSolver< dim >::initialize_dem_parameters () private
Initialize fundamental DEM simulation parameters.
Sets up basic DEM parameters including time stepping, contact detection frequency, and other core simulation settings.
Definition at line 286 of file cfd_dem_coupling.cc.
References set_particle_wall_contact_force_model().
insert_particles()
template<int dim> void CFDDEMSolver< dim >::insert_particles () private
Check if particles need to be inserted and perform insertion.
Determines if new particles should be inserted into the simulation domain based on the insertion parameters and executes particle insertion using the configured insertion method.
Definition at line 1002 of file cfd_dem_coupling.cc.
load_balance()
template<int dim> void CFDDEMSolver< dim >::load_balance () private
Check if load balancing is required and perform it if necessary.
Evaluates the current load distribution across MPI processes and performs load balancing to maintain computational efficiency when particle distribution becomes uneven.
Definition at line 770 of file cfd_dem_coupling.cc.
particle_wall_contact_force()
template<int dim> void CFDDEMSolver< dim >::particle_wall_contact_force () private
Calculate contact forces between particles and walls.
Computes collision forces and torques resulting from particle-wall interactions using the soft-sphere contact model.
Definition at line 1029 of file cfd_dem_coupling.cc.
postprocess_cfd_dem()
template<int dim> void CFDDEMSolver< dim >::postprocess_cfd_dem () private
Perform CFD-DEM coupled post-processing after each iteration.
Executes post-processing operations specific to the coupled CFD-DEM simulation including coupled field analysis and specialized output generation.
Definition at line 1276 of file cfd_dem_coupling.cc.
References calculate_fluid_and_particle_volumes(), and Parameters::verbose.
postprocess_fd()
template<int dim> void CFDDEMSolver< dim >::postprocess_fd (bool first_iteration) override private virtual
Perform fluid dynamics post-processing after each iteration.
Executes post-processing operations specific to the fluid dynamics component including output writing and monitoring.
Parameters
[in] first_iteration Flag indicating if this is the first iteration
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 1257 of file cfd_dem_coupling.cc.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::postprocess_fd().
print_particles_summary()
template<int dim> void CFDDEMSolver< dim >::print_particles_summary () private
Print final summary of particle simulation results.
Outputs a comprehensive summary of the particle simulation including final particle positions, velocities, and other relevant information at the end of the simulation.
Definition at line 1185 of file cfd_dem_coupling.cc.
References DEM::CFDDEMProperties::v_x, DEM::CFDDEMProperties::v_y, and DEM::CFDDEMProperties::v_z.
read_checkpoint()
template<int dim> void CFDDEMSolver< dim >::read_checkpoint () override private virtual
Read CFD-DEM simulation checkpoint files.
Loads the complete simulation state from previously written checkpoint files to restart a CFD-DEM simulation from a specific time step.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 564 of file cfd_dem_coupling.cc.
References deserialize_tables_vector(), and NavierStokesBase< dim, VectorType, DofsType >::gather_tables().
read_dem()
template<int dim> void CFDDEMSolver< dim >::read_dem () override private virtual
Read DEM restart files from a previous simulation.
Loads particle data, contact information, and other DEM state variables from checkpoint files to continue a previously interrupted simulation.
Reimplemented from FluidDynamicsVANS< dim >.
Definition at line 356 of file cfd_dem_coupling.cc.
References convert_particle_handler(), and DEM::DEMProperties::n_properties.
report_particle_statistics()
template<int dim> void CFDDEMSolver< dim >::report_particle_statistics () private
Calculate and report particle statistics to the terminal.
Computes and displays comprehensive statistics about particle behavior including minimum, maximum, and average values for linear velocity, angular velocity, kinetic energies, and contact search performance metrics.
Definition at line 1091 of file cfd_dem_coupling.cc.
References add_statistics_to_table_handler(), announce_string(), DEM::calculate_granular_statistics(), DEM::omega, DEM::rotational_kinetic_energy, DEM::translational_kinetic_energy, and DEM::velocity.
set_initial_condition()
template<int dim> void CFDDEMSolver< dim >::set_initial_condition (const Parameters::FluidDynamicsInitialConditionType initial_condition_type, const bool restart = false) inline override private virtual
Set the initial condition. The version in this class does not output the solution, since the void fraction is not initialized yet.
Parameters
[in] initial_condition_type Type of method use to impose initial condition.
[in] restart Indicator if the simulation is being restarted or not.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 140 of file cfd_dem_coupling.h.
References NavierStokesBase< dim, GlobalVectorType, IndexSet >::multiphysics, PhysicsSolver< VectorType >::pcout, NavierStokesBase< dim, GlobalVectorType, IndexSet >::refine_mesh(), FluidDynamicsMatrixBased< dim >::set_initial_condition_fd(), and NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_parameters.
set_insertion_type()
template<int dim> std::shared_ptr< Insertion< dim, DEM::CFDDEMProperties::PropertiesIndex > > CFDDEMSolver< dim >::set_insertion_type () private
Set up the particle insertion method for the simulation.
Creates and configures the appropriate insertion object based on the simulation parameters (e.g., volume insertion, plane insertion, etc.).
Returns
Shared pointer to the configured insertion object
Definition at line 211 of file cfd_dem_coupling.cc.
set_integrator_type()
template<int dim> std::shared_ptr< Integrator< dim, DEM::CFDDEMProperties::PropertiesIndex > > CFDDEMSolver< dim >::set_integrator_type () private
Set up the time integration method for particle motion.
Creates and configures the appropriate integration scheme for solving particle equations of motion (e.g., velocity Verlet, explicit Euler).
Returns
Shared pointer to the configured integration object
Definition at line 263 of file cfd_dem_coupling.cc.
setup_distribution_type()
template<int dim> void CFDDEMSolver< dim >::setup_distribution_type () private
Initialize the particle size distribution and related parameters.
Sets up the particle size distribution type for the simulation and calculates the maximum particle diameter and neighborhood threshold squared values required for contact detection algorithms.
Definition at line 153 of file cfd_dem_coupling.cc.
References Parameters::Lagrangian::LagrangianPhysicalProperties::diameter_max_cutoff, Parameters::Lagrangian::LagrangianPhysicalProperties::diameter_min_cutoff, Parameters::Lagrangian::LagrangianPhysicalProperties::distribution_type, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_average_diameter, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_custom_diameter, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_custom_probability, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_size_std, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number, and Parameters::Lagrangian::LagrangianPhysicalProperties::seed_for_distributions.
solve()
template<int dim> void CFDDEMSolver< dim >::solve () override virtual
Engine of the CFD-DEM solver. Calls all the necessary functions to set parameters, solve the simulation, and finish the simulation.
Reimplemented from FluidDynamicsVANS< dim >.
Definition at line 1595 of file cfd_dem_coupling.cc.
References announce_string(), Parameters::fully_explicit, Parameters::Testing::mobility_status, FluidDynamicsVANS< dim >::monitor_mass_conservation(), Parameters::Testing::particles, read_mesh_and_manifolds(), NavierStokesBase< dim, VectorType, DofsType >::refine_mesh(), and write_collision_stats().
sort_particles_into_subdomains_and_cells()
template<int dim> void CFDDEMSolver< dim >::sort_particles_into_subdomains_and_cells () inline private
Sort particles into subdomains and cells for efficient processing.
Redistributes particles among computational subdomains and associates them with their containing cells, then reinitialize containers that depend on local particle identifiers.
Definition at line 1401 of file cfd_dem_coupling.cc.
References DEM::CFDDEMProperties::dp, and DEM::CFDDEMProperties::mass.
update_dem_time_step()
template<int dim> void CFDDEMSolver< dim >::update_dem_time_step () inline private
Calculate the new DEM time-step.
Calculate the new DEM time-step in a CFD-DEM simulation with adaptive time-stepping
Definition at line 351 of file cfd_dem_coupling.h.
References CFDDEMSolver< dim >::coupling_frequency, CFDDEMSolver< dim >::dem_time_step, PhysicsSolver< VectorType >::pcout, CFDDEMSolver< dim >::rayleigh_time_step, and NavierStokesBase< dim, GlobalVectorType, IndexSet >::simulation_control.
write_checkpoint()
template<int dim> void CFDDEMSolver< dim >::write_checkpoint () override private virtual
Write CFD-DEM simulation checkpoint files.
Saves the complete state of the CFD-DEM simulation including fluid variables, particle data, and auxiliary information to enable simulation restart from the current time step.
Reimplemented from NavierStokesBase< dim, GlobalVectorType, IndexSet >.
Definition at line 466 of file cfd_dem_coupling.cc.
References NavierStokesBase< dim, VectorType, DofsType >::gather_tables(), and serialize_tables_vector().
write_dem_output_results()
template<int dim> void CFDDEMSolver< dim >::write_dem_output_results () private
Write DEM simulation results to output files.
Generates visualization output files containing particle positions, velocities, forces, and other relevant DEM variables in parallel VTU format for post-processing.
Definition at line 1064 of file cfd_dem_coupling.cc.
References Visualization< dim, PropertiesIndex >::build_patches().
Member Data Documentation
boundary_cell_object
template<int dim> BoundaryCellsInformation<dim> CFDDEMSolver< dim >::boundary_cell_object private
Information about boundary cells for contact detection.
Definition at line 461 of file cfd_dem_coupling.h.
collision_event_log
template<int dim> CompletedCollisionLog<dim> CFDDEMSolver< dim >::collision_event_log private
Object to store completed collision events.
Stores complete collision event data including start and end information for post-processing and analysis purposes.
Definition at line 422 of file cfd_dem_coupling.h.
contact_list
template<int dim> statistics CFDDEMSolver< dim >::contact_list private
Statistics container for timing and contact list information.
Definition at line 497 of file cfd_dem_coupling.h.
contact_manager
template<int dim> DEMContactManager<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMSolver< dim >::contact_manager private
Manager for particle-particle and particle-wall contact detection and handling
Definition at line 427 of file cfd_dem_coupling.h.
contact_outcome
template<int dim> ParticleInteractionOutcomes<DEM::CFDDEMProperties::PropertiesIndex> CFDDEMSolver< dim >::contact_outcome private
Container for particle interaction outcomes (forces and torques)
Definition at line 382 of file cfd_dem_coupling.h.
contact_search_counter
template<int dim> unsigned int CFDDEMSolver< dim >::contact_search_counter private
Counter for contact searches performed in the current CFD iteration.
Definition at line 491 of file cfd_dem_coupling.h.
contact_search_total_number
template<int dim> unsigned int CFDDEMSolver< dim >::contact_search_total_number private
Total number of contact searches since simulation start.
Definition at line 494 of file cfd_dem_coupling.h.
coupling_frequency
template<int dim> unsigned int CFDDEMSolver< dim >::coupling_frequency private
Frequency of coupling between CFD and DEM solvers (in DEM time steps)
Definition at line 375 of file cfd_dem_coupling.h.
dem_action_manager
template<int dim> DEMActionManager* CFDDEMSolver< dim >::dem_action_manager private
Pointer to DEM action manager for handling DEM-specific operations.
Definition at line 529 of file cfd_dem_coupling.h.
dem_parameters
template<int dim> DEMSolverParameters<dim> CFDDEMSolver< dim >::dem_parameters private
DEM simulation parameters container.
Definition at line 510 of file cfd_dem_coupling.h.
dem_time_step
template<int dim> double CFDDEMSolver< dim >::dem_time_step private
Time step size for DEM integration.
Definition at line 513 of file cfd_dem_coupling.h.
displacement
template<int dim> std::vector<double> CFDDEMSolver< dim >::displacement private
Displacement vector for particle motion calculations.
Definition at line 391 of file cfd_dem_coupling.h.
force
template<int dim> std::vector<Tensor<1, 3> >& CFDDEMSolver< dim >::force = contact_outcome.force private
Reference to force vector from contact outcomes.
Definition at line 388 of file cfd_dem_coupling.h.
forces_boundary_information
template<int dim> dem_data_structures<dim>::vector_on_boundary CFDDEMSolver< dim >::forces_boundary_information private
Force information stored on boundary elements.
Definition at line 473 of file cfd_dem_coupling.h.
g
template<int dim> Tensor<1, 3> CFDDEMSolver< dim >::g private
Gravitational acceleration vector.
Definition at line 378 of file cfd_dem_coupling.h.
grid_pvdhandler
template<int dim> PVDHandler CFDDEMSolver< dim >::grid_pvdhandler private
PVD handler for grid visualization output.
Definition at line 504 of file cfd_dem_coupling.h.
insertion_object
template<int dim> std::shared_ptr<Insertion<dim, DEM::CFDDEMProperties::PropertiesIndex> > CFDDEMSolver< dim >::insertion_object private
Particle insertion method handler.
Definition at line 443 of file cfd_dem_coupling.h.
integrator_object
template<int dim> std::shared_ptr<Integrator<dim, DEM::CFDDEMProperties::PropertiesIndex> > CFDDEMSolver< dim >::integrator_object private
Time integration scheme for particle motion equations.
Definition at line 439 of file cfd_dem_coupling.h.
load_balancing
template<int dim> LagrangianLoadBalancing<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMSolver< dim >::load_balancing private
Load balancing handler for distributing particles across MPI processes.
Definition at line 431 of file cfd_dem_coupling.h.
maximum_particle_diameter
template<int dim> double CFDDEMSolver< dim >::maximum_particle_diameter private
Maximum diameter among all particles in the simulation.
Definition at line 403 of file cfd_dem_coupling.h.
MOI
template<int dim> std::vector<double> CFDDEMSolver< dim >::MOI private
Moment of inertia values for all particles.
Definition at line 394 of file cfd_dem_coupling.h.
n_mpi_processes
template<int dim> const unsigned int CFDDEMSolver< dim >::n_mpi_processes private
Total number of MPI processes.
Definition at line 522 of file cfd_dem_coupling.h.
neighborhood_threshold_squared
template<int dim> double CFDDEMSolver< dim >::neighborhood_threshold_squared private
Squared threshold distance for neighborhood particle detection.
Definition at line 397 of file cfd_dem_coupling.h.
ongoing_collision_log
template<int dim> OngoingCollisionLog<dim> CFDDEMSolver< dim >::ongoing_collision_log private
Object to store ongoing collision information.
Stores particle ID, boundary ID, velocity tensor, angular velocity tensor, and collision time for collisions currently in progress.
Definition at line 414 of file cfd_dem_coupling.h.
particle_particle_contact_force_object
template<int dim> std::shared_ptr< ParticleParticleContactForceBase<dim, DEM::CFDDEMProperties::PropertiesIndex> > CFDDEMSolver< dim >::particle_particle_contact_force_object private
Contact force model for particle-particle interactions.
Definition at line 449 of file cfd_dem_coupling.h.
particle_point_line_contact_force_object
template<int dim> ParticlePointLineForce<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMSolver< dim >::particle_point_line_contact_force_object private
Handler for point and line contact forces between particles.
Definition at line 435 of file cfd_dem_coupling.h.
particle_wall_contact_force_object
template<int dim> std::shared_ptr< ParticleWallContactForceBase<dim, DEM::CFDDEMProperties::PropertiesIndex> > CFDDEMSolver< dim >::particle_wall_contact_force_object private
Contact force model for particle-wall interactions.
Definition at line 454 of file cfd_dem_coupling.h.
particles_pvdhandler
template<int dim> PVDHandler CFDDEMSolver< dim >::particles_pvdhandler private
PVD handler for particle visualization output.
Definition at line 507 of file cfd_dem_coupling.h.
periodic_boundaries_cells_information
template<int dim> DEM::dem_data_structures<dim>::periodic_boundaries_cells_info CFDDEMSolver< dim >::periodic_boundaries_cells_information private
Information about cells involved in periodic boundary conditions.
Definition at line 481 of file cfd_dem_coupling.h.
periodic_boundaries_object
template<int dim> PeriodicBoundariesManipulator<dim> CFDDEMSolver< dim >::periodic_boundaries_object private
Handler for periodic boundary condition manipulations.
Definition at line 484 of file cfd_dem_coupling.h.
properties_class
template<int dim> DEM::ParticleProperties<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMSolver< dim >::properties_class private
Particle properties handler for DEM simulation.
Definition at line 501 of file cfd_dem_coupling.h.
rayleigh_time_step
template<int dim> double CFDDEMSolver< dim >::rayleigh_time_step private
Rayleigh time step.
Definition at line 516 of file cfd_dem_coupling.h.
size_distribution_object_container
template<int dim> std::vector<std::shared_ptr<Distribution> > CFDDEMSolver< dim >::size_distribution_object_container private
Container for particle size distribution objects.
Definition at line 400 of file cfd_dem_coupling.h.
smallest_contact_search_criterion
template<int dim> double CFDDEMSolver< dim >::smallest_contact_search_criterion private
Smallest criterion used for contact search algorithms.
Definition at line 406 of file cfd_dem_coupling.h.
solid_surfaces_mesh_info
template<int dim> dem_data_structures<dim>::solid_surfaces_mesh_information CFDDEMSolver< dim >::solid_surfaces_mesh_info private
Mesh information for solid surfaces in contact with particles.
Definition at line 465 of file cfd_dem_coupling.h.
sparse_contacts_object
template<int dim> AdaptiveSparseContacts<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMSolver< dim >::sparse_contacts_object private
Object for handling adaptive sparse contact detection algorithms.
Definition at line 488 of file cfd_dem_coupling.h.
table_phase_volumes
template<int dim> TableHandler CFDDEMSolver< dim >::table_phase_volumes private
TableHandler for post-processing phase volume calculations Stores total fluid volume and total particle volume data
Definition at line 526 of file cfd_dem_coupling.h.
this_mpi_process
template<int dim> const unsigned int CFDDEMSolver< dim >::this_mpi_process private
Current MPI process identifier.
Definition at line 519 of file cfd_dem_coupling.h.
torque
template<int dim> std::vector<Tensor<1, 3> >& CFDDEMSolver< dim >::torque = contact_outcome.torque private
Reference to torque vector from contact outcomes.
Definition at line 385 of file cfd_dem_coupling.h.
torques_boundary_information
template<int dim> dem_data_structures<dim>::vector_on_boundary CFDDEMSolver< dim >::torques_boundary_information private
Torque information stored on boundary elements.
Definition at line 477 of file cfd_dem_coupling.h.
updated_boundary_points_and_normal_vectors
template<int dim> dem_data_structures<dim>::boundary_points_and_normal_vectors CFDDEMSolver< dim >::updated_boundary_points_and_normal_vectors private
Updated boundary points and their corresponding normal vectors.
Definition at line 469 of file cfd_dem_coupling.h.
visualization_object
template<int dim> Visualization<dim, DEM::CFDDEMProperties::PropertiesIndex> CFDDEMSolver< dim >::visualization_object private
Visualization handler for DEM output generation.
Definition at line 458 of file cfd_dem_coupling.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/cfd_dem_coupling.h
/home/runner/work/lethe/lethe/source/fem-dem/cfd_dem_coupling.cc