Lethe Open-Source Library: VANSAssemblerShearForce< dim > Class Template Reference
VANSAssemblerShearForce< dim > Class Template Reference
#include <vans_assemblers.h>
Public Member Functions
VANSAssemblerShearForce (Parameters::CFDDEM cfd_dem)
virtual void calculate_particle_fluid_interactions (NavierStokesScratchData< dim > &scratch_data) override
Public Attributes
Parameters::CFDDEM cfd_dem
Detailed Description
template<int dim>
class VANSAssemblerShearForce< dim >
Class that assembles the particle shear force that will then be added to particle_fluid_interactions.
Template Parameters
dim An integer that denotes the number of spatial dimensions
Definition at line 634 of file vans_assemblers.h.
Constructor & Destructor Documentation
VANSAssemblerShearForce()
template<int dim> VANSAssemblerShearForce< dim >::VANSAssemblerShearForce (Parameters::CFDDEM cfd_dem) inline
Definition at line 637 of file vans_assemblers.h.
Member Function Documentation
calculate_particle_fluid_interactions()
template<int dim> void VANSAssemblerShearForce< dim >::calculate_particle_fluid_interactions (NavierStokesScratchData< dim > & scratch_data) override virtual
calculate_particle_fluid_interactions calculates the shear force
Parameters
scratch_data (see base class)
copy_data (see base class)
Implements ParticleFluidAssemblerBase< dim >.
Definition at line 1862 of file vans_assemblers.cc.
References NavierStokesScratchData< dim >::cell_volume, PhysicalPropertiesManager::density_is_constant(), DEM::dp, DEM::fem_force_x, NavierStokesScratchData< dim >::fluid_velocity_laplacian_at_particle_location, PhysicalPropertiesManager::get_density_scale(), PhysicalPropertiesManager::get_kinematic_viscosity_scale(), PhysicalPropertiesManager::is_non_newtonian(), Parameters::modelB, NavierStokesScratchData< dim >::pic, NavierStokesScratchData< dim >::properties_manager, and NavierStokesScratchData< dim >::undisturbed_flow_force.
Member Data Documentation
cfd_dem
template<int dim> Parameters::CFDDEM VANSAssemblerShearForce< dim >::cfd_dem
Definition at line 650 of file vans_assemblers.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/vans_assemblers.h
/home/runner/work/lethe/lethe/source/fem-dem/vans_assemblers.cc