Lethe Open-Source Library: VOFLinearSubequationsSolver< dim, ScratchDataType > Class Template Reference
VOFLinearSubequationsSolver< dim, ScratchDataType > Class Template Reference abstract
#include <vof_linear_subequations_solver.h>
Public Member Functions
VOFLinearSubequationsSolver (const VOFSubequationsID &p_subequation_id, VOFSubequationsInterface< dim > *p_subequations, MultiphysicsInterface< dim > *p_multiphysics, const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim >> &p_triangulation, std::shared_ptr< SimulationControl > &p_simulation_control, const Parameters::Verbosity &p_subequation_verbosity, const ConditionalOStream &p_pcout)
~VOFLinearSubequationsSolver ()=default
void setup_dofs () override
void solve_linear_system_and_update_solution (const bool &is_post_mesh_adaptation=false) override
void solve (const bool &is_post_mesh_adaptation=false) override
Public Member Functions inherited from PhysicsLinearSubequationsSolver
PhysicsLinearSubequationsSolver (const ConditionalOStream &pcout)
~PhysicsLinearSubequationsSolver ()=default
Protected Member Functions
void assemble_system_matrix () override
void assemble_system_rhs () override
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, ScratchDataType &scratch_data, StabilizedMethodsCopyData &copy_data)=0
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, ScratchDataType &scratch_data, StabilizedMethodsCopyData &copy_data)=0
void copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData &copy_data)
void copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData &copy_data)
Protected Attributes
const VOFSubequationsID subequation_id
VOFSubequationsInterface< dim > * subequations
MultiphysicsInterface< dim > * multiphysics
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< SimulationControl > simulation_control
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
GlobalVectorType evaluation_point
GlobalVectorType present_solution
GlobalVectorType system_rhs
AffineConstraints< double > constraints
TrilinosWrappers::SparseMatrix system_matrix
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
std::shared_ptr< VOFSubequationAssemblerBase< ScratchDataType > > assembler
const Parameters::Verbosity linear_solver_verbosity
const Parameters::Verbosity subequation_verbosity
Protected Attributes inherited from PhysicsLinearSubequationsSolver
ConditionalOStream pcout
Detailed Description
template<int dim, typename ScratchDataType>
class VOFLinearSubequationsSolver< dim, ScratchDataType >
Generalized solver for VOF linear subequations.
Template Parameters
dim Number of dimensions of the problem.
ScratchDataType Type of scratch data object used for linear system assembly.
Definition at line 37 of file vof_linear_subequations_solver.h.
Constructor & Destructor Documentation
VOFLinearSubequationsSolver()
template<int dim, typename ScratchDataType > VOFLinearSubequationsSolver< dim, ScratchDataType >::VOFLinearSubequationsSolver (const VOFSubequationsID & p_subequation_id, VOFSubequationsInterface< dim > * p_subequations, MultiphysicsInterface< dim > * p_multiphysics, const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim >> & p_triangulation, std::shared_ptr< SimulationControl > & p_simulation_control, const Parameters::Verbosity & p_subequation_verbosity, const ConditionalOStream & p_pcout) inline
Constructor for linear subequations solvers within the VOF auxiliary physics.
Parameters
[in] p_subequation_id Identifier corresponding to the subequation.
[in,out] p_subequations Subequations interface object used to get information from other subequations and store information from the current one.
[in] p_multiphysics Multiphysics interface object used to get information from physics.
[in] p_simulation_parameters Simulation parameters.
[in] p_triangulation Distributed mesh information.
[in] p_simulation_control Object responsible for the control of steady-state and transient simulations. Contains all the information related to time stepping and the stopping criteria.
[in] p_subequation_verbosity Parameter indicating the verbosity level of the solver.
[in] p_pcout Parallel cout used to print the information.
Definition at line 66 of file vof_linear_subequations_solver.h.
References VOFLinearSubequationsSolver< dim, ScratchDataType >::cell_quadrature, VOFLinearSubequationsSolver< dim, ScratchDataType >::fe, VOFLinearSubequationsSolver< dim, ScratchDataType >::mapping, and VOFLinearSubequationsSolver< dim, ScratchDataType >::simulation_parameters.
~VOFLinearSubequationsSolver()
template<int dim, typename ScratchDataType > VOFLinearSubequationsSolver< dim, ScratchDataType >::~VOFLinearSubequationsSolver () default
Default destructor.
Member Function Documentation
assemble_local_system_matrix()
template<int dim, typename ScratchDataType > virtual void VOFLinearSubequationsSolver< dim, ScratchDataType >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, ScratchDataType & scratch_data, StabilizedMethodsCopyData & copy_data) protected pure virtual
Assemble the local matrix for a given cell.
Parameters
[in] cell Cell for which the local matrix is assembled.
[in] scratch_data Stores the calculated finite element information at Gauss points.
[in,out] copy_data Stores the results of the assembly over a cell.
Implemented in VOFPhaseGradientProjection< dim, ScratchDataType >.
assemble_local_system_rhs()
template<int dim, typename ScratchDataType > virtual void VOFLinearSubequationsSolver< dim, ScratchDataType >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, ScratchDataType & scratch_data, StabilizedMethodsCopyData & copy_data) protected pure virtual
Assemble the local right-hand side (rhs) for a given cell.
Parameters
[in] cell Cell for which the local rhs is assembled.
[in] scratch_data Stores the calculated finite element information at Gauss points.
[in,out] copy_data Stores the results of the assembly over a cell.
Implemented in VOFPhaseGradientProjection< dim, ScratchDataType >.
assemble_system_matrix()
template<int dim, typename ScratchDataType > void VOFLinearSubequationsSolver< dim, ScratchDataType >::assemble_system_matrix override protected virtual
Assemble the matrix associated with the solver.
Implements PhysicsSubequationsSolverBase.
Definition at line 74 of file vof_linear_subequations_solver.cc.
References VOFLinearSubequationsSolver< dim, ScratchDataType >::assemble_local_system_matrix(), and VOFLinearSubequationsSolver< dim, ScratchDataType >::copy_local_matrix_to_global_matrix().
assemble_system_rhs()
template<int dim, typename ScratchDataType > void VOFLinearSubequationsSolver< dim, ScratchDataType >::assemble_system_rhs override protected virtual
Assemble the rhs associated with the solver.
Implements PhysicsSubequationsSolverBase.
Definition at line 123 of file vof_linear_subequations_solver.cc.
References VOFLinearSubequationsSolver< dim, ScratchDataType >::assemble_local_system_rhs(), and VOFLinearSubequationsSolver< dim, ScratchDataType >::copy_local_rhs_to_global_rhs().
copy_local_matrix_to_global_matrix()
template<int dim, typename ScratchDataType > void VOFLinearSubequationsSolver< dim, ScratchDataType >::copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData & copy_data) protected
Copy local cell matrix information to global matrix.
Parameters
[in] copy_data Stores the results of the assembly over a cell.
Definition at line 109 of file vof_linear_subequations_solver.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim, typename ScratchDataType > void VOFLinearSubequationsSolver< dim, ScratchDataType >::copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData & copy_data) protected
Copy local right-hand side (rhs) information to global rhs.
Parameters
[in] copy_data Stores the results of the assembly over a cell.
Definition at line 154 of file vof_linear_subequations_solver.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_rhs.
setup_dofs()
template<int dim, typename ScratchDataType > void VOFLinearSubequationsSolver< dim, ScratchDataType >::setup_dofs override virtual
Set up the DofHandler and the degree of freedom associated with the physics.
Implements PhysicsSubequationsSolverBase.
Definition at line 12 of file vof_linear_subequations_solver.cc.
References Parameters::quiet.
solve()
template<int dim, typename ScratchDataType > void VOFLinearSubequationsSolver< dim, ScratchDataType >::solve (const bool & is_post_mesh_adaptation = false) override virtual
Assemble and solve linear system when the equation to solve is linear without using the non-linear solver interface.
Parameters
[in] is_post_mesh_adaptation Indicates if the equation is being solved during post_mesh_adaptation(), for verbosity.
Implements PhysicsSubequationsSolverBase.
Definition at line 255 of file vof_linear_subequations_solver.cc.
solve_linear_system_and_update_solution()
template<int dim, typename ScratchDataType > void VOFLinearSubequationsSolver< dim, ScratchDataType >::solve_linear_system_and_update_solution (const bool & is_post_mesh_adaptation = false) override virtual
Solve linear system of equation using a strategy appropriate for the partial differential equation.
Parameters
[in] is_post_mesh_adaptation Indicates if the equation is being solved during post_mesh_adaptation(), for verbosity.
Implements PhysicsLinearSubequationsSolver.
Definition at line 168 of file vof_linear_subequations_solver.cc.
References Parameters::quiet, and VOF.
Member Data Documentation
assembler
template<int dim, typename ScratchDataType > std::shared_ptr<VOFSubequationAssemblerBase<ScratchDataType> > VOFLinearSubequationsSolver< dim, ScratchDataType >::assembler protected
Definition at line 237 of file vof_linear_subequations_solver.h.
cell_quadrature
template<int dim, typename ScratchDataType > std::shared_ptr<Quadrature<dim> > VOFLinearSubequationsSolver< dim, ScratchDataType >::cell_quadrature protected
Definition at line 224 of file vof_linear_subequations_solver.h.
constraints
template<int dim, typename ScratchDataType > AffineConstraints<double> VOFLinearSubequationsSolver< dim, ScratchDataType >::constraints protected
Definition at line 232 of file vof_linear_subequations_solver.h.
dof_handler
template<int dim, typename ScratchDataType > DoFHandler<dim> VOFLinearSubequationsSolver< dim, ScratchDataType >::dof_handler protected
Definition at line 219 of file vof_linear_subequations_solver.h.
evaluation_point
template<int dim, typename ScratchDataType > GlobalVectorType VOFLinearSubequationsSolver< dim, ScratchDataType >::evaluation_point protected
Definition at line 229 of file vof_linear_subequations_solver.h.
fe
template<int dim, typename ScratchDataType > std::shared_ptr<FESystem<dim> > VOFLinearSubequationsSolver< dim, ScratchDataType >::fe protected
Definition at line 220 of file vof_linear_subequations_solver.h.
ilu_preconditioner
template<int dim, typename ScratchDataType > std::shared_ptr<TrilinosWrappers::PreconditionILU> VOFLinearSubequationsSolver< dim, ScratchDataType >::ilu_preconditioner protected
Definition at line 234 of file vof_linear_subequations_solver.h.
linear_solver_verbosity
template<int dim, typename ScratchDataType > const Parameters::Verbosity VOFLinearSubequationsSolver< dim, ScratchDataType >::linear_solver_verbosity protected
Definition at line 240 of file vof_linear_subequations_solver.h.
locally_owned_dofs
template<int dim, typename ScratchDataType > IndexSet VOFLinearSubequationsSolver< dim, ScratchDataType >::locally_owned_dofs protected
Definition at line 227 of file vof_linear_subequations_solver.h.
locally_relevant_dofs
template<int dim, typename ScratchDataType > IndexSet VOFLinearSubequationsSolver< dim, ScratchDataType >::locally_relevant_dofs protected
Definition at line 228 of file vof_linear_subequations_solver.h.
mapping
template<int dim, typename ScratchDataType > std::shared_ptr<Mapping<dim> > VOFLinearSubequationsSolver< dim, ScratchDataType >::mapping protected
Definition at line 223 of file vof_linear_subequations_solver.h.
multiphysics
template<int dim, typename ScratchDataType > MultiphysicsInterface<dim>* VOFLinearSubequationsSolver< dim, ScratchDataType >::multiphysics protected
Definition at line 211 of file vof_linear_subequations_solver.h.
present_solution
template<int dim, typename ScratchDataType > GlobalVectorType VOFLinearSubequationsSolver< dim, ScratchDataType >::present_solution protected
Definition at line 230 of file vof_linear_subequations_solver.h.
simulation_control
template<int dim, typename ScratchDataType > std::shared_ptr<SimulationControl> VOFLinearSubequationsSolver< dim, ScratchDataType >::simulation_control protected
Definition at line 218 of file vof_linear_subequations_solver.h.
simulation_parameters
template<int dim, typename ScratchDataType > const SimulationParameters<dim>& VOFLinearSubequationsSolver< dim, ScratchDataType >::simulation_parameters protected
Definition at line 214 of file vof_linear_subequations_solver.h.
subequation_id
template<int dim, typename ScratchDataType > const VOFSubequationsID VOFLinearSubequationsSolver< dim, ScratchDataType >::subequation_id protected
Definition at line 208 of file vof_linear_subequations_solver.h.
subequation_verbosity
template<int dim, typename ScratchDataType > const Parameters::Verbosity VOFLinearSubequationsSolver< dim, ScratchDataType >::subequation_verbosity protected
Definition at line 241 of file vof_linear_subequations_solver.h.
subequations
template<int dim, typename ScratchDataType > VOFSubequationsInterface<dim>* VOFLinearSubequationsSolver< dim, ScratchDataType >::subequations protected
Definition at line 209 of file vof_linear_subequations_solver.h.
system_matrix
template<int dim, typename ScratchDataType > TrilinosWrappers::SparseMatrix VOFLinearSubequationsSolver< dim, ScratchDataType >::system_matrix protected
Definition at line 233 of file vof_linear_subequations_solver.h.
system_rhs
template<int dim, typename ScratchDataType > GlobalVectorType VOFLinearSubequationsSolver< dim, ScratchDataType >::system_rhs protected
Definition at line 231 of file vof_linear_subequations_solver.h.
triangulation
template<int dim, typename ScratchDataType > std::shared_ptr<parallel::DistributedTriangulationBase<dim> > VOFLinearSubequationsSolver< dim, ScratchDataType >::triangulation protected
Definition at line 217 of file vof_linear_subequations_solver.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/vof_linear_subequations_solver.h
/home/runner/work/lethe/lethe/source/solvers/vof_linear_subequations_solver.cc