Lethe Open-Source Library: ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model > Class Template Reference
ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model > Class Template Reference
#include <particle_particle_contact_force.h>
Public Member Functions
ParticleParticleContactForce (const DEMSolverParameters< dim > &dem_parameters)
virtual ~ParticleParticleContactForce ()
virtual void calculate_particle_particle_contact (typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &local_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &ghost_adjacent_particles, typename DEM::dem_data_structures< dim >::periodic_adjacent_particle_pairs &local_local_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::periodic_adjacent_particle_pairs &local_ghost_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::periodic_adjacent_particle_pairs &ghost_local_periodic_adjacent_particles, const double dt, ParticleInteractionOutcomes< PropertiesIndex > &contact_outcome) override
Public Member Functions inherited from ParticleParticleContactForceBase< dim, PropertiesIndex >
void set_periodic_offset (const Tensor< 1, dim > &offset, const types::boundary_id boundary_id)
void set_combined_periodic_offsets (const std::vector< Tensor< 1, dim > > &offsets)
Protected Member Functions
void update_contact_information (particle_particle_contact_info< dim > &contact_info, Tensor< 1, 3 > &tangential_relative_velocity, double &normal_relative_velocity_value, Tensor< 1, 3 > &normal_unit_vector, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, const Point< 3 > &particle_one_location, const Point< 3 > &particle_two_location, const double dt)
Point< 3 > get_location (const Particles::ParticleIterator< dim > &particle) &
Point< 3 > get_periodic_location (const Particles::ParticleIterator< dim > &particle, const Tensor< 1, 3 > &periodic_offset) &
void calculate_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
double get_force_calculation_threshold_distance ()
Private Member Functions
void apply_force_and_torque_on_local_particles (const Tensor< 1, 3 > &normal_force, const Tensor< 1, 3 > &tangential_force, const Tensor< 1, 3 > &particle_one_tangential_torque, const Tensor< 1, 3 > &particle_two_tangential_torque, const Tensor< 1, 3 > &rolling_resistance_torque, Tensor< 1, 3 > &particle_one_torque, Tensor< 1, 3 > &particle_two_torque, Tensor< 1, 3 > &particle_one_force, Tensor< 1, 3 > &particle_two_force)
void apply_force_and_torque_on_single_local_particle (const Tensor< 1, 3 > &normal_force, const Tensor< 1, 3 > &tangential_force, const Tensor< 1, 3 > &particle_one_tangential_torque, const Tensor< 1, 3 > &rolling_resistance_torque, Tensor< 1, 3 > &particle_one_torque, Tensor< 1, 3 > &particle_one_force)
std::tuple< double, double > find_effective_radius_and_mass (const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties)
Tensor< 1, 3 > calculate_rolling_resistance_torque (const double effective_radius, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, const double rolling_friction_coeff, const double rolling_viscous_damping_coeff, const double dt, const double normal_spring_constant, const double normal_force_norm, const Tensor< 1, 3 > &normal_unit_vector, Tensor< 1, 3 > &cumulative_rolling_resistance_spring_torque)
void calculate_linear_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_hertz_mindlin_limit_overlap_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_hertz_mindlin_limit_force_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_hertz_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_hertz_JKR_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_DMT_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
unsigned int vec_particle_type_index (const unsigned int i, const unsigned int j)
void set_effective_properties (const DEMSolverParameters< dim > &dem_parameters)
void set_multiphysic_properties (const DEMSolverParameters< dim > &dem_parameters)
template<ContactType contact_type, typename ContactInfoContainer >
void execute_contact_calculation (ContactInfoContainer &adjacent_particles_list, const double dt, ParticleInteractionOutcomes< PropertiesIndex > &contact_outcome)
Private Attributes
unsigned int n_particle_types
std::vector< double > effective_youngs_modulus
std::vector< double > effective_real_youngs_modulus
std::vector< double > effective_shear_modulus
std::vector< double > effective_coefficient_of_restitution
std::vector< double > effective_coefficient_of_friction
std::vector< double > effective_rolling_viscous_damping_coefficient
std::vector< double > effective_coefficient_of_rolling_friction
std::vector< double > effective_surface_energy
std::vector< double > effective_hamaker_constant
std::vector< double > model_parameter_beta
const double dmt_cut_off_threshold
const double f_coefficient_epsd
std::vector< double > equivalent_surface_roughness
std::vector< double > equivalent_surface_slope
std::vector< double > effective_microhardness
std::vector< double > thermal_conductivity_particle
std::vector< double > gas_parameter_m
double thermal_conductivity_gas
Additional Inherited Members
Protected Attributes inherited from ParticleParticleContactForceBase< dim, PropertiesIndex >
std::unordered_map< types::boundary_id, Tensor< 1, dim > > periodic_offsets
std::vector< Tensor< 1, dim > > combined_periodic_offsets
Detailed Description
template<int dim, typename PropertiesIndex, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model>
class ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >
Execute calculation of particle-particle contact forces including linear, non-linear contact models, and non-linear with cohesive forces.
Instead of using an inheritance hierarchy to distinguish between the contact model, the class is templated with the type of force model and rolling friction model. Consequently, the code for each combination of force model is generated at compile time.
Template Parameters
dim The dimension of the problem.
contact_model The particle-particle contact force model.
rolling_friction_model The rolling resistance model.
Definition at line 137 of file particle_particle_contact_force.h.
Constructor & Destructor Documentation
ParticleParticleContactForce()
template<int dim, typename PropertiesIndex , ParticleParticleContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::ParticleParticleContactForce (const DEMSolverParameters< dim > & dem_parameters)
Definition at line 18 of file particle_particle_contact_force.cc.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::set_effective_properties(), and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::set_multiphysic_properties().
~ParticleParticleContactForce()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> virtual ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::~ParticleParticleContactForce () inline virtual
Definition at line 143 of file particle_particle_contact_force.h.
Member Function Documentation
apply_force_and_torque_on_local_particles()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::apply_force_and_torque_on_local_particles (const Tensor< 1, 3 > & normal_force, const Tensor< 1, 3 > & tangential_force, const Tensor< 1, 3 > & particle_one_tangential_torque, const Tensor< 1, 3 > & particle_two_tangential_torque, const Tensor< 1, 3 > & rolling_resistance_torque, Tensor< 1, 3 > & particle_one_torque, Tensor< 1, 3 > & particle_two_torque, Tensor< 1, 3 > & particle_one_force, Tensor< 1, 3 > & particle_two_force) inline private
Apply the calculated force and torque on the local-local particle pair in contact.
Parameters
[in] normal_force Contact normal force.
[in] tangential_force Contact tangential force.
[in] particle_one_tangential_torque Contact tangential torque on particle one.
[in] particle_two_tangential_torque Contact tangential torque on particle two.
[in] rolling_resistance_torque Contact rolling resistance torque.
[in,out] particle_one_torque
[in,out] particle_two_torque
[in,out] particle_one_force Force acting on particle one
[in,out] particle_two_force Force acting on particle two
Definition at line 511 of file particle_particle_contact_force.h.
apply_force_and_torque_on_single_local_particle()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::apply_force_and_torque_on_single_local_particle (const Tensor< 1, 3 > & normal_force, const Tensor< 1, 3 > & tangential_force, const Tensor< 1, 3 > & particle_one_tangential_torque, const Tensor< 1, 3 > & rolling_resistance_torque, Tensor< 1, 3 > & particle_one_torque, Tensor< 1, 3 > & particle_one_force) inline private
Apply the calculated force and torque on the local-ghost particle pair in contact. The contact force is only applied on the local particles.
Parameters
[in] normal_force Contact normal force.
[in] tangential_force Contact tangential force.
[in] particle_one_tangential_torque Contact tangential torque.
[in] rolling_resistance_torque Contact rolling resistance torque.
[in,out] particle_one_torque Torque acting on particle one (local).
[in,out] particle_one_force Force acting on particle one (local).
Definition at line 546 of file particle_particle_contact_force.h.
calculate_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline protected
Calculate the particle-particle contact force and torque according to the contact model.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 336 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_DMT_contact(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_contact(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_JKR_contact(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_force_contact(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_overlap_contact(), and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_linear_contact().
calculate_DMT_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_DMT_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle contact and cohesive forces and contact torque based on the updated values in contact_info. It uses the DMT cohesive force model.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 1427 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_overlap_contact(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_hamaker_constant, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), particle_particle_contact_info< dim >::rolling_resistance_spring_torque, particle_particle_contact_info< dim >::tangential_displacement, and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_hertz_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & , const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle non-linear contact force and torque based on the updated values in contact_info. It uses the Hertz contact model, same as the Hertz-Mindlin with limit of the tangential force without the tangential damping force.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 1138 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_rolling_viscous_damping_coefficient, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::rolling_resistance_spring_torque, particle_particle_contact_info< dim >::tangential_displacement, and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_hertz_JKR_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_JKR_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle contact and cohesive forces and contact torque based on the updated values in contact_info. It uses the JKR cohesive force model.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 1266 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_rolling_viscous_damping_coefficient, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::rolling_resistance_spring_torque, particle_particle_contact_info< dim >::tangential_displacement, and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_hertz_mindlin_limit_force_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_force_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle non-linear contact force and torque based on the updated values in contact_info. It uses the Hertz-Mindlin contact model. If gross sliding occurs, the tangential displacement and tangential force are limited to Coulomb's criterion.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 998 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_rolling_viscous_damping_coefficient, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::rolling_resistance_spring_torque, particle_particle_contact_info< dim >::tangential_displacement, and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_hertz_mindlin_limit_overlap_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_overlap_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle non-linear contact force and torque based on the updated values in contact_info. It uses the Hertz-Mindlin contact model. If gross sliding occurs, the tangential displacement is recalculated from the limited tangential to the Coulomb's criterion.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 841 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_rolling_viscous_damping_coefficient, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::rolling_resistance_spring_torque, particle_particle_contact_info< dim >::tangential_displacement, and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_linear_contact()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_linear_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const double dt, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle linear contact force and torque based on the updated values in contact_info.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] dt DEM time step.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 686 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_rolling_viscous_damping_coefficient, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::rolling_resistance_spring_torque, particle_particle_contact_info< dim >::tangential_displacement, and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_particle_particle_contact()
template<int dim, typename PropertiesIndex , ParticleParticleContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_particle_particle_contact (typename DEM::dem_data_structures< dim >::adjacent_particle_pairs & local_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs & ghost_adjacent_particles, typename DEM::dem_data_structures< dim >::periodic_adjacent_particle_pairs & local_local_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::periodic_adjacent_particle_pairs & local_ghost_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::periodic_adjacent_particle_pairs & ghost_local_periodic_adjacent_particles, const double dt, ParticleInteractionOutcomes< PropertiesIndex > & contact_outcome) override virtual
Calculate the contact outcomes using the contact pair information obtained in the fine search and physical properties of particles.
Parameters
local_adjacent_particles Container of the contact pair candidates information for calculation of the local particle-particle contact forces.
ghost_adjacent_particles Container of the contact pair candidates information for calculation of the local-ghost particle-particle contact forces.
local_local_periodic_adjacent_particles Container of the contact pair candidates information for calculation of the local periodic particle-particle contact forces.
local_ghost_periodic_adjacent_particles Container of the contact pair candidates information for calculation of the local-ghost periodic particle-particle contact forces.
ghost_local_periodic_adjacent_particles Container of the contact pair candidates information for calculation of the ghost-local periodic particle-particle contact forces.
dt DEM time step.
[out] contact_outcome Interaction outcomes.
Implements ParticleParticleContactForceBase< dim, PropertiesIndex >.
Definition at line 39 of file particle_particle_contact_force.cc.
References ghost_local_periodic_particle_particle, ghost_periodic_particle_particle, and local_periodic_particle_particle.
calculate_rolling_resistance_torque()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Tensor< 1, 3 > ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque (const double effective_radius, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, const double rolling_friction_coeff, const double rolling_viscous_damping_coeff, const double dt, const double normal_spring_constant, const double normal_force_norm, const Tensor< 1, 3 > & normal_unit_vector, Tensor< 1, 3 > & cumulative_rolling_resistance_spring_torque) inline private
Calculate the rolling resistance torque acting on the particles according to the rolling resistance model.
Parameters
[in] effective_radius Effective radius of the particle pair.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[in] rolling_friction_coeff Effective rolling friction coefficient.
[in] rolling_viscous_damping_coeff Effective rolling viscous damping coefficient
[in] f_coeff Model parameter for the EPSD model.
[in] dt DEM time step.
[in] normal_spring_constant normal contact stiffness constant.
[in] normal_force_norm Norm of the normal force.
[in] normal_unit_vector Normal unit vector between particles in contact.
[in,out] cumulative_rolling_resistance_spring_torque Cumulative spring rolling resistance torque applied between particle one and two.
Definition at line 607 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::f_coefficient_epsd, and no_rolling_resistance_torque().
execute_contact_calculation()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> template<ContactType contact_type, typename ContactInfoContainer > void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::execute_contact_calculation (ContactInfoContainer & adjacent_particles_list, const double dt, ParticleInteractionOutcomes< PropertiesIndex > & contact_outcome) inline private
Execute the contact calculation step for the particle-particle contact according to the contact type.
Parameters
[in] adjacent_particles_list Container of the adjacent particles of a particle.
[in] dt DEM time step.
[out] contact_outcome Interaction outcomes.
Definition at line 1728 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::apply_force_and_torque_on_local_particles(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::apply_force_and_torque_on_single_local_particle(), apply_heat_transfer_on_local_particles(), apply_heat_transfer_on_single_local_particle(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::calculate_contact(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_microhardness, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_real_youngs_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::equivalent_surface_roughness, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::equivalent_surface_slope, ParticleInteractionOutcomes< PropertiesIndex >::force, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::gas_parameter_m, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::get_force_calculation_threshold_distance(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::get_location(), ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::get_periodic_location(), ghost_local_periodic_particle_particle, ghost_particle_particle, ghost_periodic_particle_particle, ParticleInteractionOutcomes< PropertiesIndex >::heat_transfer_rate, local_particle_particle, local_periodic_particle_particle, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::thermal_conductivity_gas, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::thermal_conductivity_particle, ParticleInteractionOutcomes< PropertiesIndex >::torque, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::update_contact_information(), and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vec_particle_type_index().
find_effective_radius_and_mass()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::tuple< double, double > ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::find_effective_radius_and_mass (const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties) inline private
Calculate the effective mass and the effective radius of particle pair.
Parameters
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
Definition at line 568 of file particle_particle_contact_force.h.
get_force_calculation_threshold_distance()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> double ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::get_force_calculation_threshold_distance () inline protected
Calculate the minimum overlap at which particle-particle forces are computed.
Returns
minimum overlap for the force calculation.
Definition at line 467 of file particle_particle_contact_force.h.
References Parameters::Lagrangian::DMT, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::dmt_cut_off_threshold, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_hamaker_constant, and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy.
get_location()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Point< 3 > ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::get_location (const Particles::ParticleIterator< dim > & particle) & inline protected
Get the location of the particle.
Parameters
[in] particle The particle from which to get the location.
Returns
The location of the particle.
Definition at line 284 of file particle_particle_contact_force.h.
References point_nd_to_3d().
get_periodic_location()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Point< 3 > ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::get_periodic_location (const Particles::ParticleIterator< dim > & particle, const Tensor< 1, 3 > & periodic_offset) & inline protected
Get the shifted location of a particle on a periodic boundary.
Parameters
[in] particle The particle to get the location from.
[in] periodic_offset The periodic offset with which to shift the location.
Returns
The offset periodic location of the particle.
Definition at line 303 of file particle_particle_contact_force.h.
References point_nd_to_3d().
set_effective_properties()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::set_effective_properties (const DEMSolverParameters< dim > & dem_parameters) inline private
Set every containers needed to carry the particle-particle force calculation.
Parameters
[in] dem_parameters DEM parameters declared in the .prm file.
Definition at line 1528 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_restitution, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_hamaker_constant, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_rolling_viscous_damping_coefficient, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus, harmonic_mean(), DEMSolverParameters< dim >::lagrangian_physical_properties, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::n_particle_types, and Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number.
set_multiphysic_properties()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::set_multiphysic_properties (const DEMSolverParameters< dim > & dem_parameters) inline private
Set every containers needed to carry the heat transfer rate calculation.
Parameters
[in] dem_parameters DEM parameters declared in the .prm file.
Definition at line 1644 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_microhardness, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_real_youngs_modulus, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::equivalent_surface_roughness, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::equivalent_surface_slope, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::gas_parameter_m, harmonic_mean(), DEMSolverParameters< dim >::lagrangian_physical_properties, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::n_particle_types, Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number, ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::thermal_conductivity_gas, and ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::thermal_conductivity_particle.
update_contact_information()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::update_contact_information (particle_particle_contact_info< dim > & contact_info, Tensor< 1, 3 > & tangential_relative_velocity, double & normal_relative_velocity_value, Tensor< 1, 3 > & normal_unit_vector, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, const Point< 3 > & particle_one_location, const Point< 3 > & particle_two_location, const double dt) inline protected
Update the contact pair information for all contact force calculations.
Parameters
[out] contact_info Contact information of a particle pair in neighborhood.
[out] tangential_relative_velocity Tangential relative velocity.
[out] normal_relative_velocity_value Normal relative contact velocity.
[out] normal_unit_vector Normal vector of the contact.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[in] particle_one_location Location of particle one in contact.
[in] particle_two_location Location of particle two in contact.
[in] dt DEM time step.
Definition at line 200 of file particle_particle_contact_force.h.
References particle_particle_contact_info< dim >::tangential_displacement.
vec_particle_type_index()
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> unsigned int ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::vec_particle_type_index (const unsigned int i, const unsigned int j) inline private
Return the index for accessing the properties vectors for a given combinations of particle types.
Parameters
[in] i First particle type index.
[in] j Second particle type index.
Returns
index associated with the combinations of particle types.
Definition at line 1516 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::n_particle_types.
Member Data Documentation
dmt_cut_off_threshold
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> const double ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::dmt_cut_off_threshold private
Definition at line 2052 of file particle_particle_contact_force.h.
effective_coefficient_of_friction
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_friction private
Definition at line 2046 of file particle_particle_contact_force.h.
effective_coefficient_of_restitution
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_restitution private
Definition at line 2045 of file particle_particle_contact_force.h.
effective_coefficient_of_rolling_friction
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction private
Definition at line 2048 of file particle_particle_contact_force.h.
effective_hamaker_constant
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_hamaker_constant private
Definition at line 2050 of file particle_particle_contact_force.h.
effective_microhardness
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_microhardness private
Definition at line 2056 of file particle_particle_contact_force.h.
effective_real_youngs_modulus
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_real_youngs_modulus private
Definition at line 2043 of file particle_particle_contact_force.h.
effective_rolling_viscous_damping_coefficient
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_rolling_viscous_damping_coefficient private
Definition at line 2047 of file particle_particle_contact_force.h.
effective_shear_modulus
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_shear_modulus private
Definition at line 2044 of file particle_particle_contact_force.h.
effective_surface_energy
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_surface_energy private
Definition at line 2049 of file particle_particle_contact_force.h.
effective_youngs_modulus
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::effective_youngs_modulus private
Definition at line 2042 of file particle_particle_contact_force.h.
equivalent_surface_roughness
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::equivalent_surface_roughness private
Definition at line 2054 of file particle_particle_contact_force.h.
equivalent_surface_slope
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::equivalent_surface_slope private
Definition at line 2055 of file particle_particle_contact_force.h.
f_coefficient_epsd
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> const double ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::f_coefficient_epsd private
Definition at line 2053 of file particle_particle_contact_force.h.
gas_parameter_m
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::gas_parameter_m private
Definition at line 2058 of file particle_particle_contact_force.h.
model_parameter_beta
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::model_parameter_beta private
Definition at line 2051 of file particle_particle_contact_force.h.
n_particle_types
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> unsigned int ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::n_particle_types private
Definition at line 2041 of file particle_particle_contact_force.h.
thermal_conductivity_gas
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> double ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::thermal_conductivity_gas private
Definition at line 2059 of file particle_particle_contact_force.h.
thermal_conductivity_particle
template<int dim, typename PropertiesIndex , Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, PropertiesIndex, contact_model, rolling_friction_model >::thermal_conductivity_particle private
Definition at line 2057 of file particle_particle_contact_force.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/particle_particle_contact_force.h
/home/runner/work/lethe/lethe/source/dem/particle_particle_contact_force.cc