Lethe Open-Source Library: ParticleProjector< dim > Class Template Reference
ParticleProjector< dim > Class Template Reference
#include <particle_projector.h>
Public Member Functions
ParticleProjector (parallel::DistributedTriangulationBase< dim > *triangulation, std::shared_ptr< Parameters::VoidFractionParameters< dim > > input_parameters, const Parameters::LinearSolver &linear_solver_parameters, Particles::ParticleHandler< dim > *particle_handler, const unsigned int fe_degree, const bool simplex, const ConditionalOStream &pcout)
void setup_dofs () override
void setup_constraints (const BoundaryConditions::NSBoundaryConditions< dim > &boundary_conditions)
void calculate_void_fraction (const double time)
void solve () override
void percolate_void_fraction ()
void initialize_void_fraction (const double time)
template<typename VectorType >
void gather_particle_fluid_forces_onto_particles (const Parameters::CFDDEM &cfd_dem_parameters, DoFHandler< dim > &fluid_dof_handler, const VectorType &fluid_solution, const std::vector< VectorType > &fluid_previous_solutions, NavierStokesScratchData< dim > &scratch_data)
template<int n_components, int property_start_index>
void calculate_field_projection (ParticleFieldQCM< dim, n_components, property_start_index > &field_qcm)
Public Member Functions inherited from PhysicsLinearSubequationsSolver
PhysicsLinearSubequationsSolver (const ConditionalOStream &pcout)
virtual ~PhysicsLinearSubequationsSolver ()=default
Public Attributes
DoFHandler< dim > dof_handler
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > quadrature
std::vector< GlobalVectorType > previous_void_fraction
GlobalVectorType void_fraction_locally_relevant
LinearAlgebra::distributed::Vector< double > void_fraction_solution
std::shared_ptr< FiniteElement< dim > > fe
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
AffineConstraints< double > void_fraction_constraints
ParticleFieldQCM< dim, 3, DEM::CFDDEMProperties::PropertiesIndex::v_x > particle_velocity
ParticleFieldQCM< dim, 3, DEM::CFDDEMProperties::PropertiesIndex::fem_force_x > particle_fluid_force
Private Member Functions
double calculate_qcm_radius_from_cell_measure (const double cell_measure)
void calculate_void_fraction_function (const double time)
void calculate_void_fraction_particle_centered_method ()
void calculate_void_fraction_satellite_point_method ()
void calculate_void_fraction_quadrature_centered_method ()
virtual void solve_void_fraction_linear_system () override
template<int property_start_index, int n_components>
void calculate_field_projection (ParticleFieldQCM< dim, property_start_index, n_components > &field_qcm)
Tensor< 1, dim > get_periodic_offset_distance (unsigned int boundary_id) const
Static Private Member Functions
static double radius_sphere_equivalent_volume (const double volume)
static double calculate_intersection_measure (double r_particle, double r_sphere, double distance_between_spheres)
Private Attributes
parallel::DistributedTriangulationBase< dim > * triangulation
std::shared_ptr< Parameters::VoidFractionParameters< dim > > void_fraction_parameters
const Parameters::LinearSolver linear_solver_parameters
Particles::ParticleHandler< dim > * particle_handler
GlobalVectorType void_fraction_locally_owned
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
TrilinosWrappers::SparseMatrix system_matrix_void_fraction
GlobalVectorType system_rhs_void_fraction
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_cell
bool has_periodic_boundaries
Tensor< 1, dim > periodic_offset
unsigned int periodic_direction
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_periodic_cell
const double l2_smoothing_factor
bool particle_have_been_projected
Additional Inherited Members
Protected Attributes inherited from PhysicsLinearSubequationsSolver
const ConditionalOStream pcout
Detailed Description
template<int dim>
class ParticleProjector< dim >
Particle information projection. This class manages the calculation of the projection of the particle fields onto a triangulation. Its main use is the calculation of the void fraction which is used as an auxiliary field for the solvers that solve the Volume-Averaged Navier-Stokes equations. The present architecture of the class support all of the different void fraction calculation methods within a single class instead of building a class hierarchy. This is because there are only a few void fraction calculation strategies.
Using QCM, this class is also capable of projecting arbitrary fields belonging to the particle back onto the mesh by instantiating @ParticleFieldQCM class.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
Definition at line 221 of file particle_projector.h.
Constructor & Destructor Documentation
ParticleProjector()
template<int dim> ParticleProjector< dim >::ParticleProjector (parallel::DistributedTriangulationBase< dim > * triangulation, std::shared_ptr< Parameters::VoidFractionParameters< dim > > input_parameters, const Parameters::LinearSolver & linear_solver_parameters, Particles::ParticleHandler< dim > * particle_handler, const unsigned int fe_degree, const bool simplex, const ConditionalOStream & pcout) inline
Constructor for the void fraction calculator.
Parameters
triangulation The triangulation on which the simulation is being done.
input_parameters The parameters for the void fraction calculation.
linear_solver_parameters The parameters for the linear solver. This is used to solve the L2 projection of the void fraction
particle_handler The particle handler used to manage the particles in the simulation. This object must be provided even if the particles are not used to establish the void fraction.
fe_degree The finite element degree used to interpolate the void fraction.
simplex A flag to indicate if the simulations are being done with simplex elements.
pcout The ConditionalOStream used to print the information.
Definition at line 235 of file particle_projector.h.
References ParticleProjector< dim >::fe, Parameters::gauss, Parameters::gauss_lobatto, ParticleProjector< dim >::mapping, Parameters::qcm, ParticleProjector< dim >::quadrature, and ParticleProjector< dim >::void_fraction_parameters.
Member Function Documentation
calculate_field_projection() [1/2]
template<int dim> template<int n_components, int property_start_index> void ParticleProjector< dim >::calculate_field_projection (ParticleFieldQCM< dim, n_components, property_start_index > & field_qcm)
Definition at line 1023 of file particle_projector.cc.
References convert_vector_trilinos_to_dealii(), ParticleFieldQCM< dim, n_components, property_start_index >::distribute_contribution, ParticleFieldQCM< dim, n_components, property_start_index >::dof_handler, DEM::CFDDEMProperties::dp, ParticleFieldQCM< dim, n_components, property_start_index >::fe, ParticleFieldQCM< dim, n_components, property_start_index >::neumann_boundaries, ParticleFieldQCM< dim, n_components, property_start_index >::particle_field_constraints, ParticleFieldQCM< dim, n_components, property_start_index >::particle_field_locally_owned, ParticleFieldQCM< dim, n_components, property_start_index >::particle_field_locally_relevant, ParticleFieldQCM< dim, n_components, property_start_index >::particle_field_solution, Parameters::quiet, ParticleFieldQCM< dim, n_components, property_start_index >::system_matrix, ParticleFieldQCM< dim, n_components, property_start_index >::system_rhs, and DEM::CFDDEMProperties::volumetric_contribution.
calculate_field_projection() [2/2]
template<int dim> template<int property_start_index, int n_components> void ParticleProjector< dim >::calculate_field_projection (ParticleFieldQCM< dim, property_start_index, n_components > & field_qcm) private
Calculates the projection of a particle field onto the mesh.
Template Parameters
property_start_index An integer for the particle_property that will be projected
n_components The number of components of the field. This should be either 1 (scalar) or dim (a Tensor<1,dim>).
Parameters
field_qcm The container for the field that will be projected.
calculate_intersection_measure()
template<int dim> static double ParticleProjector< dim >::calculate_intersection_measure (double r_particle, double r_sphere, double distance_between_spheres) inline static private
Calculate the intersection measure (volume in 3D and area in 2D) between a particle and an hypersphere. This is used when calculating the intersection volume between the averaging sphere and a particle in QCM. The calculation inherently assumes that the radius of the averaging sphere is larger than that of the particle.
Parameters
r_particle The radius of the particle
r_sphere The radius of the averaging sphere
distance_between_spheres The distance between the centers of the spheres
Returns
The intersection volume (in 3D) or area (in 2d)
Definition at line 460 of file particle_projector.h.
References particle_circle_intersection_2d(), and particle_sphere_intersection_3d().
calculate_qcm_radius_from_cell_measure()
template<int dim> double ParticleProjector< dim >::calculate_qcm_radius_from_cell_measure (const double cell_measure) inline private
Calculate the radius of the QCM averaging sphere.
Parameters
cell_measure The measure of the cell in wich QCM is calculated.
Returns
The QCM radius used in the calculations.
Definition at line 430 of file particle_projector.h.
References ParticleProjector< dim >::radius_sphere_equivalent_volume(), and ParticleProjector< dim >::void_fraction_parameters.
calculate_void_fraction()
template<int dim> void ParticleProjector< dim >::calculate_void_fraction (const double time)
Calculate the void fraction.
Parameters
[in] time Current time for which the void fraction is to be calculated.
Definition at line 232 of file particle_projector.cc.
References announce_string(), Parameters::function, Parameters::pcm, Parameters::qcm, and Parameters::spm.
calculate_void_fraction_function()
template<int dim> void ParticleProjector< dim >::calculate_void_fraction_function (const double time) private
Calculate the void fraction using a function. This is a straightforward usage of VectorTools.
Parameters
[in] time Current time for which the void fraction is to be calculated.
Definition at line 271 of file particle_projector.cc.
References convert_vector_trilinos_to_dealii().
calculate_void_fraction_particle_centered_method()
template<int dim> void ParticleProjector< dim >::calculate_void_fraction_particle_centered_method () private
Calculate the void fraction using the particle centered method.
Definition at line 300 of file particle_projector.cc.
References DEM::CFDDEMProperties::dp.
calculate_void_fraction_quadrature_centered_method()
template<int dim> void ParticleProjector< dim >::calculate_void_fraction_quadrature_centered_method () private
Calculate the void fraction using the Quadrature-Centered Method (QCM).
Definition at line 639 of file particle_projector.cc.
References DEM::CFDDEMProperties::dp, and DEM::CFDDEMProperties::volumetric_contribution.
calculate_void_fraction_satellite_point_method()
template<int dim> void ParticleProjector< dim >::calculate_void_fraction_satellite_point_method () private
Calculate the void fraction using the satellite point method.
Definition at line 399 of file particle_projector.cc.
References DEM::CFDDEMProperties::dp.
gather_particle_fluid_forces_onto_particles()
template<int dim> template<typename VectorType > template void ParticleProjector< dim >::gather_particle_fluid_forces_onto_particles (const Parameters::CFDDEM & cfd_dem_parameters, DoFHandler< dim > & fluid_dof_handler, const VectorType & fluid_solution, const std::vector< VectorType > & fluid_previous_solutions, NavierStokesScratchData< dim > & scratch_data)
Definition at line 1379 of file particle_projector.cc.
References Parameters::beetstra, Parameters::dallavalle, Parameters::difelice, Parameters::CFDDEM::drag_force, Parameters::CFDDEM::drag_model, NavierStokesScratchData< dim >::enable_particle_fluid_interactions(), Parameters::gidaspow, Parameters::kochhill, Parameters::CFDDEM::pressure_force, NavierStokesScratchData< dim >::reinit_particle_fluid_interactions(), NavierStokesScratchData< dim >::reinit_void_fraction(), Parameters::rong, and Parameters::CFDDEM::shear_force.
get_periodic_offset_distance()
template<int dim> Tensor< 1, dim > ParticleProjector< dim >::get_periodic_offset_distance (unsigned int boundary_id) const inline private
Calculate and return the periodic offset distance vector of the domain which is needed for the periodic boundary conditions using the QCM or SPM for void fraction with the GLS VANS/CFD-DEM solver. The distance is based on one of the periodic boundaries. This periodic boundary is then used as the reference for all particle locations shifted by this offset vector.
Parameters
[in] boundary_id The ID of one of the periodic boundaries
Returns
The periodic offset vector.
Definition at line 559 of file particle_projector.h.
References ParticleProjector< dim >::triangulation.
initialize_void_fraction()
template<int dim> void ParticleProjector< dim >::initialize_void_fraction (const double time) inline
Initialize the void fraction at the beginning of a simulation.
Parameters
[in] time The current time. This is used for time-dependent functions.
Definition at line 363 of file particle_projector.h.
References ParticleProjector< dim >::calculate_void_fraction(), ParticleProjector< dim >::previous_void_fraction, and ParticleProjector< dim >::void_fraction_locally_relevant.
percolate_void_fraction()
template<int dim> void ParticleProjector< dim >::percolate_void_fraction () inline
Percolate the time vector for the void fraction. This operation is called at the end of a time-step.
Definition at line 346 of file particle_projector.h.
References ParticleProjector< dim >::previous_void_fraction, and ParticleProjector< dim >::void_fraction_locally_relevant.
radius_sphere_equivalent_volume()
template<int dim> static double ParticleProjector< dim >::radius_sphere_equivalent_volume (const double volume) inline static private
Calculate the characteristic radius of a sphere with a given volume (area in 2D): R = (2*dim*V/pi)^(1/dim) / 2.
Parameters
volume value for which the equivalent radius of a sphere is calculated.
Returns
Radius of a sphere with equivalent volume
Definition at line 416 of file particle_projector.h.
setup_constraints()
template<int dim> void ParticleProjector< dim >::setup_constraints (const BoundaryConditions::NSBoundaryConditions< dim > & boundary_conditions)
Establish the constraints of the void fraction systems.
Parameters
[in] boundary_conditions The boundary conditions of fluid dynamics. This is used to establish periodic boundary conditions for the void fraction.
Definition at line 159 of file particle_projector.cc.
References BoundaryConditions::periodic, BoundaryConditions::BoundaryConditions::periodic_direction, BoundaryConditions::BoundaryConditions::periodic_neighbor_id, Parameters::qcm, Parameters::spm, and BoundaryConditions::BoundaryConditions::type.
setup_dofs()
template<int dim> void ParticleProjector< dim >::setup_dofs () override virtual
Setup the degrees of freedom.
Implements PhysicsSubequationsSolverBase.
Definition at line 78 of file particle_projector.cc.
References maximum_number_of_previous_solutions(), and LetheGridTools::vertices_cell_mapping().
solve()
template<int dim> void ParticleProjector< dim >::solve () inline override virtual
Assemble and solve the system.
Implements PhysicsSubequationsSolverBase.
Definition at line 337 of file particle_projector.h.
solve_void_fraction_linear_system()
template<int dim> void ParticleProjector< dim >::solve_void_fraction_linear_system () override private virtual
Solve the linear system resulting from the assemblies.
Implements PhysicsLinearSubequationsSolver.
Definition at line 1563 of file particle_projector.cc.
References convert_vector_trilinos_to_dealii(), and Parameters::quiet.
Member Data Documentation
dof_handler
template<int dim> DoFHandler<dim> ParticleProjector< dim >::dof_handler
DoFHandler that manages the void fraction.
Definition at line 371 of file particle_projector.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > ParticleProjector< dim >::fe
Finite element for the void fraction.
Definition at line 390 of file particle_projector.h.
has_periodic_boundaries
template<int dim> bool ParticleProjector< dim >::has_periodic_boundaries private
Boolean to indicate if the mesh has periodic boundaries.
Definition at line 644 of file particle_projector.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> ParticleProjector< dim >::ilu_preconditioner private
Preconditioner used for the solution of the smoothed L2 projection of the void fraction
Definition at line 627 of file particle_projector.h.
l2_smoothing_factor
template<int dim> const double ParticleProjector< dim >::l2_smoothing_factor private
Initial value:
=
    Utilities::fixed_power<2>(void_fraction_parameters->l2_smoothing_length)
Smoothing length factor for the void fraction calculation.
Definition at line 659 of file particle_projector.h.
linear_solver_parameters
template<int dim> const Parameters::LinearSolver ParticleProjector< dim >::linear_solver_parameters private
Linear solvers for the calculation of the void fraction.
Definition at line 617 of file particle_projector.h.
locally_owned_dofs
template<int dim> IndexSet ParticleProjector< dim >::locally_owned_dofs
Index set for the locally owned degree of freedoms.
Definition at line 393 of file particle_projector.h.
locally_relevant_dofs
template<int dim> IndexSet ParticleProjector< dim >::locally_relevant_dofs
Index set for the locally relevant degree of freedoms.
Definition at line 396 of file particle_projector.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > ParticleProjector< dim >::mapping
Mapping for the void fraction.
Definition at line 374 of file particle_projector.h.
particle_fluid_force
template<int dim> ParticleFieldQCM<dim, 3, DEM::CFDDEMProperties::PropertiesIndex::fem_force_x> ParticleProjector< dim >::particle_fluid_force
Definition at line 672 of file particle_projector.h.
particle_handler
template<int dim> Particles::ParticleHandler<dim>* ParticleProjector< dim >::particle_handler private
Particle handler used when the void fraction depends on particles.
Definition at line 620 of file particle_projector.h.
particle_have_been_projected
template<int dim> bool ParticleProjector< dim >::particle_have_been_projected private
Boolean indicator used to check if the particle have at least been projected once. This is mainly use for assertions and sanity checking purposed
Definition at line 665 of file particle_projector.h.
particle_velocity
template<int dim> ParticleFieldQCM<dim, 3, DEM::CFDDEMProperties::PropertiesIndex::v_x> ParticleProjector< dim >::particle_velocity
Definition at line 669 of file particle_projector.h.
periodic_direction
template<int dim> unsigned int ParticleProjector< dim >::periodic_direction private
Direction associated with the periodic boundary condition.
Definition at line 650 of file particle_projector.h.
periodic_offset
template<int dim> Tensor<1, dim> ParticleProjector< dim >::periodic_offset private
Offset for the periodic boundary condition.
Definition at line 647 of file particle_projector.h.
previous_void_fraction
template<int dim> std::vector<GlobalVectorType> ParticleProjector< dim >::previous_void_fraction
The solutions are made public instead of using getters Solution of the void fraction at previous time steps
Definition at line 381 of file particle_projector.h.
quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > ParticleProjector< dim >::quadrature
Quadrature for the void fraction.
Definition at line 377 of file particle_projector.h.
system_matrix_void_fraction
template<int dim> TrilinosWrappers::SparseMatrix ParticleProjector< dim >::system_matrix_void_fraction private
System matrix used to assemble the smoothed L2 projection of the void fraction
Definition at line 631 of file particle_projector.h.
system_rhs_void_fraction
template<int dim> GlobalVectorType ParticleProjector< dim >::system_rhs_void_fraction private
Right-hand side used to assemble the smoothed L2 projection of the void fraction
Definition at line 635 of file particle_projector.h.
triangulation
template<int dim> parallel::DistributedTriangulationBase<dim>* ParticleProjector< dim >::triangulation private
Triangulation.
Definition at line 606 of file particle_projector.h.
vertices_to_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > ParticleProjector< dim >::vertices_to_cell private
Vertices to cell map, this is used in the QCM and the satellite point method to access the neighboring cells of a cell.
Definition at line 641 of file particle_projector.h.
vertices_to_periodic_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > ParticleProjector< dim >::vertices_to_periodic_cell private
Vertices to periodic cell map, this is used in the QCM and the satellite point method to access the neighboring cells of a cell.
Definition at line 656 of file particle_projector.h.
void_fraction_constraints
template<int dim> AffineConstraints<double> ParticleProjector< dim >::void_fraction_constraints
Constraints used for the boundary conditions of the void fraction. Currently, this is only used to establish periodic void fractions. This object has to be made public because the boundary conditions are set outside of the object for now.
Definition at line 402 of file particle_projector.h.
void_fraction_locally_owned
template<int dim> GlobalVectorType ParticleProjector< dim >::void_fraction_locally_owned private
Locally owned solution of the void fraction.
Definition at line 623 of file particle_projector.h.
void_fraction_locally_relevant
template<int dim> GlobalVectorType ParticleProjector< dim >::void_fraction_locally_relevant
Fully distributed (including locally relevant) solution.
Definition at line 384 of file particle_projector.h.
void_fraction_parameters
template<int dim> std::shared_ptr<Parameters::VoidFractionParameters<dim> > ParticleProjector< dim >::void_fraction_parameters private
Parameters for the calculation of the void fraction Right now this is used for the VANS matrix-free solver to directly calculate the void fraction from the function itself. The function will be removed back to private in a future PR.
Definition at line 614 of file particle_projector.h.
void_fraction_solution
template<int dim> LinearAlgebra::distributed::Vector<double> ParticleProjector< dim >::void_fraction_solution
deal.II vector for the void fraction
Definition at line 387 of file particle_projector.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/particle_projector.h
/home/runner/work/lethe/lethe/source/fem-dem/particle_projector.cc