Lethe Open-Source Library: DEMContactManager< dim, PropertiesIndex > Class Template Reference
DEMContactManager< dim, PropertiesIndex > Class Template Reference
#include <dem_contact_manager.h>
Public Member Functions
void execute_cell_neighbors_search (const parallel::distributed::Triangulation< dim > &triangulation, const typename DEM::dem_data_structures< dim >::periodic_boundaries_cells_info periodic_boundaries_cells_information)
void update_cell_neighbors (const parallel::distributed::Triangulation< dim > &triangulation, const typename DEM::dem_data_structures< dim >::periodic_boundaries_cells_info periodic_boundaries_cells_information)
void update_contacts ()
void update_local_particles_in_cells (const Particles::ParticleHandler< dim > &particle_handler)
void execute_particle_particle_broad_search (dealii::Particles::ParticleHandler< dim > &particle_handler, const AdaptiveSparseContacts< dim, PropertiesIndex > &sparse_particle_contact_object)
void execute_particle_wall_broad_search (const Particles::ParticleHandler< dim > &particle_handler, BoundaryCellsInformation< dim > &boundary_cell_object, const typename dem_data_structures< dim >::solid_surfaces_mesh_information solid_surfaces_mesh_info, const Parameters::Lagrangian::FloatingWalls< dim > &floating_walls, const double simulation_time, const AdaptiveSparseContacts< dim, PropertiesIndex > &sparse_particle_contact_object)
void execute_particle_particle_fine_search (const double neighborhood_threshold)
void execute_particle_wall_fine_search (const Parameters::Lagrangian::FloatingWalls< dim > &floating_walls, const double simulation_time, const double neighborhood_threshold)
void set_combined_periodic_offsets (const std::vector< Tensor< 1, dim > > &offsets)
dem_data_structures< dim >::particle_floating_mesh_potentially_in_contact & get_particle_floating_mesh_potentially_in_contact ()
dem_data_structures< dim >::particle_wall_in_contact & get_particle_floating_wall_in_contact ()
dem_data_structures< dim >::particle_wall_in_contact & get_particle_wall_in_contact ()
dem_data_structures< dim >::particle_line_candidates & get_particle_lines_in_contact ()
dem_data_structures< dim >::particle_point_candidates & get_particle_points_in_contact ()
dem_data_structures< dim >::adjacent_particle_pairs & get_local_adjacent_particles ()
dem_data_structures< dim >::adjacent_particle_pairs & get_ghost_adjacent_particles ()
dem_data_structures< dim >::periodic_adjacent_particle_pairs & get_local_local_periodic_adjacent_particles ()
dem_data_structures< dim >::periodic_adjacent_particle_pairs & get_local_ghost_periodic_adjacent_particles ()
dem_data_structures< dim >::periodic_adjacent_particle_pairs & get_ghost_local_periodic_adjacent_particles ()
dem_data_structures< dim >::particle_particle_candidates & get_local_contact_pair_candidates ()
dem_data_structures< dim >::particle_particle_candidates & get_ghost_contact_pair_candidates ()
Private Attributes
dem_data_structures< dim >::particle_index_iterator_map particle_container
dem_data_structures< dim >::cells_total_neighbor_list total_neighbor_list
dem_data_structures< dim >::cells_neighbor_list cells_local_neighbor_list
dem_data_structures< dim >::cells_neighbor_list cells_ghost_neighbor_list
dem_data_structures< dim >::cells_neighbor_list cells_local_periodic_neighbor_list
dem_data_structures< dim >::cells_neighbor_list cells_ghost_periodic_neighbor_list
dem_data_structures< dim >::cells_neighbor_list cells_ghost_local_periodic_neighbor_list
dem_data_structures< dim >::particle_particle_candidates local_contact_pair_candidates
dem_data_structures< dim >::particle_particle_candidates ghost_contact_pair_candidates
dem_data_structures< dim >::particle_particle_candidates ghost_local_contact_pair_candidates
dem_data_structures< dim >::particle_particle_candidates local_contact_pair_periodic_candidates
dem_data_structures< dim >::particle_particle_candidates ghost_contact_pair_periodic_candidates
dem_data_structures< dim >::particle_particle_candidates ghost_local_contact_pair_periodic_candidates
dem_data_structures< dim >::particle_floating_mesh_candidates particle_floating_mesh_candidates
dem_data_structures< dim >::particle_floating_wall_candidates particle_floating_wall_candidates
dem_data_structures< dim >::particle_point_candidates particle_point_candidates
dem_data_structures< dim >::particle_line_candidates particle_line_candidates
dem_data_structures< dim >::particle_wall_candidates particle_wall_candidates
dem_data_structures< dim >::particle_floating_mesh_potentially_in_contact particle_floating_mesh_potentially_in_contact
dem_data_structures< dim >::particle_wall_in_contact particle_floating_wall_in_contact
dem_data_structures< dim >::particle_wall_in_contact particle_wall_in_contact
dem_data_structures< dim >::particle_line_candidates particle_lines_in_contact
dem_data_structures< dim >::particle_point_candidates particle_points_in_contact
dem_data_structures< dim >::adjacent_particle_pairs local_adjacent_particles
dem_data_structures< dim >::adjacent_particle_pairs ghost_adjacent_particles
dem_data_structures< dim >::periodic_adjacent_particle_pairs local_local_periodic_adjacent_particles
dem_data_structures< dim >::periodic_adjacent_particle_pairs local_ghost_periodic_adjacent_particles
dem_data_structures< dim >::periodic_adjacent_particle_pairs ghost_local_periodic_adjacent_particles
DEM::dem_data_structures< dim >::cell_vector periodic_cells_container
std::vector< Tensor< 1, dim > > combined_periodic_offsets
Detailed Description
template<int dim, typename PropertiesIndex>
class DEMContactManager< dim, PropertiesIndex >
Manage the numerous of contact detection search operations in the DEM.
This class mostly calls proper functions in regards the type of contacts for the contact detection and updates of data containers.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Definition at line 29 of file dem_contact_manager.h.
Member Function Documentation
execute_cell_neighbors_search()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::execute_cell_neighbors_search (const parallel::distributed::Triangulation< dim > & triangulation, const typename DEM::dem_data_structures< dim >::periodic_boundaries_cells_info periodic_boundaries_cells_information)
Execute functions to find the lists of cell neighbors of the active cells in the triangulation.
For contacts of particles, the neighbor search excludes the repetitions of neighbors: B is neighbor of A but A will not be neighbor of B. For contacts of particles with floating meshes, the neighbor search includes all neighbors. These floating mesh contacts searches need all the particles located in all the neighbor cells of the main cell to detect collisions with the floating mesh.
Parameters
[in] triangulation The triangulation to access the information of the cells.
[in] periodic_boundaries_cells_information Information of periodic cells used if periodic boundaries are enabled (next parameter).
Definition at line 19 of file dem_contact_manager.cc.
References DEMActionManager::get_action_manager().
execute_particle_particle_broad_search()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::execute_particle_particle_broad_search (dealii::Particles::ParticleHandler< dim > & particle_handler, const AdaptiveSparseContacts< dim, PropertiesIndex > & sparse_particle_contact_object)
Execute the particle-particle broad searches with adaptive sparse contacts.
Calls proper functions to find the candidates of local and ghost particle-particle contact pairs and the periodic particle-particle contacts if required. These contact pairs will be used in the fine search step to investigate if they are in contact. It checks if the adaptive sparse contacts is enabled and use proper functions.
Parameters
[in,out] particle_handler Storage of particles and their accessor functions.
[in] sparse_particle_contact_object Allow to check the mobility status of cells.
Definition at line 240 of file dem_contact_manager.cc.
References DEMActionManager::get_action_manager().
execute_particle_particle_fine_search()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::execute_particle_particle_fine_search (const double neighborhood_threshold)
Execute the particle-particles fine searches.
Executes functions that update the particle contacts pairs containers and compute the contact information of the collision pairs.
Parameters
[in] neighborhood_threshold Threshold value of contact detection.
Definition at line 398 of file dem_contact_manager.cc.
References DEMActionManager::get_action_manager(), ghost_local_periodic_particle_particle, and particle_particle_fine_search().
execute_particle_wall_broad_search()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::execute_particle_wall_broad_search (const Particles::ParticleHandler< dim > & particle_handler, BoundaryCellsInformation< dim > & boundary_cell_object, const typename dem_data_structures< dim >::solid_surfaces_mesh_information solid_surfaces_mesh_info, const Parameters::Lagrangian::FloatingWalls< dim > & floating_walls, const double simulation_time, const AdaptiveSparseContacts< dim, PropertiesIndex > & sparse_particle_contact_object)
Execute the particle-wall broad searches with adaptive sparse contacts.
Calls proper functions to find the candidates of particle-wall contact pairs and the particle-floating wall or particle-floating mesh if required. These contact pairs will be used in the fine search step to investigate if they are in contact. It checks if the adaptive sparse contacts is enabled and use proper functions.
Parameters
[in] particle_handler Storage of particles and their accessor functions.
[in] boundary_cells_object Information of the boundary cells and faces.
[in] solid_surfaces_mesh_info Mapping of solid surfaces meshes.
[in] floating_wall Properties of the floating walls.
[in] simulation_time Current simulation time.
[in] sparse_particle_contact_object Allow to check the mobility status of cells.
Definition at line 294 of file dem_contact_manager.cc.
References Parameters::Lagrangian::FloatingWalls< dim >::floating_walls_number, DEMActionManager::get_action_manager(), BoundaryCellsInformation< dim >::get_boundary_cells_information(), BoundaryCellsInformation< dim >::get_boundary_cells_with_floating_walls(), BoundaryCellsInformation< dim >::get_boundary_cells_with_lines(), and BoundaryCellsInformation< dim >::get_boundary_cells_with_points().
execute_particle_wall_fine_search()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::execute_particle_wall_fine_search (const Parameters::Lagrangian::FloatingWalls< dim > & floating_walls, const double simulation_time, const double neighborhood_threshold)
Execute the particle-wall fine searches.
Executes functions that update the particle-wall contacts pairs containers and compute the contact information of the collision particle-wall.
Parameters
[in] floating_wall Properties of the floating walls.
[in] simulation_time Current simulation time.
[in] neighborhood_threshold Threshold value of contact detection.
Definition at line 447 of file dem_contact_manager.cc.
References Parameters::Lagrangian::FloatingWalls< dim >::floating_walls_number, and DEMActionManager::get_action_manager().
get_ghost_adjacent_particles()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::adjacent_particle_pairs & DEMContactManager< dim, PropertiesIndex >::get_ghost_adjacent_particles () inline
Return the local-ghost particle contact container.
Definition at line 261 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::ghost_adjacent_particles.
get_ghost_contact_pair_candidates()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::particle_particle_candidates & DEMContactManager< dim, PropertiesIndex >::get_ghost_contact_pair_candidates () inline
Return the ghost particle-particle contact candidates.
Definition at line 306 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::ghost_contact_pair_candidates.
get_ghost_local_periodic_adjacent_particles()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::periodic_adjacent_particle_pairs & DEMContactManager< dim, PropertiesIndex >::get_ghost_local_periodic_adjacent_particles () inline
Return the ghost-local periodic particle contact container.
Definition at line 288 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::ghost_local_periodic_adjacent_particles.
get_local_adjacent_particles()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::adjacent_particle_pairs & DEMContactManager< dim, PropertiesIndex >::get_local_adjacent_particles () inline
Return the local-local particle contact container.
Definition at line 252 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::local_adjacent_particles.
get_local_contact_pair_candidates()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::particle_particle_candidates & DEMContactManager< dim, PropertiesIndex >::get_local_contact_pair_candidates () inline
Return the local particle-particle contact candidates.
Definition at line 297 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::local_contact_pair_candidates.
get_local_ghost_periodic_adjacent_particles()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::periodic_adjacent_particle_pairs & DEMContactManager< dim, PropertiesIndex >::get_local_ghost_periodic_adjacent_particles () inline
Return the local-ghost periodic particle contact container.
Definition at line 279 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::local_ghost_periodic_adjacent_particles.
get_local_local_periodic_adjacent_particles()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::periodic_adjacent_particle_pairs & DEMContactManager< dim, PropertiesIndex >::get_local_local_periodic_adjacent_particles () inline
Return the local-local periodic particle contact container.
Definition at line 270 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::local_local_periodic_adjacent_particles.
get_particle_floating_mesh_potentially_in_contact()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::particle_floating_mesh_potentially_in_contact & DEMContactManager< dim, PropertiesIndex >::get_particle_floating_mesh_potentially_in_contact () inline
Return the particle-floating mesh contact container.
Definition at line 207 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::particle_floating_mesh_potentially_in_contact.
get_particle_floating_wall_in_contact()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::particle_wall_in_contact & DEMContactManager< dim, PropertiesIndex >::get_particle_floating_wall_in_contact () inline
Return the particle-floating wall contact container.
Definition at line 216 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::particle_floating_wall_in_contact.
get_particle_lines_in_contact()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::particle_line_candidates & DEMContactManager< dim, PropertiesIndex >::get_particle_lines_in_contact () inline
Return the particle-line contact container.
Definition at line 234 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::particle_lines_in_contact.
get_particle_points_in_contact()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::particle_point_candidates & DEMContactManager< dim, PropertiesIndex >::get_particle_points_in_contact () inline
Return the particle-point contact container.
Definition at line 243 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::particle_points_in_contact.
get_particle_wall_in_contact()
template<int dim, typename PropertiesIndex > dem_data_structures< dim >::particle_wall_in_contact & DEMContactManager< dim, PropertiesIndex >::get_particle_wall_in_contact () inline
Return the particle-wall contact container.
Definition at line 225 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::particle_wall_in_contact.
set_combined_periodic_offsets()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::set_combined_periodic_offsets (const std::vector< Tensor< 1, dim > > & offsets) inline
Set the combined offsets for periodic boundaries.
Parameters
[in] offsets Combined periodic offsets for periodic boundaries, used for determining periodic contacts.
Definition at line 197 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::combined_periodic_offsets.
update_cell_neighbors()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::update_cell_neighbors (const parallel::distributed::Triangulation< dim > & triangulation, const typename DEM::dem_data_structures< dim >::periodic_boundaries_cells_info periodic_boundaries_cells_information) inline
Execute functions to clear and update the neighbor lists of all the active cells in the triangulation.
Parameters
[in] triangulation The triangulation to access the information of the cells.
[in] periodic_boundaries_cells_information Information of periodic cells used if periodic boundaries are enabled (next parameter).
Definition at line 64 of file dem_contact_manager.h.
References DEMContactManager< dim, PropertiesIndex >::cells_ghost_local_periodic_neighbor_list, DEMContactManager< dim, PropertiesIndex >::cells_ghost_neighbor_list, DEMContactManager< dim, PropertiesIndex >::cells_ghost_periodic_neighbor_list, DEMContactManager< dim, PropertiesIndex >::cells_local_neighbor_list, DEMContactManager< dim, PropertiesIndex >::cells_local_periodic_neighbor_list, DEMContactManager< dim, PropertiesIndex >::execute_cell_neighbors_search(), and DEMContactManager< dim, PropertiesIndex >::total_neighbor_list.
update_contacts()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::update_contacts ()
Execute functions to update the contact data containers with the new contact pairs.
Call proper functions to remove contact repetitions and to add new contact pairs to the contact containers when particles are exchanged between processors after the fine search. Contact pairs are local particle-particle, ghost particle-particle, particle-wall, particle-floating wall contacts and particle-floating mesh contacts.
Definition at line 52 of file dem_contact_manager.cc.
References DEMActionManager::check_periodic_boundaries_enabled(), DEMActionManager::get_action_manager(), ghost_particle_particle, local_particle_particle, local_periodic_particle_particle, and update_fine_search_candidates().
update_local_particles_in_cells()
template<int dim, typename PropertiesIndex > void DEMContactManager< dim, PropertiesIndex >::update_local_particles_in_cells (const Particles::ParticleHandler< dim > & particle_handler)
Execute functions to update the particle iterators in local-local contact containers.
This is essential since sort_particles_into_subdomains_and_cells() and exchange_ghost_particles() functions change the particle iterators everytime they are called.
Parameters
[in] particle_handler Storage of particles and their accessor functions.
Definition at line 148 of file dem_contact_manager.cc.
Member Data Documentation
cells_ghost_local_periodic_neighbor_list
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::cells_neighbor_list DEMContactManager< dim, PropertiesIndex >::cells_ghost_local_periodic_neighbor_list private
Definition at line 329 of file dem_contact_manager.h.
cells_ghost_neighbor_list
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::cells_neighbor_list DEMContactManager< dim, PropertiesIndex >::cells_ghost_neighbor_list private
Definition at line 323 of file dem_contact_manager.h.
cells_ghost_periodic_neighbor_list
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::cells_neighbor_list DEMContactManager< dim, PropertiesIndex >::cells_ghost_periodic_neighbor_list private
Definition at line 327 of file dem_contact_manager.h.
cells_local_neighbor_list
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::cells_neighbor_list DEMContactManager< dim, PropertiesIndex >::cells_local_neighbor_list private
Definition at line 321 of file dem_contact_manager.h.
cells_local_periodic_neighbor_list
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::cells_neighbor_list DEMContactManager< dim, PropertiesIndex >::cells_local_periodic_neighbor_list private
Definition at line 325 of file dem_contact_manager.h.
combined_periodic_offsets
template<int dim, typename PropertiesIndex > std::vector<Tensor<1, dim> > DEMContactManager< dim, PropertiesIndex >::combined_periodic_offsets private
Storage for all precomputed periodic translation vectors, representing translations between pairs of periodic faces and corners. Initialized to identity (zero offset) for compatibility with non-periodic geometry.
Definition at line 393 of file dem_contact_manager.h.
ghost_adjacent_particles
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::adjacent_particle_pairs DEMContactManager< dim, PropertiesIndex >::ghost_adjacent_particles private
Definition at line 375 of file dem_contact_manager.h.
ghost_contact_pair_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_particle_candidates DEMContactManager< dim, PropertiesIndex >::ghost_contact_pair_candidates private
Definition at line 335 of file dem_contact_manager.h.
ghost_contact_pair_periodic_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_particle_candidates DEMContactManager< dim, PropertiesIndex >::ghost_contact_pair_periodic_candidates private
Definition at line 341 of file dem_contact_manager.h.
ghost_local_contact_pair_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_particle_candidates DEMContactManager< dim, PropertiesIndex >::ghost_local_contact_pair_candidates private
Definition at line 337 of file dem_contact_manager.h.
ghost_local_contact_pair_periodic_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_particle_candidates DEMContactManager< dim, PropertiesIndex >::ghost_local_contact_pair_periodic_candidates private
Definition at line 343 of file dem_contact_manager.h.
ghost_local_periodic_adjacent_particles
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::periodic_adjacent_particle_pairs DEMContactManager< dim, PropertiesIndex >::ghost_local_periodic_adjacent_particles private
Definition at line 381 of file dem_contact_manager.h.
local_adjacent_particles
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::adjacent_particle_pairs DEMContactManager< dim, PropertiesIndex >::local_adjacent_particles private
Definition at line 373 of file dem_contact_manager.h.
local_contact_pair_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_particle_candidates DEMContactManager< dim, PropertiesIndex >::local_contact_pair_candidates private
Definition at line 333 of file dem_contact_manager.h.
local_contact_pair_periodic_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_particle_candidates DEMContactManager< dim, PropertiesIndex >::local_contact_pair_periodic_candidates private
Definition at line 339 of file dem_contact_manager.h.
local_ghost_periodic_adjacent_particles
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::periodic_adjacent_particle_pairs DEMContactManager< dim, PropertiesIndex >::local_ghost_periodic_adjacent_particles private
Definition at line 379 of file dem_contact_manager.h.
local_local_periodic_adjacent_particles
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::periodic_adjacent_particle_pairs DEMContactManager< dim, PropertiesIndex >::local_local_periodic_adjacent_particles private
Definition at line 377 of file dem_contact_manager.h.
particle_container
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_index_iterator_map DEMContactManager< dim, PropertiesIndex >::particle_container private
Definition at line 314 of file dem_contact_manager.h.
particle_floating_mesh_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_floating_mesh_candidates DEMContactManager< dim, PropertiesIndex >::particle_floating_mesh_candidates private
Definition at line 345 of file dem_contact_manager.h.
particle_floating_mesh_potentially_in_contact
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_floating_mesh_potentially_in_contact DEMContactManager< dim, PropertiesIndex >::particle_floating_mesh_potentially_in_contact private
Definition at line 359 of file dem_contact_manager.h.
particle_floating_wall_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_floating_wall_candidates DEMContactManager< dim, PropertiesIndex >::particle_floating_wall_candidates private
Definition at line 347 of file dem_contact_manager.h.
particle_floating_wall_in_contact
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_wall_in_contact DEMContactManager< dim, PropertiesIndex >::particle_floating_wall_in_contact private
Definition at line 361 of file dem_contact_manager.h.
particle_line_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_line_candidates DEMContactManager< dim, PropertiesIndex >::particle_line_candidates private
Definition at line 351 of file dem_contact_manager.h.
particle_lines_in_contact
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_line_candidates DEMContactManager< dim, PropertiesIndex >::particle_lines_in_contact private
Definition at line 365 of file dem_contact_manager.h.
particle_point_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_point_candidates DEMContactManager< dim, PropertiesIndex >::particle_point_candidates private
Definition at line 349 of file dem_contact_manager.h.
particle_points_in_contact
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_point_candidates DEMContactManager< dim, PropertiesIndex >::particle_points_in_contact private
Definition at line 367 of file dem_contact_manager.h.
particle_wall_candidates
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_wall_candidates DEMContactManager< dim, PropertiesIndex >::particle_wall_candidates private
Definition at line 353 of file dem_contact_manager.h.
particle_wall_in_contact
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::particle_wall_in_contact DEMContactManager< dim, PropertiesIndex >::particle_wall_in_contact private
Definition at line 363 of file dem_contact_manager.h.
periodic_cells_container
template<int dim, typename PropertiesIndex > DEM::dem_data_structures<dim>::cell_vector DEMContactManager< dim, PropertiesIndex >::periodic_cells_container private
Definition at line 384 of file dem_contact_manager.h.
total_neighbor_list
template<int dim, typename PropertiesIndex > dem_data_structures<dim>::cells_total_neighbor_list DEMContactManager< dim, PropertiesIndex >::total_neighbor_list private
Definition at line 319 of file dem_contact_manager.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/dem_contact_manager.h
/home/runner/work/lethe/lethe/source/dem/dem_contact_manager.cc