Lethe Open-Source Library: /home/runner/work/lethe/lethe/include/core/utilities.h File Reference
utilities.h File Reference
#include <core/output_struct.h>
#include <deal.II/base/conditional_ostream.h>
#include <deal.II/base/parameter_handler.h>
#include <deal.II/base/point.h>
#include <deal.II/base/table_handler.h>
#include <deal.II/base/tensor.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/particles/particle_iterator.h>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <boost/math/special_functions/erf.hpp>
#include <fstream>
#include <map>
#include <regex>
#include <string>
#include <tuple>
#include <vector>
Classes
class statistics
struct cell_comparison< dim >
struct particle_comparison< dim >
struct cut_cell_comparison< dim >
Functions
void add_statistics_to_table_handler (const std::string &variable, const statistics &stats, TableHandler &table)
template<typename T >
TableHandler make_table_scalars_vectors (const std::vector< T > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< double > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation=false)
template<int dim, typename T >
TableHandler make_table_scalars_tensors (const std::vector< T > &independent_values, const std::string &independent_column_name, const std::vector< Tensor< 1, dim > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation=false)
template<int dim, typename T >
TableHandler make_table_scalars_tensors (const std::vector< T > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, dim > > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation=false)
template<int dim>
TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, dim > > &independent_vector, const std::vector< std::string > &independent_column_names, const std::vector< Tensor< 1, dim > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation=false)
template<int dim>
TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, dim > > &independent_vector, const std::vector< std::string > &independent_column_names, const std::vector< double > &dependent_values, const std::string &dependent_column_name, const unsigned int display_precision, const bool display_scientific_notation=false)
double calculate_point_property (const double phase, const double property0, const double property1)
template<typename T >
constexpr int sgn (const T val) noexcept
template<typename T >
T clip (const T &n, const T &lower, const T &upper)
double calculate_point_property_cahn_hilliard (const double phase_cahn_hilliard, const double property0, const double property1)
void fill_table_from_file (TableHandler &table, const std::string &file_name, const std::string &delimiter=" ")
void fill_vectors_from_file (std::map< std::string, std::vector< double > > &map, const std::string &file_name, const std::string &delimiter=" ")
void fill_string_vectors_from_file (std::map< std::string, std::vector< std::string > > &map, const std::string &file_name, const std::string &delimiter=" ")
void create_output_folder (const std::string &dirname)
void delete_output_folder (const std::string &dirname)
void announce_string (const ConditionalOStream &pcout, const std::string &expression, const char delimiter='-')
void announce_string (const ConditionalOStream &pcout, const std::string &expression, const unsigned int banner_size, const char delimiter='-')
void serialize_table (const TableHandler &table, const std::string &filename, const MPI_Comm &mpi_communicator, const bool serialize_on_rank_zero=true)
void deserialize_table (TableHandler &table, const std::string &filename, const MPI_Comm &mpi_communicator, const bool deserialize_on_rank_zero=true)
void serialize_tables_vector (const std::vector< OutputStructTableHandler > &table_output_structs, const MPI_Comm mpi_communicator)
void deserialize_tables_vector (std::vector< OutputStructTableHandler > &table_output_structs, const MPI_Comm mpi_communicator)
std::string get_last_value_of_parameter (const std::string &file_name, const std::string &parameter_name)
unsigned int get_dimension (const std::string &file_name)
int get_max_subsection_size (const std::string &file_name)
template<int spacedim>
Tensor< 1, spacedim > value_string_to_tensor (const std::string &value_string)
template<int spacedim>
Tensor< 1, spacedim > value_string_to_tensor (const std::string &value_string_0, const double &value_1, const double &value_2=0)
template<int dim>
double compute_cell_diameter (const double cell_measure, const unsigned int fe_degree)
double compute_cell_measure_with_JxW (const std::vector< double > &JxW_values)
template<int dim>
double identify_minimum_cell_size (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const Quadrature< dim > &cell_quadrature, const MPI_Comm &mpi_communicator)
double get_penalty_factor (const unsigned int fe_degree, const double cell_extent_here, const double cell_extent_there)
template<typename key , typename val >
std::vector< key > extract_keys_from_map (const std::map< key, val > &map)
template<typename key , typename val >
std::vector< val > extract_values_from_map (const std::map< key, val > &map)
std::string concatenate_strings (const int argc, char **argv)
void print_version_info (const ConditionalOStream &pcout)
std::tuple< std::map< std::string, bool >, std::vector< std::string > > parse_args (int argc, char **argv)
void print_parameters_to_output_file (const ConditionalOStream &pcout, const ParameterHandler &prm, const std::string &file_name)
void interpret_escape_sequences (std::string &s)
void print_comment_to_output_file (const ConditionalOStream &pcout, ParameterHandler &prm)
void delete_vtu_and_pvd_files (const std::string &output_path)
template<int dim>
double point_to_angle (const Point< dim > &point, const Point< dim > &center_of_rotation=Point< dim >())
template<int dim>
Point< dim > radius_to_point (const double radius, const double angle_rad)
void create_random_number_container (std::vector< double > &random_container, const unsigned int number_of_elements, const double maximum_range, const unsigned int prn_seed)
template<typename T >
std::vector< T > convert_string_to_vector (const ParameterHandler &prm, const std::string &entry_string)
Function Documentation
add_statistics_to_table_handler()
void add_statistics_to_table_handler (const std::string & variable, const statistics & stats, TableHandler & table) inline
Add statistical values to a TableHandler.
This function inserts a variable name and its associated statistics (minimum, maximum, total, average) into a given TableHandler.
Parameters
[in] variable The name of the variable being recorded.
[in] stats The statistics associated with the variable.
[in,out] table Reference to the TableHandler where the values will be added.
Definition at line 87 of file utilities.h.
References statistics::average, statistics::max, statistics::min, and statistics::total.
announce_string() [1/2]
void announce_string (const ConditionalOStream & pcout, const std::string & expression, const char delimiter = '-') inline
Prints a string and then adds a line above and below made with dashes containing as many dashes as the string has characters+1.
For example, if the string to be printed is "Tracer" the result will be:
-------
Tracer
-------
Parameters
[in] pcout the parallel cout used to print the information
[in] expression string that will be printed
[in] delimiter the character used to delimit the printing. Default value is "-"
Definition at line 468 of file utilities.h.
announce_string() [2/2]
void announce_string (const ConditionalOStream & pcout, const std::string & expression, const unsigned int banner_size, const char delimiter = '-') inline
Prints an expression string surrounded from above and bottom with a lines of a specified delimiter character (by default, '-'). The length of the banner lines is the length of the string + 1 character.
Parameters
[in] pcout Parallel conditional output stream used to print the information
[in] expression Expression string that will be printed
[in] banner_size Length of the decorative banner lines
[in] delimiter Characters composing the decorative lines of the banner. By default, '-' is used.
Remarks
The overload of the function with banner_size is used for cases where the expression string is multiple lines long.
Definition at line 493 of file utilities.h.
calculate_point_property()
double calculate_point_property (const double phase, const double property0, const double property1) inline
Calculate the equivalent properties for a given phase. Method called in quadrature points loops in CLS simulations.
Parameters
phase Phase value for the given quadrature point
property0 Property value for the fluid with index 0 (fluid for phase = 0)
property1 Property value for the fluid with index 1 (fluid for phase = 1)
Definition at line 297 of file utilities.h.
References phase.
calculate_point_property_cahn_hilliard()
double calculate_point_property_cahn_hilliard (const double phase_cahn_hilliard, const double property0, const double property1) inline
Calculate the equivalent property for a given phase.
This method is called in quadrature point loops in Cahn-Hilliard simulations. It interpolates between two fluid properties based on the phase value.
Parameters
[in] phase_cahn_hilliard Phase value for the given quadrature point.
[in] property0 Property value for the fluid with index 0 (fluid for phase = -1).
[in] property1 Property value for the fluid with index 1 (fluid for phase = 1).
Returns
double Equivalent property for the given phase.
Definition at line 370 of file utilities.h.
References phase, phase_cahn_hilliard, and sgn().
clip()
template<typename T > T clip (const T & n, const T & lower, const T & upper)
Clip a property between a lower and a higher value.
Template Parameters
T argument's type
Parameters
[in,out] lower Lower admissible value
[in,out] upper Upper admissible value
[in,out] n
Returns
Clipped variable that is not below the lower limit and not above the upper limit
Definition at line 351 of file utilities.h.
compute_cell_diameter()
template<int dim> double compute_cell_diameter (const double cell_measure, const unsigned int fe_degree) inline
Computes equivalent cell diameter by comparing the area to a disk (2D) or the volume to a sphere (3D).
Template Parameters
dim Number of spatial dimensions (2D or 3D).
Parameters
[in] cell_measure Area (2D) or volume (3D) of the cell.
[in] fe_degree Polynomial degree of the shape function.
Returns
Cell diameter value.
Definition at line 753 of file utilities.h.
compute_cell_measure_with_JxW()
double compute_cell_measure_with_JxW (const std::vector< double > & JxW_values) inline
Computes the area (2D) or volume (3D) of the cell by integrating 1 over the cell, by summing JxW values (quadrature weights) returned by the FEValues object.
Template Parameters
dim Number of spatial dimensions (2D or 3D).
Parameters
[in] JxW_values Vector of mapped quadrature weights.
Returns
Area (2D) volume (3D) of the cell.
Definition at line 781 of file utilities.h.
concatenate_strings()
std::string concatenate_strings (const int argc, char ** argv)
Concatenate words which are passed from the command line to a main function into a single string in which the words are seperated by space.
Parameters
[in] argc number of arguments in C style.
[in] argv arguments themselves in C style.
Definition at line 720 of file utilities.cc.
convert_string_to_vector()
template<typename T > std::vector< T > convert_string_to_vector (const ParameterHandler & prm, const std::string & entry_string)
Return the vector of size N of entry @entry_string. If the entry is specified in the .prm file, then the changed value is returned, otherwise the default value is returned. If the entry is not equivalent to a vector, an error will be thrown.
Template Parameters
T The type of vector (int, unsigned int or double)
Parameters
[in] prm A parameter handler which is currently used to parse the simulation information.
[in] entry_string A declare string in the parameter file.
Returns
A std::vector<double> corresponding to the entry_string in the prm file.
Definition at line 1062 of file utilities.h.
create_output_folder()
void create_output_folder (const std::string & dirname)
Creates the simulation output folder.
Parameters
[in] dirname Output directory name
Definition at line 365 of file utilities.cc.
create_random_number_container()
void create_random_number_container (std::vector< double > & random_container, const unsigned int number_of_elements, const double maximum_range, const unsigned int prn_seed) inline
Creates a vector of random doubles between 0 and a maximum value using a pseudo random seed.
Parameters
[in,out] random_container Container in which the doubles are stored.
[in] number_of_elements Number of random doubles to generate.
[in] maximum_range Maximum value that the random double can have.
[in] prn_seed Pseudo random seed used to generate the random doubles.
Definition at line 1034 of file utilities.h.
delete_output_folder()
void delete_output_folder (const std::string & dirname)
Delete the output folder and its content.
Parameters
[in] dirname Output directory name.
Definition at line 371 of file utilities.cc.
delete_vtu_and_pvd_files()
void delete_vtu_and_pvd_files (const std::string & output_path)
Delete vtu and pvd files.
Definition at line 860 of file utilities.cc.
deserialize_table()
void deserialize_table (TableHandler & table, const std::string & filename, const MPI_Comm & mpi_communicator, const bool deserialize_on_rank_zero = true) inline
Loads a TableHandler from a file using Boost serialization.
The filename should include the desired extension.
Parameters
[in,out] table The table to be deserialized (will be overwritten).
[in] filename Path to the file (including extension) to read the table from.
[in] mpi_communicator The MPI communicator
[in] deserialize_on_rank_zero Boolean indicating if the table should only be deserialized on rank 0 only. By default, it is set to true.
Definition at line 544 of file utilities.h.
deserialize_tables_vector()
void deserialize_tables_vector (std::vector< OutputStructTableHandler > & table_output_structs, const MPI_Comm mpi_communicator) inline
Deserializes all the TableHandler objects in table_output_structs.
Parameters
[in,out] table_output_structs Vector of structures containing references to TableHandler objects that needs to be serialized/deserialized for a given solver, and their corresponding file names.
[in] mpi_communicator The MPI communicator
Definition at line 592 of file utilities.h.
References deserialize_table().
extract_keys_from_map()
template<typename key , typename val > std::vector< key > extract_keys_from_map (const std::map< key, val > & map)
Extract the keys from map object.
Template Parameters
key Key of the map
val Value of the map. This template parameter is not used.
Parameters
[in] map Map object from which the keys are extracted
Returns
keys Vector of keys from the map
Definition at line 882 of file utilities.h.
extract_values_from_map()
template<typename key , typename val > std::vector< val > extract_values_from_map (const std::map< key, val > & map)
Extract the values from map object.
Template Parameters
key Key of the map. This template parameter is not used.
val Value of the map.
Parameters
[in] map Map object from which the keys are extracted
Returns
values Vector of values from the map
Definition at line 901 of file utilities.h.
fill_string_vectors_from_file()
void fill_string_vectors_from_file (std::map< std::string, std::vector< std::string > > & map, const std::string & file_name, const std::string & delimiter = " ")
Function that read a file that was build from a dealii table and create a map with the key being the column name and the variable the vectors of data.
Parameters
[in,out] map A map used to store the data based on column names.
[in] file_name Path to the file to read the table from.
[in] delimiter Delimiter used in the file to separate values. Default is a space (" ").
Definition at line 316 of file utilities.cc.
fill_table_from_file()
void fill_table_from_file (TableHandler & table, const std::string & file_name, const std::string & delimiter = " ")
Reads a file generated by a deal.II TableHandler and fills a TableHandler with its data.
This function reads a table from a file and populates the given TableHandler. Warning: If the table already contains data, it will be erased.
Parameters
[in,out] table The table to be filled. Existing content will be overwritten.
[in] file_name Path to the file to read the table from.
[in] delimiter Delimiter used in the file to separate values. Default is a space (" ").
Definition at line 217 of file utilities.cc.
fill_vectors_from_file()
void fill_vectors_from_file (std::map< std::string, std::vector< double > > & map, const std::string & file_name, const std::string & delimiter = " ")
function that read a file that was build from a dealii table and fill 2 vectors. The first vector contains all the columns names and the second one contained all the column data.
Parameters
[in,out] map A map used to store the data based on column names.
[in] file_name Path to the file to read the table from.
[in] delimiter Delimiter used in the file to separate values. Default is a space (" ").
Definition at line 263 of file utilities.cc.
get_dimension()
unsigned int get_dimension (const std::string & file_name)
Extract the dimension in which to run Lethe from the contents of the parameter file. This is something that we need to do before processing the parameter file since we need to know whether to use the dim=2 or dim=3 instantiation of the main classes.
Parameters
file_name[in] The file name from which dimension is read
Definition at line 632 of file utilities.cc.
References get_last_value_of_parameter().
get_last_value_of_parameter()
std::string get_last_value_of_parameter (const std::string & file_name, const std::string & parameter_name)
Retrieves the value of a specific parameter from an input file. Returns an empty string if the parameter is not found. This function is adapted from ASPECT and is mainly used to parse the dimension of the problem before creating the full parameter parser.
Parameters
[in] file_name File from which we retrieve the parameter.
[in] parameter_name Name of the parameter to retrieve.
Returns
std::string Value of the parameter, or an empty string if not found.
Definition at line 549 of file utilities.cc.
get_max_subsection_size()
int get_max_subsection_size (const std::string & file_name)
Extract the maximum value between the number of boundary conditions and the number of manifolds from the file. This value is linked to the "number" string defined in the simulation parameter file. It provides an estimate for the amount of parameters or manifolds and is used to determine the size of the vectors that will store boundary conditions and manifold data. This feature will need to be monitored extensively in the future.
Parameters
[in] file_name The file name from which the number of boundary conditions is read
Returns
The maximum number of boundary conditions or manifolds.
Definition at line 698 of file utilities.cc.
References get_max_value_of_parameter().
get_penalty_factor()
double get_penalty_factor (const unsigned int fe_degree, const double cell_extent_here, const double cell_extent_there) inline
Calculate the penalty factor for the SIPG method for the case when two cells are of different sizes. A harmonic mean is used to calculate an average cell extent.
Parameters
[in] fe_degree Finite element degree.
[in] cell_extent_here Distance of the here cell. The ratio between the volume of the cell and the area of the face is generally used as a metric for this distance.
[in] cell_extent_there Distance of the there cell. The ratio between the volume of the cell and the area of the face is generally used as a metric for this distance.
Returns
double
Definition at line 863 of file utilities.h.
identify_minimum_cell_size()
template<int dim> double identify_minimum_cell_size (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const Quadrature< dim > & cell_quadrature, const MPI_Comm & mpi_communicator) inline
Identify minimum cell size. The cell size corresponds to the diameter of a disk (2D) or sphere (3D) of equivalent area (2D) or volume (3D).
Template Parameters
dim Number of spatial dimensions (2D or 3D).
Parameters
[in] mapping Interface for transformation from the reference (unit) cell to the real cell.
[in] dof_handler Describes the layout of DoFs and the type of FE.
[in] cell_quadrature Local cell quadrature information.
[in] mpi_communicator Allows communication between cores.
Returns
Smallest cell size value.
Definition at line 808 of file utilities.h.
References compute_cell_measure_with_JxW().
interpret_escape_sequences()
void interpret_escape_sequences (std::string & s)
Identify escape sequences listed below and apply them to the string.
"\n": Newline
"\t": Horizontal tab
"\r": Carriage return
"\b": Backspace
"\v": Vertical tab
Parameters
[in,out] s String to be modified if escape sequences are specified.
Definition at line 835 of file utilities.cc.
make_table_scalars_tensors() [1/2]
template<int dim, typename T > TableHandler make_table_scalars_tensors (const std::vector< T > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, dim > > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of scalar (independent variable) and a vector of vectors of Tensor<1,dim> (dependent variables).
Template Parameters
T Scalar type of independent variables.
dim Integer that denotes the number of spatial dimensions.
Parameters
[in] independent_values Vector of scalar values that serve as the independent variable (e.g., time).
[in] independent_column_name Label of the independent variable.
[in] dependent_vector Vector of vectors of Tensor<1,dim> containing dependent variables values (e.g., force).
[in] dependent_column_names Vector of strings representing the labels of dependent variables.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variable values followed by the dependent variables values.
Definition at line 90 of file utilities.cc.
make_table_scalars_tensors() [2/2]
template<int dim, typename T > TableHandler make_table_scalars_tensors (const std::vector< T > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, dim > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of scalars (independent variable) and a vector of Tensor<1,dim> (dependent variables).
Template Parameters
T Scalar type of independent variables.
dim Integer that denotes the number of spatial dimensions.
Parameters
[in] independent_values Vector of scalar values that serve as the independent variable (e.g., time).
[in] independent_column_name Label of the independent variable.
[in] dependent_vector Vector of Tensor<1,dim> containing dependent variables values (e.g., force).
[in] dependent_column_names Vector of strings representing the labels of dependent variables.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variable values followed by the dependent variables values.
Definition at line 51 of file utilities.cc.
make_table_scalars_vectors()
template<typename T > TableHandler make_table_scalars_vectors (const std::vector< T > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< double > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of scalars (independent variable) and a vector of vectors of scalars (dependent variables).
Template Parameters
T Scalar type of independent variables.
Parameters
[in] independent_values Vector of scalar values that serve as the independent variable (e.g., time).
[in] independent_column_name Label of the independent variable.
[in] dependent_vector Vector of vectors of scalar values containing dependant variables values.
[in] dependent_column_names Vector of strings representing the labels of dependent variables.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variable values followed by the dependent variables values.
Definition at line 16 of file utilities.cc.
make_table_tensors_scalars()
template<int dim> TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, dim > > & independent_vector, const std::vector< std::string > & independent_column_names, const std::vector< double > & dependent_values, const std::string & dependent_column_name, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of Tensor<1,dim> (independent variables) and a vector of scalars (dependent variable).
Template Parameters
dim Integer that denotes the number of spatial dimensions.
Parameters
[in] independent_vector Vector of Tensor<1,dim> that serves as the independent variable (e.g., position).
[in] independent_column_names Vector of strings representing labels of the independent tensor.
[in] dependent_values Vector of doubles containing dependent variables values (e.g., force).
[in] dependent_column_name Label of the dependent variable.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variables values followed by the dependent variable values.
Definition at line 181 of file utilities.cc.
make_table_tensors_tensors()
template<int dim> TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, dim > > & independent_vector, const std::vector< std::string > & independent_column_names, const std::vector< Tensor< 1, dim > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of Tensor<1,dim> (independent variables) and a vector of Tensor<1,dim> (dependent variables).
Template Parameters
dim Integer that denotes the number of spatial dimensions.
Parameters
[in] independent_vector Vector of Tensor<1,dim> that serves as the independent variable (e.g., position).
[in] independent_column_names Vector of strings representing labels of the independent tensor.
[in] dependent_vector Vector of vectors of Tensor<1,dim> containing dependent variables values (e.g., force).
[in] dependent_column_names Vector of strings representing the labels of dependent variables.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variables values followed by the dependent variables values.
Definition at line 139 of file utilities.cc.
parse_args()
std::tuple< std::map< std::string, bool >, std::vector< std::string > > parse_args (int argc, char ** argv)
Parse the arguments given to the application.
Parameters
[in] argc Number of arguments
[in] argv Array of strings representing the arguments
Returns
Tuple containing a map with the command line flags and a boolean set to 1 for the specific flag; and a vector of strings with the rest of the arguments that are not flags; in Lethe, this corresponds to the parameter file given to the application.
Definition at line 762 of file utilities.cc.
point_to_angle()
template<int dim> double point_to_angle (const Point< dim > & point, const Point< dim > & center_of_rotation = Point<dim>()) inline
Converts point to angle (in radians)
Parameters
[in] point Point in cartesian coordinates (x-y plane)
[in] center_of_rotation Center of rotation
Returns
Angle between point and the x-axis
Definition at line 995 of file utilities.h.
print_comment_to_output_file()
void print_comment_to_output_file (const ConditionalOStream & pcout, ParameterHandler & prm)
Print a user comment at the beginning of the simulation on the console output.
Parameters
[in] pcout Parallel console output stream.
[in,out] prm ParameterHandler. specified.
Definition at line 845 of file utilities.cc.
References interpret_escape_sequences().
print_parameters_to_output_file()
void print_parameters_to_output_file (const ConditionalOStream & pcout, const ParameterHandler & prm, const std::string & file_name)
Print the parameters given by the parameter file of the application.
Parameters
[in] pcout Parallel output stream
[in] prm Object containing the parameters parsed from the parameter file.
[in] file_name File name where the parameters will be written.
[in] pcout Parallel output stream
[in] prm Object containing the parameters parsed from the parameter file
Definition at line 808 of file utilities.cc.
References get_last_value_of_parameter().
print_version_info()
void print_version_info (const ConditionalOStream & pcout)
Print the information of the deal.II and Lethe branches used to run an application in the "git describe" format.
Parameters
[in] pcout Parallel output stream
Definition at line 737 of file utilities.cc.
radius_to_point()
template<int dim> Point< dim > radius_to_point (const double radius, const double angle_rad) inline
Converts radius to point in cartesian coordinates (in the x-y plane)
Parameters
[in] radius Radial distance
[in] angle_rad Angle (in radians)
Returns
point Point cartesian coordinates
Definition at line 1013 of file utilities.h.
serialize_table()
void serialize_table (const TableHandler & table, const std::string & filename, const MPI_Comm & mpi_communicator, const bool serialize_on_rank_zero = true) inline
Serializes a TableHandler to a file using Boost serialization.
The filename should include the desired extension.
Parameters
[in] table The table to be serialized.
[in] filename Path to the file (including extension) where the table will be saved.
[in] mpi_communicator The MPI communicator
[in] serialize_on_rank_zero Boolean indicating if the table should only be serialized on rank 0 only. By default, it is set to true.
Definition at line 515 of file utilities.h.
serialize_tables_vector()
void serialize_tables_vector (const std::vector< OutputStructTableHandler > & table_output_structs, const MPI_Comm mpi_communicator) inline
Serializes all the TableHandler objects in table_output_structs.
Parameters
[in] table_output_structs Vector of structures containing references to TableHandler objects that need to be serialized/deserialized for a given solver, and their corresponding file names.
[in] mpi_communicator The MPI communicator
Definition at line 570 of file utilities.h.
References serialize_table().
sgn()
template<typename T > constexpr int sgn (const T val) constexpr noexcept
Retrieve the sign of a value.
Used in calculate_point_property_cahn_hilliard to determine the sign of the phase parameter.
Template Parameters
T The argument's type (must support comparison with zero).
Parameters
[in] val Value of the variable for which the sign is evaluated.
Return values
-1 if the value is negative.
+1 if the value is positive.
0 if the value is zero.
Definition at line 334 of file utilities.h.
value_string_to_tensor() [1/2]
template<int spacedim> Tensor< 1, spacedim > value_string_to_tensor (const std::string & value_string) inline
Return the tensor corresponding to the value_string. If the dimension correspondence of the value_string is not equivalent to spacedim (either 2 or 3), an exception will be thrown. The delimiter separating the elements of the value_string is a comma (",").
Remarks
The function is used to construct Point<spacedim> objects.
Template Parameters
spacedim Number of spatial dimensions (2D or 3D).
Parameters
[in] value_string A string in the parameter file corresponding to a given tensor.
Returns
A Tensor<1,spacedim> corresponding to the value_string in the parameter file.
Definition at line 665 of file utilities.h.
value_string_to_tensor() [2/2]
template<int spacedim> Tensor< 1, spacedim > value_string_to_tensor (const std::string & value_string_0, const double & value_1, const double & value_2 = 0) inline
Return the tensor corresponding to the value_string_0, but it can also allow the usage of deprecated parameters that used to be 3 individual entries instead of a list of values. In the case of a single entry declaration, the delimiter separating the elements of the value_string_0 is a comma (",").
Remarks
The function is used to construct Point<spacedim> objects.
Template Parameters
spacedim Number of spatial dimensions (2D or 3D).
Parameters
[in] value_string_0 A string in the parameter file corresponding to the first component of the tensor or to the tensor itself.
[in] value_1 A double in the parameter file corresponding to the second component of the tensor.
[in] value_2 A double in the parameter file corresponding to the third component of the tensor. Only specify if spacedim = 3.
Returns
A Tensor<1,spacedim> corresponding to the input parameters in the parameter file.
Definition at line 707 of file utilities.h.