Lethe Open-Source Library: /home/runner/work/lethe/lethe/include/core/grids.h File Reference
grids.h File Reference
#include <core/boundary_conditions.h>
#include <core/manifolds.h>
#include <core/parameters.h>
#include <deal.II/distributed/tria_base.h>
Functions
template<int dim, int spacedim = dim>
void attach_grid_to_triangulation (Triangulation< dim, spacedim > &triangulation, const Parameters::Mesh &mesh_parameters)
template<int dim, int spacedim = dim>
void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const BoundaryConditions::BoundaryConditions &boundary_conditions)
template<int dim, int spacedim = dim>
void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const Parameters::Mesh &mesh_parameters, const Parameters::Manifolds &manifolds_parameters, bool restart, const BoundaryConditions::BoundaryConditions &boundary_conditions)
template<int dim, int spacedim = dim>
void read_mesh_and_manifolds_for_stator_and_rotor (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const Parameters::Mesh &mesh_parameters, const Parameters::Manifolds &manifolds_parameters, bool restart, const BoundaryConditions::BoundaryConditions &boundary_conditions, const Parameters::Mortar< dim > &mortar_parameters)
template<int dim, int spacedim = dim>
void refine_triangulation_at_boundaries (const std::vector< int > boundary_ids, const unsigned int n_refinement, parallel::DistributedTriangulationBase< dim, spacedim > &triangulation)
template<int dim, int spacedim = dim>
void apply_mesh_transformation (const Parameters::Mesh &mesh_parameters, Triangulation< dim, spacedim > &triangulation)
Function Documentation
apply_mesh_transformation()
template<int dim, int spacedim = dim> void apply_mesh_transformation (const Parameters::Mesh & mesh_parameters, Triangulation< dim, spacedim > & triangulation)
Apply scaling, translation and rotation to the mesh in the listed order.
Template Parameters
dim An integer that denotes the dimensionality of the geometry.
spacedim An integer that denotes the dimension of the space occupied by the embedded geometry.
Parameters
[in] mesh_parameters Parameters of the mesh.
[in,out] triangulation Triangulation object on which the mesh transformations are applied.
Definition at line 559 of file grids.cc.
References Parameters::Mesh::rotation_angle, Parameters::Mesh::rotation_axis, Parameters::Mesh::scale, and Parameters::Mesh::translation.
attach_grid_to_triangulation()
template<int dim, int spacedim = dim> void attach_grid_to_triangulation (Triangulation< dim, spacedim > & triangulation, const Parameters::Mesh & mesh_parameters)
Attaches a grid to a triangulation using mesh parameters.
Parameters
[in,out] triangulation The triangulation to which a grid is attached
[in] mesh_parameters The mesh parameters used to decide what type of mesh or primitive is used
Definition at line 24 of file grids.cc.
References apply_mesh_transformation(), Parameters::Mesh::dealii, Parameters::Mesh::file_name, Parameters::Mesh::gmsh, Parameters::Mesh::grid_arguments, Parameters::Mesh::grid_type, Parameters::Mesh::initial_refinement, Parameters::Mesh::lethe, FicheraOvenGrid< dim, spacedim >::make_grid(), BirminghamFluidizedBedGrid< dim, spacedim >::make_grid(), PeriodicHillsGrid< dim, spacedim >::make_grid(), UniformChannelWithMeshedCylinderGrid< dim, spacedim >::make_grid(), Parameters::Mesh::scale, Parameters::Mesh::simplex, and Parameters::Mesh::type.
read_mesh_and_manifolds()
template<int dim, int spacedim = dim> void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const Parameters::Mesh & mesh_parameters, const Parameters::Manifolds & manifolds_parameters, bool restart, const BoundaryConditions::BoundaryConditions & boundary_conditions)
Completely sets up a mesh and its manifolds.
This function reads and constructs a mesh according to the given mesh parameters, sets up manifolds on boundaries, and applies boundary conditions. It is intended for distributed triangulations.
Template Parameters
dim The topological dimension of the mesh.
spacedim The embedding space dimension (default = dim).
Parameters
[in,out] triangulation The triangulation to which the grid will be attached.
[in] mesh_parameters Parameters defining the mesh or primitive to use.
[in] manifolds_parameters Information about the manifolds attached to boundaries.
[in] restart Flag indicating whether this is a restart.
[in] boundary_conditions Boundary condition information, used for periodicity.
Definition at line 254 of file grids.cc.
References attach_grid_to_triangulation(), attach_manifolds_to_triangulation(), Parameters::Mesh::boundaries_to_refine, Parameters::Mesh::gmsh, Parameters::Manifolds::id, Parameters::Mesh::initial_refinement, Parameters::Mesh::initial_refinement_at_boundaries, refine_triangulation_at_boundaries(), Parameters::Mesh::refine_until_target_size, setup_periodic_boundary_conditions(), Parameters::Mesh::simplex, Parameters::Manifolds::size, Parameters::Mesh::target_size, and Parameters::Mesh::type.
read_mesh_and_manifolds_for_stator_and_rotor()
template<int dim, int spacedim = dim> void read_mesh_and_manifolds_for_stator_and_rotor (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const Parameters::Mesh & mesh_parameters, const Parameters::Manifolds & manifolds_parameters, bool restart, const BoundaryConditions::BoundaryConditions & boundary_conditions, const Parameters::Mortar< dim > & mortar_parameters)
Completely sets up a mesh and its manifolds for rotor-stator domains.
The triangulation initially contains the stator triangulation, which is later replaced by the merged rotor-stator triangulation.
Template Parameters
dim The topological dimension of the mesh.
spacedim The embedding space dimension (default = dim).
Parameters
[in,out] triangulation The triangulation to which the grid will be attached.
[in] mesh_parameters Parameters defining the mesh or primitive to use.
[in] manifolds_parameters Information about the manifolds attached to boundaries.
[in] restart Flag indicating whether this is a restart.
[in] boundary_conditions Boundary condition information, used for periodicity.
[in] mortar_parameters Parameters controlling the mortar method, including rotor mesh info.
Definition at line 332 of file grids.cc.
References attach_grid_to_triangulation(), attach_manifolds_to_triangulation(), Parameters::Mesh::boundaries_to_refine, Parameters::Mesh::dealii, Parameters::Mesh::gmsh, Parameters::Manifolds::id, Parameters::Mesh::initial_refinement, Parameters::Mesh::initial_refinement_at_boundaries, Parameters::Mortar< dim >::interface_type, refine_triangulation_at_boundaries(), Parameters::Mesh::refine_until_target_size, Parameters::Mortar< dim >::rotor_boundary_id, Parameters::Mortar< dim >::rotor_mesh, setup_periodic_boundary_conditions(), Parameters::Mesh::simplex, Parameters::Manifolds::size, Parameters::Mortar< dim >::stator_boundary_id, Parameters::Mesh::target_size, and Parameters::Mesh::type.
refine_triangulation_at_boundaries()
template<int dim, int spacedim = dim> void refine_triangulation_at_boundaries (const std::vector< int > boundary_ids, const unsigned int n_refinement, parallel::DistributedTriangulationBase< dim, spacedim > & triangulation)
Refine a mesh around specific boundary ids.
Parameters
[in] n_refinement The number of times the boundary should be refined
[in] boundary_ids The boundary ids for which the cells should be refined
[in,out] triangulation The triangulation on which refinement must be carried out
Definition at line 117 of file grids.h.
setup_periodic_boundary_conditions()
template<int dim, int spacedim = dim> void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const BoundaryConditions::BoundaryConditions & boundary_conditions)
Modifies the triangulation to set up periodic boundary conditions in the case of CFD simulations.
Parameters
[in,out] triangulation The triangulation to which a grid is attached
[in] boundary_conditions The information about the boundary conditions id. This is used to set up the periodicity of the domain
Definition at line 226 of file grids.cc.
References BoundaryConditions::periodic, BoundaryConditions::BoundaryConditions::periodic_direction, BoundaryConditions::BoundaryConditions::periodic_neighbor_id, and BoundaryConditions::BoundaryConditions::type.