Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/dem/lagrangian_post_processing.cc File Reference
lagrangian_post_processing.cc File Reference
#include <core/solutions_output.h>
#include <dem/lagrangian_post_processing.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/lac/block_vector.h>
#include <deal.II/numerics/data_out.h>
#include <fstream>
Functions
template<int dim>
void calculate_average_particles_velocity (const parallel::distributed::Triangulation< dim > &triangulation, const Particles::ParticleHandler< dim > &particle_handler, Vector< double > &velocity_average_x, Vector< double > &velocity_average_y, Vector< double > &velocity_average_z, Vector< double > &velocity_average_magnitude)
template<int dim>
void calculate_average_granular_temperature (const parallel::distributed::Triangulation< dim > &triangulation, const Particles::ParticleHandler< dim > &particle_handler, Vector< double > &granular_temperature_average)
template<int dim>
Tensor< 1, dim > calculate_cell_average_particles_velocity (const typename parallel::distributed::Triangulation< dim >::cell_iterator &cell, const Particles::ParticleHandler< dim > &particle_handler)
template<int dim>
void write_post_processing_results (const parallel::distributed::Triangulation< dim > &triangulation, PVDHandler &grid_pvdhandler, const DoFHandler< dim > &background_dh, const Particles::ParticleHandler< dim > &particle_handler, const DEMSolverParameters< dim > &dem_parameters, const double current_time, const unsigned int step_number, const MPI_Comm &mpi_communicator, AdaptiveSparseContacts< dim > &sparse_contacts_object)
template void write_post_processing_results< 2 > (const parallel::distributed::Triangulation< 2 > &triangulation, PVDHandler &grid_pvdhandler, const DoFHandler< 2 > &background_dh, const Particles::ParticleHandler< 2 > &particle_handler, const DEMSolverParameters< 2 > &dem_parameters, const double current_time, const unsigned int step_number, const MPI_Comm &mpi_communicator, AdaptiveSparseContacts< 2 > &sparse_contacts_object)
template void write_post_processing_results< 3 > (const parallel::distributed::Triangulation< 3 > &triangulation, PVDHandler &grid_pvdhandler, const DoFHandler< 3 > &background_dh, const Particles::ParticleHandler< 3 > &particle_handler, const DEMSolverParameters< 3 > &dem_parameters, const double current_time, const unsigned int step_number, const MPI_Comm &mpi_communicator, AdaptiveSparseContacts< 3 > &sparse_contacts_object)
Function Documentation
calculate_average_granular_temperature()
template<int dim> void calculate_average_granular_temperature (const parallel::distributed::Triangulation< dim > & triangulation, const Particles::ParticleHandler< dim > & particle_handler, Vector< double > & granular_temperature_average)
Carries out the calculation of the granular temperature in each local cell. These values are summed up during the post-processing steps (imposed by post-processing frequency), and finally divided by the sampling counter to calculate time-averaged granular temperature distribution.
Parameters
triangulation Triangulation.
particle_handler Particle handler.
granular_temperature_average Average granular temperature.
Definition at line 61 of file lagrangian_post_processing.cc.
References calculate_cell_average_particles_velocity(), and DEM::v_x.
calculate_average_particles_velocity()
template<int dim> void calculate_average_particles_velocity (const parallel::distributed::Triangulation< dim > & triangulation, const Particles::ParticleHandler< dim > & particle_handler, Vector< double > & velocity_average_x, Vector< double > & velocity_average_y, Vector< double > & velocity_average_z, Vector< double > & velocity_average_magnitude)
Carries out the calculation of the average particles velocity in each local cell. These values are summed up during the post-processing steps (imposed by post-processing frequency), and finally divided by the sampling counter to calculate time-averaged particles velocity distribution.
Parameters
triangulation Triangulation.
particle_handler Particle handler.
velocity_average_x Average velocity in x-direction.
velocity_average_y Average velocity in y-direction.
velocity_average_z Average velocity in z-direction.
velocity_average_magnitude Average velocity magnitude.
Definition at line 20 of file lagrangian_post_processing.cc.
References calculate_cell_average_particles_velocity().
calculate_cell_average_particles_velocity()
template<int dim> Tensor<1, dim> calculate_cell_average_particles_velocity (const typename parallel::distributed::Triangulation< dim >::cell_iterator & cell, const Particles::ParticleHandler< dim > & particle_handler)
Carries out the calculation of average particles velocity for a single cell. It is defined as a separate private function since the calculate_average_granular_temperature function also needs to obtain the average velocity in the cell.
Parameters
cell A single cell in the triangulation
particle_handler
Returns
A tensor which stores the average particles velocity in the input cell
Definition at line 131 of file lagrangian_post_processing.cc.
References DEM::v_x.
write_post_processing_results()
template<int dim> void write_post_processing_results (const parallel::distributed::Triangulation< dim > & triangulation, PVDHandler & grid_pvdhandler, const DoFHandler< dim > & background_dh, const Particles::ParticleHandler< dim > & particle_handler, const DEMSolverParameters< dim > & dem_parameters, const double current_time, const unsigned int step_number, const MPI_Comm & mpi_communicator, AdaptiveSparseContacts< dim > & sparse_contacts_object)
Carries out writing the cell data of the domain.
This class deals with Lagrangian post-processing. At the moment, calculation of time-averaged particles velocity and granular temperature are added to the class.
Todo:
Add tracer particles
Parameters
triangulation Triangulation of the domain.
grid_pvdhandler PVD handler for grid.
background_dh Background DoF handler.
particle_handler Particle handler.
dem_parameters DEM parameters.
current_time Simulation time.
step_number DEM step number.
mpi_communicator MPI communicator.
sparse_contacts_object Àdaptive sparse contacts object.
Definition at line 174 of file lagrangian_post_processing.cc.
References AdaptiveSparseContacts< dim >::get_mobility_status_vector(), Parameters::SimulationControl::group_files, Parameters::SimulationControl::output_folder, Parameters::SimulationControl::output_name, and DEMSolverParameters< dim >::simulation_control.
write_post_processing_results< 2 >()
template void write_post_processing_results< 2 > (const parallel::distributed::Triangulation< 2 > & triangulation, PVDHandler & grid_pvdhandler, const DoFHandler< 2 > & background_dh, const Particles::ParticleHandler< 2 > & particle_handler, const DEMSolverParameters< 2 > & dem_parameters, const double current_time, const unsigned int step_number, const MPI_Comm & mpi_communicator, AdaptiveSparseContacts< 2 > & sparse_contacts_object)
write_post_processing_results< 3 >()
template void write_post_processing_results< 3 > (const parallel::distributed::Triangulation< 3 > & triangulation, PVDHandler & grid_pvdhandler, const DoFHandler< 3 > & background_dh, const Particles::ParticleHandler< 3 > & particle_handler, const DEMSolverParameters< 3 > & dem_parameters, const double current_time, const unsigned int step_number, const MPI_Comm & mpi_communicator, AdaptiveSparseContacts< 3 > & sparse_contacts_object)