Lethe Open-Source Library: /home/runner/work/lethe/lethe/include/dem/log_collision_data.h File Reference
log_collision_data.h File Reference
#include <core/tensors_and_points_dimension_manipulation.h>
#include <dem/dem_contact_manager.h>
#include <deal.II/base/tensor.h>
#include <deal.II/base/types.h>
Classes
struct collision_log< dim >
struct collision_event< dim >
class OngoingCollisionLog< dim >
class CompletedCollisionLog< dim >
Functions
template<int dim>
Point< 3 > get_location (const Particles::ParticleIterator< dim > &particle)
Tensor< 1, 3 > find_projection (const Tensor< 1, 3 > &vector_a, const Tensor< 1, 3 > &vector_b)
template<int dim, typename PropertiesIndex >
void log_collision_data (const DEMSolverParameters< dim > &parameters, typename DEM::dem_data_structures< dim >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< dim > &ongoing_collision_log, CompletedCollisionLog< dim > &collision_event_log)
template<int dim>
void write_collision_stats (const DEMSolverParameters< dim > &parameters, const CompletedCollisionLog< dim > &collision_event_log, const MPI_Comm &mpi_communicator)
Function Documentation
find_projection()
Tensor< 1, 3 > find_projection (const Tensor< 1, 3 > & vector_a, const Tensor< 1, 3 > & vector_b) inline
This function is used to find the projection of vector_a on vector_b.
Parameters
[in] vector_a A vector which is going to be projected on vector_b
[in] vector_b The projection vector of vector_a
Returns
The projection of vector_a on vector_b
Definition at line 156 of file log_collision_data.h.
get_location()
template<int dim> Point< 3 > get_location (const Particles::ParticleIterator< dim > & particle) inline
Get the 3d location of the particle.
Parameters
[in] particle The particle to get the location from.
Returns
3d location of particle.
Definition at line 139 of file log_collision_data.h.
References point_nd_to_3d().
log_collision_data()
template<int dim, typename PropertiesIndex > void log_collision_data (const DEMSolverParameters< dim > & parameters, typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< dim > & ongoing_collision_log, CompletedCollisionLog< dim > & collision_event_log)
Logs the particle-wall contact statistics.
Parameters
[in] parameters Parameters
[in] particle_wall_pairs_in_contact Required information for the calculation of the particle-wall contact.
[in] current_time Current simulation time.
[out] ongoing_collision_log Ongoing collision log.
[out] collision_event_log Collision event log.
Definition at line 12 of file log_collision_data.cc.
References CompletedCollisionLog< dim >::add_event(), collision_log< dim >::boundary_id, Parameters::Lagrangian::LagrangianPostProcessing::collision_verbosity, collision_log< dim >::dp, OngoingCollisionLog< dim >::end_collision(), find_projection(), get_location(), OngoingCollisionLog< dim >::is_in_collision(), Parameters::Lagrangian::LagrangianPostProcessing::log_collisions_with_all_walls, collision_log< dim >::mass, collision_log< dim >::omega, collision_log< dim >::particle_id, collision_event< dim >::particle_id, Parameters::Lagrangian::LagrangianPostProcessing::particle_wall_collision_boundary_ids, DEMSolverParameters< dim >::post_processing, OngoingCollisionLog< dim >::start_collision(), collision_log< dim >::time, collision_log< dim >::velocity, and Parameters::verbose.
write_collision_stats()
template<int dim> void write_collision_stats (const DEMSolverParameters< dim > & parameters, const CompletedCollisionLog< dim > & collision_event_log, const MPI_Comm & mpi_communicator)
Writes the collision statistics to a file.
Parameters
[in] collision_event_log Completed collision event log.
[in] parameters Parameters
[in] mpi_communicator MPI communicator
Definition at line 158 of file log_collision_data.cc.
References Parameters::Lagrangian::LagrangianPostProcessing::collision_stats_file_name, CompletedCollisionLog< dim >::get_events(), and DEMSolverParameters< dim >::post_processing.