Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/dem/log_collision_data.cc File Reference
log_collision_data.cc File Reference
#include <dem/log_collision_data.h>
Functions
template<int dim, typename PropertiesIndex >
void log_collision_data (const DEMSolverParameters< dim > &parameters, typename DEM::dem_data_structures< dim >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< dim > &ongoing_collision_log, CompletedCollisionLog< dim > &collision_event_log, const ConditionalOStream &pcout)
template<int dim>
void write_collision_stats (const DEMSolverParameters< dim > &parameters, const CompletedCollisionLog< dim > &collision_event_log)
template void log_collision_data< 2, DEM::DEMProperties::PropertiesIndex > (const DEMSolverParameters< 2 > &parameters, typename DEM::dem_data_structures< 2 >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 2 > &ongoing_collision_log, CompletedCollisionLog< 2 > &collision_event_log, const ConditionalOStream &pcout)
template void log_collision_data< 3, DEM::DEMProperties::PropertiesIndex > (const DEMSolverParameters< 3 > &parameters, typename DEM::dem_data_structures< 3 >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 3 > &ongoing_collision_log, CompletedCollisionLog< 3 > &collision_event_log, const ConditionalOStream &pcout)
template void log_collision_data< 2, DEM::CFDDEMProperties::PropertiesIndex > (const DEMSolverParameters< 2 > &parameters, typename DEM::dem_data_structures< 2 >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 2 > &ongoing_collision_log, CompletedCollisionLog< 2 > &collision_event_log, const ConditionalOStream &pcout)
template void log_collision_data< 3, DEM::CFDDEMProperties::PropertiesIndex > (const DEMSolverParameters< 3 > &parameters, typename DEM::dem_data_structures< 3 >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 3 > &ongoing_collision_log, CompletedCollisionLog< 3 > &collision_event_log, const ConditionalOStream &pcout)
template void log_collision_data< 2, DEM::DEMMPProperties::PropertiesIndex > (const DEMSolverParameters< 2 > &parameters, typename DEM::dem_data_structures< 2 >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 2 > &ongoing_collision_log, CompletedCollisionLog< 2 > &collision_event_log, const ConditionalOStream &pcout)
template void log_collision_data< 3, DEM::DEMMPProperties::PropertiesIndex > (const DEMSolverParameters< 3 > &parameters, typename DEM::dem_data_structures< 3 >::particle_wall_in_contact &particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 3 > &ongoing_collision_log, CompletedCollisionLog< 3 > &collision_event_log, const ConditionalOStream &pcout)
template void write_collision_stats< 2 > (const DEMSolverParameters< 2 > &parameters, const CompletedCollisionLog< 2 > &collision_event_log)
template void write_collision_stats< 3 > (const DEMSolverParameters< 3 > &parameters, const CompletedCollisionLog< 3 > &collision_event_log)
Function Documentation
log_collision_data()
template<int dim, typename PropertiesIndex > void log_collision_data (const DEMSolverParameters< dim > & parameters, typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< dim > & ongoing_collision_log, CompletedCollisionLog< dim > & collision_event_log, const ConditionalOStream & pcout)
Logs the particle-wall contact statistics.
Parameters
[in] parameters Parameters
[in] particle_wall_pairs_in_contact Required information for the calculation of the particle-wall contact.
[in] current_time Current simulation time.
[out] ongoing_collision_log Ongoing collision log.
[out] collision_event_log Collision event log.
Definition at line 10 of file log_collision_data.cc.
References CompletedCollisionLog< dim >::add_event(), collision_log< dim >::boundary_id, Parameters::Lagrangian::LagrangianPostProcessing::collision_verbosity, OngoingCollisionLog< dim >::end_collision(), find_projection(), get_location(), OngoingCollisionLog< dim >::is_in_collision(), Parameters::Lagrangian::LagrangianPostProcessing::log_collisions_with_all_walls, collision_log< dim >::omega, collision_log< dim >::particle_id, collision_event< dim >::particle_id, Parameters::Lagrangian::LagrangianPostProcessing::particle_wall_collision_boundary_ids, DEMSolverParameters< dim >::post_processing, OngoingCollisionLog< dim >::start_collision(), collision_log< dim >::time, collision_log< dim >::velocity, and Parameters::verbose.
log_collision_data< 2, DEM::CFDDEMProperties::PropertiesIndex >()
template void log_collision_data< 2, DEM::CFDDEMProperties::PropertiesIndex > (const DEMSolverParameters< 2 > & parameters, typename DEM::dem_data_structures< 2 >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 2 > & ongoing_collision_log, CompletedCollisionLog< 2 > & collision_event_log, const ConditionalOStream & pcout)
log_collision_data< 2, DEM::DEMMPProperties::PropertiesIndex >()
template void log_collision_data< 2, DEM::DEMMPProperties::PropertiesIndex > (const DEMSolverParameters< 2 > & parameters, typename DEM::dem_data_structures< 2 >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 2 > & ongoing_collision_log, CompletedCollisionLog< 2 > & collision_event_log, const ConditionalOStream & pcout)
log_collision_data< 2, DEM::DEMProperties::PropertiesIndex >()
template void log_collision_data< 2, DEM::DEMProperties::PropertiesIndex > (const DEMSolverParameters< 2 > & parameters, typename DEM::dem_data_structures< 2 >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 2 > & ongoing_collision_log, CompletedCollisionLog< 2 > & collision_event_log, const ConditionalOStream & pcout)
log_collision_data< 3, DEM::CFDDEMProperties::PropertiesIndex >()
template void log_collision_data< 3, DEM::CFDDEMProperties::PropertiesIndex > (const DEMSolverParameters< 3 > & parameters, typename DEM::dem_data_structures< 3 >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 3 > & ongoing_collision_log, CompletedCollisionLog< 3 > & collision_event_log, const ConditionalOStream & pcout)
log_collision_data< 3, DEM::DEMMPProperties::PropertiesIndex >()
template void log_collision_data< 3, DEM::DEMMPProperties::PropertiesIndex > (const DEMSolverParameters< 3 > & parameters, typename DEM::dem_data_structures< 3 >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 3 > & ongoing_collision_log, CompletedCollisionLog< 3 > & collision_event_log, const ConditionalOStream & pcout)
log_collision_data< 3, DEM::DEMProperties::PropertiesIndex >()
template void log_collision_data< 3, DEM::DEMProperties::PropertiesIndex > (const DEMSolverParameters< 3 > & parameters, typename DEM::dem_data_structures< 3 >::particle_wall_in_contact & particle_wall_pairs_in_contact, const double current_time, OngoingCollisionLog< 3 > & ongoing_collision_log, CompletedCollisionLog< 3 > & collision_event_log, const ConditionalOStream & pcout)
write_collision_stats()
template<int dim> void write_collision_stats (const DEMSolverParameters< dim > & parameters, const CompletedCollisionLog< dim > & collision_event_log)
Writes the collision statistics to a file.
Parameters
[in] collision_event_log Completed collision event log.
[in] parameters Parameters
Definition at line 152 of file log_collision_data.cc.
References Parameters::Lagrangian::LagrangianPostProcessing::collision_stats_file_name, CompletedCollisionLog< dim >::get_events(), and DEMSolverParameters< dim >::post_processing.
write_collision_stats< 2 >()
template void write_collision_stats< 2 > (const DEMSolverParameters< 2 > & parameters, const CompletedCollisionLog< 2 > & collision_event_log)
write_collision_stats< 3 >()
template void write_collision_stats< 3 > (const DEMSolverParameters< 3 > & parameters, const CompletedCollisionLog< 3 > & collision_event_log)