Lethe Open-Source Library: internalFunctionParserCustom Namespace Reference
internalFunctionParserCustom Namespace Reference
Classes
class muParserBase
class Parser
struct ParserData
class ParserImplementation
Functions
int mu_round (double val)
double mu_if (double condition, double thenvalue, double elsevalue)
double mu_or (double left, double right)
double mu_and (double left, double right)
double mu_int (double value)
double mu_ceil (double value)
double mu_floor (double value)
double mu_cot (double value)
double mu_csc (double value)
double mu_sec (double value)
double mu_log (double value)
double mu_pow (double a, double b)
double mu_erf (double value)
double mu_erfc (double value)
double mu_rand_seed (double seed)
double mu_rand ()
std::vector< std::string > get_function_names ()
DeclException2 (ExcParseError, int, std::string,<< "Parsing Error at Column "<< arg1<< ". The parser said: "<< arg2)
Function Documentation
DeclException2()
internalFunctionParserCustom::DeclException2 (ExcParseError , int , std::string , << "Parsing Error at Column "<< arg1<< ". The parser said: "<< arg2)
get_function_names()
std::vector< std::string > internalFunctionParserCustom::get_function_names ()
Get the array of all function names.
Returns
Available implemented functions
Definition at line 125 of file mu_parser_internal.cc.
mu_and()
double internalFunctionParserCustom::mu_and (double left, double right)
Logical and.
Parameters
[in] left First parameter
[in] right Second parameter
Returns
1 if both are true, 0 else
Definition at line 32 of file mu_parser_internal.cc.
References mu_round().
mu_ceil()
double internalFunctionParserCustom::mu_ceil (double value)
Rounds the value to the upper integer
Parameters
[in] value Value to round
Returns
Rounded value
Definition at line 44 of file mu_parser_internal.cc.
mu_cot()
double internalFunctionParserCustom::mu_cot (double value)
Performs the cotangent operation.
Parameters
[in] value Value to process
Returns
Cotan(value)
Definition at line 56 of file mu_parser_internal.cc.
mu_csc()
double internalFunctionParserCustom::mu_csc (double value)
Performs the cosecant operation.
Parameters
[in] value Value to process
Returns
Cosec(value)
Definition at line 62 of file mu_parser_internal.cc.
mu_erf()
double internalFunctionParserCustom::mu_erf (double value)
Performs the erf operation.
Parameters
[in] value Value to process
Returns
std::erf(value)
Definition at line 86 of file mu_parser_internal.cc.
mu_erfc()
double internalFunctionParserCustom::mu_erfc (double value)
Performs the erfc operation.
Parameters
[in] value Value to process
Returns
std::erfc(value)
Definition at line 92 of file mu_parser_internal.cc.
mu_floor()
double internalFunctionParserCustom::mu_floor (double value)
Rounds the value to the lower integer.
Parameters
[in] value Value to round
Returns
Rounded value
Definition at line 50 of file mu_parser_internal.cc.
mu_if()
double internalFunctionParserCustom::mu_if (double condition, double thenvalue, double elsevalue)
If-condition.
Parameters
[in] condition Boolean expression
[in] thenvalue Expression if true
[in] elsevalue Expression if false
Returns
Resulting value
Definition at line 17 of file mu_parser_internal.cc.
References mu_round().
mu_int()
double internalFunctionParserCustom::mu_int (double value)
Rounds the value to the nearest integer (same as round)
Parameters
[in] value Value to round
Returns
Rounded value
Definition at line 38 of file mu_parser_internal.cc.
References mu_round().
mu_log()
double internalFunctionParserCustom::mu_log (double value)
Performs the natural-logarithm operation.
Parameters
[in] value Value to process
Returns
std::log(value)
Definition at line 74 of file mu_parser_internal.cc.
mu_or()
double internalFunctionParserCustom::mu_or (double left, double right)
Logical or.
Parameters
[in] left First parameter
[in] right Second parameter
Returns
1 if either is true, 0 else
Definition at line 26 of file mu_parser_internal.cc.
References mu_round().
mu_pow()
double internalFunctionParserCustom::mu_pow (double a, double b)
Performs the a to the power b operation.
Parameters
[in] a Base
[in] b Exponent
Returns
std::pow(a,b)
Definition at line 80 of file mu_parser_internal.cc.
mu_rand()
double internalFunctionParserCustom::mu_rand ()
Generate number in [0,1].
Returns
Random number
Definition at line 114 of file mu_parser_internal.cc.
mu_rand_seed()
double internalFunctionParserCustom::mu_rand_seed (double seed)
Generate number in [0,1] with a specific seed.
Parameters
[in] seed Number to be able to reproduce random behavior between runs
Returns
Random number
Definition at line 98 of file mu_parser_internal.cc.
mu_round()
int internalFunctionParserCustom::mu_round (double val)
Rounds the value to the nearest integer.
Parameters
[in] val Value to round
Returns
Rounded value
Definition at line 11 of file mu_parser_internal.cc.
mu_sec()
double internalFunctionParserCustom::mu_sec (double value)
Performs the secant operation.
Parameters
[in] value Value to process
Returns
Sec(value)
Definition at line 68 of file mu_parser_internal.cc.