Lethe Open-Source Library: LetheGridTools Namespace Reference
LetheGridTools Namespace Reference
Classes
struct equal_cell
struct hash_cell
Enumerations
enum class ParticleTriangleContactIndicator : std::uint8_t { face_contact , edge_contact , vertex_contact }
Functions
template<int dim>
void vertices_cell_mapping (const DoFHandler< dim > &dof_handler, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > &vertices_cell_map)
template<int dim>
void vertices_cell_mapping_with_periodic_boundaries (const DoFHandler< dim > &dof_handler, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > &vertices_cell_map)
template<int dim>
DoFHandler< dim >::active_cell_iterator find_cell_around_point_with_tree (const DoFHandler< dim > &dof_handler, const Point< dim > &point)
template<int dim>
DoFHandler< dim >::active_cell_iterator find_cell_around_point_with_neighbors (const DoFHandler< dim > &dof_handler, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > &vertices_cell_map, const typename DoFHandler< dim >::active_cell_iterator &cell, const Point< dim > &point)
template<int dim>
std::vector< typename DoFHandler< dim >::active_cell_iterator > find_cells_around_cell (std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > &vertices_cell_map, const typename DoFHandler< dim >::active_cell_iterator &cell)
template<int dim>
std::vector< typename DoFHandler< dim >::active_cell_iterator > find_cells_around_flat_cell (const DoFHandler< dim > &dof_handler, const typename DoFHandler< dim - 1, dim >::active_cell_iterator &cell, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > &vertices_cell_map)
template<int dim>
std::vector< typename DoFHandler< dim >::active_cell_iterator > find_cells_around_edge (const DoFHandler< dim > &dof_handler, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > &vertices_cell_map, const typename DoFHandler< dim >::active_cell_iterator &cell, Point< dim > &point_1, Point< dim > &point_2)
template<int dim>
std::vector< typename DoFHandler< dim >::active_cell_iterator > find_cells_in_cells (const DoFHandler< dim > &dof_handler, const typename DoFHandler< dim >::active_cell_iterator &cell)
template<int dim>
bool cell_cut_by_flat (const typename DoFHandler< dim >::active_cell_iterator &cell, const typename DoFHandler< dim - 1, dim >::active_cell_iterator &cell_flat)
template<int dim>
bool cell_pierced_by_edge (const typename DoFHandler< dim >::active_cell_iterator &cell, const TriaIterator< CellAccessor< 1, dim > > &cell_edge)
template<int dim>
bool cell_pierced_by_edge (const typename DoFHandler< dim >::active_cell_iterator &cell, Point< dim > point_1, Point< dim > point_2)
template<int spacedim, int structdim>
std::pair< std::pair< Point< spacedim >, bool >, Tensor< 1, spacedim > > project_to_d_linear_object (const typename DoFHandler< structdim, spacedim >::active_cell_iterator &object, const Point< spacedim > &trial_point)
template<int dim>
std::vector< typename DoFHandler< dim >::active_cell_iterator > find_boundary_cells_in_sphere (const DoFHandler< dim > &dof_handler, const Point< dim > &center, const double radius)
template<int spacedim, int structdim>
std::map< typename DoFHandler< spacedim >::active_cell_iterator, std::map< unsigned int, typename DoFHandler< structdim, spacedim >::active_cell_iterator > > find_cells_cut_by_object (const DoFHandler< spacedim > &dof_handler, std::map< unsigned int, std::set< typename DoFHandler< spacedim >::active_cell_iterator > > &vertices_cell_map, std::vector< SerialSolid< structdim, spacedim > > &list_of_objects)
template<int dim, typename PropertiesIndex >
std::tuple< std::vector< bool >, std::vector< Point< 3 > >, std::vector< Tensor< 1, 3 > >, std::vector< ParticleTriangleContactIndicator > > find_particle_triangle_projection (const std::vector< Point< dim > > &triangle, const std::vector< Particles::ParticleIterator< dim > > &particles, const unsigned int &n_particles_in_base_cell)
template<int dim>
double find_point_triangle_distance (const std::vector< Point< dim > > &triangle_vertices, const Point< dim > &point)
template<int dim>
std::vector< Point< dim > > find_line_sphere_intersection (const Point< dim > &line_start, const Tensor< 1, dim > &line_direction, const Point< dim > &sphere_center, const double &sphere_diameter)
template<int dim>
double find_point_line_distance (const Point< dim > &line_origin, const Tensor< 1, dim > &line_direction, const Point< dim > &point)
template<int dim>
void rotate_mapping (const DoFHandler< dim > &dof_handler, MappingQCache< dim > &mapping_cache, const Mapping< dim > &mapping, const double &radius, const double &rotation_angle, const Point< dim > &center_of_rotation=Point< dim >(), const Tensor< 1, dim > &rotation_axis=Tensor< 1, dim >())
template<int dim, int spacedim>
void vertices_cell_mapping (const Triangulation< dim, spacedim > &tria, std::map< unsigned int, std::set< typename Triangulation< dim, spacedim >::active_cell_iterator > > &vertices_cell_map)
template<int dim, int spacedim = dim>
std::vector< typename Triangulation< dim, spacedim >::active_cell_iterator > find_cells_around_cell (std::map< unsigned int, std::set< typename Triangulation< dim, spacedim >::active_cell_iterator > > &vertices_cell_map, const typename Triangulation< dim, spacedim >::active_cell_iterator &cell)
Enumeration Type Documentation
ParticleTriangleContactIndicator
enum class LetheGridTools::ParticleTriangleContactIndicator : std::uint8_t strong
Indicates the type of contact between a particle and a triangle.
Enumerator
face_contact
edge_contact
vertex_contact
Definition at line 267 of file lethe_grid_tools.h.
Function Documentation
cell_cut_by_flat()
template<int dim> bool LetheGridTools::cell_cut_by_flat (const typename DoFHandler< dim >::active_cell_iterator & cell, const typename DoFHandler< dim - 1, dim >::active_cell_iterator & cell_flat)
Return a bool that indicates if a cell is cut by a flat cell.
Parameters
cell The cell that we want to check.
cell_flat The cell that describes the flat.
Definition at line 791 of file lethe_grid_tools.cc.
References project_to_d_linear_object().
cell_pierced_by_edge() [1/2]
template<int dim> bool LetheGridTools::cell_pierced_by_edge (const typename DoFHandler< dim >::active_cell_iterator & cell, const TriaIterator< CellAccessor< 1, dim > > & cell_edge)
Return a bool that say if a cell is cut by a edge cell.
Parameters
cell The cell that we want to check.
cell_edge The cell that describes the edge.
Definition at line 429 of file lethe_grid_tools.cc.
cell_pierced_by_edge() [2/2]
template<int dim> bool LetheGridTools::cell_pierced_by_edge (const typename DoFHandler< dim >::active_cell_iterator & cell, Point< dim > point_1, Point< dim > point_2)
Return a bool that say if a cell is cut by a edge cell.
Parameters
cell The cell that we want to check.
point_1 The first point that describes the edge
point_2 The second point that describes the edge
Definition at line 530 of file lethe_grid_tools.cc.
find_boundary_cells_in_sphere()
template<int dim> std::vector< typename DoFHandler< dim >::active_cell_iterator > LetheGridTools::find_boundary_cells_in_sphere (const DoFHandler< dim > & dof_handler, const Point< dim > & center, const double radius)
Function returns all the boundary cells with at least one vertex in a sphere.
Parameters
dof_handler the dof handler containing all the elements.
center The center of the sphere.
radius The radius of the sphere.
Definition at line 252 of file lethe_grid_tools.cc.
find_cell_around_point_with_neighbors()
template<int dim> DoFHandler< dim >::active_cell_iterator LetheGridTools::find_cell_around_point_with_neighbors (const DoFHandler< dim > & dof_handler, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > & vertices_cell_map, const typename DoFHandler< dim >::active_cell_iterator & cell, const Point< dim > & point)
Return the cell around a point based on an initial guess of a nearby cell.
Parameters
cell The initial cell. We suspect that the point is in one of the neighbours of this cell.
point The point around which we want to find the cell.
vertices_cell_map see vertices_cell_mapping function description.
Definition at line 339 of file lethe_grid_tools.cc.
References find_cell_around_point_with_tree().
find_cell_around_point_with_tree()
template<int dim> DoFHandler< dim >::active_cell_iterator LetheGridTools::find_cell_around_point_with_tree (const DoFHandler< dim > & dof_handler, const Point< dim > & point)
Return the cell around a point by starting from the least refined level and iterating over children.
Parameters
point The point around which we want to find the cell.
Definition at line 145 of file lethe_grid_tools.cc.
find_cells_around_cell() [1/2]
template<int dim> std::vector< typename DoFHandler< dim >::active_cell_iterator > LetheGridTools::find_cells_around_cell (std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > & vertices_cell_map, const typename DoFHandler< dim >::active_cell_iterator & cell)
Return a vector of cells around a cell. The vector of cells includes all the cells that share a vertex with the initial cell, including the initial cell.
Parameters
cell The initial cell. We want to know all the cells that share a vertex with this cell.
vertices_cell_map see vertices_cell_mapping function description.
Definition at line 366 of file lethe_grid_tools.cc.
find_cells_around_cell() [2/2]
template<int dim, int spacedim = dim> std::vector< typename Triangulation< dim, spacedim >::active_cell_iterator > LetheGridTools::find_cells_around_cell (std::map< unsigned int, std::set< typename Triangulation< dim, spacedim >::active_cell_iterator > > & vertices_cell_map, const typename Triangulation< dim, spacedim >::active_cell_iterator & cell)
Return a vector of cells around a cell. This vector includes all the cells that share a vertex with the initial cell, including the initial cell.
Parameters
cell The initial cell. We want to know all the cells that share a vertex with this cell.
vertices_cell_map Map of vertex ids to the set of neighbor cells.
Definition at line 1960 of file lethe_grid_tools.cc.
find_cells_around_edge()
template<int dim> std::vector< typename DoFHandler< dim >::active_cell_iterator > LetheGridTools::find_cells_around_edge (const DoFHandler< dim > & dof_handler, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > & vertices_cell_map, const typename DoFHandler< dim >::active_cell_iterator & cell, Point< dim > & point_1, Point< dim > & point_2)
Return a vector of cells around an edge cell in spacedim. An edge cell as a dim of 1.
Parameters
point_1 The first point that describes the edge
point_2 The second point that describes the edge
vertices_cell_map see vertices_cell_mapping function description.
Definition at line 682 of file lethe_grid_tools.cc.
References cell_pierced_by_edge(), find_cell_around_point_with_tree(), and find_cells_around_flat_cell().
find_cells_around_flat_cell()
template<int dim> std::vector< typename DoFHandler< dim >::active_cell_iterator > LetheGridTools::find_cells_around_flat_cell (const DoFHandler< dim > & dof_handler, const typename DoFHandler< dim - 1, dim >::active_cell_iterator & cell, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > & vertices_cell_map)
Return a vector of cells around a flat cell in spacedim. A flat cell has a dim of spacedim-1.
Parameters
cell The cell that describes the flat. We want to know all the cells that are cut by the flat.
vertices_cell_map see vertices_cell_mapping function description.
Definition at line 913 of file lethe_grid_tools.cc.
References find_cell_around_point_with_tree().
find_cells_cut_by_object()
template<int spacedim, int structdim> std::map< typename DoFHandler< spacedim >::active_cell_iterator, std::map< unsigned int, typename DoFHandler< structdim, spacedim >::active_cell_iterator > > LetheGridTools::find_cells_cut_by_object (const DoFHandler< spacedim > & dof_handler, std::map< unsigned int, std::set< typename DoFHandler< spacedim >::active_cell_iterator > > & vertices_cell_map, std::vector< SerialSolid< structdim, spacedim > > & list_of_objects)
Function returns all the cells cut by a list of object defined by a mesh.
Parameters
dof_handler the dof handler containing all the elements.
vertices_cell_map An objects that maps the vertices to cells.
list_of_objects Solid objects
Definition at line 992 of file lethe_grid_tools.cc.
References find_cells_around_flat_cell().
find_cells_in_cells()
template<int dim> std::vector< typename DoFHandler< dim >::active_cell_iterator > LetheGridTools::find_cells_in_cells (const DoFHandler< dim > & dof_handler, const typename DoFHandler< dim >::active_cell_iterator & cell)
Return a vector of cells from the dof_handler that are inside a cell from another mesh.
Parameters
cell Describes the volume for which we want to obtain the enclosed cells.
Definition at line 393 of file lethe_grid_tools.cc.
find_line_sphere_intersection()
template<int dim> std::vector< Point< dim > > LetheGridTools::find_line_sphere_intersection (const Point< dim > & line_start, const Tensor< 1, dim > & line_direction, const Point< dim > & sphere_center, const double & sphere_diameter)
Calculates the intersection points between a line and a sphere. The full calculation is taken from Geometric Tools for Computer Graphics, Eberly 2003 Chapter 11.3.2 - LINEAR COMPONENTS AND A SPHERE. The entire reference is available at: https://www.sciencedirect.com/science/article/pii/B978155860594750014X.
Parameters
[in] line_start The starting point of the line
[in] line_direction The direction of the line
[in] sphere_center The center of the sphere
[in] sphere_diameter The diameter of the sphere
Returns
A vector of points that are the intersection points between the line and the sphere. The vector can be empty if there is no intersection, or contain one or two points if there is an intersection.
Definition at line 1769 of file lethe_grid_tools.cc.
find_particle_triangle_projection()
template<int dim, typename PropertiesIndex > std::tuple< std::vector< bool >, std::vector< Point< 3 > >, std::vector< Tensor< 1, 3 > >, std::vector< ParticleTriangleContactIndicator > > LetheGridTools::find_particle_triangle_projection (const std::vector< Point< dim > > & triangle, const std::vector< Particles::ParticleIterator< dim > > & particles, const unsigned int & n_particles_in_base_cell)
Calculates the distance between particles and a triangle (defined using three vertices). The full calculation is taken from Geometric Tools for Computer Graphics, Eberly 2003 Chapter 10.3.2 - Point to triangle. The entire reference is available at: https://www.sciencedirect.com/science/article/pii/B9781558605947500138 A full implementation of the above reference is also available here: https://www.geometrictools.com/Documentation/DistancePoint3Triangle3.pdf Variables name are taken straight from this reference to ensure a better readability.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Parameters
triangle A vector of points that defines a triangle
particles A particle_iterator_range that refers to all the particles located in the background (base) cell
n_particles_in_base_cell Number of particles in the base cell
Returns
A tuple in which: 0. a vector of bools to determine if the particle is less than a radius away from the triangle plane, 1. a vector of projected location of particles on the triangle, 2. a vector of normal contact vectors between the triangle and the particles, 3. a vector of the contact type between the particle and the triangle.
find_point_line_distance()
template<int dim> double LetheGridTools::find_point_line_distance (const Point< dim > & line_origin, const Tensor< 1, dim > & line_direction, const Point< dim > & point) inline
Calculate the minimum distance between a point and a line (defined using its orign and direction). The full calculation is taken from Geometric Tools for Computer Graphics, Eberly 2003 Chapter 10.2 - Point to linear component. The entire reference is available at: https://www.sciencedirect.com/science/article/pii/B9781558605947500138 A full implementation of the above reference is also available here: https://www.geometrictools.com/Documentation/DistancePointLine.pdf Variables name are taken straight from this reference to ensure a better readability.
Returns
A distance
Parameters
[in] line_origin Origin of the line (any point on the line)
[in] line_direction Vector tangent to the line
[in] point A point for which we want to find the minimum distance to the line
return distance
Definition at line 378 of file lethe_grid_tools.h.
find_point_triangle_distance()
template<int dim> double LetheGridTools::find_point_triangle_distance (const std::vector< Point< dim > > & triangle_vertices, const Point< dim > & point)
Calculates the distance between points and a triangle (defined using three vertices). The full calculation is taken from Geometric Tools for Computer Graphics, Eberly 2003 Chapter 10.3.2 - Point to triangle. The entire reference is available at: https://www.sciencedirect.com/science/article/pii/B9781558605947500138 A full implementation of the above reference is also available here: https://www.geometrictools.com/Documentation/DistancePoint3Triangle3.pdf Variables name are taken straight from this reference to ensure a better readability.
Returns
A distance
Parameters
triangle_vertices A vector of points that defines a triangle
point A point for which we want to find the distance to the triangle
Definition at line 1558 of file lethe_grid_tools.cc.
project_to_d_linear_object()
template<int spacedim, int structdim> std::pair< std::pair< Point< spacedim >, bool >, Tensor< 1, spacedim > > LetheGridTools::project_to_d_linear_object (const typename DoFHandler< structdim, spacedim >::active_cell_iterator & object, const Point< spacedim > & trial_point)
A copy of the project_to_d_linear from dealii that also outputs the normal of the flat.
Parameters
object The flat or the edge.
trial_point The point we project on the flat or edge
Definition at line 561 of file lethe_grid_tools.cc.
rotate_mapping()
template<int dim> void LetheGridTools::rotate_mapping (const DoFHandler< dim > & dof_handler, MappingQCache< dim > & mapping_cache, const Mapping< dim > & mapping, const double & radius, const double & rotation_angle, const Point< dim > & center_of_rotation = Point<dim>(), const Tensor< 1, dim > & rotation_axis = Tensor<1, dim>())
Rotate the mapping according to the rotation angle in a rotor-stator configuration.
Parameters
[in] dof_handler DofHandler of the triangulation
[in] mapping Current mapping
[in] radius Radius or the rotor domain which is going to be rotated
[in] rotation_angle Rotation angle of the rotor domain
[in] center_of_rotation Center of rotation of the rotor domain. Default is the origin
[in] rotation_axis Rotation axis of the rotor domain for 3D case
Definition at line 1831 of file lethe_grid_tools.cc.
vertices_cell_mapping() [1/2]
template<int dim> void LetheGridTools::vertices_cell_mapping (const DoFHandler< dim > & dof_handler, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > & vertices_cell_map)
Map the vertex index to the cells that includes that vertex.
Parameters
dof_handler DofHandler of the triangulation on which to create the map
vertices_cell_map The map container of vertex ids with its set of neighbor cells
Definition at line 21 of file lethe_grid_tools.cc.
vertices_cell_mapping() [2/2]
template<int dim, int spacedim> void LetheGridTools::vertices_cell_mapping (const Triangulation< dim, spacedim > & tria, std::map< unsigned int, std::set< typename Triangulation< dim, spacedim >::active_cell_iterator > > & vertices_cell_map)
Map the vertex index to the cells which include that vertex.
Parameters
tria Triangulation
vertices_cell_map The map container of vertex ids with its set of neighbor cells.
Definition at line 1905 of file lethe_grid_tools.cc.
vertices_cell_mapping_with_periodic_boundaries()
template<int dim> void LetheGridTools::vertices_cell_mapping_with_periodic_boundaries (const DoFHandler< dim > & dof_handler, std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > & vertices_cell_map)
Map the vertex index to the cells on periodic boundaries that includes the periodic coinciding vertex.
Parameters
dof_handler DofHandler of the triangulation on which to create the map
vertices_cell_map The map of vertex ids at periodic boundary to the set of periodic neighbor cells
Definition at line 52 of file lethe_grid_tools.cc.