Lethe Open-Source Library: ShapeGenerator Namespace Reference
ShapeGenerator Namespace Reference
Functions
template<int dim>
std::shared_ptr< Shape< dim > > initialize_shape (const std::string &type, const std::string &shape_arguments_str, const Point< dim > &position, const Tensor< 1, 3 > &orientation)
template<int dim>
std::shared_ptr< Shape< dim > > initialize_shape_from_vector (const std::string &type, const std::vector< double > &shape_arguments, const Point< dim > &position, const Tensor< 1, 3 > &orientation)
template<int dim>
std::shared_ptr< Shape< dim > > initialize_shape_from_file (const std::string &type, const std::string &file_name, const Point< dim > &position, const Tensor< 1, 3 > &orientation)
Function Documentation
initialize_shape()
template<int dim> std::shared_ptr< Shape< dim > > ShapeGenerator::initialize_shape (const std::string & type, const std::string & shape_arguments_str, const Point< dim > & position, const Tensor< 1, 3 > & orientation)
Initializes the shape from its type and arguments
Parameters
type the type of shape
shape_arguments_str the raw arguments
position the position of the shape
orientation the orientation of the shape
Definition at line 8 of file shape_parsing.cc.
References initialize_shape_from_file(), and initialize_shape_from_vector().
initialize_shape_from_file()
template<int dim> std::shared_ptr< Shape< dim > > ShapeGenerator::initialize_shape_from_file (const std::string & type, const std::string & file_name, const Point< dim > & position, const Tensor< 1, 3 > & orientation)
Initializes the shape from its type and a text file that contains the real initialization data
Parameters
type the type of shape
file_name the name of the file that contains the initialization data
position the position of the shape
orientation the orientation of the shape
Definition at line 159 of file shape_parsing.cc.
References initialize_shape().
initialize_shape_from_vector()
template<int dim> std::shared_ptr< Shape< dim > > ShapeGenerator::initialize_shape_from_vector (const std::string & type, const std::vector< double > & shape_arguments, const Point< dim > & position, const Tensor< 1, 3 > & orientation)
Initializes the shape from its type and numerical arguments
Parameters
type the type of shape
shape_arguments the numerical arguments
position the position of the shape
orientation the orientation of the shape
Definition at line 37 of file shape_parsing.cc.