Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/dem/particle_wall_fine_search.cc File Reference
particle_wall_fine_search.cc File Reference
#include <core/tensors_and_points_dimension_manipulation.h>
#include <dem/contact_info.h>
#include <dem/particle_wall_fine_search.h>
#include <deal.II/particles/particle_handler.h>
#include <boost/math/special_functions/sign.hpp>
#include <vector>
Functions
template<int dim>
void particle_wall_fine_search (const typename dem_data_structures< dim >::particle_wall_candidates &particle_wall_contact_pair_candidates, typename dem_data_structures< dim >::particle_wall_in_contact &particle_wall_pairs_in_contact)
template<int dim>
void particle_floating_wall_fine_search (const typename dem_data_structures< dim >::particle_floating_wall_candidates &particle_floating_wall_candidates, const Parameters::Lagrangian::FloatingWalls< dim > &floating_wall_properties, const double simulation_time, typename dem_data_structures< dim >::particle_wall_in_contact &particle_floating_wall_pairs_in_contact)
template<int dim>
void particle_floating_mesh_fine_search (const typename dem_data_structures< dim >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, typename dem_data_structures< dim >::particle_floating_mesh_potentially_in_contact &particle_floating_mesh_potentially_in_contact)
template void particle_wall_fine_search< 2 > (const typename dem_data_structures< 2 >::particle_wall_candidates &particle_wall_contact_pair_candidates, typename dem_data_structures< 2 >::particle_wall_in_contact &particle_wall_pairs_in_contact)
template void particle_wall_fine_search< 3 > (const typename dem_data_structures< 3 >::particle_wall_candidates &particle_wall_contact_pair_candidates, typename dem_data_structures< 3 >::particle_wall_in_contact &particle_wall_pairs_in_contact)
template void particle_floating_wall_fine_search< 2 > (const typename dem_data_structures< 2 >::particle_floating_wall_candidates &particle_floating_wall_candidates, const Parameters::Lagrangian::FloatingWalls< 2 > &floating_wall_properties, const double simulation_time, typename dem_data_structures< 2 >::particle_wall_in_contact &particle_floating_wall_pairs_in_contact)
template void particle_floating_wall_fine_search< 3 > (const typename dem_data_structures< 3 >::particle_floating_wall_candidates &particle_floating_wall_candidates, const Parameters::Lagrangian::FloatingWalls< 3 > &floating_wall_properties, const double simulation_time, typename dem_data_structures< 3 >::particle_wall_in_contact &particle_floating_wall_pairs_in_contact)
template void particle_floating_mesh_fine_search< 2 > (const typename dem_data_structures< 2 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, typename dem_data_structures< 2 >::particle_floating_mesh_potentially_in_contact &particle_floating_mesh_potentially_in_contact)
template void particle_floating_mesh_fine_search< 3 > (const typename dem_data_structures< 3 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, typename dem_data_structures< 3 >::particle_floating_mesh_potentially_in_contact &particle_floating_mesh_potentially_in_contact)
Function Documentation
particle_floating_mesh_fine_search()
template<int dim> void particle_floating_mesh_fine_search (const typename DEM::dem_data_structures< dim >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, typename DEM::dem_data_structures< dim >::particle_floating_mesh_potentially_in_contact & particle_floating_mesh_potentially_in_contact)
Iterate over the contact candidates from particle-floating mesh broad search (particle_floating_mesh_contact_candidates) to add new contact pairs to the particle_floating_mesh_potentially_in_contact container.
Parameters
particle_floating_mesh_contact_candidates The output of particle-floating mesh broad search which shows contact pair candidates
particle_floating_mesh_potentially_in_contact A map of maps which stores all the particle-floating mesh pairs which are potentially in contact
Definition at line 170 of file particle_wall_fine_search.cc.
particle_floating_mesh_fine_search< 2 >()
template void particle_floating_mesh_fine_search< 2 > (const typename dem_data_structures< 2 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, typename dem_data_structures< 2 >::particle_floating_mesh_potentially_in_contact & particle_floating_mesh_potentially_in_contact)
particle_floating_mesh_fine_search< 3 >()
template void particle_floating_mesh_fine_search< 3 > (const typename dem_data_structures< 3 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, typename dem_data_structures< 3 >::particle_floating_mesh_potentially_in_contact & particle_floating_mesh_potentially_in_contact)
particle_floating_wall_fine_search()
template<int dim> void particle_floating_wall_fine_search (const typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates & particle_floating_wall_contact_candidates, const Parameters::Lagrangian::FloatingWalls< dim > & floating_wall_properties, const double simulation_time, typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_floating_wall_in_contact)
Iterate over the contact candidates from particle-floating wall broad search (particle_floating_wall_candidates) to add new contact pairs to the particle_floating_wall_pairs_in_contact container.
Parameters
particle_floating_wall_contact_candidates The output of particle-floating wall broad search which shows contact pair candidates
floating_wall_properties Properties of floating walls defined in the parameter handler
simulation_time Simulation time
particle_floating_wall_in_contact An unordered_map of maps which stores all the particle-floating wall pairs which are in contact, and the contact information in a struct. Note that the size of this unordered map is equal to the number of particles
Definition at line 75 of file particle_wall_fine_search.cc.
References Parameters::Lagrangian::FloatingWalls< dim >::floating_walls_normal_vectors, point_nd_to_3d(), Parameters::Lagrangian::FloatingWalls< dim >::points_on_walls, tensor_nd_to_3d(), Parameters::Lagrangian::FloatingWalls< dim >::time_end, and Parameters::Lagrangian::FloatingWalls< dim >::time_start.
particle_floating_wall_fine_search< 2 >()
template void particle_floating_wall_fine_search< 2 > (const typename dem_data_structures< 2 >::particle_floating_wall_candidates & particle_floating_wall_candidates, const Parameters::Lagrangian::FloatingWalls< 2 > & floating_wall_properties, const double simulation_time, typename dem_data_structures< 2 >::particle_wall_in_contact & particle_floating_wall_pairs_in_contact)
particle_floating_wall_fine_search< 3 >()
template void particle_floating_wall_fine_search< 3 > (const typename dem_data_structures< 3 >::particle_floating_wall_candidates & particle_floating_wall_candidates, const Parameters::Lagrangian::FloatingWalls< 3 > & floating_wall_properties, const double simulation_time, typename dem_data_structures< 3 >::particle_wall_in_contact & particle_floating_wall_pairs_in_contact)
particle_wall_fine_search()
template<int dim> void particle_wall_fine_search (const typename DEM::dem_data_structures< dim >::particle_wall_candidates & particle_wall_contact_pair_candidates, typename DEM::dem_data_structures< dim >::particle_wall_in_contact & particle_wall_pairs_in_contact)
Iterate over the contact candidates from particle-wall broad search (particle_wall_contact_pair_candidates) to add new contact pairs to the particle_wall_pairs_in_contact container.
Parameters
particle_wall_contact_pair_candidates The output of particle-wall broad search which shows contact pair candidates
particle_wall_pairs_in_contact An unordered_map of maps which stores all the particle-wall pairs which are physically in contact, and the contact information in a struct. Note that the size of this unordered map is equal to the number of particles
Definition at line 20 of file particle_wall_fine_search.cc.
References point_nd_to_3d(), and tensor_nd_to_3d().
particle_wall_fine_search< 2 >()
template void particle_wall_fine_search< 2 > (const typename dem_data_structures< 2 >::particle_wall_candidates & particle_wall_contact_pair_candidates, typename dem_data_structures< 2 >::particle_wall_in_contact & particle_wall_pairs_in_contact)
particle_wall_fine_search< 3 >()
template void particle_wall_fine_search< 3 > (const typename dem_data_structures< 3 >::particle_wall_candidates & particle_wall_contact_pair_candidates, typename dem_data_structures< 3 >::particle_wall_in_contact & particle_wall_pairs_in_contact)