Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/dem/particle_point_line_fine_search.cc File Reference
particle_point_line_fine_search.cc File Reference
#include <core/dem_properties.h>
#include <core/tensors_and_points_dimension_manipulation.h>
#include <dem/contact_info.h>
#include <dem/particle_point_line_fine_search.h>
#include <deal.II/particles/particle_handler.h>
Functions
template<int dim, typename PropertiesIndex >
void particle_point_fine_search (const typename DEM::dem_data_structures< dim >::particle_point_candidates &particle_point_contact_candidates, const double neighborhood_threshold, typename DEM::dem_data_structures< dim >::particle_point_in_contact &particle_point_pairs_in_contact)
template<int dim, typename PropertiesIndex >
void particle_line_fine_search (const typename DEM::dem_data_structures< dim >::particle_line_candidates &particle_line_contact_candidates, const double neighborhood_threshold, typename DEM::dem_data_structures< dim >::particle_line_in_contact &particle_line_pairs_in_contact)
Point< 3 > find_projection_point (const Point< 3 > &point_p, const Point< 3 > &point_a, const Point< 3 > &point_b)
template void particle_point_fine_search< 2, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_point_candidates &particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_point_in_contact &particle_point_pairs_in_contact)
template void particle_point_fine_search< 3, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_point_candidates &particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_point_in_contact &particle_point_pairs_in_contact)
template void particle_line_fine_search< 2, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_line_candidates &particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_line_in_contact &particle_line_pairs_in_contact)
template void particle_line_fine_search< 3, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_line_candidates &particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_line_in_contact &particle_line_pairs_in_contact)
template void particle_point_fine_search< 2, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_point_candidates &particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_point_in_contact &particle_point_pairs_in_contact)
template void particle_point_fine_search< 3, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_point_candidates &particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_point_in_contact &particle_point_pairs_in_contact)
template void particle_line_fine_search< 2, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_line_candidates &particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_line_in_contact &particle_line_pairs_in_contact)
template void particle_line_fine_search< 3, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_line_candidates &particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_line_in_contact &particle_line_pairs_in_contact)
template void particle_point_fine_search< 2, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_point_candidates &particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_point_in_contact &particle_point_pairs_in_contact)
template void particle_point_fine_search< 3, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_point_candidates &particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_point_in_contact &particle_point_pairs_in_contact)
template void particle_line_fine_search< 2, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_line_candidates &particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_line_in_contact &particle_line_pairs_in_contact)
template void particle_line_fine_search< 3, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_line_candidates &particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_line_in_contact &particle_line_pairs_in_contact)
Function Documentation
find_projection_point()
Point< 3 > find_projection_point (const Point< 3 > & point_p, const Point< 3 > & point_a, const Point< 3 > & point_b) inline
This private function is used to find the projection of point_p on a line with beginning and ending vertices of point_a and point_b, respectively.
Parameters
point_p A point which is going to be projected on the line
point_a Beginning point of the line
point_b Ending point of the line
Returns
The projection of point_p on the line (from point_a to point_b)
Definition at line 138 of file particle_point_line_fine_search.cc.
particle_line_fine_search()
template<int dim, typename PropertiesIndex > void particle_line_fine_search (const typename DEM::dem_data_structures< dim >::particle_line_candidates & particle_line_contact_candidates, const double neighborhood_threshold, typename DEM::dem_data_structures< dim >::particle_line_in_contact & particle_line_pairs_in_contact)
Iterate over a map of tuples (particle_line_contact_candidates) to see if the particle-line pairs are in contact or not. If they are in contact, the normal overlap, normal vector of contact and contact normal relative velocity are stored in a map which is the output of this function.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Parameters
particle_line_contact_candidates The output of particle-line broad search which shows contact pair candidates.
neighborhood_threshold A value which defines the neighbor particles.
particle_line_pairs_in_contact A map which contains all the required information (normal overlap, normal vector and contact normal relative velocity) for calculation of particle-line contact force.
Definition at line 78 of file particle_point_line_fine_search.cc.
References find_projection_point(), particle_line_contact_info< dim >::particle, point_nd_to_3d(), particle_line_contact_info< dim >::point_one, and particle_line_contact_info< dim >::point_two.
particle_line_fine_search< 2, DEM::CFDDEMProperties::PropertiesIndex >()
template void particle_line_fine_search< 2, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_line_candidates & particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_line_in_contact & particle_line_pairs_in_contact)
particle_line_fine_search< 2, DEM::DEMMPProperties::PropertiesIndex >()
template void particle_line_fine_search< 2, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_line_candidates & particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_line_in_contact & particle_line_pairs_in_contact)
particle_line_fine_search< 2, DEM::DEMProperties::PropertiesIndex >()
template void particle_line_fine_search< 2, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_line_candidates & particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_line_in_contact & particle_line_pairs_in_contact)
particle_line_fine_search< 3, DEM::CFDDEMProperties::PropertiesIndex >()
template void particle_line_fine_search< 3, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_line_candidates & particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_line_in_contact & particle_line_pairs_in_contact)
particle_line_fine_search< 3, DEM::DEMMPProperties::PropertiesIndex >()
template void particle_line_fine_search< 3, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_line_candidates & particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_line_in_contact & particle_line_pairs_in_contact)
particle_line_fine_search< 3, DEM::DEMProperties::PropertiesIndex >()
template void particle_line_fine_search< 3, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_line_candidates & particle_line_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_line_in_contact & particle_line_pairs_in_contact)
particle_point_fine_search()
template<int dim, typename PropertiesIndex > void particle_point_fine_search (const typename DEM::dem_data_structures< dim >::particle_point_candidates & particle_point_contact_candidates, const double neighborhood_threshold, typename DEM::dem_data_structures< dim >::particle_point_in_contact & particle_point_pairs_in_contact)
Iterate over a map of pairs (particle_point_contact_candidates) to see if the particle-point pairs are in contact or not. If they are in contact, the normal overlap, normal vector of contact and contact normal relative velocity are stored in a map which is the output of this function.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Parameters
particle_point_contact_candidates The output of particle-point broad search which shows contact pair candidates.
neighborhood_threshold A value which defines the neighbor particles.
particle_point_pairs_in_contact A map which contains all the required information (normal overlap, normal vector and contact normal relative velocity) for calculation of particle-point contact force.
Definition at line 20 of file particle_point_line_fine_search.cc.
References particle_point_contact_info< dim >::particle, particle_point_contact_info< dim >::point, and point_nd_to_3d().
particle_point_fine_search< 2, DEM::CFDDEMProperties::PropertiesIndex >()
template void particle_point_fine_search< 2, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_point_candidates & particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_point_in_contact & particle_point_pairs_in_contact)
particle_point_fine_search< 2, DEM::DEMMPProperties::PropertiesIndex >()
template void particle_point_fine_search< 2, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_point_candidates & particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_point_in_contact & particle_point_pairs_in_contact)
particle_point_fine_search< 2, DEM::DEMProperties::PropertiesIndex >()
template void particle_point_fine_search< 2, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::particle_point_candidates & particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 2 >::particle_point_in_contact & particle_point_pairs_in_contact)
particle_point_fine_search< 3, DEM::CFDDEMProperties::PropertiesIndex >()
template void particle_point_fine_search< 3, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_point_candidates & particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_point_in_contact & particle_point_pairs_in_contact)
particle_point_fine_search< 3, DEM::DEMMPProperties::PropertiesIndex >()
template void particle_point_fine_search< 3, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_point_candidates & particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_point_in_contact & particle_point_pairs_in_contact)
particle_point_fine_search< 3, DEM::DEMProperties::PropertiesIndex >()
template void particle_point_fine_search< 3, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::particle_point_candidates & particle_point_contact_candidates, const double neighborhood_threshold, DEM::dem_data_structures< 3 >::particle_point_in_contact & particle_point_pairs_in_contact)