Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/dem/particle_heat_transfer.cc File Reference
particle_heat_transfer.cc File Reference
#include <dem/particle_heat_transfer.h>
Functions
double calculate_corrected_contact_radius (const double effective_radius, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double normal_force_norm)
double calculate_macrocontact_resistance (const double harmonic_conductivity, const double contact_radius)
double calculate_microcontact_resistance (const double equivalent_surface_slope, const double equivalent_surface_roughness, const double effective_microhardness, const double contact_radius_squared, const double harmonic_conductivity, const double maximum_pressure)
double calculate_solid_macrogap_resistance (const double radius, const double thermal_conductivity, const double contact_radius_squared)
double calculate_interstitial_gas_microgap_resistance (const double equivalent_surface_roughness, const double contact_radius_squared, const double gas_parameter_m, const double thermal_conductivity_gas, const double maximum_pressure, const double effective_microhardness)
double calculate_interstitial_gas_macrogap_resistance (const double harmonic_radius, const double thermal_conductivity_gas, const double contact_radius_squared, const double gas_parameter_m)
template<ContactType contact_type>
void calculate_contact_thermal_conductance (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double &thermal_conductance)
void apply_heat_transfer_on_local_particles (const double temperature_one, const double temperature_two, const double thermal_conductance, double &particle_one_heat_transfer_rate, double &particle_two_heat_transfer_rate)
void apply_heat_transfer_on_single_local_particle (const double temperature_one, const double temperature_two, const double thermal_conductance, double &particle_one_heat_transfer_rate)
template void calculate_contact_thermal_conductance< ContactType::local_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double &thermal_conductance)
template void calculate_contact_thermal_conductance< ContactType::ghost_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double &thermal_conductance)
template void calculate_contact_thermal_conductance< ContactType::local_periodic_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double &thermal_conductance)
template void calculate_contact_thermal_conductance< ContactType::ghost_periodic_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double &thermal_conductance)
template void calculate_contact_thermal_conductance< ContactType::ghost_local_periodic_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double &thermal_conductance)
template void calculate_contact_thermal_conductance< ContactType::particle_floating_mesh > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double &thermal_conductance)
Function Documentation
apply_heat_transfer_on_local_particles()
void apply_heat_transfer_on_local_particles (const double temperature_one, const double temperature_two, const double thermal_conductance, double & particle_one_heat_transfer_rate, double & particle_two_heat_transfer_rate)
Apply the heat transfer to a local-local particle pair in contact.
Parameters
[in] temperature_one Temperature of particle one.
[in] temperature_two Temperature of particle two.
[in] thermal_conductance Total thermal conductance between the two particles.
[in,out] particle_one_heat_transfer_rate Heat transfer rate due to contact applied to particle one.
[in,out] particle_two_heat_transfer_rate Heat transfer rate due to contact applied to particle two.
Definition at line 256 of file particle_heat_transfer.cc.
apply_heat_transfer_on_single_local_particle()
void apply_heat_transfer_on_single_local_particle (const double temperature_one, const double temperature_two, const double thermal_conductance, double & particle_one_heat_transfer_rate)
Apply the heat transfer to a local particle. This function is used for local-ghost particle pairs or particle-wall pairs in contact. The heat transfer is only applied to the local particle, thus particle one should be the local particle here.
Parameters
[in] temperature_one Temperature of particle one.
[in] temperature_two Temperature of particle two or of wall.
[in] thermal_conductance Total thermal conductance of the pair.
[in,out] particle_one_heat_transfer_rate Heat transfer rate due to contact applied to particle one.
Definition at line 269 of file particle_heat_transfer.cc.
calculate_contact_thermal_conductance()
template<ContactType contact_type> void calculate_contact_thermal_conductance (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double & thermal_conductance)
Calculate the total thermal conductance for particle-particle or particle-wall contacts. The resistance_macrocontact, resistance_solid_macrogap and resistance_gas_macrogap differ from particle-particle contacts to particle-wall contacts.
Template Parameters
contact_type Type of contact. Only particle-particle and particle-floating-mesh contacts are accepted for now.
Parameters
[in] radius_one Radius of particle one.
[in] radius_two Radius of particle two for particle-particle contacts. Unused for particle-wall contacts.
[in] effective_youngs_modulus Effective young's modulus of the contact pair.
[in] effective_real_youngs_modulus Effective real young's modulus of the contact pair.
[in] equivalent_surface_roughness Equivalent surface roughness of the contact pair.
[in] equivalent_surface_slope Equivalent surface slope of the contact pair.
[in] effective_microhardness Effective microhardness of the contact pair.
[in] thermal_conductivity_one Thermal conductivity of particle one.
[in] thermal_conductivity_two Thermal conductivity of particle two or of wall.
[in] thermal_conductivity_gas Thermal conductivity of the interstitial gas.
[in] gas_parameter_m Gas parameter.
[in] normal_overlap Normal overlap of the contact pair.
[in] normal_force_norm Norm of the normal contact force of the contact pair.
[out] thermal_conductance Total thermal conductance for the contact pair.
Definition at line 131 of file particle_heat_transfer.cc.
References calculate_corrected_contact_radius(), calculate_interstitial_gas_macrogap_resistance(), calculate_interstitial_gas_microgap_resistance(), calculate_macrocontact_resistance(), calculate_microcontact_resistance(), calculate_solid_macrogap_resistance(), harmonic_mean(), and particle_floating_mesh.
calculate_contact_thermal_conductance< ContactType::ghost_local_periodic_particle_particle >()
template void calculate_contact_thermal_conductance< ContactType::ghost_local_periodic_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double & thermal_conductance)
calculate_contact_thermal_conductance< ContactType::ghost_particle_particle >()
template void calculate_contact_thermal_conductance< ContactType::ghost_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double & thermal_conductance)
calculate_contact_thermal_conductance< ContactType::ghost_periodic_particle_particle >()
template void calculate_contact_thermal_conductance< ContactType::ghost_periodic_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double & thermal_conductance)
calculate_contact_thermal_conductance< ContactType::local_particle_particle >()
template void calculate_contact_thermal_conductance< ContactType::local_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double & thermal_conductance)
calculate_contact_thermal_conductance< ContactType::local_periodic_particle_particle >()
template void calculate_contact_thermal_conductance< ContactType::local_periodic_particle_particle > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double & thermal_conductance)
calculate_contact_thermal_conductance< ContactType::particle_floating_mesh >()
template void calculate_contact_thermal_conductance< ContactType::particle_floating_mesh > (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double & thermal_conductance)
calculate_corrected_contact_radius()
double calculate_corrected_contact_radius (const double effective_radius, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double normal_force_norm)
Calculate the corrected contact radius for a particle-particle or particle-wall pair in contact.
Parameters
[in] effective_radius Effective radius of the pair in contact.
[in] effective_youngs_modulus Effective young's modulus of the pair in contact.
[in] effective_real_youngs_modulus Effective real young's modulus of the pair in contact.
[in] normal_force_norm Norm of the normal contact force for the pair in contact.
Returns
Corrected contact radius of the pair in contact.
Definition at line 7 of file particle_heat_transfer.cc.
calculate_interstitial_gas_macrogap_resistance()
double calculate_interstitial_gas_macrogap_resistance (const double harmonic_radius, const double thermal_conductivity_gas, const double contact_radius_squared, const double gas_parameter_m)
Calculate the interstitial gas macrogap thermal resistance for a particle-particle or particle-wall pair in contact.
Parameters
[in] harmonic_radius Harmonic mean of the particles' radii for a particle-particle contact, radius of the particle for a particle-wall contact.
[in] thermal_conductivity_gas Thermal conductivity of the interstitial gas.
[in] contact_radius_squared Squared contact radius of the pair in contact.
[in] gas_parameter_m Gas parameter.
Returns
Interstitial gas microgap thermal resistance for the pair in contact.
Definition at line 111 of file particle_heat_transfer.cc.
calculate_interstitial_gas_microgap_resistance()
double calculate_interstitial_gas_microgap_resistance (const double equivalent_surface_roughness, const double contact_radius_squared, const double gas_parameter_m, const double thermal_conductivity_gas, const double maximum_pressure, const double effective_microhardness)
Calculate the interstitial gas microgap thermal resistance for a particle-particle or particle-wall pair in contact.
Parameters
[in] equivalent_surface_roughness Equivalent surface roughness of the pair in contact.
[in] contact_radius_squared Squared contact radius of the pair in contact.
[in] gas_parameter_m Gas parameter.
[in] thermal_conductivity_gas Thermal conductivity of the interstitial gas.
[in] maximum_pressure Maximum pressure for hertzian contacts.
[in] effective_microhardness Effective microhardness of the pair in contact.
Returns
Interstitial gas microgap thermal resistance for the pair in contact.
Definition at line 74 of file particle_heat_transfer.cc.
calculate_macrocontact_resistance()
double calculate_macrocontact_resistance (const double harmonic_conductivity, const double contact_radius)
Calculate the macrocontact thermal resistance for a particle-particle or particle-wall pair in contact.
Parameters
[in] harmonic_conductivity Harmonic mean of the thermal conductivities for a particle-particle contact or twice the particle thermal conductivity for a particle-wall contact.
[in] contact_radius Contact radius of the pair in contact.
Returns
Macrocontact thermal resistance for the pair in contact.
Definition at line 27 of file particle_heat_transfer.cc.
calculate_microcontact_resistance()
double calculate_microcontact_resistance (const double equivalent_surface_slope, const double equivalent_surface_roughness, const double effective_microhardness, const double contact_radius_squared, const double harmonic_conductivity, const double maximum_pressure)
Calculate the microcontact thermal resistance for a particle-particle or particle-wall pair in contact.
Parameters
[in] equivalent_surface_slope Equivalent surface slope of the pair in contact.
[in] equivalent_surface_roughness Equivalent surface roughness of the pair in contact.
[in] effective_microhardness Effective microhardness of the pair in contact.
[in] contact_radius_squared Squared contact radius of the pair in contact.
[in] harmonic_conductivity Harmonic mean of the thermal conductivities of the pair in contact.
[in] maximum_pressure Maximum pressure for hertzian contacts.
Returns
Microcontact thermal resistance for the pair in contact.
Definition at line 38 of file particle_heat_transfer.cc.
calculate_solid_macrogap_resistance()
double calculate_solid_macrogap_resistance (const double radius, const double thermal_conductivity, const double contact_radius_squared)
Calculate the solid macrogap thermal resistance for one particle.
Parameters
[in] radius Radius of the particle.
[in] thermal_conductivity Thermal conductivity of the particle.
[in] contact_radius_squared Squared contact radius of the pair in contact.
Returns
Solid macrogap thermal resistance for one particle.
Definition at line 57 of file particle_heat_transfer.cc.