Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/dem/particle_wall_broad_search.cc File Reference
particle_wall_broad_search.cc File Reference
#include <dem/particle_wall_broad_search.h>
Functions
template<int dim>
void find_particle_wall_contact_pairs (const std::map< int, boundary_cells_info_struct< dim > > &boundary_cells_information, const Particles::ParticleHandler< dim > &particle_handler, typename DEM::dem_data_structures< dim >::particle_wall_candidates &particle_wall_contact_candidates)
template<int dim>
void find_particle_floating_wall_contact_pairs (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< dim >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< dim > &particle_handler, const Parameters::Lagrangian::FloatingWalls< dim > &floating_wall_properties, const double simulation_time, typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates &particle_floating_wall_candidates)
template<int dim>
void particle_solid_surfaces_contact_search (const typename DEM::dem_data_structures< dim >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< dim > &particle_handler, typename DEM::dem_data_structures< dim >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, typename DEM::dem_data_structures< dim >::cells_total_neighbor_list &cells_total_neighbor_list)
template<int dim, typename PropertiesIndex >
void find_particle_wall_contact_pairs (const std::map< int, boundary_cells_info_struct< dim > > &boundary_cells_information, const Particles::ParticleHandler< dim > &particle_handler, typename DEM::dem_data_structures< dim >::particle_wall_candidates &particle_wall_contact_candidates, const AdaptiveSparseContacts< dim, PropertiesIndex > &sparse_contacts_object)
template<int dim, typename PropertiesIndex >
void find_particle_floating_wall_contact_pairs (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< dim >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< dim > &particle_handler, const Parameters::Lagrangian::FloatingWalls< dim > &floating_wall_properties, const double simulation_time, typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates &particle_floating_wall_candidates, const AdaptiveSparseContacts< dim, PropertiesIndex > &sparse_contacts_object)
template<int dim, typename PropertiesIndex >
void particle_solid_surfaces_contact_search (const typename DEM::dem_data_structures< dim >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< dim > &particle_handler, typename DEM::dem_data_structures< dim >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, typename DEM::dem_data_structures< dim >::cells_total_neighbor_list &cells_total_neighbor_list, const AdaptiveSparseContacts< dim, PropertiesIndex > &sparse_contacts_object)
template<int dim>
void store_candidates (const typename Particles::ParticleHandler< dim >::particle_iterator_range::iterator &particle_iterator, const DEM::global_face_id &floating_wall_id, typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates &contact_pair_candidates)
template void find_particle_wall_contact_pairs< 2 > (const std::map< int, boundary_cells_info_struct< 2 > > &boundary_cells_information, const Particles::ParticleHandler< 2 > &particle_handler, DEM::dem_data_structures< 2 >::particle_wall_candidates &particle_wall_contact_candidates)
template void find_particle_wall_contact_pairs< 3 > (const std::map< int, boundary_cells_info_struct< 3 > > &boundary_cells_information, const Particles::ParticleHandler< 3 > &particle_handler, DEM::dem_data_structures< 3 >::particle_wall_candidates &particle_wall_contact_candidates)
template void find_particle_wall_contact_pairs< 2, DEM::DEMProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 2 > > &boundary_cells_information, const Particles::ParticleHandler< 2 > &particle_handler, DEM::dem_data_structures< 2 >::particle_wall_candidates &particle_wall_contact_candidates, const AdaptiveSparseContacts< 2, DEM::DEMProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_wall_contact_pairs< 3, DEM::DEMProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 3 > > &boundary_cells_information, const Particles::ParticleHandler< 3 > &particle_handler, DEM::dem_data_structures< 3 >::particle_wall_candidates &particle_wall_contact_candidates, const AdaptiveSparseContacts< 3, DEM::DEMProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_wall_contact_pairs< 2, DEM::CFDDEMProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 2 > > &boundary_cells_information, const Particles::ParticleHandler< 2 > &particle_handler, DEM::dem_data_structures< 2 >::particle_wall_candidates &particle_wall_contact_candidates, const AdaptiveSparseContacts< 2, DEM::CFDDEMProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_wall_contact_pairs< 3, DEM::CFDDEMProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 3 > > &boundary_cells_information, const Particles::ParticleHandler< 3 > &particle_handler, DEM::dem_data_structures< 3 >::particle_wall_candidates &particle_wall_contact_candidates, const AdaptiveSparseContacts< 3, DEM::CFDDEMProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_wall_contact_pairs< 2, DEM::DEMMPProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 2 > > &boundary_cells_information, const Particles::ParticleHandler< 2 > &particle_handler, DEM::dem_data_structures< 2 >::particle_wall_candidates &particle_wall_contact_candidates, const AdaptiveSparseContacts< 2, DEM::DEMMPProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_wall_contact_pairs< 3, DEM::DEMMPProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 3 > > &boundary_cells_information, const Particles::ParticleHandler< 3 > &particle_handler, DEM::dem_data_structures< 3 >::particle_wall_candidates &particle_wall_contact_candidates, const AdaptiveSparseContacts< 3, DEM::DEMMPProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_floating_wall_contact_pairs< 2 > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 2 >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< 2 > &particle_handler, const Parameters::Lagrangian::FloatingWalls< 2 > &floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 2 >::particle_floating_wall_candidates &particle_floating_wall_candidates)
template void find_particle_floating_wall_contact_pairs< 3 > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 3 >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< 3 > &particle_handler, const Parameters::Lagrangian::FloatingWalls< 3 > &floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 3 >::particle_floating_wall_candidates &particle_floating_wall_candidates)
template void find_particle_floating_wall_contact_pairs< 2, DEM::DEMProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 2 >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< 2 > &particle_handler, const Parameters::Lagrangian::FloatingWalls< 2 > &floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 2 >::particle_floating_wall_candidates &particle_floating_wall_candidates, const AdaptiveSparseContacts< 2, DEM::DEMProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_floating_wall_contact_pairs< 3, DEM::DEMProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 3 >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< 3 > &particle_handler, const Parameters::Lagrangian::FloatingWalls< 3 > &floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 3 >::particle_floating_wall_candidates &particle_floating_wall_candidates, const AdaptiveSparseContacts< 3, DEM::DEMProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_floating_wall_contact_pairs< 2, DEM::CFDDEMProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 2 >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< 2 > &particle_handler, const Parameters::Lagrangian::FloatingWalls< 2 > &floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 2 >::particle_floating_wall_candidates &particle_floating_wall_candidates, const AdaptiveSparseContacts< 2, DEM::CFDDEMProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_floating_wall_contact_pairs< 3, DEM::CFDDEMProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 3 >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< 3 > &particle_handler, const Parameters::Lagrangian::FloatingWalls< 3 > &floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 3 >::particle_floating_wall_candidates &particle_floating_wall_candidates, const AdaptiveSparseContacts< 3, DEM::CFDDEMProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_floating_wall_contact_pairs< 2, DEM::DEMMPProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 2 >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< 2 > &particle_handler, const Parameters::Lagrangian::FloatingWalls< 2 > &floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 2 >::particle_floating_wall_candidates &particle_floating_wall_candidates, const AdaptiveSparseContacts< 2, DEM::DEMMPProperties::PropertiesIndex > &sparse_contacts_object)
template void find_particle_floating_wall_contact_pairs< 3, DEM::DEMMPProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 3 >::active_cell_iterator > > &boundary_cells_for_floating_walls, const Particles::ParticleHandler< 3 > &particle_handler, const Parameters::Lagrangian::FloatingWalls< 3 > &floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 3 >::particle_floating_wall_candidates &particle_floating_wall_candidates, const AdaptiveSparseContacts< 3, DEM::DEMMPProperties::PropertiesIndex > &sparse_contacts_object)
template void particle_solid_surfaces_contact_search< 2 > (const DEM::dem_data_structures< 2 >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< 2 > &particle_handler, DEM::dem_data_structures< 2 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 2 >::cells_total_neighbor_list &cells_total_neighbor_list)
template void particle_solid_surfaces_contact_search< 3 > (const DEM::dem_data_structures< 3 >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< 3 > &particle_handler, DEM::dem_data_structures< 3 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 3 >::cells_total_neighbor_list &cells_total_neighbor_list)
template void particle_solid_surfaces_contact_search< 2, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< 2 > &particle_handler, DEM::dem_data_structures< 2 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 2 >::cells_total_neighbor_list &cells_total_neighbor_list, const AdaptiveSparseContacts< 2, DEM::DEMProperties::PropertiesIndex > &sparse_contacts_object)
template void particle_solid_surfaces_contact_search< 3, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< 3 > &particle_handler, DEM::dem_data_structures< 3 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 3 >::cells_total_neighbor_list &cells_total_neighbor_list, const AdaptiveSparseContacts< 3, DEM::DEMProperties::PropertiesIndex > &sparse_contacts_object)
template void particle_solid_surfaces_contact_search< 2, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< 2 > &particle_handler, DEM::dem_data_structures< 2 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 2 >::cells_total_neighbor_list &cells_total_neighbor_list, const AdaptiveSparseContacts< 2, DEM::CFDDEMProperties::PropertiesIndex > &sparse_contacts_object)
template void particle_solid_surfaces_contact_search< 3, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< 3 > &particle_handler, DEM::dem_data_structures< 3 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 3 >::cells_total_neighbor_list &cells_total_neighbor_list, const AdaptiveSparseContacts< 3, DEM::CFDDEMProperties::PropertiesIndex > &sparse_contacts_object)
template void particle_solid_surfaces_contact_search< 2, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< 2 > &particle_handler, DEM::dem_data_structures< 2 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 2 >::cells_total_neighbor_list &cells_total_neighbor_list, const AdaptiveSparseContacts< 2, DEM::DEMMPProperties::PropertiesIndex > &sparse_contacts_object)
template void particle_solid_surfaces_contact_search< 3, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::solid_surfaces_mesh_information &solid_surfaces_mesh_information, const Particles::ParticleHandler< 3 > &particle_handler, DEM::dem_data_structures< 3 >::particle_floating_mesh_candidates &particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 3 >::cells_total_neighbor_list &cells_total_neighbor_list, const AdaptiveSparseContacts< 3, DEM::DEMMPProperties::PropertiesIndex > &sparse_contacts_object)
Function Documentation
find_particle_floating_wall_contact_pairs() [1/2]
template<int dim> void find_particle_floating_wall_contact_pairs (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< dim >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< dim > & particle_handler, const Parameters::Lagrangian::FloatingWalls< dim > & floating_wall_properties, const double simulation_time, typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates & particle_floating_wall_candidates)
Find a two-layered unordered map of particle iterators which shows the candidate particle-floating wall collision candidates. These collision pairs will be investigated in the fine search to check if they are in contact or not.
Parameters
boundary_cells_for_floating_walls Boundary cells located adjacent to floating walls
particle_handler Particle handler of particles located in boundary cells
floating_wall_properties Properties of the floating walls specified in the parameter handler file
simulation_time Simulation time
particle_floating_wall_candidates Output of particle-floating wall broad search which contains all the particle-floating wall collision candidates
Definition at line 60 of file particle_wall_broad_search.cc.
References Parameters::Lagrangian::FloatingWalls< dim >::time_end, and Parameters::Lagrangian::FloatingWalls< dim >::time_start.
find_particle_floating_wall_contact_pairs() [2/2]
template<int dim, typename PropertiesIndex > void find_particle_floating_wall_contact_pairs (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< dim >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< dim > & particle_handler, const Parameters::Lagrangian::FloatingWalls< dim > & floating_wall_properties, const double simulation_time, typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates & particle_floating_wall_candidates, const AdaptiveSparseContacts< dim, PropertiesIndex > & sparse_contacts_object)
Find a two-layered unordered map of particle iterators which shows the candidate particle-floating wall collision candidates. These collision pairs will be investigated in the fine search to check if they are in contact or not.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Parameters
boundary_cells_for_floating_walls Boundary cells located adjacent to floating walls
particle_handler Particle handler of particles located in boundary cells
floating_wall_properties Properties of the floating walls specified in the parameter handler file
simulation_time Simulation time
particle_floating_wall_candidates Output of particle-floating wall broad search which contains all the particle-floating wall collision candidates
sparse_contacts_object The object that contains the information about the mobility status of cells
Definition at line 268 of file particle_wall_broad_search.cc.
References AdaptiveSparseContacts< dim, PropertiesIndex >::check_cell_mobility(), Parameters::Lagrangian::FloatingWalls< dim >::time_end, and Parameters::Lagrangian::FloatingWalls< dim >::time_start.
find_particle_floating_wall_contact_pairs< 2 >()
template void find_particle_floating_wall_contact_pairs< 2 > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 2 >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< 2 > & particle_handler, const Parameters::Lagrangian::FloatingWalls< 2 > & floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 2 >::particle_floating_wall_candidates & particle_floating_wall_candidates)
find_particle_floating_wall_contact_pairs< 2, DEM::CFDDEMProperties::PropertiesIndex >()
template void find_particle_floating_wall_contact_pairs< 2, DEM::CFDDEMProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 2 >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< 2 > & particle_handler, const Parameters::Lagrangian::FloatingWalls< 2 > & floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 2 >::particle_floating_wall_candidates & particle_floating_wall_candidates, const AdaptiveSparseContacts< 2, DEM::CFDDEMProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_floating_wall_contact_pairs< 2, DEM::DEMMPProperties::PropertiesIndex >()
template void find_particle_floating_wall_contact_pairs< 2, DEM::DEMMPProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 2 >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< 2 > & particle_handler, const Parameters::Lagrangian::FloatingWalls< 2 > & floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 2 >::particle_floating_wall_candidates & particle_floating_wall_candidates, const AdaptiveSparseContacts< 2, DEM::DEMMPProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_floating_wall_contact_pairs< 2, DEM::DEMProperties::PropertiesIndex >()
template void find_particle_floating_wall_contact_pairs< 2, DEM::DEMProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 2 >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< 2 > & particle_handler, const Parameters::Lagrangian::FloatingWalls< 2 > & floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 2 >::particle_floating_wall_candidates & particle_floating_wall_candidates, const AdaptiveSparseContacts< 2, DEM::DEMProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_floating_wall_contact_pairs< 3 >()
template void find_particle_floating_wall_contact_pairs< 3 > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 3 >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< 3 > & particle_handler, const Parameters::Lagrangian::FloatingWalls< 3 > & floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 3 >::particle_floating_wall_candidates & particle_floating_wall_candidates)
find_particle_floating_wall_contact_pairs< 3, DEM::CFDDEMProperties::PropertiesIndex >()
template void find_particle_floating_wall_contact_pairs< 3, DEM::CFDDEMProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 3 >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< 3 > & particle_handler, const Parameters::Lagrangian::FloatingWalls< 3 > & floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 3 >::particle_floating_wall_candidates & particle_floating_wall_candidates, const AdaptiveSparseContacts< 3, DEM::CFDDEMProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_floating_wall_contact_pairs< 3, DEM::DEMMPProperties::PropertiesIndex >()
template void find_particle_floating_wall_contact_pairs< 3, DEM::DEMMPProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 3 >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< 3 > & particle_handler, const Parameters::Lagrangian::FloatingWalls< 3 > & floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 3 >::particle_floating_wall_candidates & particle_floating_wall_candidates, const AdaptiveSparseContacts< 3, DEM::DEMMPProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_floating_wall_contact_pairs< 3, DEM::DEMProperties::PropertiesIndex >()
template void find_particle_floating_wall_contact_pairs< 3, DEM::DEMProperties::PropertiesIndex > (const std::unordered_map< types::global_dof_index, std::set< typename Triangulation< 3 >::active_cell_iterator > > & boundary_cells_for_floating_walls, const Particles::ParticleHandler< 3 > & particle_handler, const Parameters::Lagrangian::FloatingWalls< 3 > & floating_wall_properties, const double simulation_time, DEM::dem_data_structures< 3 >::particle_floating_wall_candidates & particle_floating_wall_candidates, const AdaptiveSparseContacts< 3, DEM::DEMProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_wall_contact_pairs() [1/2]
template<int dim> void find_particle_wall_contact_pairs (const std::map< int, boundary_cells_info_struct< dim > > & boundary_cells_information, const Particles::ParticleHandler< dim > & particle_handler, typename DEM::dem_data_structures< dim >::particle_wall_candidates & particle_wall_contact_candidates)
Finds unordered map of tuples (tuple of particle located in boundary cells, normal vector of the boundary face, a point on the face and the corresponding boundary cell) which shows the candidate particle-wall collision pairs. These collision candidates will be investigated in the fine search to check if they are in contact or not.
Parameters
boundary_cells_information Information of the boundary cells and faces. This is the output of the FindBoundaryCellsInformation class.
particle_handler Particle handler of particles located in boundary cells.
particle_wall_contact_candidates A two-layered unordered map of tuples. Each tuple contains a particle located near boundaries, the normal vector of the corresponding face boundary, a point on the boundary and the boundary cell. The contact pair is used in the fine search.
Definition at line 10 of file particle_wall_broad_search.cc.
References store_candidates().
find_particle_wall_contact_pairs() [2/2]
template<int dim, typename PropertiesIndex > void find_particle_wall_contact_pairs (const std::map< int, boundary_cells_info_struct< dim > > & boundary_cells_information, const Particles::ParticleHandler< dim > & particle_handler, typename DEM::dem_data_structures< dim >::particle_wall_candidates & particle_wall_contact_candidates, const AdaptiveSparseContacts< dim, PropertiesIndex > & sparse_contacts_object)
Finds unordered map of tuples (tuple of particle located in boundary cells, normal vector of the boundary face, a point on the face and the corresponding boundary cell) which shows the candidate particle-wall collision pairs. These collision candidates will be investigated in the fine search to check if they are in contact or not.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Parameters
boundary_cells_information Information of the boundary cells and faces. This is the output of the FindBoundaryCellsInformation class.
particle_handler Particle handler of particles located in boundary cells.
particle_wall_contact_candidates A two-layered unordered map of tuples. Each tuple contains a particle located near boundaries, the normal vector of the corresponding face boundary, a point on the boundary and the boundary cell. The contact pair is used in the fine search.
sparse_contacts_object The object that contains the information about the mobility status of cells
Definition at line 215 of file particle_wall_broad_search.cc.
References AdaptiveSparseContacts< dim, PropertiesIndex >::check_cell_mobility(), and store_candidates().
find_particle_wall_contact_pairs< 2 >()
template void find_particle_wall_contact_pairs< 2 > (const std::map< int, boundary_cells_info_struct< 2 > > & boundary_cells_information, const Particles::ParticleHandler< 2 > & particle_handler, DEM::dem_data_structures< 2 >::particle_wall_candidates & particle_wall_contact_candidates)
find_particle_wall_contact_pairs< 2, DEM::CFDDEMProperties::PropertiesIndex >()
template void find_particle_wall_contact_pairs< 2, DEM::CFDDEMProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 2 > > & boundary_cells_information, const Particles::ParticleHandler< 2 > & particle_handler, DEM::dem_data_structures< 2 >::particle_wall_candidates & particle_wall_contact_candidates, const AdaptiveSparseContacts< 2, DEM::CFDDEMProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_wall_contact_pairs< 2, DEM::DEMMPProperties::PropertiesIndex >()
template void find_particle_wall_contact_pairs< 2, DEM::DEMMPProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 2 > > & boundary_cells_information, const Particles::ParticleHandler< 2 > & particle_handler, DEM::dem_data_structures< 2 >::particle_wall_candidates & particle_wall_contact_candidates, const AdaptiveSparseContacts< 2, DEM::DEMMPProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_wall_contact_pairs< 2, DEM::DEMProperties::PropertiesIndex >()
template void find_particle_wall_contact_pairs< 2, DEM::DEMProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 2 > > & boundary_cells_information, const Particles::ParticleHandler< 2 > & particle_handler, DEM::dem_data_structures< 2 >::particle_wall_candidates & particle_wall_contact_candidates, const AdaptiveSparseContacts< 2, DEM::DEMProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_wall_contact_pairs< 3 >()
template void find_particle_wall_contact_pairs< 3 > (const std::map< int, boundary_cells_info_struct< 3 > > & boundary_cells_information, const Particles::ParticleHandler< 3 > & particle_handler, DEM::dem_data_structures< 3 >::particle_wall_candidates & particle_wall_contact_candidates)
find_particle_wall_contact_pairs< 3, DEM::CFDDEMProperties::PropertiesIndex >()
template void find_particle_wall_contact_pairs< 3, DEM::CFDDEMProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 3 > > & boundary_cells_information, const Particles::ParticleHandler< 3 > & particle_handler, DEM::dem_data_structures< 3 >::particle_wall_candidates & particle_wall_contact_candidates, const AdaptiveSparseContacts< 3, DEM::CFDDEMProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_wall_contact_pairs< 3, DEM::DEMMPProperties::PropertiesIndex >()
template void find_particle_wall_contact_pairs< 3, DEM::DEMMPProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 3 > > & boundary_cells_information, const Particles::ParticleHandler< 3 > & particle_handler, DEM::dem_data_structures< 3 >::particle_wall_candidates & particle_wall_contact_candidates, const AdaptiveSparseContacts< 3, DEM::DEMMPProperties::PropertiesIndex > & sparse_contacts_object)
find_particle_wall_contact_pairs< 3, DEM::DEMProperties::PropertiesIndex >()
template void find_particle_wall_contact_pairs< 3, DEM::DEMProperties::PropertiesIndex > (const std::map< int, boundary_cells_info_struct< 3 > > & boundary_cells_information, const Particles::ParticleHandler< 3 > & particle_handler, DEM::dem_data_structures< 3 >::particle_wall_candidates & particle_wall_contact_candidates, const AdaptiveSparseContacts< 3, DEM::DEMProperties::PropertiesIndex > & sparse_contacts_object)
particle_solid_surfaces_contact_search() [1/2]
template<int dim> void particle_solid_surfaces_contact_search (const typename DEM::dem_data_structures< dim >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< dim > & particle_handler, typename DEM::dem_data_structures< dim >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, typename DEM::dem_data_structures< dim >::cells_total_neighbor_list & cells_total_neighbor_list)
Find a two-layered unordered map (particle_floating_mesh_contact_candidates) of particle iterators that shows the candidate particle-floating mesh collision candidates. These collision pairs will be investigated in the fine search to check if they are in contact or not.
Parameters
solid_surfaces_mesh_information Information of the solid surfaces mapped in the background triangulation.
particle_handler
particle_floating_mesh_contact_candidates Particle-floating mesh contact candidates.
cells_total_neighbor_list A container in which all the neighbor cells of the local cells are stored.
Definition at line 129 of file particle_wall_broad_search.cc.
particle_solid_surfaces_contact_search() [2/2]
template<int dim, typename PropertiesIndex > void particle_solid_surfaces_contact_search (const typename DEM::dem_data_structures< dim >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< dim > & particle_handler, typename DEM::dem_data_structures< dim >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, typename DEM::dem_data_structures< dim >::cells_total_neighbor_list & cells_total_neighbor_list, const AdaptiveSparseContacts< dim, PropertiesIndex > & sparse_contacts_object)
Find a two-layered unordered map (particle_floating_mesh_contact_candidates) of particle iterators that shows the candidate particle-floating mesh collision candidates. These collision pairs will be investigated in the fine search to check if they are in contact or not.
Template Parameters
dim An integer that denotes the number of spatial dimensions.
PropertiesIndex Index of the properties used within the ParticleHandler.
Parameters
solid_surfaces_mesh_information Information of the solid surfaces mapped in the background triangulation.
particle_handler
particle_floating_mesh_contact_candidates Particle-floating mesh contact candidates
cells_total_neighbor_list A container in which all the neighbor cells of the local cells are stored
sparse_contacts_object The object that contains the information about the mobility status of cells
Definition at line 340 of file particle_wall_broad_search.cc.
References AdaptiveSparseContacts< dim, PropertiesIndex >::check_cell_mobility().
particle_solid_surfaces_contact_search< 2 >()
template void particle_solid_surfaces_contact_search< 2 > (const DEM::dem_data_structures< 2 >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< 2 > & particle_handler, DEM::dem_data_structures< 2 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 2 >::cells_total_neighbor_list & cells_total_neighbor_list)
particle_solid_surfaces_contact_search< 2, DEM::CFDDEMProperties::PropertiesIndex >()
template void particle_solid_surfaces_contact_search< 2, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< 2 > & particle_handler, DEM::dem_data_structures< 2 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 2 >::cells_total_neighbor_list & cells_total_neighbor_list, const AdaptiveSparseContacts< 2, DEM::CFDDEMProperties::PropertiesIndex > & sparse_contacts_object)
particle_solid_surfaces_contact_search< 2, DEM::DEMMPProperties::PropertiesIndex >()
template void particle_solid_surfaces_contact_search< 2, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< 2 > & particle_handler, DEM::dem_data_structures< 2 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 2 >::cells_total_neighbor_list & cells_total_neighbor_list, const AdaptiveSparseContacts< 2, DEM::DEMMPProperties::PropertiesIndex > & sparse_contacts_object)
particle_solid_surfaces_contact_search< 2, DEM::DEMProperties::PropertiesIndex >()
template void particle_solid_surfaces_contact_search< 2, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 2 >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< 2 > & particle_handler, DEM::dem_data_structures< 2 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 2 >::cells_total_neighbor_list & cells_total_neighbor_list, const AdaptiveSparseContacts< 2, DEM::DEMProperties::PropertiesIndex > & sparse_contacts_object)
particle_solid_surfaces_contact_search< 3 >()
template void particle_solid_surfaces_contact_search< 3 > (const DEM::dem_data_structures< 3 >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< 3 > & particle_handler, DEM::dem_data_structures< 3 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 3 >::cells_total_neighbor_list & cells_total_neighbor_list)
particle_solid_surfaces_contact_search< 3, DEM::CFDDEMProperties::PropertiesIndex >()
template void particle_solid_surfaces_contact_search< 3, DEM::CFDDEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< 3 > & particle_handler, DEM::dem_data_structures< 3 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 3 >::cells_total_neighbor_list & cells_total_neighbor_list, const AdaptiveSparseContacts< 3, DEM::CFDDEMProperties::PropertiesIndex > & sparse_contacts_object)
particle_solid_surfaces_contact_search< 3, DEM::DEMMPProperties::PropertiesIndex >()
template void particle_solid_surfaces_contact_search< 3, DEM::DEMMPProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< 3 > & particle_handler, DEM::dem_data_structures< 3 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 3 >::cells_total_neighbor_list & cells_total_neighbor_list, const AdaptiveSparseContacts< 3, DEM::DEMMPProperties::PropertiesIndex > & sparse_contacts_object)
particle_solid_surfaces_contact_search< 3, DEM::DEMProperties::PropertiesIndex >()
template void particle_solid_surfaces_contact_search< 3, DEM::DEMProperties::PropertiesIndex > (const DEM::dem_data_structures< 3 >::solid_surfaces_mesh_information & solid_surfaces_mesh_information, const Particles::ParticleHandler< 3 > & particle_handler, DEM::dem_data_structures< 3 >::particle_floating_mesh_candidates & particle_floating_mesh_contact_candidates, DEM::dem_data_structures< 3 >::cells_total_neighbor_list & cells_total_neighbor_list, const AdaptiveSparseContacts< 3, DEM::DEMProperties::PropertiesIndex > & sparse_contacts_object)
store_candidates()
template<int dim> void store_candidates (const typename Particles::ParticleHandler< dim >::particle_iterator_range::iterator & particle_iterator, const DEM::global_face_id & floating_wall_id, typename DEM::dem_data_structures< dim >::particle_floating_wall_candidates & contact_pair_candidates) inline
Store the candidate particle-floating wall contact pairs.
Parameters
particle_iterator The particle iterator to start boundary id.
floating_wall_id The floating wall id.
contact_pair_candidates A map which will contain all the particle/wall pairs candidate.
Definition at line 424 of file particle_wall_broad_search.cc.