Lethe Open-Source Library: /home/runner/work/lethe/lethe/include/dem/particle_particle_heat_transfer.h File Reference
particle_particle_heat_transfer.h File Reference
#include <core/auxiliary_math_functions.h>
#include <boost/math/special_functions/erf.hpp>
#include <float.h>
#include <cmath>
#include <iostream>
Functions
double calculate_corrected_contact_radius (const double effective_radius, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double normal_force_norm)
double calculate_macrocontact_resistance (const double harmonic_particle_conductivity, const double contact_radius)
double calculate_microcontact_resistance (const double equivalent_surface_slope, const double equivalent_surface_roughness, const double effective_microhardness, const double contact_radius_squared, const double harmonic_particle_conductivity, const double maximum_pressure)
double calculate_solid_macrogap_resistance (const double radius_one, const double radius_two, const double thermal_conductivity_one, const double thermal_conductivity_two, const double contact_radius_squared)
double calculate_interstitial_gas_microgap_resistance (const double equivalent_surface_roughness, const double contact_radius_squared, const double gas_parameter_m, const double thermal_conductivity_gas, const double maximum_pressure, const double effective_microhardness)
double calculate_interstitial_gas_macrogap_resistance (const double harmonic_radius, const double thermal_conductivity_gas, const double contact_radius_squared, const double gas_parameter_m)
void calculate_contact_thermal_conductance (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double &thermal_conductance)
void apply_heat_transfer_on_local_particles (const double temperature_one, const double temperature_two, const double thermal_conductance, double &particle_one_heat_transfer, double &particle_two_heat_transfer)
void apply_heat_transfer_on_single_local_particle (const double temperature_one, const double temperature_two, const double thermal_conductance, double &particle_one_heat_transfer)
Function Documentation
apply_heat_transfer_on_local_particles()
void apply_heat_transfer_on_local_particles (const double temperature_one, const double temperature_two, const double thermal_conductance, double & particle_one_heat_transfer, double & particle_two_heat_transfer)
Apply the heat transfer to the local-local particle pair in contact.
Parameters
[in] temperature_one Temperature of particle one.
[in] temperature_two Temperature of particle two.
[in] thermal_conductance Total thermal conductance between the two particles.
[in,out] particle_one_heat_transfer Heat transfer due to contact applied to particle one.
[in,out] particle_two_heat_transfer Heat transfer due to contact applied to particle two.
Definition at line 208 of file particle_particle_heat_transfer.cc.
References heat_transfer.
apply_heat_transfer_on_single_local_particle()
void apply_heat_transfer_on_single_local_particle (const double temperature_one, const double temperature_two, const double thermal_conductance, double & particle_one_heat_transfer)
Apply the heat transfer to the local-ghost particle pair in contact. The heat transfer is only applied to the local particle, thus particle one should be the local particle here.
Parameters
[in] temperature_one Temperature of particle one.
[in] temperature_two Temperature of particle two.
[in] thermal_conductance Total thermal conductance between the two particles.
[in,out] particle_one_heat_transfer Heat transfer due to contact applied to particle one.
Definition at line 221 of file particle_particle_heat_transfer.cc.
calculate_contact_thermal_conductance()
void calculate_contact_thermal_conductance (const double radius_one, const double radius_two, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double equivalent_surface_roughness, const double equivalent_surface_slope, const double effective_microhardness, const double thermal_conductivity_one, const double thermal_conductivity_two, const double thermal_conductivity_gas, const double gas_parameter_m, const double normal_overlap, const double normal_force_norm, double & thermal_conductance)
Calculate the total thermal conductance between two particles.
Parameters
[in] radius_one Radius of particle one.
[in] radius_two Radius of particle two.
[in] effective_youngs_modulus Effective young's modulus of the two particles.
[in] effective_real_youngs_modulus Effective real young's modulus of the two particles.
[in] equivalent_surface_roughness Equivalent value of the two particles' surface roughness.
[in] equivalent_surface_slope Equivalent value of the two particles' surface slope.
[in] effective_microhardness Effective microhardness of the two particles.
[in] thermal_conductivity_one Thermal conductivity of particle one.
[in] thermal_conductivity_two Thermal conductivity of particle two.
[in] thermal_conductivity_gas Thermal conductivity of the interstitial gas.
[in] gas_parameter_m Gas parameter.
[in] normal_overlap Normal overlap between the two particles.
[in] normal_force_norm Norm of the normal contact force between the two particles.
[out] thermal_conductance Total thermal conductance between the two particles.
Definition at line 124 of file particle_particle_heat_transfer.cc.
References calculate_corrected_contact_radius(), calculate_interstitial_gas_macrogap_resistance(), calculate_interstitial_gas_microgap_resistance(), calculate_macrocontact_resistance(), calculate_microcontact_resistance(), calculate_solid_macrogap_resistance(), and harmonic_mean().
calculate_corrected_contact_radius()
double calculate_corrected_contact_radius (const double effective_radius, const double effective_youngs_modulus, const double effective_real_youngs_modulus, const double normal_force_norm)
Calculate the corrected contact radius between two particles.
Parameters
[in] effective_radius Effective radius of the two particles.
[in] effective_youngs_modulus Effective young's modulus of the two particles.
[in] effective_real_youngs_modulus Effective real young's modulus of the two particles.
[in] normal_force_norm Norm of the normal contact force between the two particles.
Returns
Corrected contact radius of the two particles.
Definition at line 7 of file particle_particle_heat_transfer.cc.
calculate_interstitial_gas_macrogap_resistance()
double calculate_interstitial_gas_macrogap_resistance (const double harmonic_radius, const double thermal_conductivity_gas, const double contact_radius_squared, const double gas_parameter_m)
Calculate the interstitial gas macrogap thermal resistance between two particles.
Parameters
[in] harmonic_radius Harmonic mean of the particles' radii.
[in] thermal_conductivity_gas Thermal conductivity of the interstitial gas.
[in] contact_radius_squared Squared contact radius of the two particles.
[in] gas_parameter_m Gas parameter.
Returns
Interstitial gas microgap thermal resistance between the two particles.
Definition at line 109 of file particle_particle_heat_transfer.cc.
calculate_interstitial_gas_microgap_resistance()
double calculate_interstitial_gas_microgap_resistance (const double equivalent_surface_roughness, const double contact_radius_squared, const double gas_parameter_m, const double thermal_conductivity_gas, const double maximum_pressure, const double effective_microhardness)
Calculate the interstitial gas microgap thermal resistance between two particles.
Parameters
[in] equivalent_surface_roughness Equivalent value of the two particles' surface roughness.
[in] contact_radius_squared Squared contact radius of the two particles.
[in] gas_parameter_m Gas parameter.
[in] thermal_conductivity_gas Thermal conductivity of the interstitial gas.
[in] maximum_pressure Maximum pressure for hertzian contacts.
[in] effective_microhardness Effective microhardness of the two particles.
Returns
Interstitial gas microgap thermal resistance between the two particles.
Definition at line 76 of file particle_particle_heat_transfer.cc.
calculate_macrocontact_resistance()
double calculate_macrocontact_resistance (const double harmonic_particle_conductivity, const double contact_radius)
Calculate the macrocontact thermal resistance between two particles.
Parameters
[in] harmonic_particle_conductivity Harmonic mean of the two particles' thermal conductivities.
[in] contact_radius Contact radius of the two particles.
Returns
Macrocontact thermal resistance between the two particles.
Definition at line 27 of file particle_particle_heat_transfer.cc.
calculate_microcontact_resistance()
double calculate_microcontact_resistance (const double equivalent_surface_slope, const double equivalent_surface_roughness, const double effective_microhardness, const double contact_radius_squared, const double harmonic_particle_conductivity, const double maximum_pressure)
Calculate the microcontact thermal resistance between two particles.
Parameters
[in] equivalent_surface_slope Equivalent value of the two particles' surface slope.
[in] equivalent_surface_roughness Equivalent value of the two particles' surface roughness.
[in] effective_microhardness Effective microhardness of the two particles.
[in] contact_radius_squared Squared contact radius of the two particles.
[in] harmonic_particle_conductivity Harmonic mean of the two particles' thermal conductivities.
[in] maximum_pressure Maximum pressure for hertzian contacts.
Returns
Microcontact thermal resistance between the two particles.
Definition at line 34 of file particle_particle_heat_transfer.cc.
calculate_solid_macrogap_resistance()
double calculate_solid_macrogap_resistance (const double radius_one, const double radius_two, const double thermal_conductivity_one, const double thermal_conductivity_two, const double contact_radius_squared)
Calculate the solid macrogap thermal resistance between two particles.
Parameters
[in] radius_one Radius of particle one.
[in] radius_two Radius of particle two.
[in] thermal_conductivity_one Thermal conductivity of particle one.
[in] thermal_conductivity_two Thermal conductivity of particle two.
[in] contact_radius_squared Squared contact radius of the two particles.
Returns
Solid macrogap thermal resistance between the two particles.
Definition at line 54 of file particle_particle_heat_transfer.cc.