Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/solvers/postprocessing_cfd.cc File Reference
postprocessing_cfd.cc File Reference
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/lac/dynamic_sparsity_pattern.h>
#include <deal.II/lac/vector.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/dofs/dof_accessor.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/lac/trilinos_parallel_block_vector.h>
#include <deal.II/lac/trilinos_vector.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_system.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_q.h>
#include <core/boundary_conditions.h>
#include <core/parameters.h>
#include <core/rheological_model.h>
#include <core/vector.h>
#include <solvers/postprocessing_cfd.h>
Functions
template<int dim, typename VectorType >
std::pair< double, double > calculate_pressure_drop (const DoFHandler< dim > &dof_handler, const Mapping< dim > &mapping, const VectorType &evaluation_point, const Quadrature< dim > &cell_quadrature_formula, const Quadrature< dim - 1 > &face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
template std::pair< double, double > calculate_pressure_drop< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const Mapping< 2 > &mapping, const GlobalVectorType &evaluation_point, const Quadrature< 2 > &cell_quadrature_formula, const Quadrature< 1 > &face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
template std::pair< double, double > calculate_pressure_drop< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const Mapping< 3 > &mapping, const GlobalVectorType &evaluation_point, const Quadrature< 3 > &cell_quadrature_formula, const Quadrature< 2 > &face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
template std::pair< double, double > calculate_pressure_drop< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const Mapping< 2 > &mapping, const GlobalBlockVectorType &evaluation_point, const Quadrature< 2 > &cell_quadrature_formula, const Quadrature< 1 > &face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
template std::pair< double, double > calculate_pressure_drop< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const Mapping< 3 > &mapping, const GlobalBlockVectorType &evaluation_point, const Quadrature< 3 > &cell_quadrature_formula, const Quadrature< 2 > &face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
template std::pair< double, double > calculate_pressure_drop< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const Mapping< 2 > &mapping, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 2 > &cell_quadrature_formula, const Quadrature< 1 > &face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
template std::pair< double, double > calculate_pressure_drop< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const Mapping< 3 > &mapping, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 3 > &cell_quadrature_formula, const Quadrature< 2 > &face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
template<int dim, typename VectorType >
double calculate_CFL (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const double time_step, const Quadrature< dim > &quadrature_formula, const Mapping< dim > &mapping)
template double calculate_CFL< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &evaluation_point, const double time_step, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_CFL< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &evaluation_point, const double time_step, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_CFL< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const double time_step, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_CFL< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const double time_step, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_CFL< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const double time_step, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_CFL< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const double time_step, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
double calculate_enstrophy (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const Quadrature< dim > &quadrature_formula, const Mapping< dim > &mapping)
template double calculate_enstrophy< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_enstrophy< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_enstrophy< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_enstrophy< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_enstrophy< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_enstrophy< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
double calculate_pressure_power (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const Quadrature< dim > &quadrature_formula, const Mapping< dim > &mapping)
template double calculate_pressure_power< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_pressure_power< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_pressure_power< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_pressure_power< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_pressure_power< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_pressure_power< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
double calculate_viscous_dissipation (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const Quadrature< dim > &quadrature_formula, const Mapping< dim > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_viscous_dissipation< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_viscous_dissipation< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_viscous_dissipation< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_viscous_dissipation< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_viscous_dissipation< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_viscous_dissipation< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping, const PhysicalPropertiesManager &properties_manager)
template<int dim, typename VectorType >
double calculate_kinetic_energy (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const Quadrature< dim > &quadrature_formula, const Mapping< dim > &mapping)
template double calculate_kinetic_energy< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_kinetic_energy< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_kinetic_energy< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_kinetic_energy< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_kinetic_energy< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_kinetic_energy< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
double calculate_apparent_viscosity (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const Quadrature< dim > &quadrature_formula, const Mapping< dim > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_apparent_viscosity< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_apparent_viscosity< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_apparent_viscosity< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_apparent_viscosity< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_apparent_viscosity< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping, const PhysicalPropertiesManager &properties_manager)
template double calculate_apparent_viscosity< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping, const PhysicalPropertiesManager &properties_manager)
template<int dim, typename VectorType >
std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > calculate_forces (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< dim > &boundary_conditions, const Quadrature< dim - 1 > &face_quadrature_formula, const Mapping< dim > &mapping)
template std::vector< std::map< types::boundary_id, Tensor< 1, 2 > > > calculate_forces< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > &boundary_conditions, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::vector< std::map< types::boundary_id, Tensor< 1, 3 > > > calculate_forces< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > &boundary_conditions, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template std::vector< std::map< types::boundary_id, Tensor< 1, 2 > > > calculate_forces< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > &boundary_conditions, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::vector< std::map< types::boundary_id, Tensor< 1, 3 > > > calculate_forces< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > &boundary_conditions, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template std::vector< std::map< types::boundary_id, Tensor< 1, 2 > > > calculate_forces< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > &boundary_conditions, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::vector< std::map< types::boundary_id, Tensor< 1, 3 > > > calculate_forces< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > &boundary_conditions, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< dim > &boundary_conditions, const Quadrature< dim - 1 > &face_quadrature_formula, const Mapping< dim > &mapping)
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 2, GlobalVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > &boundary_conditions, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 3, GlobalVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > &boundary_conditions, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 2, GlobalBlockVectorType > (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > &boundary_conditions, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 3, GlobalBlockVectorType > (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > &boundary_conditions, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > &boundary_conditions, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &evaluation_point, const PhysicalPropertiesManager &properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > &boundary_conditions, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
std::pair< double, double > calculate_L2_error (const DoFHandler< dim > &dof_handler, const VectorType &evaluation_point, const Function< dim > *exact_solution, const Quadrature< dim > &quadrature_formula, const Mapping< dim > &mapping)
template std::pair< double, double > calculate_L2_error (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &present_solution, const Function< 2 > *l_exact_solution, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template std::pair< double, double > calculate_L2_error (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &present_solution, const Function< 3 > *l_exact_solution, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template std::pair< double, double > calculate_L2_error (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &present_solution, const Function< 2 > *l_exact_solution, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template std::pair< double, double > calculate_L2_error (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &present_solution, const Function< 3 > *l_exact_solution, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template std::pair< double, double > calculate_L2_error (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &present_solution, const Function< 2 > *l_exact_solution, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template std::pair< double, double > calculate_L2_error (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &present_solution, const Function< 3 > *l_exact_solution, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
std::pair< double, double > calculate_flow_rate (const DoFHandler< dim > &dof_handler, const VectorType &present_solution, const unsigned int &boundary_id, const Quadrature< dim - 1 > &face_quadrature_formula, const Mapping< dim > &mapping)
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &present_solution, const unsigned int &boundary_id, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &present_solution, const unsigned int &boundary_id, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &present_solution, const unsigned int &boundary_id, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &present_solution, const unsigned int &boundary_id, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &present_solution, const unsigned int &boundary_id, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &present_solution, const unsigned int &boundary_id, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
double calculate_average_velocity (const DoFHandler< dim > &dof_handler, const VectorType &present_solution, const unsigned int &boundary_id, const Quadrature< dim - 1 > &face_quadrature_formula, const Mapping< dim > &mapping)
template double calculate_average_velocity (const DoFHandler< 2 > &dof_handler, const GlobalVectorType &present_solution, const unsigned int &boundary_id, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_average_velocity (const DoFHandler< 3 > &dof_handler, const GlobalVectorType &present_solution, const unsigned int &boundary_id, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_average_velocity (const DoFHandler< 2 > &dof_handler, const GlobalBlockVectorType &present_solution, const unsigned int &boundary_id, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_average_velocity (const DoFHandler< 3 > &dof_handler, const GlobalBlockVectorType &present_solution, const unsigned int &boundary_id, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_average_velocity (const DoFHandler< 2 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &present_solution, const unsigned int &boundary_id, const Quadrature< 1 > &face_quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_average_velocity (const DoFHandler< 3 > &dof_handler, const LinearAlgebra::distributed::Vector< double > &present_solution, const unsigned int &boundary_id, const Quadrature< 2 > &face_quadrature_formula, const Mapping< 3 > &mapping)
template<int dim, typename VectorType >
double calculate_average_velocity (const DoFHandler< dim > &dof_handler, const DoFHandler< dim > &void_fraction_dof_handler, const VectorType &present_solution, const VectorType &present_void_fraction_solution, const unsigned int &flow_direction, const Quadrature< dim > &quadrature_formula, const Mapping< dim > &mapping)
template double calculate_average_velocity (const DoFHandler< 2 > &dof_handler, const DoFHandler< 2 > &void_fraction_dof_handler, const GlobalVectorType &present_solution, const GlobalVectorType &present_void_fraction_solution, const unsigned int &flow_direction, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_average_velocity (const DoFHandler< 3 > &dof_handler, const DoFHandler< 3 > &void_fraction_dof_handler, const GlobalVectorType &present_solution, const GlobalVectorType &present_void_fraction_solution, const unsigned int &flow_direction, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
template double calculate_average_velocity (const DoFHandler< 2 > &dof_handler, const DoFHandler< 2 > &void_fraction_dof_handler, const LinearAlgebra::distributed::Vector< double > &present_solution, const LinearAlgebra::distributed::Vector< double > &present_void_fraction_solution, const unsigned int &flow_direction, const Quadrature< 2 > &quadrature_formula, const Mapping< 2 > &mapping)
template double calculate_average_velocity (const DoFHandler< 3 > &dof_handler, const DoFHandler< 3 > &void_fraction_dof_handler, const LinearAlgebra::distributed::Vector< double > &present_solution, const LinearAlgebra::distributed::Vector< double > &present_void_fraction_solution, const unsigned int &flow_direction, const Quadrature< 3 > &quadrature_formula, const Mapping< 3 > &mapping)
Function Documentation
calculate_apparent_viscosity()
template<int dim, typename VectorType > double calculate_apparent_viscosity (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const Quadrature< dim > & quadrature_formula, const Mapping< dim > & mapping, const PhysicalPropertiesManager & properties_manager)
Calculates the apparent viscosity of the fluid for non Newtonian flows.
Returns
the apparent viscosity Post-processing function
Parameters
dof_handler The dof_handler used for the calculation
evaluation_point The solution at which the force is calculated
quadrature_formula The quadrature formula for the calculation
mapping The mapping of the simulation
physical_properties The parameters containing the required physical properties
Definition at line 757 of file postprocessing_cfd.cc.
References calculate_shear_rate_magnitude(), PhysicalPropertiesManager::get_rheology(), shear_rate, and velocity.
calculate_apparent_viscosity< 2, GlobalBlockVectorType >()
template double calculate_apparent_viscosity< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_apparent_viscosity< 2, GlobalVectorType >()
template double calculate_apparent_viscosity< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_apparent_viscosity< 2, LinearAlgebra::distributed::Vector< double > >()
template double calculate_apparent_viscosity< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_apparent_viscosity< 3, GlobalBlockVectorType >()
template double calculate_apparent_viscosity< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_apparent_viscosity< 3, GlobalVectorType >()
template double calculate_apparent_viscosity< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_apparent_viscosity< 3, LinearAlgebra::distributed::Vector< double > >()
template double calculate_apparent_viscosity< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_average_velocity() [1/12]
template double calculate_average_velocity (const DoFHandler< 2 > & dof_handler, const DoFHandler< 2 > & void_fraction_dof_handler, const GlobalVectorType & present_solution, const GlobalVectorType & present_void_fraction_solution, const unsigned int & flow_direction, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_average_velocity() [2/12]
template double calculate_average_velocity (const DoFHandler< 2 > & dof_handler, const DoFHandler< 2 > & void_fraction_dof_handler, const LinearAlgebra::distributed::Vector< double > & present_solution, const LinearAlgebra::distributed::Vector< double > & present_void_fraction_solution, const unsigned int & flow_direction, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_average_velocity() [3/12]
template double calculate_average_velocity (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & present_solution, const unsigned int & boundary_id, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_average_velocity() [4/12]
template double calculate_average_velocity (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & present_solution, const unsigned int & boundary_id, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_average_velocity() [5/12]
template double calculate_average_velocity (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & present_solution, const unsigned int & boundary_id, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_average_velocity() [6/12]
template double calculate_average_velocity (const DoFHandler< 3 > & dof_handler, const DoFHandler< 3 > & void_fraction_dof_handler, const GlobalVectorType & present_solution, const GlobalVectorType & present_void_fraction_solution, const unsigned int & flow_direction, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_average_velocity() [7/12]
template double calculate_average_velocity (const DoFHandler< 3 > & dof_handler, const DoFHandler< 3 > & void_fraction_dof_handler, const LinearAlgebra::distributed::Vector< double > & present_solution, const LinearAlgebra::distributed::Vector< double > & present_void_fraction_solution, const unsigned int & flow_direction, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_average_velocity() [8/12]
template double calculate_average_velocity (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & present_solution, const unsigned int & boundary_id, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_average_velocity() [9/12]
template double calculate_average_velocity (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & present_solution, const unsigned int & boundary_id, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_average_velocity() [10/12]
template double calculate_average_velocity (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & present_solution, const unsigned int & boundary_id, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_average_velocity() [11/12]
template<int dim, typename VectorType > double calculate_average_velocity (const DoFHandler< dim > & dof_handler, const DoFHandler< dim > & void_fraction_dof_handler, const VectorType & present_solution, const VectorType & present_void_fraction_solution, const unsigned int & flow_direction, const Quadrature< dim > & quadrature_formula, const Mapping< dim > & mapping)
calculate_average_velocity. This function calculates the average velocity of the domain for the solver GLS VANS.
Ū = ∫ε(v⋅γ)dΩ/∫εdΩ Where Ū is the average velocity, ε is the void fraction, v is the velocity of the cell, γ is the vector of the cell (flow direction) and dΩ is the volume of the cell.
Parameters
dof_handler. The argument used to get velocity at quadrature points
void_fraction_dof_handler. The argument used to get void fraction at quadrature points
present_solution. The vector which contains the velocity values
present_void_fraction_solution. The vector which contains the void fraction values
flow_direction. The flow direction
quadrature_formula The quadrature formula for the calculation
mapping The mapping of the simulation
Definition at line 1552 of file postprocessing_cfd.cc.
References void_fraction.
calculate_average_velocity() [12/12]
template<int dim, typename VectorType > double calculate_average_velocity (const DoFHandler< dim > & dof_handler, const VectorType & present_solution, const unsigned int & boundary_id, const Quadrature< dim - 1 > & face_quadrature_formula, const Mapping< dim > & mapping)
calculate_average_velocity. This function calculates average velocity from the volumetric flow rate at the selected boundary.
Parameters
dof_handler. The argument used to get finite elements
present_solution. The vector which contains all the values to calculate the flow rate
boundary_id. The inlet boundary
face_quadrature_formula The face quadrature formula for the calculation
mapping The mapping of the simulation
Definition at line 1485 of file postprocessing_cfd.cc.
References calculate_flow_rate().
calculate_CFL()
template<int dim, typename VectorType > double calculate_CFL (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const double time_step, const Quadrature< dim > & quadrature_formula, const Mapping< dim > & mapping)
Calculate the CFL condition on the simulation domain.
Returns
CFL maximal value in the domain Post-processing function This function calculates the maximal CFL value in the domain
Parameters
dof_handler The dof_handler used for the calculation
evaluation_point The solution for which the CFL is calculated. The velocity field is assumed to be the first field.
quadrature_formula The quadrature formula for the calculation
mapping The mapping of the simulation
Definition at line 234 of file postprocessing_cfd.cc.
References compute_cell_measure_with_JxW().
calculate_CFL< 2, GlobalBlockVectorType >()
template double calculate_CFL< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const double time_step, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_CFL< 2, GlobalVectorType >()
template double calculate_CFL< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & evaluation_point, const double time_step, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_CFL< 2, LinearAlgebra::distributed::Vector< double > >()
template double calculate_CFL< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const double time_step, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_CFL< 3, GlobalBlockVectorType >()
template double calculate_CFL< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const double time_step, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_CFL< 3, GlobalVectorType >()
template double calculate_CFL< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & evaluation_point, const double time_step, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_CFL< 3, LinearAlgebra::distributed::Vector< double > >()
template double calculate_CFL< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const double time_step, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_enstrophy()
template<int dim, typename VectorType > double calculate_enstrophy (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const Quadrature< dim > & quadrature_formula, const Mapping< dim > & mapping)
Calculate the average enstrophy in the simulation domain.
Returns
average kinetic energy in the domain Post-processing function This function calculates the average enstrophy in the simulation domain
Parameters
dof_handler The dof_handler used for the calculation
evaluation_point The solution at which the force is calculated
quadrature_formula The quadrature formula for the calculation
mapping The mapping of the simulation
Definition at line 339 of file postprocessing_cfd.cc.
calculate_enstrophy< 2, GlobalBlockVectorType >()
template double calculate_enstrophy< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_enstrophy< 2, GlobalVectorType >()
template double calculate_enstrophy< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_enstrophy< 2, LinearAlgebra::distributed::Vector< double > >()
template double calculate_enstrophy< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_enstrophy< 3, GlobalBlockVectorType >()
template double calculate_enstrophy< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_enstrophy< 3, GlobalVectorType >()
template double calculate_enstrophy< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_enstrophy< 3, LinearAlgebra::distributed::Vector< double > >()
template double calculate_enstrophy< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_flow_rate() [1/7]
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & present_solution, const unsigned int & boundary_id, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_flow_rate() [2/7]
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & present_solution, const unsigned int & boundary_id, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_flow_rate() [3/7]
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & present_solution, const unsigned int & boundary_id, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_flow_rate() [4/7]
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & present_solution, const unsigned int & boundary_id, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_flow_rate() [5/7]
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & present_solution, const unsigned int & boundary_id, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_flow_rate() [6/7]
template std::pair< double, double > calculate_flow_rate (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & present_solution, const unsigned int & boundary_id, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_flow_rate() [7/7]
template<int dim, typename VectorType > std::pair< double, double > calculate_flow_rate (const DoFHandler< dim > & dof_handler, const VectorType & present_solution, const unsigned int & boundary_id, const Quadrature< dim - 1 > & face_quadrature_formula, const Mapping< dim > & mapping)
calculate_flow_rate. This function calculates the volumetric flow rate at the selected boundary. It actually calculates the flow rate through the summation of the value at each cell surface with the normal vector, the velocity value and the area.
Parameters
dof_handler. The argument used to get finite elements
present_solution. The vector which contains all the values to calculate the flow rate
boundary_id. The inlet boundary
face_quadrature_formula The face quadrature formula for the calculation
mapping The mapping of the simulation
Definition at line 1380 of file postprocessing_cfd.cc.
calculate_forces()
template<int dim, typename VectorType > std::vector< std::map< types::boundary_id, Tensor< 1, dim > > > calculate_forces (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< dim > & boundary_conditions, const Quadrature< dim - 1 > & face_quadrature_formula, const Mapping< dim > & mapping)
Calculates the force due to the fluid motion on every boundary conditions.
Returns
std::vector of forces on each boundary condition Post-processing function This function calculates the force acting on each of the boundary conditions within the domain. It generates a vector which size is the number of boundary conditions
Parameters
dof_handler The dof_handler used for the calculation
evaluation_point The solution at which the force is calculated
physical_properties The parameters containing the required physical properties
boundary_conditions The boundary conditions object
face_quadrature_formula The face quadrature formula for the calculation
mapping The mapping of the simulation
Definition at line 882 of file postprocessing_cfd.cc.
References calculate_shear_rate_magnitude(), PhysicalPropertiesManager::get_rheology(), pressure, shear_rate, and BoundaryConditions::BoundaryConditions::type.
calculate_forces< 2, GlobalBlockVectorType >()
template std::vector< std::map< types::boundary_id, Tensor< 1, 2 > > > calculate_forces< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > & boundary_conditions, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_forces< 2, GlobalVectorType >()
template std::vector< std::map< types::boundary_id, Tensor< 1, 2 > > > calculate_forces< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > & boundary_conditions, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_forces< 2, LinearAlgebra::distributed::Vector< double > >()
template std::vector< std::map< types::boundary_id, Tensor< 1, 2 > > > calculate_forces< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > & boundary_conditions, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_forces< 3, GlobalBlockVectorType >()
template std::vector< std::map< types::boundary_id, Tensor< 1, 3 > > > calculate_forces< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > & boundary_conditions, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_forces< 3, GlobalVectorType >()
template std::vector< std::map< types::boundary_id, Tensor< 1, 3 > > > calculate_forces< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > & boundary_conditions, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_forces< 3, LinearAlgebra::distributed::Vector< double > >()
template std::vector< std::map< types::boundary_id, Tensor< 1, 3 > > > calculate_forces< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > & boundary_conditions, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_kinetic_energy()
template<int dim, typename VectorType > double calculate_kinetic_energy (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const Quadrature< dim > & quadrature_formula, const Mapping< dim > & mapping)
Calculate the average kinetic energy in the simulation domain.
Returns
average kinetic energy in the domain Post-processing function This function calculates the average kinetic energy in the simulation domain
Parameters
[in] dof_handler The dof_handler used for the calculation
[in] evaluation_point The solution for the calculation
[in] quadrature_formula The quadrature formula for the calculation
[in] mapping The mapping of the simulation
Definition at line 660 of file postprocessing_cfd.cc.
calculate_kinetic_energy< 2, GlobalBlockVectorType >()
template double calculate_kinetic_energy< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_kinetic_energy< 2, GlobalVectorType >()
template double calculate_kinetic_energy< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_kinetic_energy< 2, LinearAlgebra::distributed::Vector< double > >()
template double calculate_kinetic_energy< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_kinetic_energy< 3, GlobalBlockVectorType >()
template double calculate_kinetic_energy< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_kinetic_energy< 3, GlobalVectorType >()
template double calculate_kinetic_energy< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_kinetic_energy< 3, LinearAlgebra::distributed::Vector< double > >()
template double calculate_kinetic_energy< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_L2_error() [1/7]
template std::pair< double, double > calculate_L2_error (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & present_solution, const Function< 2 > * l_exact_solution, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_L2_error() [2/7]
template std::pair< double, double > calculate_L2_error (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & present_solution, const Function< 2 > * l_exact_solution, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_L2_error() [3/7]
template std::pair< double, double > calculate_L2_error (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & present_solution, const Function< 2 > * l_exact_solution, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_L2_error() [4/7]
template std::pair< double, double > calculate_L2_error (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & present_solution, const Function< 3 > * l_exact_solution, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_L2_error() [5/7]
template std::pair< double, double > calculate_L2_error (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & present_solution, const Function< 3 > * l_exact_solution, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_L2_error() [6/7]
template std::pair< double, double > calculate_L2_error (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & present_solution, const Function< 3 > * l_exact_solution, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_L2_error() [7/7]
template<int dim, typename VectorType > std::pair< double, double > calculate_L2_error (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const Function< dim > * exact_solution, const Quadrature< dim > & quadrature_formula, const Mapping< dim > & mapping)
Calculates the L2 norm of the error on velocity and pressure.
Returns
std::pair<double,double> containing the L2 norm of the error for velocity and pressure Post-processing function This function calculates the L2 norm of the error on the velocity and pressure. Since the pressure in GLS is defined up to a given constant, the mean solution of the pressure is removed from both the analytical and the numerical solution to ensure that the convergence can be monitored correctly.
Parameters
dof_handler The dof_handler used for the calculation.
evaluation_point The solution at which the torque is calculated.
exact_solution The exact solution, a function of dim+1 component for velocity + pressure
quadrature_formula The quadrature formula for the calculation.
mapping The mapping of the simulation.
Definition at line 1221 of file postprocessing_cfd.cc.
References pressure.
calculate_pressure_drop()
template<int dim, typename VectorType > std::pair< double, double > calculate_pressure_drop (const DoFHandler< dim > & dof_handler, const Mapping< dim > & mapping, const VectorType & evaluation_point, const Quadrature< dim > & cell_quadrature_formula, const Quadrature< dim - 1 > & face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
Calculate the pressure drop and total pressure drop between two boundaries. The pressure drop thus calculated has units of Length^2/Time^2.
Returns
Pressure drop of the flow between two boundaries of the domain
Parameters
dof_handler The dof_handler used for the calculation
evaluation_point The solution for which the pressure drop is calculated. The velocity field is assumed to be the "dim" field
cell_quadrature_formula The cell quadrature formula for the calculation
face_quadrature_formula The face quadrature formula for the calculation
mapping The mapping of the simulation
inlet_boundary_id The id of the inlet boundary
outlet_boundary_id The id of the outlet boundary
Definition at line 41 of file postprocessing_cfd.cc.
References pressure.
calculate_pressure_drop< 2, GlobalBlockVectorType >()
template std::pair< double, double > calculate_pressure_drop< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const Mapping< 2 > & mapping, const GlobalBlockVectorType & evaluation_point, const Quadrature< 2 > & cell_quadrature_formula, const Quadrature< 1 > & face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
calculate_pressure_drop< 2, GlobalVectorType >()
template std::pair< double, double > calculate_pressure_drop< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const Mapping< 2 > & mapping, const GlobalVectorType & evaluation_point, const Quadrature< 2 > & cell_quadrature_formula, const Quadrature< 1 > & face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
calculate_pressure_drop< 2, LinearAlgebra::distributed::Vector< double > >()
template std::pair< double, double > calculate_pressure_drop< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const Mapping< 2 > & mapping, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 2 > & cell_quadrature_formula, const Quadrature< 1 > & face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
calculate_pressure_drop< 3, GlobalBlockVectorType >()
template std::pair< double, double > calculate_pressure_drop< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const Mapping< 3 > & mapping, const GlobalBlockVectorType & evaluation_point, const Quadrature< 3 > & cell_quadrature_formula, const Quadrature< 2 > & face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
calculate_pressure_drop< 3, GlobalVectorType >()
template std::pair< double, double > calculate_pressure_drop< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const Mapping< 3 > & mapping, const GlobalVectorType & evaluation_point, const Quadrature< 3 > & cell_quadrature_formula, const Quadrature< 2 > & face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
calculate_pressure_drop< 3, LinearAlgebra::distributed::Vector< double > >()
template std::pair< double, double > calculate_pressure_drop< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const Mapping< 3 > & mapping, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 3 > & cell_quadrature_formula, const Quadrature< 2 > & face_quadrature_formula, const unsigned int inlet_boundary_id, const unsigned int outlet_boundary_id)
calculate_pressure_power()
template<int dim, typename VectorType > double calculate_pressure_power (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const Quadrature< dim > & quadrature_formula, const Mapping< dim > & mapping)
Calculate the average power done by pressure in the simulation domain. The average power is defined as ∫u.∇pdΩ/∫1dΩ
Returns
Average power done by pressure in the simulation domain Post-processing function
Parameters
[in] dof_handler The dof_handler used for the calculation
[in] evaluation_point The solution for the calculation
[in] quadrature_formula The quadrature formula for the calculation
[in] mapping The mapping of the simulation
Definition at line 448 of file postprocessing_cfd.cc.
References pressure, and velocity.
calculate_pressure_power< 2, GlobalBlockVectorType >()
template double calculate_pressure_power< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_pressure_power< 2, GlobalVectorType >()
template double calculate_pressure_power< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_pressure_power< 2, LinearAlgebra::distributed::Vector< double > >()
template double calculate_pressure_power< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping)
calculate_pressure_power< 3, GlobalBlockVectorType >()
template double calculate_pressure_power< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_pressure_power< 3, GlobalVectorType >()
template double calculate_pressure_power< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_pressure_power< 3, LinearAlgebra::distributed::Vector< double > >()
template double calculate_pressure_power< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping)
calculate_torques()
template<int dim, typename VectorType > std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< dim > & boundary_conditions, const Quadrature< dim - 1 > & face_quadrature_formula, const Mapping< dim > & mapping)
Calculates the torques due to the fluid motion on every boundary conditions.
Returns
std::vector of torques on each boundary condition Post-processing function This function calculates the torqueacting on each of the boundary conditions within the domain. It generates a vector which size is the number of boundary conditions.
Parameters
dof_handler The dof_handler used for the calculation.
evaluation_point The solution at which the torque is calculated.
physical_properties The parameters containing the required physical properties.
boundary_conditions The boundary conditions object.
face_quadrature_formula The face quadrature formula for the calculation.
mapping The mapping of the simulation.
Definition at line 1049 of file postprocessing_cfd.cc.
References calculate_shear_rate_magnitude(), PhysicalPropertiesManager::get_rheology(), BoundaryConditions::NSBoundaryConditions< dim >::navier_stokes_functions, pressure, shear_rate, and BoundaryConditions::BoundaryConditions::type.
calculate_torques< 2, GlobalBlockVectorType >()
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > & boundary_conditions, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_torques< 2, GlobalVectorType >()
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > & boundary_conditions, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_torques< 2, LinearAlgebra::distributed::Vector< double > >()
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 2 > & boundary_conditions, const Quadrature< 1 > & face_quadrature_formula, const Mapping< 2 > & mapping)
calculate_torques< 3, GlobalBlockVectorType >()
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > & boundary_conditions, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_torques< 3, GlobalVectorType >()
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > & boundary_conditions, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_torques< 3, LinearAlgebra::distributed::Vector< double > >()
template std::map< types::boundary_id, Tensor< 1, 3 > > calculate_torques< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const PhysicalPropertiesManager & properties_manager, const BoundaryConditions::NSBoundaryConditions< 3 > & boundary_conditions, const Quadrature< 2 > & face_quadrature_formula, const Mapping< 3 > & mapping)
calculate_viscous_dissipation()
template<int dim, typename VectorType > double calculate_viscous_dissipation (const DoFHandler< dim > & dof_handler, const VectorType & evaluation_point, const Quadrature< dim > & quadrature_formula, const Mapping< dim > & mapping, const PhysicalPropertiesManager & properties_manager)
Calculate the viscous dissipation of kinetic energy which is defined as ∫∇u.τdΩ/∫1dΩ
Returns
Viscous dissipation of kinetic energy Post-processing function
Parameters
[in] dof_handler The dof_handler used for the calculation
[in] evaluation_point The solution for the calculation
[in] quadrature_formula The quadrature formula for the calculation
[in] mapping The mapping of the simulation
[in] properties_manager Manager for the physical properties used to calculate the kinematic viscosity
Definition at line 543 of file postprocessing_cfd.cc.
References calculate_shear_rate_magnitude(), PhysicalPropertiesManager::get_rheology(), shear_rate, and velocity.
calculate_viscous_dissipation< 2, GlobalBlockVectorType >()
template double calculate_viscous_dissipation< 2, GlobalBlockVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_viscous_dissipation< 2, GlobalVectorType >()
template double calculate_viscous_dissipation< 2, GlobalVectorType > (const DoFHandler< 2 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_viscous_dissipation< 2, LinearAlgebra::distributed::Vector< double > >()
template double calculate_viscous_dissipation< 2, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 2 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 2 > & quadrature_formula, const Mapping< 2 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_viscous_dissipation< 3, GlobalBlockVectorType >()
template double calculate_viscous_dissipation< 3, GlobalBlockVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalBlockVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_viscous_dissipation< 3, GlobalVectorType >()
template double calculate_viscous_dissipation< 3, GlobalVectorType > (const DoFHandler< 3 > & dof_handler, const GlobalVectorType & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping, const PhysicalPropertiesManager & properties_manager)
calculate_viscous_dissipation< 3, LinearAlgebra::distributed::Vector< double > >()
template double calculate_viscous_dissipation< 3, LinearAlgebra::distributed::Vector< double > > (const DoFHandler< 3 > & dof_handler, const LinearAlgebra::distributed::Vector< double > & evaluation_point, const Quadrature< 3 > & quadrature_formula, const Mapping< 3 > & mapping, const PhysicalPropertiesManager & properties_manager)