Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/dem/read_checkpoint.cc File Reference
read_checkpoint.cc File Reference
#include <core/checkpoint_control.h>
#include <dem/dem_action_manager.h>
#include <dem/read_checkpoint.h>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <fstream>
#include <iostream>
Functions
template<int dim, typename PropertiesIndex >
void read_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< dim > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< dim > &triangulation, Particles::ParticleHandler< dim > &particle_handler, std::shared_ptr< Insertion< dim, PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > &solid_surfaces, CheckpointControl &checkpoint_controller)
template void read_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 2 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 2 > &triangulation, Particles::ParticleHandler< 2 > &particle_handler, std::shared_ptr< Insertion< 2, DEM::DEMProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > &solid_surfaces, CheckpointControl &checkpoint_controller)
template void read_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 3 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 3 > &triangulation, Particles::ParticleHandler< 3 > &particle_handler, std::shared_ptr< Insertion< 3, DEM::DEMProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > &solid_surfaces, CheckpointControl &checkpoint_controller)
template void read_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 2 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 2 > &triangulation, Particles::ParticleHandler< 2 > &particle_handler, std::shared_ptr< Insertion< 2, DEM::CFDDEMProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > &solid_surfaces, CheckpointControl &checkpoint_controller)
template void read_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 3 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 3 > &triangulation, Particles::ParticleHandler< 3 > &particle_handler, std::shared_ptr< Insertion< 3, DEM::CFDDEMProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > &solid_surfaces, CheckpointControl &checkpoint_controller)
template void read_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 2 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 2 > &triangulation, Particles::ParticleHandler< 2 > &particle_handler, std::shared_ptr< Insertion< 2, DEM::DEMMPProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > &solid_surfaces, CheckpointControl &checkpoint_controller)
template void read_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 3 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 3 > &triangulation, Particles::ParticleHandler< 3 > &particle_handler, std::shared_ptr< Insertion< 3, DEM::DEMMPProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > &solid_surfaces, CheckpointControl &checkpoint_controller)
Function Documentation
read_checkpoint() [1/7]
template void read_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 2 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 2 > & triangulation, Particles::ParticleHandler< 2 > & particle_handler, std::shared_ptr< Insertion< 2, DEM::CFDDEMProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > & solid_surfaces, CheckpointControl & checkpoint_controller)
read_checkpoint() [2/7]
template void read_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 2 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 2 > & triangulation, Particles::ParticleHandler< 2 > & particle_handler, std::shared_ptr< Insertion< 2, DEM::DEMMPProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > & solid_surfaces, CheckpointControl & checkpoint_controller)
read_checkpoint() [3/7]
template void read_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 2 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 2 > & triangulation, Particles::ParticleHandler< 2 > & particle_handler, std::shared_ptr< Insertion< 2, DEM::DEMProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > & solid_surfaces, CheckpointControl & checkpoint_controller)
read_checkpoint() [4/7]
template void read_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 3 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 3 > & triangulation, Particles::ParticleHandler< 3 > & particle_handler, std::shared_ptr< Insertion< 3, DEM::CFDDEMProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > & solid_surfaces, CheckpointControl & checkpoint_controller)
read_checkpoint() [5/7]
template void read_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 3 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 3 > & triangulation, Particles::ParticleHandler< 3 > & particle_handler, std::shared_ptr< Insertion< 3, DEM::DEMMPProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > & solid_surfaces, CheckpointControl & checkpoint_controller)
read_checkpoint() [6/7]
template void read_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 3 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 3 > & triangulation, Particles::ParticleHandler< 3 > & particle_handler, std::shared_ptr< Insertion< 3, DEM::DEMProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > & solid_surfaces, CheckpointControl & checkpoint_controller)
read_checkpoint() [7/7]
template<int dim, typename PropertiesIndex > void read_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< dim > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< dim > & triangulation, Particles::ParticleHandler< dim > & particle_handler, std::shared_ptr< Insertion< dim, PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > & solid_surfaces, CheckpointControl & checkpoint_controller)
Read a DEM simulation checkpoint, allowing the simulation to restart from where it stopped.
Parameters
computing_timer Dem timer
parameters Input DEM parameters in the parameter handler file
simulation_control Simulation control
particles_pvdhandler PVD handler
grid_pvdhandler PVD handler for post-processing
triangulation Triangulation
particle_handler Particle handler
insertion_object Shared pointer of Insertion type.
solid_surfaces Vector of solids surfaces used in DEM simulations
checkpoint_controller Checkpoint controller
Definition at line 19 of file read_checkpoint.cc.
References CheckpointControl::deserialize(), DEMActionManager::get_action_manager(), CheckpointControl::get_filename(), CheckpointControl::get_next_checkpoint_id(), Parameters::Lagrangian::LagrangianPostProcessing::lagrangian_post_processing_enabled, DEMSolverParameters< dim >::post_processing, and PVDHandler::read().