Lethe Open-Source Library: /home/runner/work/lethe/lethe/include/dem/read_checkpoint.h File Reference
read_checkpoint.h File Reference
#include <core/pvd_handler.h>
#include <core/serial_solid.h>
#include <dem/dem_solver_parameters.h>
#include <dem/insertion.h>
#include <deal.II/base/timer.h>
#include <deal.II/distributed/tria.h>
#include <deal.II/particles/particle_handler.h>
Functions
template<int dim, typename PropertiesIndex >
void read_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< dim > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< dim > &triangulation, Particles::ParticleHandler< dim > &particle_handler, std::shared_ptr< Insertion< dim, PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > &solid_surfaces, CheckpointControl &checkpoint_controller)
Function Documentation
read_checkpoint()
template<int dim, typename PropertiesIndex > void read_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< dim > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< dim > & triangulation, Particles::ParticleHandler< dim > & particle_handler, std::shared_ptr< Insertion< dim, PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > & solid_surfaces, CheckpointControl & checkpoint_controller)
Read a DEM simulation checkpoint, allowing the simulation to restart from where it stopped.
Parameters
computing_timer Dem timer
parameters Input DEM parameters in the parameter handler file
simulation_control Simulation control
particles_pvdhandler PVD handler
grid_pvdhandler PVD handler for post-processing
triangulation Triangulation
particle_handler Particle handler
insertion_object Shared pointer of Insertion type.
solid_surfaces Vector of solids surfaces used in DEM simulations
checkpoint_controller Checkpoint controller
Definition at line 19 of file read_checkpoint.cc.
References CheckpointControl::deserialize(), DEMActionManager::get_action_manager(), CheckpointControl::get_filename(), CheckpointControl::get_next_checkpoint_id(), Parameters::Lagrangian::LagrangianPostProcessing::lagrangian_post_processing_enabled, DEMSolverParameters< dim >::post_processing, and PVDHandler::read().