Lethe Open-Source Library: Parameters::Lagrangian::BCDEM Struct Reference
Parameters::Lagrangian::BCDEM Struct Reference
#include <parameters_lagrangian.h>
Public Types
enum class BoundaryType {
fixed_wall , outlet , translational , rotational ,
periodic
}
Public Member Functions
void declare_parameters (ParameterHandler &prm)
void parse_parameters (ParameterHandler &prm)
void declareDefaultEntry (ParameterHandler &prm)
void parse_boundary_conditions (ParameterHandler &prm)
Public Attributes
unsigned int DEM_BC_number
std::vector< BoundaryType > bc_types
std::vector< unsigned int > outlet_boundaries
std::unordered_map< unsigned int, Tensor< 1, 3 > > boundary_translational_velocity
std::unordered_map< unsigned int, double > boundary_rotational_speed
std::unordered_map< unsigned int, Tensor< 1, 3 > > boundary_rotational_vector
std::unordered_map< unsigned int, Point< 3 > > point_on_rotation_axis
types::boundary_id periodic_boundary_0
types::boundary_id periodic_boundary_1
types::boundary_id periodic_direction
Private Member Functions
void initialize_containers (std::unordered_map< unsigned int, Tensor< 1, 3 > > &boundary_translational_velocity, std::unordered_map< unsigned int, double > &boundary_rotational_speed, std::unordered_map< unsigned int, Tensor< 1, 3 > > &boundary_rotational_vector, std::unordered_map< unsigned int, Point< 3 > > &point_on_rotation_axis, std::vector< unsigned int > &outlet_boundaries, std::vector< BoundaryType > &bc_types)
Private Attributes
unsigned int DEM_BC_number_max = 10
Detailed Description
Definition at line 427 of file parameters_lagrangian.h.
Member Enumeration Documentation
BoundaryType
enum class Parameters::Lagrangian::BCDEM::BoundaryType strong
Enumerator
fixed_wall
outlet
translational
rotational
periodic
Definition at line 434 of file parameters_lagrangian.h.
Member Function Documentation
declare_parameters()
void Parameters::Lagrangian::BCDEM::declare_parameters (ParameterHandler & prm)
Definition at line 1400 of file parameters_lagrangian.cc.
References declareDefaultEntry(), and DEM_BC_number_max.
declareDefaultEntry()
void Parameters::Lagrangian::BCDEM::declareDefaultEntry (ParameterHandler & prm)
Definition at line 1283 of file parameters_lagrangian.cc.
initialize_containers()
void Parameters::Lagrangian::BCDEM::initialize_containers (std::unordered_map< unsigned int, Tensor< 1, 3 > > & boundary_translational_velocity, std::unordered_map< unsigned int, double > & boundary_rotational_speed, std::unordered_map< unsigned int, Tensor< 1, 3 > > & boundary_rotational_vector, std::unordered_map< unsigned int, Point< 3 > > & point_on_rotation_axis, std::vector< unsigned int > & outlet_boundaries, std::vector< BoundaryType > & bc_types) private
Definition at line 1449 of file parameters_lagrangian.cc.
References bc_types, boundary_rotational_speed, boundary_rotational_vector, boundary_translational_velocity, DEM_BC_number, DEM_BC_number_max, outlet_boundaries, and point_on_rotation_axis.
parse_boundary_conditions()
void Parameters::Lagrangian::BCDEM::parse_boundary_conditions (ParameterHandler & prm)
Definition at line 1338 of file parameters_lagrangian.cc.
References bc_types, boundary_rotational_speed, boundary_rotational_vector, boundary_translational_velocity, fixed_wall, outlet, outlet_boundaries, periodic, periodic_boundary_0, periodic_boundary_1, periodic_direction, point_on_rotation_axis, rotational, and translational.
parse_parameters()
void Parameters::Lagrangian::BCDEM::parse_parameters (ParameterHandler & prm)
Definition at line 1423 of file parameters_lagrangian.cc.
References bc_types, boundary_rotational_speed, boundary_rotational_vector, boundary_translational_velocity, DEM_BC_number, initialize_containers(), outlet_boundaries, parse_boundary_conditions(), and point_on_rotation_axis.
Member Data Documentation
bc_types
std::vector<BoundaryType> Parameters::Lagrangian::BCDEM::bc_types
Definition at line 444 of file parameters_lagrangian.h.
boundary_rotational_speed
std::unordered_map<unsigned int, double> Parameters::Lagrangian::BCDEM::boundary_rotational_speed
Definition at line 454 of file parameters_lagrangian.h.
boundary_rotational_vector
std::unordered_map<unsigned int, Tensor<1, 3> > Parameters::Lagrangian::BCDEM::boundary_rotational_vector
Definition at line 457 of file parameters_lagrangian.h.
boundary_translational_velocity
std::unordered_map<unsigned int, Tensor<1, 3> > Parameters::Lagrangian::BCDEM::boundary_translational_velocity
Definition at line 451 of file parameters_lagrangian.h.
DEM_BC_number
unsigned int Parameters::Lagrangian::BCDEM::DEM_BC_number
Definition at line 431 of file parameters_lagrangian.h.
DEM_BC_number_max
unsigned int Parameters::Lagrangian::BCDEM::DEM_BC_number_max = 10 private
Definition at line 478 of file parameters_lagrangian.h.
outlet_boundaries
std::vector<unsigned int> Parameters::Lagrangian::BCDEM::outlet_boundaries
Definition at line 447 of file parameters_lagrangian.h.
periodic_boundary_0
types::boundary_id Parameters::Lagrangian::BCDEM::periodic_boundary_0
Definition at line 463 of file parameters_lagrangian.h.
periodic_boundary_1
types::boundary_id Parameters::Lagrangian::BCDEM::periodic_boundary_1
Definition at line 464 of file parameters_lagrangian.h.
periodic_direction
types::boundary_id Parameters::Lagrangian::BCDEM::periodic_direction
Definition at line 465 of file parameters_lagrangian.h.
point_on_rotation_axis
std::unordered_map<unsigned int, Point<3> > Parameters::Lagrangian::BCDEM::point_on_rotation_axis
Definition at line 460 of file parameters_lagrangian.h.
The documentation for this struct was generated from the following files:
/home/runner/work/lethe/lethe/include/core/parameters_lagrangian.h
/home/runner/work/lethe/lethe/source/core/parameters_lagrangian.cc