Lethe Open-Source Library: Parameters::CLS Struct Reference
Parameters::CLS Struct Reference
#include <parameters_multiphysics.h>
Public Member Functions
void declare_parameters (ParameterHandler &prm) const
void parse_parameters (ParameterHandler &prm)
Public Attributes
Parameters::CLS_SurfaceTensionForce surface_tension_force
Parameters::CLS_PhaseFilter phase_filter
Parameters::CLS_RegularizationMethod regularization_method
Parameters::FluidIndicator viscous_dissipative_fluid
double diffusivity
bool compressible
Detailed Description
CLS - Defines the parameters for free surface simulations using the CLS method. Has to be declared before member creation in Multiphysics structure.
Definition at line 351 of file parameters_multiphysics.h.
Member Function Documentation
declare_parameters()
void Parameters::CLS::declare_parameters (ParameterHandler & prm) const
Definition at line 116 of file parameters_multiphysics.cc.
References Parameters::CLS_SurfaceTensionForce::declare_parameters(), Parameters::CLS_PhaseFilter::declare_parameters(), Parameters::CLS_RegularizationMethod::declare_parameters(), phase_filter, regularization_method, and surface_tension_force.
parse_parameters()
void Parameters::CLS::parse_parameters (ParameterHandler & prm)
Definition at line 148 of file parameters_multiphysics.cc.
References Parameters::both, Parameters::fluid0, and Parameters::fluid1.
Member Data Documentation
compressible
bool Parameters::CLS::compressible
Definition at line 365 of file parameters_multiphysics.h.
diffusivity
double Parameters::CLS::diffusivity
Definition at line 363 of file parameters_multiphysics.h.
phase_filter
Parameters::CLS_PhaseFilter Parameters::CLS::phase_filter
Definition at line 354 of file parameters_multiphysics.h.
regularization_method
Parameters::CLS_RegularizationMethod Parameters::CLS::regularization_method
Definition at line 355 of file parameters_multiphysics.h.
surface_tension_force
Parameters::CLS_SurfaceTensionForce Parameters::CLS::surface_tension_force
Definition at line 353 of file parameters_multiphysics.h.
viscous_dissipative_fluid
Parameters::FluidIndicator Parameters::CLS::viscous_dissipative_fluid
Definition at line 357 of file parameters_multiphysics.h.
The documentation for this struct was generated from the following files:
/home/runner/work/lethe/lethe/include/core/parameters_multiphysics.h
/home/runner/work/lethe/lethe/source/core/parameters_multiphysics.cc