Lethe Open-Source Library: Parameters::NonNewtonian Struct Reference
Parameters::NonNewtonian Struct Reference
#include <parameters.h>
Public Member Functions
void declare_parameters (ParameterHandler &prm) const
void parse_parameters (ParameterHandler &prm, const Dimensionality &dimensions)
Public Attributes
CarreauParameters carreau_parameters
PowerLawParameters powerlaw_parameters
Detailed Description
non-Newtonian - Defines the parameters for non-Newtonian flows according to the chosen rheological model.
Definition at line 281 of file parameters.h.
Member Function Documentation
declare_parameters()
void Parameters::NonNewtonian::declare_parameters (ParameterHandler & prm) const
Definition at line 404 of file parameters.cc.
References carreau_parameters, Parameters::PowerLawParameters::declare_parameters(), Parameters::CarreauParameters::declare_parameters(), and powerlaw_parameters.
parse_parameters()
void Parameters::NonNewtonian::parse_parameters (ParameterHandler & prm, const Dimensionality & dimensions)
Definition at line 415 of file parameters.cc.
References carreau_parameters, Parameters::PowerLawParameters::parse_parameters(), Parameters::CarreauParameters::parse_parameters(), and powerlaw_parameters.
Member Data Documentation
carreau_parameters
CarreauParameters Parameters::NonNewtonian::carreau_parameters
Definition at line 283 of file parameters.h.
powerlaw_parameters
PowerLawParameters Parameters::NonNewtonian::powerlaw_parameters
Definition at line 284 of file parameters.h.
The documentation for this struct was generated from the following files:
/home/runner/work/lethe/lethe/include/core/parameters.h
/home/runner/work/lethe/lethe/source/core/parameters.cc