Lethe Open-Source Library: Parameters::Multiphysics Struct Reference
Parameters::Multiphysics Struct Reference
#include <parameters_multiphysics.h>
Public Member Functions
void declare_parameters (ParameterHandler &prm)
void parse_parameters (ParameterHandler &prm, const Dimensionality dimensions)
Public Attributes
bool fluid_dynamics
bool heat_transfer
bool tracer
bool VOF
bool cahn_hilliard
bool viscous_dissipation
bool buoyancy_force
Parameters::VOF vof_parameters
Parameters::CahnHilliard cahn_hilliard_parameters
Detailed Description
Multiphysics - the parameters for multiphysics simulations and handles sub-physics parameters.
Definition at line 390 of file parameters_multiphysics.h.
Member Function Documentation
declare_parameters()
void Parameters::Multiphysics::declare_parameters (ParameterHandler & prm)
Definition at line 32 of file parameters_multiphysics.cc.
References cahn_hilliard_parameters, Parameters::VOF::declare_parameters(), Parameters::CahnHilliard::declare_parameters(), and vof_parameters.
parse_parameters()
void Parameters::Multiphysics::parse_parameters (ParameterHandler & prm, const Dimensionality dimensions)
Definition at line 79 of file parameters_multiphysics.cc.
References cahn_hilliard, fluid_dynamics, heat_transfer, Parameters::VOF::parse_parameters(), and tracer.
Member Data Documentation
buoyancy_force
bool Parameters::Multiphysics::buoyancy_force
Definition at line 400 of file parameters_multiphysics.h.
cahn_hilliard
bool Parameters::Multiphysics::cahn_hilliard
Definition at line 396 of file parameters_multiphysics.h.
cahn_hilliard_parameters
Parameters::CahnHilliard Parameters::Multiphysics::cahn_hilliard_parameters
Definition at line 403 of file parameters_multiphysics.h.
fluid_dynamics
bool Parameters::Multiphysics::fluid_dynamics
Definition at line 392 of file parameters_multiphysics.h.
heat_transfer
bool Parameters::Multiphysics::heat_transfer
Definition at line 393 of file parameters_multiphysics.h.
tracer
bool Parameters::Multiphysics::tracer
Definition at line 394 of file parameters_multiphysics.h.
viscous_dissipation
bool Parameters::Multiphysics::viscous_dissipation
Definition at line 399 of file parameters_multiphysics.h.
VOF
bool Parameters::Multiphysics::VOF
Definition at line 395 of file parameters_multiphysics.h.
vof_parameters
Parameters::VOF Parameters::Multiphysics::vof_parameters
Definition at line 402 of file parameters_multiphysics.h.
The documentation for this struct was generated from the following files:
/home/runner/work/lethe/lethe/include/core/parameters_multiphysics.h
/home/runner/work/lethe/lethe/source/core/parameters_multiphysics.cc