Lethe Open-Source Library: Parameters::Ramp Struct Reference
Parameters::Ramp Struct Reference
#include <initial_conditions.h>
Public Member Functions
void declare_parameters (ParameterHandler &prm)
void parse_parameters (ParameterHandler &prm)
Public Attributes
Ramp_n ramp_n
Ramp_viscosity ramp_viscosity
Detailed Description
Definition at line 58 of file initial_conditions.h.
Member Function Documentation
declare_parameters()
void Parameters::Ramp::declare_parameters (ParameterHandler & prm)
Definition at line 83 of file initial_conditions.cc.
References Parameters::Ramp_n::declare_parameters(), Parameters::Ramp_viscosity::declare_parameters(), ramp_n, and ramp_viscosity.
parse_parameters()
void Parameters::Ramp::parse_parameters (ParameterHandler & prm)
Definition at line 94 of file initial_conditions.cc.
References Parameters::Ramp_n::parse_parameters(), Parameters::Ramp_viscosity::parse_parameters(), ramp_n, and ramp_viscosity.
Member Data Documentation
ramp_n
Ramp_n Parameters::Ramp::ramp_n
Definition at line 60 of file initial_conditions.h.
ramp_viscosity
Ramp_viscosity Parameters::Ramp::ramp_viscosity
Definition at line 61 of file initial_conditions.h.
The documentation for this struct was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/initial_conditions.h
/home/runner/work/lethe/lethe/source/solvers/initial_conditions.cc