Lethe Open-Source Library: Parameters::Lagrangian::LagrangianPhysicalProperties Struct Reference
Parameters::Lagrangian::LagrangianPhysicalProperties Struct Reference
#include <parameters_lagrangian.h>
Public Member Functions
void declare_parameters (ParameterHandler &prm) const
void parse_parameters (ParameterHandler &prm)
void parse_particle_properties (const unsigned int &particle_type, const ParameterHandler &prm)
Static Public Member Functions
static void declareDefaultEntry (ParameterHandler &prm)
Public Attributes
Tensor< 1, 3 > g
unsigned int particle_type_number
std::vector< SizeDistributionType > distribution_type
std::vector< double > particle_average_diameter
std::vector< double > particle_size_std
std::vector< bool > custom_distribution_from_file
std::vector< std::string > custom_distribution_filenames
std::vector< ProbabilityFunctionType > custom_probability_function_type
std::vector< bool > custom_distribution_interpolation
std::vector< std::vector< double > > particle_custom_diameter
std::vector< std::vector< double > > particle_custom_probability
std::vector< DistributionWeightingType > distribution_weighting_type
std::vector< unsigned int > seed_for_distributions
std::vector< double > diameter_min_cutoff
std::vector< double > diameter_max_cutoff
std::vector< int > number
std::vector< double > density_particle
std::vector< double > youngs_modulus_particle
std::vector< double > poisson_ratio_particle
std::vector< double > restitution_coefficient_particle
std::vector< double > friction_coefficient_particle
std::vector< double > rolling_viscous_damping_coefficient_particle
std::vector< double > rolling_friction_coefficient_particle
std::vector< double > surface_energy_particle
std::vector< double > hamaker_constant_particle
std::vector< double > thermal_conductivity_particle
std::vector< double > specific_heat_particle
std::vector< double > microhardness_particle
std::vector< double > surface_slope_particle
std::vector< double > surface_roughness_particle
std::vector< double > thermal_accommodation_particle
std::vector< double > real_youngs_modulus_particle
double youngs_modulus_wall
double poisson_ratio_wall
double restitution_coefficient_wall
double friction_coefficient_wall
double rolling_friction_wall
double rolling_viscous_damping_wall
double surface_energy_wall
double hamaker_constant_wall
double thermal_conductivity_wall
double microhardness_wall
double surface_slope_wall
double surface_roughness_wall
double thermal_accommodation_wall
double real_youngs_modulus_wall
double thermal_conductivity_gas
double specific_heat_gas
double dynamic_viscosity_gas
double specific_heats_ratio_gas
double molecular_mean_free_path_gas
Private Member Functions
void initialize_containers (std::vector< SizeDistributionType > &dist_types, std::vector< double > &p_average_diameter, std::vector< double > &p_size_std, std::vector< bool > &custom_dist_read_from_file, std::vector< std::string > &custom_dist_file_names, std::vector< ProbabilityFunctionType > &custom_function_type, std::vector< bool > &custom_interpolation, std::vector< std::vector< double > > &custom_diameter_values, std::vector< std::vector< double > > &custom_probabilities_values, std::vector< DistributionWeightingType > &distribution_weighting_basis_type, std::vector< unsigned int > &seed_for_dist, std::vector< double > &dia_min_cutoff, std::vector< double > &dia_max_cutoff, std::vector< int > &p_number, std::vector< double > &p_density, std::vector< double > &p_youngs_modulus, std::vector< double > &p_poisson_ratio, std::vector< double > &p_restitution_coefficient, std::vector< double > &p_friction_coefficient, std::vector< double > &p_rolling_viscous_damping_coefficient, std::vector< double > &p_rolling_friction_coefficient, std::vector< double > &p_surface_energy, std::vector< double > &p_hamaker_constant, std::vector< double > &p_thermal_conductivity, std::vector< double > &p_specific_heat, std::vector< double > &p_microhardness, std::vector< double > &p_surface_slope, std::vector< double > &p_surface_roughness, std::vector< double > &p_thermal_accommodation, std::vector< double > &p_real_youngs_modulus) const
Private Attributes
unsigned int particle_type_maximum_number = 5
Detailed Description
Physical properties of particles, walls, and interstitial gas for Lagrangian (DEM) simulations.
This structure stores all material properties needed for contact force computations, including per-particle-type mechanical and thermal properties, wall properties, and interstitial gas properties.
Definition at line 120 of file parameters_lagrangian.h.
Member Function Documentation
declare_parameters()
void Parameters::Lagrangian::LagrangianPhysicalProperties::declare_parameters (ParameterHandler & prm) const
Declare the parameters in the parameter handler.
Parameters
[in,out] prm The parameter handler.
Definition at line 13 of file parameters_lagrangian.cc.
References declareDefaultEntry(), and particle_type_maximum_number.
declareDefaultEntry()
void Parameters::Lagrangian::LagrangianPhysicalProperties::declareDefaultEntry (ParameterHandler & prm) static
Declare default parameter entries for a single particle type.
Parameters
[in,out] prm The parameter handler.
Definition at line 219 of file parameters_lagrangian.cc.
initialize_containers()
void Parameters::Lagrangian::LagrangianPhysicalProperties::initialize_containers (std::vector< SizeDistributionType > & dist_types, std::vector< double > & p_average_diameter, std::vector< double > & p_size_std, std::vector< bool > & custom_dist_read_from_file, std::vector< std::string > & custom_dist_file_names, std::vector< ProbabilityFunctionType > & custom_function_type, std::vector< bool > & custom_interpolation, std::vector< std::vector< double > > & custom_diameter_values, std::vector< std::vector< double > > & custom_probabilities_values, std::vector< DistributionWeightingType > & distribution_weighting_basis_type, std::vector< unsigned int > & seed_for_dist, std::vector< double > & dia_min_cutoff, std::vector< double > & dia_max_cutoff, std::vector< int > & p_number, std::vector< double > & p_density, std::vector< double > & p_youngs_modulus, std::vector< double > & p_poisson_ratio, std::vector< double > & p_restitution_coefficient, std::vector< double > & p_friction_coefficient, std::vector< double > & p_rolling_viscous_damping_coefficient, std::vector< double > & p_rolling_friction_coefficient, std::vector< double > & p_surface_energy, std::vector< double > & p_hamaker_constant, std::vector< double > & p_thermal_conductivity, std::vector< double > & p_specific_heat, std::vector< double > & p_microhardness, std::vector< double > & p_surface_slope, std::vector< double > & p_surface_roughness, std::vector< double > & p_thermal_accommodation, std::vector< double > & p_real_youngs_modulus) const private
initialize_containers - Initialize the containers used to store the particle size distribution and physical properties of each particle type.
Parameters
[in,out] dist_types Indicates the SizeDistributionType type.
[in,out] p_average_diameter Average diameter.
[in,out] p_size_std Diameter standard deviation for the normal and lognormal distributions.
[in,out] custom_dist_read_from_file Indicates whether the diameter and probability values are stored in a separate file.
[in,out] custom_dist_file_names Vector of filenames from which the custom distributions are read.
[in,out] custom_function_type Indicates whether the values defining the custom distribution correspond to the PDF or the CDF.
[in,out] custom_interpolation Indicates whether the diameter values are interpolated from the input values.
[in,out] custom_diameter_values Lists of diameters for the custom distribution.
[in,out] custom_probabilities_values Lists of probability values corresponding to each diameter value in the custom distribution.
[in,out] distribution_weighting_basis_type Weighting basis for the PSD.
[in,out] seed_for_dist Pseudo random seed for the PSD sampling.
[in,out] dia_min_cutoff Minimal cutoff value when sampling a PSD.
[in,out] dia_max_cutoff Maximal cutoff value when sampling a PSD.
[in,out] p_number Number of particles.
[in,out] p_density Density.
[in,out] p_youngs_modulus Young's modulus.
[in,out] p_poisson_ratio Poisson's ratio.
[in,out] p_restitution_coefficient Coefficient of restitution.
[in,out] p_friction_coefficient Sliding friction coefficient.
[in,out] p_rolling_viscous_damping_coefficient Rolling viscous damping coefficient
[in,out] p_rolling_friction_coefficient Rolling friction coefficient.
[in,out] p_surface_energy Surface energy.
[in,out] p_hamaker_constant Hamaker constant.
[in,out] p_thermal_conductivity Thermal conductivity.
[in,out] p_specific_heat Specific heat.
[in,out] p_microhardness Microhardness.
[in,out] p_surface_slope Surface slope.
[in,out] p_surface_roughness Surface roughness.
[in,out] p_thermal_accommodation Thermal accommodation coefficient.
[in,out] p_real_youngs_modulus Real Young's modulus.
Definition at line 485 of file parameters_lagrangian.cc.
References particle_type_maximum_number.
parse_parameters()
void Parameters::Lagrangian::LagrangianPhysicalProperties::parse_parameters (ParameterHandler & prm)
Parse the parameters from the parameter handler.
Parameters
[in,out] prm The parameter handler.
Definition at line 134 of file parameters_lagrangian.cc.
References custom_distribution_filenames, custom_distribution_from_file, custom_distribution_interpolation, custom_probability_function_type, density_particle, diameter_max_cutoff, diameter_min_cutoff, distribution_type, distribution_weighting_type, dynamic_viscosity_gas, friction_coefficient_particle, friction_coefficient_wall, g, hamaker_constant_particle, hamaker_constant_wall, initialize_containers(), microhardness_particle, microhardness_wall, molecular_mean_free_path_gas, number, parse_particle_properties(), particle_average_diameter, particle_custom_diameter, particle_custom_probability, particle_size_std, particle_type_number, poisson_ratio_particle, poisson_ratio_wall, real_youngs_modulus_particle, real_youngs_modulus_wall, restitution_coefficient_particle, restitution_coefficient_wall, rolling_friction_coefficient_particle, rolling_friction_wall, rolling_viscous_damping_coefficient_particle, rolling_viscous_damping_wall, seed_for_distributions, specific_heat_gas, specific_heat_particle, specific_heats_ratio_gas, surface_energy_particle, surface_energy_wall, surface_roughness_particle, surface_roughness_wall, surface_slope_particle, surface_slope_wall, thermal_accommodation_particle, thermal_accommodation_wall, thermal_conductivity_gas, thermal_conductivity_particle, thermal_conductivity_wall, youngs_modulus_particle, and youngs_modulus_wall.
parse_particle_properties()
void Parameters::Lagrangian::LagrangianPhysicalProperties::parse_particle_properties (const unsigned int & particle_type, const ParameterHandler & prm)
Parse the physical properties for a given particle type.
Parameters
[in] particle_type Index of the particle type to parse.
[in,out] prm The parameter handler.
Definition at line 380 of file parameters_lagrangian.cc.
References Parameters::Lagrangian::CDF, Parameters::Lagrangian::custom, custom_distribution_filenames, custom_distribution_from_file, custom_distribution_interpolation, custom_probability_function_type, density_particle, diameter_max_cutoff, diameter_min_cutoff, distribution_type, distribution_weighting_type, friction_coefficient_particle, hamaker_constant_particle, Parameters::Lagrangian::lognormal, microhardness_particle, Parameters::Lagrangian::normal, number, Parameters::Lagrangian::number_based, particle_average_diameter, particle_custom_diameter, particle_custom_probability, particle_size_std, Parameters::Lagrangian::PDF, poisson_ratio_particle, real_youngs_modulus_particle, restitution_coefficient_particle, rolling_friction_coefficient_particle, rolling_viscous_damping_coefficient_particle, seed_for_distributions, specific_heat_particle, surface_energy_particle, surface_roughness_particle, surface_slope_particle, thermal_accommodation_particle, thermal_conductivity_particle, Parameters::Lagrangian::uniform, Parameters::Lagrangian::volume_based, and youngs_modulus_particle.
Member Data Documentation
custom_distribution_filenames
std::vector<std::string> Parameters::Lagrangian::LagrangianPhysicalProperties::custom_distribution_filenames
Filename for the custom distribution for each particle type.
Definition at line 143 of file parameters_lagrangian.h.
custom_distribution_from_file
std::vector<bool> Parameters::Lagrangian::LagrangianPhysicalProperties::custom_distribution_from_file
Indicate if the custom distribution is read from file.
Definition at line 140 of file parameters_lagrangian.h.
custom_distribution_interpolation
std::vector<bool> Parameters::Lagrangian::LagrangianPhysicalProperties::custom_distribution_interpolation
Indicates whether the diameter values generated from the custom distribution are interpolated
Definition at line 150 of file parameters_lagrangian.h.
custom_probability_function_type
std::vector<ProbabilityFunctionType> Parameters::Lagrangian::LagrangianPhysicalProperties::custom_probability_function_type
Custom distribution function type (PDF or CDF)
Definition at line 146 of file parameters_lagrangian.h.
density_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::density_particle
Density of each particle type.
Definition at line 176 of file parameters_lagrangian.h.
diameter_max_cutoff
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::diameter_max_cutoff
Maximum diameter cutoff for lognormal distribution.
Definition at line 170 of file parameters_lagrangian.h.
diameter_min_cutoff
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::diameter_min_cutoff
Minimum diameter cutoff for lognormal distribution.
Definition at line 167 of file parameters_lagrangian.h.
distribution_type
std::vector<SizeDistributionType> Parameters::Lagrangian::LagrangianPhysicalProperties::distribution_type
Definition at line 131 of file parameters_lagrangian.h.
distribution_weighting_type
std::vector<DistributionWeightingType> Parameters::Lagrangian::LagrangianPhysicalProperties::distribution_weighting_type
Distribution weighting type of each particle type (number-based, volume-based)
Definition at line 161 of file parameters_lagrangian.h.
dynamic_viscosity_gas
double Parameters::Lagrangian::LagrangianPhysicalProperties::dynamic_viscosity_gas
Dynamic viscosity of the interstitial gas.
Definition at line 272 of file parameters_lagrangian.h.
friction_coefficient_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::friction_coefficient_particle
Friction coefficient of each particle type.
Definition at line 188 of file parameters_lagrangian.h.
friction_coefficient_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::friction_coefficient_wall
Friction coefficient of the wall.
Definition at line 233 of file parameters_lagrangian.h.
g
Tensor<1, 3> Parameters::Lagrangian::LagrangianPhysicalProperties::g
Gravitational acceleration vector.
Definition at line 124 of file parameters_lagrangian.h.
hamaker_constant_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::hamaker_constant_particle
Hamaker constant of each particle type.
Definition at line 200 of file parameters_lagrangian.h.
hamaker_constant_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::hamaker_constant_wall
Hamaker constant of the wall.
Definition at line 245 of file parameters_lagrangian.h.
microhardness_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::microhardness_particle
Microhardness of each particle type.
Definition at line 209 of file parameters_lagrangian.h.
microhardness_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::microhardness_wall
Microhardness of the wall.
Definition at line 251 of file parameters_lagrangian.h.
molecular_mean_free_path_gas
double Parameters::Lagrangian::LagrangianPhysicalProperties::molecular_mean_free_path_gas
Molecular mean free path of the interstitial gas.
Definition at line 278 of file parameters_lagrangian.h.
number
std::vector<int> Parameters::Lagrangian::LagrangianPhysicalProperties::number
Number particles of each particle type.
Definition at line 173 of file parameters_lagrangian.h.
particle_average_diameter
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::particle_average_diameter
Average diameter of each particle type.
Definition at line 134 of file parameters_lagrangian.h.
particle_custom_diameter
std::vector<std::vector<double> > Parameters::Lagrangian::LagrangianPhysicalProperties::particle_custom_diameter
List of diameters for the custom distribution for each particle type.
Definition at line 153 of file parameters_lagrangian.h.
particle_custom_probability
std::vector<std::vector<double> > Parameters::Lagrangian::LagrangianPhysicalProperties::particle_custom_probability
Probability of each diameter value based on volume fraction for the custom distribution for each particle type
Definition at line 157 of file parameters_lagrangian.h.
particle_size_std
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::particle_size_std
Size standard deviation of each particle type.
Definition at line 137 of file parameters_lagrangian.h.
particle_type_maximum_number
unsigned int Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_maximum_number = 5 private
Definition at line 315 of file parameters_lagrangian.h.
particle_type_number
unsigned int Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number
Number of particle types.
Definition at line 127 of file parameters_lagrangian.h.
poisson_ratio_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::poisson_ratio_particle
Poisson's ratio of each particle type.
Definition at line 182 of file parameters_lagrangian.h.
poisson_ratio_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::poisson_ratio_wall
Poisson's ratio of the wall.
Definition at line 227 of file parameters_lagrangian.h.
real_youngs_modulus_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::real_youngs_modulus_particle
Real Young's modulus of each particle type.
Definition at line 221 of file parameters_lagrangian.h.
real_youngs_modulus_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::real_youngs_modulus_wall
Real Young's modulus of the wall.
Definition at line 263 of file parameters_lagrangian.h.
restitution_coefficient_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::restitution_coefficient_particle
Coefficients of restitution of each particle type.
Definition at line 185 of file parameters_lagrangian.h.
restitution_coefficient_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::restitution_coefficient_wall
Coefficient of restitution of the wall.
Definition at line 230 of file parameters_lagrangian.h.
rolling_friction_coefficient_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_friction_coefficient_particle
Rolling friction coefficient of each particle type.
Definition at line 194 of file parameters_lagrangian.h.
rolling_friction_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_friction_wall
Rolling friction coefficient of the wall.
Definition at line 236 of file parameters_lagrangian.h.
rolling_viscous_damping_coefficient_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_viscous_damping_coefficient_particle
Rolling viscous damping coefficient of each particle type.
Definition at line 191 of file parameters_lagrangian.h.
rolling_viscous_damping_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::rolling_viscous_damping_wall
Rolling viscous damping coefficient of the wall.
Definition at line 239 of file parameters_lagrangian.h.
seed_for_distributions
std::vector<unsigned int> Parameters::Lagrangian::LagrangianPhysicalProperties::seed_for_distributions
Random seed for the size distribution.
Definition at line 164 of file parameters_lagrangian.h.
specific_heat_gas
double Parameters::Lagrangian::LagrangianPhysicalProperties::specific_heat_gas
Specific heat of the interstitial gas.
Definition at line 269 of file parameters_lagrangian.h.
specific_heat_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::specific_heat_particle
Specific heat of each particle type.
Definition at line 206 of file parameters_lagrangian.h.
specific_heats_ratio_gas
double Parameters::Lagrangian::LagrangianPhysicalProperties::specific_heats_ratio_gas
Specific heats ratio of the interstitial gas.
Definition at line 275 of file parameters_lagrangian.h.
surface_energy_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::surface_energy_particle
Surface energy of each particle type.
Definition at line 197 of file parameters_lagrangian.h.
surface_energy_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::surface_energy_wall
Surface energy of the wall.
Definition at line 242 of file parameters_lagrangian.h.
surface_roughness_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::surface_roughness_particle
Surface roughness of each particle type.
Definition at line 215 of file parameters_lagrangian.h.
surface_roughness_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::surface_roughness_wall
Surface roughness of the wall.
Definition at line 257 of file parameters_lagrangian.h.
surface_slope_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::surface_slope_particle
Surface slope of each particle type.
Definition at line 212 of file parameters_lagrangian.h.
surface_slope_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::surface_slope_wall
Surface slope of the wall.
Definition at line 254 of file parameters_lagrangian.h.
thermal_accommodation_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::thermal_accommodation_particle
Thermal accommodation coefficient of each particle type.
Definition at line 218 of file parameters_lagrangian.h.
thermal_accommodation_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::thermal_accommodation_wall
Thermal accommodation coefficient of the wall.
Definition at line 260 of file parameters_lagrangian.h.
thermal_conductivity_gas
double Parameters::Lagrangian::LagrangianPhysicalProperties::thermal_conductivity_gas
Thermal conductivity of the interstitial gas.
Definition at line 266 of file parameters_lagrangian.h.
thermal_conductivity_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::thermal_conductivity_particle
Thermal conductivity of each particle type.
Definition at line 203 of file parameters_lagrangian.h.
thermal_conductivity_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::thermal_conductivity_wall
Thermal conductivity of the wall.
Definition at line 248 of file parameters_lagrangian.h.
youngs_modulus_particle
std::vector<double> Parameters::Lagrangian::LagrangianPhysicalProperties::youngs_modulus_particle
Young's modulus of each particle type.
Definition at line 179 of file parameters_lagrangian.h.
youngs_modulus_wall
double Parameters::Lagrangian::LagrangianPhysicalProperties::youngs_modulus_wall
Young's modulus of the wall.
Definition at line 224 of file parameters_lagrangian.h.
The documentation for this struct was generated from the following files:
/home/runner/work/lethe/lethe/include/core/parameters_lagrangian.h
/home/runner/work/lethe/lethe/source/core/parameters_lagrangian.cc