Lethe Open-Source Library: /home/runner/work/lethe/lethe/source/dem/write_checkpoint.cc File Reference
write_checkpoint.cc File Reference
#include <core/checkpoint_control.h>
#include <dem/write_checkpoint.h>
#include <boost/archive/text_oarchive.hpp>
#include <fstream>
#include <iostream>
Functions
template<int dim, typename PropertiesIndex >
void write_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< dim > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< dim > &triangulation, Particles::ParticleHandler< dim > &particle_handler, std::shared_ptr< Insertion< dim, PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > &solid_objects, const ConditionalOStream &pcout, MPI_Comm &mpi_communicator, const CheckpointControl &checkpoint_controller)
template void write_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 2 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 2 > &triangulation, Particles::ParticleHandler< 2 > &particle_handler, std::shared_ptr< Insertion< 2, DEM::DEMProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > &solid_objects, const ConditionalOStream &pcout, MPI_Comm &mpi_communicator, const CheckpointControl &checkpoint_controller)
template void write_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 3 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 3 > &triangulation, Particles::ParticleHandler< 3 > &particle_handler, std::shared_ptr< Insertion< 3, DEM::DEMProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > &solid_objects, const ConditionalOStream &pcout, MPI_Comm &mpi_communicator, const CheckpointControl &checkpoint_controller)
template void write_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 2 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 2 > &triangulation, Particles::ParticleHandler< 2 > &particle_handler, std::shared_ptr< Insertion< 2, DEM::CFDDEMProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > &solid_objects, const ConditionalOStream &pcout, MPI_Comm &mpi_communicator, const CheckpointControl &checkpoint_controller)
template void write_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 3 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 3 > &triangulation, Particles::ParticleHandler< 3 > &particle_handler, std::shared_ptr< Insertion< 3, DEM::CFDDEMProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > &solid_objects, const ConditionalOStream &pcout, MPI_Comm &mpi_communicator, const CheckpointControl &checkpoint_controller)
template void write_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 2 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 2 > &triangulation, Particles::ParticleHandler< 2 > &particle_handler, std::shared_ptr< Insertion< 2, DEM::DEMMPProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > &solid_objects, const ConditionalOStream &pcout, MPI_Comm &mpi_communicator, const CheckpointControl &checkpoint_controller)
template void write_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< 3 > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< 3 > &triangulation, Particles::ParticleHandler< 3 > &particle_handler, std::shared_ptr< Insertion< 3, DEM::DEMMPProperties::PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > &solid_objects, const ConditionalOStream &pcout, MPI_Comm &mpi_communicator, const CheckpointControl &checkpoint_controller)
Function Documentation
write_checkpoint() [1/7]
template void write_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 2 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 2 > & triangulation, Particles::ParticleHandler< 2 > & particle_handler, std::shared_ptr< Insertion< 2, DEM::CFDDEMProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > & solid_objects, const ConditionalOStream & pcout, MPI_Comm & mpi_communicator, const CheckpointControl & checkpoint_controller)
write_checkpoint() [2/7]
template void write_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 2 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 2 > & triangulation, Particles::ParticleHandler< 2 > & particle_handler, std::shared_ptr< Insertion< 2, DEM::DEMMPProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > & solid_objects, const ConditionalOStream & pcout, MPI_Comm & mpi_communicator, const CheckpointControl & checkpoint_controller)
write_checkpoint() [3/7]
template void write_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 2 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 2 > & triangulation, Particles::ParticleHandler< 2 > & particle_handler, std::shared_ptr< Insertion< 2, DEM::DEMProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 1, 2 > > > & solid_objects, const ConditionalOStream & pcout, MPI_Comm & mpi_communicator, const CheckpointControl & checkpoint_controller)
write_checkpoint() [4/7]
template void write_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 3 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 3 > & triangulation, Particles::ParticleHandler< 3 > & particle_handler, std::shared_ptr< Insertion< 3, DEM::CFDDEMProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > & solid_objects, const ConditionalOStream & pcout, MPI_Comm & mpi_communicator, const CheckpointControl & checkpoint_controller)
write_checkpoint() [5/7]
template void write_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 3 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 3 > & triangulation, Particles::ParticleHandler< 3 > & particle_handler, std::shared_ptr< Insertion< 3, DEM::DEMMPProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > & solid_objects, const ConditionalOStream & pcout, MPI_Comm & mpi_communicator, const CheckpointControl & checkpoint_controller)
write_checkpoint() [6/7]
template void write_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< 3 > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< 3 > & triangulation, Particles::ParticleHandler< 3 > & particle_handler, std::shared_ptr< Insertion< 3, DEM::DEMProperties::PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< 2, 3 > > > & solid_objects, const ConditionalOStream & pcout, MPI_Comm & mpi_communicator, const CheckpointControl & checkpoint_controller)
write_checkpoint() [7/7]
template<int dim, typename PropertiesIndex > void write_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< dim > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< dim > & triangulation, Particles::ParticleHandler< dim > & particle_handler, std::shared_ptr< Insertion< dim, PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > & solid_objects, const ConditionalOStream & pcout, MPI_Comm & mpi_communicator, const CheckpointControl & checkpoint_controller)
Write_checkpoint Write a DEM simulation checkpointing to allow for DEM simulation restart.
Parameters
computing_timer Dem timer
parameters Input DEM parameters in the parameter handler file
simulation_control Simulation control
particles_pvdhandler PVD handler
grid_pvdhandler PVD handler for post-processing
triangulation Triangulation
particle_handler Particle handler
insertion_object Insertion object
solid_objects Vector of solids objects used in DEM simulations
pcout Printing in parallel
mpi_communicator
checkpoint_controller Checkpoint controller
Definition at line 17 of file write_checkpoint.cc.
References CheckpointControl::get_filename(), CheckpointControl::get_next_checkpoint_id(), Parameters::Lagrangian::LagrangianPostProcessing::lagrangian_post_processing_enabled, DEMSolverParameters< dim >::post_processing, PVDHandler::save(), and CheckpointControl::serialize().