Lethe Open-Source Library: /home/runner/work/lethe/lethe/include/dem/write_checkpoint.h File Reference
write_checkpoint.h File Reference
#include <core/pvd_handler.h>
#include <core/serial_solid.h>
#include <dem/dem_solver_parameters.h>
#include <dem/insertion.h>
#include <deal.II/base/timer.h>
#include <deal.II/distributed/tria.h>
#include <deal.II/particles/particle_handler.h>
Functions
template<int dim, typename PropertiesIndex >
void write_checkpoint (TimerOutput &computing_timer, const DEMSolverParameters< dim > &parameters, std::shared_ptr< SimulationControl > &simulation_control, PVDHandler &particles_pvdhandler, PVDHandler &grid_pvdhandler, parallel::distributed::Triangulation< dim > &triangulation, Particles::ParticleHandler< dim > &particle_handler, std::shared_ptr< Insertion< dim, PropertiesIndex > > &insertion_object, std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > &solid_objects, const ConditionalOStream &pcout, MPI_Comm &mpi_communicator, const CheckpointControl &checkpoint_controller)
Function Documentation
write_checkpoint()
template<int dim, typename PropertiesIndex > void write_checkpoint (TimerOutput & computing_timer, const DEMSolverParameters< dim > & parameters, std::shared_ptr< SimulationControl > & simulation_control, PVDHandler & particles_pvdhandler, PVDHandler & grid_pvdhandler, parallel::distributed::Triangulation< dim > & triangulation, Particles::ParticleHandler< dim > & particle_handler, std::shared_ptr< Insertion< dim, PropertiesIndex > > & insertion_object, std::vector< std::shared_ptr< SerialSolid< dim - 1, dim > > > & solid_objects, const ConditionalOStream & pcout, MPI_Comm & mpi_communicator, const CheckpointControl & checkpoint_controller)
Write_checkpoint Write a DEM simulation checkpointing to allow for DEM simulation restart.
Parameters
computing_timer Dem timer
parameters Input DEM parameters in the parameter handler file
simulation_control Simulation control
particles_pvdhandler PVD handler
grid_pvdhandler PVD handler for post-processing
triangulation Triangulation
particle_handler Particle handler
insertion_object Insertion object
solid_objects Vector of solids objects used in DEM simulations
pcout Printing in parallel
mpi_communicator
checkpoint_controller Checkpoint controller
Definition at line 17 of file write_checkpoint.cc.
References CheckpointControl::get_filename(), CheckpointControl::get_next_checkpoint_id(), Parameters::Lagrangian::LagrangianPostProcessing::lagrangian_post_processing_enabled, DEMSolverParameters< dim >::post_processing, PVDHandler::save(), and CheckpointControl::serialize().