name: Check_indent

# Called by ci.yml, which sets the triggers and concurrency
on:
  workflow_call:

permissions:
  contents: read

jobs:
  indent:

    name: indent
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 100
    - name: setup
      run: |
        ./contrib/utilities/download_clang_format
    - name: indent
      run: |
        ./contrib/utilities/check_indentation.sh
