name: Docker Image Build & Push

on:
  # Runs on every push on master branch.
  push:
#    branches:
#      - master
  # Runs when a release is published
  release:
    types:
      - published

env:
  IMAGE_TAG: lethe-cfg/lethe

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
#          push: true
          # Either the name of the branch or the tag used by the release
          tags: ${{ env.IMAGE_TAG }}:latest,${{ env.IMAGE_TAG }}:${{ github.ref_name }}