name: Doxygen

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Doxygen documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./doc/doxygen/doxygen-config-file"
        working-directory: "."
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html