name: CI-Warnings

on:
  # Runs on every push on master branch. If a push contains multiple commits, it will be ran on the latest one.
  push:
    paths-ignore:
      - 'doc/**'
  pull_request_target:
    paths-ignore:
      - 'doc/**'

env:
  COMPILE_JOBS: 2
  MULTI_CORE_TESTS_REGEX: "mpirun=2"

jobs:
  build:
    name: Build (deal.ii:${{ matrix.dealii_version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dealii_version: ["master", "v9.5.0"]
    
    # Run steps in container of dealii's master branch
    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-focal
      options: --user root

    steps:
      - name: Setup
        run: |
          # Since dealii image doesn't include Node.js, we'll install it
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends nodejs



          echo "Github actions is sane!"
          echo "Running build with deal.ii version ${{ matrix.dealii_version }} on branch ${GITHUB_REF#refs/heads/}"

      # Checks-out Lethe with branch of triggering commit
      - name: Checkout code
        uses: actions/checkout@v2

      #
      # Warnings
      #
      - name: Compile Lethe to check for warnings (deal.ii:${{ matrix.dealii_version }})
        run: |
          mkdir build-warnings
          cd build-warnings
          cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
          make -j${{ env.COMPILE_JOBS }}
