name: Check_prm_indent

# Called by ci.yml, which sets the triggers and concurrency
on:
  workflow_call:

jobs:
  indent:

    name: prm-indent
    runs-on: [ubuntu-latest]

    steps:
    # Checks-out Lethe with branch of triggering commit
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check parameter files indentation
      run: |
        ./contrib/utilities/check_parameter_files_indentation.sh
