name: CI-Warnings

# Called by ci.yml, which sets the triggers and concurrency, once the
# indentation and documentation checks pass
on:
  workflow_call:

env:
  COMPILE_JOBS: 40
  TEST_JOBS: 40

jobs:
  build:
    name: Build (deal.ii:${{ matrix.dealii_version }})
    runs-on: self-hosted


    strategy:
      fail-fast: false
      matrix:
        dealii_version: ["master-noble"]

    # Run steps in container of dealii's master branch
    container:
      image: dealii/dealii:${{ matrix.dealii_version }}
      options: --user root

    steps:
      - name: Setup
        run: |
          # Since dealii image doesn't include Node.js, we'll install it
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends nodejs



          echo "Github actions is sane!"
          echo "Running build with deal.ii version ${{ matrix.dealii_version }} on branch ${GITHUB_REF#refs/heads/}"

      # Checks-out Lethe with branch of triggering commit
      - name: Checkout code
        uses: actions/checkout@v2

      #
      # Warnings
      #
      - name: Compile Lethe to check for warnings (deal.ii:${{ matrix.dealii_version }})
        run: |
          mkdir build-warnings
          cd build-warnings
          cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DBUILD_PROTOTYPES=ON -G Ninja
          ninja -j${{ env.COMPILE_JOBS }}
